### ISSUE TITLE
Push widget sets itself

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#10]
The push button widget sets itself. That is pressing the push wiget, lights it's own LED. Most control surfaces I have worked with (mackie protocol control surfaces like the mackie or x-touch) leave LED control completely to the DAW. So the expected action is that press send /path i 1 and release sends /path i 0 but that the LED does not light or unlight for either of these actions. The LED should only respond to the DAW sending /path i 1 or /path i 0 not to the local push button value.

**Comment by jean-emmanuel** [comment]
Alright I get the point now, this would indeed match the "soft touch" button spirit.

**Comment by jean-emmanuel** [comment]
Fixed (238acbd)
