### ISSUE TITLE
Adapt file extension changes also in launcher

### ISSUE THREAD

**Issue by danielappelt** [jean-emmanuel/open-stage-control#101]
In the launcher session files are still associated with file extension "js":

https://github.com/jean-emmanuel/open-stage-control/blob/2a319b85fb2fc5824a95042e867758480587d25c/app/main/launcher/launcher.js#L60

Suggested change:

`
              dialog.showOpenDialog({filters:[{name:'json',extensions:['json', 'js']}]},function(file){
                  input.val(file).change()
`

**Comment by jean-emmanuel** [comment]
Good catch !

**Comment by jean-emmanuel** [comment]
fixed in v0.20.3 (uploading)
