### ISSUE TITLE
MASTER slider doesen't work...

### ISSUE THREAD

**Issue by AudioMG** [jean-emmanuel/open-stage-control#102]
Hi

At first manny thanks for this great project.
I like this concept and I have installed now 
the version v0.20.3 on my audio workstation.

I use KXStudio based on Ubuntu 14.04 and
Ardour 5.11.4.

The TRACK tap works fine with all the slisers
and all the nops only the MASTER slider dosent 
work. If I enable in the Settings MASTER than
I can see a MASTER slider right from the others. 
And this slider works. But the slider on the 
right site of the window don't work. I hope
you can follow my description.

I use a copy of the ardour.json file from the
demo site: http://openstagecontrol.herokuapp.com/

How can I get this MASTER slider running?

Best regards
Manfred

**Comment by jean-emmanuel** [comment]
Hi, thanks for you feedback :)

It's my mistake, now fixed, you can download ardour.json again !

**Comment by AudioMG** [comment]
Wow, perfect that's it ;-)

By the way. I have 8 MIDI channels in my Ardour Mixer.
But in the open stage intervace I can see always only 6.
And in the window is more space left. 

I don't have find out how to use the whole left space for
the other sliders if I have more than 6.

Best regards
Manfred
