### ISSUE TITLE
Channels higher than 6 dosen't work like expected

### ISSUE THREAD

**Issue by AudioMG** [jean-emmanuel/open-stage-control#103]
Hi

I have installed the version v0.20.3 on my audio workstation.
I use KXStudio based on Ubuntu 14.04 and Ardour 5.11.4.

I think I have faced an issue.

- In the Ardour OSC set-up I use "Bank Size 0"
- If I change this "Bank Size" value I can't see any changes of the behaviour of the OSC
- In the OSC tap TRACK I have add 4 more Channels by copy of the Channel 6 and Past+ID.

**ISSUE:**
- Channel 1 - 06 Works perfect
- Channel 7 - 10 The sliders are OK
- Channel 7 - 10 MUTE is OK
- Channel 7 - 10 SOLO is not working
- Channel 7 - 10 The name of the Channel is not shown
- Channel 7 - 10 The meter don't work

If it is useful I can provide some screen-shoots for you.
It would be great to have a solution for that ;-)

Best regards
Manfred

**Comment by jean-emmanuel** [comment]
Hi,

Sorry for taking that long to respond, you're almost there though :
- n+1 pasting is not enough here unfortunately, you have to manually increment the values found in the `variables` option of the additionnal clones.
- you alsa have to edit this widget :
![screenshot-2017-09-25-22 55 06](https://user-images.githubusercontent.com/5261671/30830752-61187cb6-a245-11e7-8f5c-86f940f3bdf6.png)
It sets Ardour's osc options, and the the value in its `preArgs` option sets the bank's size.

**Comment by AudioMG** [comment]
Hi

Wow that is great.
Now I am really happy. 

Thanks a lot

Greetings
Manfred
