### ISSUE TITLE
Impossible to start openstagecontrol from ssh ?

### ISSUE THREAD

**Issue by brunetton** [jean-emmanuel/open-stage-control#104]
Hi Jean Emmanuel,

First of all, I wanted to thanks you very much for OpenStageControl. I was looking for a way to control some devices via Wifi with a old Android tablet, and this wonderful piece of software came up as the graal :sparkles: !
=> you'll hear from me when my project will be accomplished (open source of course) as OSC is one of the pieces I'm trying to get working together.

So ... I wanted to lunch OSC on the Pi.
I first downloaded the bundle (0.20.3-linux-armv7l), but unfortunately inside ssh,the binary exited silently without any error messages (using `./open-stage-control -n`).
It seems that it only works inside a Xorg environment: switching to `tty1` have the same effect as by ssh.

This is quite blocking since I'm working on a headless server.
Do you have an explanation for that ? 

Thanks !

**Comment by brunetton** [comment]
My bad ! I just didn't read the [getting started](http://osc.ammd.net/getting-started/) page to the end !

Sorry for the stupid question !

**Comment by jean-emmanuel** [comment]
No problem at all ! Thanks for your feedback, I'm looking forward to seeing your project :).

**Comment by brunetton** [comment]
Don't worry, you will ! This weekend I'll playing with your OSS2MIDI. I
like the way it is simple (and probably efficient).
I've of course noticed the other projects for the same purpose, I've to
test them (but the general lack of documentation for complex configuration
files is a major barrier for week-end hobbyists project).
It's clearly not the purpose of a issue, but if you come sometimes to Paris
(I can see you're French, like me), maybe we can have a beer! (I'll pay ;-)
)

**Comment by jean-emmanuel** [comment]
You can also send MIDI with Open Stage Control : http://osc.ammd.net/extras/midi/
I'll keep that in mind :beer:  !

**Comment by brunetton** [comment]
You just made up my day! What a good present for "my day" (it's St Bruno
today).
I really have to *RTFM ^^)*

*THANKS again *

**Comment by jean-emmanuel** [comment]
FYI, it's also possible to run a headless server with node : http://osc.ammd.net/getting-started/#running-without-electron
