### ISSUE TITLE
Building releases from source might fail due to electron beta dependency

### ISSUE THREAD

**Issue by danielappelt** [jean-emmanuel/open-stage-control#105]
It seems that currently, all open-stage-control source releases depending on electron 1.8.0 fail during build.

The latest releases like v0.20.3 depend on electrong 1.8.0. This electron version seems to be no longer available as the next electron beta release 1.8.1 seems to have replaced 1.8.0. Currently, these are the releases available for electron:

```
[xyz@xyz ~]$ npm view electron versions
 
[ '0.1.0',
  '0.1.1',
  '0.1.2',
  '0.2.0',
  '0.2.1',
  '0.3.0',
  '0.4.0',
  '0.4.1',
  '1.3.1',
  '1.3.2',
  '1.3.3',
  '1.3.4',
  '1.3.5',
  '1.3.6',
  '1.3.7',
  '1.3.8',
  '1.3.9',
  '1.3.10',
  '1.3.12',
  '1.3.13',
  '1.3.14',
  '1.3.15',
  '1.4.0',
  '1.4.1',
  '1.4.2',
  '1.4.3',
  '1.4.4',
  '1.4.5',
  '1.4.6',
  '1.4.7',
  '1.4.8',
  '1.4.10',
  '1.4.11',
  '1.4.12',
  '1.4.13',
  '1.4.14',
  '1.4.15',
  '1.4.16',
  '1.5.0',
  '1.5.1',
  '1.6.0',
  '1.6.1',
  '1.6.2',
  '1.6.3',
  '1.6.4',
  '1.6.5',
  '1.6.6',
  '1.6.7',
  '1.6.8',
  '1.6.9',
  '1.6.10',
  '1.6.11',
  '1.6.12',
  '1.6.13',
  '1.6.14',
  '1.7.0',
  '1.7.1',
  '1.7.2',
  '1.7.3',
  '1.7.4',
  '1.7.5',
  '1.7.6',
  '1.7.7',
  '1.7.8',
  '1.8.1' ]
```
In order to have working source releases it would either help to stick to non-beta releases of electron, or to use a '~' dependency.

**Comment by jean-emmanuel** [comment]
Good point, I'm prefixing all dependencies version with a `~`, seems safer.

**Comment by jean-emmanuel** [comment]
Whoops, bad idea actually, I should have given that some more thought... I'm applying this only to electron instead, since electron's updates are very likely to have an anecdotical impact on the the app's behaviour.
