### ISSUE TITLE
all Faders move

### ISSUE THREAD

**Issue by terrar** [jean-emmanuel/open-stage-control#106]
I tested with two open browsers on different machines.
When moving one fader in browser A all faders (not only the one i moved) on browser B go to the same position as this one i moved. Same when opening two tabs in one browser.
Is this a bug or do i something wrong?

**Comment by jean-emmanuel** [comment]
Hi,

Widgets respond to osc messages (from the outside and from other clients) that match their `address` (and `preArgs`) property. It looks like your faders have  the same `address`.

Within a client's context, widgets are synchronized with each other when they share the same `id` or when they are [clone widgets](http://osc.ammd.net/widgets/containers/#clone), regardless of their `address` property, hence only one fader moving in browser A.

**Comment by terrar** [comment]
Thank you!
After I've only created the surface and have not linked anything yet, I do not even notice that down in osc the names are all the same.
Works as expected.
A masterpiece!

**Comment by jean-emmanuel** [comment]
Cool !


Le 11/10/2017 à 17:38, terrar a écrit :
