### ISSUE TITLE
PreArgs does not allow setting type.

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#11]
preArgs is wonderful. It does a pretty good job of setting string or float but it does not allow sending Ints. That is sending a /path if 3 3.57 for example. It seems a number is either ff or ii. Perhaps only setting float of the number is *.* and int for no . would work. So a preArg of 3 is an int and 3.0 is a float. As happens, the DAW I am working with doesn't seem to care and will accept a float where an int is specified. However, the developer I was talking to, seems to consider this a bug.

**Comment by jean-emmanuel** [comment]
I had thought of this too... Distinction between floats and integers can't be done reliably in javascript, hence the precision option that indicates the osc sending function the type of the args, widget-wise. I'm not sure how to fix this yet.

**Comment by jean-emmanuel** [comment]
`preArgs` and buttons values can now be set as objects if the type needs to be specified : 
```js
preArgs:[
  {
    type:"integer",
    value:1
  },
  // etc
]
```
