### ISSUE TITLE
any Ardour specialist in here?

### ISSUE THREAD

**Issue by terrar** [jean-emmanuel/open-stage-control#110]
Since I am not the best in these matters, I must turn to you.
Is there a skilled Ardour user here?

I have tested the ardour.json successfully and am impressed by the optics and the functions.
For my purposes this is unfortunately to be overloaded.

I would like to use the system in order to allow my musicians to adjust the monitor sound.
For this I need only the following things in the interface:

* The bus over which the monitoring is running
* All sends leading to this bus

The display shows only one fader for each channel (the bus fader = master in a different optics than the sends) and one mute button per channel.
A selection option of the respective bus would be a dropdown or similar.

I need about 12 channel foxes plus the bus fader

That would fit perfectly for my purpose, but I am unfortunately not the right to create such a surface from scratch.

Does anyone have pity on me?

**Comment by jean-emmanuel** [comment]
Hi !
I'll try to make it if I find some time, I'll keep you up to date.

**Comment by terrar** [comment]
Thank you very much.
I am already looking forward to the result.

**Comment by ovenwerks** [comment]
Please see: http://manual.ardour.org/using-control-surfaces/controlling-ardour-with-osc/osc-personal-monitoring/ for the way to do this... if you are using touchOSC then you may find: https://github.com/ovenwerks/ardour-touchOSC/tree/master/personal-phn of interest. Though the Control Applet may be usable for this too. I do not know if O. S. C. can run on an android or iPhone (what most musicians likely have). Using the personal monitoring set of controls would require one O.S.C. server per monitor to use with chrome.

**Comment by jean-emmanuel** [comment]
@terrar 
Sorry I didn't get back to you sooner, unfortunately I didn't find the time to help you with this, I hope you've managed to get something working on your side !
