### ISSUE TITLE
midi<>osc bridge. scriptable

### ISSUE THREAD

**Issue by AlexFundorin** [jean-emmanuel/open-stage-control#111]
Hi, I wonder if it's possible to use this app as a bridge between DAW that sends\receives OSC messages and midi controller to be able to control DAW and also have midi feedback on the controller (LEDs and LCD text)?

**Comment by jean-emmanuel** [comment]
Hi !
Unfortunately not. I'm guessing you are looking for a solution that works under Windows, you could try using this https://thewizardofosc.com/, I haven't tried it much it *might* do the job.

**Comment by AlexFundorin** [comment]
Yeah, I'm using Windows. Unfortunately, Wiz uses direct namespace conversion and mapping via gui, whien I need some script based software, where logic could be set by regular expressions.
Anyway, thanks fot you time and suggestion. 👍 

I've played with your app a bit. Funny thing that when I've opened harokuapp page in my desktop browser and on my phone, fader movement in one browser was reflected in the other one. I suppose that it happened because both devices share the same IP in the internet.
Good luck with your project. Looks a bit like Ctrlr for web.

**Comment by jean-emmanuel** [comment]
If you are familiar with the python language, you could write your own bridge using [pyo](http://ajaxsoundstudio.com/pyodoc/api/index.html), it does much more than osc and midi but can do the job.

The behavior you are describing is the result of clients synchronisation when connected to a single open-stage-control server instance, it's a feature ;)

**Comment by AlexFundorin** [comment]
I know what Python is, but not a programmer myself, to be true. I can deal with simple Lua scripts or Arduino IDE. Tried Python several times and ended with nothing.

What if some other person connects to the same stage server? What would happen to the surface on my device when that other guy would manipulate the controls?

**Comment by jean-emmanuel** [comment]
Ok then I can't think of anything else than [OSC2MIDI](https://github.com/ssj71/OSC2MIDI) right now, which you seem to have found already (can't help with the windows compilation though, sorry...) 

Well, if two clients can send the exact same osc messages, you'd want them to show the latest value that's been sent to avoid fader values jumps or misleading toggles states for example. Now if you wanna make sure nobody can mess with your controls, I think protecting the network is enough.

**Comment by AlexFundorin** [comment]
Reaper has kinda similar setting in it's web control feature, giving several users behind one network to control Reaper at the same time : 
https://www.youtube.com/watch?v=TMZZvk4x93o
https://www.youtube.com/watch?v=CkMAj8CpvIU

I've seen OSC2MIDI. Even if there's no windows version, I've checked it and found out that it doesn't support Sysex. It also performs straight osc address <> midi command conversion only.
I've been searching for a proper app for five years, if not more. It seems that such app simply doesn't exist. 😞 

Thanks again for your time, Jean.
