### ISSUE TITLE
Empty Window on RPi 3 with Raspbian Stretch

### ISSUE THREAD

**Issue by hugoderwolf** [jean-emmanuel/open-stage-control#112]
Hi!

I'm trying to get OSC to run on a Raspberry Pi 3. But when I launch it, all I get is an empty window. No error messages or anything apart from that. Also doesn't matter if I run it with or without any cmdline arguments.

I can connect to the server with a browser via network and also with Chromium on the RPi. But I want to run a solution as lightweight as possible in terms of both resources and screen real estate (7" touch screen, BTW I'd like to run it on a plain X server without any desktop environment if that's possible).

Happens both with the binary release 0.21.1-linux-arm7l and when running OSC from source as described on the website.

Any idea what else I could try to hunt down the issue?

**Comment by jean-emmanuel** [comment]
Hi ! 
Can you run it with at least one command-line argument and hit f12 once the window shows ? This should open the devtool panel, there might be some helpfull error messages in the javascript console.
Running the headless server and Chromium should increase the cpu load (the builtin gui is chromium-based)

**Comment by hugoderwolf** [comment]
Wow, thanks for the ultra-quick reply! Pressing F12 does nothing at all though, with or without cmdline arguments.

**Comment by jean-emmanuel** [comment]
You're welcome ! I'll get back to you when I have more ideas to track this. Also I made a mistake in my previous post: 

> Running the headless server and Chromium should**n't** increase the cpu load

**Comment by jean-emmanuel** [comment]
- how exactly / in what context are you running the app ?
- can you try to run it from the source after running `npm install electron@1.7.9` in the repository (this will install the latest stable electron instead of the currently installed beta)

**Comment by hugoderwolf** [comment]
I've been running it from the terminal on a fresh standard raspbian installation with no further modifications (so the standard desktop that comes with it). First the binary release and later from source (latest git master), which both didn't work.

Just tried it with Electron 1.7.9 as you suggested and that works. Thanks a lot! It's really slow though and eating up a whole core. Any chance to speed it up?

**Comment by jean-emmanuel** [comment]
Ok cool ! I'll probably downgrade electron in next release then.

There are many flags that can affect chromium performances, electron doesn't support support them all so you should try running chromium as client and experiment with the options available in chrome://flags. I'd try :
- enable `override software rendering list` in chrome://flags
- set `GPU rasterization` to `force-enabled on all pages` in  chrome://flags
- run chromium with `--disable-gpu-vsync` (see the [list of switches](https://peter.sh/experiments/chromium-command-line-switches/)) (this one is avaible in O-S-C as `--disabke-vsync`)
