### ISSUE TITLE
Switcher / Crossfader not working in v0.21.1

### ISSUE THREAD

**Issue by glennsky** [jean-emmanuel/open-stage-control#113]
Adding two faders, then trying to add a Switcher or Crossfader linked to those two faders no longer works and gives the following error:

[Renderer process error] Uncaught TypeError: Cannot read property 'getValue' of undefined Source: src/browser/js/app/widgets/switchers/_switchers_base.js @ line 1

My linkedWidgets were entered as: 

[ "fader_1", "fader_2" ]

This works fine on an older version I tried (v0.17.5).   

Saving the simple example described above and the trying to load it hangs during Loading Session File...  
Session attached.

[test_cross.json.zip](https://github.com/jean-emmanuel/open-stage-control/files/1459054/test_cross.json.zip)

**Comment by jean-emmanuel** [comment]
Hi, thanks for your feedback. This is now fixed in master branch (see online demo), a release should follow soon !

**Comment by glennsky** [comment]
Merci bien!

**Comment by jean-emmanuel** [comment]
Pas de souci !
