### ISSUE TITLE
range sliders

### ISSUE THREAD

**Issue by glennsky** [jean-emmanuel/open-stage-control#114]
It would be great if there was a range slider widget with two handles for min/max settings, or even three for min/neutral/max.

I found noUiSlider - which looks pretty good and supports a lot of different configurations.  It has a WTFPL license.
[https://refreshless.com/nouislider/](url)
[https://github.com/leongersen/noUiSlider/](url)

Would it be possible to integrate this (or similar) range slider?

**Comment by jean-emmanuel** [comment]
Funny thing is that the very first prototype of O-S-C was using nouislider ! Now the current slider implementation would be a better base for creating a range slider. It might happen someday, let's say it's in the todo list ;)

**Comment by jean-emmanuel** [comment]
The range slider is in git for testing and will be included in next release.

**Comment by glennsky** [comment]
Amazing, it seems that christmas has come a little early this year! ;-)

I had a very quick play with the online demo and it looks goods.  

There is no "input" property to show / edit the values.  Obviously, this will be a little more complicated to do as it requires two input fields.

Would it be possible to make the range draggable?

**Comment by jean-emmanuel** [comment]
The input field will be added soon (it will work like the xy's input).

> Would it be possible to make the range draggable?

I think so !

**Comment by jean-emmanuel** [comment]
Input added.

**Comment by jean-emmanuel** [comment]
The range can now be move by holding `shift` (touch devices users can use two fingers ;) ).

**Comment by jean-emmanuel** [comment]
Included in v0.23, cheers !
