### ISSUE TITLE
Feature request:  \EDIT_NEW ,{"type": "fader", "id": "my_new_fader"...} 

### ISSUE THREAD

**Issue by joenotjoe** [jean-emmanuel/open-stage-control#115]
Feature request: 
Hello,
       Thank for making Open Stage Control . I have found that  \EDIT works well for modifying existing widgets, I use it with Supercollider.  It would be nice if there was a way to put in a new widget, like \EDIT_NEW ,{"type": "fader", "id": "my_new_fader"...} . That way a external  language could generate and load in interface automatically over OSC. 

Thanks again,
-Joe

**Comment by jean-emmanuel** [comment]
Hi, thanks for your feedback !
Since it's possible to edit the `widgets` property of any container widget, you should be able to achieve what you are describing. Note that in this case, `/EDIT_SOFT` can be useful as it will merge the new widget list to the old one, where `/EDIT` would just replace it.

**Comment by joenotjoe** [comment]
hello,
Thanks I think I get it now. Will play with it.

**Comment by cyberic99** [comment]
I have made an example program to clone an existing widget, in python.
@jean-emmanuel, do you think it could be useful to include it in the examples?

**Comment by jean-emmanuel** [comment]
Embedding a full python example in the docs might be a bit overkill, but a link to a self explained repository would be cool ! I'd really like to see community projects listed as examples somewhere here.

**Comment by cyberic99** [comment]
OK. I might setup a gist for that purpose, as it is only an example and not a full project (yet)
Once I have a real demo of o-s-c I'll let you know...
But the potential is huge!!
