### ISSUE TITLE
add support for copy-pasting values in the side panel fields

### ISSUE THREAD

**Issue by amir-arad** [jean-emmanuel/open-stage-control#116]
It's hard to configure widgets without copy-paste support. 

I think the way to implement this is by adding an edit menu with accelerators  like so:
```js
  const template = [{
    label: 'Edit',
    submenu: [
      {role: 'undo', accelerator: "CmdOrCtrl+Z"},
      {role: 'redo', accelerator: "Shift+CmdOrCtrl+Z"},
      {type: 'separator'},
      {role: 'cut', accelerator: "CmdOrCtrl+X"},
      {role: 'copy', accelerator: "CmdOrCtrl+C"},
      {role: 'paste', accelerator: "CmdOrCtrl+V"}
    ]
  }]

const menu = Menu.buildFromTemplate(template)
Menu.setApplicationMenu(menu)
```
would you accept a PR?

**Comment by jean-emmanuel** [comment]
I'd be happy to review a PR ! Copy-pasting seems to work fine here though, does copy-pasting work normally when using Chrome/Chromium as client ?

**Comment by amir-arad** [comment]
will try out. 
I use OSX btw

**Comment by jean-emmanuel** [comment]
Could you try again with a fresh build from git ?

**Comment by amir-arad** [comment]
will do. hopefully today

**Comment by amir-arad** [comment]
sorry for the delay.
works on 0.22.0

thanks a lot!

**Comment by jean-emmanuel** [comment]
cool !
