### ISSUE TITLE
Feedback welcome : glass effect over non-interactive widgets 

### ISSUE THREAD

**Issue by jean-emmanuel** [jean-emmanuel/open-stage-control#119]
Since b3c82251f9391b11c488f4af9bb7c4457d387826, non-interactive widgets have some kind of glass effect that aims to differentiate them from the other widgets. I tried to make it subtle, less skeuomorphic than the average, but not totally flat either. Any thought ?

-> [online demo](http://openstagecontrol.herokuapp.com)

**Comment by cyberic99** [comment]
I find it is discrete, but I find it does the job ;-)

**Comment by jean-emmanuel** [comment]
Thanks for the feedback, it's in v0.22.0, I'm closing this since it's not getting much attention.
