### ISSUE TITLE
demo site in readme no longer works

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#12]
I understand you probably already know this, so this is a "just in case" thing.

**Comment by jean-emmanuel** [comment]
Yeah, sorry about that, it will be fixed tomorrow. 

Le 26.03.2016 22:23, Len a écrit : 

> I understand you probably already know this, so this is a "just in case" thing. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub [1]

  

Links:
------
[1] https://github.com/jean-emmanuel/open-stage-control/issues/12

**Comment by jean-emmanuel** [comment]
I could fix it remotely, it's live again.
