### ISSUE TITLE
Cannot /EDIT/GET on cloned objects

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#120]
Hello

Thank you again for your wonderful work on open-stage-control
I am once again trying to do something strange:

When I do:
```
send_osc osc.udp://localhost:8080 /EDIT/GET 127.0.0.1:5555 multitoggle2
```

I get:
```
OSC received:  { address: '/EDIT/GET',
  args: [ '127.0.0.1:5555', 'multitoggle2' ] } From : 127.0.0.1:36158
A JavaScript error occurred in the main process: Uncaught Exception:
TypeError: Cannot read property 'concat' of undefined
    at Object.sendOsc (/data/od/open-stage-control-git/app/main/callbacks.js:189:38)
    at Socket.socket.on (/data/od/open-stage-control-git/app/main/server.js:54:32)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at /data/od/open-stage-control-git/app/node_modules/socket.io/lib/socket.js:513:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
I don't know exactly what I was expecting, but I tried anyway...

In fact, my goal is to have some premade widgets, such as the mixer strips in ardour example.
And to clone them programmatically (to add or remove mixer strips), similarly to issue #115)

**Comment by jean-emmanuel** [comment]
Widgets with no `address` or `target` option did not respond properly to `/EDIT/GET` and `/GET`, this should be fixed now !

**Comment by cyberic99** [comment]
Yes, it is fixed, thanks!
I have the impression that each time you fix a bug, you actually *remove* code, that's great!

**Comment by jean-emmanuel** [comment]
;-)
