### ISSUE TITLE
Genius work we need to get in touch! Notice small encoder and crossfader issues on iPad.

### ISSUE THREAD

**Issue by Soundisplay** [jean-emmanuel/open-stage-control#121]
I really love the interface and it is exactly what I am looking for since a long time.
We need to get in touch!
I notice encoder doesn't respond to touch at all when accessing from a browser on the iPad (chrome).
Also crossfader, only buttons are showing up on the iPad no slider...

Thanks again for the great work,
Arny

**Comment by jean-emmanuel** [comment]
Thanks a lot for the kind word, I'm glad you found what you where looking for :). I often hang around on irc/freenode (#ammd and sometimes #lad) if you wan't to chat a bit.

There are still some iOS specific issues here and there, I have reproduced the issue and I'll keep you up to date.

**Comment by jean-emmanuel** [comment]
Hi, could you try the online demo and tell me if it works now ?

**Comment by jean-emmanuel** [comment]
Fixed in v0.24.0 ...?
