### ISSUE TITLE
widgetId and text widget

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#122]
Hi

I tried playing with property inheritance.
I would like to be able to display an ip:address in a text widget, and later use it as a target for another widget.

So first I created a text widget text_1, and another text_2, with widgettId=text_1
I changed the value of text_1, and expected text_2 to change too, but it didn't happen...

For the next step, is it correct if I put `"/"@{text_1.value}` in the address field, and then I set text_1 to `ip:port`?
or rather put `@{text_1.value}` in the address field, and then I set text_1 to `/ip:port` ? (with the slash) 

My simple example is attached.
[gh_issue_2018-01-01_20-42.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1596373/gh_issue_2018-01-01_20-42.json.txt)

Thank you

**Comment by jean-emmanuel** [comment]
> I changed the value of text_1, and expected text_2 to change too, but it didn't happen...

It is a bug with all plot widgets that will be fixed soon.

> For the next step, is it correct if I put "/"@{text_1.value} in the address field [...]

This would only retrieve the `value` property that defines the widget's initial value, not it actual value. What you're describing is not possible yet, but it might be soon: something like `@{id._value}`...

**Comment by cyberic99** [comment]
ok, thx
the _value property could be useful to 'store' some states directly into o-s-c.
I assumed that the value was a normal property, but you are right, this is the initial value 

Could I di the same thing, for unstance with the label property?

Or could this be done by using variables for instance?
Do we have the ability to set variables using OSC?

**Comment by jean-emmanuel** [comment]
> the _value property could be useful to 'store' some states directly into o-s-c.

Note that the session file won't store the changing value, that's what states saves are for, `_value` is just a convenience for including this particular case to property property inheritance.

> Could I do the same thing, for unstance with the label property?

Yes, as property inheritance is supposed to apply to all properties :). Note that inherited property changes trigger a whole widget recreation everytime -> use with caution.

> Or could this be done by using variables ?
Do we have the ability to set variables using OSC?

Yes, `variables` are here to store data that don't fit in any other property but that are to be retrieved by other widgets. Remote editing is the way to go. Assuming `variables` is an object/dictionnary (`{}`), using `/EDIT/MERGE` you can change its values without overriding the widget's data:

`/EDIT/MERGE widgetId "{variables:{key: value, key2: value2}}"

**Comment by jean-emmanuel** [comment]
`_value` support is in git for testing ;)

**Comment by cyberic99** [comment]
Great, thanks for your developments and your tips!
Yes, variables seem more appropriate for what I want to do, and I can display their values anyway in a text widget if I want to.

**Comment by jean-emmanuel** [comment]
You're welcome ! 

> I changed the value of text_1, and expected text_2 to change too, but it didn't happen...

- [x] fixed :)

**Comment by cyberic99** [comment]
Thx! I'll test it ASAP

**Comment by cyberic99** [comment]
I tested it and I get a strange behavior:
- load the attached session
- oscsend osc.udp://localhost:8080 /ip s 127.0.0.1:5555
- move the fader... in the o-s-c console I see it is sending its value to 127.0.0.1:5555
- oscsend osc.udp://localhost:8080 /ip s 127.0.0.1:5556
- move the fader... in the o-s-c console I see it is sending its value to 127.0.0.1:5555 *AND* 127.0.0.1:5556... seems something has been cached somewhere...
[gh_issue_2018-01-02_22-11.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1598904/gh_issue_2018-01-02_22-11.json.txt)

**Comment by cyberic99** [comment]
Another strange thing:
with this attached file, I do:
```oscsend osc.udp://localhost:8080 /EDIT ss root "{'variables':{'ip': '127.0.0.1:5001'}}"
```
I was expecting the widget value to change to the new ip:port, but only the label changes

After that, I did:
```oscsend osc.udp://localhost:8080 /EDIT ss root "{'variables':{'ip': '127.0.0.1:5002'}}"
```
and I clicked on the ip widget.
I got:
```
OSC received:  { address: '/EDIT',
  args: [ 'root', '{\'variables\':{\'ip\': \'127.0.0.1:5002\'}}' ] } From : 127.0.0.1:49250
[Renderer process error]
Uncaught RangeError: Maximum call stack size exceeded
Source: src/browser/js/app/widgets/common/_widgets_base.js @ line 219
```
I am sorry if it is something not supported or that I didn understand correctly...
I do not know if putting a property in the 'value' field is supposed to work...

Feel free to discard this issue if you find I am doing something silly... ;-)
[2018-01-02_22-38i-2.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1598938/2018-01-02_22-38i-2.json.txt)

**Comment by jean-emmanuel** [comment]
1. I see what could go wrong but everything works as expected here, no duplicate message: can you check that you have pulled the latest commit and run `npm install` to make sure all dependencies are up to date ?

**Comment by cyberic99** [comment]
I just reproduced the first issue with commit aceb8e1, after doing npm install again. should I do a clean checkout?

**Comment by jean-emmanuel** [comment]
1. Still no luck here... are you experiencing this with the embed client gui or from a remote client ?

2. Ok, there was a bug here, preventing property inheritance to get a parent's property when targetted with its id. The infinite loop was due to a logic error in the editor allowing property inheritance to search through a replaced widget's data. 

> I was expecting the widget value to change to the new ip:port, but only the label changes

In general, when recreating a widget (ie when changing any of its properties), the editor tries to restore its value (as in state). Editing the `value` property should override this, but it doesn't yet...

**Comment by cyberic99** [comment]
1. I launch o-s-c directly from the sources with npm.
Maybe I can try to do an /EDIT/GET to see what value I have in target?
is it possible that 2 widgets send the vakues to 2 different targets?

**Comment by cyberic99** [comment]
1. I use npm directly with the sources.
Is it possible that the different values are aent by 2 different widgets?
Maybe I could do an /EDIT/GET to see what value I have in target?

**Comment by jean-emmanuel** [comment]
1. can you do `rm -rf node_modules app/node_modules && npm install` (fresh dependencies install) ?

**Comment by cyberic99** [comment]
@jean-emmanuel I tried to reproduce with a completely fresh checkout and a fresh nodejs install, on another machine... without success...
I am sorry about that.
I don't know what happened, I don't know if I can still reproduce it on the original machine, but you can discard the first part.
If I encounter the issue again, I'll reopen another issue.

**Comment by cyberic99** [comment]
second part of the issue fixed now (maybe related to https://github.com/jean-emmanuel/open-stage-control/issues/123)

**Comment by jean-emmanuel** [comment]
> In general, when recreating a widget (ie when changing any of its properties), the editor tries to restore its value (as in state). Editing the value property should override this, but it doesn't yet...

a6401b6 should fix that
