### ISSUE TITLE
properties that depend on variables are not refreshed

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#123]
I think I can reproduce a bug correctly, this time.

To repro:
- open o-s-c in debug mode
- open the attached session

There is a switch that has a value of `@{parent.variables}` so when we set a variable on its parent widget (`services`), it should appear.

The text widget's label value is `@{services.variables.svce1}` so if we set this variable, it should be displayed on the label

The fader has a target value of `@{services.variables.svce1}` so it should send its value to the service once the service ip:port is set.

So let's set the ip:port of svce1:
`oscsend osc.udp://localhost:8080 /EDIT ss services '{"variables":{"svce1":"127.0.0.1:5000"}}'`

The switch updates itself, and the editor will show that the variables of `services` have been set correctly.

However, the fader still sends nothing, and the label is still 'undefined'.

but... 
if we go in the editor, we click the text widget, then 'label' field, then enter...
the value appears in the label.

Same thing for the fader's target field.

I don't know if what I do is supposed to be supported...

It could be very powerful if it would work, because it would allow each OSC 'service' to register itself, only by sending its ip:port at startup to o-s-c... that would be detected through zeroconf...

It should also allow multiple targets per service, for example:
```
oscsend osc.udp://localhost:8080 /EDIT ss services '{"variables":{"svce1":"[\"127.0.0.1:5003\",\"127.0.0.1:5004\"]"}}'
```
[try3.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1601987/try3.json.txt)

**Comment by jean-emmanuel** [comment]
This should be fixed now, was half regression half bug ;)
e874cc7f969d79a30f3a81a915764bcdd209f779
d753646118b173e7ba860e857394e9bd3ef24a87

**Comment by cyberic99** [comment]
Fixed!
Thanks
