### ISSUE TITLE
Midi Help

### ISSUE THREAD

**Issue by meadmachine** [jean-emmanuel/open-stage-control#125]
Hi mate,

Love this loads - the only thing is I don't understand how to get midi to work.

I'm more of and end user and not familiar with Python. I've downloaded it and tried following tutorials but with no results.

Please could you consider writing a step-by-step guide on getting this to work? I'm even struggling getting rtmidi working...

Many thanks,
Alex

**Comment by cyberic99** [comment]
Hello
What are you trying to achieve?
Are you trying to use a MIDI controller as input for o-s-c?
When you launch o-s-c with `-m list`, do you see your MIDI device in the list?

**Comment by meadmachine** [comment]
![osc 2](https://user-images.githubusercontent.com/35278950/34768629-4bb6220e-f5f3-11e7-9739-2084afaa326d.PNG)
Hi - thanks for your reply!

I would like o-s-c to be able to send midi to another program on my computer. I would then use a tablet with the o-s-c web server to remotely control aspects of the other program.

When I type -m list into the midi field on the opening screen and launch the program, nothing happens. I assume it's because I still don't know where to start with Python and rtmidi?

Please see attached for examples.

Thanks for bearing with me!
![osc 1](https://user-images.githubusercontent.com/35278950/34768642-58be6330-f5f3-11e7-9360-6a4a3b375f38.PNG)
![osc 2](https://user-images.githubusercontent.com/35278950/34768643-5915ded0-f5f3-11e7-8f51-7acc504b4b4a.PNG)

**Comment by cyberic99** [comment]
What Operating system are you using?
I think that you should start open stage control from a terminal or a console, to be able to see the output

**Comment by jean-emmanuel** [comment]
Thanks for helping @cyberic99 !

In order to enable midi support, you have to : 
1. install [python](https://www.python.org/downloads/)
2. install `rtmidi` from a terminal : `pip install rtmidi` (`pip` is python's package manager)

You can check if it's properly installed by running `open-stage-control --midi list` from a terminal.

**Comment by meadmachine** [comment]
Thanks for your help guys.

Unfortunately I think this is beyond my skillset. Rtmidi started installing then came up with some errors. I think I'll wait until this becomes an all-in-one package as I'll need to quickly install the app on different computers in venues I work in and can't spend much time getting it working. I think you've developed something really great here though!
