### ISSUE TITLE
Empty window as in #112, but on ubuntu 16.04

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#126]
A friend of mine had this issue as well on ubuntu 16.04 (see screenshot with web debugger)

He couldn't build from the git because of various issues related to nodejs (but not to o-s-c) so I used docker to build a package for him.
He told me he had an empty screen.
Using docker I was able to replicate the same setup as his.

I don't know if you are familiar with docker, but I share my Dockerfile here.
Maybe you could include it in the official repo? your choice.

Here is what you can try to do in order to (try to) reproduce.
If it is too much work or not practical to you, you can give me instructions to help you to debug.

* build o-s-c on debian:
  put the 2 files in a directory
  ```
  make  # this should download ubuntu, build o-s-c
  make shell
  ```
That should give you a shell inside the docker environment.
Now, from here, install o-s-c and the deps:
```
sudo dpkg -i dist/open-stage-control-linux-x64/open-stage-control_0.22.0_amd64.deb   # it will install but fail because of some dpes
sudo apt-get -f install
sudo apt-get install libglib2.0-bin libgtk2.0-bin libasound2 libx11-xcb1
```
then launch o-s-c:
```
open-stage-control 
```
The attached screenshot is what I get

Tested and reproduced with:
git aced94ad
git 77b3b6be

Thx for your help!
Eric

[Makefile.txt](https://github.com/jean-emmanuel/open-stage-control/files/1620781/Makefile.txt)
[Dockerfile.txt](https://github.com/jean-emmanuel/open-stage-control/files/1620782/Dockerfile.txt)
![o-s-c-debugger](https://user-images.githubusercontent.com/193917/34801868-a4d4dc80-f662-11e7-80a5-4702b2092d1f.png)

**Comment by jean-emmanuel** [comment]
Hi, can you access the `dist` folder after running `make` and run open-stage-control binary directly ?

**Comment by cyberic99** [comment]
yes.
If I do this after all this steps (after the packaging), I still get the same result.

**Comment by cyberic99** [comment]
npm start shows an empty screen as well

**Comment by cyberic99** [comment]
` ` `
$ node --version
` ` `
v9.4.0

**Comment by jean-emmanuel** [comment]
This is not related to Docker, but to a javascript minification problem that occurs when packaging the app for production, b96bf4f  fixes it.
I'd prefer not to include a dockerfile, .it seems too opiniated regarding how to install a software (for instance, I'd never execute something containing `sudo apt-get dist-upgrade` ;) )

Now this makes me think the documentation should advise users to build from the latest release tag unless they want to experiment the latest features and bugs !

**Comment by cyberic99** [comment]
Thx!
At least the Dockerfile allowed to reproduce exactly the same steps from a clean env...
I agree that an apt-get dist upgrade is not always a thing to do, but in the case of o-s-c, wen I build it, I prefer it to have the latest versions of the libraries available.

I wil test it right now and ask my friend to do that as well.

**Comment by cyberic99** [comment]
Fixed!
Thank you!
