### ISSUE TITLE
Cannot read property 'concat' of undefined when sending OSC

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#128]
Hello
When I load the attached session with git version (4b8e6ed),
and when I send:
```send_osc osc.udp://localhost:8080 /EDIT/MERGE services '{"variables": {"midiplayer": "192.168.0.47:5001"}}'```

I get an exception:
```
OSC received:  { address: '/EDIT/MERGE',
  args: 
   [ 'services',
     '{"variables": {"midiplayer": "192.168.0.47:5001"}}' ] } From : 127.0.0.1:37182
[Renderer process error]
Uncaught TypeError: Cannot read property 'concat' of undefined
Source: src/browser/js/app/widgets/common/_widgets_base.js @ line 267
```

It is true that some values are not yet defined at this point...

But even after defining then (with OSC), the 'cog' panel objects are no more editable...
I can't right click on any object.

Thank you
Eric

[2tabs.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1628853/2tabs.json.txt)

**Comment by jean-emmanuel** [comment]
Fixed.
