### ISSUE TITLE
parent.getProp is not a function

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#129]
Maybe related to #128...
- open the attached file
- delete the 'cog' panel
```
TypeError: parent.getProp is not a function
Source: src/browser/js/app/widgets/common/_widgets_base.js @ line 199
```

Or you can try to add a widget to this panel, you will get the same error as in #128.

[2tabs.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1628860/2tabs.json.txt)

**Comment by jean-emmanuel** [comment]
Fixed :)

**Comment by cyberic99** [comment]
thx @jean-emmanuel!
