### ISSUE TITLE
fader continues to send OSC info after reaching the end of stroke.

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#13]
in a fader (in this case min=-1000, max=10) moving the fader past the end of the wiget continues to send OSC data. For example moving the mouse up the value reaches +10 (FS) i get 9.81, 9.87, 10, 10, 10, etc. till I stop moving the mouse. The same going down, I can get a screen of -1000 events. A new osc event should not be sent if it is identical to the last one sent. It may even be able to be discarded farther upstream. This is not a huge deal as the DAW will not do anything bad.

**Comment by jean-emmanuel** [comment]
I was planning to fix it already, coming soon! 

Le 27.03.2016 00:41, Len a écrit : 

> in a fader (in this case min=-1000, max=10) moving the fader past the end of the wiget continues to send OSC data. For example moving the mouse up the value reaches +10 (FS) i get 9.81, 9.87, 10, 10, 10, etc. till I stop moving the mouse. The same going down, I can get a screen of -1000 events. A new osc event should not be sent if it is identical to the last one sent. It may even be able to be discarded farther upstream. This is not a huge deal as the DAW will not do anything bad. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub [1]

  

Links:
------
[1] https://github.com/jean-emmanuel/open-stage-control/issues/13

**Comment by jean-emmanuel** [comment]
Fixed in 0b4548a2b91b36c1ffd7f514658ea6f0aff4e557 (fader/knob/xy/rgb)
