### ISSUE TITLE
How to select a switcher by value, if the value is an array...

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#136]
Hello
I have a switch with these values:
```
{
  "A": [ 0, 0 ],
  "B": [ 1, 1 ],
}
```
The switch has the same ID as a range fader, so when I click on a switch item, it moves the faders.

Now I'd like to select a switch item, using OSC.
What value do I have to send in order to select "A" for instance?
I tried ff 0.0 0.0 or s [0,0]...

Thank you

**Comment by jean-emmanuel** [comment]
Switch widgets don't receive array properly, to be fixed very soon !

**Comment by jean-emmanuel** [comment]
here you go ;)

**Comment by cyberic99** [comment]
Thanks!
Tested and working!
And it added another bonus (as far as I remember):
When I move the fader and the fader matches the switch values, the switch autoselects itself!

**Comment by jean-emmanuel** [comment]
yay ! :)


Le 26/01/2018 à 00:26, cyberic99 a écrit :
