### ISSUE TITLE
send double values instead of float, for a range fader

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#137]
I have a range fader that have these values:
{
  "min": 0,
  "max": 46.033536
}
When I select the whole fader, I see in o-s-c window:
OSC sent:  { address: '/FADER',
  args: [ { type: 'f', value: 0 }, { type: 'f', value: 46.033536 } ] } To : 192.168.0.47:5001

But my application receives:
/FADER 0.0 46.03353500366211

My app is in python and uses python-osc
I am not sure if it is because of the data type f rather than d ...

I tried to play with the precision...

when I send 46 as a float, my app receives: 46.0
46.03  ->   46.029998779296875  (precision 2)
46.034 -> 46.034000396728516
46.0335 -> 46.03350067138672
and so on.

**Comment by jean-emmanuel** [comment]
Yep, this is a data type problem, sending doubles fixes it. I need to do some research to decide weither this should be the default data type for floats or an alternative mode (ie `--use-double-precision`).

**Comment by cyberic99** [comment]
maybe it can be a per-widget field? or a special precision value like '10f' ?

**Comment by jean-emmanuel** [comment]
Good idea, it's in git now, appending an osc typetag to a widget's `precision` option now works:
- `2` or `2f` -> 2 decimals rounded float
- `2d` -> 2 decimals rounded double (higher precision)
- `2s` -> 2 decimals rounded stringified number !

**Comment by jean-emmanuel** [comment]
Included in v0.23, cheers !
