### ISSUE TITLE
Open two different tabs in different devices

### ISSUE THREAD

**Issue by hiramegl** [jean-emmanuel/open-stage-control#138]
Hi,

I have created a GUI with many tabs (root tabs) and I would like to open two different tabs in two different devices.
For example my GUI has tab "Session" and tab "Clip". In my ipad i want to open the "Session" tab, while in my mobile i want to have the "Clip" tab opened. The problem is that when I switch a tab in any of the devices, the other device is automatically jumping to the tab I selected in the first device.

Is it possible to avoid this behaviour?
Is some configuration that I need to do?

Thanks for your great job and effort, open stage control is a great platform.

Regards,

Hiram

**Comment by jean-emmanuel** [comment]
Hi, thanks a lot for your feedback :).

Currently this is not possible without duplicating your session file and changing one of the root's `target` option (clients' wiudgets are synchronized only if all their osc attributes match, including `target` ). 

However, it would make sense to bypass this behaviour in some cases such as yours, I shall make that possible before next release, which is coming soon !

**Comment by jean-emmanuel** [comment]
Here we go : ad40de2ffbe52d56e3d73aeb96f2dfda68977273

**Comment by hiramegl** [comment]
OMG!

Thanks a lot Jean-Emmanuel for the quick response and fix!
So happy I discovered Open-Stage-Control!

Best regards!

Hiram

**Comment by jean-emmanuel** [comment]
Included in v0.23, cheers !

**Comment by jean-emmanuel** [comment]
`noSync` option will be removed in next release, as a new generic option has been added for all widgets : `bypass` allows preventing any osc message from being sent by a widget (thus preventing clients synchronization). Widgets with `noSync` option enabled will fallback to using the now `bypass` option automatically.

**Comment by cyberic99** [comment]
@jean-emmanuel: what is the difference between bypass and having a target set to null ?

**Comment by jean-emmanuel** [comment]
having a target set to `[null]` doesn't prevent client synchronization (if target is `[null]` on both sides)

**Comment by cyberic99** [comment]
thx, I hadn't thought about it.
So the sync mechanism is completely independent from OSC messages?

**Comment by jean-emmanuel** [comment]
> @jean-emmanuel: what is the difference between bypass and having a target set to null ?

Check out https://github.com/jean-emmanuel/open-stage-control/issues/279, this has changed a bit.

> So the sync mechanism is completely independent from OSC messages?

I missed this question sorry. The sync mechanism is actually very close from OSC : osc messages are broadcasted to clients (except the sending one) that interpret them as any osc messages. The only difference is that the widget's target is passed and compared to define matching widgets.
