### ISSUE TITLE
OSM and Sonic Pi 

### ISSUE THREAD

**Issue by nlebellier** [jean-emmanuel/open-stage-control#139]
Hello,

I try to use your program with sonic pi. I just want to send this osc message 

**/play, :c4, 8**

:c4 is the note sonic pi will play and 8 is the delay value.

can't find how to write this in the widget part.
i put a button toggle  and put address /play
it works :)

but how to indicate the parameters  ?
preargs ? 
[ 
":c4",
8
]

Sinon à quel endroit peut-on poser nos questions ?

**Comment by cyberic99** [comment]
You can do as you said, or you can also put a fader for instance, with address /play and preargs ":c4".
Moving the fader will send /play :c4 <fader_value> 
You can see what is sent by o-s-c using the --debug flag

**Comment by jean-emmanuel** [comment]
Hi @nlebellier, you're missing the widget's `value` in how osc messages are constructed :
```
/widget_address <preArgs> <value>
```

In your case, setting `preArgs` to `[":c4"}` and `on` would make the toggle send the appropriate message when activating the toggle (you'd have to set the `off` option to choose what would be sent when deactivating the toggle).

> Sinon à quel endroit peut-on poser nos questions ?

Ici c'est bien :)

**Comment by nlebellier** [comment]
Merci pour vos réponses.

> You can see what is sent by o-s-c using the --debug flag

euh how can i access a console to see this ? the chrome console ? nothing is written.
127.0.0.1:8080

> /widget_address <preArgs> <value>

where do i put the <value>
je ne vois pas où mettre la valeur ?
screenshot : https://flic.kr/p/22B9YF2

Sinon pas de screencasts dispo ? même un tout petit :). Ce serait dommage de ne démocratiser votre bel outil. 

Merci de votre aide.

**Comment by jean-emmanuel** [comment]
La propriété `value` sert à définir la valeur initial du bouton, ce sont les propriétés `on` et `off` qui permettent de choisir la valeur envoyée lorsqu'on allume ou éteint le bouton (valeur qui précédée des valeurs contenue dans l'option `preArgs`)
Quelques liens pour mieux comprendre les différentes options : http://osc.ammd.net/widgets/widgets/ (options générique de la plupart des widgets) & http://osc.ammd.net/widgets/buttons/#toggle (options spécifiques aux boutons)

Pour la console, il s'agit soit:
- d'un terminal si tu as lancé le logiciel de puis un termil
- de la partie en bas de la fenêtre de lancement de l'application (dans laquelle tu peux activer l'option `debug`)

Pour les screencasts j'ai vraiment pas le temps ni l'envie, écrire la documentation en demande déjà tellement !

Sinon n'hésite pas à récupérer la dernière version en date, si tu rencontre un bug ce sera plus facile de t'aider.

**Comment by nlebellier** [comment]
[image: Images intégrées 1]

pas de console... dans la version 0.22 malgré le debug true

Sinon avec la version 0.23 sous windows problème de chemin trop long à
l'install. Node_modules et windows 10 une histoire d'amour pour les chemins
trop longs...
https://flic.kr/p/FQEenJ

La doc est déjà très bien même in english.



---
Nicolas Le Bellier








Le 1 février 2018 à 14:35, jean-emmanuel <notifications@github.com> a écrit
:

**Comment by nlebellier** [comment]
pour la console manquante :
https://flic.kr/p/22TRoVC

---
Nicolas Le Bellier








Le 1 février 2018 à 15:03, Nicolas Le Bellier <nlebellier@gmail.com> a
écrit :

**Comment by jean-emmanuel** [comment]
> Sinon avec la version 0.23 sous windows problème de chemin trop long 

C'est corrigé dans la 0.23.1 publiée à l'instant.

Pour la console manquante il semble que soit un problème uniquement sous Windows, je vais essayer de trouver une solution, merci pour tes retours.

**Comment by jean-emmanuel** [comment]
Pour la console, pourrais-tu tester cela depuis un terminal (genre cmd.exe) et me dire si la console est toujours muette ? 
```
cd C:\chemin_vers_osc
set ELECTRON_NO_ATTACH_CONSOLE=true
open-stage-control.exe
```

**Comment by nlebellier** [comment]
essayé ce matin  avec 0.23.1 > pas mieux concernant la console. Rien dans
la zone de console. Il devrait y avoir un prompt ?

Plus de souci de chemins trop longs. :-)

---
Nicolas Le Bellier








2018-02-01 23:03 GMT+01:00 jean-emmanuel <notifications@github.com>:

**Comment by jean-emmanuel** [comment]
Oui, c'est un problème connu apparement, en revanche la solution n'est pas évidente, ça devra attendre que j'ai un windows sous la main.

Les informations que je t'ai données t'ont-elles permis d'envoyer les messages osc que tu voulais ?

**Comment by nlebellier** [comment]
ok pour la console pas de souci j'ai de quoi m'occuper avant avec la doc.
Oui j'ai réussi à envoyer le message que je voulais. je te remercie.
Je découvre osc avec sonic pi et open stage control donc je tatonne :-)
J'ai beaucoup de questions et doit lire plus de doc pour avoir les bases
sur osc.

par exemple :
quelle est l'utilité d'une valeur initiale pour un bouton toggle ?
A quoi servent les preArgs et Target ? aurais-tu un exemple d'utilisation
concret ?

Pour l'instant j'essaie de mettre en place la chose suivante

un bouton de type toggle pour lancer la lecture d'un échantillon dans
sonicpi. Une fois l'échantillon joué, je souhaite éteindre la led de ce
toggle_1 dans open stage control. quel message osc envoyé vers
openstagecontrol ?
Si tu pouvais m'éclairer mais je ne veux pas abuser de ton temps.


---
Nicolas Le Bellier








Le 2 février 2018 à 21:49, jean-emmanuel <notifications@github.com> a écrit
:

**Comment by jean-emmanuel** [comment]
> quelle est l'utilité d'une valeur initiale pour un bouton toggle ?

Cela permet éventuellement de faire en sorte que le bouton soit allumé au démarrage.

> A quoi servent les preArgs et Target ?

- `preArgs` : permet de construire des messages osc un peu plus complexe. Par exemple pour controller  un mixeur multipiste audio on pourrait avoir besoin d'envoyer `/piste/volume <numero_piste> <valeur_volume>`, alors `<numero_piste>` ira dans `preArgs` et `<valeur_volume>` sera la valeur du widget (par exemple un knob/fader). On peut voir ça comme un prolongement de l'adresse osc (`address`, parfois appelé `path`). La norme est assez ouverte et la nomenclature des messages osc varie selon les applications, `preArgs` permet de construire des messages pour la plupart d'entre elles.

- `target`:  c'est le/les destinataires du messsage osc, on peut le définir de façon globale avec l'option `send` au lancement de l'application, cette option permet de définir des destinataires spécifiques pour chaque widgets (pour s'adresser à plusieurs applications à la fois). 

>  je souhaite éteindre la led de ce toggle_1 dans open stage control

Le principe est simple : il suffit d'envoyer le message qu'envoie le toggle quand il s'éteint. C'est valable pour tous les widgets: ils répondent aux messages qu'ils envoient, c-a-d qui ont la même adresse et les mêmes `preArgs`.

**Comment by nlebellier** [comment]
merci pour toutes ces précisions.

Peut-on mettre une addresse différente sur un bouton toggle ? on :
/play/start et off: /play/stop.

---
Nicolas Le Bellier








Le 3 février 2018 à 00:52, jean-emmanuel <notifications@github.com> a écrit
:

**Comment by jean-emmanuel** [comment]
Pas de souci. Non, ce n'est pas possible, il faut utiliser 2 boutons.
