### ISSUE TITLE
Fader meter doesn't show on some chrome browsers.

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#14]
Using chromium (Linux 64bit) I can see the fader meter (very narrow) ok. However, using Chrome on an android the fader meter does not show up. I tried changing:
width:1rem; to width:8rem; in _fader.scss but that made no difference. I am using a width for the fader itself that is less than "auto" would give, so less than 100%.

In my case it may make more sense to use a separate meter so the colour can contrast as well. But I thought you would like to know that the meter can not always be seen.

BTW, I am very happy with the new release, I can at least "npm start *" on the RPi (arm) now though I can still not install. So far it is very usable and has escaped any of the normal android remote control pitfalls. (like faders that jump)

**Comment by jean-emmanuel** [comment]
Note: scss files are not compiled on the fly, the procedure for doing so will be documented soon ;) 

Android-chrome's way of handling font sizes is messing with the pixel scaling system i use (based on css font-size). There seems to be a simple workaround I tried in 4460227. I can't check it since I don't have any tablet / smartphone, please run the demo to try it out.

This bug was probably causing some other sizes miscalculations in the UI, thus causing some narrow elements such as fader pips and meters to be not rendered properly. Your pixel perfect template might need some tweaking because of this, but in the end it's for the best.

> BTW [...]

I'm glad to read that, thank you for your feedback !

**Comment by ovenwerks** [comment]
On Sun, 3 Apr 2016, jean-emmanuel wrote:

> Note: scss files are not compiled on the fly, the procedure for doing so will be
> documented soon ;)

Ah.

> Android-chrome's way of handling font sizes is messing with the pixel scaling
> system i use (based on css font-size). There seems to be a simple workaround I
> tried in 4460227. I can't check it since I don't have any tablet / smartphone,
> please run the demo to try it out.

Very hard for me to see with the demo :) so I built it here so I can use 
oscsend to put a value in. My first test showed no meter still. I 
remembered that my faders in my file are narrower than stock, so I tried a 
new fader with width, etc. left on auto. meters work on linux and android 
(Great!). Then I tried align left (which I use) and even with auto width, 
there is no meter on the android. This means the bug may not just be size 
but align related.

> This bug was probably causing some other sizes miscalculations in the UI, thus
> causing some narrow elements such as fader pips and meters to be not rendered
> properly. Your pixel perfect template might need some tweaking because of this,
> but in the end it's for the best.

Everything is still fine size/position wise. Because I use panels for each 
strip, it is quite easy to add separate meters with the plus that I can 
have a different colour meter from the fader. I also have wider meters. I 
think I will use a "push" as an OL indicator/reset.

I am willing to test more meter_within_fader fixes on the android, if I 
use it or not.

I will be adding more OSC code to Ardour (banking for one) as well as my 
own HW project that is using open stage control displayed by an android 
for displaying things like channels names, meters, button/fader/encoder 
status, etc. So I am quite happy to be able to point to open stage control 
as a way of doing that. It should be easy to set up performer 
individualized monitor control as well.

more fader wish list :) Tablets do not generally have a keyboard and so 
the ability to use ctl mouse scroll for fine control is not there. I have 
seen various ways of dealing with this...

1) touching a control opens a 
screen wide control instead (probably not doable)...
https://play.google.com/store/apps/details?id=com.behringer.android.control.app.xair
screen shot of how horizontal sliders are expanded:
https://lh6.ggpht.com/cqcC3xRDDtGCgel7lQugSOEBneTLxPHDuagOawv8Lc4xEF-Cdmj1N3rOMMoITal1Nr4K=h900
It has it's usage problems too. I am not saying do this, just showing what 
I mean.
2) finger movement is 
not directly coupled to fader/encoder/knob movement. That is the amount of 
finger movement is greater than the amount of slider/knob movement. 
Perhaps a setting somethingratio where 1 is 1:1, 2 is 2:1 etc. default to 
1. The X-air desktop control app (for linux) uses 2) for pan as an 
example.
downloads.music-group.com/software/behringer/XAIR/X-AIR-Edit_LINUX_V1.3.tar.gz

(both of these use OSC so far as I know, not very nice OSC though)



--
Len Ovens
www.ovenwerks.net

**Comment by jean-emmanuel** [comment]
> Very hard for me to see with the demo [...]

I just tested it on an android, nothing has changed indeed, the problem only occurs with aligned fader, it will be fixed soon.

Btw, there is currently no way to get any osc feedback from Ardour...

> more fader wish lisl [...]

I'm thinking two-fingers dragging for fine value scrolling, would that make sense UX-wise ?

**Comment by ovenwerks** [comment]
On Sun, 3 Apr 2016, jean-emmanuel wrote:

>       Very hard for me to see with the demo [...]
> 
> I just tested it on an android, nothing has changed indeed, the problem only
> occurs with aligned fader, it will be fixed soon.
> 
> Btw, there is currently no way to get any osc feedback from Ardour...

Not true. Less than easy to use with open stage control as it is though. I 
am thinking of either having ardour or some middle ware start the feedback 
and use that to create the ardour.js file for the open-stage-control 
server to use. Both ardroid (hard to find) and ardouvy use the OSC 
feedback.

>       more fader wish lisl [...]
> 
> I'm thinking two-fingers dragging for fine value scrolling, would that make sense
> UX-wise ?

I don't know how it would work, but seems easier than other things. I am 
assuming one finger first to select the wiget and the second one makes it 
fine (landing where ever). I am not great at designing UIs... if it feels 
ok to you it will probably work fine.

--
Len Ovens
www.ovenwerks.net

**Comment by jean-emmanuel** [comment]
Ahem, maybe I spoke too fast, I meant I didn't manage to get any osc feedback in a local setup, maybe i'll get more success over the network since I've read Ardour sends feedback messages using the sender's address/port, which doesn't make sense in a local setup...

**Comment by jean-emmanuel** [comment]
Here is the problem :

Ardour sends feedback messages to the sender's address, which is different from the initial message's target and not necessarily specified (currently random). I can make open stage control use its osc input port (set with `open-stage-control -p PORT`) as the sending port to make sure feedback messages are sent back to it.

Unfortunately, ardour doesn't use the same osc paths for incoming and outgoing messages, open stage control does. This breaks the previous fix proposal, as an osc router would be needed to listen to the same port and convert the paths.

I can see one solution for now : add a command line switch that allow choosing from which port open stage control sends messages. This will make the use of a third party router possible.

Example:
```bash
open-stage-control -p 5555 -o 6666 # "-o" would mean osc-output-port 
```
A router could then listen to the port 6666 for feedback messages from Ardour, translate and send them to the port 5555 to update the app.

Does that make sense ?

**Comment by ovenwerks** [comment]
On Mon, 4 Apr 2016, jean-emmanuel wrote:

> 
> Here is the problem :
> 
> Ardour sends feedback messages to the sender's address, which is different from
> the initial message's target and not necessarily specified (currently random). I
> can make open stage control use its osc input port (set with open-stage-control
> -p PORT) as the sending port to make sure feedback messages are sent back to it.

Ardour's OSC code is not anywhere near finished. There are a number of 
things that need to be done. However, sending replies to the port that 
sent things just makes sense. This allows any number of controlers to work 
with Ardour at the same time. If the return IP:port was set only one would 
be possible.

> Unfortunately, ardour doesn't use the same osc paths for incoming and outgoing
> messages, open stage control does. This breaks the previous fix proposal, as an
> osc router would be needed to listen to the same port and convert the paths.

This is one of the things I would like to change. There are other problems 
with the feed back as well. For example, there are three ways of sending 
fader gain to Ardour: absolute gain, dB gain and fader position (just 
added this). Of the three the least useful one for a control surface is 
absolute gain, but absolute gain is the only one Ardour seems to send back 
to the controller. (This gain value is the one Ardour uses internally... 
abs_gain * sample = new sample) There are some control uses for abs_gain, 
so just replacing it is not the best thing. This leaves the controller 
with the mess of calculating a reasonable fader position. Using it is puts 
0 db at 50%, so the most useful range of fade is squeezed into about 25% 
range. Using log scale (as open stage control offers) is better, but still 
a long way from what people are used to for mixing with. (most faders have 
two different log scales and a linear below that) In my controller I used:
http://www.cw-industrialgroup.com/getattachment/ff841b57-256b-4469-bc76-6bcc317306b2/pgf3000_brochure
which has db values by distance for various lengths of fader. I used the 
104 mm fader and starting from the top used the distances to set my break 
points and shifted everything by +10db. It may be possible using break 
points to convert from abs->dB, but then the manual entry/displayed value 
would still be abs making it a lot less useful. Other controls have 
similar problems.

I am proposing a new OSC namespace /ardour/bank where the controls are 
treated generally as control position similar to the mackie control 
protocol (MIDI) for example. The problem with this is that the banked 
controls would be only usable by one device or if used by more than one 
device those devices end up synced in terms of bank number and size. The 
other possiblity would be middleware (as you suggest below). My own HW 
will have it's own middleware anyway so that it can be used with other SW 
besides Ardour. In the banked scheme, it would be possible to save 
first_rid/bank_size against each known output URL as well and use that to 
filter the feedback.

> I can see one solution for now : add a command line switch that allow choosing
> from which port open stage control sends messages. This will make the use of a
> third party router possible.

This is probably needed for any use where the controller and DAW are on 
the same machine.

> Example:
> 
> open-stage-control -p 5555 -o 6666 # "-o" would mean osc-output-port 
> 
> A router could then listen to the port 6666 for feedback messages from Ardour,
> translate and send them to the port 5555 to update the app.
> 
> Does that make sense ?

Perfacet sense. I will see what I can do (I do not work near as fast as 
you have been) about making feedback more reasonable so that middleware is 
not needed.

I have started having some wierd stuff on the android where touching a 
widget makes a bunch of stuff vanish. I will check against a second tablet 
to see if it is just this one.

--
Len Ovens
www.ovenwerks.net

**Comment by jean-emmanuel** [comment]
>  However, sending replies to the port that sent things just makes sense. This allows any number of controlers to work with Ardour at the same time. [...]

Good point

> [...] absolute gain is the only one Ardour seems to send back to the controller. [...]

This is problematic indeed...

> I have started having some wierd stuff on the android where touching a widget makes a bunch of stuff vanish. I will check against a second tablet to see if it is just this one.

uhoh ! i'll wait for the bug report then

**Comment by jean-emmanuel** [comment]
I've come to the conclusion that using the osc input port (`-p / --port`) as a sender reference is the most logical way to go :  if no middleware is used, feedback messages are sent to open stage control, otherwise, it's up to the middleware to declare its own sending port in order to catch the controlled app's feedback and route it to open stage control.

**Comment by jean-emmanuel** [comment]
Faders & Meters design has been improved, built-in meters should be visible now !
Note that the fader's `align` option has been removed, faders are now left aligned by default or right aligned if `alignRight` is set to `true``(centered faders with mirrored pips didn't work so well)
https://github.com/jean-emmanuel/open-stage-control/commit/7687a2db23f4db0eccefa66ca08bf52a002652a8
