### ISSUE TITLE
Dropdown feature request

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#140]
I have just started working on groups in Ardour for OSC. The strip's group is now displayed fine. I want to allow a strip to add it self to a group and thought the dropdown  might be nice for that. However, I see that the drop down choices are preset. What I would like to see: User presses dropdown button, O.S.C. sends /group/list. The DAW sends /group/list is 1 groupname1 and /group/list is 2 groupname2. O.S.C. then creates a dropdown with two items groupname1 and groupname2. The user selects one of them and O.S.C. sends /group/list is ID Text. If the user presses the dropdown button again, the items are cleared and the DAW is expected to send a new set.

This would be useful anywhere the DAW has a dynamic list of things for the user to choose from like plugins in a strip or whatever.

**Comment by jean-emmanuel** [comment]
I don't think it's doable the way you describe it, although the custom module feature already allow something very close:
- a push button sends /group/list
- the custom module listen to /group/list messages and update the surface accordingly -> /EDIT dropdown_id "{values:[...]}"

**Comment by jean-emmanuel** [comment]
In general, dynamic widget generation is best handled from the custom module : the parsing logic for this kind of messages (ie /goup/list, /strip/plugins/list) is too specific to each DAW and application to be implemented in a general way at a widget level. I prefer to have widgets as generic as possible, although easely editable, and let 3rd party apps, router, and custom modules handle the DAW specific logic.

**Comment by ovenwerks** [comment]
Right that was why I used only one OSC /path. The idea is it would always be /path is index "Text". Preargs could be applied as normal. The only difference is the button press would send no arguments, just /path, but sending /path is 0 "" would work just as well.... though that would mean the index would have to be 1 based. I am sorry I used a specific path name :) But to be generic the path would have to always be the same. both receiving and sending. It would actually be possible to do away with the index and just use /path s "text"... That may actually be better in fact. The button sends /path s "" or even /path s <current text>

I am going to have to learn to do a custom one for sure. In a GUI dropdowns are dynamic by their nature. It is this dynamic list creation for files, plugins, groups, VCAs, etc. that right now forces the user to go back to the DAW's GUI. A generic list creator/selector is really missing in remote control. I shall ask how Lemur does this (if it does).

**Comment by jean-emmanuel** [comment]
In O-S-C, sending messages to /widget/path is meant to change a widget's value, not its properties. Changing any property other than `value` implies recreating the widget and therefore loosing current interaction (ie closing the dropdown). Allowing changing properties without recreating widgets would require writing specific update routines for each property of each widget, I'm not going down that road now, and even if I did it would still be through the /EDIT way. Using the same osc address for different purposes like Ardour does seems to much confusing to me.

By generic I don't mean "every applications should understand each other out of the box via osc messages", I don't think it's a realistic goal. The way I see it, every application should describe and update itself in a coherent way via osc, but you always have to connect the wires and adapt the different application's logics at some point. Imho, a reasonable goal is to make the hacking part as easy as possible. 

> In a GUI dropdowns are dynamic by their nature

I highly doubt it is a common usage to populate a dropdown only after a user opens it, is it ?

**Comment by ovenwerks** [comment]
On Thu, 1 Feb 2018, jean-emmanuel wrote:

> In O-S-C, sending messages to /widget/path is meant to change a widget's value,
> not its properties. Changing any property other than value implies recreating the
> widget and therefore loosing current interaction (ie closing the dropdown).

So far that is fine. However in the case of a drop down, or something 
similar like a simple file selector for example, the list of things to 
choose from is/are the values.

>       In a GUI dropdowns are dynamic by their nature
> 
> I highly doubt it is a common usage to populate a dropdown only after a user
> opens it, is it ?

That is true. I just started the "how do I do this" thought process 
yesterday. In the real world, the DAW has a new strip to 
create and will fill the dropdown at that time before it is touched and 
set the current value.

Using /EDIT does not work for this, at least from a DAW developers POV as 
it is controller specific. OSC is not MIDI, where midi controllers are 
generally set and the DAW does the mapping of incoming MIDI to function, 
in OSC the DAW has a set of OSC commands that do things and the controller 
is considered smart enough to send them.

Using /EDIT is quite painful from a Controller user's POV as well. I have 
looked at 
https://github.com/jean-emmanuel/ardour-control/blob/master/ardour-plugins-module.js

In this case adding a new dropdown means effectively hacking this over and 
over rather than making a new widget once and just using it as many times 
as needed. If I could do something like ardour-plugins-module.js that 
became a widget that I could use genericly, that is just change the path 
and go, that would be much better. Really the dropdown is the only thing 
close to what is needed. Though a dialog with window that can have 
selectable lines of text/index like a file selector would work too.

So another look at a widget as I would see it. This may be a dropdown or a 
dialog, though in truth there is not much difference between the two. 
Looking at the slider/fader widget, there are three OSC address fields. So 
having more than one OSC address field is not out of the question. The 
main address, as now, would be value, that is index. It does not matter if 
it is 1 or 0 based as the 0 can be unset/blank if not needed. (sorry for 
the random thought process) Now to fill the list, we need both index and 
text. I think this can best be done with one OSC command per item (/path 
index text), but would work probably just as well as one OSC command with 
all the index/text pairs in it. (thinking "out loud") After more thought, 
the most generic method would be to have the fill path set up like:
/path ss... "text" "text"...

When the controller receives the fill path, it knows to clear whatever 
stuff is there now and take each "text" in order to fill the drop down. To 
make things as generic as possible, start the index at 0. Someone like me 
who does everything starting at 1 can send a "" as the 0 text or use it to 
unset things (ie as "none") but that is not relevant to the controller 
anyway.

So leaving the drop as is except add one more user settable address to 
fill it. A set of commands might look like this:

Daw->O-S-C /path/list sss "option 1" "option 2" "option 3"
Daw->O-S-C /path i 2
The dropdown shows "Option 2".
The user clicks the dropdown and selects "Option 1"
O-S-C->Daw /path i 1

If the fill path (setup path or whatever) is not set (or even if it is) 
the "Values" field would supply the default values as now.

I am sorry for putting you through my thought process as I thought this 
through. But this is something that I see as missing in OSC controllers 
for future expansion. If it would be easier to use a dialog which would 
automatically allow for scrolling through long lists and possible be more 
generic in the long run, I am not opposed to that either. At this time I 
do not see myself needing a file selector with paths and new folders and 
all that junk. However, the more stuff I add to Ardour's OSC, the more 
people look at it and go "this is really useful, if only it also...". 
There is a headless version of Ardour and some people would like to be 
able to use OSC as the GUI. I suppose I am slowly moving in that direction 
from a most used to least used POV.

--
Len Ovens
www.ovenwerks.net

**Comment by jean-emmanuel** [comment]
I just realized it's already 99% possible... take a look at the attached session (latest release required), the dropdown inherits from the input's dynamic value (targetted via the special `_value` introduced in v0.23), you can use the input for /group/list and the dropdown for /group. Here's what would be missing here:
- [ ] make dropdowns correctly interpret a single non-array/dict value in the `values` property 
- [ ] add an option to set a dropdown's value based on the index/key rather than the actual value

I could make a shorthand widget that would contain these two but I'm not sure it is necessary.

[dynamic-dropdown.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1690542/dynamic-dropdown.json.txt)

**Comment by jean-emmanuel** [comment]
Added `sendKey` option to send selected value's key/index;

**Comment by cyberic99** [comment]
cool stuff!
This could be very useful!
Will test it soon.

**Comment by ovenwerks** [comment]
Used the method in:
dynamic-dropdown.json.txt
It works fine. It is text based rather than indexed based which is more robust from my point of view. The index may change if an item is removed, but the name should be the same in that case. (in any of the places I have so far contemplated) It does mean hiding the input box... is there a correct order to always make one on top of the other? (it looks like input first, dropdown after will allow dropdown to be on top hiding input)

Not sure about the sendKey option, the editor doesn't show it but that may be because I am using 0.23.1 and as I said above, using a name (even if a string search takes longer) is more robust.

I also like that I can have 1 input widget (/group/list) with 9 dropdowns (/strip/group x8 and /select/group) all with the same list. (I think, I haven't tried that yet)

PS I have come to rely on the editor a lot, my layout files have gotten too large for hand editing. I am glad these tricks seem to still work all right in the editor.

**Comment by jean-emmanuel** [comment]
sendKey is only in master for testing yet. I agree the string way is more robust.

> it looks like input first, dropdown after will allow dropdown to be on top hiding input

Yes. You can also use css `z-index` property : widgets with a position different from `auto` have `z-index:10` by default, In case of equality, the last widget wins.

> PS I have come to rely on the editor a lot, my layout files have gotten too large for hand editing

Me too :)

**Comment by jean-emmanuel** [comment]
> I also like that I can have 1 input widget (/group/list) with 9 dropdowns (/strip/group x8 and /select/group) all with the same list. (I think, I haven't tried that yet... they would have to be in the same container maybe)

You can do that, no need to be in the same container,.

**Comment by jean-emmanuel** [comment]
> **jean-emmanuel:** 
Allowing changing properties without recreating widgets would require writing specific update routines for each property of each widget

I've been giving this some thought and figured it would actually only need a few changes to prevent a complete widget recreation in many cases (ie  when properties are not processed in the widget's constructor and not cached server-side). I think I might be able to implement routines for the remaining properties in a not-that-far future, bit by bit. In the mean time I'll try to document which props are `dynamic` and which props are not. If I do this right, this could greatly improve editing operations :)

**Comment by ovenwerks** [comment]
Hmm, A funny thing happened on the way to the dropdown... Using the method detailed in dynamic-dropdown.json above, everything works just fine except if there is only one entry... then it shows each character as a separate entry. This is something I could work around... but it is messy. What happens is that if more than one string is sent the value looks like ["string", "string"] but, if there is only one, it is set like string with no quotes or [ ]. I am guessing the dropdown is treating the text as char sized ints.

**Comment by jean-emmanuel** [comment]
Fixed 3 days ago : 319e5e0dd9d19e625867ab608dc85c38a9b77aa2 ;)

**Comment by ovenwerks** [comment]
Thank you. Next release then.

**Comment by jean-emmanuel** [comment]
FYI, I'm dropping the `sendKey` options and "receiving key" feature as they imply too much ambiguity.

**Comment by cyberic99** [comment]
@jean-emmanuel I think that sendKey could have been useful...
Is it the sending part or the receiving part that caused issues?

**Comment by jean-emmanuel** [comment]
Well sending the key doesn't really make sense since one can already put anything as key/value : if you want to send numbers, set `values` as numbers. 

Being able to receive both keys or value just seemed too ambiguous and doesn't comply with the general "value is meant to set value"  logic I try to keep in place.

**Comment by cyberic99** [comment]
Hi
I tested this feature with the latest git version (f33248c), and I noticed that when the choices list is changed, the dropdown loses its current selection.
I am using something similar with an 'switch' widget, and in that case, the selection is not lost, which is better ;-)

**Comment by jean-emmanuel** [comment]
-> fixed ;)

**Comment by jean-emmanuel** [comment]
v0.24.0 is out
