### ISSUE TITLE
Feature request Editable text plot

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#141]
It would be really nice to be able to edit a text plot. Daw sends /strip/name is 1 "Audio 1", User sends /strip/name is 1 "Jerry" back and DAW changes strip name.

**Comment by jean-emmanuel** [comment]
I believe the `input` widget already fulfill this purpose :)

**Comment by ovenwerks** [comment]
Cool, I am not finding that in http://osc.ammd.net/widgets/widgets/

**Comment by jean-emmanuel** [comment]
Damned, the page was missing from the index, fixing right now !

**Comment by jean-emmanuel** [comment]
http://osc.ammd.net/widgets/inputs/

**Comment by ovenwerks** [comment]
Thank you

**Comment by ovenwerks** [comment]
Already there (works good)
