### ISSUE TITLE
Property inheritance

### ISSUE THREAD

**Issue by micpool** [jean-emmanuel/open-stage-control#142]
This is really genius software. Thanks
I've got nearly everything working as I would like it, but am completely stumped on property inheritance.

I would be really grateful if you give me an example of exactly how to do the following.

2 sliders:  fader_1 to have the value of fader_2

1 slider 1 RGB: fader_1 to have  the value of RGB_1 red

Thanks

Mic

**Comment by jean-emmanuel** [comment]
Hi, thank you for your feedback :)

> 2 sliders: fader_1 to have the value of fader_2

You can either
  1. give them an identical `id` (synced value, osc message sent by the touched slider only)
  2. give them an identical `linkId` (synced value and osc messages sent by the 2 sliders)
  3. create a `clone` widget (category: `containers`) that targets the slider (same as 1. but easier to maintain)
  4. use one-way property inheritance: set fader_1's `value` property to `@{fader_2._value}` (one way sync, both will send osc) 
  5. use both-ways property inheritance: set fader_1's `value` property to `@{fader_2._value}`  and fader_2's `value` property to `@{fader_1._value}` 

> 1 slider 1 RGB: fader_1 to have the value of RGB_1 red

Set fader_1's `value` property to `@{rgb_1._value.0}`

**Comment by micpool** [comment]
On 5 Feb 2018, at 10:35, jean-emmanuel <notifications@github.com> wrote:
> 1 slider 1 RGB: fader_1 to have the value of RGB_1 red
> 
> Set fader_1's value property to @{rgb_1._value.0}
> 
Thanks very much I’ve now  got the rgb widget controlling 3 faders for a RGB LED light fiting.

. How would that be written in a formula?

${rgb_1._value.0} doesn’t work.

Mic

**Comment by jean-emmanuel** [comment]
Currently formulas don't follow the same rules, it's actually about to change in next release as I'm implementing a unified, math-expression-compatible, syntax for all properties. For now you have to write `${rgb_1}[0]` to use `rgb_1`'s first value item in the formula.

**Comment by jean-emmanuel** [comment]
Cool ! Thank you for sharing :)
