### ISSUE TITLE
XY pad bug?

### ISSUE THREAD

**Issue by micpool** [jean-emmanuel/open-stage-control#143]
XYpad widgets don't send their values to  formulas when double tapped (sliders do)

Thanks

**Comment by jean-emmanuel** [comment]
I'm not sure to understand, are you using the fader's `doubleTap` option ?

**Comment by micpool** [comment]
Yes, I have the double tap box checked on the xypad widget. I have set the double tap to centre the cursor.  When I double tap the cursor moves back to centre but doesn’t send it’s values to maths formulas.

With a fader widget  set to double tap, it behaves as expected and sends its new value when it returns  to the position set.

**Comment by jean-emmanuel** [comment]
Nice catch, it a bug, the fix is pushed and will be included in next release.

**Comment by jean-emmanuel** [comment]
v0.24.0 is out
