### ISSUE TITLE
Dropdown default value

### ISSUE THREAD

**Issue by micpool** [jean-emmanuel/open-stage-control#146]
I can't reproduce this in a simple workspace but...

 the attached file opens fine. If you change the default value of dropdown_6 (top right of panel) from 0 to 1. It immediately throws an error. If you save the file won't open again.

Thanks

[CatalystQLab.json.zip](https://github.com/jean-emmanuel/open-stage-control/files/1711943/CatalystQLab.json.zip)

**Comment by jean-emmanuel** [comment]
Hi, looks like a cool project !

The dropdown issue seems to be fixed in git, hopefully to be released soon.

What prevents the session to open is the same as in #145.

**Comment by jean-emmanuel** [comment]
v0.24.0 is out
