### ISSUE TITLE
Freeze when sending plots

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#148]
This one is funny.
To repro:
- open a new editor.
- create a plots widget
```
oscsend localhost 8080 /plot_1 s "{'10':10}"
```

The UI is frozen.
The debug console still prints what is received

Version: git e2be66f59716f8f29450cae2f17347c996d24866

**Comment by jean-emmanuel** [comment]
Nice catch, fixed in git !

**Comment by jean-emmanuel** [comment]
v0.24.0 is out
