### ISSUE TITLE
issue with dynamic properties

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#149]
Hello
I am not really sure this is a bug, feel free to discard...
In the attached dahsboard, I have 2 faders.
I would like the labels to update at the same time as the faders. 
I use dynamic properties for that.

You can see that below the first fader, I added buttons that set the first  fader automatically to -1 or 1
I do that by using push buttons with the same id as the fader (ie speed)
I don't know if it is supposed to work like this, but it works for me ;-)

What does not work is the dynmic label on the first fader
(it works correctly on the 2nd one)

What do you think? Are such things supported?
[gh-issue-fader.txt](https://github.com/jean-emmanuel/open-stage-control/files/1714941/gh-issue-fader.txt)

**Comment by jean-emmanuel** [comment]
It's not really a bug but more a limitation : property inheritance doesn't differenciate multiple widgets with the same id, your toggle's label is retrieving the push's off value. This needs some tinkering, I'll get back to it soon.

**Comment by cyberic99** [comment]
I don't know if it is worth complexifying the code for that...
But... it is still useful to be able to set a widget value based on another one, without any server interaction.
I use it with a 'loop' range fader and a dropdown, for exemple, so that when I click on the dropdown, that moves both ends of the fader accordingly.
It uses the same trick: the dropdown and the fader share the same id.

**Comment by jean-emmanuel** [comment]
Well at first there was no property inheritance so widget `id` could not be ambiguous that easily, it would be good to fix that, I'm considering encouraging users to rely on the `linkId` property and adding an additionnal `linkSend` option for choosing whether to send osc messages or not when updated this way.

**Comment by cyberic99** [comment]
But what would be the difference between 2 widgets having the same id, and two widgets linked by the linkId?

**Comment by jean-emmanuel** [comment]
Two widgets linked by a linkId could have different id and be targetted separately by `@{id}` statements. Giving identical `id` would only be used in case of cloned widgets (for example when one needs the same widget in different tabs).

**Comment by cyberic99** [comment]
I see. But would the 'link' be bidiectional?
In my use case, I would have the push button's ``linkid`` property set to the fader's id?
If so, what would be the button's value after I move the fader?

**Comment by jean-emmanuel** [comment]
`linkId` doesn't refer to another widget's `id`, it's an arbitrary value you choose, all widgets that share the same `linkId` are synced

**Comment by cyberic99** [comment]
Okaaay, I had not understood that point ;-)
So that means I can already have my use case working, using the linkId?

**Comment by jean-emmanuel** [comment]
I think so :)

**Comment by cyberic99** [comment]
Ok.
I'll try the proper way, then.
Closing the issue since ... it is not really an issue.

**Comment by jean-emmanuel** [comment]
Side note: `#{@{id}}` is the same as `@{id}` except it takes more cpu and memory because of the associated math parser (that does nothing here).
