### ISSUE TITLE
New code to allow fine control on touch screens doesn't work

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#15]
Tried on two different devices. As soon as a second finger touches the same fader, the value resets to minimum value and stays there. Tried holding one finger still and moving the second (both the one closer to the top and the bottom. Moving both at the same time or moving them apart). Found out that holding a finger anywhere on the widget for too long opens the on screen keyboard :)

I can however operate 5 fader strips at the same time :) (my big fingers tend to have problems getting more than that on the 7inch screen)

**Comment by jean-emmanuel** [comment]
Ok I"ll have to borrow a device to make it work ;)

> Found out that holding a finger anywhere on the widget for too long opens the on screen keyboard

This is new and intended but I don't know if it can be annoying, can it ? The goal was to be able to set the value manually even for compact widgets (faders and knob with the appropriate option atm). Maybe this feature should be restricted to this case.

**Comment by ovenwerks** [comment]
On Tue, 5 Apr 2016, jean-emmanuel wrote:

> 
> Ok I"ll have to borrow a device to make it work ;)

Second best is a setting to force ratio

>       Found out that holding a finger anywhere on the widget for too long
>       opens the on screen keyboard
> 
> This is new and intended but I don't know if it can be annoying, can it ? The
> goal was to be able to set the value manually even for compact widgets (faders
> and knob with the appropriate option atm). Maybe this feature should be
> restricted to this case.

I did not find the action limiting in normal use. Just trying to test 
multi-finger use means thinking while trying and so:
place finger-think-place finger-think- move

Any of those thinks may be overly long. Once a person is used to doing 
things I think it will not be a problem. I certainly did not mean that 
comment as a bug. Maybe something to watch/test though.


--
Len Ovens
www.ovenwerks.net

**Comment by jean-emmanuel** [comment]
> I certainly did not mean that comment as a bug. Maybe something to watch/test though.

I'll probably limit the feature to one-finger-only long taps

**Comment by jean-emmanuel** [comment]
8f9a13008c7c92e9ed9882571f89f829b03f067d introduces something that seems to work !

**Comment by jean-emmanuel** [comment]
included in [v0.11.2](https://github.com/jean-emmanuel/open-stage-control/releases/tag/v0.11.2)
