### ISSUE TITLE
Copier/coller

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#153]
Hello. C'est Black Adopo, le beatboxer qui fait du LGML avec qui tu as fait un peu de debuggage cette aprem. Je vais déjà spammé ton github ;). J'ai un mini soucis avec la nouvelle version de open stage control.
Encore ce matin je pouvais copier/coller ce que je voulais dans tes paramètres (par exemple l'adresse OSC dans un bouton). Depuis ta nouvelle version je ne peux plus. Ce qui peut être assez contraignant.

En tout cas bravo pour cette application !

**Comment by jean-emmanuel** [comment]
En effet, petite regression du jour ! Je viens d'envoyer une version 0.24.2 dans les tuyaux pour régler ça. Merci pour tes retours :)

**Comment by Adopo** [comment]
Avec plaisir ! Merci pour ton logiciel !

**Comment by jean-emmanuel** [comment]
Est-ce que le problème est bien réglé du coup ? Normalement tu devrais avoir quelques menus en plus dans la barre de menu d'OSX.

**Comment by Adopo** [comment]
Oui pardon le problème est réglé ! Et en effet il y a plus d’option en haut. C’est chouette !
