### ISSUE TITLE
linkId not preserved when copy/pasting

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#155]
to repro:
- create a widget with a non empty linId
- copy
- paste (id+1)
The linkId of the pasted widget is now empty

**Comment by jean-emmanuel** [comment]
I confirlm : https://github.com/jean-emmanuel/open-stage-control/blob/master/src/browser/js/app/editor/data-workers.js#L88
This piece of code is very old, deleting linkId doesn't make sense anymore (if it ever did). Will fix ;)

**Comment by jean-emmanuel** [comment]
fixed in git

**Comment by jean-emmanuel** [comment]
Included in v0.24.3
