### ISSUE TITLE
Sélection multiple

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#156]
Ce qui pourrait être vachement chouette c’est de pouvoir sélectionner plusieurs widget à la fois et pouvoir avoir acces a leur propriétés communes. 
Par exemple je fais un looper avec plusieurs pistes. J’aimerais pouvoir aligner plus facilement mes widget en pouvant selectionner par exemple tous veux d’une ligne verticale et de leur mettre le meme « left » ou de les mettre d’un coup tous de la meme couleur.
Ca pourrait être chouette d’avoir aussi le copier/coller lors de cette sélection multiple pour par exemple copier a l’id + 1 plusieurs controleurs d’une piste 1 pour une piste 2

**Comment by jean-emmanuel** [comment]
Ça pourrait être cool en effet ! Je vais creuser un peu la question, ça impliquerait pas mal de changements.

**Comment by jean-emmanuel** [comment]
Pour l'instant je te conseille d'utiliser des panel/strip pour ranger tes widgets, ça aide, et la copie n+1 sur un container est récursive.

**Comment by Adopo** [comment]
Ouep c’est ce que je fais depuis mon post et ca aide un peu. Toujous dans le domaine de la copie. Pouvoir avoir les raccourcis pour copier/coller ca pourrait faciliter la tâche également.

**Comment by jean-emmanuel** [comment]
Ok ça commence à ressembler à quelque chose, tu peux tester avec la demo:

- en maintenant `ctrl` appuyé, les widgets sont ajoutés/enlevés de la selection
- les actions du menu contextuel (clic droit) s'appliquent à tous
- le panneau d'édition affiche les propriétés communes aux widgets (les valeurs affichées sont celles du premier selectionné, mais toute modification est appliquée à tous)
- la selection multiple est limitée aux widgets ayant le même parent.

**Comment by Adopo** [comment]
cool :). Mais ce n'est pas effectif dans la derniere maj c'est ca?

**Comment by jean-emmanuel** [comment]
Non, c'est dans la demo en ligne et dans le depot github ):

**Comment by Adopo** [comment]
D’accord. On fait comment pour utiliser le dépot github? Il fait recompiler soit meme c’est ca?

**Comment by jean-emmanuel** [comment]
Oui, je viens de simplifier les instructions pour le faire, ce n'est pas encore en ligne sur le site, mais tu peux regarder ici https://github.com/jean-emmanuel/open-stage-control/blob/master/resources/docs/getting-started.md#run-from-sources

**Comment by jean-emmanuel** [comment]
-> v0.25.0

**Comment by jean-emmanuel** [comment]
pour les raccourcis clavier ->  #186
