### ISSUE TITLE
Editor: prevent sending osc messages when selecting a widget 

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#157]
Lorsque l’on est en mode édition on est susceptible de cliquer sur des push par exemple pour les déplacer. Hors pour le moment en mode edition lorsque l’on clique sur un push il envoi encore son message. Je penses qu’Il faudrait le désactiver. Car par exemple si mon logiciel controlé est allumé les enregistrements pistes, etc. se déclenchent tout seul par exemple.

**Comment by cyberic99** [comment]
comme un mode 'mute' qui n'enverrait aucun message OSC?

**Comment by jean-emmanuel** [comment]
C'est un truc qui traine depuis quelque temps, je viens de faire en sorte que la selection d'un widget dans l'éditeur ne déclenche pas d'interraction (une fois selectionné, le widget répond toujours normalement par contre pour éviter les allers-retours entre editeur on et off).

@Adopo  au passage je crois que j'ai réglé le problème du bouton d'ouverture du panneau latéral sur ios

**Comment by Adopo** [comment]
Oh je vais aller voir ca ! 
C’est un bon compromis de pouvoir sélectionner mais aussi tester en appuyant dessus, j’expérimenterais pour voir si ca fait l’affaire.

Oui c’est ca une sorte de mute. Après si jamais ca se déclenche encore facilement ca peut etre aussi une option a côté du edit qui permet d’activer ou non les touches. A voir si ca ne complexifie pas trop.

**Comment by jean-emmanuel** [comment]
Ah oui, un mute general pourrait le faire aussi, à voir, si ce que j'ai fait est suffisant à l'usage ou non.

**Comment by jean-emmanuel** [comment]
Included in v0.24.3
