### ISSUE TITLE
Server-side session saving

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#158]
On avait parlé du save côté client qui ne fonctionnait pas et tu voulais le retirer et retirer toute cette partie edition sur le client. Au contraire après réflexion je penses qu’il faudrait la laisser et la rendre fonctionnelle. Lemur a par la suite intégré la possibilité d’éditer côté client et parfois c’esr vraiment utile. Ne serait ce que dans le cas de ton soft pour bien placer les boutons en fonction de la taille de l’ecran client qu’on ne visualise pas forcément sur le serveur.
Après je ne sais pas dans quelle mesure il est possible qu’un client sauvegarde sur le serveur. Ca peut être considéré parfois comme une faille réseau.

**Comment by jean-emmanuel** [comment]
L'idée serait effictevement de toujours pouvoir sauver mais en faisant l'écriture côté serveur, ça permettra d'éviter les démarches du type "sauvegarde + recharge pour faire apparaitre dans la liste au démarrage". À suivre.

**Comment by Adopo** [comment]
Ouep je voyais ca du côté serveur également car si je puis me permettre, l’aspect rien a installer côté client est vraiment un plus non négligeable ! C’est pour ca que je me posais des questions sur les droits mais si c’est faisable c’est chouette !

**Comment by jean-emmanuel** [comment]
moved to #200
