### ISSUE TITLE
copy a value from one object to another one

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#159]
It would find it very useful to be able, when pressing or toggling a button, to copy a widget value from one to another.
We could use it to sync 2 faders, or for momentarily copy a fader's current position somewhere.

It can be achieved partially by having dynamic linkIds, but maybe there are other ways to do it...

Or maybe within mathjs...

What do you think?

**Comment by jean-emmanuel** [comment]
I could add a special math function that allow setting any widget's value from within a formula, something like `setValue(id, value)` but I'm really not sure it's a good idea. I'll give it some thoughts.

**Comment by jean-emmanuel** [comment]
I think this should be enough : https://github.com/jean-emmanuel/open-stage-control/issues/161#issuecomment-368822162
Added to #152.
