### ISSUE TITLE
feedback sent with preargs doesn't work

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#16]
If I set a fader as /fade1 range -200 to +10 I can use oscsend localhost <port> /fade1 f -10 and the fader on my GUI moves to -10, great. However, If I set it to /fade ff 1 -10 (that is prearg = 1.0) and I send oscsend localhost <port> /fade ff 1 -10 Open stage control does not respond. o-s-c sends the messages correctly, but does not respond to the same messages sent back.

**Comment by jean-emmanuel** [comment]
My bad, this was broken with commit 65457bfb3ae668e14c5c07a08c1a7ab83dff99fe, fixed in 34a3caf9843dad478937f04c03c8868ca7356f49 :)

**Comment by ovenwerks** [comment]
Yup that fixes it. Now I can't get npm run build to run.
