### ISSUE TITLE
Envie de faire plein de trucs

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#160]
Bon... je ne sais plus si on t’a dis, on a fait des tests de performance avec Ezra. A tester plus en performance mais la latence n’a pas l’air si éloignée que ca de lemur. En filaire c’est même pas si mal. A tester en profondeur.
De plus j’ai téléchargé tes deux exemples et je me rends compte qu’il y a moyen d’aller tres loin en terme de controleur. C’est encore plus ouvert que lemur. Les données gyroscope en plus et on est proche d’un outil exceptionnel malgré les contraintes page navigateur qu’on a vu ensemble.
Je ne me souviens plus comment tu avais fait pour faire des fonction qui font communiquer les widget entre eux et comment en osc on peut attaquer les parametres de certains widget pour modifier leur caractéristique. Y a t il une doc pour ca?
Y a t il aussi une doc sur par exemple les icones dans les push possibles?

J’ai fais mon premier contoleur looper à 6 pistes. Encore un peu long a faire en raison du copier/coller multiple absent et de la non possibilité de modifier la taille de plusieurs widget en meme temps surtout en vnc depuis un telephone pendant que je fais autre chose mais c’est vraiment puissant !
![Image](https://i.imgur.com/mUbL9zJ.jpg)

**Comment by cyberic99** [comment]
> et comment en osc on peut attaquer les parametres de certains widget pour modifier leur caractéristique. Y a t il une doc pour ca?
C'est avec /EDIT. On peut changer des paramètres ou renvoyer carrément tout le widget en json

> Y a t il aussi une doc sur par exemple les icones dans les push possibles?
Tu peux mettre toutes les icones de fontawesome, avec un '^' avant

> J’ai fais mon premier contoleur looper à 6 pistes. Encore un peu long a faire en raison du copier/coller multiple absent et de la non possibilité de modifier la taille de plusieurs widget en meme temps surtout en vnc depuis un telephone pendant que je fais autre chose mais c’est vraiment puissant !
Normalement tu devrais pouvoir faire une seule tranche, puis la cloner autant de fois que tu veux.
Chaque tranche peut overrider des variables, avec son propre numéro de tranche.
Pour différencier les messages OSC que les tranches enverront, tu peux utiliser les preArgs.

Je crois que dans cette issue il y a un controleur qui pourrait te montrer ce qu'on peut faire:
https://github.com/jean-emmanuel/open-stage-control/issues/127

N'hésites pas à parcourir toute la doc, parfois une phrase ou deux te montrent la richesse de ce que tu peux faire ;-)

**Comment by Adopo** [comment]
Ouep j’avais vu l’exemple j’ai vu aussi le ardour. Ca m’a éclairé sur certaines choses. Par contre désolé j’ai encore du mal a capter certaines choses. J’ai voulu refaire l’exemple que tu m’avais montré en transférant la valeur d’un fader sur un input. J’ai beau lire la dic j’y arrive pas. Sans exemple concrets sous les yeux j’ai du mal.

**Comment by Adopo** [comment]
La doc*
Et est ce que je mets mon code dans l’envoi osc?

**Comment by cyberic99** [comment]
Hello c'est @cyberic99 qui t'a répondu, pas @jean-emmanuel.
J; essaye de filer un coup de main si ke peux ;-)
tu veux qu'un input suive un ader et vice-versa?
dans ces cas la il faut simplement que dans leur champ linkId tu mettes la meme chose, un identifiant.
Genre 'volume' ou 'gain' ou heu ce que tu veux

**Comment by Adopo** [comment]
Oh pardon j’avais pas vu.
Pas tout à fait. En fait je voudrais qu’un widget puisse influé sur un autre. Par exemple un push qui une fois actionné mettrait 2 fader à 1, 2 fader à 0,5 et 2 fader à 0. Ou alors un fader qui en fonction de son niveau activerait tel ou tel push. 
Pour l’instant j’essayais de faire un exemple avec un fader qui transmet sa valeur au push car Jean-Emmanuel  était passé par la comme exemple mais je cherche un truc plus complexe qu’un simple link.

En tout cas merci pour l’astuce pour le link je vais explorer cela en parallèle

**Comment by cyberic99** [comment]
pas de souci ;-)

Si tu veux un fader qui active un push, tu peux mettre dans la 'value' de ton push:
```
#{@{fader}>50?1:0}
```
(enfin je fais ca de tête)

Le fait d'avoir une action temporaire sur un push...
j'ai justement demandé la même feature a @jean-emmanuel...
Je trouverait ca super intéressant, par exemple pour fixer un BPM d'un input à un fader, ou copie une valeur d'un widget à l'autre....
ca pourrait aussi se faire en mathjs...

En fait j'ai réussi à le faire, mais ca nécessite un widget text intermédiaire, et de la bidouille...
Si @jean-emmanuel ne trouve pas de solution on ne veut pas implémenter cette feature, j'essayerai de faire un exemple simple.

Ou alors dis moi si ca t'intéresse de facon urgente ;-)

**Comment by Adopo** [comment]
Merci pour ces infos j’y vois plus clair !
Alors le fait de pouvoir avoir une action temporaire sur un push ça m’intéresse mais ce n’est pas urgent.
En gros j’ai mes contrôleurs lemur via ipad et ipod. On a discuté avec jean emmanuel et ma compagnie et le fait de pouvoir avoir un controleur sans appli à installée est un atout non négligeable en ateliers. Du coup j’essaie d’explorer ce qu’on peut faire mais je n’irai sans doute pas jusque la pour le moment.
Par contre au fur et a mesure je me rends compte que ce logiciel va tres loin et, hormis un souci d’affichage sur ma tablette a cause des onglets chromes qui ne se cachent pas en plein ecran, je serais susceptible de créer une interface plus poussée pour concurencer mon interface lemur !

**Comment by Adopo** [comment]
Je suis d’accord. Ca fait vraiment plaisir d’avoir découvert ce soft et le travail de Jean-Emmanuel.
J’ai commencé a refaire mon interface lemur avec open stage control. J’ai fais 2/3 tests et je penses que je peux réussir a faire  tout ce que j’avais fait sur lemur. Ensuite je verrais comment aller plus loin !

**Comment by Adopo** [comment]
Il y a encore un truc que je capte pas. Comment fonctionne exactement les /edit,/set et /get? J’ai voulu utiliser ca pour qu’une led influence le css d’un push mais j’arrive pas à attaquer mon push. Je n’y arrive pas.

**Comment by cyberic99** [comment]
Est-ce que ca ca ti'aide?
https://github.com/jean-emmanuel/open-stage-control/issues/152#issuecomment-367259026

En gros tu fais un /EDIT/GET sur un widget
Ca te retrourne le tout le widget en json.
Tu le modifies, puis tu le renvoies avec un /EDIT

Est-ce que c'est ca que tu veux faire, ou simplement des /EDIT/SET?

**Comment by Adopo** [comment]
Merci pour l’exemple ca pourra être utile mais ce n’est pas ce que je souhaite faire.
Mais en regardant ton exemple va va me permettre de mieux expliquer.
En fait je souhaite utiliser un widget LED et dans celui la je cherche l’endroit et la syntaxe pour ecrire un /EDIT ou /SET qui influencera un autre wodget, en l’occurence le css d’un autre widget (un push) pour changer sa couleur.
J’imagine qui fait placer le /EDIT dans la partie OSC des option du widget let mais pour l’instant ce que j’ai essayé ne fonctionne pas.

**Comment by cyberic99** [comment]
je comprends pas, c'est une led qui réagit en OSC et qui applique sa couleur à un bouton push, c est ca?

**Comment by Adopo** [comment]
C’est a peu pres ca. Une led qui lorsqu’elle est active control le css d’un push. Pas forcément en lui donnant sa couleur, en lui donnant une couleur quelconque. En l’occurrence un background-color:grey dans mon cas. J’utilise la led comme passerelle mais ca pourrait etre n’importe quoi en intermediaire. Mais ca peut pas etre le push lui meme car il envoi deja un message osc précis différent de ce qui doit etre recu pour déclencher ca.

**Comment by Adopo** [comment]
Peut etre qu’un push est plus adéquate si une les ne renvoie pas forcément d’osc

**Comment by cyberic99** [comment]
Genre comme ca?
Tu n'as pas besoin de /EDIT pour ca.
Ou alors j'ai mal compris ce ue tu voulais
[led_push_color.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1743989/led_push_color.json.txt)

**Comment by Adopo** [comment]
Ah d’accord. En fait dans le css tu mets une condition qui surveille l’état de la led, pas bête !
Ouep ca marche dans mon cas ! Merci !
J’ai trop tendance a avoir le reflexe envoyé une info quelque part alors que parfois surveillée l’état est plus facile.
Et si un jour j’ai a utiliser un edit dans un widget. Déjà, est ce que c’est possible? Et si oui comment? Est ce necessaire aussi car en meme temps si en surveillant des idées ont peut toujours s’en servir ca ne sert pas forcément au sein du logiciel.

**Comment by jean-emmanuel** [comment]
Merci pour ton aide @cyberic99 . En effet, les commandes générales type `/EDIT` sont plutôt pensées pour être utilisées depuis des scripts externe, tu peux faire en sorte qu'un widget envoie ses messages à l'interface qui le contient propre client avec la cible (target) spéciale "self", mais honnêtement je ne pense pas que ce soit une bonne approche.

**Comment by Adopo** [comment]
D’accord. Merci pour toutes ces astuces à vous deux !

**Comment by jean-emmanuel** [comment]
@Adopo : tu peux essayer d'ajouter la page de la demo sur le bureau de ton ipad et me dire si ça se lance en plein écran ? (http://openstagecontrol.herokuapp.com)

**Comment by Adopo** [comment]
Oooh trop bien ! J’ai pas encore testé avec l’ipad mais avec l’iphone ca marche nikel ! Je te tiens au courant pour l’ipod !

**Comment by Adopo** [comment]
Ipad*

**Comment by Adopo** [comment]
Alors ma journée fut plus remplie que prévue et je n’ai pas eu le temps de trainer sur mon ipad. Par contre sur téléphone j’ai remarqué une chose, quand on mets le liens en signets si je verouille la rotation ca se met automatiquement en vertical comme dans safari. Et malheureusement je sais que dans dolphin on peu réglé ca mais possible que ca soit directement lié au navigateur auquel cas en signet ca ne fonctionnera pas.
Peut etre une solution un peu farfelu, avoir une option « mode paysage » ou « orientation » dans open stage control permettant de faire en sorte que l’interface s’affiche avec 90% de rotation. Enfin, qu’elle s’affiche en biais quoi. Que X devienne Y et vice versa. Je sais pas si j’ai été clair ^^

**Comment by jean-emmanuel** [comment]
Pas possible pour la solution farfelue malheureusement, trop compliqué à gérer techniquement. Si ça marche bien avec Dolphin tant mieux, tu peux aussi tenter de forcer le mode paysage mais ça à l'air d'être un problème connu sur iOS. Voilà quelques techniques lues sur reddit : 

> Much simpler way to lock any landscape compatible apps: 1. Lock rotation 2. Go to fullscreen youtube video 3. Open siri and ask it to open desired app 4. ??? 5. Profit!

>1. Turn phone to landscape
>2. Press lock
>3. That's it.

(https://www.reddit.com/r/iphone/comments/4lcwej/there_is_a_way_to_lock_landscape_mode/?st=je41ol0d&sh=3bbfdd79)

**Comment by Adopo** [comment]
Je me doutais que ma solution était trop farfelue pour être réalisable. Malheureusement ca marche finalement à moitié sur dolphin. En effet ca marche pour une application avec juste des boutons mais si il y a un slider le fait de glisser le doigt fait sortir du plein écran sur iphone (alors que non sur tablette).
Sinon j'ai essayé ton lien sur ma tablette, ca fonctionne nickel ! Du coup pour le moment il faut attendre une mise à jour pour en bénéficier c'est ca?

**Comment by Adopo** [comment]
PS : j'ai testé les astuces du lien que tu m'a filé, ca ne fonctionne pas. Je vais continuer à faire des recherches. Si un moment je trouve une solution je te la transmettrais

**Comment by jean-emmanuel** [comment]
Ok, les versions d'iOS diffèrent peut être entre ton iPhone et ton iPad ? Si tu peux préciser quelle astuce marche pour quelle version j'ajouterai ça à la FAQ.

**Comment by jean-emmanuel** [comment]
Je ferme le ticket, n'hésite pas à en ouvrir un autre si besoin.
