### ISSUE TITLE
Filtered dropbown/switch: is it possible?

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#161]
I'm just asking about the feasibility of this:
Suppose that I have a list of items ie a dropdown or in a switch
There is a 'full' version of the widget, containing all possible values.
Is it possible to display a dropdown/switch, which would have its entries filtered by a text widget?

It there a possibility the generate the 'values' property from inside mathjs, by outputing a dictionary, or calling the map() function?

I tried to put some mathjs stuff in the values, with no success...
like this for instance:
```
{
  "a": 1,
  "b": 2,
  "c": 3,
  "@{input_1}": 5
}
```
I am just asking if it is possible already, I might have missed a step ...
And this processing can be done server side as well anyway.

Thank you

**Comment by cyberic99** [comment]
Wow that could be a huge feature, as we would be able to create dropdowns dynamically with no action on the server.
Adding a value taken from an input, for instance, would be very useful.

So you would have to put this in the value field?

Would it work also to assign a value to a text, for exemple, by pressing a push button?
(and the value would stay even after the button release)
```
@{push_1} ? object = 3 : "";
```

**Comment by jean-emmanuel** [comment]
> Wow that could be a huge feature

It's already there actually

> Would it work also to assign a value to a text, for exemple, by pressing a push button?

I'm not sure to understand, but basically you can't set another widget's value from a formula.

**Comment by cyberic99** [comment]
> It's already there actually
You said that 'Currently, object keys can't be defined with @{} calls without using formulas, I'll try to fix that' , so you've done it already?

> I'm not sure to understand, but basically you can't set another widget's value from a formula.
OK but can I do the other way around:
An text field would take the value of say a fader when a button is pressed.
So when the button is pressed, the text 'value' would return 10
and when the button is not pressed, it would not return anything.
So that the text would still say 10 even after the push is released

**Comment by jean-emmanuel** [comment]
> Currently, object keys can't be defined with @{} calls without using formulas

Translates to "pour l'instant, on ne peut pas definir les noms des propriétés d'un objet avec la syntaxe `@{}` _à moins d'utiliser_ les formules. 

> OK but can I do the other way around [...]

Désolé mais ça reste très confus... peut-être en français ? J'ai l'impression que ça revient à #159

**Comment by cyberic99** [comment]
oops désolé.
du coup en francais:
Ce que je voudrais obtenir:
on a un fader. et un champ texte. Quand on clique sur un push, le champ texte prend la valeur du fader.
La valeur est conservée quand le push est relaché.

Est-ce que c'est possible avec cette feature?
j'ai l'impression que si, lorsque le bouton est à 1, on renvoie @{fader}, et lorsque le bouton est à 0, on ne renvoie rien, ça peut le faire.

Ça permet la même chose que #159, oui mais dans l'autre sens.

**Comment by jean-emmanuel** [comment]
Ok, j'ai capté, ytu peux mettre ça dans le champ de texte:

**`value:`**
```
#{
@{push_1} ? @{fader_1} : @{this}
}
```

**Comment by cyberic99** [comment]
Exactly, that's it, thanks!
It works with a push or a toggle too.
Thanks a lot!
