### ISSUE TITLE
error:ENOENT: no such file or directory, stat ‘/catws/control.html'

### ISSUE THREAD

**Issue by micpool** [jean-emmanuel/open-stage-control#162]
Since downloading 24 something strange as happened,

I can’t load any projects or open a blank project.

I get:

error:ENOENT: no such file or directory, stat ‘/catws/control.html'

I have done the obvious, like erasing cache and plist files.

I have repeated installing all the OSX builds sequentially on a clean machine and everything functions normally with no errors

Clearly,  a file to do with the underlying framework has gone rogue on my main machine , but I am at a loss in finding it.

Thanks

Mic

**Comment by jean-emmanuel** [comment]
Very strange indeed, there is no such file in the sources nor in any of the dependencies... When does the error shows exactly ?

**Comment by micpool** [comment]
When the main window opens instead of being the open stage control window it’s an error window and the error appears in the log at the bottom of the server launch window. This happened when trying to open a previously saved json file or a blank workspace.

I’ve sorted the problem by nuking all preferences and caches  that were modified when the program was launched, but it would be good to know the specific cause so I can sort it out in a more precise way if it happens again.

Mic

**Comment by jean-emmanuel** [comment]
> I’ve sorted the problem by nuking all preferences and caches  that were modified when the program was launched

Do you remember what you had to remove precisely to get it fixed ?

**Comment by micpool** [comment]
No, I started off doing it one file at a time, but in the end just trashed any preferences and caches that had anything to do with Electron or Chrome.

If it happens again I’ll try to be more methodical.

Mic

**Comment by jean-emmanuel** [comment]
Ok maybe it was just an odd side effect due to chromium's version update, I haven't found anything relevant about a `control.html` file, we'll see if it happens again next time I update the engine's version.

Closing for now, feel free to reopen if it happens again.
