### ISSUE TITLE
[windows] glitches

### ISSUE THREAD

**Issue by ABadoil** [jean-emmanuel/open-stage-control#163]
Since the version V0.24.0, the app  doesn't open correctly. Some widget isn't fully loaded ,like in the picture for the both text widget. I run open-stage-control on windows x64.
![image](https://user-images.githubusercontent.com/16114066/36434808-3a9e83c0-1660-11e8-9e89-526ae48cf23d.png)

**Comment by jean-emmanuel** [comment]
What client browser are you using ? The built-in one ?

**Comment by ABadoil** [comment]
Yes, the build one for win32 x64.

**Comment by jean-emmanuel** [comment]
Could you upload your session file (change the extension to .txt, .json won't upload here).

**Comment by ABadoil** [comment]
Hear my session file.
[dario-control.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1752325/dario-control.json.txt)

**Comment by jean-emmanuel** [comment]
Thank you, nice panel ! 

Does the problem occur when accessing the interface with google chrome (http://127.0.0.1:8080)  ? 

I have not managed to reproduce the bug yet, could you please describe more precisely how you launch o-s-c and open your session ?

**Comment by ABadoil** [comment]
It's works with the online demo...
I launch with a .bat with the following line command : 
`open-stage-control\dist\open-stage-control-win32-x64\open-stage-control.exe --debug true --load dario-control.json --port 6969 --send 10.155.165.231:6969 --custom-module dario-module.js
`
I also use a custom module.
[dario-module.js.txt](https://github.com/jean-emmanuel/open-stage-control/files/1757727/dario-module.js.txt)

**Comment by jean-emmanuel** [comment]
Thanks, it works fine here. Just to be sure, you are using v0.24.2, right ?  Can you try to access 127.0.0.1:6969 with google chrome and tell me if the glitch is there ?

**Comment by ABadoil** [comment]
I tried and the glitch wasn't here.. I made a video with the glitch, how can send you it?

**Comment by jean-emmanuel** [comment]
Ok, so you are actually building the app yourself from sources, we are getting somewhere ! :)
Looks like a Elctron+Windows bug, hopefully it won't be there in next release as, can you:
- edit `package.json` in sources and replace `"electron": "~1.8.2"` with `"electron": "2.0.0-beta.1"`
- run `npm install`
- run `npm run package`
- launch the new packaged app

**Comment by jean-emmanuel** [comment]
Also, since you're on windows, if you have a minute:  #171

**Comment by ABadoil** [comment]
Yes, it's work on v0.24.2!

**Comment by jean-emmanuel** [comment]
You mean when built with electron 2.0.0  ?

**Comment by ABadoil** [comment]
Yes! On v0.24.2 with electron 2.0.0.beta.1. I have no glitch.

**Comment by jean-emmanuel** [comment]
Ok cool, I'll wait for a stable electron release before upgrading it in open-stage-control though, thanks for your feedback.

**Comment by jean-emmanuel** [comment]
Just in case, would you mind rebuilding with electron `1.8.2` (it might as well have been a cache problem on your side) ?

**Comment by jean-emmanuel** [comment]
Feel free to reopen if the issue happens again.
