### ISSUE TITLE
Feature Request: Startup fullscreen

### ISSUE THREAD

**Issue by ABadoil** [jean-emmanuel/open-stage-control#164]
Is it possible to add an command-line option to open the fullscreen app directly? Like '-f --fullscreen'.

**Comment by jean-emmanuel** [comment]
Good idea !

**Comment by jean-emmanuel** [comment]
Done, add `--fullscreen` command-line option, it works only for the default client gui though (it's not allowed by regular browsers without any user interaction). Will be included in next release.

**Comment by ABadoil** [comment]
Oh perfect! Thanks!

**Comment by jean-emmanuel** [comment]
-> v0.25.0

**Comment by cyberic99** [comment]
on browsers, the user must click on a button to activate the fullscreen mode.
Would it be possible to add a switch that would add a big 'fullscreen' button in front of the interface?
it is not so practical to click on the tiny hamburger button of the editor

Or a javascript event that we would bind ourselves to a button?

Thx
