### ISSUE TITLE
Ask for confirmation when leaving to prevent data loss

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#165]
Je ne sais pas si c’est moi et mes habitudes mais j’ai un petit souci avec le système de sauvegarde. Ça fait deux fois que j’ai le réflexe de sauvegarder par raccourci (commande+s sur mac) et que je ne penses pas a sauvegarder mon projet et je quitte. Et moi n travaille de la journée est perdu.
Ca serait utile de pouvoir sauver par raccourci ou au moins avoir un message quand onquitte sans sauver.

**Comment by cyberic99** [comment]
ha oui pas de bol...
moi ce qui m est arrivé c est de faire load a la place de save, et la non plus y a pas de confirmation, ca perd les modifs en cours...

**Comment by jean-emmanuel** [comment]
Bonne idée!

**Comment by jean-emmanuel** [comment]
C'est ajouté, pour l'instant c'est basique : si l'éditeur à été activé au moins une fois, l'appli demandera systématiquement confirmation avant de rafraichir/quitter la page. Si #158 avance, il y aura moyen de détecter plus précisement si la session à été sauvée.

note: ça ne marche pas sur iOS

**Comment by jean-emmanuel** [comment]
Included in v0.24.3
