### ISSUE TITLE
OSC In and Out

### ISSUE THREAD

**Issue by micpool** [jean-emmanuel/open-stage-control#167]
I have a setup with a fader widget whose value is used in an  input widget formula.
The input sends it's output to an OSC address

If I move the fader within Open Stage Control  the OSC transmits from the Input widget 

If I move the fader by sending an OSC message from outside the program to fader_1, the fader moves, the input widget updates but no OSC is sent from the input widget.

How do I sort this?

Thanks
Mic

[OSCinOut.json.zip](https://github.com/jean-emmanuel/open-stage-control/files/1754711/OSCinOut.json.zip)

**Comment by jean-emmanuel** [comment]
Updating a widget's value by sending an osc message to its address does make it send its osc message in return, you can use the [`/SET`](http://osc.ammd.net/extras/remote-control/#set-target-id-value) command to do that.

**Comment by micpool** [comment]
Thanks that works great
