### ISSUE TITLE
Sound to osc

### ISSUE THREAD

**Issue by ManuelWaldmann** [jean-emmanuel/open-stage-control#168]
Hello,

A nice feature would be a sound widget.
This Widget shows the input from Soundcard or mic or something and you could configure at what bandwith and level an OSC command will be send.
And the widget can analyze the beats per minute and sends in tact an OSC command.
And you can turn off and on the widget.

Best wishes,
Great work my friend,

Manuel

**Comment by jean-emmanuel** [comment]
Hmm, this is the kind of things I wan't to avoid implementing actually, as imho separation of concerns is the key to a stable workflow. O-S-C receives and sends control, not audio ;)
