### ISSUE TITLE
Congratulations !

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#169]

**Comment by Adopo** [comment]
Bon, je suis pas encore a l’aise dans github et je sais que ici c’est pour les bugs. Et en plus j’ai posté mon messages sans mettre le contenu ahah.
Mais bon je voulais juste te félicité pour ton teavaul.
J’ai utilisé ton app pour la première fois en ateliers où des gamins comme des adultes geek ce sont amusé a se connecter à mon réseau et on utilisés leur navigateur pour controler des boucles de beatboxs que j’avais faite et ca les a éclaté. Ton app est une révolution et j’en ai beaucoup parlé aujourd’hui.
Voila je tenais juste a tirer mon chapeau !

**Comment by Adopo** [comment]
Ah, et si tu doutais sur appli ou pas. Cette aprem j’ai e la preuve que tu es sur la bonne voix !
Et pour info sur ios il y a le navigateur dolphin qui fonctionne bien. Je sais pas si il y a des bjgs en fonction des widget mais pour le moment tout a bien fonctionné et l’appli propose un mode paysage avec juste la fleche retour sur telephone et deux mini icone sur tablette. Plus de barres d’onglet. Et en plus on peu verrouiller en paysage meme sur téléphone !

**Comment by jean-emmanuel** [comment]
Trop cool merci beaucoup ! J'ai fais des essais pour le plein écran avec la technique du scroll et ça marche pas terrible mais par contre maintenant tu peux ajouter l'adresse de ton serveur à l'écran d'accueil et l'appli se lance en plein écran (la barre de status du système apparaît en transparence en haut, à voir si il vaut mieux lui laisser sa place normale).
