### ISSUE TITLE
Bitwig support

### ISSUE THREAD

**Issue by kdejaeger** [jean-emmanuel/open-stage-control#170]
Hi, I was looking into way's to control bitwig studio. Someone made a TouchOSC template like this one : https://imgur.com/a/jbFSi . Unfortunately there seem bugs in the TouchOSC implementation and the developers barely react to any questions/issues.

Would it be possible to use this project for bitwig? Bitwig defines an incoming and outgoing port for OSC communication.

**Comment by jean-emmanuel** [comment]
I'm not a bitwig user myself but it is definitely the kind of application Open Stage Control is meant to work with. There's no premade session for that though so you'll have to dive deep into the documentations of both apps to build one:

- bitwig osc script - https://github.com/git-moss/DrivenByMoss/wiki/Open-Sound-Control-(OSC)
- open stage control - http://osc.ammd.net

**Comment by kdejaeger** [comment]
Nice. With _session_ you mean, there's not json template yet for the open stage control app?

**Comment by kdejaeger** [comment]
I did a quick test with a toggle button and I could send the /play request to bitwig. I could also press the play button in bitwig and the button toggle went on. So the bidirectional stuff seems to be working. These were my settings:
![image](https://user-images.githubusercontent.com/279268/36675950-a10ab3b4-1b0a-11e8-9227-f14acccfac49.png)
Pretty good start :).

**Comment by jean-emmanuel** [comment]
Cool ! I'd be glad to help if you have issues with o-s-c while building your interface.

**Comment by kdejaeger** [comment]
Hi! On windows 10, I cannot get the connection to work. I used exactly the same settings. Starting the server does not result in any debug messages being shown at the bottom of the 'Open Stage Control' window. In Linux I remember it was showing the connection was successful.

**Comment by jean-emmanuel** [comment]
Unfortunately the console doesn't work on windows, I haven't found a proper fix yet.

**Comment by kdejaeger** [comment]
Finally, I got it working by removing all OSC plugin entries in bitwig and keeping just 1 active. Somehow, that was the problem.

**Comment by jean-emmanuel** [comment]
If you have the ability to build o-s-c from sources, I could use some testing on the windows/console issue: https://github.com/jean-emmanuel/open-stage-control/issues/171

**Comment by kdejaeger** [comment]
I think so. Somewhere tomorrow
