### ISSUE TITLE
[windows] no console

### ISSUE THREAD

**Issue by jean-emmanuel** [jean-emmanuel/open-stage-control#171]
**What's expected**
The launcher's gui should print debug messages in its bottom section.

**What's happening**
Console messages are swallowed on Windows, nothings is printed.

This could fix it: https://github.com/cypress-io/cypress/commit/b6d1481bd97854c9ec9a80c2e3cbea3f99a61aee
(found @ https://github.com/cypress-io/cypress/issues/977)

**Comment by jean-emmanuel** [comment]
Maybe-fix pushed, waiting for feedback from windows users.

**Comment by jean-emmanuel** [comment]
The fix (?) is included in v0.24.3, no need to build from sources to test.

**Comment by ABadoil** [comment]
I try with the new release and the debug console is working.

**Comment by jean-emmanuel** [comment]
Awesome, thanks.

**Comment by kdejaeger** [comment]
It works.
