### ISSUE TITLE
Theme configuration does not support spaces in filepaths

### ISSUE THREAD

**Issue by kdejaeger** [jean-emmanuel/open-stage-control#173]
Theme is a multi value field (array). The string is splitted with a space ' '.
Because of this it's not really possible to put a filepath in it when you have a folder with a space in the path.

I think it's not possible to support theme paths AND theme names in 1 configuration option.

**Comment by jean-emmanuel** [comment]
The command-line parser works fine with that (you can enclose your path in quotes or escape space characters), but the launcher window happens to do it wrong, will fix. Thanks for your feedback !

**Comment by jean-emmanuel** [comment]
Fixed in git, quoted items can contain spaces.

**Comment by jean-emmanuel** [comment]
-> v0.25.0
