### ISSUE TITLE
Double click -> OSC value

### ISSUE THREAD

**Issue by kdejaeger** [jean-emmanuel/open-stage-control#174]
Hello, I saw in bitwig you can double click on a knob, and it would go back to it's default value. (A default value which you can update any time in bitwig.) Probably we can make a OSC url to expose this.

How could we consume this dynamic osc value so that it can be used when double tapping and set a knob to this default value that comes from bitwig?

**Comment by kdejaeger** [comment]
Actually, I come to think of it. A URL instead of a 'value' field would be enough. I remember there's a 'setdefaultvalue' in bitwig. So all we need more on a double click is to send 1 osc message instead of filling in the default value.

BTW, shouldn't 'value' be called 'default value' in open stage control?

**Comment by cyberic99** [comment]
You can still change the default value like this:
```
oscsend  osc.udp://localhost:8080 /EDIT ss knob_1 '{"value": 1}'
```
After that , if you have checked ``doubleTap`` and that you double click, the knob will be set to the new value you defined
The problem is that setting the 'value' property also changes the widget current value...

> BTW, shouldn't 'value' be called 'default value' in open stage control?

I agree with that
For now you have ``value`` and ``_value``, this can be confusing too...

**Comment by jean-emmanuel** [comment]
Good point, the `value` property was initially meant to represent the initital value only, but now it's a bit ambiguous. The most obvious solution is to add a `initialValue` property that only serve this purpose. 

@kdejaeger I assume by URL you mean an osc address to change the widget's parameter. You can either 
- use a dedicated widget to store the parameter (and update it with its osc address) and use its value using property inheritance
- use the /EDIT command to change the property

The first solution is much more performant when changing dynamic properties.

**Comment by kdejaeger** [comment]
Thank you for your quick responses. Me, I lost the train of though a bit here :). Must be technical debt, I'm not familiar enough yet with everything.

I'm not looking to send/update a default value in bitwig. Just to read it out and consume it when double clicking a know in open stage control. The 'oscsend' example I don't get yet (how to integrate with editor). The first example of @jean-emmanuel I think I get this: so I would create an invisible 'read-only' knob with for instance an OSC url of /device/param/1/defaultValue; it will fetch the value when bitwig pushes it. Then I can consume this widget value into the knob 'value' = (default value) property, which will then be used when double tapping.

**Comment by jean-emmanuel** [comment]
Yes that's the way it used to work, the problem is that the `value` property has come to also affect the widget's *current* value and is now very useful this way. To resolve this ambiguity, I've just pushed a new `default` property that only serve this purpose : setting the initial (as is "when the session is loaded) value. Now the `value` property just allow setting the value dynamically (via inheritance/maths).

`value` and `_value` are now the same thing -> https://github.com/jean-emmanuel/open-stage-control/commit/72e724aa85aadb97251c690e1f7ce95b28d54c3e, this should clarify things a bit.

**Comment by jean-emmanuel** [comment]
Long story short, from now on, the answer to your initial request is:

- create a widget to hold the doubleTap value (can be a knob or an input for example), let's say its `id` is `defaultValue` and its address is `/device/param/1/defaultValue`
- set your knob's `default` property to `@{doubleTap_1}` (same as `@{doubleTap_1.value}`)
- change the default value by sending it to `/device/param/1/defaultValue`
- profit !

**Comment by kdejaeger** [comment]
Looks like there was no url to get the default value in bitwig. However, there is a url to trigger a reset of the parameter. 

/device/param/xxx/reset

So I would still need to trigger an OSC url to reset the value on double click.

**Comment by jean-emmanuel** [comment]
Having the knob itself send this message on doubleTap is not possible. As of 02523903c8b31af69e26cb21a4c767234bece665, you can solve this by using an additional input widget that sends its osc message only when the knob's value is equals to its default value (ie when double tapped). See attached session file.
[knob.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1777394/knob.json.txt)

**Comment by kdejaeger** [comment]
I checked it out, tnx for the example. It works as well. It still took me half an hour to get it though.

I don't like this solution because of several reasons:
- I find the implementation to tricky to maintain and understand
- I have to somehow make the reset input invisible because I don't really need it
- When I manyally turn the knob to it's default openstagecontrol value (let's say all the way to the left, at 0), it triggers the reset's input OSC request, which puts the know into the default bitwigs value. So I cannot set the knob at value 0 anymore! :)

**Comment by jean-emmanuel** [comment]
Double tapping a knob resets it to its default value, so maybe the answer is you can't do it this way since bitwig doesn't expose this value (you'd still need an extra widget to receive in anyway). A push button sending the reset message seems to be the best answer.

**Comment by jean-emmanuel** [comment]
I'm giving some more thought on adding an optionnal specific address for sliders' doubletap event (like `touchAddress`), I'll try it soon.

**Comment by jean-emmanuel** [comment]
You should be able to set `doubleTap` as an osc address too now, to make the widget send a special message instead of resetting its value.

**Comment by kdejaeger** [comment]
I think so, I think I'll have to simply add a "reset" button.

**Comment by kdejaeger** [comment]
Pheew :)
