### ISSUE TITLE
Bug rangement tab

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#175]
Hello. Il y a un petit bug sur le rangement des Widgets dans un tab. En effet quand on est dans le tab et qu'a droite il dans l'édition du tab il y a les différents widgets, on peut les glisser vers le bas pour faire le rangement mais on ne peut pas les glisser vers le haut.

**Comment by jean-emmanuel** [comment]
Yes, trouvé, c'est reglé pour la prochaine version !

**Comment by Adopo** [comment]
Bien joué !

**Comment by jean-emmanuel** [comment]
-> v0.25.0
