### ISSUE TITLE
Feature request: text-align css shortcut

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#176]
@jean-emmanuel: you had given me a tips, and I think that previously, if I had ``.input {text-align:left;}`` in the css property of a text field, it would align the text to the left.
It does not seem to work anymore...
Could you please add support for it? 
This is useful when you have a very long text, sometimes it is better to see the first characters rather than the ones in the middle...

Thank you

**Comment by jean-emmanuel** [comment]
New props added for next release !

**Comment by jean-emmanuel** [comment]
-> v0.25.0
