### ISSUE TITLE
Besoin d'aide - envoyer a une adresse OSC différente en fonction d'une condition

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#178]
Hello. Je voulais savoir. Est ce que c'est possible de pouvoir utiliser par exemple un push pour envoyer en fonction de l'état d'un autre widget à une adresse  OSC différente. 
J'ai essayer de mettre quelque chose du genre dans l'adresse OSC
 #{@{widget}=="valeur"?"/message/1":"/message/2"} 

Mais ca n'a vraiment pas l'air de fonctionner ca bloque même tout envoi d'OSC du programme.

**Comment by Adopo** [comment]
Ah, et si il y a un truc pour réécrire cette condition, est il possible aussi d’ecrire une condition pour plus de 2 envoies différents?

**Comment by jean-emmanuel** [comment]
Ta première version devrait marcher, mais il y a un petit bug que j'em vais régler de ce pas (la formule ajoute un espace au début de l'addresse qui la rend invalide).

> Ah, et si il y a un truc pour réécrire cette condition, est il possible aussi d’ecrire une condition pour plus de 2 envoies différents?

> Ah, et si il y a un truc pour réécrire cette condition, est il possible aussi d’ecrire une condition pour plus de 2 envoies différents?

```
#{
address = "";
@{widget} == 1 ?  address = "/1" : 0;
@{widget} == 2 ?  address = "/2" : 0;
#etc, puis on retourne la variable address (pas de point-virgule)
address
}
```

**Comment by Adopo** [comment]
Ah d’accord parfait ! Alors c’était pas une demande mais la découverte d’un bug :-).
Cool. Faudra que je vois comment récupérer directement le programme sur github. J’ai vu ta réponse sur l’autre post. J’ai regardé vite fais mais pour l’instant j’ai paq compris grand chose ahah

**Comment by jean-emmanuel** [comment]
J'ai parlé un peu vite, en fait ta ton code marchait très bien...

**Comment by Adopo** [comment]
En effet il y avait un espace. Ca marche !
Je vais tester la version a plus de 2 possibilités. Quand tu dis on retourne la variable. C’est genre return adress?

**Comment by Adopo** [comment]
J’ai essayé un truc mais ca ne marche pas. A ton avis quelle serait l’erreur?

#{
address="";
@{state_1_1}=="cleared"?"/node/looper1/tracks/0/recorplay" : 0;
@{state_1_1}=="recording"?"/node/looper1/tracks/0/recorplay" : 0;
@{state_1_1}=="stopped"?"/node/looper1/tracks/0/recorplay" : 0;
@{state_1_1}=="playing"?"/node/looper1/tracks/0/stop" : 0;
return address
}

**Comment by jean-emmanuel** [comment]
remplacer `return address` par `address`

**Comment by Adopo** [comment]
Il y n’y a aucune autre erreur dans ce que j’ai copier. Car j’ai enlevé le return et ca le fonctionne pas

**Comment by Adopo** [comment]
Et cette fois pas d’espace avant le #. Dois je retirer tous les retours à la ligne?

**Comment by Adopo** [comment]
En fait je suis en train de me dire que ton code ne peux pas fonctionner.

Car si par exemple la première condition est la bonne, l’adresse est remplacée par un zero dans la condition suivante.

Dans un autre endroit du push pour le label j’ai fais :
#{@{state_1_1}=="playing"?"^square":""}
#{@{state_1_1}=="stopped"?"^play":""}
#{@{state_1_1}=="cleared"?"^circle":""}
#{@{state_1_1}=="recording"?"^circle":""}
#{@{state_1_1}=="willPlay"?"^play":""}
#{@{state_1_1}=="willRecord"?"^circle":""}

C’est moins élégant mais ca a l’air de fonctionner

**Comment by jean-emmanuel** [comment]
Ah j'vais mal lu, il manquait un `address=` dans chaque ligne...
```

#{
address="/default";
@{state_1_1}=="cleared"? address="/node/looper1/tracks/0/recorplay" : 0;
@{state_1_1}=="recording"? address="/node/looper1/tracks/0/recorplay" : 0;
@{state_1_1}=="stopped"? address="/node/looper1/tracks/0/recorplay" : 0;
@{state_1_1}=="playing"? address="/node/looper1/tracks/0/stop" : 0;
address
}
```

**Comment by Adopo** [comment]
Merci ! c'était ca et ca fonctionne. c'est puissant !

Encore une question, la par exemple mon widget ciblé et state_1_1. Mais admettons que je me situe dans state_1_1 et que je veux changer par exemple la couleur de ce widget en fonction de sa propre valeur. Je ne peux apparemment pas le cibler avec un @{state_1_1}. Comment puis je faire?

**Comment by jean-emmanuel** [comment]
Il faut utiliser `@{this}`

**Comment by Adopo** [comment]
Ok parfait ! J’ai encore une question. Désolé c’est tellement puissant que j’essaie de voir jusqu’ou on peut aller.
Est ce que dans un « if » je peux mettre deux conditions? Si oui quelle est la syntaxe?
Genre est ce qu’un truc de ce genre fonctionnerait :
@{state_1_1}=="playing" && @{option}== ="mute" ?"/node/looper1/tracks/0/mute" : 0;

**Comment by Adopo** [comment]
J’ai testé écrit comme c’est écrit là ça ne fonctionne pas

**Comment by jean-emmanuel** [comment]
La syntaxe des formules est proche du javascript mais comporte quelques différence : http://mathjs.org/docs/expressions/syntax.html#operators
-> && et || s'écrivent "and" et "or"

C'est un peu perturbant, à voir si je peux ajouter ça éventuellement...

**Comment by Adopo** [comment]
Ok ca fonctionne ! Trop bien. C’est pas dérangeant que ca soit and et or quand on le sait ;-)
