### ISSUE TITLE
Has the address parser a depth limitation?

### ISSUE THREAD

**Issue by git-moss** [jean-emmanuel/open-stage-control#180]
I use the following address on 8 tracks:

/track/@{parent.variables.n}/send/1/name

When "/track/8/send/1/name" is received with an empty name value, all 8 texts are set to unknown.

This is on Windows 10 64 bit.

**Comment by jean-emmanuel** [comment]
> Has the address parser a depth limitation

nope ;)

Does your widget have any `preArgs` set ? If yes, these must also match for the incoming message to be received.

You can drop your session file here.

**Comment by git-moss** [comment]
I have no preArgs set. The problem is not that the message is not matched. It is matched by ALL track widgets but should only be matched by track 8.

**Comment by git-moss** [comment]
Seems I cannot upload the file (even a ZIP). I put it here: http://mossgrabers.de/stuff/OSC4Bitwig-Test.zip

**Comment by jean-emmanuel** [comment]
Alright, you have to add `@{parent.variables.n}` somewhere (anywhere) in the text widget `id`, so that the cloned widgets don't have the same (widgets with the same id are synced).

**Comment by git-moss** [comment]
Thanks a lot! I did only look at the address.
