### ISSUE TITLE
Can colors be set based on an OSC command?

### ISSUE THREAD

**Issue by git-moss** [jean-emmanuel/open-stage-control#181]
I'd like to set a track strip to the color of a track. Is that possible?

The message is like:

/track/{1-8}/color   with RGB(r,g,b). r,g,b = 0..1

**Comment by jean-emmanuel** [comment]
Widgets don't expose their properties directly, they listen on only one address+preArgs at a time. You have 2 ways to do that:

- use the [`/EDIT`](http://osc.ammd.net/extras/remote-control/#edit-id-options) command to change the widget `color` property
- use another widget that holds the color in its value and inherit from it in the color property

**Comment by git-moss** [comment]
The first is not an option for me since it would mean to change the server.

For the second option: How do I assign a command to a widget so that it changes its color?
E.g.:
/track/3/color RGB(0.2,0.8,1)

**Comment by kdejaeger** [comment]
Nice to see Mr. Moss is building something as well :).

**Comment by jean-emmanuel** [comment]
- create an input widget with `address` = `/track/3/color`, and `id` = `color_3`
- set the widget's `color` to 
```
#{
print("rgb($r,$g,$b)", @{rgb})
}
```

**Comment by git-moss** [comment]
Thanks for all the hints! Since Bitwig does currently not support the sending of color type the print-trick did not work.
However, I found an easier solution: I send now rgb(255,255,255) to the input widget and directly assign this to the value-property of a RGBLED. This works fine in the test case. But now when I try to integrate that into a mixer (with clones) the linking seems not to work:
@{input_track_color_@{parent.variables.n}}
Should this double linked variable work?

**Comment by Sebastian-blu** [comment]
oh man i hope you get that going moss ;-) the plots page might have some clues here... not that I know how to decipher them

http://openstagecontrol.herokuapp.com

**Comment by jean-emmanuel** [comment]
> @{input_track_color_@{parent.variables.n}}
Should this double linked variable work?

Nested property calls are not supported yet.

I forgot to mention you can also write a custom module for filtering in/output message and send `/EDIT` commands from here, it's a different approach, more code, less widgets. http://osc.ammd.net/extras/custom-module/

**Comment by cyberic99** [comment]
@git-moss you can't have 'recursive' @{..} values... I had the same problem here: https://github.com/jean-emmanuel/open-stage-control/issues/166#issuecomment-368460207

I think it would be useful too.

**Comment by git-moss** [comment]
Yes, would be a useful addition.

Seems I was thinking too complicated: Now with my change to rgb(...) I do not need the workaround with the input module! I can directly assign it to the rgbled.
