### ISSUE TITLE
Improvements for startup window

### ISSUE THREAD

**Issue by git-moss** [jean-emmanuel/open-stage-control#182]
1) On my system (Windows 10 64 bit) after startup the Save and Start buttons are not visible. I first have to enlarge the window or scroll down.

2) After closing the window with the user interface, the Save and Start button should be displayed again in the control window.

3) It would be nice to have a Clear and Copy function for the log window.

**Comment by jean-emmanuel** [comment]
1. Fixed already -> next release

2. Closing the window doesn't shut the server down, as it is meant to stay accessible to the other clients. The window is just the default client. However, I see your point, needs some tinkering.

3. Clear: good idea
3. Copy: you mean like a right-click context menu ?

**Comment by git-moss** [comment]
First, thanks for all your quick feedback!

4) -> Yes, like "copy to clipboard".

**Comment by jean-emmanuel** [comment]
1. -> v0.25.0

**Comment by jean-emmanuel** [comment]
3.4. -> in git

**Comment by jean-emmanuel** [comment]
2. -> in git: I've added an item in the context menu to relaunch the app/launcher. Feels like a good compromise with my previous statement.

**Comment by jean-emmanuel** [comment]
-> v0.28.0
