### ISSUE TITLE
How to dynamically reload scss

### ISSUE THREAD

**Issue by kdejaeger** [jean-emmanuel/open-stage-control#185]
I saw you added an orange theme.
Maybe I should also code my theme further in SCSS.
But how do I get it compiled and updated at run time, just like the theme property does?

**Comment by jean-emmanuel** [comment]
if you write it in scss, put your scss file in src/browser/scss/themes/, and run `npm run watch-css`, your theme will be watched and compiled automatically to a css file located in app/browser/themes/ (css files in this directory can be selected from the theme option by their name, without .css suffix). If o-s-c's server is running on default http port (8080, osc-port can be different), clients will reload style automatically.

**Comment by jean-emmanuel** [comment]
I did the orange theme as a first step toward a bitwig-like theme (not naming it "bitwig" though as the name/software isn't free). I like what you did with the push and toggle buttons, I will try to add them as tiny themes extensions that could be enabled independently.

**Comment by kdejaeger** [comment]
Ok, it works. I find the orange version better than what I created. In the end mine was to black. It lacked the effects as well that scss made possible.

**Comment by kdejaeger** [comment]
Indeed inverted colors for buttons or toggles that are on, make it much more apparent. Got the idea from the bitwig transport bar.

**Comment by jean-emmanuel** [comment]
I just pushed "alt-buttons" as a theme extension, you can combine it with "orange"

**Comment by kdejaeger** [comment]
I see, nice. It works. One thing I'd also still like is an overall more responsive font-size. I personally have everything at 125% now. But on a small phone it's too big again.

**Comment by jean-emmanuel** [comment]
That would be fixed by using css media queries, until just now a little bug prevent them to be properly parsed though:

Putting this in root's css would increase font-size for screen bigger than 800px only
```css
@media screen and (min-width:800px) {
& {
font-size:125%;
}
}
```
