### ISSUE TITLE
[editor] keyboard shortcuts

### ISSUE THREAD

**Issue by jean-emmanuel** [jean-emmanuel/open-stage-control#186]
- [x] copy
- [x] paste
- [x] undo*
- [x] redo*

* much more complicated... don't expect that soon

**Comment by nesdnuma** [comment]
Please do also add a link between the Delete key and the widget deletion.

**Comment by WillyKaze** [comment]
Could we imagine something like this, in editor mode:
* `Arrow` move the selected widget(s) to 1 grid cell
* `Maj`+`Arrow` move the selected widget(s) to 10 grid cells

It would be pretty awesome to quickly layout the widget like this

**Comment by jean-emmanuel** [comment]
Good idea !

**Comment by jean-emmanuel** [comment]
I made some progress on this today:

`delete`:  delete
`ctrl + c`: copy
`ctrl + x`: cut
`ctrl + v`: paste
`ctrl + shift + v`: paste (n+1)
`arrows`: move (`+ shift` for bigger move)
`alt + arrows`: resize (`+ shift` for bigger resize)

**Comment by NucularJohn** [comment]
Is there any way to assign keystrokes to control whatever we're osc-ing into? i.e. copy/pasting in a daw or similar, or do we have to stick to a MIDI translator?

**Comment by jean-emmanuel** [comment]
@NucularJohn Open Stage Control can only send OSC or MIDI messages (which can be triggered by keystrokes thanks to the `keys` widget), you might be able to convert these messages to keystroke on the receiving end but you'd need a 3rd party to take care of this.

**Comment by jean-emmanuel** [comment]
Surprisingly, it was possible to <s>hack</s> implement the undo/redo feature without much trouble ! This should be included in next release.

`ctrl + z`: undo
`ctrl + y / ctrl + shift + z`: redo

:tada:

**Comment by jean-emmanuel** [comment]
-> v0.36.0
