### ISSUE TITLE
{bug} resizing clone with 8 clones inside cause freeze macOS 

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#187]
hey I was making a clone of a panel with 8 faders and 8 labeles, one original and 7 clones. 

made new clone object next to it
then pointed the widget id to the panel obove
and it populates...slowly
if I resize it then the program freezes up

**Comment by jean-emmanuel** [comment]
Could you upload a session file (add .txt to filename to upload it here), that would freeze when resizing the widget ?

**Comment by Sebastian-blu** [comment]
yeah i worked around it but ill recreate and send to ya later today

**Comment by jean-emmanuel** [comment]
Thank you, it's a tricky bug with nested clones, I'll try to fix it.

**Comment by Sebastian-blu** [comment]
cool thanks for trying. :) if not what about stopping the user from being able to do it as to not freeze them out if changes aren’t saved?

**Comment by jean-emmanuel** [comment]
Preventing a bug to happen and fixing it is very similar ;)

**Comment by Sebastian-blu** [comment]
Lol ok

**Comment by jean-emmanuel** [comment]
Found it, at last ! It was a bad memory leak... :)
