### ISSUE TITLE
Edit field value written in wrong widget

### ISSUE THREAD

**Issue by git-moss** [jean-emmanuel/open-stage-control#188]
1) Edit a value of a property field 
2) Do not confirm the change with Return or by clicking on another input field.
3) Click on another widget
4) The changed text is now written in the newly selected field and not the one in which the change was done.

**Comment by jean-emmanuel** [comment]
Wow, nice one, fixed in git right now !

**Comment by Sebastian-blu** [comment]
cool that was happening to me too

**Comment by Sebastian-blu** [comment]
I'm new to this kind of thing how might I get my hands on the fix? or is it just in the new update whenever that is? no big deal just curious.

**Comment by jean-emmanuel** [comment]
You have to wait for next release (likely soon) or build the app from sources.

The new behavior makes the field change apply to the widget that was previously selected, does it feel natural this way or should the change be discarded ?

**Comment by git-moss** [comment]
That is the expected behaviour. Thanks!

**Comment by Sebastian-blu** [comment]
I agree with moss. I messed up my inputs more the once because of forgetting to hit enter before moving on.
