### ISSUE TITLE
Pinch to zoom macOS 

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#189]
Pinch to zoom is a little too quick, it tends to jump from one zoom extreme to the other really fast. If it could be tamed that might be better. Cheers.

**Comment by jean-emmanuel** [comment]
- does it occur when using chrome as client instead of the default one   
- does the problem occur when zooming with ctrl+scroll instead

**Comment by jean-emmanuel** [comment]
Native zoom is supposed to be prevented anyway to be handled internally , I shall try to disable pinch zoom and make the keyboard shortcut cross platform (ie cmd+scroll on mac)
