### ISSUE TITLE
Out of limits incoming OSC value gives 0 result

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#19]
I have a fader set up in db with max = 10 and min = -200 (-196 = inf on this DAW). Everything works except for right at the bottom of the fader. I am playing with Ardour code right now and using the gain to dB functions for feed back. When I pull the fader in the GUI all the way down I have either -inf or I have -700. In both cases the open stage control fader jumps to 0 rather than min. In my opinion, if the value input is less than min the fader should become min, and if the value is greater than max the fader should be set to max. (I have not tested the over-max situation)

Also, it would be nice (wish list), if the value for the the fader showed the text next to the fader scale. example:"min": {
                                "inf": -200
                            },
Still puts -200 in the editable value field, inf would be nice so that the user sees the same thing on the scale and the value. I will not be upset if this just gets put aside as won't fix though...

**Comment by jean-emmanuel** [comment]
Can you provide a session file for testing ?

**Comment by ovenwerks** [comment]
I am no longer sure what is happening. I think I was looking at one thing while sending another. My fader range looks like this:
"range": { "min": {"inf": -200 },
 "6%": -60, "12%": -50, "20%": -40, "30%": -30, "42%": -20, "60%": -10, "80%": 0, "max": 10 },
Ardour normally gives feedback for fader as gain with range 0-2. (-inf -> +6dB) and so I was adding feedback in dB as well. There are two conversions in Ardour for this fast or accurate. Accurate tracks the GUI fader and fast is off a bit. Anyway, fast ends at -766.792 and accurate ends at "-std::numeric_limits<float>::infinity()" I had my debug set to fast and the OSC I was sending to Accurate. As it turns out  -766.792 is fine, but -std::numeric_limits<float>::infinity() is not. If I on the CLI do: 
oscsend localhost 8100 /strip/gaindB ff 1 -inf
It does the same thing. I think rather than fixing open stage, I will fix Ardour (well mangle really) dB numbers below -192 do not translate to gain and back properly anyway, so I can do an if < before sending. I suspect there may be other controllers with the same issue.

Thank you for looking anyway.

**Comment by jean-emmanuel** [comment]
Ok, I'm closing this then. Note that you can use the `-d / --debug` switch to make OSC print sent/received messages in the console.
