### ISSUE TITLE
Marquee select multiple objects 

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#190]
Hey maybe I missed it but I haven’t been able to select multiple widgets to move them around unless they are in a panel already. I find myself wanting to marquee select. Thanks again

**Comment by jean-emmanuel** [comment]
It wasn't possible, I just pushed that feature, you can try it in the online demo : all selected widgets will be affected by size/position dragging made on the first selected widget. Changes are relative to the first selected widget, if you just wan't to set the same position/size to multiple widgets, you should use the sidepanel instead.

**Comment by Sebastian-blu** [comment]
ok I tried the demo, that works great, how come ctrl click and not shift? just curious, old habit ya know.

**Comment by jean-emmanuel** [comment]
shift click is the default shortcut on mac right ?

**Comment by Sebastian-blu** [comment]
Yeah, oh I forgot that’s not crossplatform standard.

**Comment by Sebastian-blu** [comment]
How would you do it on the touch screen?

**Comment by jean-emmanuel** [comment]
I'll add an exception case for that.

**Comment by Sebastian-blu** [comment]
For touch screen or Mac?

**Comment by jean-emmanuel** [comment]
Nope, for the command+click case. You can't with touch screen.
