### ISSUE TITLE
OSC value of text field is empty

### ISSUE THREAD

**Issue by kdejaeger** [jean-emmanuel/open-stage-control#195]
If a text field receives an empty OSC value, the id of the text widget is shown as the label. Which can be very ugly and long. Can this be defaulted to '' or hidden?

**Comment by jean-emmanuel** [comment]
Should default to `default` in this case, but doesn't, it's a bug. Fixed.

**Comment by kdejaeger** [comment]
Ow didn' t think about that. Nice.
