### ISSUE TITLE
feature: shrinkwrap for containers

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#196]
In particular the modal box would look a lot nicer if it shrinkwrapped to the size of whatever is inside the opened modal box.

Along the same lines... the multitoggle (and perhaps other multi-widgets) the height and width should describe the toggleswitch size and not the overall size. Or there should be two sets of sizes and when the overall size is "auto" then the overall size should be big enough to just include the number of sub-units. Maybe this is already possible by setting the height using some math (number of items * 40)

now, just for fun, I want the matrix value to adjust itself depending on what I send so I can have [1,3] if there are 3 items and [1,5] if there are 5. I am guessing there is a way to do this with math but I am not sure how. In fact I am guessing I could get the modal size to change using some math interaction too. Sort of like a dropdown with checkboxes, but modal makes more sense because more than one toggle can be set while the dialog is open.

I am not sure yet the best way to send this from the DAW.  For the particular application I am looking at now, I could send /address iiii 1 0 1 0 where the 4 toggles are on, off on, off to an input and use some math to set the matrix right and then the values.

Maybe I should request a more comprehensive manual :)

**Comment by jean-emmanuel** [comment]
Hmm I don't think that's doable really, or worth the effort, the whole thing is built the opposite way : children should use percent dimensions to fit their parents' .

> now, just for fun [...]

I'll get back to that later !

**Comment by ovenwerks** [comment]
Sorry, it looks like matrix toggle will not work at all for my application. While I can represent VCAs as an index number, there may be missing indexes :P  If you have an Ardour session and add a few VCAs, each mixer strip will show a "- VCAs -" button under the fader. That is what I am trying to emulate. Ardour uses a dropdown with checkboxes. I can easily get a list like {name, value}, {name, value}, ... via /address sisi... name 1 name 0 ... but the matrix does not allow naming the toggle with anything other than index that I can see.

I could send two messages /select/vca/connected and /select/vca/available and use two dropdowns: "Connect VCA" and "Remove VCA", but that is hacky. Using custom to create a dialog with single toggles would be much nicer, if more painful to create :)  If nothing else comes along this is likely what I will do as I only intend to include this in /select not /strip, so it would only be one. However, I have a feeling I will get to a place where I need this functionality again and then custom starts to get messy.

I am certainly open to suggestions such as using a different widget or whatever. Adding values to the drop down? Adding a "toggle dropdown"? (checkboxdropdown)

**Comment by cyberic99** [comment]
In fact you want a kind of switcher but with toggle buttons instead of a single value, right?
I would have found it useful too (or a matrix toggle that would send a value instead of an index)

for now I create it server side then I use /EDIT...

**Comment by jean-emmanuel** [comment]
Custom module is definately the way to go, I'm open to suggestions on how to enhance this feature ;).
