### ISSUE TITLE
touch screen editor doesn't accept text iOS

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#199]
hey just thought it would be nice to edit on the touch screen tried it but was not able t enter any text.

**Comment by Sebastian-blu** [comment]
moving thins works though

**Comment by Sebastian-blu** [comment]
Well I guess if I try to save on the touch screen I just get a white page of code that starts with “type”: “root”. And I can’t back out of it. So I loose what ever changes I make in touch screen anyhow.

**Comment by jean-emmanuel** [comment]
Text fields bug fixed in git. As for the saving problem it is a known limitaion on ios that might be fixed if #200 gets done one day.

**Comment by jean-emmanuel** [comment]
-> 0.26.1
