### ISSUE TITLE
fader log scale seems backwards

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#20]
Assuming that gain is being plotted by the fader, the range (in Ardour) is 0 -> 2 (-inf to +6 and 1= 0dB) with logscale false, 1 or 0dB is at the centre (linear scale). Setting logscale true would have the expectation that 1(0dB) would move up to about 80% to streach out the area between 0 and -144dB (the limit for 24bit audio) or more practically -90dB. Instead, the 0dB point moves to the 25%(ish) point so that 6dB takes up 75% of the scale and 0 to -90 gets 25% of scale.
Below is a complete fader widget, This for Ardour which has only +6 rather than the more normal +10 or +12. (for a fader that is +12 to -inf use min=0 and max=4) If you look at any mixer you will see that 0db (1 in this example) is at about %80 up. You should be able to see this just by watching the value at the bottom of the fader.

The relevant part of a fader spec is:

                    {
                        "type": "fader",
                        "id": "fade2",
                        "linkId": "",
                        "label": false,
                        "left": 0,
                        "top": 90,
                        "width": 74,
                        "height": 380,
                        "horizontal": false,
                        "css": "",
                        "range": {
                            "min": 0,
                            "max": 2
                        },
                        "logScale": true,
                        "precision": 2,
                        "meter": false,
                        "target": [],
                        "path": "/strip/gainabs",
                        "align": "left",
                        "color": "auto",
                        "preArgs": [
                            2
                        ],
                        "noPip": false,
                        "snap": false,
                        "compact": false,
                        "unit": "gain"
                    },

FYI: the path spec is where Ardour is going for 5.0, feedback works as well with the same path. Not in GIT yet :)

**Comment by jean-emmanuel** [comment]
The log scale is not backwards : it aims to bring higher precision when approaching the upper value. But it seems to me that ardour uses multiple breakpoints for its fader rather than a single log scale : create a fader in OSC log scaled between `-50` and  `6`, you will see the scaling is very much similar to ardour's. Mapping a single log scale (in OSC) to a multiple segment scale (in Ardour) is what doesn't work here I think.
