### ISSUE TITLE
Server side session management

### ISSUE THREAD

**Issue by jean-emmanuel** [jean-emmanuel/open-stage-control#200]

**Comment by jean-emmanuel** [comment]
Client side:
    - export session file locally (current behavior)
    - save on server
    - "save as" on server
    - file saving gui ?

    Server side:
    - feed file saving gui ?
    - keep history system as is
    - add saved sessions to history

    -> ext libs ?

**Comment by cyberic99** [comment]
regarding sessions, would it be possible to have the session name somehow embedded in the zeroconf attributes?
thx

**Comment by jean-emmanuel** [comment]
@cyberic99 since the server can run multiple sessions at a time, no. If you only use one session (ie autoloaded with `--load`), then setting `--instance-name` is fine I think.

**Comment by jean-emmanuel** [comment]
With the additions described in #451, I've decided to drop this feature: I'm not going to develop a remote file browser just to implement "save as".

**Comment by cyberic99** [comment]
> setting `--instance-name` is fine I think

I had forgotten about this feature!

yes it is fine, thx
