### ISSUE TITLE
command for multi select and comand for zoom battle each other mac

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#202]
hey maybe zoom should be control now? cause I'm scrolling and command clicking and when I do that the zoom kicks in...

**Comment by jean-emmanuel** [comment]
Was that any different when both actions where using `ctrl` ?

**Comment by Sebastian-blu** [comment]
Never happened, I tried control zoom once when you mentioned it in response to pinch to zoom and nothing happened so I disregarded it.

**Comment by jean-emmanuel** [comment]
It seems to be a common bug with trackpads, does it occur with latest chrome browser too ?

**Comment by Sebastian-blu** [comment]
let me check on that
I don't really use chrome much

**Comment by Sebastian-blu** [comment]
its the same on chrome. I think I may be communicating poorly its not happening randomly its just if I am selecting something with the command key then I need to scroll down in a panel or something I inadvertently zoom the screen because command is held down so I think it might be better to set zoom as ctrl so you can hold command down and scroll too

**Comment by jean-emmanuel** [comment]
I just realized I assigned command to multi selection instead of shift on os x, despite our discussion here #190... Command for zooming and shift for selecting should fix the problem.

**Comment by jean-emmanuel** [comment]
-> v0.26.3
