### ISSUE TITLE
exact ponel size black bands left and right bug?

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#203]
so I want to make it exact to screen size
looks like the top iOS bar and the tabs take up 60-62pt, according to the screen shot I cropped down

my iPad dimensions into the main panel 1112x834

so subtracted 62pt from 834pt for the tabs and made the main panel 772pt

sized everything into that panel frame but when I load it up Get a black band about 50pt on the right and bottom of the screen

the band travels the length of the right side up to the tabs and hamburger button, those parts are unaffected by the band

I can move it left and right a bit to reveal whats cut off by the right band but there are no scroll bars just the small iOS ones if I pull to far

thanks again

**Comment by jean-emmanuel** [comment]
Have you tried using percentage instead of absolute units ?

**Comment by Sebastian-blu** [comment]
i put more time into it after posting and here is what I found. 

I went back to percent for the outermost panel, after I had all the nested faders and buttons within the iPad creek limits. The heavy bands went away, but I was sill able to pull the screen left past all the objects, to about 50% empty black space, sort of like when a website doesn’t have the div tags correct and it doesn’t feel feel fixed on the x axis. 

So I thought I would delete my first tab, I hadn’t formatted all the objects to fit in the iPad screen yet so it was still x axis scrollable and had the open sound control scroller at the bottom. Deleting that page  prevented me from being to pull the first screen so far to the left. Now just about fifty pts of black on the right side. 

It was all looking pretty good, I went back to the two tabs and formatted spent some time formatting the first pace to fit in the iPad with no scrolls.  Once that was done I loaded it up to the pad. 

The Newley formated page has no scroll bar and page I had formatted to fit in the first place now has an x axis scroll bar at the bottom with once pixel scroll depth. Lol. 

Both pages allow me to pull them off to the left into about 30% empty black screen.

**Comment by Sebastian-blu** [comment]
![beddd969-32d5-4ab0-9601-aee5104efa85](https://user-images.githubusercontent.com/28813706/37051683-fbbd4890-212b-11e8-9598-7c43b8a9c1c4.png)

**Comment by Sebastian-blu** [comment]
![441ec873-9b5a-4e7a-96c4-5949bae9b933](https://user-images.githubusercontent.com/28813706/37051754-2ec36bac-212c-11e8-8cc9-2b09383f6e0e.png)
Here is the first page with scroll bar, and black space.

**Comment by jean-emmanuel** [comment]
Ok I see what it is, should be fixed soon.

**Comment by Sebastian-blu** [comment]
Ok thank 😁

**Comment by jean-emmanuel** [comment]
Can you check if the bug is fixed in the online demo ?

**Comment by jean-emmanuel** [comment]
Should be fixed in 0.26.2, feel free to reopen if it is happens again.
