### ISSUE TITLE
Pull request of one commit

### ISSUE THREAD

**Issue by kdejaeger** [jean-emmanuel/open-stage-control#204]
I have some of my own script files in my own master.
Now, when I do a pull request, it wants to pull those as well.
How can I make a pull request for just one commit. Or do you have to proactively cherry pick my commits? I don't understand very well. It' s about this little change: https://github.com/jean-emmanuel/open-stage-control/commit/46a6abc46f0e1d5f006671245aabca615d003502

**Comment by jean-emmanuel** [comment]
I think there are already many very good explanations on how git/github work on the internet :)
I added this css line to the component's css directly, it should be default : d4eb1b8ca2ae59530a4056cd7df995f9bfe4e663
