### ISSUE TITLE
keyboard 88 gives 87 keys

### ISSUE THREAD

**Issue by kdejaeger** [jean-emmanuel/open-stage-control#205]
I have clue but was looking on the internet how to emulate 25/49/61/88 key's keyboards.
keys -> start position
25 -> 48
49 -> 36
61 -> 36
88 -> 21

All good but the 88 configuration gives me only 87 keys : a blank one at the end is missing.
If I put the starting position at 14, it looks correct. But off course then the C4 (midi 60) note is not like in the real keyboard. So the starting position is I think correct.

**Comment by jean-emmanuel** [comment]
It's a bug, fixed in git, I'm adding the standard settings to docs as well. Thanks.

**Comment by kdejaeger** [comment]
Nice.
