### ISSUE TITLE
Wrapped buttons in panel : some buttons were duplicated and sprayed around the screen. 

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#206]
I wrapped 9 buttons in a panel.  Three were duplicated outside the panel and in random spots on the screen. The nine wrapped nicely in the panel regardless.

**Comment by jean-emmanuel** [comment]
Nasty bug, was also affecting multi widget delete & cut.

**Comment by Sebastian-blu** [comment]
Ahh that would explain some other things I don’t know how to describe.

**Comment by jean-emmanuel** [comment]
-> 0.26.2
