### ISSUE TITLE
dynamic start value for keyboard

### ISSUE THREAD

**Issue by kdejaeger** [jean-emmanuel/open-stage-control#207]
I made a switch with this value:
{
  "25": 25,
  "49": 49,
  "61": 61,
  "88": 88
}

The keyboard get's number of key's from the switch's value: @{tools_extra_keyboard_nr_of_keys}

I tried to make the start dynamic as well without success: @{tools_extra_keyboard_nr_of_keys} == 25 ? 48 : @{tools_extra_keyboard_nr_of_keys} == 88 ? 21 : 36

**Comment by kdejaeger** [comment]
ow wait a sec it does work ... checking ...

**Comment by kdejaeger** [comment]
Hmm no it even mingles with the nr of keys now. Can you check it out?

**Comment by kdejaeger** [comment]
I did it!

#{
nrOfKeys = @{tools_extra_keyboard_nr_of_keys};
start = nrOfKeys == 25 ? 48 : nrOfKeys == 88 ? 21 : 36
}

**Comment by kdejaeger** [comment]
Tnx to the example earlier (knobs.json.txt) in which I also saw a calculation.

**Comment by jean-emmanuel** [comment]
ok cool

**Comment by kdejaeger** [comment]
I was trying to do something similar today with a css property, but it didn't work. It looked something like this:

#{
css = @{somevar0or1} == 1 ? '' : 'display: none'
}

**Comment by jean-emmanuel** [comment]
Mathjs syntax does not accept single quotes for strings, only double quotes : http://mathjs.org/docs/expressions/syntax.html#strings

**Comment by kdejaeger** [comment]
Aha! Tricky. This works now:

#{
css = @{tools_track_isgroup} == 0 ? "visibility:hidden" : "" 
}

**Comment by kdejaeger** [comment]
I have another mathjs experiment to combine 2 @{} objects:

#{
nameId = concat("strip_device_param_name_", @{parent.variables.n})
css = @{nameId} == " " ? "visibility:hidden" : "" 
}

Is there any way to make this work?

**Comment by jean-emmanuel** [comment]
@{parent.variables.n} is a number, you have to turn in into a string:
```#{
nameId = concat("strip_device_param_name_", string(@{parent.variables.n}))
css = @{nameId} == " " ? "visibility:hidden" : ""
}
```

**Comment by kdejaeger** [comment]
Doesn't work. And just clarify, this works:

#{
css = @{strip_device_param_name_2} == " " ? "visibility:hidden" : ""
}

So maybe he doesn not accept a string in @{} ?

**Comment by jean-emmanuel** [comment]
I had not fully understood your code, there is currently no way to construct property inheritance calls dynamically.

**Comment by kdejaeger** [comment]
Okey :)
