### ISSUE TITLE
Switch does not get default value

### ISSUE THREAD

**Issue by kdejaeger** [jean-emmanuel/open-stage-control#208]
I have a switch with this value:
{
  "25": 25,
  "49": 49,
  "61": 61,
  "88": 88
}

Default is set to 49.

Save & refresh -> switch is not initialized at the default value.

**Comment by jean-emmanuel** [comment]
Works fine here: [switch.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1786828/switch.json.txt)

**Comment by kdejaeger** [comment]
Yup. But not in this one: [open_stage_control_bitwig.zip](https://github.com/jean-emmanuel/open-stage-control/files/1786869/open_stage_control_bitwig.zip)

**Comment by jean-emmanuel** [comment]
It does too, maybe try with latest release ?

**Comment by kdejaeger** [comment]
That's funny it works now.

**Comment by kdejaeger** [comment]
Aha found it, it goes wrong as soon as I connect my with more than 1 device. From then on it does not get initialized properly.

**Comment by jean-emmanuel** [comment]
Some widgets have the same osc address as your switch and send their value to it at initialization, thus conflicting with the synchronisation: the swtch receives `49` correctly but then receives `undefined` (from some strip widgets) and goes unselected.

**Comment by kdejaeger** [comment]
Ok, I'll look for the duplicate Id.

**Comment by jean-emmanuel** [comment]
Changing the switch's address will do

**Comment by kdejaeger** [comment]
Indeed, that worked.
