### ISSUE TITLE
encoder as fader?

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#209]
widget that functions the encoder does but is a fader centered so pull left would be like rotating left pull right would be rotate right might be good for space in some circumstances

**Comment by jean-emmanuel** [comment]
This sound really specific and not , I'd prefer not to add a widget for that. Attached session show how to do that using an input widget whose value is either -1, 0 or 1 depending on the fader's value
[fader_encoder.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1820173/fader_encoder.json.txt)
. The input's value has a small random number added to it to force the value to change and trigger osc sending, then the sent value is rounded thanks to the `precision` propoerty set to `0`.
