### ISSUE TITLE
Fine control on faders with integer values is odd.

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#21]
When using an int for fader value (0 to 1023 in this case) control mouse wheel seems to just send the same two values over and over. Things are fine with floats (-200 to +10). This is feed back related. When I turn Ardour's feedback off the problem goes away. So it is something to do with mapping from int back to pixel (or internal value). Debug mode shows that Ardour returns the same int that open stage control sends. This may go away if max is less than fader height. I am testing for working with motor faders with a 10bit ADC which seem to be common (so 0 to 1023). The idea is to make Ardour's OSC code as easy to use as possible with as many controllers as possible. So an int from 0 to 1023 for position and a dB value are the two modes I am looking at.
My config file is below. (testing against the osc branch of Ardour - F2 sets feedback up.)

[ardour1024.js.zip](https://github.com/jean-emmanuel/open-stage-control/files/264701/ardour1024.js.zip)

**Comment by jean-emmanuel** [comment]
I'm not sure to get what's wrong here, can you provide more details : 
- what's being controlled with the mouse wheel, in which software
- what's the expected behavior
- what's the actual behavior
- some log file from OSC's debug output might be helpful too

**Comment by ovenwerks** [comment]
On Sun, 15 May 2016, jean-emmanuel wrote:

> 
> I'm not sure to get what's wrong here, can you provide more details :

As always my descriptions are not very good, I am sorry for not being 
clear enough.

>  *  what's being controlled with the mouse wheel, in which software

The mouse wheel is controlling the fader that has max 1023. The software 
it is sending to is Ardour and as you can see, Ardour just sends back the 
same value as was sent to it. So using OSCsend to return the same value as 
was sent would be the same.

The control key is being held down so that the change increments are in 
fine mode.

The mouse wheel is being rolled only in the up direction.

>  *  what's the expected behavior

The expected behaviour would be for the value to continue to rise.

>  *  what's the actual behavior

As you can see from the debug output, the value actually goes down 
sometimes.

>  *  some log file from OSC's debug output might be helpful too

Here is some debug output:
OSC sent:  { path: '/strip/fader',
   args:
    [ { type: 'integer', value: 1 },
      { type: 'integer', value: 809 } ] } To : 172.17.128.30:3819
OSC received:  { path: '/strip/fader', args: [ 1, 809 ] } From : 
172.17.128.30:3819
OSC sent:  { path: '/strip/fader',
   args:
    [ { type: 'integer', value: 1 },
      { type: 'integer', value: 810 } ] } To : 172.17.128.30:3819
OSC sent:  { path: '/strip/fader',
   args:
    [ { type: 'integer', value: 1 },
      { type: 'integer', value: 811 } ] } To : 172.17.128.30:3819
OSC received:  { path: '/strip/fader', args: [ 1, 811 ] } From : 
172.17.128.30:3819
OSC sent:  { path: '/strip/fader',
   args:
    [ { type: 'integer', value: 1 },
      { type: 'integer', value: 809 } ] } To : 172.17.128.30:3819
OSC received:  { path: '/strip/fader', args: [ 1, 809 ] } From : 
172.17.128.30:3819
OSC sent:  { path: '/strip/fader',
   args:
    [ { type: 'integer', value: 1 },
      { type: 'integer', value: 810 } ] } To : 172.17.128.30:3819
OSC received:  { path: '/strip/fader', args: [ 1, 810 ] } From : 
172.17.128.30:3819
OSC sent:  { path: '/strip/fader',
   args:
    [ { type: 'integer', value: 1 },
      { type: 'integer', value: 809 } ] } To : 172.17.128.30:3819
OSC received:  { path: '/strip/fader', args: [ 1, 809 ] } From : 
172.17.128.30:3819


Note: this does not happen if the feedback is not present. I suspect it is 
the feedback math that sets the internal value (gui %) to the closest gui 
value which may sometimes be lower than the sending value. The mouse 
control should be done on the OSC value rather than the GUI value. Any 
change in the GUI value should be ignored unless the mouse button is 
pressed. I do not know if the browser sends this information though. The 
other solution is to detect when the range of OSC message is greater than 
the number of clicks in the GUI, widen fine increments to the size of GUI 
increments. (or even one greater than)

Another way of saying this is that the fine increment should be the 
smallest of GUI increment or OSC increment. If this means that sometimes 
the fine increment moves the OSC value more than +/- 1 that is ok.

I don't know the internal math at all, it may be possible to just use the 
GUI increment and just not send an OSC message if the movement is not yet 
enough to change the OSC value.

Please feel free to ask more questions.

--
Len Ovens
www.ovenwerks.net

**Comment by jean-emmanuel** [comment]
Very good guess ! There was some unneeded rounding involved in the widgets' value setter method that was causing this.

**Comment by jean-emmanuel** [comment]
fixed in v0.5.1 https://github.com/jean-emmanuel/open-stage-control/releases/tag/v0.5.1
