### ISSUE TITLE
possible to run without internet?

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#210]
I am hoping to use this at rehearsal tonight and at shows going forward is it possible to do it with no internet? is that what the node.js thing you referenced is for?

**Comment by jean-emmanuel** [comment]
Yes, internet is not needed, all you need is having the devices on the same network and connect to the server's address (printed when it starts), but not 127.0.0.1 only works from a device to itself.

**Comment by Sebastian-blu** [comment]
omg, im embarrassed...... I didn't see the ip changed when I switched to adhoc haha, but I guess of course that would happen. 

So then A different question arises is it possible make the stop the ip from changing when I switch from my home router to adhoc at rehearsal and shows? or is it possible to make it so I can rename the full screen app icons so I open the correct one depending on the network I'm on. at the moment I have two app buttons both labeled openStage... 

just looking down the line when time is more precious like at a gig 

thanks so much for all this you have no idea how excited I am haha

**Comment by cyberic99** [comment]
If you want to reach a mac os server, it should advertise its IP through Zeroconf/bonjour.
So you should be able to put '<MY_SERVER_NAME>.local' in place of the IP address

**Comment by Sebastian-blu** [comment]
Oh ok, that sounds promising. Put that in safari on the tablet phone side? Or put it in the .json file?

**Comment by cyberic99** [comment]
it depends... we need more precisions about your hardware, tablet, computer...

Please tell us what you will use, which OS it runs etc...

**Comment by jean-emmanuel** [comment]
> just looking down the line when time is more precious like at a gig

If you use it in performances, always use a network you own and configure it so that the computer that host the server always has the same ip address.

**Comment by Sebastian-blu** [comment]
I am running on macOS Sierra 2016 mbp with touchbar. And iPad Pro 10.5inch. Want to be able to go from my home network airport express. To adhoc network between the tablet and Mac when at rehearsal and possibly gigs.

**Comment by Sebastian-blu** [comment]
Ideally without having to switch up the IP address each time.

**Comment by Sebastian-blu** [comment]
I figured it out, So on iOS when you save the ip to home screen you can name it after hitting the button. So you can just have multiple open sound control icons on the home screen with different labels depending on the router you are connected to. So when I am home I hit app with label home. And at work hit the one labeled work. and at rehearsal studio hit the one labeled studio. its very simple solution that will keep things error proof in high stress situations. hopefully...haha
