### ISSUE TITLE
odd things when using @{id.value} in preargs

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#211]
I have a group of toggles that I want to send the values of with one press in the form of:
/address iiii toggle1 toggle2 toggle3 toggle4
So I have been doing preargs:
[@{toggle1.value}, @{toggle2.value}, @{toggle3.value}, @{toggle4.value}]
Which seems to work if I hold my mouth right.
Though the editor doesn't break it down to:
[
@{toggle1.value},
value,
]
If I start with:
[
1,
2
]
And try to change the 1 to @{id.value} then it changes the whole thing to a string.
 Sometimes the whole thing gets escaped into one string and sent as one argument. In fact this always happens if I try to use @{this.value} in any form. It seems to think @{this.value} is undefined.
The reason I want to send this.value in the preargs is because there is no "postargs" :) I have 9 toggles and I want the first one to send it's value first then the others, the second to sends the value of the first toggle followed by it's own value and then the rest of the toggles, etc.

Or... I want each of these toggles after setting their value to trigger the last one to send it's stuff, but I can't use linkid because it sets all the values the same.

**Comment by ovenwerks** [comment]
After looking at how I do everything else... I am probably best to break this into 9 messages with one parameter each. They do not need to be changed all at once anyway. I would still like to know why the editing works different when using @{id.value} as a prearg.

**Comment by jean-emmanuel** [comment]
Preargs (and target) are coerced to arrays and it has bad side effects in some cases, this will take some time to process but eventually I'll fix this :).

**Comment by jean-emmanuel** [comment]
Ok it should behave more consistently with 04fafb15eeff5e667ff2097a14ccdd3f9542399e. What doesn't change though is that arrays are not always auto-formatted in the editor depending on how they are written:
- `[@{toggle_1}]` is not a valid javascript array until `@{toggle_1}` is resolved -> not formatted
- `["@{toggle_1}"]` is a valid javascript array -> formatted

**Comment by jean-emmanuel** [comment]
-> v0.30.0
