### ISSUE TITLE
osc split property for fader osc

### ISSUE THREAD

**Issue by kdejaeger** [jean-emmanuel/open-stage-control#212]
Hi I have a fader sending values to /vkb_midi/0/aftertouch .
However the backend needs /vkb_midi/0/aftertouch/1  , /vkb_midi/0/aftertouch/2 , etc ... . Not /vkb_midi/0/aftertouch 1 , /vkb_midi/0/aftertouch 2 .

Can you add a 'split' property, just like in for instance the keyboard?

**Comment by jean-emmanuel** [comment]
No, widgets don't send their value as part of their address, you'll have to use to filter the fader value with an additionnal widget or with a custom module.
