### ISSUE TITLE
colors on cloned pan faders not showing on ipad

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#214]
<img width="1379" alt="screenshot_2018-03-07 19 23 27_oxxiej" src="https://user-images.githubusercontent.com/28813706/37131566-c02a9d6a-223d-11e8-8ca5-9f59a4ca2315.png">

notice the horizontal faders under the track names

![img_0042](https://user-images.githubusercontent.com/28813706/37131579-d37798e6-223d-11e8-8386-e1ea3981b1ab.JPG)

**Comment by Sebastian-blu** [comment]
looks like that only happens when they are set to color auto, so I don't know if that is the intended behavior or not, but if I change color to red they are the same on desktop and tablet

**Comment by jean-emmanuel** [comment]
Fixed in git, thank you !

**Comment by jean-emmanuel** [comment]
-> 0.26.3
