### ISSUE TITLE
possible to make strip padding and panel label scalable?

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#215]
starting to really understand the percentage formatting now. Wondering if its possible to make paling in strip objects scalable?

**Comment by jean-emmanuel** [comment]
Added support for percentages in strip's `spacing`.

**Comment by kdejaeger** [comment]
How does this work? I tried with the latest code. Changed on a strip spacing 4 to 4%. Or 20%. I don't see any difference.

**Comment by jean-emmanuel** [comment]
Did run `npm run build` after pulling ?

**Comment by kdejaeger** [comment]
yes

**Comment by jean-emmanuel** [comment]
[spacing.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1798710/spacing.json.txt)

Attached session is supposed to work: the spacing should be proportionnal to the strip's width, can you try it ?

**Comment by kdejaeger** [comment]
I have 2 commands in a run-windows.bat file:

npm install
npm run build

He only does the first one when I execute the file.

**Comment by kdejaeger** [comment]
I changed it to this now

npm install && npm run build

winblows huh

**Comment by jean-emmanuel** [comment]
hehe ok :)
