### ISSUE TITLE
open editor to different screen sizes ideas

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#216]
would be nice to have a drop dow that opens the editor to different screen sizes

1. would make it easier to develop for preferred screen sizes while keeping things in percentage formatted scalable and universal

2. if it did open to a specific screen size the editor hamburger button would have resize the app window out as to keep the editing window 

3. if this all happened then maybe it would be useful have a setting to allow the user editing to drag and move widgets in the edit window visually and producing percentage values for top left height etc.

I was just doing this by having a photo editor with guides sized to my iPad open behind the application and scaling the open stage window window to fit. doing that made working in percentages much better.

**Comment by jean-emmanuel** [comment]
1. 2. You can already hit F12 and use chrome's devices emulator, might do the job!

3. I'll try that: it'd use percentages only if percentages were already used though.

**Comment by Sebastian-blu** [comment]
Cool I think that would be great

**Comment by jean-emmanuel** [comment]
3. -> in git, for next release.

**Comment by jean-emmanuel** [comment]
-> v0.27.0
