### ISSUE TITLE
border -> false does not get inherited by cloned strip

### ISSUE THREAD

**Issue by kdejaeger** [jean-emmanuel/open-stage-control#219]
I have a panel with strips. The first strip has border set to false. The next strips are clones but still have a border. I guess you'd expect the clone not to have a border.
[open_stage_control_bitwig.zip](https://github.com/jean-emmanuel/open-stage-control/files/1799202/open_stage_control_bitwig.zip)

**Comment by jean-emmanuel** [comment]
Confirmed.

**Comment by jean-emmanuel** [comment]
fixed in git
