### ISSUE TITLE
Feature request: Send OSC message at startup

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#22]
There may already be a way to do this, but I could not find it. Right now I have a button that tells the host how many strips it has for banking, what kind of feedback I want, what kind of fader math to use, etc. (/set_surface iiii as happens) It would be nice if the *.js file had a "send at load" OSC message. This is important because it tells all the buttons, faders, text boxes what the current state is.

**Comment by jean-emmanuel** [comment]
It not currently possible but it would be a nice feature, i'll think of a clever way to allow that !

**Comment by jean-emmanuel** [comment]
I've been giving this request some thought and I think it

**Comment by jean-emmanuel** [comment]
Some more thought later... I'm planning to fix this by adding the new feature described in #34 :)
