### ISSUE TITLE
Précision et valeur envoyée

### ISSUE THREAD

**Issue by nlebellier** [jean-emmanuel/open-stage-control#220]
Bonjour,
Ce n'est probablement pas une issue mais une question de ma part ;-)
Est-ce normal que malgré une précision à 2 sur un fader, la valeur envoyée n'est pas limitée à 2 chiffres après la virgule ?

https://flic.kr/p/24YZnBS

Merci pour d'éventuelles précisions :)

**Comment by jean-emmanuel** [comment]
La valeur est bien arrondie à deux chiffres après la virgule, mais le format par défaut (_floats_) peut ajouter souvent des chiffres après la virgule, c'est un problème de précision classique. Tu peux envoyer des nombres à double précision (_doubles_) en mettant `2d` par example, mais il faut que l'application de l'autre côté accepte ce type de valeur. Je te laisse googler les subtilités des floats vs doubles...

**Comment by nlebellier** [comment]
Ok ça marche avec 2d. Merci pour ta réponse.

**Comment by jean-emmanuel** [comment]
de rien !
