### ISSUE TITLE
Main Tabs do not send OSC

### ISSUE THREAD

**Issue by git-moss** [jean-emmanuel/open-stage-control#221]

**Comment by jean-emmanuel** [comment]
Does the root widget have a target set ?

**Comment by git-moss** [comment]
![root](https://user-images.githubusercontent.com/3090132/37247642-37d36da4-24b6-11e8-8b91-73065929778f.png)

**Comment by jean-emmanuel** [comment]
When bypass is true -> no osc is sent.

**Comment by git-moss** [comment]
Yes, sure, but it is not true on the individual tabs. I expected that the messages are sent which are configured in the tabs.

**Comment by jean-emmanuel** [comment]
Nope, it works the opposite way, it's the containing widget that sends its selected tab index ;)

**Comment by git-moss** [comment]
So, the OSC strings in the individual tabs do nothing?
I wanted to send different OSC strings to indicate the edited parameters.

**Comment by jean-emmanuel** [comment]
Tabs send messages if they contain tabs. I see what's confusing about it though, to be improved...

**Comment by jean-emmanuel** [comment]
The editor now disables the panel's osc fields when they don't apply, this should help disambiguate things a bit. Sending different messages for each tab is doable via custom module.
