### ISSUE TITLE
"strip: spacing now accepts percents" introduces space when set to 0

### ISSUE THREAD

**Issue by git-moss** [jean-emmanuel/open-stage-control#222]
With "0" you get now a lot of spacing, setting it to "0%" fixes it.

**Comment by jean-emmanuel** [comment]
Can you provide an example ? I can't reproduce this. If you are running the app from sources, make sure you've run `npm run build` after pulling.

**Comment by git-moss** [comment]
No, it is the EXE from the download. I also cannot produce it in a simple example.
In this complex example it happens with the two small Punch-in/out buttons right of the time text. When you change the "0%" of their Container to "0". Also there is now space in all the Strip Containers when you open the Settings-modal (the tool Icon on the left).

[OpenStageControl4Bitwig.zip](https://github.com/jean-emmanuel/open-stage-control/files/1799879/OpenStageControl4Bitwig.zip)

**Comment by jean-emmanuel** [comment]
Ok, found it, fixed it !

**Comment by jean-emmanuel** [comment]
-> v0.27.0
