### ISSUE TITLE
Paste clone doesn’t behave like a  clone widget 

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#224]
Hey I’m not sure if it’s the intended functionality but when I copy something like a channel strip of multiple things then paste as clone (not Id + 1), it behaves nothing like when I add a clone widget and name the widget Id after the widget I want to clone. 

I personally would prefer to be able to past as clone and have it behave the way the clone widget does. 

Thanks!!!

**Comment by git-moss** [comment]
I agree that the naming is confusing. I suggest to rename it to "Paste" and "Paste (ID + 1)".
An actualy "Paste as clone" function would be nice!

**Comment by jean-emmanuel** [comment]
Yeah good idea.

**Comment by jean-emmanuel** [comment]
-> v0.27.0
