### ISSUE TITLE
Improvement for "Wrap in".

### ISSUE THREAD

**Issue by git-moss** [jean-emmanuel/open-stage-control#225]
The new "wrap in" function is a real time safer! But it should insert the new container at the same position as the wrapped element was before. Also I would prefer to have the "label" disabled as the default of the new container.

I mostly use this to add another element left or right to an element in a strip. After I chose "wrap in" the whole layout freak out since a really big container is added at the end with a fat title bar :-) I then need some time to wrap my head around what was going on and how I need to move the element back to where it was before.

**Comment by jean-emmanuel** [comment]
Makes sense, will try.

**Comment by jean-emmanuel** [comment]
-> v0.27.0
