### ISSUE TITLE
Option to close Modal on button press

### ISSUE THREAD

**Issue by git-moss** [jean-emmanuel/open-stage-control#226]
I have now some modals which I would like to automatically close after the user pushed a button (in the modal container).

**Comment by jean-emmanuel** [comment]
If the button is as push, you could put this in the modal's `value` property:

```
#{
# returns 0 if the push is pressed, otherwise keep current value
@{push_id} ? 0 : @{this}
}
```

**Comment by git-moss** [comment]
This has no effect and I do not understand how that should close the modal?!

**Comment by jean-emmanuel** [comment]
You have to replace `push_id` with the actual push's id. This sets the modal's value (ie open/closed state) to 0 if the push's value is truthy. This assumes the push's on value is `1`.  A more reliable way to do it would be the following:
```
#{
@{push_id} == @{push_id.on} ? 0 : ""
}
```

When the push's value changes, if it's equal to its `on` value, the modal's value will be set to 0. This only work with latest sources, there was a little bug preventing it to work.

**Comment by git-moss** [comment]
Sorry, I cannot make that work. Can you post an example?

**Comment by jean-emmanuel** [comment]
[modal-close.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1800560/modal-close.json.txt)
(latest source build needed)

**Comment by git-moss** [comment]
Will wait till the official update. Thanks!
