### ISSUE TITLE
Documentation: Newline in label

### ISSUE THREAD

**Issue by jamols** [jean-emmanuel/open-stage-control#229]
I was digging through the documentation to find a way to insert a newline in a label. Then I thought... it's an Electron app.. maybe HTML will work?.. Lo and behold, it does.

In case anyone else is looking for it, you can insert a line break in a label by adding a `<BR>` tag.

Thanks for the great work!

**Comment by Sebastian-blu** [comment]
cool might need that soon thanks

**Comment by jean-emmanuel** [comment]
Properties are multiline, shift+enter does that already : http://osc.ammd.net/editing-sessions/#properties
