### ISSUE TITLE
Build directions don't work

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#23]
On Ubuntu 16.04 nodejs version 4.2.6, the command:
sudo npm install -g npm
fails with: /usr/bin/env: ‘node’: No such file or directory

I did a:
sudo ln -s nodejs node
in /usr/bin and all is fine.
This may mean that instances of "node" should be changed to "nodejs"

This was a fresh pull from git with tag 5.1.

**Comment by jean-emmanuel** [comment]
This is not related to OSC. The fact that nodejs binary has to be linked to node on debian based distros is [documented](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions). I'll mention it in the docs though.
