### ISSUE TITLE
would love to be able to resize the inspector so not so much parameter scrolling

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#230]
I have some longer widget ID's going I would love to be able to pull out the inspector pain to make it larger so I could see all of my text without having to scroll the text box

**Comment by jean-emmanuel** [comment]
Good idea, it's in git you can try it with the online demo, there's a little handle in the upper-left corner of the sidepanel.

**Comment by jean-emmanuel** [comment]
-> v0.27.0
