### ISSUE TITLE
make it possible to click through text box to widget placed directly below

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#231]
it would be useful to be able to place text with a transparent background over the top of a button/fader widget and still be able to click the button below

**Comment by jean-emmanuel** [comment]
You can add `pointer-events:none;` to css (then the widget won't be selectable by the editor except from its parent childlist).

**Comment by Sebastian-blu** [comment]
awesome that makes things so much more polished. thanks

**Comment by jean-emmanuel** [comment]
Next release will include a patch that makes the editor ignore `pointer-events:none;` on widgets to make sure they can always be selected. This means this trick will onlt work when the editor is disabled.

**Comment by cyberic99** [comment]
maybe it could be useful to add a property rather than messing up with the css?

**Comment by jean-emmanuel** [comment]
I'd rather not (one could argue that any css hack case could be added as a property too ;) )
