### ISSUE TITLE
how do I change the default orange of buttons that recieving info from bitwig

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#232]
these aren't toggle buttons but they light up when communication is working. 

I want to dim them down globally

and also change the color on a case by case basis in the inspecto

.widget.push-container.on,
.widget.toggle-container.on
{
	background : #FF7D00;	
}

changing that in my css sheet has no effect

<img width="1411" alt="screenshot_2018-03-12 19 41 53_qqk1mj" src="https://user-images.githubusercontent.com/28813706/37319725-88ab27c6-262d-11e8-9596-ae422aa010bf.png">

and also change the color on a case by case basis in the inspector to match the faders that it is close to

**Comment by jean-emmanuel** [comment]
There is the `color` property for that.

**Comment by Sebastian-blu** [comment]
When I change that I’m still seeing orange

**Comment by Sebastian-blu** [comment]
And it seems to disable the feedback from the program.

**Comment by Sebastian-blu** [comment]
changing this value without my css file loaded changes the color of the text in the button when pressed, but not the orange color of the background
<img width="290" alt="screenshot_2018-03-13 10 14 39_xnypmo" src="https://user-images.githubusercontent.com/28813706/37358168-9f1cb0b8-26a7-11e8-82d4-ae6dc9a886e1.png">

when my css file is loaded it doesn't override the color of the text, and it remains that light blue no matter if I change the color from auto to red or green

thanks again :-)

**Comment by jean-emmanuel** [comment]
Try the `alt-buttons` theme (can be combined with custom themes), it makes buttons look the way you want I think.

**Comment by Sebastian-blu** [comment]
I'm sorry, I have been poking around and I can't figure out what alt button theme is, is that a css thing? I looked online didnt see it, didnt see it on your documentation. Im out of my depth a bit at this point lol
can you point me in the correct direction

**Comment by jean-emmanuel** [comment]
http://osc.ammd.net/extras/theming/
launch the app this way : `open-stage-control --theme alt-buttons /optional/other/file.css` or put `alt-buttons /optional/other/file.css` in the theme option if you are using the gui.

**Comment by Sebastian-blu** [comment]
Thanks I’ll look into it further.
