### ISSUE TITLE
You can pull down on full screen interface on ios

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#235]
you can pull the interface down as if you were pulling down to refresh a website. I’m only noticing it as I am making some smaller fader controls were missing is possible. Is it possible to freeze it vertically like u did horizontally?

**Comment by jean-emmanuel** [comment]
What's your iOS version ?
Which browser are you using ?
Does it occur when the the app is launched from the home screen too ?

**Comment by Sebastian-blu** [comment]
I’m on the most current iOS 11.2.6. 

Safari, saving to home screen doesn’t work in chrome far as I can tell. 

I have the app saved to home screen launch it in full and if I tap empty space I can pull down and it springs back up.

**Comment by jean-emmanuel** [comment]
Ok thanks.

**Comment by jean-emmanuel** [comment]
Can you confirm it only happens in fullscreen mode ?

**Comment by Sebastian-blu** [comment]
It seems to happen in either mode sorry I forgot to get back on that

**Comment by jean-emmanuel** [comment]
Could you build from branch `issue-235` and try again ?

**Comment by Sebastian-blu** [comment]
hey sorry I dropped off the map for a while... I got caught up with a bunch of band stuff, but I am back in the mix here. I rebuilt it and it does still pull down on full screen mode. I just got back into using it and everything else is functioning as it should.

**Comment by jean-emmanuel** [comment]
The issue should be fixed in master now, could check please ?

**Comment by Sebastian-blu** [comment]
yep I dont have time today but I will in the next couple days 😊
Barry Sebastian
barry@barrysebastian.com


 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	Intel Core i9
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Memory:	32 GB

audio interface: apogee ensemble

**Comment by Sebastian-blu** [comment]
seems to still do it in .36, it pulls down like when you refresh a website

**Comment by jean-emmanuel** [comment]
The fix only in git for now, can you try with the online demo ?

**Comment by Sebastian-blu** [comment]
just checking that it seems to still allow me to pull down to refresh

**Comment by jean-emmanuel** [comment]
Hmm that's disappointing, I had managed to reproduce and fix the bug on an iOS 11...

**Comment by Sebastian-blu** [comment]
ahhh, my iPad is up to 12 now maybe that is it?

Barry Sebastian
barry@barrysebastian.com


 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	Intel Core i9
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Memory:	32 GB

audio interface: apogee ensemble

**Comment by Sebastian-blu** [comment]
I just checked on my wife ipad which is on 11 and I can still pull down on full screen with the online demo 
Barry Sebastian
barry@barrysebastian.com


 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	Intel Core i9
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Memory:	32 GB

audio interface: apogee ensemble

**Comment by jean-emmanuel** [comment]
Okay, it seems my remote iOS testing devices are not enough to debug this, it'll probably have to wait untill I get my hands on someone iPad (which is rare !). Thank you for testing again :)

**Comment by Sebastian-blu** [comment]
my pleasure always happy to help test, don't hesitate to ask ✌️
Barry Sebastian
barry@barrysebastian.com


 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	Intel Core i9
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Memory:	32 GB

audio interface: apogee ensemble

**Comment by jean-emmanuel** [comment]
It's very unlikely to be get ever fixed, sound reasonable to close.
