### ISSUE TITLE
Transformer un push en toggle

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#236]
Hello. Est il possible de transformer un push en toggle?

Je pensais a un truc du genre dans une des propriétés d’un push mettre :
#{@{option}==2?@{this.type}="toggle" : ""}

Mais visiblement ca ne fonctionne pas

**Comment by jean-emmanuel** [comment]
Non, ce n'est pas possible. On ne peut pas changer une propriété comme 
ça pour l'instant.


Le 14/03/2018 à 02:37, Adopo a écrit :

**Comment by Adopo** [comment]
D’accord. Je cherche une alternative...
Est ce que par exemple si on voulait un bouton push qui se tranforme en toggle avec des propriétés différentes, ca pourrait marcher en creant un push et un toggle planqué quelque part et d’utiliser un troisieme widget clone et de faire une condition qui fait que le widget clone le push ou le toggle?

**Comment by jean-emmanuel** [comment]
Probablement, faut essayer !

**Comment by cyberic99** [comment]
@Adopo peux tu expliquer ton cas d'usage, histoire de mieux comprendre?
merci

**Comment by Adopo** [comment]
Ca fonctionne pratiquement !!! Il y a juste ce que l’on peut considerer comme un bug. Un cas de figure auquel tu n’as peut-être pas pensé.

J’explique:
Cela fais quelque jour que je souhaite faire le bouton looper de la mort qui tue. Un bouton qui permetrait de faire tout ce qu’on veut sur une piste de boucleur sans avoir des tas de bouton.
Ca serait donc un bouton qui changerait d’etat selon la situation. Son etat change en fonction d’un switch ( mode stop, mute et solo) et en fonction de l.etat de la piste.
- en mode stop il enregistre la piste si celle ci est vide puis stop l’enregistrement et la piste joue. Une fois la piste en lecture il devient un bouton stop pour stopper la piste. Une fois la piste stoppée mais contenant un enregistrement il devient un bouton play
-en mode mute, quelque soit l’etat de la piste il devien un toggle pour muter ou demuter la piste
-en mode solo c’est pareil que le mode stop sauf que quand la piste joue il devient un toggle pour mettre la piste en solo ou non
J’avais reussi a faire toutes les conditions sur un bouton mais mon bouton ne devenait pas un toggle. Du coup j’ai trois boutons, un push et deux toggle, un par mode.
Et le clone prends l’apparence du bon bouton en fonction du mode et de l’etat de la piste.
Tout fonctionne sauf une chose. Un clone n’a pas de valeur. Je suppose qu’il prend donc la valeur du widget qu’il clone. Sauf que lorsqu’il clone un autre widget et qu’il revient sur un mute enclenché il remet sa valeur à zero meme si le widget qu’il copie est a 1. A part si le clone a une valeur qui lui est propre (ce qui serait compliqué car certains widget on des valeurs differentes) il faudrait qu’il reprenne aussi l’etat du widget. Du coup je suis bloqué la pour le moment. J’y suis presque.

**Comment by cyberic99** [comment]
@Adopo Est-ce que tu ne peux pas tout simplement faire plusieurs boutons situés au même endroit, et les cacher, ou changer leur taille à 0, lorsque tu ne veux pas qu'ils apparaissent?

du coup là tu changes le label, l'adresse, et la value en fonction d'autres widgets, c'est ca?

**Comment by Adopo** [comment]
Oui là je changeais le label, la valeur et l’envoi osc. Je change aussi le css. Par exemple quand j’appuie sur enregistrer pendant aue ca enregistre le label (en l’occurence un ^circle) devient rouge. Entre autre.
J’ai fais ta solution. Ca m’avait effleuré l’esprit mais je trouvais ca tellement classe avec un clone ahah.
Par contre avec ta solution il y a un mini bug etrange. J’ai fais des boutons ayant un width a 0% et j’ai mis mes conditions. Mais sur mes trois boutons, celui qui apparait semble décalé genre un left a 1% alors qu’il est a 0

**Comment by cyberic99** [comment]
oui c'est peut être moins classe effectivement, mais peut-être plus maintenable ;-)

et si tu les cache au lieu de mettre leur taille à 0%?
y a peut etre du spacing ou du padding qui s'applique quand même, je laisse @jean-emmanuel nous dire ce qu'il en pense ;-)

**Comment by jean-emmanuel** [comment]
Il me faudra fichier de session pour vérifier ça. Pour le clone qui ne prend pas la valeur je n'ai pas encore trouvé de solution.

**Comment by Adopo** [comment]
C'est bon. En effet il reste un truc quand on mets à 0. Sans doute une histoire de contour de widget.
Résultat j'ai mis la taille et la longueur à zéro et j'ai planqué dans un coin tout ca et ca fonctionne !
Bon j'ai fais les 5 premières pistes. Il y en a 25. C'est chiant et redondant mais après ca sera classe. Je peux envoyer la session mais j'ai plus la version clone j'ai la version qui fonctionne.

[ipad.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1818749/ipad.json.txt)

**Comment by jean-emmanuel** [comment]
Pas de souci, j'ai pu reproduire le problème des clones facilement. Pour cacher le widget, il vaut mieux utiliser le css (avec une taille de 0, on peut quand même voir le contour du widget). Tu peux mettre ça dans `css` (et mettre des valeurs fixes dans `top`, `height` et `width`):
```css
background-color:SaddleBrown;
#{
@{option} != "2"? "display:none;" : ""
}
```

**Comment by jean-emmanuel** [comment]
Sinon, petite astuce, dans le troisième onglet, les panels qui contiennent les faders pourraient être des strips en mode `horizontal`, ça évite de devoir calculer la largeur manuellement.

**Comment by Adopo** [comment]
Oh très bonne idée pour le css !
J’avoue que ma solution finale fonctionne. Et faire la solution des display implique de remettre le top, le height et le width de 3 bouton par pistes soit 15 boutons soit 45 valeurs a modifier pour en suite placer les codes display css dans 15 boutons soit 60 changements...
Pour ensuite faire mes 4 autres looper.
Ma solution fonctionne donc je vais dupliquer ca pour le moment.
Si un jour j’ai le courage ou pour d’autres cas de figures similaire j’adopterai ta solution.

Pour les stips Je viens de tester c’est magique ahah ! A l’avenir quand j’aurais des fades a faire je ferais ca !

**Comment by cyberic99** [comment]
@Adopo moi je fais a peu près pareil, je duplque des panels,
Je fais un /GET sur un panel "modèle", je change une variable, puis je fais un /SET
Comme ca pas besoin de tout refaire à la main

**Comment by Adopo** [comment]
D’accord. Sauf que si tu vois sur le projet que j’ai mis. Il y a énormément de variable qui change.
Il y a des conditions dans le css, le label, l’adresse osc, le top, le width le height et les noms de tous les push est identifier par son num de looper et sa piste. De coup ca fait beaucoup a changer même avec ta méthode je penses

**Comment by Adopo** [comment]
Je veux bien que tu me dise comment on fait exactement pour utiliser c’est /get et /set pour voir ce que je recupere. Puis je le faire sur un mac?

**Comment by jean-emmanuel** [comment]
hop: http://osc.ammd.net/extras/remote-control/#get-target-id

ça demande de programmer un peu... ;)

**Comment by Adopo** [comment]
Merci. J’avais lu cette page mais la veritable question c’est, ou tape t on ces commande?
Genre est ce que si j’ouvre un terminal sous mac je tape ces commandes pendant que open stage control fonctionne et hop ca marche?
Ou est ce que c’est soecifique linux? Ou faut il installer quelque chose?

**Comment by jean-emmanuel** [comment]
Ce n'est pas spécifique à linux, ce sont juste des messages osc que l'on peut envoyer au serveur pour déclancher des actions spéciales. Depuis un terminal c'est possible mais ça n'a pas trop de sens, ça prend de l'intérêt quand on fait ça depuis un script, quelque soit le language, où l'on peut traiter les données reçues pour en envoyer d'autres . @cyberic99  a posté un example [ici](https://github.com/jean-emmanuel/open-stage-control/issues/152#issuecomment-367259026). Je n'ai pas trop le temps de faire une démonstration pour le coup, ça commencerait à ressembler à un cours de programmation..

**Comment by cyberic99** [comment]
oui effectivement le programme que j ai donné en exemple, une fois un peu adapté, pourrait t etre utile.
moi dans mon cas je me base systematiquement sur @{parent.variables.n}, que je remplace simplement par sa valeur (1, 2, 3, 4 etc)

Une fois que tu as lancé ca, tu peux sauvegarder et tu n airas besoin du script en python qie si tu changes le 'modèle'

**Comment by Adopo** [comment]
D’accord. Je comprends un peu. Je pourrais peut être reussir à faire quelque chose mais j’avoue que même si mes connaissances me permettent de comprendre, je risque de prendre beaucoup de temps à assimiler et à reproduire un code adapté à mon problème, surtout en commençant par un cas de figure assez complexe car en plus de ce que j’ai énoncé il y a aussi la couleur par looper qui change. Je risque de prendre plus de temps que de recopier manuellement ^^.
Mais je garde l’option dans le coin de ma tête si j’ai l’occasion d’expérimenter ça sur des cas de figure plus simple.
Merci pour toutes les infos !

**Comment by jean-emmanuel** [comment]
J'ai réglé le problème des clones pour la prochaine version (mais je pense que c'est plus performant de cacher les widgets plutôt que les creer à la volée (c'est ce qui se passe quand le clone change de cible)).

**Comment by Adopo** [comment]
Ok cool. Ca pourra etre utile a l’occase. En attendant j’ai finis cette partie de mon looper! Merci beaucoup !

**Comment by jean-emmanuel** [comment]
-> v0.27.0
