### ISSUE TITLE
General question about clones and efficiency 

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#237]
Wondering if files boot up faster if things are not cloned and nested but rather copied via Id +1

I have a modal with 8 faders in it. 1 real fader and 7 clone widgets. Then this modal is cloned 8 times on one page. Creating a sense on fader page for bitwig. 

It’s slow to load on a phone. I’m wondering if you think writing each modal out would be faster performance? Or does it not matter after the first time.

**Comment by jean-emmanuel** [comment]
Clones are likely to be a tiny bit slower to create but it should not make a big difference.

If by perfomance you mean touch reactivity, it won't change anything, big interfaces are slower, the only thing you can do about it is breaking them in smaller tabs (hidden tabs consume few resources).

**Comment by jean-emmanuel** [comment]
I've been testing your interface and I must admit I had not made such a big one yet. it outlines some performance issues I'll try to address.

**Comment by jean-emmanuel** [comment]
d46b893 brings about 25% of loading time improvement with your session file. The total time is still pretty huge though.
