### ISSUE TITLE
when loading a new file in local and tablet: Sometimes have to browse twice

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#238]
So as I am saving new files on the mac I when I load them from browser for the first on the tablet I will click and loading will not trigger. Then I have to go into the browser and click the file again usually this launches the new file. sometimes it doesn't and I have to restart the program to get it to load. not a big problem, just wanted to pass it on

**Comment by jean-emmanuel** [comment]
Yeah I'm having it too from time to time, haven't had the time to trace it.

**Comment by jean-emmanuel** [comment]
If you happen to figure out some reproduction steps, I could use them.

**Comment by jean-emmanuel** [comment]
Next time it happens, can you try waiting a few seconds before hitting load again ? it might just be the file taking time to upload (then the fix would just be to notify that).

**Comment by jean-emmanuel** [comment]
I think I have fixed it, although it's hard to say for sure since it only happened once in a while. I'll close the issue with next release (and reopen if it's happens again).

**Comment by Sebastian-blu** [comment]
I trired it out yesterday

Fresh file name and it loaded first try.

**Comment by jean-emmanuel** [comment]
-> v0.28.0

**Comment by jean-emmanuel** [comment]
This might be fixed for real now :)
