### ISSUE TITLE
faders with text layered at he same left and top point in modal, hierarchy no effect

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#239]
So I was trying to layer a textbox onto a fader inside a modal
in the modal
the fader and text box are nested in a panel 
both set to top 0 and left zero
both are vertical
I set the text to transparent no pointer etc.

I try to use hierarchy to make the text on top

hierarchy of the panel seems to have no effect

**Comment by jean-emmanuel** [comment]
Absolutely positionned widgets behave differently regarding z-ordering. You can use the css `z-index` property to define the layers order manually. Absolutely positionned widgets have `z-index:10;` by default (I'll add that to the docs).

**Comment by jean-emmanuel** [comment]
Added to the docs (to be published with next release).
