### ISSUE TITLE
electron commandline paramters seem to have changed

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#24]
New version of electron was downloaded as part of install.
running:
npm run build
Failed with:
Usage: electron-packager <sourcedir> <appname> --platform=<platform> --arch=<arch>
(and the rest of the usage statement below that)

Running npm start {whatever} works fine.

**Comment by jean-emmanuel** [comment]
Did you set the `ARCH` and `PLATFORM` environment variables (as explained [here](http://jean-emmanuel.github.io/open-stage-control/getting-started/#build-from-sources)) before running the command ?

**Comment by ovenwerks** [comment]
On Mon, 16 May 2016, jean-emmanuel wrote:

> 
> Did you set the ARCH and PLATFORM environment variables (as explained here)
> before running the command ?

I did... but it appears I made a spelling mistake/mistype while doing so. 
Sorry for the noise.

--
Len Ovens
www.ovenwerks.net

**Comment by jean-emmanuel** [comment]
No problem :)
