### ISSUE TITLE
osc message avec les tabs

### ISSUE THREAD

**Issue by guitmart** [jean-emmanuel/open-stage-control#240]
Bonjour Jean-Emmanuel,
Quand je change de TAB, le message OSC envoyer est:
OSC sent: { address: '/root', args: [ { type: 'i', value: 0 } ] }
sauf que l'application que je veux controller s'attend d'avoir /mixes.
Pourtant l'adresse du TAB est /mixes.

Comment fonctionne l'addresss OSC du TAB?
Merci et good job!

**Comment by jean-emmanuel** [comment]
Salut, la question déjà a été posée ici : #221
