### ISSUE TITLE
Osc: hidden deactivated tracks still show on openstage

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#241]
Add a track deactivate it and hide it with the x on bitwig and it remains visible on the tablet. Should disappear from view I would think. 

Also hiding deactivated tracks on a large file crashed your script once. But it didn’t say it crashed. But the clip window disappeared and wouldn’t come back until I restarted bitwig.

**Comment by Sebastian-blu** [comment]
Oops wrongs git

**Comment by jean-emmanuel** [comment]
haha ;)
