### ISSUE TITLE
Default value not reflected in dynamic properties

### ISSUE THREAD

**Issue by kdejaeger** [jean-emmanuel/open-stage-control#242]
I have a widget with id **tools_drums_edit_switch** which is consumed on the drums page. It's default 0. However the dynamic properties where it is consumed think it's at 1 when refreshing the page at init?
[open_stage_control_bitwig.zip](https://github.com/jean-emmanuel/open-stage-control/files/1820687/open_stage_control_bitwig.zip) . Might be a regression because remember the keyboard choice, that one too is not being put to the default 49 anymore.

I hope it's not because I was using some build I baked myself, I'm going to start using stable versions soon.

Really love what I've done so far with open-stage-control. I'm about to finish with my template and start using it while learning Bitwig.

**Comment by jean-emmanuel** [comment]
Hmm, it seems to work fine with current master build, here's how it looks like when I load your session:
![screenshot-2018-03-16-22 42 24](https://user-images.githubusercontent.com/5261671/37546056-704d335e-296b-11e8-9cf2-0cc188745f44.png)

I tried setting `default` to `1` and it looked the other way when reloading, as expected. Sounds like a build problem indeed. AMaybe you have another client connected that's sending its state containing  tools_drums_edit_switch's value to 0 ? 

I'll try to publish a release soon, your template will appear in the example section :)

**Comment by kdejaeger** [comment]
Oké, strange. Nice :). Also, mr Moss is building a template for Bitwig. He's still busy at it. It's not in GitHub yet but in http://www.mossgrabers.de/Software/Bitwig/DrivenByMoss.zip
