### ISSUE TITLE
possible to make text wrap at white space?

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#243]
hey I have some tiny text boxes going and I'm wondering if its possible to have text wrap only occur at white space, the text is being sent in by bitwig so using <br> one work because its not fixed text.

**Comment by jean-emmanuel** [comment]
Can you give an example ?

**Comment by jean-emmanuel** [comment]
I think this is what you're looking for.
```css
.text {
  word-break: normal;
}
```

**Comment by jean-emmanuel** [comment]
Does it work for you ? Do you think this should be the default behavior when `wrap` is set to `true` ?

**Comment by jean-emmanuel** [comment]
This is now the default behavior, breaking words is still possible via css (documented workaround).

**Comment by Sebastian-blu** [comment]
Hey yeah it’s been working!! Looks much nicer. I think that will make people happy to see. Thanks

**Comment by jean-emmanuel** [comment]
Cool !
-> v0.28.0
