### ISSUE TITLE
button color change when recieving osc information solved

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#244]
So I made some progress here just wanted to let you know for any further questions people may have

Sooooo

.widget.push-container.on,
.widget.toggle-container.on  
{
background : #FE9A00;
}

1. above does not work directly when placed in a buttons css field

2. it _does_ work in the custom css there

the reason it wasn't working in my file was because the above statement was in the css of the main panel on my device page a leftover from someone elses page I had used as a template

3. It will work work on individual buttons if that css  statement is placed in a container that holds the buttons

4. I tried alt buttons but it seems to be just a small 1px color boarder around the button when pressed, I don't know if its supposed to be more of a change then that but that is all I was getting

**Comment by jean-emmanuel** [comment]
1. That's normal, CSS rules in this field apply to the .widget element, so it tries to target a .widget element inside the widget. CSS documentation will be updated toon to clarify that, but in this field here's what would have worked:
```css
:host.on {
  /* here goes the rules for the actual widget with "on" class enabled */ 
  /* :host is the standard selector for the "&" I told you about in another issue */
}

4. The big changes happens on toggles. Push have two different visual state changes: one when pushed (soft), one when receiving feedback (the later _is_ actually changing the background color in `alt-buttons` mode).

I'm closing this as it's not an issue .

**Comment by Sebastian-blu** [comment]
Ok thanks so much
