### ISSUE TITLE
feature request: Allow set default text in text widget

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#25]
Right now a text widget defaults to the widget id on startup. It stays that way till it gets an OSC message. Sometimes that doesn't happen. For example I have 10 "send" strips set up because I don't know how many any one channel will have and I can't:
 - create a widget on the fly
 - remotely hide/unhide a widget
 - change the text colour from background to forground remotely.
So they all say sendname1, sendname2 etc. Then if a select another channel with fewer sends The ones I was using are cleared (blank). SO now I have realname, blank, sendname3, etc. Defaulting to either blank or settable text would be nice.

**Comment by jean-emmanuel** [comment]
97e8389d4fd8d1a25ceedf6aa89b1500a3123831 adds the possibility to set a [default text](http://jean-emmanuel.github.io/open-stage-control/user-guide/widgets-specifics/plots/#defaulttext) different from `id` or `label`. Sending `default` to the widget will reset it.

> create a widget on the fly
> remotely hide/unhide a widget

The editor part of the app is quite messy, I might try to make it osc-controllable but expect it too soon nor too stable...

**Comment by ovenwerks** [comment]
On Tue, 7 Jun 2016, jean-emmanuel wrote:

> 97e8389 adds the possibility to set a default text different from id or label.
> Sending default to the widget will reset it.

Perfect! Sending "default" to the widget is no easier than sending " "  :)

>       create a widget on the fly
>       remotely hide/unhide a widget
> 
> The editor part of the app is quite messy, I might try to make it
> osc-controllable but expect it too soon nor too stable...

No worries. I wouldn't be able to use it on my current project (OSC UI for 
Ardour) as it needs to be usable by anything from touchosc (yuck), to 
Pure Data, to homemade hardware.  So putting something in there that can 
send 100lines of *.js to insert in this tab as widget n is more than 
should be in there. My own HW project is a ways away just yet.

So don't be in a hurry to include adding widgets by OSC.

--
Len Ovens
www.ovenwerks.net

**Comment by jean-emmanuel** [comment]
> Perfect! Sending "default" to the widget is no easier than sending " " :)

Not ideal indeed, 2e821aff7cf5dab7cd1da0fdb0783f76001ea9c2 brings a more logical behaviour : sending a message with no argument resets the widgets to its initial/default value. Sending an empty string (`""`) will just display... an empty string !
