### ISSUE TITLE
multipush index in address

### ISSUE THREAD

**Issue by micpool** [jean-emmanuel/open-stage-control#250]
Hi
Is it possible to insert the index of a multi push within an address.

e.g when I push button 3, I want to send the address /cue/3/start (with no arguments)

Thanks

**Comment by jean-emmanuel** [comment]
Hi, it's not possible currently, the closest thing you can do is setting split to true which will append the index to the multipush's address. It could be cool to have more control over this though, so lets leave this open as a feature request.

**Comment by micpool** [comment]
Thanks. This would be really useful for use with lots of programs i use.

e.g in QLab most addresses to do things to cues are in the form 

/cue/{number}/someparameter  arguments

in Resolume Arena the Layer number and grid locations are usually part of the address other than arguments.

e.g /layer2/clip3/connect

**Comment by jean-emmanuel** [comment]
The `split` property has been extended to allow this (https://github.com/jean-emmanuel/open-stage-control/blob/master/resources/docs/widgets/matrices.md#split), it will be included in next release !

**Comment by micpool** [comment]
Fantastic. I didn't expect such a fast response.
Thanks

**Comment by cyberic99** [comment]
awesome, thanks!

**Comment by jean-emmanuel** [comment]
-> v0.28.0

**Comment by jean-emmanuel** [comment]
You  might be interested in https://github.com/jean-emmanuel/open-stage-control/issues/320#issuecomment-400458649
