### ISSUE TITLE
Envoyer plusieurs OSC et affecter plusieurs linkid

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#251]
J’ai deux questions :
- est il possible d’envoyer un message OSC sur 2 adresse OSC différentes en même temps?
- est il possible d’affecter plusieurs linkid a un widget? 
Dans mon cas ca serait 5 widget qui gere 5 sources en spatialisation sur 4 enceintes et un widget global qui controle les 5 sources en meme temps. Du coup j’imaginais soit avoir 5 linkid, 1 par widget source et le global qui possède les 5 id ou encore le global qui envoi 5 message osc en meme temps

**Comment by jean-emmanuel** [comment]
Tu peux mettre une liste dans linkId : `["a", "b", "c", "d", "e"]`

**Comment by jean-emmanuel** [comment]
Un widget seul ne peut pas envoyer sur plusieurs adresse à quelques exceptions près (pads et matrices). Il faut soit utiliser les linkId, soit filtrer les messages en sortie d'O-S-C pour en envoyer d'autres (via un script externe ou un module [integré](http://osc.ammd.net/extras/custom-module/))

**Comment by Adopo** [comment]
Parfait ! J’ai tout ce qu’il me fallait ! C’est vrai qu’avec mon serveur osc je peux aussi faire le travail en sortie

**Comment by Adopo** [comment]
Mais l’avantage avec le linkid c’est que mon global gere la position des 5 sources en minimisant les messages osc inter logiciel

**Comment by jean-emmanuel** [comment]
Cool !

**Comment by Adopo** [comment]
Je me permets de réintervenir sur ce sujet. Il y a un soucis sur les linkid multiple. 
Par exemple dans mon cas j'a un widget xy qui en controle 5. Si j'utilise le widget xy qui controle les 5 tout va bien. Mais si j'utilise l'un des 5 xy, comme il a un linkid parmis les linkid du widget master, le xy maitre bouge également, et comme il possède tous les linkid les autres bougent aussi. 
Dans de tel condition il n'y a aucun intérêt a en mettre plusieurs car de ce fait ca réagit comme si tous avaient le même linkID.
Il faudrait faire un système qui fait qu'un widget ayant plusieurs linkID devienne maitre et non plus à rôle équivalent.

**Comment by jean-emmanuel** [comment]
Je viens d'ajouter la possibilité de préfixer les linkId avec `>>` ou `<<` pour permettre cela:
- `>> xyz`: le widget envoie sa valeur aux widgets qui ont le linkId `xyz` mais ne la reçoit pas
- `<< xyz`: le widget reçoit mais n'envoie pas
- `xyz`: le widget envoie et reçoit

Dans ton cas par exemple:
- 5 pads xy slaves : linkid = `<< xyz`
- pads xy master : linkId = `>> xyz`

**Comment by cyberic99** [comment]
Excellent feature, thanks!

**Comment by jean-emmanuel** [comment]
:) -> v0.30.0
