### ISSUE TITLE
session qui ne s'ouvre plus

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#253]
Hello. J’ai un bug avec ma session. Je commencais a bosser un controleur pour une soacialisation 4 enceintes. Et quand je veux rouvrir mon projet il me dit : TypeError: this.getProp(...),replace is not a function.
[ipad space.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1826799/ipad.space.json.txt)

**Comment by jean-emmanuel** [comment]
Yes, trouvé !

**Comment by jean-emmanuel** [comment]
-> 0.27.1

**Comment by jean-emmanuel** [comment]
-> 0.27.2 (cette modification avait entrainé une regression cassant l'appli sur certaines versions d'iOS / safari.
