### ISSUE TITLE
[example] QLab dashboard

### ISSUE THREAD

**Issue by micpool** [jean-emmanuel/open-stage-control#254]
I've got a more complex example on the QLab Cook Book now

https://qlabcookbook.com/1962/02/21/lighting-fixture-profiles/

The example in the tutorial  is based on a rig of 4 VariLight 3000 spot fixtures, which can be  visualised in the free to download  Capture Nexum Student edition.

The QLab dashboard is controlled by fixture profiles created in Open Stage Control
![announceimage](https://user-images.githubusercontent.com/36141834/37744217-be4b5f7e-2d65-11e8-9b83-64ca245417d4.jpg)

Mic

**Comment by jean-emmanuel** [comment]
Nice, thanks for sharing, I've updated the examples page !
