### ISSUE TITLE
Clocks

### ISSUE THREAD

**Issue by micpool** [jean-emmanuel/open-stage-control#255]
Is there a way to get a widget to send its OSC message repeatedly e.g once a second?
Or of creating LFOs etc using the maths functions?

Thanks

**Comment by jean-emmanuel** [comment]
There is no way to do that for now. This could be easily done from a [custom module](http://osc.ammd.net/extras/custom-module/) though. The following code will only work with latest master build (custom module lacked of the `setInterval` method until now). It sends `/heartbeat 1` every seconds and filters osc message to disable/enable the clock if the app sends or receive `/heartbeat 0`.

```js
(function(){

    // Do whatever you want, initialize some variables, declare some functions, ...
    var heartbeatEnabled = false,
        heartbeat = setInterval(()=>{
            if (heartbeatEnabled) {
                sendOsc({
                    address: '/heartbeat',
                    args: [
                        {type: 'i', value: 1}
                    ],
                    host: '127.0.0.1',
                    port: 5555
                })
            }
        }, 1000)


    return {
        init: function(){
            // this will be executed once when the osc server starts
            heartbeatEnabled = true
        },
        oscInFilter:function(data){
            // Filter incomming osc messages

            var {address, args, host, port} = data

            if (address === '/heartbeat' && args[0]) {
                heartbeatEnabled = !!args[0].value
            }

            // return data if you want the message to be processed
            return {address, args, host, port}

        },
        oscOutFilter:function(data){
            // Filter outgoing osc messages

            var {address, args, host, port} = data

            if (address === '/heartbeat' && args[0]) {
                heartbeatEnabled = !!args[0].value
            }

            // return data if you want the message to be and sent
            return {address, args, host, port}
        }
    }

})()

```

**Comment by micpool** [comment]
I've got this working,  sending /heartbeat 1

I'm probably being thick but I can't change the OSC message sent in the script. e.g if i change all 3 instances of '/heartbeat' to '/cue' I get an error message: Invalid or unexpected token

**Comment by jean-emmanuel** [comment]
Can you paste your code here ? A space character before the first slash can break it.

**Comment by micpool** [comment]
Here's my code with /heartbeat changed to /connect

(function(){

    // Do whatever you want, initialize some variables, declare some functions, ...
    var heartbeatEnabled = false,
        heartbeat = setInterval(()=>{
            if (heartbeatEnabled) {
                sendOsc({
                    address: ‘/connect’,
                    args: [
                        {type: 'i', value: 1}
                    ],
                    host: '127.0.0.1',
                    port: 53000
                })
            }
        }, 1000)


    return {
        init: function(){
            // this will be executed once when the osc server starts
            heartbeatEnabled = true
        },
        oscInFilter:function(data){
            // Filter incomming osc messages

            var {address, args, host, port} = data

            if (address === ‘/connect’ && args[0]) {
                heartbeatEnabled = !!args[0].value
            }

            // return data if you want the message to be processed
            return {address, args, host, port}

        },
        oscOutFilter:function(data){
            // Filter outgoing osc messages

            var {address, args, host, port} = data

            if (address === ‘/connect’ && args[0]) {
                heartbeatEnabled = !!args[0].value
            }

            // return data if you want the message to be and sent
            return {address, args, host, port}
        }
    }

})()



The actual message I want to use is '/cue/sendValues/start'  but I thought I would try to get it  working with a simple substitution first.

Thanks

**Comment by jean-emmanuel** [comment]
Your are using an invalid single quote character : ‘ instead of '

**Comment by micpool** [comment]
Thanks. I didn't realise TextEdit had a smart quotes option for plain text.
All working perfectly now, and exactly what I needed.

**Comment by jean-emmanuel** [comment]
Cool :)

**Comment by micpool** [comment]
Hi

This seems to have stopped working with latest versions of everything.

Any ideas please?


Best


Mic

–––––––––––––––––––––––––
Mic Pool
Sound and Video Designer
www.micp.tv
***@***.***
07711 308549
________________________

**Comment by jean-emmanuel** [comment]
I suppose you updated your version of open stage control from a very old one to the latest available, in which case you'll notice many things have changed included the custom module's expected format. I advise you take a close look at the [changelog](https://openstagecontrol.ammd.net/docs/changelog/) and even maybe at the v0 changelog if you're coming from before [v0.49.12](https://github.com/jean-emmanuel/open-stage-control/blob/master/CHANGELOG.v0.md).

Regarding the custom module from this ticket, everything should work by simply removing the self-invoking function wrapper and by replacing the top level return statement with a `module.exports` assignment:

```js
(function(){
/* some code */
return {
    /* init, oscInFilter, etc */
}
})()
```

would become

```js
/* some code */
module.exports = {
    /* init, oscInFilter, etc */
}
```

**Comment by jean-emmanuel** [comment]
Also, see the the custom module's documentation for an up to date reference: https://openstagecontrol.ammd.net/docs/custom-module/custom-module

**Comment by micpool** [comment]
Many thanks for your speedy reply. All working now

Mic
