### ISSUE TITLE
small wrap in panel bug

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#256]
hey I was doing the old trick with text and rgb led 

I had a text box that I thought could use an rgbled behind it 

the text box had text from bitwig

so i wrapped the box in a panel and added a rgbled got every thing lined up to 0 top 0 left

got it all looking good but I could make the hierarchy work to put the led behind the text. text would show when I was editing it but not after I was done. so i dragged the text around just to see what happened then reset the text to 0 top 0 left and the hierarchy snapped into working order. I dunno what happened other then reentering those 0's seemed to fix it?

no big just passing it on

**Comment by jean-emmanuel** [comment]
Are you using css `z-index` as I suggested (http://osc.ammd.net/extras/css-tips/#layering-z-index) ?

**Comment by Sebastian-blu** [comment]
Well I didn’t do that because this one is not in a modal, I thought that was specific to layering in modals?

**Comment by jean-emmanuel** [comment]
Nope, this is genuine generic css :)
