### ISSUE TITLE
percent drag is great but adds small decimal amounts to left value

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#257]
love being able to drag and keep things in % mode but when I do it seems to create a an additional .06% on the end of what should be a number with no decimal

so if I drag something to 40% on the grid it goes to 40.06% or something like that. I don't know if its always the same thing

**Comment by jean-emmanuel** [comment]
Percentage are computed from absolute coordinates in pixels, you need some decimals to be accurate and have the widget positionned where you actually dropped it.

**Comment by Sebastian-blu** [comment]
Makes sense but I have the grid at the ten default, and it seems to be moving snapped to the grid. Then adding the small amount.

**Comment by jean-emmanuel** [comment]
The grid's width is in pixels, percentages are very unlikely to snap to the grid without some decimals.

**Comment by dumski** [comment]
Possible to allow grid to be defined in percents? It'd allow to resize elements and snap to the grid regardless of window size. For me it's a very important thing because I ofter edit sessions on other devices. 

@jean-emmanuel Thanks for your great work, BTW.
Cheers!

**Comment by jean-emmanuel** [comment]
The way it's currently implement doesn't make it possible. Btw I highly recommend building responsive interface using horizontal/vertical/grid layouts instead of absolute positionning + percent units.
