### ISSUE TITLE
possible to do a blend mode type thing with txt?

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#258]
so stacking text on rgb led is great but sometimes the led color ends up obscuring the text.. wondering if I could set my text to some like a difference blend mode found in photo editor so if text was white and the led that came on behind it was white then text would show as black?

**Comment by jean-emmanuel** [comment]
Try https://css-tricks.com/almanac/properties/m/mix-blend-mode/

**Comment by Sebastian-blu** [comment]
Ahh ok I’ll try that out looks promising
