### ISSUE TITLE
WebRTC Video viewer

### ISSUE THREAD

**Issue by hu-o** [jean-emmanuel/open-stage-control#259]
Salut ! 

OSC is amazing ! I'm trying to use it for live video control surfaces (Video mixing, VJing,...), so having the ability to have video views on the pages would be really great ! 

As very low latency is the key to these usages,  I think WebRTC could be an option. I'm experimenting with https://www.medialooks.com/ndi, a little new software that takes NDI or SDI live video feeds and convert them to WebRTC.

Any chance to have that kind of feature implemented one day ? What could be the approach if I want to add that ? 
 
Hugo

**Comment by jean-emmanuel** [comment]
I've done some tests, here's what _seems_ to be possible:
- a server option to define RTSP urls (`rtsp://...`) and encoding options (framerate, resolution, quality)
- a Stream widget that displays the video stream

I don't think very low latency (as in milliseconds) is possible here, but hopefully decent latency is.

**Comment by jean-emmanuel** [comment]
Yep, server-side ffmepg is what I had in mind, I just pushed a something to be tested if you can build the app from sources:
- set the server's `video-streams` option to a valid rtsp url
- create an Image widget and set its `stream` property to `0`

note:
- `video-streams`: one or multiple rtsp urls separated by spaces, and (optionnal) settings: framerate=<int> resolution=<int>x<int>
- `stream`: rtsp url index starting with at `0`.

**Comment by jean-emmanuel** [comment]
Maybe with a powerful computer you'll get decent latency, I can't tell with mine. 

I'm not going to implement any audio handling in O-S-C. Actually I'm not even sure yet this stream experimentation should be included in the end. Audio and video both come with specific performance concerns I'm not willing to address: separation of concerns is the key, O-S-C does the controls, not audio/video processing.

**Comment by hu-o** [comment]
Wow, that was fast !

Can't wait to try that, give me a day or two.

**Comment by hu-o** [comment]
![oscfreezed](https://user-images.githubusercontent.com/37731508/37922445-d9430726-312c-11e8-9df1-ee1f141f3d81.png)

If I try to specify a rtsp url, I got this error. This rtsp URL can be opened and work in VLC.

**Comment by jean-emmanuel** [comment]
You need to install ffmpeg : http://www.ffmpeg.org/download.html

**Comment by jean-emmanuel** [comment]
I've been giving this some thoughts and doing a few researchs, and I'm going to remove this from the core app. The proposed test is just a very simple conversion from rtsp stream to base64-encoded jpeg images that are sent to the Image widget. This is easy to handle externally and would avoid O-S-C being responsible for ffmpeg's state (which seems inconsistent). I'll create a repository to demonstrate that.

As for an actual WebRTC implementation, it's a real PITA as far as I can see and is not worth the effort given that the previous solution looks promising enough and matches O-S-C's logic.

**Comment by jean-emmanuel** [comment]
https://github.com/jean-emmanuel/rtsp2osc

**Comment by jean-emmanuel** [comment]
@jblanteigne @hu-o 
I've been thinking of another solution: adding a "frame" widget that would allow users to embed external http pages to their interface, you'd just have to configure a webrtc stream server that can be reached through http such as https://github.com/mpromonet/webrtc-streamer. What do you think ?

**Comment by hu-o** [comment]
That would be great, and not only for video preview. Integrating existing
web control pages in a OSC project makes sense for some use case where you
have equipment that already have web control.

Hugo

Le mar. 28 août 2018 à 11:32, jean-emmanuel <notifications@github.com> a
écrit :

**Comment by jean-emmanuel** [comment]
It's in git (widgets/plots/frame). https://github.com/jean-emmanuel/open-stage-control/blob/master/resources/docs/widgets/plots.md#frame

**Comment by jblanteigne** [comment]
Good idea. It will be lighter than converting the frames with ffmpeg. I will test whenever I have time. Thanks!

**Comment by jean-emmanuel** [comment]
@hu-o how has the iframe solution out so far for you ?

**Comment by jean-emmanuel** [comment]
@hu-o how did the iframe solution turned out so far for you ?
