### ISSUE TITLE
Widget xy

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#260]
J’avais l’impression d’avoir mis un poste hier mais plus moyen de le trouver.
Je voulais savoir, on peut separer les envoi osc d’un widget xy mais est ce que dans un autre widget on peut a l’aide des @{widget.propriete} on peut recupérer juste le y ou le x de ce widget? Ou meme faire la somme du x et du y?

**Comment by jean-emmanuel** [comment]
C'est possible en utilisant la valeur du xy dans une formule. Voilà quelques possiblitiés
```
#{
x = @{xy}[0];
y = @{xy}[1];
somme = @{xy}[0] + @{xy}[1];
somme = sum(@{xy});
}
```

**Comment by Adopo** [comment]
Ah d’accord. C’est un array ! C’est tout bête. Merci beaucoup !
