### ISSUE TITLE
How to build from sources

### ISSUE THREAD

**Issue by hu-o** [jean-emmanuel/open-stage-control#261]
Hi,

Following the previous topic, I'm trying to build the project from sources. I'm new to electron / web app dev / git, can you recommand tools ?

Thanks

**Comment by amir-arad** [comment]
these are the instructions as i recall them (I haven't done it in a year)
install [nodejs](https://nodejs.org/en/) and git
clone this repo `git clone git@github.com:jean-emmanuel/open-stage-control.git`
change working dir to the newly created directory
`cd open-stage-control`
install dependencies
`npm install` (this will take a while as it downloads and compiles a bunch of stuff)
build the program
`npm run build`
start it
`npm start`

**Comment by amir-arad** [comment]
oops, seems there's a clear official [documentation](http://osc.ammd.net/getting-started/#run-from-sources)

**Comment by hu-o** [comment]
Ooops, didn't saw it... Thanks !

**Comment by jean-emmanuel** [comment]
@amir-arad thank you !

**Comment by amir-arad** [comment]
oh no no no @jean-emmanuel , thank *you*! ;P

**Comment by hu-o** [comment]
I finally managed to build it from sources. When I launch the exe (windows) I can setup the options, but then when I click on "start" it freezes and nothing happens. Any idea ? is there logs somewhere ?

**Comment by jean-emmanuel** [comment]
Can you send a screenshot of  the launcher ?

**Comment by jean-emmanuel** [comment]
Wait I just saw the error, fixing in a sec.

**Comment by jean-emmanuel** [comment]
Ok you can run `git pull` and build again (don't forget `npm install`), it should be fixed.

**Comment by hu-o** [comment]
Thanks, it work now !
