### ISSUE TITLE
Trying to send out MIDI signals from computed value change

### ISSUE THREAD

**Issue by brunetton** [jean-emmanuel/open-stage-control#266]
Hi Jean-Emmanuel

## Abstract

I'll be using OpenStageControl to control/monitor setBfree (Hammond organ emulation) on a Raspberry Pi 3 for [live performance](https://calh-herlies.fr/la-nuit-du-blues-chti-blues-all-stars/) in a few weeks. I've almost finished but some little things have to be done so far. Here's one of them.

I'm trying to use a control wheel in my MK-361 controller to control Leslie effect (whirl) in [setBfree](https://github.com/pantherb/setBfree).
This effect has 3 positions that can be controlled by MIDI `Control Change` with 3 values:

- 0 -> off
- 64 -> slow
- 127 -> fast

Controlling the effect "as it" (sending wheel values directly to setBfree->whirl) makes setBfree map incoming CC values like that:

- [0-45] -> 0 (off)
- [46-89] -> 64 (slow)
- [90-127] -> 127 (fast)

But this default mapping is not very convenient while playing on stage, using a physical button: it's quite hard to get the "middle" position each time, sometimes I'm still on off, sometimes I'm already on fast.

## What I'm trying to get

After some testing, I found that this mapping would be great for my usage:

- [0-9] -> 0
- [10-120] -> 64
- [121-127] -> 127

### The json file

I [attached my current json file here](https://github.com/jean-emmanuel/open-stage-control/files/1863291/whirl_tests.json.txt) (adding `.txt` extension to make Github accept it ...)

### Explanations

I had the idea to use Open Stage Control new [formulas](https://osc.ammd.net/extras/advanced-property-syntax/#formulas) to compute my mapping from keyboard's wheel input:

    wheel input      Open Stage Control       setBfree
       CC 1      ->   compute mapping    ->    CC 91

To achieve my goal, I used two sliders:
- `kb_wheel`, that reads the raw wheel input from keyboard
- `wheel_enc` ("enc" stands for encoded), that transform that value using this formula in value property:

        #{
          @{kb_wheel} < 10 ? 0 : (
            @{kb_wheel} > 120 ? 127 : (
              64
            )
          )
        }

- I also added the switch button I'm using to control/monitor whirl status, linked with `wheel_enc` by "leslie" linkID. This is the switch that is intended to send MIDI CC values (on channel 91 in this particular example).

## Results and problems

The mapping computation works well: when I move my wheel, the `wheel_enc` and switch button are updated.

The problem is that no signal is sent by the 3 states switch when controlled via keyboard wheel (via computed `wheel_enc`). When I change switch state by touching it, its send the CC cignal, but not when it's changed "programmatically".
I tried different "implementations" as well, but I didn't managed to get this work.

Maybe this can't be achieved using Open Stage Control ? I'm guessing that it should exist a program dedicated to midi maths on signals values (with a conf file) but I didn't managed to find one :s And I prefer trying to get it done in OpenStageControl not to multiply the number of services I'm using.

Sorry for this long issue, but I'm trying to be as clear as possible to avoid you loose your time !

Thanks a lot for reading

**Comment by jean-emmanuel** [comment]
Hi, thanks for the very clear post :)

Indeed, widgets are not supposed to send any osc messages when updating their value after receiving osc messages.

[Mididings](http://das.nasophon.de/mididings/) is an awesome tool to manipulate and filter MIDI events in real-time with a very low latency, you should definitely give it a try.

**Comment by jean-emmanuel** [comment]
There would be a way to achieve it in O-S-C using a [custom module](http://osc.ammd.net/extras/custom-module/), although there is a little modification that needs to be done before it could work (osc messages converted from MIDI events are not passed to the custom module currently).

**Comment by jean-emmanuel** [comment]
OSC messages converted from MIDI events can now be filtered by the custom module (in git -> next release). Here's a minimal custom module example that would map incomming CC events as you described:

```js
(function(){

    return {
        oscInFilter:function(data){
            // Filter incomming osc messages

            var {address, args, host, port} = data


            if (host === 'midi' && port === 'a' && address === '/control') {

                var channel = args[0].value,
                    cc      = args[1].value,
                    value   = args[2].value,
                    mappedValue

                if (cc === 1) {

                    if (value < 10) {
                        mappedValue = 0
                    } else if (value < 120) {
                        mappedValue = 64
                    } else {
                        mappedValue = 127
                    }
                    sendOsc({
                        address: data.address,
                        host: data.host,
                        port: data.port,
                        args: [
                            args[0], // same channel
                            {type: 'i', value: 91}, // new cc
                            {type: 'i', value: mappedValue} // mapped value
                        ]
                    })
                    console.log({
                        address: data.address,
                        host: data.host,
                        port: data.port,
                        args: [
                            args[0], // same channel
                            {type: 'i', value: 91}, // new cc
                            {type: 'i', value: mappedValue} // mapped value
                        ]
                    })

                }


            }

            // return data if you want the message to be processed
            // the original data hasn't changed so the widgets will receive it as is
            return {address, args, host, port}

        }
    }

})()
```

**Comment by brunetton** [comment]
Thank you ! This is GREAT. I'll definitely try to find some time to play with that !
Thanks a lot 👍

**Comment by jean-emmanuel** [comment]
-> v0.29.0 :)

**Comment by jean-emmanuel** [comment]
Nice ! Feel free to open an issue :)
