### ISSUE TITLE
Astuce IOS landscape

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#267]
Hello. Voici un petit message car peut être que ça pourrait aider certaines personnes.
Depuis que le mode plein écran sur ipad est possible en rajoutant une page safari comme application sur l'écran d'accueil, open stage control marche à merveille que ce soit en portrait ou paysage.

Par contre sur un iphone/ipod, safari a la mauvaise habitude de se mettre en mode portrait quand on active le lockscreen. Ca fait plusieurs jours que je trifouille mon ipod 5 dans tous les sens dans l'espoir de casser ca. J'ai trouvé une solution pour IOS 9.3.5. Malheureusement il faut jailbreak son appareil et il je ne sais pas si ca fonctionne pour IOS 11 car ma version d'IOS sur mon iphone ne peut pas être jailbreak.

La solution : avec le tweak SBflip il est possible d'activer le mode landscape pour l'écran d'accueil. Mais ce qui fait que ca fonctionne par rapport aux autres tweak, c'est qu'il est possible de faire la même chose pour l'écran de vérouillage. Ceci activé il faut activer le lockscreen. Au début ca ne fonctionne pas, mais si on verouille l'appareil et qu'on le dévérouille, on se rends compte que le mode landscape est présent sur l'écran vérouillé et qu'il reste bloqué sur ce mode même quand on dévérouille l'écran. Ainsi on a open stage control en mode plein écran et en landscape !!!!! Alleluya !

**Comment by Adopo** [comment]
PS : il faut aussi dans sbflip activer l’option pour forcer le mode paysage

**Comment by jean-emmanuel** [comment]
Merci pour l'astuce ! Je me permet de fermer le ticket, ce sera toujours disponible si quelqu'un cherche ça :).

**Comment by Adopo** [comment]
Cool ! De rien ;-)
