### ISSUE TITLE
appareil multiple

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#268]
Petite question : je sais qu'il est possible d'utiliser différents appareils avec différentes interface open stage control. Par contre, est il possible de faire en sorte que chaque interface est un port OSC différent afin de pouvoir par exemple qu'un appareil prenne en compte un message OSC à un autre appareil ou est ce que tout est envoyé forcément au même port? 

Ca pourrait être une amélioration utile dans certains cas si pour le moment ce n'est pas possible mais je ne sais pas dans quelle mesure c'est réalisable

**Comment by jean-emmanuel** [comment]
Ce n'est pas possible ni prévu avec un seul serveur, il faut lancer plusieurs serveurs pour cela.

**Comment by Adopo** [comment]
Est il possible de lancer plusieurs serveur sur une seule machine? Genre d’avoir deux open stage control qui tournent?

**Comment by jean-emmanuel** [comment]
Tout à fait, il faut juste leur assigner des ports différents (changer l'option `port` suffit, Par défaut ça change le port http et le port osc)
