### ISSUE TITLE
Modifier un widget a la reception d'un message OSC

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#269]
J'avais l'impression qu'il y avait déjà un post la dessus mais plus moyen de le retrouver...

Est il possible de modifier par exemple le label d'un widget en fonction de la reception d'un message OSC différent du message OSC envoyé par le widget en question?

**Comment by jean-emmanuel** [comment]
hop,
- la discussion de la feature : https://github.com/jean-emmanuel/open-stage-control/issues/191#issuecomment-372457300
- la doc : http://osc.ammd.net/extras/advanced-property-syntax/#osc-listeners-osc

**Comment by Adopo** [comment]
Merci !

**Comment by Adopo** [comment]
Désolé je relance ici car malgré les liens j’arrive pas a faire fonctionné la reception OSC.
Je cherche a receptionner un message osc /selectpage me permettant a sa reception d’aller de tab root en tab root. De base j’envoi en argument osc un int de valeur 1 j’ai essayé aussi un float et ca ne réagit pas.

Voici l’etat de mon code actuel :
#{
OSC{/selectpage,0}>=0?valeur=2:0;
valeur
}

Je cherchais pour le moment a aller des la reception d’un message osc a me rendre au tab 2. La finalité serait un code du genre qui incrementerai @{this} a la reception du message avec un sorte de variable definie remettant le compteur à zero si on depasse le tab max. par exemple sur mon ipod j’ai 3 tab donc des que je depasse 2 je reviens à zéro.

**Comment by Adopo** [comment]
Mon code doit vraiment pas etre bon car je n’arrivais plus a ouvrir le projet a cause de ce code

**Comment by jean-emmanuel** [comment]
Il y a une erreur dans ton écriture conditionnelle : la partie après le signe deux-points n'assigne pas la variable `valeur`, et la ligne suivante échoue losque la valeur osc est inférieure à 0. Il faudrait mettre à la place
```
#{
OSC{/selectpage,0}>=0?valeur=2:valeur=0;
valeur
}
```
ou
```
#{
valeur = OSC{/selectpage,0}>=0?2:0;
valeur
}
```

Le fait que la session ne s'ouvre plus est assez récurrent sur ce genre d'erreur, j'essaye de rendre les choses plus souple à ce niveau là mais il y a encore de la marge..

**Comment by Adopo** [comment]
Ah d’accord. En effet le projet ne crash plus. Par contre ca ne fonctionne toujours pas.
Après plusieurs tests, je remarque que ce petit code une fois écrit mets directement la valeur a 2 et switch sur le tab 2 quand je valide le code. Alors que je n’ai envoyé aucun message osc. Par contre apres j’envoi le message osc il ne se passe plus rien meme si change manuellement de tab. Et si par exemple dans la condition je remplace 2 par 1 des que je valide mon code il passe sur le tab 1 puis ne réagit plus.

**Comment by jean-emmanuel** [comment]
C'est normal, `valeur = OSC{/selectpage,0}>=0?2:0;` signifie «si OSC{0 par defaut} est égal ou supérieur à 0, valeur = 2, sinon valeur = 0»

**Comment by Adopo** [comment]
Ah d’accord. J’imaginais que si on ne lui envoyais pas d’osc il ne prenez pas en compte ma formule.
Désolé de te solliciter autant sur ce problème ca fonctionne mais j’arrive toujours pas a arriver au but de ce que je veux faire.
Des que j’utilise @{this} sur le root pour incrémenter sa propre valeur il affiche toutes les tab en meme temps.

J’en suis là :
#{
is_plus = OSC{/selectpage,0}>=1?1:0;
valeur=@{this}>=2?0:@{this}+1
}

**Comment by jean-emmanuel** [comment]
Je ne suis pas sûr de bien comprendre ce que tu veux faire, tu peux m'expliquer ? En tout cas ce n'est pas la bonne manière d'y parvenir : chaque changement de tab déclenche le calcul de la formule car la valeur de @{this} change, cela crée une boucle infinie.

**Comment by Adopo** [comment]
D’accord je vois. En effet ce n’est pas la bonne solution alors.
En fait j’ai un controleur qui envoi un message osc unique : /selectpage avec la valeur int 1 quand il est actionné.
L’objectif serait qu’a chaque fois que je recois ce message OSC j’aille ai tab principal suivant. Pour l’instant j’ai 3 tab. Arrivé au dernier il faudrait qu’il revienne au premier.
Ainsi avec mon controleur je pourrais défiler les tabs via se controleur.
Je fais ca car sur scene j’ai un gant controleur et mon ipod etant accroché au bras j’ai des difficulté a cliquer sur les tabs. Donc j’avais trouvé cette astuce pour palier a ca

**Comment by Adopo** [comment]
J’ai fais autrement. J’ai fais en sorte que mon logiciel envoi un message osc desormais appelé /selecttab qui a une valeur qui s’incrémente et qui revient à zéro apres 2. Et dans la valeur je mets juste la la valeur osc de ce message.
Mais si un moment tu trouve comment faire ce genre de chose dans ton logiciel je suis preneur.
