### ISSUE TITLE
Can't edit a full container.

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#27]
If a strip or panel is full of widgets. It can not be selected to edit. This is particularly noticeable with the strip container where the widgets auto size to fill the strip. I would suggest that being able to select a widget by clicking on it from the list in it's parents list of widgets would be the best way of doing this.
(I have been getting around this by removing enough widgets from a strip to have open space to click on)

**Comment by ovenwerks** [comment]
I guess I should add that I often replace the container label with a text widget so the label can be changed remotely such as when a set of mixer strips is banked. So container label = false. It becomes easy to cover all the strip or panel real estate.

**Comment by jean-emmanuel** [comment]
> I would suggest that being able to select a widget by clicking on it from the list in it's parents list of widgets would be the best way of doing this.

This was the expected behaviour but it's been broken, and will be fixed soon !
