### ISSUE TITLE
indicateur batterie

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#270]
Proposition d'amélioration : le plein écran n'indique pas l'indicateur batterie. Ca pourrait être chouette d'avoir un petit widget qui est capable d'indiquer la batterie de l'appareil.
Ou alors peut être que c'est récupérable en javascript pour le mettre dans un widget text?

**Comment by jean-emmanuel** [comment]
Malheureusement ce n'est pas possible sans faire une application native, dommage! Cela a été possible pendant un temps dans les navigateurs mais l'API à été supprimé des standards et n'est plus du tout supportée.

**Comment by Adopo** [comment]
Arf dommage. Tant pis le fait que ce ne soit pas une application native est plus intéressant !
