### ISSUE TITLE
Css label strip

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#271]
Hello, je voudrais savoir si il y a moyen de choisir la couleur de fond du la banderole en haut d’un strip pour le label. D’ailleurs la je travaille sur un strip mais j’imagine que ma question pourrait se poser sur tout les banderoles labels de widget.
Les styles css s’appliquent a l’interieur du widget non a la banderole. Pour le moment j’ai essayer de triturer directement dans la case label du genre : <div style="width:400px;line-height:100px;background-color:green;">in</div>
Mais j’ai beau mettre des tailles en px ou en pourcentage j’ai presque réussi a y arriver mais j’ai deux bandes de chaque côté qui ne se colorent pas.

Peut être serait il intéressant d’avoir une propriété widget pour y mettre directement la couleur.

**Comment by jean-emmanuel** [comment]
Il faut utiliser les sélécteurs css : http://osc.ammd.net/extras/css-tips/#selector-syntax
```
:host {
  /* ici le css pour le widget lui même */
}
.label {
  background-color: red; /* bouya ! */
}
```

**Comment by Adopo** [comment]
Ah cool ! Etrange j'avais essayé avec la classe label mais j'ai du faire n'importe quoi. La ca marche niquel. Par contre du coup :host ca peut être chouette aussi ! mais est ce qu'on a acces au border. Car j'ai essayé d'atteindre les border avec cette technique du genre border-style: solid;border-style:red; et ca ne fonctionne pas

**Comment by jean-emmanuel** [comment]
ok :)
