### ISSUE TITLE
A propos du display:none; problème initialisation

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#272]
Je reviens sur un sujet dont on a déjà parlé mais je créé une nouvelle issue car le problème est différent.
Je cherchais il y a peu a cacher des widgets. Il y avait la technique qui consistait à mettre les tailles à zéro mais les bordures de widgets sont susceptible de se voir encore.
La solution était donc le display:none; dans le css.
Sauf que sur les fader et les xy j’ai remarqué un petit bug.
Lorsque l’on charge un projet sur un appareil, les faders et les xy ainsi cachés ne s’initialisent pas. Le fader n’a plus de niveau et le xy perds son point. La seule solution pour le faire revenir et d’avoir un évènements qui lui redéfinisse une valeur mais au touché rien ne change.

**Comment by jean-emmanuel** [comment]
Hop, corrigé pour la prochaine version, merci.

**Comment by jean-emmanuel** [comment]
v0.28.3
