### ISSUE TITLE
donner accès à la prop globalAlpha pour les meters

### ISSUE THREAD

**Issue by guitmart** [jean-emmanuel/open-stage-control#274]
bonjour Jean-Emmanuel,
j'aimerais savoir si c'était possible d'avoir accès à l'opacité des meters car je voudrais qu'ils soient plus voyant.
Merci.

**Comment by jean-emmanuel** [comment]
Salut, oui ça pourrait être pas mal je vais faire ça via une variable css `--gauge-opacity` ce sera valable pour les faders/knobs aussi.

**Comment by jean-emmanuel** [comment]
Ajouté pour la prochaine version, seulement pour les _faders_ en mode _compact_ et les _meters_ finalement.

**Comment by jean-emmanuel** [comment]
Il suffira donc d'ajouter `--gauge-opacity:0.8;` (par example) à la propriété css du widget pour définir une opacité fixe.

**Comment by guitmart** [comment]
super merci

2018-04-07 6:11 GMT-04:00 jean-emmanuel <notifications@github.com>:

**Comment by jean-emmanuel** [comment]
-> v0.29.0
