### ISSUE TITLE
fader ne fonctionne pas sur ipad

### ISSUE THREAD

**Issue by blueunicorn1234** [jean-emmanuel/open-stage-control#275]
je n'arrive pas a bouger les fader ou tout widget incluant un mouvement a partir d'un appareil sur ios.
les boutons marche mais tout ce qui implique un deplacement ne repond pas.

merci de ce merveilleux logiciel.

**Comment by jean-emmanuel** [comment]
Salut,
Quel iPad as-tu exactement ? Le système iOS n'est supporté qu'à partir de la version 9.3.

**Comment by jean-emmanuel** [comment]
Ah oui, gros bug qui devait trainer depuis un moment... réglé dans la v0.29.0 !
