### ISSUE TITLE
broadcast can not be used

### ISSUE THREAD

**Issue by naotobando** [jean-emmanuel/open-stage-control#276]
A broadcast address (in my case 192.168.100.255) was not available.
When I use  an individual IP addresses it works perfectly.

<img width="686" alt="2018-04-11 14 24 11" src="https://user-images.githubusercontent.com/38273637/38597696-1d02be70-3d94-11e8-8da6-ecb3316c16e1.png">

**Comment by jean-emmanuel** [comment]
> v0.29.1
