### ISSUE TITLE
Value switcher

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#277]
Hello. Ca faisait quelque temps que je n’avais pas remis le nez dans open stage control. Je m’y remets et je m’attarde cette fois sur le widget switcher.
Je voulais faire apparaître d’autres Widgets en fonction de la valeur du switcher. Je ne comprends pas trop comment on peut récupérer la valeur active du widget. Pour le switch il on peut faire un truc du genre @{switch}==1?ok:pasok mais avec switcher cela ne fonctionne pas. 
Comment doit on procéder ?

**Comment by jean-emmanuel** [comment]
Effectivement c'est un peu plus subtil, la valeur du switcher contient plus que son propre état, tu peux acceder à l'état du commutateur comme suit : #{@{switcher}._selected}`
Pour le crossafader, la valeur du fader est accessible comme cela : `#{@{switcher}._fader}`

Ce n'est pas hyper évident ni documenté, ça a été fait avant la logique de propriétés dynamiques.

**Comment by Adopo** [comment]
Ah d’accord ! Merci beaucoup !
