### ISSUE TITLE
Open a project automatically without clicking START

### ISSUE THREAD

**Issue by LDaVeM** [jean-emmanuel/open-stage-control#278]
Hi,

Sorry if this question has already been asked.
is it possible to launch the application automatically on a project without having to click on Start?
Basically the idea is that as soon as a machine turns on, it automatically starts a project without the need to intervene on it

Thk's 

David

**Comment by jean-emmanuel** [comment]
Hi,
You can launch the app with command line arguments (from a terminal), the launcher is just an interface to help setting them, check out the examples in http://osc.ammd.net/getting-started/
There are multiple way to run a command-line application at startup depending on the system you're using.
I hope this will get you on track :)
