### ISSUE TITLE
Default targets

### ISSUE THREAD

**Issue by micpool** [jean-emmanuel/open-stage-control#279]
If a default target is set in the send field of the main Open Stage Control window does a target set in a widget override this. If it meant to I can't get it to work. e.g.

[
  "127.0.0.1:10052"
]

**Comment by jean-emmanuel** [comment]
Widget's targets are not meant to override the default targets, current behavior is intended.

**Comment by jean-emmanuel** [comment]
The `null̀` target can now be used with regular targets to override the global default targets (it used to disable osc sending completely but there is the `bypass` option for that now) :)

**Comment by jean-emmanuel** [comment]
-> v0.30.0
