### ISSUE TITLE
open stage control application won't launch

### ISSUE THREAD

**Issue by micpool** [jean-emmanuel/open-stage-control#280]
had an error after I wrongly configured multiple port pairs and now can't start the app. Main window opens but I only get a blank window with a  spinning circle icon instead of the list of start options.

I've re downloaded the app and trashed the applicant support folder, but it still won't start.

**Comment by micpool** [comment]
console log

21/04/2018 19:09:31.810 open-stage-control[1168]: Can't open input server /Library/InputManagers/QuicKeysIM
21/04/2018 19:09:31.873 open-stage-control Helper[1171]: GVA warning: failed to get a service for display id: 4128835
21/04/2018 19:09:31.873 open-stage-control Helper[1171]: GVA warning: failed to get a service for display id: 4128836
21/04/2018 19:09:31.873 open-stage-control Helper[1171]: GVA warning: failed to get a service for display id: 4128837
21/04/2018 19:09:31.874 open-stage-control Helper[1171]: GVA warning: failed to get a service for display id: 4128838
21/04/2018 19:09:31.874 open-stage-control Helper[1171]: GVA warning: failed to get a service for display id: 4128840
21/04/2018 19:09:31.874 open-stage-control Helper[1171]: GVA warning: failed to get a service for display id: 4128839

**Comment by micpool** [comment]
I think I have now tried reinstalling open stage control and chrome, and deleting every plist and preference file that could possibly be used at startup. When I launch open stage control.app I just get a blank window with a spinning circle. I am obviously missing a file decency which is corrupt or missing, any ideas where to look next?

**Comment by jean-emmanuel** [comment]
Did you delete the file named `.open-stage-control` in your home folder ? If not there might be some relevant informations in it.

**Comment by jean-emmanuel** [comment]
File names beginning with a period are hidden under mac (and linux), there should be a hidden file named `.open-stage-control` in your home folder.

**Comment by micpool** [comment]
Yes that's fixed it, thanks very much

I'm a huge fan of the program, I think it has huge potential and have huge admiration for the work you have invested in this as free software

It would be very useful to have all the file  dependencies th program needs to run  listed. This is the second time I have been caught not being able to run the program for a few days,  despite reinstalling everything I could think of and trashing preferences etc.. In an experimental situation this doesn't matter too much , but it would be very difficult to deploy on major projects without the confidence that if the program ceased to function in similar circumstances I couldn't rapidly solve the problem by deinstalling and reinstalling.

**Comment by jean-emmanuel** [comment]
I'll mention this in the docs. I assume you've deleted the file, by any chance do you remember what you put in the options that could have caused the bug ?

**Comment by micpool** [comment]
I retrieved the file from time machine

{
    "argv": {
        "_": [],
        "help": false,
        "h": false,
        "blank": false,
        "debug": false,
        "no-gui": false,
        "noGui": false,
        "examples": false,
        "disableVsync": false,
        "disableGpu": false,
        "readOnly": false,
        "version": false,
        "v": false,
        "$0": "Users/micpool/Desktop/open-stage-control.app/Contents/MacOS/open-stage-control",
        "l": "/Users/micpool/Desktop/bigknob.json",
        "s": [
            null
        ]
    },
    "recentSessions": [
        "/Users/micpool/Desktop/bigknob.json",
        "/Users/micpool/Desktop/OpSC Faders.json",
        "/Users/micpool/Desktop/2018-03-29_09-47.json",
        "/Users/micpool/Desktop/Qlab cookbook stuff/QLab control Catalyst/jsons/4VL3000s.json",
        "/Users/micpool/Desktop/Qlab cookbook stuff/QLab control Catalyst/jsons/VL3000rig.json",
        "/Users/micpool/Desktop/Qlab cookbook stuff/QLab control Catalyst/jsons/8VL3000.json",
        "/Users/micpool/Desktop/Qlab cookbook stuff/QLab control Catalyst/jsons/RGBCMY.json",
        "/Users/micpool/Desktop/Qlab cookbook stuff/QLab control Catalyst/jsons/catalystMediaServerQLabController.json",
        "/Users/micpool/Desktop/Qlab cookbook stuff/QLab control Catalyst/jsons/Pannerhelper.json",
        "/Users/micpool/Desktop/Qlab cookbook stuff/QLab control Catalyst/jsons/OSCinOut.json",
        "/Users/micpool/Desktop/Qlab cookbook stuff/QLab control Catalyst/jsons/New maths.json",
        "/Users/micpool/Desktop/Qlab cookbook stuff/QLab control Catalyst/jsons/subtract.json",
        "/Users/micpool/Desktop/Qlab cookbook stuff/QLab control Catalyst/jsons/Catalyst won't open.json",
        "/Users/micpool/Desktop/CatalystQLab.json",
        "/Users/micpool/Desktop/dropdown.json",
        "/Users/micpool/Desktop/dropdown no val.json",
        "/Users/micpool/Desktop/Math's won't open.json",
        "/Users/micpool/Desktop/Maths.json",
        "/Users/micpool/Desktop/subtract.json",
        "/Users/micpool/Desktop/2018-02-09_14-55.json",
        "/Users/micpool/Desktop/2018-02-09_14-32.json",
        "/Users/micpool/Desktop/2018-02-09_14-30.json",
        "/Users/micpool/Desktop/2018-02-09_14-12.json",
        "/Users/micpool/Desktop/2018-02-09_14-24.json",
        "/Users/micpool/Desktop/2018-02-09_14-20.json",
        "/Users/micpool/Desktop/2018-02-09_14-05.json",
        "/Users/micpool/Desktop/2018-02-09_13-49.json",
        "/Users/micpool/Desktop/2018-02-09_13-57.json",
        "/Users/micpool/Desktop/CatalystQLab2.json",
        "/Users/micpool/Desktop/2018-02-09_01-02.json",
        "/Users/micpool/Desktop/2018-02-09_01-19.json",
        "/Users/micpool/Desktop/2018-02-09_00-36.json",
        "/Users/micpool/Desktop/2018-02-09_11-55.json",
        "/Users/micpool/Desktop/2018-02-09_11-36.json",
        "/Users/micpool/Desktop/2018-02-08_20-39.json",
        "/Users/micpool/Desktop/2018-02-08_17-00.json",
        "/Users/micpool/Desktop/2018-02-08_16-37.json",
        "/Users/micpool/Desktop/2018-02-08_14-32.json",
        "/Users/micpool/Desktop/2018-02-08_14-27.json",
        "/Users/micpool/Desktop/2018-02-08_12-59.json",
        "/Users/micpool/Desktop/2018-02-08_13-04.json",
        "/Users/micpool/Desktop/2018-02-08_13-07.json",
        "/Users/micpool/Desktop/2018-02-08_13-23.json",
        "/Users/micpool/Desktop/2018-02-08_12-44.json",
        "/Users/micpool/Desktop/2018-02-08_11-44.json",
        "/Users/micpool/Desktop/2018-02-08_11-39.json",
        "/Users/micpool/Desktop/2018-02-08_11-40.json",
        "/Users/micpool/Desktop/Catalyst.json",
        "/Users/micpool/Desktop/2018-02-08_02-44.json",
        "/Users/micpool/Desktop/2018-02-08_11-17.json",
        "/Users/micpool/Desktop/subs.json",
        "/Users/micpool/Desktop/subs copy.json",
        "/Users/micpool/Desktop/2018-02-07_02-40.json",
        "/Users/micpool/Desktop/2018-02-07_02-33.json",
        "/Users/micpool/Desktop/rgb master.json",
        "/Users/micpool/Desktop/RGBFixture.json",
        "/Users/micpool/Desktop/rgb masterfade.json",
        "/Users/micpool/Desktop/Lighting v2.json",
        "/Users/micpool/Desktop/2018-02-03_15-09.json",
        "/Users/micpool/Desktop/lighting.json",
        "/Users/micpool/Desktop/2018-02-03_12-50.json"
    ]
}


I think it happened after I put multiple destinations in the default field with the incorrect syntax, but I can't see the record for these in this file.

**Comment by jean-emmanuel** [comment]
> ```
> "s": [
> null
> ]
> ```

That's the problem, `--send` was indeed malformed, null is not a valid target here. I don't understand how you managed to get this saved though, the launcher shows an error and prevent saving/starting when an option is not properly written:

![screenshot-2018-04-24-13 42 19](https://user-images.githubusercontent.com/5261671/39184853-5df11f04-47c5-11e8-9e32-87f54a481b7d.png)

**Comment by micpool** [comment]
Try 
"127.0.0.1":"53000"

**Comment by jean-emmanuel** [comment]
Alright ! I'll make it robust to this case and try to make the launcher more tolerant to errors.

**Comment by micpool** [comment]
Thanks. There probably won't be anyone else who will attempt something so idiotic as making the destination spec a pair of strings, but you never know.

**Comment by jean-emmanuel** [comment]
Done!
