### ISSUE TITLE
Changing default send 

### ISSUE THREAD

**Issue by micpool** [jean-emmanuel/open-stage-control#281]
If you change the default send, existing widgets do not send to the new destination but newly created ones do.

e.g 
open open-stage-control
set default to 127.0.0.1:10051
load blank workspace
add slider
save file and quit
open open-stage-control
set default to 127.0.0.1:10052
set saved file to load
original fader does not send to 127.0.0.1:10052
create a new fader
new fader sends to 127.0.0.1:10052

**Comment by jean-emmanuel** [comment]
I'm unable to reproduce this behavior when following the steps your describe (defaults targets are not stored in session files anyway).

**Comment by micpool** [comment]
Sorry, I can't either now. I'll let you know if it crops up again

**Comment by jean-emmanuel** [comment]
ok !
