### ISSUE TITLE
Probleme avec un fichier sur un seul appareil

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#282]
Hello. J'ai un soucis un peu étrange. J'ai améliorer l'interface de mon ipod. Mais je ne sais pas pourquoi j'ai une erreur quand je veux la lancer avec mon ipod : 
TypeError: this.getProp('css').replace is not a function. (in 'this'.getProp('css').replace(/\{[^\}*\}/g,'')', 'this.getProp('css').replace' is undefined)

J'espère l'avoir bien recopiée car je l'ai fais manuellement. Car curieusement, cette erreur n'apparait que sur l'ipod. Je peux charger le fichier sans probleme sur mon ordi. Et sur un ipad ca fonctionne aussi. je ne comprends pas pourquoi ca ne veux pas se lancer sur l'ipod sachant que tout autre fichier fonctionne dessus. 

Voici le fichier en piece jointe.
[Ipod 7 .json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1959300/Ipod.7.json.txt)

**Comment by jean-emmanuel** [comment]
C'est un bug dans la gestion de la propriété `css` qui est un peu différente pour iOS 9. Corrigé à l'instant, je publie la v0.29.2 ce matin.

**Comment by Adopo** [comment]
ok chouette ! merci !
