### ISSUE TITLE
Impossible to open session files

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#285]
Hello,

I've installed version 0.301 for Windows 64 bit. I have created the "Open Stage Control" folder and renamed the subfolder extracted from the .zip into "open-stage-control-win32-x64". However when trying to open an example session, I have error messages "invalid session file".

**Comment by jean-emmanuel** [comment]
Does it happen from the online demo too ? http://openstagecontrol.herokuapp.com/

**Comment by nesdnuma** [comment]
I wonder if it might be because I renamed the folder after zip archive extraction: I removed the version number in the folder's name. Anyway now in version 0.30.3 everything seems to be fine (no renaming made).

**Comment by jean-emmanuel** [comment]
Hmm, as said in https://github.com/jean-emmanuel/open-stage-control/issues/291#issuecomment-387755076, it really sounds like a corrupted archive download... If you manage to reproduce the issue by renaming the folder let me know though.
