### ISSUE TITLE
feature request: option to make sliders jump to touch position, possibly with smoothing

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#287]
Hello,

IMHO one advantage of sliders on a touchscreen versus sliders on a real mixer is the possibility to put your finger anywhere on the slider and make the slider "jump" to this point immediately, possibly with an adjustable smoothing time.

**Comment by jean-emmanuel** [comment]
The fader's [snap](https://osc.ammd.net/widgets/sliders/#snap) options does that. You can also enable traversing gestures in the sidepanel to make this enabled globally. I'm not planning to implement timing/easing anytime soon sorry.

**Comment by nesdnuma** [comment]
I have tried these features but then the slider always goes to minimum and won't move from there...
