### ISSUE TITLE
can't move upper slider on range slider on touchscreen, functions with mouse

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#288]
I want to move the upper slider in the range slider. It doesn't function when using a touchscreen. However it does function with the mouse.

The lower slider moves as expected.

**Comment by nesdnuma** [comment]
Same issue with the encoder and the knob.

**Comment by jean-emmanuel** [comment]
There is a big regression breaking many things for touch events, I'm going to fix it asap. Thanks for your feedback.

**Comment by nesdnuma** [comment]
It seems to affect the multixy too (no touch at all reported) but the "single" xy functions as expected.

**Comment by jean-emmanuel** [comment]
Fixed in v0.30.3 (build/upload in progress)
