### ISSUE TITLE
Is there any way to create interactions between widgets?

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#289]
I'd like one widget to appear when pushing a button and another one instead when pushing another button.

**Comment by jean-emmanuel** [comment]
Yes, using https://osc.ammd.net/extras/advanced-property-syntax/ and css. For example, to hide a widget if some toggle is enabled, you'd set the widget's css property as follows:

```css
#{
@{toggle_id} ? "display:none;" : ""
}
``` 

This involves advanced features, you should consider reading the manual (including referenced external documentations) carefully.

**Comment by jean-emmanuel** [comment]
note: for simple value interaction, use the `linkId` property (https://osc.ammd.net/widgets/widgets/#linkid)
