### ISSUE TITLE
Can't use bulk editing to move/resize objects

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#290]
This issue was the main reason why I opened issue  #286. Bulk editing is nice to change widget's features but I would like to group objects to move or resize them and currently it doesn't work.

**Comment by jean-emmanuel** [comment]
You can either:
- select multiple widgets (they must have the same parent) and resize/move them using the appropriate handles (resize/move calculation is base on the first selected widget)
- wrap the widgets in a container and make their dimension relative to the container's using percentages

**Comment by jean-emmanuel** [comment]
:)
