### ISSUE TITLE
Desktop touchscreen compatibility

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#292]
I have noticed that widgets which one would expect to be multitouch-compliant. Are not. For instance, I can't move both upper and lower sliders in range slider simultaneously. Also, I can't move several points in a multixy simultaneously. It's annoying because multitouch is the very first reason for me to try Open Stage Controller. Also, if I activate snap in the multixy. I can't move any point anymore with the touch interface (but I can still do it with the mouse again...). If I reduce the number of points to 1 it functions as expected as long as I don't put an additional finger on the device because in this case the point either seem to be constrainded by all the touches. Then if I remove my fingers and put them again on the widget the point won't move anymore. There's definitely something strange with the touch tracking...

**Comment by jean-emmanuel** [comment]
Did you have "traversing gestures" enabled when you encountered the issue ? I've found and fixed another regression that might be involved here. You can check it out with the online demo.

**Comment by jean-emmanuel** [comment]
By the way what's your touch device exactly ?

**Comment by nesdnuma** [comment]
No, traversing gestures were off. The device is a Hanns G HT225.

**Comment by nesdnuma** [comment]
What about multi-touch inside a widget?

**Comment by nesdnuma** [comment]
By the way, I have now set inpiut to off, but I do still have all the widgets stopping to respond to touches. I think it has something to do with switching to another app and/or putting the focus on another screen because to write this message I have my browser opened on one screen and Open Stage Control opened on an other one.

**Comment by nesdnuma** [comment]
I can't even open the editing drawbar anymore.

**Comment by nesdnuma** [comment]
No change to the multixy after update 0.30.4

**Comment by jean-emmanuel** [comment]
Multixy and range sliders _are_ multitouch, there might actually be a problem with how chrome handles the touchscreen, multitouch has been designed with tablets in mind, I never had a chance to try a desktop multitouch screen.

**Comment by jean-emmanuel** [comment]
Could you try accessing the app with google chrome and check if it behaves the same way ?

**Comment by nesdnuma** [comment]
OK. By the way, I still have some slider or range widgets stopping to respond to controls (both touches and mouse) at some point.

**Comment by nesdnuma** [comment]
Same issue with multitouch with Google Chrome in 0.30.4.

**Comment by jean-emmanuel** [comment]
Thank you. From what I've read, there are definitely compatibility issues with touchscreens on chrome.

**Comment by jean-emmanuel** [comment]
You can try with google chrome canary in case it's been fixed recently but not yet release to the stable channel.

**Comment by nesdnuma** [comment]
I've just tried and Chrome Canary doesn't change anything. However, as I am usually not going trough a browser, isn't there another solution?

**Comment by jean-emmanuel** [comment]
The default client is an embedded chrome browser. Unfortunately I can't think of any solution for now, hopefully things will be fixed upstream (https://github.com/electron/electron/issues/8725)

**Comment by davismiculis** [comment]
@nesdnuma You can try using Brave Browser version of Electron, it helped me with touch screen problems. See my comment https://github.com/electron/electron/issues/8725#issuecomment-382350002

**Comment by jean-emmanuel** [comment]
@davismiculis good idea, thank you !

**Comment by nesdnuma** [comment]
Hello, I've just tested the Bravo browser. Indeed is doesn't seem to freeze at all. However multitouch is still not handled within single objects (range, multixy...).

**Comment by jean-emmanuel** [comment]
Could you try again with the online demo ?

**Comment by nesdnuma** [comment]
Doesn't function in Brave. I get an empty page with a black screen.

**Comment by jean-emmanuel** [comment]
Multitouch widgets are working fine again on tablets in v0.31.0. Does multitouch work in https://soulwire.github.io/sketch.js/examples/drawing.html ?

**Comment by Manaberry** [comment]
It does. On both main touchscreen and tablet.

**Comment by jean-emmanuel** [comment]
Thank you !

@nesdnuma still not working on your side ? Sounds like a hardware compatibility issue that's out of my reach, although it might just get solved at some point with chromium/electron updates.
