### ISSUE TITLE
Touch issues with slider and range widgets

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#293]
sometimes, when using sliders and range, the number showing the slider's value(s) become highlighted and a blinking cursor appears next to the number(s) as if one wanted to change them with a keyboard. Is there a way to prevent this to happen? This has also a strange consequence: the slider or the slider of some other widget can't be move anymore.

**Comment by jean-emmanuel** [comment]
I've decided to change this : long touch / right-click won't give focus to value input in next version.

**Comment by nesdnuma** [comment]
I approve! :-)
