### ISSUE TITLE
feature request: inactive color panels to put behind widgets

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#295]
This would help to identify widgets or groups of widgets just by the background color.

**Comment by jean-emmanuel** [comment]
You can use the `css` property to do/hack that your way :)

**Comment by nesdnuma** [comment]
Mhhh... ...another language to learn! :-))

**Comment by jean-emmanuel** [comment]
Haha yes, sorry about that, the thing is I'm trying not to add an option for each use case and rather make things hackable.

**Comment by nesdnuma** [comment]
So, I've added a panel.

I've tried this code in the CSS field: :host{"background-color": blue;} but it doesn't function. I have also tried wihtout ":host" and without the brackets. Same results.

**Comment by jean-emmanuel** [comment]
In this case the color is defined one level deeped in the widget: `.panel{background-color:blue}` would work. Playing with css often requires to dig into the widget's structure with the inspector (F12). I'll add this case to the CSS Tips page (https://osc.ammd.net/extras/css-tips/).

**Comment by nesdnuma** [comment]
OK, I see. Thanks!

**Comment by nesdnuma** [comment]
Indeed it works!
