### ISSUE TITLE
Slider and range widgets stop to track touch

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#296]
For instance, in the attached screen caption, the range widgets (in the red square) have stopped to track touches, then some seconds later the sliders in the green square have stopped too. All the others widgets are still tracking the touches correctly.

I can still move the range widgets with the mouse but on the sliders it doesn't even function.

Could it have something to do with the fact that each of these ensembles of widgets have been grouped together at some point to change their color?

![capture d ecran 94](https://user-images.githubusercontent.com/6513218/39840695-99dbc380-53e0-11e8-834a-398e9cd7eeb8.jpg)

**Comment by nesdnuma** [comment]
And now nothing works anymore. I think it has something to do with me switching the focus to my borwser to write the previous message...

**Comment by jean-emmanuel** [comment]
This is related to https://github.com/jean-emmanuel/open-stage-control/issues/292 and look very much like what I've read online about it. Please write in the other issue instead.
