### ISSUE TITLE
why is there a dependency on ffmpeg?

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#297]
It has been discussed on issue https://github.com/jean-emmanuel/open-stage-control/issues/259, but I thought you had reverted your commit, @jean-emmanuel ?

**Comment by jean-emmanuel** [comment]
Fixed in latest release

**Comment by jean-emmanuel** [comment]
This step just replaces the default chromium ffmpeg library with one that's compatible with the GPL3 license. Yes, it's is required by electron/chromium to run (https://github.com/electron/electron/issues/6242#issuecomment-228579972), although I haven't tried
