### ISSUE TITLE
TCP Support?

### ISSUE THREAD

**Issue by mesayre** [jean-emmanuel/open-stage-control#298]
I'd like to have two-way communication between Open Stage Control and my DAW (Digital Performer), but it only supports two-way via TCP, not UDP.

Are there plans to support TCP connections?

 I'm open to customizing the code to do this myself if you don't intend to support it in your app, but I'm a novice at this stuff. Any suggestions would be appreciated.

Thanks for the great work on this so far. Really stellar app.

**Comment by jean-emmanuel** [comment]
Thanks for the kind word :)
TCP support is actually something I'd like to implement someday, I'll try to look into this soon.

**Comment by mesayre** [comment]
Thanks for the response. I'd be happy to test it out for you when you do.

**Comment by jean-emmanuel** [comment]
You can try version 0.32.0-beta.0 :)

There are 2 new options:
- `tcp-port`: open-stage-control will listen for tcp connections on this port
- `tcp-targets`: open-stage-control will try to connect to these tcp servers (tcp-port must set)

Once this is set, when open-stage-control sends osc messages, if the target is found among the active tcp connections, the message will be sent to it (udp is always sent).

**Comment by mesayre** [comment]
Wow, thanks!

I just tried out 0.32Beta0, but I wasn't able to get a response from my client (Digital Performer). It's a little tough to see where it's failing. I'm on Win10, and running netstat I can see that DP is sending a SYN message on port 7865. If I set Open Stage Control to receive on that port and start it, then run netstat again, it shows a connection established. But I send a message that should get a response, and I don't see anything in console.

I don't know how to set the TCP send port, as I believe that is dynamically assigned after the initial connection is made. If I pick a random port in the unassigned range, I just get a connection refused.

I can try again later with the next build, as I see you've already committed some changes.

**Comment by jean-emmanuel** [comment]
Can you try 
- disable DP's output port
- set `tcp-port` to some random unused port number
- set `tcp-targets` to `127.0.0.1:DP_INPUT_PORT` ?

**Comment by jean-emmanuel** [comment]
Sorry it's a bit hard to help since I don't have DP and there is no documentation on how it handles osc... according to the manual:
>Digital Performer’s implementation of the OSC protocol is described in the OSC Programming Guide for Digital Performer, available via Help menu > Control Surfaces Help. 

Maybe there are some relevant infos here ?

Anyway, make sure to either set the `--send` option or your widget's `target` to `127.0.0.1:DP_INPUT_PORT` to actually send messages (these will print in the console).

**Comment by jean-emmanuel** [comment]
The latest release adds some log messages on the tcp connections state, this might help a bit.

**Comment by mesayre** [comment]
Thanks for that. The latest shows "TCP:connection established" on the correct port, but doesn't indicate that a message is sent.

**Comment by jean-emmanuel** [comment]
I forgot to mention you need to enable the "debug" option to see see these messages.

**Comment by jean-emmanuel** [comment]
And just in case
>make sure to either set the --send option or your widget's target to 127.0.0.1:DP_INPUT_PORT to actually send messages (these will print in the console).

**Comment by jean-emmanuel** [comment]
As far as I can tell, TCP support seem to be functional on o-s-c's end, I'm closing the issue until more information is provided.
