### ISSUE TITLE
User guide is missing arm arch

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#30]
It is mentioned that one can use:
npm run debarm
but not that one needs export ARCH=armv7l
(it is unfortunate that it is still not installable on a pi :)  I think what is used of v7l is compatible with armhf though so I may try a fudge)

Extra note: I can go to the dist/open-stage-control-linux-armv7l/ directory and run ./open-stage-control from that directory. So the executable seems to run on a pi anyway.

**Comment by jean-emmanuel** [comment]
I'll add that, thanks. Actually you can run the app with plain Node (6.5.0+) , which runs on the pi, as long as you don't run it with the gui (it's the built-in chrome/gui client that doesn't run everywhere): 
```node path/to/app -n```
