### ISSUE TITLE
Set the target for a tab

### ISSUE THREAD

**Issue by suhr** [jean-emmanuel/open-stage-control#300]
This allows to control different synths from different tabs.

**Comment by suhr** [comment]
Interesting. In OSC v0.31.0 there's no way to set the target for a panel.

I'm talking about the root tabs though.

**Comment by jean-emmanuel** [comment]
The root tabs are contained in a "root" panel.

**Comment by jean-emmanuel** [comment]
This is exactly what I was trying to explain. A panel only sends osc if it contain tabs, its value represents the active tab's index (https://osc.ammd.net/widgets/containers/#panel).

**Comment by jean-emmanuel** [comment]
This is what you're looking for: https://osc.ammd.net/extras/advanced-property-syntax/
