### ISSUE TITLE
Exponential scale

### ISSUE THREAD

**Issue by suhr** [jean-emmanuel/open-stage-control#301]
This makes sense for ADSR, where you need to control small values more precisely.

**Comment by jean-emmanuel** [comment]
Why not, although I've come to think that using multiple breakpoints is actually more handy than exp/log scales, did you try [that](https://osc.ammd.net/widgets/sliders/#range) ?

**Comment by suhr** [comment]
Just tried it, it doesn't seem to do anything useful.

**Comment by jean-emmanuel** [comment]
You could try something like
```
{
  "min":0,
  "50%":0.1,
   "max":1
}
```

**Comment by jean-emmanuel** [comment]
I'm closing this because custom scales can be achieved with ranges or property maths (eg by using the fader's value in a `#{}` statement in another widget's value property). If anything, It's the logScale options that should be removed.

**Comment by suhr** [comment]
So I need *two* widgets for this? There's no way to do this using only one widget, even with advanced property syntax.

**Comment by jean-emmanuel** [comment]
The slider's range option actually works just fine if you don't want an extra widget. Otherwise yes, you have to use another widget to filter the value (the input widget is perfect for this purpose), this way you can choose precisely your mapping.
