### ISSUE TITLE
all links for .32 beta 1 go to beta 0

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#304]
Hey just a quick note all links for beta 1 point to beta 0 so it always prompts you to update when you open it. not a big deal just thought I would let ya know. the beta 0 seems more responsive on the tablet end as far as loading things up.

**Comment by jean-emmanuel** [comment]
Sorry about that, I've havent incremented the version properly for beta1, will release a stable version today.

**Comment by jean-emmanuel** [comment]
v0.32.0 is out and replaces the former .32.0-beta releases
