### ISSUE TITLE
faders with color set to auto or just a named value don't show in the tablet

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#305]
hey I was having this problem on .31 and .32 beta, any faders with color set to "auto" or with a color value like "red" don't translate to the tablet. I just gave them pound sign values and it works as expected.

**Comment by jean-emmanuel** [comment]
What tablet exactly ? Did it work fine in 0.30 ?

**Comment by Sebastian-blu** [comment]
iPad pro, I checked on safari and chrome browser

as far as .30 goes, I took a break from the development for a bit, So when I got back into it I noticed that the colors were missing. I don't actually know which version it started on... my apologies. It shows the proper colors on the desktop editor.

**Comment by jean-emmanuel** [comment]
Fixed in upcomming release
