### ISSUE TITLE
OSC patchbay

### ISSUE THREAD

**Issue by suhr** [jean-emmanuel/open-stage-control#307]
How do you control a modular synth using OSC?

I have an idea how to do it. Let there're two kind of widgets: the input one and the output one. Suppose the first widget has the address `/input` and the second one has the address `/output`. When you connect the input widget to the output widget, the following message is sent:

```
/input /output 1
```

When `/output` is disconnected:

```
/input /output 0
```

Possible extension: linear mapping with `/input /output coefficient offset`. For example, `/x /y 0.5 0.1` means `y = 0.5 * x + 0.1`.

**Comment by jean-emmanuel** [comment]
It could be nice to have something like this, I'll dig the idea someday soon.

> Possible extension: linear mapping with /input /output coefficient offset. For example, /x /y 0.5 0.1 means y = 0.5 * x + 0.1.

You can already build this kind of messages using the existing widgets and the [advanced property syntax](https://osc.ammd.net/extras/advanced-property-syntax/).

**Comment by suhr** [comment]
Sure, but the point is this is *server-side interpretation,* not client-side. The client just sends `/x /y 0.5 0.1`.

**Comment by jean-emmanuel** [comment]
I'm not sure to understand the idea, you wan't o-s-c to do the value mapping for other control surfaces ? This would add a significant delay and is a bit out of the app's scope.

**Comment by suhr** [comment]
1. In OSC, I connect `x` to `y` and select and amount of modulation (like in a modular synth ui)
2. The OSC message `/x /y 0.5 0.1` is sent.
3. The synth understands it as `y = 0.5 * x + 0.1` parametrization.

The client doesn't have to do anything special.

**Comment by jean-emmanuel** [comment]
Ok I get it; it will take some time before I find a way to make this fit in o-s-c's logic, I'll keep you up to date when I start working on it.

**Comment by jean-emmanuel** [comment]
Patchbay is implemented and will be included in next release, it does not do the modulation stuff, only the connections, the rest can be done with the advanced property syntax or external scripting.
