### ISSUE TITLE
how to use with packaged app?

### ISSUE THREAD

**Issue by fanyer** [jean-emmanuel/open-stage-control#31]
I can only access to control dashboard by Browser `localhost:port` , while the native OSX app(packaged from source) show nothing optional with backgroud only.

**Comment by jean-emmanuel** [comment]
Can you give me more infos: 
- which version of the app are you using (version number or commit)
- how exactly are you launching the app
- if accessing the app with a browser other than the built-in one, which one is it

thank you for testing
