### ISSUE TITLE
Add an Android APK 

### ISSUE THREAD

**Issue by diegodorado** [jean-emmanuel/open-stage-control#310]
It would be nice to have an android apk that would let you connect to a server, and enjoy open stage control more easily.
It could remember the last server you connected to, autoconnect to the last one if posible, and be opened without tabs, favorites, and be fullscreen right away

**Comment by jean-emmanuel** [comment]
I'm not going to develop an android app as I don't wan't to spend more time than I already do on this project. If someone if willing to do it I'd more than happy though ;).
Here's what's currently possible : 
- discovering an o-s-c server on the network using zeroconf / bonjour (https://play.google.com/store/apps/details?id=jp.deci.tbt.andro.bonjoursearch, not tested)
- adding an o-s-c server's address to the home screen (enables fullscreen automatically)
