### ISSUE TITLE
/EDIT/GET then /EDIT/SET ==> error

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#311]
Hi
I have a button that I use as 'template'. (see attachment)
[playpause.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/2073107/playpause.json.txt)

I do a /EDIT/GET on it, transform the json (or not), and send it back to o-s-c.

```
oscsend osc.udp://localhost:8080 /EDIT/GET ss 127.0.0.1:8080 PLAYPAUSE
```

I get this printed in the console:
```
OSC received:  { address: '/EDIT/GET',
  args: 
   [ 'PLAYPAUSE',
     '{"type":"toggle","top":90,"left":110,"id":"PLAYPAUSE","linkId":"","width":"auto","height":"auto","label":"#{@{this}==\\"PLAY\\"?\\"^pause\\":\\"^play\\"}","color":"auto","css":"","doubleTap":false,"led":false,"on":"PLAY","off":"PAUSE","default":"","value":"","precision":2,"address":"/toggle_1","preArgs":[],"target":[],"bypass":false}' ] } From : 127.0.0.1:8080
```
Here, you can see that the antislashes before the double quotes are escaped...

If I copy the output and use it to do:
```
oscsend osc.udp://localhost:8080 /EDIT ss PLAYPAUSE  '{"type":"toggle","top":90,"left":110,"id":"PLAYPAUSE","linkId":"","width":"auto","height":"auto","label":"#{@{this}==\\"PLAY\\"?\\"^pause\\":\\"^play\\"}","color":"auto","css":"","doubleTap":false,"led":false,"on":"PLAY","off":"PAUSE","default":"","value":"","precision":2,"address":"/toggle_1","preArgs":[],"target":[],"bypass":false}' 
```
I get an error because the escaped antislashes:
```
Uncaught SyntaxError: JSON5: invalid character 'P' at 1:121
    at k (index.js:1)
    at j (index.js:1)
    at Object.afterPropertyValue (index.js:1)
    at Object.default (index.js:1)
    at b (index.js:1)
    at JSON.parse [as parseFlex] (index.js:1)
    at Object.EDIT [as /EDIT] (remote-control.js:11)
    at Object.exec (remote-control.js:163)
    at Osc.receive (osc.js:38)
    at receiveOsc (callbacks.js:17)
```
But it is only a display error, because my application receives correct OSC and is able to send it back.

If I fix the escaping:
```
oscsend osc.udp://localhost:8080 /EDIT ss PLAYPAUSE '{"type":"toggle","top":0,"left":0,"id":"PLAYPAUSE","linkId":"","width":80,"height":80,"label":"#{@{this}==\"PLAY\"?\"^pause\":\"^play\"}","color":"auto","css":"font-size: 35rem","doubleTap":false,"led":true,"on":"PLAY","off":"PAUSE","default":"","value":"","precision":2,"address":"@{this.id}","preArgs":[],"target":["],"bypass":false}'
```
it changes the widget, but I get this in the web debugger:
```
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. in drag.js:222
```
If I do that with bigger or more complex objects, I get lots of these errors, and the GUI freezes for several seconds...

I know I should'nt do that, but it is the only way I've found....

I need to do some 'regexes' to my templates, because I have nested widgets...

I can provide some other repro cases if needed.

Thanks for your support
Eric

**Comment by jean-emmanuel** [comment]
Yo!
The JSON parsing error is just an escaping problem indeed that only happen because of the terminal's limitations, in general you should parse and modify these JSON objects programmatically instead of using regexp, it's much more robust.

> [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. in drag.js:222

It is not an error and can't be removed :  "passive" event handler just can't be used in this context. That being said, if the number of these messages for a single editing operation grows drastically each time the operation is performed while the overall number of widget doesn't increase, it might come from a memory leak issue.
