### ISSUE TITLE
"Feedback sent with preArgs" regression

### ISSUE THREAD

**Issue by gsenna** [jean-emmanuel/open-stage-control#314]
Thanks for the quick fix to #313 ! But I think there is still a regression in regards to issue #16 .

I'm testing with a fader and the same preArgs ([{ "type": "i", "value": 1 }]). I'm trying to send with:

`oscsend localhost 13256 /fader_1 if 2 0.510000`

Thanks!

**Comment by jean-emmanuel** [comment]
You're welcome ! Actually, this was never implemented, I guess I just forgot to... it's fixed now and will be included in next release.

**Comment by jean-emmanuel** [comment]
-> v0.32.5
