### ISSUE TITLE
Installation sous raspberry pi raspbian stretch 9

### ISSUE THREAD

**Issue by nlebellier** [jean-emmanuel/open-stage-control#315]
Juste une question : comment installer l'excellent open stage control sous raspbian ? 
quelques pistes ?
merci pour une éventuelle réponse.

**Comment by jean-emmanuel** [comment]
Salut, désolé pour l'attente, as-tu essayé d'installer le paquet `open-stage-control-0.32.4-armv7l.deb` ?

**Comment by nlebellier** [comment]
Hello Jean-Emmanuel,
merci pour ta réponse. 
oui j'ai essayé avec le paquet deb et voici quelques traces. 
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
```

```
pi@raspberrypi:~/Downloads $ uname -a
Linux raspberrypi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 **armv7l** GNU/Linux
```

```
sudo dpkg -i open-stage-control-0.32.4-armv7l.deb 
dpkg: erreur de traitement de l'archive open-stage-control-0.32.4-armv7l.deb (--install) :
 l'architecture du paquet (armv7l) ne correspond pas à celle du système (armhf)
Des erreurs ont été rencontrées pendant l'exécution :
 open-stage-control-0.32.4-armv7l.deb
```
Je crois comprendre que les anciens rpi ne sont pas sur l'architecture que tu supportes ?
ce qui est curieux c'est la commande uname m'indique armv7l !
Dans ce cas, il faut passer par les sources Linux et les compiler à la main ?

**Comment by jean-emmanuel** [comment]
Tu peux effectivement tenter de le compiler/lancer depuis les sources en suivant les indications ici : https://osc.ammd.net/getting-started/#run-from-sources

C'est un rpi de quelle génération ?

**Comment by nlebellier** [comment]
Finalement je suis passé par les sources et je le lance sans interface avec
node directement comme c'est très bien indiqué ton ta doc :)
J'en ai profité pour installer la toute dernière version de node et npm sur
raspbian 9 et ensuite j'ai fait de la place sur ma carte sd en supprimant
pleins de paquets inutiles car node_modules ça prend un peu de place,
j'ai pu le faire fonctionner pour piloter sonic pi lancé sur le rpi donc
c'est cool !

J'ai une question : si j'ai bien compris chaque personne qui charge
@ip:8080 depuis un navigateur du même réseau doit charger un fichier json
pour avoir l'interface ?
chaque utilisateur a une version propre à son navigateur, si le "Arhur"
bouge un fader depuis son navigateur, "Léa" ne peut voir le fader bouger
sur son navigateur ? Est-possible ou pas du tout ?
et merci pour tes réponses !


---
Nicolas Le Bellier








2018-06-19 13:36 GMT+02:00 jean-emmanuel <notifications@github.com>:

**Comment by jean-emmanuel** [comment]
> chaque personne qui charge @ip:8080 depuis un navigateur du même réseau doit charger un fichier json pour avoir l'interface

Oui, mais si le fichier a été chargé une fois côté serveur, il apparaîtra dans la liste des sessions récentes et il n'est alors pas nécéssaire d'avoir le fichier json sur chaque machine cliente.

> Est-ce possible que Léa et Arthur est en temps réel le même état de l'interface ?

Tous les clients connectés à une même instance de serveur O-S-C sont synchronisés automatiquement; si Arthur bouge un fader, Lea verra le fader bouger aussi, à condition que les deux faders aient les mêmes réglages osc (address, preArgs et target).
