### ISSUE TITLE
Ajouter dynamiquement des boutons

### ISSUE THREAD

**Issue by nlebellier** [jean-emmanuel/open-stage-control#319]
Bonsoir,

Peut-on ajouter un bouton par exemple à l'aide d'une commande osc ?
genre on a une playlist et on veut ajouter des boutons pour déclencher la lecture de chaque titre donc un toggle par morceau de la playlist ?
Merci pour une piste si c'est possible.

**Comment by cyberic99** [comment]
Hello
La playlist est faite avec quel widget?
Soit tu peux mettre un widget vise a l avance a coté de chaque morceau, et le modifier avec la commande /EDIT (voir la doc), sinon tu peux faire ton bouton à l'avance, et le cacher avec du css ou en mettant sa taille à 0, puis changer cette propriété quand tu veux l'afficher

**Comment by jean-emmanuel** [comment]
Tu as deux possibilités pour changer le contenu de tes widgets avec des messages osc : 

- associer des paramètres de widgets à des adresses osc https://osc.ammd.net/extras/advanced-property-syntax/#osc-listeners-osc
- editer l'interface à distance : https://osc.ammd.net/extras/remote-control/

Dans les deux cas je crois qu'il y a pas mal d'exemples qui traînent dans les différents tickets ici..:)

**Comment by nlebellier** [comment]
Merci pour vos réponses à tous les deux je vais regarder mais même si la
doc est extra complète des fois des exemples c'est mieux pour démarrer et
donner envie d'aller plus loin...
Mais je continue mes recherches et j'espère faire un petit doc.

---
Nicolas Le Bellier








2018-06-26 17:08 GMT+02:00 jean-emmanuel <notifications@github.com>:

**Comment by nlebellier** [comment]
Bonjour, bonjour

Je poursuis mes tests...
J'envoie le message avec un script python en utilisant python-osc
```
"""
Test d'envoi vers open stage control d'un message osc
pour changer un label dynamiquement
"""
import argparse
import random
import time

from pythonosc import osc_message_builder
from pythonosc import udp_client


if __name__ == "__main__":
  parser = argparse.ArgumentParser()
  parser.add_argument("--ip", default="127.0.0.1",
      help="adresse du serveur openstagecontrol")
  parser.add_argument("--port", type=int, default=8080,
      help="8080 the port is listening on")
  args = parser.parse_args()

  client = udp_client.SimpleUDPClient(args.ip, args.port)
  client.send_message("/EDIT", "push_4 {\"label\":\"New Label\"}")
```

et dans les logs du serveur Open Stage Control 

```
App available at http://192.168.75.1:8080 & http://192.168.0.112:8080 & http://127.0.0.1:8080
OSC received: { address: '/EDIT', args: 'push_4 {"label":"New Label"}' } From : 127.0.0.1:55772
[Renderer process error]
Uncaught SyntaxError: JSON5: invalid character 'u' at 1:1
at default (node_modules/json5/dist/index.js:1:0)
at default (node_modules/json5/dist/index.js:1:0)
at default (node_modules/json5/dist/index.js:1:0)
at default (node_modules/json5/dist/index.js:1:0)
at default (node_modules/json5/dist/index.js:1:0)
at EDIT (src/browser/js/app/remote-control.js:11:53)
at exec (src/browser/js/app/remote-control.js:163:28)
at receive (src/browser/js/app/osc.js:38:72)
at receiveOsc (src/browser/js/app/ipc/callbacks.js:17:12)
at require (src/browser/js/app/ipc/index.js:40:16)
```
la doc nous dit :

```
/EDIT id options¶
Apply a set of options to an existing widget by replacing the old ones with the new ones.

id: string, widget's id
options: string, JSON5 stringified object defining the new properties to merge
example: {"label":"New Label", "color":"red"}
```
Si vous avez des idées pourquoi ça bug .... Merci !

**Comment by cyberic99** [comment]
Tu peux aussi tester avec oscsend

Je pense que tu devrais plutot faire:
```
client.send_message("/EDIT", "push_4", '{"label":"New Label"}')
```
cad séparer les arguments,

Sinon regarde ici, ca ressemble un peu à ce que tu veux faire:

https://github.com/jean-emmanuel/open-stage-control/issues/152#issuecomment-367259026

**Comment by nlebellier** [comment]
c'est quoi ocssend ?? quel lien avec csound ?
je vais regarder ton script mais je ne connais pas python...


---
Nicolas Le Bellier








2018-06-27 11:42 GMT+02:00 cyberic99 <notifications@github.com>:

**Comment by jean-emmanuel** [comment]
En effet, il faut séparer les arguments, dans l'exemple que tu donnes tu n'envoies qu'une seule chaine de caractères pour les deux arguments :  `"push_4 {\"label\":\"New Label\"}"`. Oscsend est une autre librairie mais ça devrait fonctionner avec celle que tu utilises.

**Comment by nlebellier** [comment]
@cyberic99 

`client.send_message("/EDIT", "push_4", '{"label":"New Label"}')` ne marche pas avec l'erreur suivante

```
d:\audio\osc-scripts>python envoi-message.py
Traceback (most recent call last):
  File "envoi-message.py", line 35, in <module>
    client.send_message("/EDIT", "push_4", '{"label":"New Label"}')
TypeError: send_message() takes 3 positional arguments but 4 were given
```

donc si oscsend est mieux peux-tu m'indiquer un lien ? merci.

**Comment by jean-emmanuel** [comment]
@nlebellier je suis allé regarder la doc de ta librairie, il faut mettre les differents arguments dans une liste ou un tuple, ceci devrait marcher:
```python
client.send_message("/EDIT", ("push_4", '{"label":"New Label"}'))
```

**Comment by nlebellier** [comment]
yes it works merci beaucoup 👍 
bon désolé mais je ne sais pas où tu as pu trouver l'info https://github.com/attwad/python-osc
maintenant que je connais la syntaxe en python il va falloir que je trouve en ruby pour l'utiliser dans sonic pi car c'était mon idée première mais les chemins de traverse sont toujours formateurs :-)

**Comment by jean-emmanuel** [comment]
Autannt pour moi, j'ai regardé dans le code source en fait... (https://github.com/attwad/python-osc/blob/master/pythonosc/udp_client.py#L33)

**Comment by jean-emmanuel** [comment]
Je me doutais bien que ça ferait débat, ce n'est pas si tranché, même dans l'article que tu cites...

**Comment by cyberic99** [comment]
Pour que tout le monde soit content, parlez en anglais ;-)

**Comment by nlebellier** [comment]
et donc ça donne en anglais ? :-)
sinon moi je suis content car j'apprends plein de choses !

**Comment by jean-emmanuel** [comment]
-> my bad ;)

**Comment by nlebellier** [comment]
https://fr.wiktionary.org/wiki/my_bad funny isn't it to find again our
friend "autant pour moi"

---
Nicolas Le Bellier








2018-06-27 13:43 GMT+02:00 jean-emmanuel <notifications@github.com>:

**Comment by nlebellier** [comment]
Pour revenir à nos moutons (Let's get back to our sheep ! )
donc pour ajouter dynamiquement un bouton, je vais envoyer le code css display:block pour faire apparaître mes boutons qui initialement sont à display:none.

Sinon @cyberic99  parlait d'une deuxième méthode https://osc.ammd.net/extras/advanced-property-syntax/#osc-listeners-osc

Auriez-vous un exemple sous la main pour mettre le pied à l'étrier ?
et encore un grand merci pour votre aide.

**Comment by cyberic99** [comment]
Sorry je ne m'en sers pas, c'est une feature relativement récente et je n'en n'ai pas (encore) trouvé l'utilité...

**Comment by nlebellier** [comment]
pas de souci !
est-ce que par exemple map la propriété display planqué dans le code css
vers une adresse osc ?   /fader_4/display none
c'est ça le principe non ?
mais je ne vois pas comment.

---
Nicolas Le Bellier








2018-06-27 16:02 GMT+02:00 cyberic99 <notifications@github.com>:

**Comment by cyberic99** [comment]
je pense que tu dois plutot mettre un truc du genre dans le css:
``display: OSC{/fader4/display, "none"}``

Et ensuite tu envoies ``block`` à l'adresse ``/fader4/display`` pour faire apparaître ton bouton

**Comment by nlebellier** [comment]
and the winner is @cyberic99  !

en effet il faut mettre dans le css le code suivant

```
display: OSC{/push_5/display, "block"}
```
et par exemple avec python-osc

```
client.send_message("/push_5/display", ('block'))
time.sleep(2)
client.send_message("/push_5/display", ('none'))
time.sleep(2)
client.send_message("/push_5/display", ('block'))
time.sleep(2)
```
Bon ben encore merci on avance on avance !

**Comment by jean-emmanuel** [comment]
C'est l'idée, mais le plus sûr pour la compatibilité avec le css déjà en place est de faire comme suit (les widgets ne sont pas forcément en display:block par défaut, on va donc seulement changer cette propriété si besoin vers display:none)

**css:**
```css
#{
OSC{/push_5/display, 0} == 0 ? "display:none" : ""
}
```
Le widget est alors caché par défaut et on peut envoyer 1 ou 0 pour l'afficher / le cacher.

**Comment by nlebellier** [comment]
c'est à placer où ton bout de code ?

---
Nicolas Le Bellier

**Comment by nlebellier** [comment]
ok c'est bon ! parfait ! Merci

---
Nicolas Le Bellier








2018-06-27 18:27 GMT+02:00 jean-emmanuel <notifications@github.com>:
