### ISSUE TITLE
Feature request: generic matrix

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#320]
Hi

I would find it very useful to have a kind of multipush but with custom values.
Using a switch can be a workaround, but with a switch you cannot click the same item/button twice, because it stays selected...
So would it be possible to have a 'autorelease' property in a switcher?
It would allow the user to click an item, then click it again, and it would send the value twice.

Thx a lot
Eric

**Comment by jean-emmanuel** [comment]
I'm working on a generic and more flexible matrix widget that should do the job and much more ;)

**Comment by jean-emmanuel** [comment]
It's in git for testing and should be included in next release. It's really black magic stuff...:)

Simple exemple for a matrix `props` property (with all other properties to default values):
```
{
  "color": "red",
  "label": "#{\"abcd\"[i]}"
}
```

Complex example:
```
#{
props = {\}
props.label = "abcd"[i];
props.color = ["red", "cyan"][i % 2];
props.preArgs = [i];
props.address = concat("/test/", string(i));
props.target = "127.0.0.1:4444";
}
```

**Comment by cyberic99** [comment]
Wow, that's huge!

I tested it with pushbuttons and was able to set other properties such as norelease and such.

It can be really useful for a grid of knobs too, or even for multifaders

I will try to use it dynamically with a list of buttons to play some samples

The sample list will be a json dict: ``{"sample1": 1, "sample2": 2}``

Hope it will work, especially updating the sample list ;-)

**Comment by jean-emmanuel** [comment]
In your case you could do set the matrix' `widgetType` to `push` and its `props` to something like:
```
#{

props = {\} # no semicolon -> outputed by formula
            # closing bracket must be escaped here

values = [1,2,3,4];

props.on = values[i];
props.address = concat("/test/", string(i));
props.target = "127.0.0.1:4444";

}
```

**Comment by jean-emmanuel** [comment]
I changed the index variable to $ to be consistent with the existing matrix widgets (plus `i` is already used in formulas for complex numbers, although I'm not sure it's of any use in o-s-c).

**Comment by cyberic99** [comment]
OK. I think that ``$`` can be confusing... ``idx`` or ``index`` would be IMHO more appropriate, but you choose ;-)

**Comment by cyberic99** [comment]
@jean-emmanuel : even with master (4728599406364b7dbfc01d9bdc87b0819ffe0589), ``i`` has still to be used as index, nd this is not working with ``$``

**Comment by jean-emmanuel** [comment]
Fixed !

**Comment by jean-emmanuel** [comment]
Included in v0.33.0, I'm sticking to `$`, it has the benefit of being consistent with the older matrices widgets plus `index` is already a function available in formulas'. Now let's try it and find the bugs ;)

**Comment by cyberic99** [comment]
For me it's working as expected. I have a matrix of pushes, complex props, and I dynamically change the matrix size. it is working as expected. thx!

**Comment by akobelan** [comment]
**In case somebody stumbles across the same needs as I had ...**  #335

- Example 1: 
-- toggle button matrix
-- user defined labels
-- user defined values
-- alternating colors for enabled buttons 

MATRIX/widgetType: **toggle**
MATRIX/props: 

```
#{
props = {\} # no semicolon -> outputed by formula
            # closing bracket must be escaped here.

values = [1,2,3,4,5,6,7,8,9,10];
props.on = values[$];
props.label = ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"][$];
props.color = ["red", "cyan"][$ % 2];
props.address = concat("/test/", string($));
props.target = "127.0.0.1:8088";
}
```
- Example 2: 
-- push button matrix
-- user defined labels
-- user defined values
-- alternating colors for enabled buttons 
-- no OSC message sent on release

MATRIX/widgetType: **push**
MATRIX/props: 

```
#{
props = {\} # no semicolon -> outputed by formula
            # closing bracket must be escaped here.

values = [1,2,3,4,5,6,7,8,9,10];
props.on = values[$];
props.norelease = true;
props.label = ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"][$];
props.color = ["red", "cyan"][$ % 2];
props.address = concat("/test/", string($));
props.target = "127.0.0.1:8088";
}
```
