### ISSUE TITLE
How to access input fields in compact, horizontal faders?

### ISSUE THREAD

**Issue by danielappelt** [jean-emmanuel/open-stage-control#321]
In v0.30.4 it was possible to enable the input field in a compact, horizontal fader via right clicking on it's numeric value. In the current release, v0.32.6, the only way that I found to enable the input field is by left clicking on the fader's label and then hitting the TAB key.

Is it possible to get back the old behaviour?

**Comment by jean-emmanuel** [comment]
This behaviour was really annoying for touch device users, I guess I could put it back for mouse right-click only though.

**Comment by danielappelt** [comment]
I see. Using a right click was not the most inuitive thing either.
In a regular web app, clicking an input's label (if authored correctly) would enable the input. Maybe this could be a cross-device solution?

**Comment by jean-emmanuel** [comment]
Hmm I'm not sure, unexpected input focuses are really annoying on touch devices as they brings up the virtual keyboard, this would potentially trigger those often. In most case clicking/tapping the input does the job, the only caveat is the compact fader's case but it can be solved by using an external input widget.

**Comment by jean-emmanuel** [comment]
-> old behaviour restored for mouse only in v0.33.0.
