### ISSUE TITLE
Switching from Python to pure Web MIDI

### ISSUE THREAD

**Issue by danielappelt** [jean-emmanuel/open-stage-control#322]
As far as I can tell, the current Web MIDI implementation in electron should be capable of handling the MIDI needs in open-stage-control. I think, it would be a good idea to switch to a pure electron / JS implementation to make MIDI use cases more accessible to users who are not familiar with installing python dependencies.
I could help to implement this if I find the time :-)

**Comment by jean-emmanuel** [comment]
MIDI and OSC protocols are handled server-side, I don't wan't to rely on the client WebMIDI implementation. The reasons I'm using this python approach are:

- it runs server-side
- it handles virtual ports on linux and osx
- it does not add any cross-platform compilation steps in the app's release process

I haven't found a pure node/electron MIDI implementation that does that yet, there's https://github.com/justinlatimer/node-midi but it's not maintained and does not provide cross-platform binaries.

**Comment by danielappelt** [comment]
OK. I thought the server side has electron running headless and would provide all the regular APIs that are available in electron, no?

**Comment by jean-emmanuel** [comment]
There's some progress on this: https://github.com/djipco/webmidi/issues/15
However it doesn't seem stable enough yet, and the webMIDI API still lacks of virtual ports support (https://github.com/WebAudio/web-midi-api/issues/45). I'll keep an eye on the nodejs thing though, it should be possible to have python handle the virtual port feature only someday.

**Comment by jean-emmanuel** [comment]
I'm closing the issue since this seems unlikely to change anytime soon. Feel free to reopen if it does.
