### ISSUE TITLE
Accessing rgb values to plot

### ISSUE THREAD

**Issue by Gerfunky** [jean-emmanuel/open-stage-control#323]
Hi im more of a c++ programmer and still trying to understand these data structures
I have to say nice pice of software!

I have 16 RGB values assigned to rgb_leds widgets.
Now i would like to create one plot, where i have one line for red, one for green and one for Blue. Over the 16 leds, Is this possible? 
And how can i get the single r,g & b values? I cant figure it out. I expected an array and tried to access it as @{rgb_led[0]}  but this does not work.
I also looked at the widget code but could not find it.
Thanks for the help.

**Comment by jean-emmanuel** [comment]
Hi, thanks :)

You can't retreive a subset from a widget's value with the `@{}` syntax, but you can with the formula syntax: `#{ @{rgb_led}[0] }`.

Now plots only draw one line at a time, you'll have to use 3 plots. The attached session file should be a good start, check out the plots' value properties.
[rbgline.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/2162113/rbgline.json.txt)

**Comment by jean-emmanuel** [comment]
Here is another way to do it in a single `svg` widget and more of the [formula syntax](http://mathjs.org/docs/index.html). : 
[rgbsvg.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/2162267/rgbsvg.json.txt)

**Comment by Gerfunky** [comment]
Thanks thats what i need.  would be great if you add this to the docs.

**Comment by jean-emmanuel** [comment]
I've added the session to the default examples shipped with the app. I made a few adjustments and I put a matrix widget to create the rgb pads (because you can retreive all it's children's values with one `@{}` call instead of listing them manually). The session will be available in a minute in the online demo.
