### ISSUE TITLE
texte à la vertical dans un push ?

### ISSUE THREAD

**Issue by nlebellier** [jean-emmanuel/open-stage-control#325]
J'avance sur mon interface :-) et j'ai une question 
Peut-on mettre un texte à la vertical sur un push ? j'ai pour l'instant mis un input sur lequel j'envoie les titres des pistes ?
L'idéal serait que le nom de pistes spit réactifs pour l'instant ce sont des push mais pourquoi pas des toggles dans peu de temps.

![image](https://user-images.githubusercontent.com/4880966/42345018-65d66406-809e-11e8-8df3-9b2577736bba.png)

Autre question concernant github : en fait ce n'est pas une issue qui peut mettre que c'est une question ?

Merci encore pour ce logiciel que j'apprécie de plus en plus !

ps : je viens de découvrir que github permettait un copier-coller d'une capture d'écran sans hébergement extérieur et bien c'est super pratique de chez pratique.

**Comment by jean-emmanuel** [comment]
> Peut-on mettre un texte à la vertical sur un push 

Tu peux mettre ça dans le css du `push`:
```css
.label {
  writing-mode:vertical-rl;
  transform: rotate(180deg);
  padding:0;
}
```

>  qui peut mettre que c'est une question ?

Seulement les administrateurs du dépôt, donc moi, mais ce n'est pas un souci les question sont bienvenues ;)
> Merci encore pour ce logiciel que j'apprécie de plus en plus !

Merci à toi ! Je vois sur ta capture d'écran que tu utilises o-s-c avec firefox, je te conseille d'utiliser chrome/chromium, je ne vise que ce navigateur en terme de compatibilité (on voit d'ailleurs quelques bugs d'affichage sur l'image).

**Comment by cyberic99** [comment]
Cool pour le texte vertical!
@jean-emmanuel, on voit que pas mal d utilisateurs utilisent des "tranches" d'objets complexes...
Un peu comme le concept des matrices, mais appliqué à des groupes d'objets....
Envisages tu d'étendre les matrices à des objets complexes? Genre des strips ou des panels?
Apres il faudrait trouver un moyen d accédes aux différentes sous-propriétés, je vois pas trop comment faire ca....

**Comment by jean-emmanuel** [comment]
Tu peux faire des matrices de clones... ;)
