### ISSUE TITLE
Matrix of clones: help needed

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#326]
Hello

Following your comment in https://github.com/jean-emmanuel/open-stage-control/issues/325#issuecomment-402935348, I tried to create matrices of clones.

I created a strip with a fader and a push, I cloned it, and I tried to replicate this group of widgets with a matrix.
For now I just tried to set a different label per strip, but I can't find the proper way to do it properly

My session file is attached.

Maybe there is already a "complex" matrix in the examples?

Thank you

[clone_matrix.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/2169880/clone_matrix.json.txt)

**Comment by jean-emmanuel** [comment]
Here is an amended version of you session : [clone_matrix.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/2170178/clone_matrix.json.txt)

- `$` is only valid in a formula context `#{$}`
- values in the matrix `props` property overrides the subwidgets' properties, you need to address them accurately. In the case of a clone, you will likely have to override its own `props` property, yep, that means nested `props`.

**Comment by cyberic99** [comment]
Oooh I see! 

I don't even need to create a clone!
And I could also start as index 1 instead of 0.

That is very usefull, and fully dynamic!

I attached an improved session if it is useful to somebody

[clone_matrix.v3.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/2170394/clone_matrix.v3.json.txt)

![image](https://user-images.githubusercontent.com/193917/42377886-7b662ebe-8125-11e8-9242-5ed99e3c6d3e.png)

**Comment by jean-emmanuel** [comment]
Great! The small style bug behind the widgets' labels is fixed in git FYI.

**Comment by cyberic99** [comment]
I just add another example here:

[matrixclone4.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/2493543/matrixclone4.json.txt)

![image](https://user-images.githubusercontent.com/193917/47182907-05d79580-d327-11e8-88a2-a81d1c483e68.png)
