### ISSUE TITLE
Feature request: length() for dictionaries

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#327]
Could you please extend the ``length()`` function to work with dictionaries?

Sometimes I use a dict in a switch, for instance, and I would find useful to be able to get the length of the dict, ie the nb of elements in it.

But for now, ``#{length({"a":1})}`` is not evaluated...

Thank you

**Comment by jean-emmanuel** [comment]
Good idea, btw `length` doesn't exist at all for now you only have `size`. You also need to escape closing brackets of objects with a backslash.

**Comment by cyberic99** [comment]
It does not exist?
But ``#{length([1,2])}`` returns 2, right?

**Comment by jean-emmanuel** [comment]
Haha sorry it does exist actually because I added it, I just forgot about it...

**Comment by jean-emmanuel** [comment]
I've added two functions: [`keys()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) and [`values()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values), you can either do `#{length(values({"a":1\}))}` or `#{length(keys({"a":1\}))}` (I prefer not to extend length to objects and stay consistent with the javascript syntax as much as possible).

**Comment by cyberic99** [comment]
Perfect! ``keys()`` and ``values()`` are what I wanted to ask next, and they solve my initial request. Thx!

I am gonna use it to autosize matrixes depending on the nb of elements they contain

**Comment by jean-emmanuel** [comment]
-> v0.33.2
