### ISSUE TITLE
[Feature Request]: Ableton Link + time based Matrix

### ISSUE THREAD

**Issue by CamoKrooked** [jean-emmanuel/open-stage-control#328]
Hey,

has there been any thought about including Ableton Link (https://github.com/Ableton/link), so f.e. matrices could be made time-dependent?

**Comment by jean-emmanuel** [comment]
Hi!
Unfortunately timing and audio are out of open stage control's scope, I prefer to delegate this to 3rd party apps and scripts and focus on the pure control part. Separation of concerns... ;)
