### ISSUE TITLE
css autoreload

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#329]
Hello

I ad understood that changes made to a custom .css file would automatically reload the css...

I cannot get it to work....

is it compatible with the ``npm start`` method?

However, if I do:

```
node scripts/reload-css.js
```

then it gets reloaded

**Comment by jean-emmanuel** [comment]
> I ad understood that changes made to a custom .css file would automatically reload the css...

This feature has been removed a long time ago, the proper way to develop your theme is described [here](https://github.com/jean-emmanuel/open-stage-control/issues/185#issuecomment-370181540) and will end up in the docs.

**Comment by cyberic99** [comment]
Allright thx
