### ISSUE TITLE
use in a network and preset files sharing

### ISSUE THREAD

**Issue by brucelane** [jean-emmanuel/open-stage-control#33]
hi, this looks like a very nice project!!

how can it be used in a network? I saw the fader moving in sync with the electron app and the browser on the same machine.

I tryed the electron app and the browser app, they don't seem to be able to load the preset files exported by one(electron) an imported by the other(web)

Merci

**Comment by jean-emmanuel** [comment]
Hi ! Thank you for your interest :)

> how can it be used in a network

Once launched, the app is accessible on the network at http://server-ip:8080 (8080 being the default port)

> they don't seem to be able to load the preset files exported by one(electron) an imported by the other(web)
It's the way it works for now:
The state's saving and loading isn't shared between the apps, although loading/importing a state will update all clients as osc message are sent. As for preset files, they are currently just simple files created on the client's filesystem, therefore they can't be shared between clients. Someday, I'll try to bring a smarter way to deal with states/preset.
