### ISSUE TITLE
switch widget using dictionnary for its value: can't guarantee the order of the buttons

### ISSUE THREAD

**Issue by jblanteigne** [jean-emmanuel/open-stage-control#330]
I'm trying to update the values of a switch widget to automatically resize the widget and rename each button based on which scene I am in my project. I am able to send this command with the /EDIT message and this makes open stage control completely awesome for me. Wow.

The only problem is that using a dictionary to store the label:value of each button in my switch widget makes it hard to guarantee the order of the buttons. Even though I send the osc message as a string in the desired order, the buttons are not displayed in the desired order in open stage control's GUI.

**Comment by jean-emmanuel** [comment]
It makes sense, but I must admit I haven't been able to create a switch that doesn't honor the order of its values. I'll add a way to force the order, but out of curiosity could you provide a reproduction case ?

**Comment by jblanteigne** [comment]
I found the culprit.

Note: on my end, I format the dictionary as a string so I can guarantee the order of the elements in the message sent to O-S-C.

Here's the dictionary:

`{"zero state": 0, 
"front": 1, 
"side": 2, 
"new snap": 3,
 "5": 4,
 "6": 5,
 "7": 6,
 "8": 7,
 "9": 8}`

So the order of the received osc message is fine, and it is displayed fine in the widget's values parameter. But it displays the buttons with labels being "integers" first. Other than this, the order is fine. It shows: 5, 6, 7, 8, 9, zero state, front, side, new snap

Renaming the "integer" labels to something else starting with letters fixes the order.

**Comment by jean-emmanuel** [comment]
I had not tried with numeric keys...thanks.

**Comment by jean-emmanuel** [comment]
Quick workaround: add a whitespace before or after numeric keys to ensure they are treated as strings.

**Comment by jean-emmanuel** [comment]
I've decided to just add this workaround to the docs instead of adding a new syntax for this case, I'll reconsider the issue in the future if it happens to be be too confusing.
