### ISSUE TITLE
Is there a build of rtmidi with jack ?

### ISSUE THREAD

**Issue by wargreen** [jean-emmanuel/open-stage-control#331]
Hi,
I try to get some midi control via jack. I've tried to install :
the package python3-rtmidi from debian (but too old)
the packages rtmidi form pip and pip3,

But no one seem to be build with the jack option :
```
Error: 
RtMidiIn: no compiled support for specified API argument!
RtMidiOut: no compiled support for specified API argument!

```
And when i ask O-S-C to list the available ports it show to me only the alsa ports.
So is it a way to get a good build of rtmidi without build by my own ?

Thanks a lot

**Comment by jean-emmanuel** [comment]
You have to build it yourself with the `--jack-midi` flag: https://github.com/patrickkidd/pyrtmidi

**Comment by wargreen** [comment]
Successfully build and run.
