### ISSUE TITLE
Switcher don't seem to send anything

### ISSUE THREAD

**Issue by wargreen** [jean-emmanuel/open-stage-control#334]
Hi again,
It seem to me than the switcher widget don't send any datas.
I use O-S-C 0.33.2.

Thanks !

**Comment by jblanteigne** [comment]
Hi,

If you're looking for a switch that outputs its value to the server you're trying to remotely control, you need the switch widget (located under the button category). They work similarly but server different purposes.

Switcher is meant to switch between two or more presets on O-S-C itself. It "listens" to the values of other widgets specified in the linkedWidgets field and when you switch from a preset to another, these other widgets will output their value. It is similar to the preset object in MAX/MSP if you happen to know this platform.

**Comment by jean-emmanuel** [comment]
You are both right. I should be able to make the switcher and the crossfader send their value though (it's been disabled because these widgets hold more than their own values), but I have to ensure it doesn't mess with the inter-clients synchronization.

**Comment by wargreen** [comment]
Ok, sorry, i havn't search a lot, with the small time in the festival.
Thank for the tip, the switch widget seem fine for me, so i push request between the chair an the keyboard.
