### ISSUE TITLE
How to set labels on a multixxx widget

### ISSUE THREAD

**Issue by pat1shea** [jean-emmanuel/open-stage-control#335]
Hi, I can't find in the documentation how to set labels on a multipush or multi anything widget

Is it possible?

**Comment by jblanteigne** [comment]
Hi,
I encountered the same problem and I found a couple of workaround. There is a switch widget which you can edit its dictionary to specify different labels.

However, this might not do what you need so here's something else:

You can disable the labels on your multi (by entering the value "false" in the label parameter) and then create custom labels with text widgets. Placing them above your multi widget. If you do so you will need to tweak your text widget a little bit by adding " pointer-events:none; " in the css field. This will let you click the multi widget through the text widget.

**Comment by jean-emmanuel** [comment]
The [matrix](https://osc.ammd.net/widgets/matrices/#matrix) provides this kind of flexibility, some examples can be found here: https://github.com/jean-emmanuel/open-stage-control/issues/320

**Comment by pat1shea** [comment]
Event better! This not only solve the label issue but all other multi value property also
 
Thank
Patrick
 
-----Original Message-----

**Comment by jean-emmanuel** [comment]
:+1:
