### ISSUE TITLE
darkside of the moon sur un raspberrypi 3b+ 

### ISSUE THREAD

**Issue by nlebellier** [jean-emmanuel/open-stage-control#336]
bonjour Emmanuel,

Après installation à partir des sources, npm start > écran tout gris
![2018-07-20-142310_1680x1050_scrot](https://user-images.githubusercontent.com/4880966/43002351-bd7d0580-8c28-11e8-831f-3d6b50d53e23.png)

version 0.33.2

Où peut-on trouver un journal des erreurs ?.

merci pour une éventuelle réponse mais rien de pressé !

**Comment by jean-emmanuel** [comment]
Il y a des soucis de compatibilité avec electron sur rpi, je pensais que c'était réglé mais visiblement non. Tu as deux solutions:
- editer `package.json`, remplacer `"electron": "~1.8.7",` par `"electron": "~1.7.11",`  et refaire un `npm install`; il me semble que cette version n'a pas ce problème
- lancer o-s-c sans electron, avec node, ça implique de se passer du launcher (mettre les options en ligne de commande) et oblige à être en mode headless (accès à l'interface avec chromium) : `node /path/to/open-stage-control/app/ --no-gui`

**Comment by jean-emmanuel** [comment]
edit: pour la 1ere solution, bien enlever le `~` avant le numéro de version.

**Comment by nlebellier** [comment]
ok merci j'ai testé tes deux solutions et c'est ok. il faut bien faire un npm run build après le npm start ?
la deuxième option avec Chromium fonctionne également 
donc je lance sans gui !

**Comment by jean-emmanuel** [comment]
Parfait ! `npm build` n'est nécessaire qu'après une mise à jour des sources (dossier `src`)

**Comment by cyberic99** [comment]
@jean-emmanuel j'en profite pour te demander ce qui prend le plus de ressources selon toi:
- la version electron, en nativ
- la version headless + chromium, sur la même machine

La solution 2 doit surement prendre plus de ram, mais à part ca?

**Comment by jean-emmanuel** [comment]
Donc à mon avis le mieux est de lancer sans electron en headless et d'utiliser un chromium bien configuré.

**Comment by jean-emmanuel** [comment]
Et surtout: ne jamais laisser le mode debug en production!

**Comment by nlebellier** [comment]
c'est quoi un chromium bien configuré ? qu'est-ce ce que tu désactives ?

---
Nicolas Le Bellier








2018-07-20 16:29 GMT+02:00 jean-emmanuel <notifications@github.com>:

**Comment by cyberic99** [comment]
A mon avis il faut surtout vérifier que l'accélération 2D voire 3D est bien activée

**Comment by jean-emmanuel** [comment]
À partir de la version 0.34.0, un les paquets pour rpi / armv7l seront compilés avec la version 1.7.11 d'electron; un script spécifique a été ajouté (`npm run package-rpi`).

**Comment by jean-emmanuel** [comment]
-> v0.34.0

**Comment by nlebellier** [comment]
Merci ! Je teste dès que possible.

---
Nicolas Le Bellier








2018-07-26 10:44 GMT+02:00 jean-emmanuel <notifications@github.com>:
