### ISSUE TITLE
Having 2 different tab openned on two different browser

### ISSUE THREAD

**Issue by pat1shea** [jean-emmanuel/open-stage-control#337]
Is it possible to have two browser window on the same app but viewing 2 different tabs? Right now when I click on a tab both windows are switching to the new tab.

Patrick

**Comment by jean-emmanuel** [comment]
You can set the the tabs' parent `bypass` property to `true` to prevent it from sending osc messages on tab selection, this will prevent synchronization with other clients as well.

**Comment by pat1shea** [comment]
I tried that and set bypass on all my tabs but both browser windows still keep showing the same tab.

**Comment by jean-emmanuel** [comment]
It's the tab's parent that must be bypassed, as it sends its current selected tab through osc by default.

**Comment by pat1shea** [comment]
Brillant, that does exactly what I wanted.
 
Thanks again
Patrick
 
 
-----Original Message-----

**Comment by jean-emmanuel** [comment]
cool ;)


Le 21/07/2018 à 19:50, pat1shea a écrit :
