### ISSUE TITLE
Feature request: show dictonaries values for switches

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#338]
Hello

It could be useful to be able to display the values of a switch when they are objects.

For instance, if a switch contains
```
{
  "1": { "name": "song1" },
  "2": 2
}
```
, we see:
```
1: [OBJECT OBJECT]
2: 2
```
Would it be possible to add a function to 'stringify' dictionaries?
Maybe this is already possible with math.js but I couldn't find a way

Thanks

**Comment by jean-emmanuel** [comment]
Fixed in git!

**Comment by jean-emmanuel** [comment]
-> v0.34.0
