### ISSUE TITLE
How do I send multiple OSC commands in response to a single button press?

### ISSUE THREAD

**Issue by ke5stl** [jean-emmanuel/open-stage-control#340]
like the subject says:

if I have a button, to be pressed in a one-shot kind of way (eg: only when pressed), I see how to do that and only send 1 osc message as result.

but, if I want the button to initiate a series of osc and/or midi messages, how is that done?

please advise!

**Comment by cyberic99** [comment]
Isn't it possible to do this with linked widgets too?

**Comment by jean-emmanuel** [comment]
I'll try to think of something clever to make this possible, mabe something like a very simple "script" widget that gets executed everytime it receives a value.

**Comment by jean-emmanuel** [comment]
Script widget prototype is in git (add widget > inputs > scripts). https://github.com/jean-emmanuel/open-stage-control/blob/master/resources/docs/widgets/inputs.md#script
This might open some cool hacking possibilities...

**Comment by cyberic99** [comment]
looks cool! @jean-emmanuel could you also expose value, send() and set() in other formulas too? ie in value fields etc?
They could be useful too. (Is value equivalent to @{this} ?)

**Comment by jean-emmanuel** [comment]
I don't think it's a good idea, it's much harder to control precisely how and when formulas get executed in these contexts.

Currently the script widget doesn't store received values so @{this} is undefined. This is to make sure execution only happens when it is explicitly required.

**Comment by cyberic99** [comment]
I agree that it won't be easy to know what happens when. But it could be useful for a pushbutton for instance ,to use send() in the 'on' field, to be able to send several OSC messages....

But I agree that the beheavior will be hard to guess when the button *receives* something...

**Comment by jean-emmanuel** [comment]
You could link a push and a script together to do what you describe.

**Comment by cyberic99** [comment]
yeah right

**Comment by jean-emmanuel** [comment]
-> v0.35
