### ISSUE TITLE
Broken argv Key references in makeDefaultConfig

### ISSUE THREAD

**Issue by rveitch** [jean-emmanuel/open-stage-control#343]
Commit https://github.com/jean-emmanuel/open-stage-control/commit/c6411d443e1436f49a8c2110c969cc32d57fa1e5 breaks the `argv` key references in `makeDefaultConfig`.  By changing them to the human-readable format used by the aliases, the defaults no longer properly read keys from saved/default config files user entered fields.

I noticed this when trying to debug why send targets no longer worked for me.

**Example**
Previously: `targets: argv.s || argv.sync || false,` (this works)
Currently: `targets: argv['send'] || argv.sync || false,` (no key ref, will end up returning false)

**Comment by jean-emmanuel** [comment]
Sorry, I forgot to update the launcher as well (this doesn't occurs in command line), will fix soon !

**Comment by jean-emmanuel** [comment]
Should be fixed in v0.34.2 !
