### ISSUE TITLE
Possible Bug in MultiXY

### ISSUE THREAD

**Issue by fg-uulm** [jean-emmanuel/open-stage-control#344]
Hi, 
specs first: Running v0.34.2  on Win10x64 Enterprise.

I'm using a MultiXY within a Panel, which is the linkedWidget of a Switcher. Besides the MultiXY, there are also several buttons and other stuff in the Panel. All of the Panel components have their OSC adress set using the "value._selected" variable of the switcher (e.g. /projector@{pswitcher.value._selected}/blackout), which should resolve to a number and thus allow for separate control of different devices, depending on the switcher value. With the buttons (and also rotaries etc.) this works fine, however, the MultiXY does not seem to update the variable value after the first time (always stuck with the value the switcher had at the last edit to the MultiXY component). Do you have any idea what might cause this, or even a fix or workaround?

Thanks, 
Flo

**Comment by fg-uulm** [comment]
Side note: Tried to get a local development environment with openstagecontrol running to investigate the bug (via git clone, node was already installed), but didn't succeed - is there some document or anything to guide through this process?

**Comment by jean-emmanuel** [comment]
Hi,

The process for running from source is explained here: https://osc.ammd.net/getting-started/#run-from-sources.

Could you please upload your session file here to help me understand the issue ? (append `.txt` to the filename, github doesn't accept `.js` files)

**Comment by fg-uulm** [comment]
[2018-07-31_10-16.txt](https://github.com/jean-emmanuel/open-stage-control/files/2244860/2018-07-31_10-16.txt)
There you go - and thanks for the link!

**Comment by fg-uulm** [comment]
Small addition: Apparently the same behaviour also occurs for sliders (at least range sliders)

**Comment by jean-emmanuel** [comment]
The `@{}` syntax doesn't give access to nested structures values, you should replace `@{pswitcher.value._selected}` with `#{@{pswitcher}._selected}` (see https://osc.ammd.net/extras/advanced-property-syntax/)

**Comment by fg-uulm** [comment]
Thanks for your answer Jean! Unfortunately I also already tried this and some other variations, but it changes nothing :/ The controls that worked before still work with your syntax, and the ones who didn't work still show the same problem...any further ideas? Otherwise I'd start to dig into the sources, maybe you have a tip for a good starting point there?

**Comment by jean-emmanuel** [comment]
I found and fixed the bug, it was the split property that wasn't properly updated !

**Comment by fg-uulm** [comment]
Another issue that appeared to me, which may be somehow related or not:
I now have the switcher running, together with the ._selected variable in the OSC addresses of the switched widgets (see example above). If I use the switcher however, the sent OSC messages expose a behaviour different to what I would expect:

Expected behaviour:
- Switcher is switched
- Variables are being evaluated
- Widgets are being updated to stored values from switcher
- OSC Messages are sent (so the recalled values get sent to the address of the device the switcher was set to)

Observed behaviour:
- Switcher is switched
- Widgets are being updated to stored values from switcher
- OSC Messages are sent (so the recalled values get sent to the address of the device the switcher was set to)
- Variables are being evaluated

This means, that on switching, the values are recalled correctly, but are being sent to the wrong device because the ._selected variable is only evaluated afterwards. On the next widget interaction the values are evaluated correctly.

Is this some sort of bug, or maybe even correct behaviour? If latter, can I do anything to prevent this "wrong" messages?

**Comment by jean-emmanuel** [comment]
It's an interesting edge case ! Fixed in git, hopefully it have side effects... ;)

**Comment by fg-uulm** [comment]
Merci beaucoup, Jean, great work! Works like a charm, so far with no visible side effects. There is one more small thing about the switcher behavior I might make a feature request later on, but nothing to worry about...but first I have to fix my own application errors.
If you ever happen to visit southern germany let me know, there's now a 24 projector 6K powerwall controlled by your great software :)

**Comment by cyberic99** [comment]
@fg-uulm can you make a video?

**Comment by jean-emmanuel** [comment]
You are welcome !

Let me guess, you'd like the switcher's states to be populated at initialization ? That'd make sense :)

I sure will, I haven't played in Germany for a while but it's likely to happen again someday.
