### ISSUE TITLE
OSC ERROR: malformed address: "undefined"

### ISSUE THREAD

**Issue by schoko11** [jean-emmanuel/open-stage-control#345]
hello,

i have two little issues with open stage control, after connecting on the tablet, it takes about 2 seconds to switch to another tab.(i use the reaper open stage control, this example is also on your website), and the error above.

open stage control options:
send: 192.168.0.1:7000
port: 7080
instance-name:schoko
fullscreen:true

hardware:
xoro megapad 1851,android 4.4.2, connection via wlan, mac and ip(192.168.1.100) address can be seen in the network settings,
connection with chrome(67): 192.168.1.101:7080

how to debug the lag and the error?
Great software!(hopefully it is not my buggy android firmware, which i can't replace...)

**Comment by jean-emmanuel** [comment]
Hi, thanks for our feedback :)

I think this Reaper interface was designed for large desktop screens, it is quite heavy indeed. There's isn't much you can do about it besides developing a lighter interface for your device, with less widgets. I'm not a Reaper user myself, but @ThrashJazzAssassin, who made this session might be of some help.

Now about the error I haven's been able to reproduce it yet, are you using the unmodified session from the [REAPER-OSC-panels](https://github.com/ThrashJazzAssassin/REAPER-OSC-panels) repository ? When does it occur exactly ?

**Comment by schoko11** [comment]
hi!
thank you for your quick reply!
yes i took the original template.
i could reproduce it finally
on the server
1.) editor on
2.) change the width of a grid
3.) save as
4.) send all
the debugger says(one example out of 20..??)
"
Osc sent: { address: '/fxinstparam/15/value',
args: [{type: 'f', value: 0}]} to: 192.168.0.1:7000
osc error: malformed address: "undefined"
....
"
the error message is displayed when "args" is matching with the above...
thank you! Dienstag, 31 Juli 2018, 07:36nachm. +02:00 von jean-emmanuel  notifications@github.com :

**Comment by jean-emmanuel** [comment]
Alright I found the problem, it will be fixed soon thank you (the good news is it's harmless)

**Comment by jean-emmanuel** [comment]
> v0.34.4
