### ISSUE TITLE
Add multiple values and outputs

### ISSUE THREAD

**Issue by AndreasAustPMX** [jean-emmanuel/open-stage-control#346]
For OSC:
Hey "Open Stage" is really cool and it would be great to send multiple values for multiple targets with one klick like this:
(maybe with a delay)
[-Super Button-]

output [+] ->(klick to set more outputs in array)
------------------------

Output1:
> delay:{0 sec}
> target:  {"10.1.145.12:8090"}
> address: {/slider/x}
> value: {150}

------------------------

Output2:
> delay: {2 sec}
> target:  {"10.1.145.13:8090"}
> address: {/txt/info}
> value: {"Hello World"}

------------------------

**Comment by jean-emmanuel** [comment]
I'm merging this with #340

**Comment by jean-emmanuel** [comment]
On the delay subject, I'm not willing to develop timing related features anytime soon, some basic timing things can be achieved server-side from the custom module.
