### ISSUE TITLE
Buffer() DeprecationWarning grave ou pas ?

### ISSUE THREAD

**Issue by epnlespieux** [jean-emmanuel/open-stage-control#348]
c'est embêtant ou pas ?

```(node:1659) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.```

**Comment by jean-emmanuel** [comment]
Non, juste un avertissement, il faudra que je fasse un petit ajustement pour que ça ne devienne pas une erreur avec une future version de node.

**Comment by jean-emmanuel** [comment]
J'ai reglé le problème dans le code d'osc, les différentes dépendences vont très probablement faire de même ou l'on déjà fait, le message devrait donc disparaitre d'ici quelques versions.
