### ISSUE TITLE
Command line switch for loading state files?

### ISSUE THREAD

**Issue by fg-uulm** [jean-emmanuel/open-stage-control#349]
Hi Jean,

title says all, is it possible to implement a command line switch for loading an initial state file and to trigger "send all" once?

Thanks!

**Comment by jean-emmanuel** [comment]
Good idea !

**Comment by fg-uulm** [comment]
Thanks! A little more background info - I'm using a switcher to have presets for some other widgets , however running the whole setup on a raspberry pi, which might lose power from time to time. So after that, not only the values previously set are gone, but also the switcher "presets". Wouldn't be that much of a  problem if the access wouldn't take place via web interface on mobile devices - for them it's quite hard to distribute and upload the saved state file (our emergency solution is Dropbox at the moment). Thus the need for loading it at startup like already possible with the session file.

And sending the initial values would be great because the values loaded then correspond to the values being sent out from the beginning, which makes sense in this combination (OpenStageControl + OLA on the pi sending DMX to light fixtures - different project than with the two bugs I reported last week ;) ).

**Comment by jean-emmanuel** [comment]
It's in git, here is what happens when a clients loads a session
- it receives the state and applies it
- it sends its osc messages if there are no other clients connected to the server
- it receives the other clients' current states (if any)

**Comment by jean-emmanuel** [comment]
-> v0.35
