### ISSUE TITLE
width and height of current Tab

### ISSUE THREAD

**Issue by schoko11** [jean-emmanuel/open-stage-control#350]
This might be an idea, i don't know if it is worth to mention, but i will give it a try.
Thank's to open-stage-control i plan to use a fairly standard touch screen instead of a quite "crapy" android tablet with lemur.

It would be nice to have a display (in the menu to the right?) show the "right-most" and "down-most" Pixel count. 
-> e.g.: widget 20 is positioned farest to the right at 400 pixel(+ 100 pixel widget width) would show 500 pixel width -> you know really fast how much you can move objects in this direction without getting a scrollbar -> something like "Template" Dimensions.
It would be further nice to see this info before loading a file with the start dialog.
 
I wanted to make this a feature request, but i just found the issue submit...?

a second thing to mention, would be the possibility to minify the json object(built in minify save), maybe a little bit faster loading times..? -> i tried it out manually but i am not sure if there was a real benefit 

Thank you!

**Comment by jean-emmanuel** [comment]
Note: when loading a session file from the session history, the session data sent by the server is minified anyway.
