### ISSUE TITLE
multiple visualizers with the same duration = hiccup

### ISSUE THREAD

**Issue by jango-fx** [jean-emmanuel/open-stage-control#352]
i have just 2 visualizers set on 2 different addresses, receiving continuous values between 0.0 and 1.0.
as long i have set them to different durations all is good. except, they are not in sync.
as soon as i set them to the same duration one seems to stop. the other seems to reset / jitter / hiccup.

or is there some missunderstanding?

![works](https://user-images.githubusercontent.com/2352352/44609637-cdb94800-a7f8-11e8-9791-acd619365337.gif)
![doesnot](https://user-images.githubusercontent.com/2352352/44609641-d1e56580-a7f8-11e8-84b4-3b35979674aa.gif)

im working on macOS 10.13.6 with open stage control version 0.35.0.

**Comment by jean-emmanuel** [comment]
Hmm, it works if you give the two visualizers different `id`s. It's due to the widget synchronization logic that doesn't really fit in this case, will fix soon. Thanks for the feedback !

**Comment by jean-emmanuel** [comment]
Fixed in git

**Comment by jean-emmanuel** [comment]
-> v0.36.0
