### ISSUE TITLE
Feature request: ability to specify an alternative path for theme files

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#353]
Would it be possible to look for the theme files in another directory (eg $HOME/.config/open-stage-control) or in the same folder as the session file ? (so we could have different themes for different sessions)

Because right now, depending on where o-s-c is installed, theming the app could require root access

Thx

**Comment by jean-emmanuel** [comment]
You can already load theme files with their absolute path:
`open-stage-control --theme /path/to/custom.css` 
https://osc.ammd.net/extras/theming/

**Comment by jean-emmanuel** [comment]
To elaborate: the default path that might require root access (for themes that can be loaded just by names) is for built-in themes, aka "official"  / "maintained" :). Having different theme for simultaneous sessions doesn't strike me as a something necessary, however it's already possible to embed a theme in a sessions file (using the root's css property).
