### ISSUE TITLE
make a widget pulse to an external signal

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#354]
Gello

I try to trigger a css animation each time a "/BEAT" OSC event is received
for example a fadeout.

I d like to trigger the animation each time a /BEAT is received

Using tricks found in the "FAQ and tips" issue, I am able to make my widget blink, but I cannot get the css animation to retrigger (it is played only once)

It there a way to retrigger the css animation or reinit the object?

**Comment by jean-emmanuel** [comment]
Try the attached session file: [pulse.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/2334967/pulse.json.txt)
```
#{
    @{beat_receiver}; #subscribe to value updates
    value = randomInt(0,100);
}

@keyframes pulse-#{value} {
    0% {opacity:0;}
    10% {opacity:1;}
    100% {opacity:0;}
}
```
.led:before {
    animation: pulse-#{value} .5s 1 forwards
}


The trick here is to use a random suffix to make sure the animation is reset each time the input's value updates. You should be able to replace `@{beat_receiver}` with `OSC{/BEAT}` but currently OSC{} receivers don't update unless their value change, I'm gonna fix this.

**Comment by jean-emmanuel** [comment]
The aforementioned fix for the `OSC{}` is in git.

**Comment by cyberic99** [comment]
It works great, thanks!

I have also tested the OSC{} syntax, working too

Just one remark:

instaed using a random int to generate a new animation, couldn't we use for instance the current timestamp? (in ms)

Will all these animations be correctly garbage collected? because at 200BPM, this can make a lot of beats ;-)

**Comment by jean-emmanuel** [comment]
That'd be more reliable, I'll add it. Yes, css animations should not create memory leaks. Now while this is a nice trick, it might be worth having a built-in way to do this with the led widget, I'll think about it.

**Comment by cyberic99** [comment]
maybe you could add a property to retrigger css animations or a function to retrigger them?

That would make it more generic.

I have been able to use this method to make a push button blink, it doesn't apply only to leds

**Comment by jean-emmanuel** [comment]
Hmm, then adding a timestamp on the animation's name is the best way to retrigger it.

**Comment by cyberic99** [comment]
A few months after... I notice on another of my computers (a core i5), such a button is eating 50% of the cpu time.
If I delete the ``animation`` css property, the cpu goes back to idle...

**Comment by cyberic99** [comment]
No, in fact something is funny...

When I want to disable the blink, I simply set the period to thousands of seconds....

If I use 1s, cpu usage is normal.

But with 5000s, it eats 50% of cpu time!

**Comment by jean-emmanuel** [comment]
Looks like a chromium bug to me ! Instead of changing the period to stop the animation you could set the iteration count to `0` instead of `infinite`.

**Comment by cyberic99** [comment]
I already have a workaround, but thanks for the tip ;-)
