### ISSUE TITLE
`doubleTap` not working on iPad with toggle button

### ISSUE THREAD

**Issue by SteffeyDev** [jean-emmanuel/open-stage-control#356]
I enabled the `doubleTap` option for several toggle buttons in my layout, and while it does take a double click on a computer to trigger the toggle, it only takes a single tap on my iPad.  Everything else is constant between the computer and iPad.  I love the idea of doubleTap as I am worried about users accidentally bumping into buttons on the iPad that have significant effects.  Let me know if you need any other details.  I am using the latest version of open-stage-control (downloaded a few days ago)

**Comment by jean-emmanuel** [comment]
Hi, thank you for your feedback ! I think I've found the cause of the issue. Could you load your session in the [online demo](http://openstagecontrol.herokuapp.com) and check if it's fixed ?

**Comment by SteffeyDev** [comment]
Thanks for getting back to me! The issue does not appear to be fixed in the online demo, I tested my configuration and even just creating a new session and adding a doubleTab toggle button still toggles with only one tap on my iPad.

I also noticed that all my custom colors were gone when I loaded into the demo, not sure if that is intended or not...

**Comment by jean-emmanuel** [comment]
Alright, after a few more tweaks it seems to be fixed, can you confirm ? About the color issue, could you be more specific ? How are these colors defined ? (You can upload your session file here to as well, just append `.txt` to the filename otherwise github won't accept it)

**Comment by jean-emmanuel** [comment]
Great ! I restored the color field, I've been refactoring the code lately and this was a little mistake ;)

**Comment by SteffeyDev** [comment]
Cool, thanks for helping me out!  I love your work and already transferred my whole layout from TouchOSC to Open Stage Control.

**Comment by jean-emmanuel** [comment]
Feel free to share ;)
