### ISSUE TITLE
Create widget via OSC message

### ISSUE THREAD

**Issue by uliss** [jean-emmanuel/open-stage-control#359]
Is it possible to create new widget with OSC message?
I found ability only to edit widgets via /EDIT message. 

I want to do automatic GUI building for PureData patches. So this ability could be very useful for me.

Thank you!

**Comment by jean-emmanuel** [comment]
As @cyberic99 said, you have to edit a container's  `widgets` property to add new widgets to it.

**Comment by levelig** [comment]
Thank you very much!

**Comment by jean-emmanuel** [comment]
:)
