### ISSUE TITLE
No OSC message sent

### ISSUE THREAD

**Issue by workino** [jean-emmanuel/open-stage-control#360]
Hello,
i'm trying open stage control and i create a simple butto to send a command to my own osc server written in python.
If i try with send_osc (pyliblo) everything is working like expectation, but when i try to send command trough Open Stage Control i can see in debug the message:
OSC sent:  { address: '/playlist',
  args: [ { type: 's', value: '' }, { type: 'i', value: 1 } ] } To : 192.168.0.24:5055
OSC sent:  { address: '/playlist',
  args: [ { type: 's', value: '' }, { type: 'i', value: 2 } ] } To : 192.168.0.24:5055
OSC sent:  { address: '/playlist',
  args: [ { type: 's', value: '' }, { type: 'i', value: 1 } ] } To : 192.168.0.24:5055

but server doesn't receive nothing.

On the other hand if server send mesage all is working like expectation.

This is my command to lunch Open Stage Control:
./open-stage-control -s 192.168.0.24:5055 -o 5006 -d -n

How can i solve?
Regards

**Comment by jean-emmanuel** [comment]
There was a little regression that added an extra empty string argument to your messages, it's just been fixed in v0.37.2 (uploading at the moment). Thank you for the feedback !
