### ISSUE TITLE
Feature request: ability to add a custom class in the css field

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#361]
Hello

Is it possible to put something like this in the css field: ``class: myclass`` to add a class to the target widget?

or even better, something like: ``class: #{@{this}==1?"class1":"class2 class3"}``

Thx

**Comment by jean-emmanuel** [comment]
That's doable, but how is it different from writing conditional css rules ?

**Comment by cyberic99** [comment]
If you want to restyle several widgets conditionaly, and using several rules, I think it is more practical and clean to put the rules only once, in a separated class

**Comment by cyberic99** [comment]
That's the whole point of css classes, isn't it?
to group several properties and apply them conditionaly at once

**Comment by jean-emmanuel** [comment]
I see how css alone can be limited here. I'd rather avoid adding a property just for this though, I'll try think of something handy within the css property to handle this, maybe [`@extend` rule](https://tabatkins.github.io/specs/css-extend-rule/#extend-rule), not really css, but close enough...
