### ISSUE TITLE
OSC on iPad?

### ISSUE THREAD

**Issue by Norihirock** [jean-emmanuel/open-stage-control#362]
Hi, I'm new to GitHub and Open Stage Control.

How do you use OSC on an iPad? I think I need to download amd64.deb file but I cannot do it from my iPad. Do I have to download the file to my computer and convert it to IPA file?

Thanks.

**Comment by jean-emmanuel** [comment]
Hi,
Open Stage Control itself doesn't run on the iPad, it is a desktop app for Linux/Windows/OSX that runs as a webserver which you can connect to with your iPad's browser (see [supported platforms](http://osc.ammd.net/#supported-platforms)).

**Comment by Norihirock** [comment]
Thank you for your feedback! It seems I had some misunderstanding... Open Stage Control is now working on my Mac without any issues.
