### ISSUE TITLE
getting fader or button value

### ISSUE THREAD

**Issue by mrsstaceyseigle** [jean-emmanuel/open-stage-control#364]
Is there any way to get a fader or button current values and preAgr without moving the fader or pressing the button. 

Example let say that I have not moved the fader or button but they had a preset value of 50 .  Using pure data I can get the values or preAgr if I press the button or move the fader. Is there any way we can ping the widgets and get all of there values and PreAgr

**Comment by jean-emmanuel** [comment]
Yep, http://osc.ammd.net/extras/remote-control/#get-target-id :)

**Comment by mrsstaceyseigle** [comment]
could you provide an example using pure data

**Comment by jean-emmanuel** [comment]
Sorry but I can't, I haven't used pure data in years. The idea is to send `/GET 127.0.0.1:5555 widgetId` or `/GET 127.0.0.1:5555 /widget/address preArg` to o-s-c to retrieve the matching widget's value on port 5555, enabling the `debug` flag can help checking what's received sent by o-s-c.

**Comment by mrsstaceyseigle** [comment]
When I send the command you provided 
/GET 127.0.0.1:5555 widgetId

my router is as follow
/GET 127.0.0.1:9696 fader_1

I get the follow output in the debug window
OSC received: { address: '/GET', args: [ '127.0.0.1:9080', 'fader_1' ] } From : 127.0.0.1:59145
OSC sent: { address: '/GET',
args: [ { type: 's', value: 'fader_1' }, { type: 'f', value: 91.59 } ] } To : 127.0.0.1:9080
