### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by mrsstaceyseigle** [jean-emmanuel/open-stage-control#366]
Can Open stage control handle basic math. 1+2 
Can we setup conditions like if this is true then do something. 

I am trying to use the script widget but do not understand how to use it. 

Can we run javascript do make things happen.

**Comment by jean-emmanuel** [comment]
The [formula syntax](http://osc.ammd.net/extras/advanced-property-syntax/#formulas), along with the [inheritance syntax](http://osc.ammd.net/extras/advanced-property-syntax/#inheritance) can be used to write conditions in any property. Here is a simple example for defining a widget's `color` property according to another widget's value:

```
#{
@{other_widgets_id} > 0.5 ? "red" auto
}
``` 

Check the attached session file: when the slider's value is above 0.5, the text widget turns red.
[condition.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/2434566/condition.json.txt)

----

The script widget add a few functions to the formula syntax, but it's not required for doing simple maths between widgets.

No, you can't write javascript within the app, but you can from the [custom module](http://osc.ammd.net/extras/custom-module/) which filters the app's inputs and outputs.

**Comment by jean-emmanuel** [comment]
Thank you very much ! :-)

**Comment by mrsstaceyseigle** [comment]
could you tell me what I am missing. Try to tell if the fader is > 0.5 then red. if < 0.5 blue.  if this can be done.

#{
@{fader_1} > 0.5 ? "red" : "auto"
}
#{
@{fader_1} < 0.5 ? "blue" : "auto"
}

**Comment by jean-emmanuel** [comment]
```
#{
@{fader_1} > 0.5 ? "red" : "blue"
}
```
