### ISSUE TITLE
Running on ARMv6?

### ISSUE THREAD

**Issue by simonmcbrown** [jean-emmanuel/open-stage-control#368]
Is it possible to run open-stage-control on a Pi-Zero which is ARMv6?  Presumably one would follow the run/build from sources instructions?

**Comment by jean-emmanuel** [comment]
The engine (electron) doesn't work on armv6 but it should be possible to run the app [from sources](http://osc.ammd.net/getting-started/#run-from-sources) in headless mode [with node](http://osc.ammd.net/getting-started/#running-without-electron):
```
git clone https://github.com/jean-emmanuel/open-stage-control
cd open-stage-control/
# uncomment next line if you want the latest release
# instead of the current development version
# git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
npm install
npm run build
node ./app --no-gui
```

**Comment by simonmcbrown** [comment]
Perfect.  Thank you very much.
pi@raspberrypi:~/Downloads/open-stage-control $ node ./app --no-gui
App available at http://127.0.0.1:8080 & http://192.168.2.10:8080

Would  i be correct in that one cannot build package for armv6 as the missing electron stuff will make it fail?  This is just for interest.

**Comment by jean-emmanuel** [comment]
You are correct ;)

**Comment by simonmcbrown** [comment]
OK, I'm lacking understanding here.  My objective is to be running PureData on a piZero and get OSC messages to it using an android tablet via open-stage-control.  I have open-stage-control running headless on the pi and can bring up the interface in chrome running on a laptop.  The bit I dont get is that when I click browse I am presented with the laptop filesystem not the pi's.  Even so if I navigate to the widgets.json file or start new session I get the following errors:  

pi@raspberrypi:~/Downloads/open-stage-control $ node ./app --no-gui
App available at http://127.0.0.1:8080 & http://192.168.2.11:8080
[Renderer process error]
Uncaught TypeError: Object.values is not a function
    at reset (src/browser/js/app/managers/widgets.js:235:34)
    at reset (src/browser/js/app/parser.js:23:22)
    at load (src/browser/js/app/managers/session.js:37:23)

Is this due to electron not running on the pi?  I thought the electron bit needed to be working on the laptop I'm running chrome from.  Is this wrong?  If so is my use case not possible with a Pizero?

Many thanks, Simon.

**Comment by jean-emmanuel** [comment]
> The bit I dont get is that when I click browse I am presented with the laptop filesystem not the pi's

That's normal. Ideally I'd want to manage files on the server remotely but that's far from trivial and I haven't found a satisfying solution yet. For know, you must store sessions on client side or rely on the server's session history if the files are stored on th pi.

> Uncaught TypeError: Object.values is not a function

Looks like a browser compatiblity issue, not related to node or electron. What's your browser exactly (including version) ?

**Comment by jean-emmanuel** [comment]
This error is probably the same as #417, I'm closing here since the original issue has been addressed.

**Comment by simonmcbrown** [comment]
Sorry for the delay.  I agree with closing.  For completeness:
1)  Uncaught TypeError: Object.values is not a function - yes this was an old browser issue.
2) My other issues came from i) the complicated network situation not passing info between two subnets and ii) me not understanding that you have to explicitly send to an ip & port.  Got the pi/PD receiving OSC messages using:
node da-di-da/open-stage-control/app --no-gui --port 7654 --send pi-ip-address:6789

Thanks for your help and great program.

**Comment by simonmcbrown** [comment]
npm install is now failing. Any ideas? watchify is indeed missing.

Many thanks.

pi@raspberrypi:~/Downloads/open-stage-control $ git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
Note: checking out 'v0.46.1'.

HEAD is now at fea808e7... package; 0.46.1
pi@raspberrypi:~/Downloads/open-stage-control $ npm install
npm WARN deprecated cardinal-spline-js@2.3.10: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! path /home/pi/Downloads/open-stage-control/node_modules/watchify/bin/cmd.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/pi/Downloads/open-stage-control/node_modules/watchify/bin/cmd.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-05-18T18_50_25_955Z-debug.log

system info:
model name	: ARMv6-compatible processor rev 7 (v6l)
Linux raspberrypi 4.19.42+ #1219 Tue May 14 21:16:38 BST 2019 armv6l GNU/Linux
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"

**Comment by jean-emmanuel** [comment]
It seems the installation script fail to find the  system's `chmod` command, is it available in your terminal ?
