### ISSUE TITLE
Launch program

### ISSUE THREAD

**Issue by mrsstaceyseigle** [jean-emmanuel/open-stage-control#370]
Can we launch a different program using Open Stage Control. 

example
assign a button to open notepad or run cmd when the button is pressed.

If not can you add this. 

I would like to open up Open Stage Control and have a widget that can send a cmd or terminal command

Widget>cmd

Widget> terminal

**Comment by jean-emmanuel** [comment]
Short: nope

Long: open stage control can only send and receive osc/midi messages, it's designed to be best used in a modular environment (where each software handles one task and does it well).  Spawning a terminal is out of the app's scope (and always will be), it must be handled elsewhere. For instance, you would need an external script that spawns a terminal when receiving the appropriate osc message.
