### ISSUE TITLE
touche Supprimer

### ISSUE THREAD

**Issue by Ezrabox** [jean-emmanuel/open-stage-control#374]
la sélection + touche "supprimer" ne supprime pas les widgets

(Sierra + v 0.37.4)

**Comment by jean-emmanuel** [comment]
Peux-tu préciser ? Je ne parviens pas à reproduire ce bug.

**Comment by jean-emmanuel** [comment]
Cela devrait ếtre résolu grâce à la propo de Martin (#380) !
