### ISSUE TITLE
confirmation suppression

### ISSUE THREAD

**Issue by Ezrabox** [jean-emmanuel/open-stage-control#375]
la confirmation de suppression ne me semble pas très pertinente car le "pom+z" suffit si on fait une erreur. Si tu tiens à le garder peut serait il intéressant que ce soit une option ex: une case à cocher "ne plus afficher ce message"

**Comment by jean-emmanuel** [comment]
Effectivement, l'arrivée de l'historique d'annulation est très récente et je n'y avait pas pensé.

**Comment by jean-emmanuel** [comment]
hop, pour la prochaine version
