### ISSUE TITLE
raccourcis "Editer texte"

### ISSUE THREAD

**Issue by Ezrabox** [jean-emmanuel/open-stage-control#377]
pouvoir éditer le texte par un double click? (ou un raccourcis)

**Comment by jean-emmanuel** [comment]
Pourquoi pas, je vais tester ça (l'édition se fera quand même depuis le panneau latéral mais on doit pouvoir se servir du double click pour mettre le focus sur le bon champ d'édition).

**Comment by jean-emmanuel** [comment]
Finalement j'ai opté pour le raccourci clavier F2 qui est un standard assez répandu, le double click n'était pas adapté dans certains cas de figures.
