### ISSUE TITLE
Plier / déplier les onglets de la barre d’édition latérale  

### ISSUE THREAD

**Issue by Ezrabox** [jean-emmanuel/open-stage-control#378]
de manière à avoir une vue d'ensemble et pas nécessairement avoir les infos de session en permanence par exemple

**Comment by cyberic99** [comment]
as tu vu le bouton 'hamburger' en haut à droite?

**Comment by Ezrabox** [comment]
oui, ma suggestion porte sur les sections à l’intérieur de la barre d'édition, c'est pas un truc fondamental mais ça serait bien de ne déplier (verticalement) que les sections qui nous interesse régulièrement. Par exemple la section générale, je ne m'en sert que rarement et pourtant elle est dominante en permanence, donc si je pouvais la plier, je verrais directement ce qui m’intéresse le plus fréquemment.

**Comment by jean-emmanuel** [comment]
Petite session code dans le train... c'est dans git pour la prochaine version,(visible dans la demo en ligne).

**Comment by jean-emmanuel** [comment]
version beta 0.38 en cours d'upload
