### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#38]
Downloaded from git (commit 91b5db7e39dad7ad3d7ecafc05bb5f99021ab869) got only to npm install.

[npm-debug.log.zip](https://github.com/jean-emmanuel/open-stage-control/files/613995/npm-debug.log.zip)

**Comment by jean-emmanuel** [comment]
Damned, I might have started to use some node v6 features that could explain the failure under v4, I'll check that asap...

**Comment by jean-emmanuel** [comment]
it's something else ! still investigating

**Comment by jean-emmanuel** [comment]
Running `npm cache clean` before `npm install` should do the trick.

**Comment by jean-emmanuel** [comment]
see https://github.com/npm/npm/issues/5133

**Comment by ovenwerks** [comment]
On Sat, 26 Nov 2016, jean-emmanuel wrote:

> Damned, I might have started to use some node v6 features that could explain the
> failure under v4, I'll check that asap...

Probably not a great idea to use versions of libs ahead of what the 
distros are using. But in my case I am willing to build a newer version if 
I need to.

--
Len Ovens
www.ovenwerks.net

**Comment by jean-emmanuel** [comment]
v6 is the current stable, it's not a dangerous one to update, but its not he problem here anyway ;)

**Comment by jean-emmanuel** [comment]
Wops, closed by mistake, have you tried `npm cache clean`

**Comment by ovenwerks** [comment]
Still have the same problem, npm cache clean, made no difference.
also tried:
rm -r open-stage-control
git clone https://github.com/jean-emmanuel/open-stage-control

To make sure there was nothing left from before.
I still get:

" Tell the author that this fails on your system:
npm ERR!     browserify src/browser/js/browser.js -o app/browser/scripts.js"

[npm-debug.log.zip](https://github.com/jean-emmanuel/open-stage-control/files/614375/npm-debug.log.zip)

**Comment by jean-emmanuel** [comment]
The provided debug.log doesn't show this error, can you send one that does ?

**Comment by jean-emmanuel** [comment]
Also, since this seems to fail :

`cp resources/images/logo.ico app/browser/favicon.ico && cd app && npm install && cd .. && npm run build-js && npm run build-css`

Can you try executing these function one at a time ?

**Comment by ovenwerks** [comment]
OK, start over again:
rm -r open-stage-control
sudo npm install -g npm
git clone https://github.com/jean-emmanuel/open-stage-control
cd open-stage-control
npm cache clean
...Fails as above...
cp resources/images/logo.ico app/browser/favicon.ico  - OK
cd app
npm install
cd ..  - OK
npm run build-js - FAIL

----------------------------8<-------------------------------
$ npm run build-js

> open-stage-control-builder@0.12.0 build-js /home/sda1/home/len/software/open-stage-control/open-stage-control
> browserify src/browser/js/browser.js -o app/browser/scripts.js

ReferenceError: Invalid left-hand side in assignment
    at module.exports (/home/sda1/home/len/software/open-stage-control/open-stage-control/node_modules/syntax-error/index.js:13:52)
    at DestroyableTransform._transform (/home/sda1/home/len/software/open-stage-control/open-stage-control/node_modules/browserify/index.js:640:23)
    at DestroyableTransform.Transform._read (/home/sda1/home/len/software/open-stage-control/open-stage-control/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/sda1/home/len/software/open-stage-control/open-stage-control/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at Labeled.Pipeline._write (/home/sda1/home/len/software/open-stage-control/open-stage-control/node_modules/stream-splicer/index.js:70:22)
    at doWrite (/home/sda1/home/len/software/open-stage-control/open-stage-control/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/home/sda1/home/len/software/open-stage-control/open-stage-control/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at Labeled.Writable.write (/home/sda1/home/len/software/open-stage-control/open-stage-control/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at Labeled.ondata (/home/sda1/home/len/software/open-stage-control/open-stage-control/node_modules/readable-stream/lib/_stream_readable.js:546:20)
    at emitOne (events.js:77:13)
---------------------------------------8<----------------------------------------

**Comment by jean-emmanuel** [comment]
Alright, I've tracked it down. Node 4 doesn't compile many javascript features I use, and since the browser-side compiled javascript is no longer shipped with the repository, building the app does requires node 6. 

It's a shame a didn't realized that earlier, however I won't backtrack on this, here's why: 

- node is a "dev" dependency, only needed for building the app, not for actually running it. It's quite common to be a little ahead of stable distros
- node v6 is the official stable
- using [nvm](https://github.com/creationix/nvm) makes building and using multiple node binaries very easy
- provided precompiled binaries will do the job for must users
- these new javascript features are just really really really handy ;)

**Comment by ovenwerks** [comment]
On Sun, 27 Nov 2016, jean-emmanuel wrote:

> Alright, I've tracked it down. Node 4 doesn't compile many javascript features I
> use, and since the browser-side compiled javascript is no longer shipped with the
> repository, building the app does requires node 6.
> 
> It's a shame a didn't realized that earlier, however I won't backtrack on this,
> here's why:

No problem. I will build it on both of my machines (linux 64bit and arm).

This web page:
http://osc.ammd.net/getting-started/

About half way down still says "Node.js >= 4.0"

--
Len Ovens
www.ovenwerks.net

**Comment by jean-emmanuel** [comment]
You're right, if's fixed now !

**Comment by jean-emmanuel** [comment]
I've found a workaround... i've added a building script that bypasses syntax checking after building the js file : running `npm run build-js-node4` instead of `npm run build-js` should work. You'll have to replace  `npm run build-js` with `npm run build-js-node4 in the `package.json` for the default scripts to work.

**Comment by jean-emmanuel** [comment]
It now detects node's version and disables the failing check if node < 6. https://github.com/jean-emmanuel/open-stage-control/commit/df9db253affd7b7fa2243f618ac72c5faf84d567

**Comment by ovenwerks** [comment]
On Mon, 28 Nov 2016, jean-emmanuel wrote:

> It now detects node's version and disables the failing check if node < 6. df9db25

Thank you. I have used both node 4 and 6 and it works. It seems I need to 
learn the CLI parameters all over again though.

As a note, is there any way of telling node what the system Arch is before 
doing anything? The R-pi and Node are at odds with each other. I found on 
the R-pi, I had to use node version 4 because there is something in Node6 
that looks at system arch part way through npm install and fails with a 
note about not knowing what to do with an arm machine. With node 4 it just 
works. Then I create an armv7l deb... which won't install because it is an 
armhf machine... So:
  npm install detects the arch as arm
  node only does armv6l, armv7l or armv8l (arm7l is correct it seems)
  dpkg wants armhf in the deb package before it will install

It seems there may be a place where I could set NODE_ARCH=armv7l because I 
have seen something like that in some of the command lines that go by.

Anyway, to cut things shorter, on the r-pi, I removed node 6, reinstalled 
node 4, made an armv7l deb package and the used a variation of:
https://ubuntuforums.org/showthread.php?t=636724
To change the package arch to armhf which dpkg was willing to install.

In both cases (node4 with armv7l and node6 with x64) when I start open 
stage control on it's own and load my map, it is ok. But when I use my 
script to start it the widgets won't release. So my script must be doing 
something wrong... of to more investigations.

Thank you for all your work. Now that I have it working natively on the 
PI, I can start working on the rest of my controller.

--
Len Ovens
www.ovenwerks.net

**Comment by jean-emmanuel** [comment]
>  As a note, is there any way of telling node what the system Arch is before doing anything

I don't know yet, I haven't been using node on arm a lot... maybe some log from the node 6 + arm build would help.

> dpkg wants armhf in the deb package before it will install

If its only a matter of arch name in the .deb package, in the main `package.json`, try editing the the line that starts with `"debarm"` and replace `--arch armv7l` with `--arch armhf`.

> But when I use my script to start it the widgets won't release

Don't hesitate to drop your script here  !

**Comment by jean-emmanuel** [comment]
> It seems I need to learn the CLI parameters all over again though.

Yep, many things might have changed, note that running the app without any cli parameter will spawn the launcher windows, which helps setting them and also saves them (in `~/.open-stage-control`)

**Comment by ovenwerks** [comment]
On Tue, 29 Nov 2016, jean-emmanuel wrote:

>       It seems I need to learn the CLI parameters all over again though.
> 
> Yep, many things might have changed, note that running the app without any cli
> parameter will spawn the launcher windows, which helps setting them and also
> saves them (in ~/.open-stage-control)

I noticed. I also tried downloading one of your premade deb packages for 
my laptop. (today - 32 bit) and that lancher never goes away when started 
from the system menu. The one I built from git has window decorations so I 
can hit the X, but the deb packaged one doesn't at least from the system 
menu. I think that window should close on it's own anyway when the main 
window goes away.

BTW it turns out my problem was not the cli parameters, but rather the 
push buttons have changed. I seem to have it figured out. false used to 
stop something from being sent on release, but now it sends #false :) you 
have added something to make it only active on press already.

I have not been able to test fine on Android yet...

--
Len Ovens
www.ovenwerks.net

**Comment by jean-emmanuel** [comment]
> I also tried downloading one of your premade deb packages for my laptop. (today - 32 bit) and that lancher never goes away when started from the system menu

Yep, this was fixed in master and will be included in next release (06c4becf07bc157fa1cd06a8415317184d528efc)

>  I seem to have it figured out. false used to stop something from being sent on release, but now it sends #false :)

Yeah, I thought it was not clear that way, as well as making not obvious how to send booleans over osc.

I tried to make the [changelog](https://github.com/jean-emmanuel/open-stage-control/blob/master/CHANGELOG.md) as complete as possible, it might be useful ;)
