### ISSUE TITLE
mathjs utility [discussion]

### ISSUE THREAD

**Issue by MartinHN** [jean-emmanuel/open-stage-control#384]
Hi again,
just a general question about scripting in o-s-c,
this is mainly because of the script object that use the same resolveprop than every other parameter...

why using mathjs over plain old eval in context ? (that could also be filled with mathjs functions)
using eval we could benefit a nicer js syntax. 

if its for a performance reason (i think security may not be a major issue here) i see two problems : 
 - accessing unwanted value, can put the app in a unstable state ->  i think we could pass a reduced context to avoid that

- speed : with some basic tests (attached below), my first impression is that mathjs is significantly slower than eval (~50x), even whith precompiled expression. although i'm very new to testing js code perfs

I know that modifying variables from script is not yet allowed (right?)
but if it where to come object modification could be lot cleaner.

[tstSpeed.zip](https://github.com/jean-emmanuel/open-stage-control/files/2476206/tstSpeed.zip)
unzip and npm i following archive to reproduce (keep devtools closed to avoid weird stalls)

**Comment by jean-emmanuel** [comment]
The main reason is that I have found no reliable way to do sandboxed eval in the browser. Test your `evalInContext`: as far as I can see, it doesn't prevent the eval'd code from accessing the global context and fails to mutate the provided context object. There might be a lead [here](https://github.com/browserify/vm-browserify) but last time I checked it wasn't doing the job.

**Comment by jean-emmanuel** [comment]
> I know that modifying variables from script is not yet allowed (right?)

Could you give an example please ?

**Comment by jean-emmanuel** [comment]
Although `eval` does perform much better than mathjs, it's worth noting that precompiliing the expression does make a difference (about 3x faster here): replacing `const expr = math.pase(exprToEval)` with `const expr = math.compile(exprToEval)` would be closer to the in-app usage.

**Comment by jean-emmanuel** [comment]
When the context's variables are used in the evaluated expression, results are much less conclusive, try the following:
```js
const context = {b:4}
const exprToMathEval = "a=2*b"
const exprToEval = "a=2*context.b"
const expr = math.compile(exprToMathEval)


function evalInContext() {
    //# Return the results of the in-line anonymous function we .call with the passed context
    return function() { return eval(exprToEval); }.call(context);
}

function testmath(){
    expr.eval(context)
}

function testeval(){
    eval(exprToEval)
}
```

**Comment by jean-emmanuel** [comment]
Also, filling the context with a hundred values appears to heavily affect mathjs parser's speed, but real use cases are unlikely to have more than a few variables (one per `@{}`/`OSC{}` call and previously declared variables within the same property).

**Comment by jean-emmanuel** [comment]
Yeah, writing plain js would be better if only it could be properly sandboxed... Until there is a way to do that, I see two solutions:
- some missing js native functions can be added to mathjs safely [here](https://github.com/jean-emmanuel/open-stage-control/blob/master/src/browser/js/app/widgets/utils.js#L79-L91), it doesn't seem affect the parser's performances
- pure js can be written in a [custom module](https://osc.ammd.net/extras/custom-module/)

Note that you can set a widget's value with the script widget, with the extra `set` function available in its scope (https://osc.ammd.net/widgets-reference/#script) 

What's really missing to mathjs is a proper if-else syntax (only ternary expressions currently) and loops, but I don't think it's planned (although it's been discussed already https://github.com/josdejong/mathjs/issues/518)

**Comment by jean-emmanuel** [comment]
This looks interesting ! 

> doing tests , again a simple expression is 2x faster in mathjs, but as soon as one context value is accessed or assigned, mathjs get much slower

You meant the opposite, right ? From what I saw, it's eval() that gets slower when accessing the context. 

> what is the context we need to pass, is a this from widget is sufficient, safe?

I think the context would be the same as for the #{} syntax, a very limited context with no direct access no widget instances, just @{} values and setters if executed in a script widget. 

> do we still authorize @{} to trigger auto script re-evaluation?
> we could wrap that in a new JS{} object to avoid overlaps with #{}

Absolutely, if we were to add something like this, I'd have it work exactly like mathjs but with a different syntax.

**Comment by jean-emmanuel** [comment]
I've come to the conclusion that the only acceptable compromise between security and performance is to run the code in an iframe sandbox, it's actually the trick used in the first link I posted above but for some reason I didn't manage to make it work at the time. Abstract-syntax-tree based solutions are the most elegant but they are way too slow compared to MathJs. Sounds like we'll have a JS syntax soon !

**Comment by jean-emmanuel** [comment]
`JS{{}}` is in git, it looks safe enough (no access to the app's context, no network requests), common involuntary infinite loops are automatically prevented, not much harm can be done besides crashing the app or breaking the parser. Now you can write 

```js
JS{{
console.log('Yeah')
return Math.PI
}}
```

**Comment by cyberic99** [comment]
@jean-emmanuel cool feature!

can it have one or several input variables?
or is it only evaluated at widget creation?

**Comment by jean-emmanuel** [comment]
It works exactly the same as mathjs formulas but with a different syntax.
