### ISSUE TITLE
startup screen does not allow not loading a session like "new"

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#39]
The startup screen defaults to last used session, this can be changed to another session but there is no option to use a blank unnamed session. Hmm, canceling session load seems to do that. Adding a new session button would be more intuitive.

Also, unless the session is cleared (with cancel in the file dialog) the example button being set to true does nothing. Setting example to true should reset last used session I think, but not be saved for next start. That is, when the session is started and one of the examples is chosen, the examples: true should be reset.

In both cases, once the user knows about these issues and how to deal with them, they don't matter. But for a new user it may be confusing.

**Comment by jean-emmanuel** [comment]
The launcher is really just a gui on top of the cli settings module, hence it's not impossible to set incoherent settings (I'll try to prevent/warn them though). The fact is, setting `--load` bypasses the client side app's lobby which lists recent sessions (or examples) and offers to create a new one. This should be documented indeed. 

> Adding a new session button would be more intuitive.

That would be an additional cli parameter, why not 

> Also, unless the session is cleared (with cancel in the file dialog)

You also have the little `x` buttons on the right to reset parameters.

**Comment by jean-emmanuel** [comment]
Just pushed some fixes to prevent setting incoherent cli switches (`--example + --load`, `--no-gui + --gui-only` for now)

**Comment by jean-emmanuel** [comment]
Pushed `-b / --blank` cli parameter to start editing a new session directly :)

**Comment by jean-emmanuel** [comment]
included in [v0.13.0](https://github.com/jean-emmanuel/open-stage-control/releases)
