### ISSUE TITLE
Building Issues

### ISSUE THREAD

**Issue by mrsstaceyseigle** [jean-emmanuel/open-stage-control#396]
Trying to build Open Stage Control on windows however have issues. 
I have installed Node and Git

When I use Git CMD and put in the commands provided, it seam to build and I have a dis directory. but when I run open stage control I get the error staging modules are missing. 
      cant find module  yarg  module js 485:15

When I use Git Bash and put in the commands provided, after build process complete there is no dis directory. 

How do we build on windows. 
![preview](https://user-images.githubusercontent.com/43449594/47257826-b5645300-d460-11e8-9861-307779ceead0.png)

**Comment by mrsstaceyseigle** [comment]
yes

**Comment by jean-emmanuel** [comment]
Could you tell me your versions of node and npm please ?

**Comment by mrsstaceyseigle** [comment]
Node  v8.12.0
npm   v6.4.1

**Comment by mrsstaceyseigle** [comment]
I have attached a video so that you can see what is going on. I have installed with
Node v4.8   then I tried with v8.12.0 and the current release v10    
I get the same issue. 
[Videos.zip](https://github.com/jean-emmanuel/open-stage-control/files/2498749/Videos.zip)

**Comment by jean-emmanuel** [comment]
Ok, the postinstall script fails because of a tiny command (`cp`) being different on windows (`copy`), I just updated the build scripts to fix that. You should be able to run `npm install` without error after running `git pull origin master`.
