### ISSUE TITLE
version 0.38 le midi ne fonctionne plus

### ISSUE THREAD

**Issue by guitmart** [jean-emmanuel/open-stage-control#397]
Bonjour Jean-Emmanuel,
Dans mon projet j'ai un custom module et une interface midi.
Si je fais la moindre référence au setting midi, l'app ne démarre pas.
Si je démarre la version 0.37.4 tout fonctionne normalement.

![capture](https://user-images.githubusercontent.com/28285097/47258941-e9e00b00-d470-11e8-8813-ac0159e59c76.PNG)

**Comment by jean-emmanuel** [comment]
Salut ! L'API du lanceur python a changée et je ne m'en suis pas rendu compte, je vais régler ça très vite. Merci

**Comment by guitmart** [comment]
super!
Merci.

**Comment by jean-emmanuel** [comment]
0.38.1 en cours d'upload. Il y a de gros changements dans les 0.38.*, ces versions sont encore en phase de test.
