### ISSUE TITLE
variables nesting regression

### ISSUE THREAD

**Issue by MartinHN** [jean-emmanuel/open-stage-control#398]
the current regex , don't seem to find nested variables 

when applying the current regex : `/@\{(?:[^{}]|(@\{[^{}]*\}))*\}/g `
to  @{@{parent.address}/state}
it don't seem to return nested @{parent.address}

do you see what could go wrong?

in my opinion, I find regex quite verbose (sometimes even unreadable) and sub optimal for the recursive case, shouldn't we switch to an other way of finding @{ 's? or using proper recursive regex implementations like XRegExp's matchRecursive?

**Comment by jean-emmanuel** [comment]
The regexp is working, but the mechanism was broken with the dynamic edition change, this fixes it 8a1c0da6 (but the limitation stated in the docs regarding nesting still stands).

**Comment by MartinHN** [comment]
thanks!

**Comment by jean-emmanuel** [comment]
I'm fixing it right now ;)

**Comment by MartinHN** [comment]
for now i got it working in a suboptimal way but a bit simpler

```
while(propValue.includes('@')){
            propValue = propValue.replace(/@\{[^{}]*\}/g, (m)=>{
// need to put back VARS if resolving @'s
                for(var n = 0 ; n < varnumber ; n++){
                    var varname = "VAR_"+n
                    m = m.replace(varname,variables[varname])
                }
...
}
```

**Comment by jean-emmanuel** [comment]
0a9929d0 makes it dynamic, yay !

**Comment by MartinHN** [comment]
just to be sure, can you check https://regex101.com/r/Ce3fB6/1?
I used the current regex and it doesn't return the math but no nested @{parent.variable} from the full expression @{@{parent.address}/state}. am I missing something?

**Comment by MartinHN** [comment]
on the link i gave switching to pcre gives the correct result, but we don't have this natively in chrome i think

**Comment by jean-emmanuel** [comment]
Oh sorry, I totally missed that, now it should be ok with 402ee329

**Comment by jean-emmanuel** [comment]
https://www.debuggex.com/r/m-BUPuzVTmuuRfkQ

**Comment by jean-emmanuel** [comment]
Oh my, I just realized it could be much simpler
