### ISSUE TITLE
OSC Message won't to be sending

### ISSUE THREAD

**Issue by baydam** [jean-emmanuel/open-stage-control#40]
Hi,
I love this software because it's fully customizable. But I am wondering why my OSC message wont to be send from this app to another. I've already try to intercept messages with oscdump but still not having feedback. Thank you so far

**Comment by jean-emmanuel** [comment]
Hi ! This might be a bug; can you give me more informations:

- open-stage-control version

- operating system

- session file (`.js` file)


Thanks for your feedback :)

**Comment by jean-emmanuel** [comment]
Any news regarding the issue ?
