### ISSUE TITLE
question sur le widget script

### ISSUE THREAD

**Issue by guitmart** [jean-emmanuel/open-stage-control#402]
Comment utiliser le widget script, je pense que sais la solution à mon problème, mais je n'arrive pas à le faire fonctionner. Est-ce qu'il y a un petit exemple?
Merci.

**Comment by guitmart** [comment]
Merci pour l'exemple, je vais voir si je peux réduire l'utilisation du customModule par le widget script

**Comment by jean-emmanuel** [comment]
ok cool !
