### ISSUE TITLE
Panels with a font-awesome label are not displaying correctly

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#409]
To repro, at commit 173d48352580:
- create a new panel
- set label to ``^PLAY`` or ``^COG``

The icon should be displayed in the tab, but instead I get:
``<I class="fa fa=fw fa=cog"></I>``

Thx!

**Comment by jean-emmanuel** [comment]
You might need to fully rebuild the app to get it working.

**Comment by jean-emmanuel** [comment]
Tab labels were broken though, fixed with 8d1e29ab

**Comment by jean-emmanuel** [comment]
There might other quircks like this one, don't hesitate to report them. It is worth the change, sessions are loading about 30% faster now :)

**Comment by cyberic99** [comment]
> There might other quircks like this one, don't hesitate to report them.
will do
> It is worth the change, sessions are loading about 30% faster now :)
👍🏻
