### ISSUE TITLE
Launch without X server

### ISSUE THREAD

**Issue by wargreen** [jean-emmanuel/open-stage-control#41]
Hi !
Is it possible to launch the server (no gui) without any X server ?
Or from an ssh session without need X forward ?

It seem just crash, and return "1".

Thanks a lot,
wargreen

**Comment by jean-emmanuel** [comment]
[Electron needs a display server to run](http://electron.atom.io/docs/tutorial/testing-on-headless-ci/), but a virtual one can do the trick. Install [https://en.wikipedia.org/wiki/Xvfb](xfvb) and do the following:
```
$ xfvb-run open-stage-control -n
```

**Comment by jean-emmanuel** [comment]
(reopening until docs are updated)
