### ISSUE TITLE
question: knob avec valeurs fixes

### ISSUE THREAD

**Issue by guitmart** [jean-emmanuel/open-stage-control#412]
Est-il possible d'utiliser un knob qui retourne des valeurs fixes comme 0, 3, 6, 9, 11, 14, 18...
Ma console tascam tm-d1000 fonctionne avec 100 steps de 0 à 127 et d'autres paramètres 25 steps de 0 à 127 etc.
Je me disais si on pouvait utiliser le range pour cela
ex:
[
      "min":{"step":0, "valeur":0},
      "1":{"step":1, "valeur":3},
      "2":{"step":2, "valeur":6},
...
      "max":{"step":100, "valeur":127}
]
et que le message midi envoyé ou osc soit    /control 1 7 valeur  ou /knob valeur on pourrait l'utiliser aussi avec des string
[
      "min":{"step":0, "valeur":"low"},
      "1":{"step":1, "valeur":"mid"},
...
      "max":{"step":100, "valeur":"high"}
]   /knob mid ...
On pourrait faire du mapping directement dans le widget au lieu de le faire dans un custom module.
Toujours très apprécier ton logiciel.
Merci martin.

**Comment by jean-emmanuel** [comment]
C'est déjà possible assez facilement en fait, essaye la session ci-jointe: [knob_mappedscale.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/2537765/knob_mappedscale.json.txt)

- le knob va entre 0 et 100
- l'input met la valeur sur une echelle de 0 à 25 avec une formule
- la valeur du knob remet celle de l'input sur sa propre échelle

il ne reste qu'à utiliser l'input au lieu du knob pour envoyer/recevoir les messages et le tour est joué.

**Comment by jean-emmanuel** [comment]
(exemple mis à jour)

**Comment by cyberic99** [comment]
il y a aussi moyen d'utiliser ``[0, 14, 26, 39, 64, 76, 89, 102, 114, 127][round(@{knob_value})]`` 
(voir l'exemple)

On met les valeurs dans un tableau et on prend la valeur a l'index correspondant à la position du knob.

[k.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/2540653/k.json.txt)

Par contre je ne sais pas s'il y a moyen que le knob avance plus par accoups, pour avancer de 1 en 1.

on peut changer la précision mais le mouvement est toujours ``smooth``

Sinon @jean-emmanuel j'ai essayé de mettre ca dans le range:
```
{
  "4": 4,
  "5": 5,
  "6": 6,
  "min": 0,
  "max": 9
}
``` 
Mais on ne peut mettre que des pourcentages, c'est ca?

**Comment by guitmart** [comment]
Le dernier exemple avec le tableau et mettre la precision à 0 pourrait faire l'affaire.
Je vais tester plus demain et merci pour l'exemple et oui les slider fonctionnent avec des pourcentages.

**Comment by jean-emmanuel** [comment]
> on peut changer la précision mais le mouvement est toujours smooth

Il y a peut être moyen de changer ça, à voir...


> Mais on ne peut mettre que des pourcentages, c'est ca?

oui

**Comment by jean-emmanuel** [comment]
Aller, nouvelle option `steps` pour les faders/knob

> Restricts the widget\'s value:
>- `auto`: use values defined in `range`
>- `number`: define a number of evenly spaced steps
>- `array`: use arbitrary values

**Comment by jean-emmanuel** [comment]
-> v0.39.4
