### ISSUE TITLE
Widget switch avec icones

### ISSUE THREAD

**Issue by jibestudio** [jean-emmanuel/open-stage-control#413]
Bonjour, 
D'abord bravo pour cette formidable application.
Lors de la mise à jour 0.39.0 (version Windows 64bits), mes widgets "switch" avec des icônes fontawesome avec dans le champ Values :
 {
  "^play": 1,
  "^pause": 2,
}
Ne s'affiche plus correctement. En revanche pour les boutons toggle ou push, l'affichage des icones est normal.
Faut-il changer de syntaxe pour les icones dans les switch ? Merci.

**Comment by jean-emmanuel** [comment]
v0.39.1 en cours d'upload

**Comment by jean-emmanuel** [comment]
```css
.input {
  font-size: 200%;
}
```

L'inspecteur (F12) peut aider à trouver le bon nom des classes des elements qu'on souhaite personnaliser ;)

**Comment by jibestudio** [comment]
Super merci, je n'y ai pas pensé et c'était pourtant écrit dans la doc !

Pour info dans la dernière release Windows x64, j'ai : "Theme error:
"alt-buttons" not found"

Bien cordialement,
