### ISSUE TITLE
tab selection broken

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#414]
Hello

At commit 4fad3d7c212594616ea086e4369ae457fd8e2f69, 

I cannot switch between tabs anymore by sending /TABS tab1 or /TABS tab2

It still works with /root 0 or /root 1

Tell me if you want me to do a git bisect

thx

**Comment by jean-emmanuel** [comment]
It's been broken before that with the rendering improvement patch. It's fixed in 0.39.3, note that the command used to trigger osc sendings, it doesn't anymore (to match the normal value setting behavior).
