### ISSUE TITLE
Container modal

### ISSUE THREAD

**Issue by jibestudio** [jean-emmanuel/open-stage-control#419]
Bonjour Jean-Emmanuel,
Dans la dernière release (0.39.4 win32x64), quand on crée un container "modal" et qu'on accède à la session sans GUI, via le navigateur Chrome, la fenêtre modal se trouve affichée en tout petit dans le bouton "modal".
En revanche il n'y a pas ce genre de souci d'affichage avec la GUI.

Par ailleurs, quand on coche "Fullscreen", je ne constate pas que le client (Chrome) se lance en plein écran par défaut. Peut-être faut-il faire quelque chose supplémentaire ?

Bien cordialement,
Jean-Baptiste

**Comment by jean-emmanuel** [comment]
Salut,

Peux tu préciser la version de chrome utilisée ?

Le mode fullscreen ne fonctionne que avec l'interface par défaut.

**Comment by jibestudio** [comment]
la dernière (Version 70.0.3538.77 (Build officiel) (64 bits)

Par ailleurs, j'ai cherché en vain à agrandir la taille des onglets et
de leur police mais je n'arrive pas à trouver la bonne classe.

Bonne soirée

**Comment by jean-emmanuel** [comment]
Merci, le bug n'apparait qu'à partir de la version 70 de chrome et est corrigé dans la v0.39.6.

Pour la taille de la police des tabs, il faut bien agir sur le css du widget parent (root pour les tabs principaux) :

```css
.tablink {
font-size:150%;
}
```

Pour augmenter la hauteurs des boutons:

```css
:host {
--nav-height: 50rem;
}
```

**Comment by jibestudio** [comment]
Oui je viens de voir la notification de mise à jour. C'est moi qui te
remercie de ta réactivité !;)

C'est l'appli que j'attendais pour faire des interfaces osc. On peut
vraiment les personnaliser comme on veut, même si je ne suis pas encore
très familiarisé avec le langage web.
J'avais commencé une interface avec Processing mais ça ne marchait pas
très bien sous Android. Avec OSC c'est parfait avec toutes les
tablettes. Prochaine étape : l'interface complètement responsive. J'ai
vu que c'était possible mais je vais y aller progressivement ;)
Je l'utilise avec Pure Data que je pratique depuis longtemps et ça
communique très bien sans planter. Le seul truc qui n'a pas l'air de
bien passer, c'est quand j'envoie de l'osc qui contient des accents de
Pd à OSC (pour des messages de rétroaction dans un widget text). Là les
accents sont remplacés par des signes cabalistiques. Un problème de
codage ASCII mais je ne sais pas trop à quel niveau ça se situe.

Encore merci pour ton super travail !
JB
