### ISSUE TITLE
Modal widget

### ISSUE THREAD

**Issue by jibestudio** [jean-emmanuel/open-stage-control#422]
Hello, il y a une regression dans la version 39.7 win32-x64. Le bug fixé dans la 39.6 de la fenêtre modale avec Chrome v70 est revenu.
Bien cordialement.
JB

**Comment by jean-emmanuel** [comment]
Peux tu envoyer une session où le bug se produit ? Le cas ne se présente pas chez moi (session vide avec un widget modal).

**Comment by jibestudio** [comment]
Et bien là, ça ne le fait plus. J'ai eu ça à partir d'une ancienne
session faite avec la 36.5 non sauvegardée. Désolé pour la fausse alerte.

**Comment by jean-emmanuel** [comment]
Pas de souci, n'hésite pas à réouvrir si le problème refait surface.

**Comment by jibestudio** [comment]
Bonjour Jean-Emmanuel,

Je me demandais à quoi et comment se servir du widget "script" ?
Est-ce que je pourrais éventuellement m'en servir pour faire des popup
textuel de rétroaction quand on appuie sur un bouton ?

Merci à toi,
Jean-Baptiste

**Comment by jean-emmanuel** [comment]
Salut, un petit exemple a été donné [ici](https://github.com/jean-emmanuel/open-stage-control/issues/402). Non, cela ne permet pas de faire ce que tu décris.

**Comment by jibestudio** [comment]
Ok, merci pour l'exemple.
Bonne soirée
