### ISSUE TITLE
Consume note played of keyboard in address

### ISSUE THREAD

**Issue by kdejaeger** [jean-emmanuel/open-stage-control#423]
I have an ''aftertouch' slider that needs to send a url as such: /vkb_midi/1/aftertouch/64 127
64 is the dynamic value here, the note played. That value I need to consume from the keyboard widget, how can I do that?
I tried setting the url to /vkb_midi/1/aftertouch/@{the_keyboard}

**Comment by jean-emmanuel** [comment]
Matrices are a bit inconsistent here, it needs some work. I the mean time you should be able to do that with a custom module.

**Comment by kdejaeger** [comment]
Cool, looking forward to it.

**Comment by jean-emmanuel** [comment]
In next release you'll be able to do what you want by setting your slider's address to 
```
#{
key = indexOf(@{the_keyboard}, @{the_keyboard.on}) + @{the_keyboard.start}
}
/vkb_midi/1/aftertouch/#{key}
```

**Comment by jean-emmanuel** [comment]
A different approach: create a script widget that sends the aftertouch whener the keyboard or the slider updates.

**value** (subscribe to slider & keyboard)
```
@{aftertouch} / @{the_keyboard}
```

**script**
```
#{

key = indexOf(@{the_keyboard}, @{the_keyboard.on}) + @{the_keyboard.start};
aftertouch = @{aftertouch};
address = concat('/vkb_midi/1/aftertouch/', key);

key != -1 ? send(false, address, aftertouch) : "";

}
```

**Comment by jean-emmanuel** [comment]
v0.40.0 is out, above tricks work now

**Comment by kdejaeger** [comment]
I tried the second trick as well. No errors but no OSC messages seem to be send. This is the script's JSON:

`                        {
                          "type": "script",
                          "id": "script_aftertouch",
                          "linkId": "",
                          "height": "auto",
                          "label": "auto",
                          "color": "auto",
                          "css": "",
                          "condition": 1,
                          "script": "#{\nkey = indexOf(@{the_keyboard}, @{the_keyboard.on}) + @{the_keyboard.start};\naftertouch = @{aftertouch};\naddress = concat('/vkb_midi/1/aftertouch/', string(key));\nkey != @{the_keyboard.start} - 1 ? send(false, address, aftertouch) : \"\";\n}",
                          "default": "",
                          "value": "",
                          "precision": 2,
                          "address": "auto",
                          "preArgs": "",
                          "target": "",
                          "bypass": false
                        }
`

**Comment by jean-emmanuel** [comment]
I forgot to tell you the 2nd examples assumes you have set the scripts `target` property.

**Comment by kdejaeger** [comment]
Ow I seem to have forgotten to set the script's value to ''@{aftertouch} / @{the_keyboard}''

**Comment by kdejaeger** [comment]
Can you check if it still need documentation or examples?

**Comment by jean-emmanuel** [comment]
What do you mean ?

**Comment by kdejaeger** [comment]
I mean it wasn't clear from the documentation that the script's component value property had to be filled in in order to subscribe. In this case with '@{aftertouch} / @{the_keyboard'.

**Comment by jean-emmanuel** [comment]
Done, thanks

**Comment by kdejaeger** [comment]
After reading this new documentation, I am doubting if I am using it correctly. I don't understand the whole slash character between @{aftertouch} and @{the_keyboard}.

So the json is as follows now:

                        {
                          "type": "script",
                          "id": "script_aftertouch",
                          "linkId": "",
                          "height": "auto",
                          "label": "auto",
                          "color": "auto",
                          "css": "",
                          "condition": 1,
                          "script": "#{\nkey = indexOf(@{the_keyboard}, @{the_keyboard.on}) + @{the_keyboard.start};\naftertouch = @{aftertouch};\naddress = concat('/vkb_midi/1/aftertouch/', string(key));\nkey != @{the_keyboard.start} - 1 ? send(false, address, aftertouch) : \"\";\n}",
                          "default": "",
                          "value": "@{aftertouch} / @{the_keyboard}",
                          "precision": 2,
                          "address": "/script_aftertouch",
                          "preArgs": "",
                          "target": "",
                          "bypass": false
                        }

Do you mean that the value property is actually 'misused' in a way so that the script compontent listens to it? I guess then @{aftertouch} * @{the_keyboard} would have worked as well then?

**Comment by jean-emmanuel** [comment]
Yes, the slash doesn't make sense here, all we are interested in here is to trigger a value change everytime of the two widgets changes.

**Comment by jean-emmanuel** [comment]
It'd cleaner to put it this way:

**value**
```
[ @{aftertouch}, @{the_keyboard}]
```

**script**
```
#{

key = indexOf(value[0], @{the_keyboard.on}) + @{the_keyboard.start};
aftertouch = value[1];
address = concat('/vkb_midi/1/aftertouch/', string(key));

key != @{the_keyboard.start} - 1 ? send(false, address, aftertouch) : "";

}
```

**Comment by jean-emmanuel** [comment]
(Above example edited)
