### ISSUE TITLE
custom font handling

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#424]
Hello

I am using a custom font in o-s-c

I can install it system wide, and it works

I'd like to be able to put the ttf file in the same folder as the theme file.

So I did:
```
@font-face {
    font-family:"My Font";
    src: url("MyFint.ttf")
}
```
And o-s-c told me that it searches for the fonts in app/assets

I copied the font there, and it works

But is there a way to look for the fonts in a custom folder, or in the same folder as the theme file?

thx

**Comment by jean-emmanuel** [comment]
You have to use an absolute path if you need to use a custom directory.
