### ISSUE TITLE
Feature: fader meter visual appearance

### ISSUE THREAD

**Issue by manfred-mp** [jean-emmanuel/open-stage-control#429]
This is great tool and has a lot of potential - thanks! Currently using it with Ardour and trying to implement X Air support. 

Then a request. As current state it is hard to see the actual level of meter (fader embedded) and would be nice to have bright color ranges as seen here: [CSS audio meter](https://codepen.io/brancep/pen/EKzBmw)

**Comment by jean-emmanuel** [comment]
The embeded faders are quite basic, but you can do what you need with regular meters using the `gradient` property and adjusting the opacity with the css variable `--gauge-opacity`:

- css: `--gauge-opacity: 1;`
- gradient: `["green", "yellow"]`

Not that the gradient property was broken until just now... you can try it in the online demo, a patch release on the way.

**Comment by jean-emmanuel** [comment]
Load the attached session to see the above example in action. 
[bright-meter.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/2579937/bright-meter.json.txt)

**Comment by manfred-mp** [comment]
That was quick - cool! Only way I figured to have own adjusted ranges was like this ["green", "green", "green", "yellow", "red", "red"]. Is there more accurate way? Anyway this already helped a lot, thx.

**Comment by cyberic99** [comment]
@jean-emmanuel is it possible to apply css animations to a fader or a meter? I see they are drawn using a canvas some I don't think it is possible...

thx

**Comment by jean-emmanuel** [comment]
It's not currently possible to animate a slider between 2 values. While not impossible to implement, I don't think it's worth adding a layer of computation to display intermediate values that are not representing the actual state of the app.

**Comment by jean-emmanuel** [comment]
Gradient can now be set as an object to define custom color scales: `{"0": "blue", "0.28": "red", "1": "yellow"}

**Comment by cyberic99** [comment]
> I don't think it's worth adding a layer of computation to display intermediate values that are not representing the actual state of the app.

I agree with you

I thought it was doable in css, where the css would interpolate the steps between the current value and the target value

But I guess it is not doable with canvas...

The ``CSS audio meter`` example uses DIVs to draw he meters.

Is there already a widget like that in o-s-c?

**Comment by jean-emmanuel** [comment]
You might get somewhere with the svg widget, this one doesn't rely on canvas.

**Comment by jean-emmanuel** [comment]
Closigin since the initial issue has been addressed in v0.40.0

**Comment by jean-emmanuel** [comment]
Check out attached session file with v0.40.1 (includes a fix for svg), here you have an animated meter made of svg magic.

[svg_transition.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/2599747/svg_transition.json.txt)

**Comment by cyberic99** [comment]
wow you rock @jean-emmanuel , thx! 
I'll post my final results too
