### ISSUE TITLE
[Feature] Use parent's ID in osc adress

### ISSUE THREAD

**Issue by wargreen** [jean-emmanuel/open-stage-control#43]
hi !
Is there a way to use the widget ID or the parent's ID in the osc adress ?
Use case : a slider in a Strip named "MyTrack" send "/strip/MyTrack/Gain"

Thanks !

**Comment by jean-emmanuel** [comment]
Nope, the osc address must be manually set ;)

**Comment by ovenwerks** [comment]
Just a comment, what would one gain from using the ID? Doesn't that have to be manually set as well?

**Comment by jean-emmanuel** [comment]
Well I guess would allow some kind of property inheritance between containers and widgets, unfortunately this is not possible currently and it's probably not going to be anytime soon ;)

**Comment by wargreen** [comment]
This can be realy usefull for fast tracks controlers .
You can build one DAW track, an just copy this one and change the container ID for other tracks.
