### ISSUE TITLE
QUESTION: avoir accès à un indexof

### ISSUE THREAD

**Issue by guitmart** [jean-emmanuel/open-stage-control#431]
Bonjour Jean-Emmanuel et merci pour la propriété steps.
J'aimerais savoir si il y a un moyen de faire un indexof sur un array. Je n'ai pas trouvé cette fonctionnalité dans math.js et je n'ai pas accès au indexof natif du javascript.
Merci.

**Comment by jean-emmanuel** [comment]
Yes, ça manquait, c'est dans git.

**Comment by guitmart** [comment]
super merci

Le jeu. 15 nov. 2018 à 01:40, jean-emmanuel <notifications@github.com> a
écrit :

**Comment by guitmart** [comment]
super merci

**Comment by jean-emmanuel** [comment]
-> v0.40.0
