### ISSUE TITLE
How to update/modify props in matrix widget

### ISSUE THREAD

**Issue by akobelan** [jean-emmanuel/open-stage-control#433]
Just when I think I've figured this out ... Can someone provide an example of how I'd send an OSC message (/EDIT, or otherwise) to set/change the "props" of a matrix widget.

Specifically, I'm trying to dynamically change the widget labels. Ideally, any one, and not necessarily all
at the same time.

**Comment by cyberic99** [comment]
Is this exemple useful?

https://github.com/jean-emmanuel/open-stage-control/issues/152#issuecomment-367259026

**Comment by jean-emmanuel** [comment]
> . Ideally, any one, and not necessarily all at the same time.

I had missed that part. You can edit a subwidget from the matrix without editing the matrix itself by targetting the id `matrix_id/i` with the `/EDIT` command, where `i` is the subwidget's index plus the matrix' `start` property. However, any edition on the matrix' `props` will erase these modifications.

**Comment by jean-emmanuel** [comment]
If you need a persistent solution, you can store the labels in some container's `variables` property, consumpe it in the matrixs `props` and edit it with /EDIT/MERGE:

**variables** (parent container)
```js
{
  labels: {
    "0": "Label 0",
    "1": "Label 1",
    "2": "Label 2"
  }
}
```

**props**
```js
{
  label: "#{@{parent.variables}.labels[string($)]}"
}
```

`/EDIT/MERGE parentId {variables: {label: {"1": "New label 1"}}}`

**Comment by akobelan** [comment]
Thanks for the `OSC{}` syntax tip. This software is really rich in scope. Just when you feel there is something you need or there is a feature that is missing, re-reading the documentation reveals something really useful, but subtle the first time you read it.

The `OSC{}` syntax marries well with Node-Red. _Read the documentation!_

Thanks!

**Comment by jean-emmanuel** [comment]
Haha, I must admit the docs could be more self-explanatory, that's really the hardest part... 

I'm closing the issue, feel free to reopen.
