### ISSUE TITLE
Error with option --no-gui

### ISSUE THREAD

**Issue by kdejaeger** [jean-emmanuel/open-stage-control#435]
"C:\Program Files\open-stage-control-win32-x64\open-stage-control.exe" --port 9090 --send 127.0.0.1:8000 --osc-port 9000 --theme orange alt-buttons responsive-fonts --load C:\\Users\\koen\\IdeaProjects\\open-stage-control-bitwig\\open_stage_control_bitwig.json --no-gui --fullscreen

Gives error 'no option gui'

**Comment by jean-emmanuel** [comment]
Are you using prebuilt binaries ?

**Comment by jean-emmanuel** [comment]
I mean `npm install` and `npm run build`

**Comment by kdejaeger** [comment]
Prebuild yes, the windows zip file from the github releases.

**Comment by jean-emmanuel** [comment]
Ok, it only happens when not running the app from the executable's folder. I've found a workaround, it'll be included in next release.

**Comment by jean-emmanuel** [comment]
Hmm, not that simple, I've reported the bug upstream https://github.com/yargs/yargs/issues/1248

**Comment by jean-emmanuel** [comment]
Fixed in git
