### ISSUE TITLE
Feature: timer widget

### ISSUE THREAD

**Issue by manfred-mp** [jean-emmanuel/open-stage-control#437]
At least in some cases we need a keep alive type of message to prevent other end to disconnect. With timer that would be easy to overcome. There must be a lot of use cases where timer would be handy. 

Just for consideration.  And others please comment any possible use cases.

Some suggestion for options:
- single / repeat
- null args
- hidden

**Comment by cyberic99** [comment]
I think it would be useful too

A bit like a script widget, but auto triggered

**Comment by jean-emmanuel** [comment]
It's a feature request I have rejected a few time in the past already, I'll think about it again but it's not a priority yet.

**Comment by jean-emmanuel** [comment]
I'm deciding against this once more, it should be handled from the server (custom module). Here is a simple example that prints elapsed time since session loading and allows resetting the timer.

[timer.zip](https://github.com/jean-emmanuel/open-stage-control/files/2909625/timer.zip)
