### ISSUE TITLE
Feature request: OSC default behaviour

### ISSUE THREAD

**Issue by akobelan** [jean-emmanuel/open-stage-control#438]
I propose to extend the syntax definition of the `OSC{}` construct. When specifying the "/address" a leading "/" should imply an absolute `OSC` target. An address that is specified without a leading "/" should be with respect to the widget's address that the `OSC{}` appears in. 

This would be useful in the event that one is making wholesale changes to the OSC naming space. I know one workaround is to use extended variables. My proposal would make for cleaner syntax. 

e.g.

Widget OSC Address: "_/banana_"

`OSC{destination_address} `is a listener on `/banana/destination_address`, where the widget OSC address `/banana`  prefixes the `destination_address`.

**Comment by jean-emmanuel** [comment]
Interesting, I'll dig the idea.

**Comment by jean-emmanuel** [comment]
It's in git now !
