### ISSUE TITLE
[Feature][multiXY] Name points and use the name in the osc address

### ISSUE THREAD

**Issue by wargreen** [jean-emmanuel/open-stage-control#44]
Hi !
It will be very usefull if we can name the points of a multiXY widget, and use the name in the osc  address.

**Comment by jean-emmanuel** [comment]
Yo !

- c9daa7dc8374183266dc2d17b0215776b775f063 adds support for naming points by setting `points` to an `array ` of labels
- setting `split` to `true``will use the these in the osc addresses (as address suffixes)
- it is also possible to define each address manually by writting the `split` option as an `array` of addresses

See [mutlixy docs](http://osc.ammd.net/user-guide/widgets-specifics/pads/#multixy)

**Comment by jean-emmanuel** [comment]
(docs are now up to date)
