### ISSUE TITLE
Question: Store a variable for each client?

### ISSUE THREAD

**Issue by ShadowOfThePenguin** [jean-emmanuel/open-stage-control#441]
I am using this to control a lighting console and a really love how easy it is to work with. There is one feature I am really struggling with. 

I would love to be able to have each of my clients recognized as a different "user" by the board. The board expects the OSC command to be something like "/eos/user/{user number}/key/clear_cmd". So I would like each client to be able to insert its own user number.

I did have it working universally using a dropdown menu of user numbers and then calling it "/eos/user/@{user.value}/key/clear_cmd". And that worked great except all the clients had the same user number, even though that number could change.

Next I tried removing the OSC sync from the drop down menu, then one client would work, but others would send "undefined" as their user number. 

Most recently I have been playing around with the app event listener, but since I am only a novice programmer, I can't seem to get that to work or find simple enough documentation for me to get it set up.

Any help figuring out how to do this would be greatly appreciated.

**Comment by jean-emmanuel** [comment]
> Next I tried removing the OSC sync from the drop down menu, then one client would work, but others would send "undefined" as their user number.

Setting the dropdown `bypass` property to true should do the trick, you might also have to specify a default value to avoid the undefined user number. This seems the best solution so far.

**Comment by ShadowOfThePenguin** [comment]
I did have a default value of 1 when I set it to bypass. 

I seem to have it working now. I once again bypassed the OSC and then did value: @self.value and it is working now. 

Thanks for your help.
