### ISSUE TITLE
Question: Remote Control /EDIT function

### ISSUE THREAD

**Issue by ianm55** [jean-emmanuel/open-stage-control#442]
HI there,

I'm wanting to change the value of a widget's "Value", and it's not quite clear what my command would be for it. For this specific widget in the image below, I'm wanting to send both what's already there, and also want to send a message to change it to @{freedom_intensity._value} . Does anyone know what the message I would need to send would be? Thanks.

![screen shot 2018-11-28 at 5 36 01 pm](https://user-images.githubusercontent.com/42524426/49191522-1b7fa800-f334-11e8-8479-52a7ce7fa4d6.png)

**Comment by jean-emmanuel** [comment]
I'm not sure to fully understand your question. Here's what you need to send to change the value property from `@{master_intensity._value}` to `@{freedom_intensity._value}`:
```
/EDIT widget_id '{value: "@{freedom_intensity._value}"}'
```

Note that the underscore before `value` has been deprecated for a very long time, it's not documented anymore and is likely to stop working someday.

**Comment by ianm55** [comment]
> I'm not sure to fully understand your question. Here's what you need to send to change the value property from `@{master_intensity._value}` to `@{freedom_intensity._value}`:
> 
> ```
> /EDIT widget_id '{value: "@{freedom_intensity._value}"}'
> ```
> Note that the underscore before `value` has been deprecated for a very long time, it's not documented anymore and is likely to stop working someday.

**Comment by jean-emmanuel** [comment]
it is still supposed to be opened ?
