### ISSUE TITLE
Setting matrix labels and values effeciently

### ISSUE THREAD

**Issue by Alzy** [jean-emmanuel/open-stage-control#444]
I'm currently building a custom Ableton OSC controller to control the Session view using a Matrix component. I can already move up and down along the session view while updating the 4x4 matrix's labels on open stage control using /EDIT on props on every scroll. The problem I'm now having is that I can't seem to update the button states on open stage control whenever a new clip is launched.

For example, in Ableton Live, whenever you launch a clip within a column (track), any other clips in that column will have to stop. I already have ableton set up to send over an array of 16 button states as OSC messages to open stage control. The thing is, I don't know what to do from here. sending /EDIT on props doesn't do anything to the values of the buttons if they have already been pressed by the user.. What is an efficient way to accomplish this?

**EDIT**: Just to be a little more clear, I am trying to silently set the button's value without it sending out an OSC message as if it was pressed by the user.

**Comment by jean-emmanuel** [comment]
The most straightforward way to set the buttons' values is to send one message per button to OSC : `/button/address/x value`
This won't make OSC send any message.

**Comment by jean-emmanuel** [comment]
I'm closing the issue, feel free to reopen if you need more help.
