### ISSUE TITLE
switch to another tab by pressing a button, but only this client

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#445]
Hello @jean-emmanuel I hope you are doing well, as o-s-c development is kind of slow nowadays ;-)

I tried to find a way to switch to another tab, by pressing a button

I got it working by making a push with these properties:

address: /TABS
preArgs: [ "tab_title" ]
target: [ "self" ]

It works, but I'd like to switch only on the client that pressed the button...

I have tried to enable 'bypass', but then, the push has no action at all...

Thx

**Comment by jean-emmanuel** [comment]
Cool !
Well I guess it only only _seems_ stable because less bugs have been found recently ;)
