### ISSUE TITLE
Bug on reordering strips widget

### ISSUE THREAD

**Issue by MartinHN** [jean-emmanuel/open-stage-control#448]
Hi,

i noticed that if one move a widget to more than one element further in strip ordering list, widgets on the way are not rebuilt correctly (I think the same bug happens in tabs).
the widget originally moved and the one it replace gets correctly updated but the other in between don't

details : 
the strip ordering list shows the correct order but the visible widgets are not updated.
editor panels show correct properties of the non rebuilt widgets, so fake editing the id to recreate the correct widget.

**Comment by jean-emmanuel** [comment]
Thanks, the "children reuse" algorythm is flawed here, I'll have a look at it soon.

**Comment by jean-emmanuel** [comment]
Fixed in git
