### ISSUE TITLE
Feature request : client can save to current opened session in server side

### ISSUE THREAD

**Issue by MartinHN** [jean-emmanuel/open-stage-control#451]
Hi, I know these are global consideration you already have on session management, but as a first step I think to add the ability to save current opened session, on the remote side could be really useful  : 

use case 1  : (on mac afaik) triggering save currently act as a Save As, so we need to re specify  the name of the session each time

use case 2 : on remote server (e.g raspberry pi running headless server) we need to manually sync the files (download , rename then send..)

I'm not sure how complicated it would be , but I'm sure it could be useful!

let me know if i can help in any way

[edit]
when I say "a first step" I'm referring to ignore for now a full blown remote file system handler (browsing saving, etc..) that is far more complex I presume

**Comment by MartinHN** [comment]
if security is concerned, may be a setting allowing or not clients to be able to save on the server (a global boolean or an ip list)

**Comment by jean-emmanuel** [comment]
included in v0.41.0

**Comment by jean-emmanuel** [comment]
I've finally implemented a simple but decent remote file browser, it's in git.
