### ISSUE TITLE
BUG : app crashes if no HOME environment set

### ISSUE THREAD

**Issue by MartinHN** [jean-emmanuel/open-stage-control#453]
Hi,
it's a kind of corner case scenario, but worth to mention it I think
when launching o-s-c without HOME environement variable set, the server crashes when trying to build the settings path : https://github.com/jean-emmanuel/open-stage-control/blob/6f79c91ba35364b2b6e247357237687ea3ba95a3/src/server/settings.js#L5 

(baseDir is undefined)

can we either : 
- document this somewhere (almost done by posting this issue...)
 - notify a clear error if no HOME environment variable is found?
- use a temporary empty file ( and so disabling permanent settings functionnality)
- find an other workaround

my use case : i'm launching o-s-c (headless node version) in the boot process of raspberry py (in rclocal) so HOME is not defined here
in my case, the obvious workaround is to prepend ```HOME=/home/pi```  to the command ```node openstagecontrol ...``` 

it's not a critical bug but can be hard to track down

cheers and thanks again for the amazing support!!

Martin

**Comment by jean-emmanuel** [comment]
Thanks for reporting this, I've retained the 3rd option (warning + no permanent settings), can you test it ?

**Comment by MartinHN** [comment]
working!!
 ```/home/pi/Documents/openFrameworks/apps/anima/script/../openstagecontrol/anima.json
Home directory not found, settings and session history will not be saved.
Running with node
