### ISSUE TITLE
How do I use another language in text box

### ISSUE THREAD

**Issue by juninjune** [jean-emmanuel/open-stage-control#455]
Hi, I'm using open-stage-control in Korea.
and when I send some information to openstagecontrol in Korean, it shows broken words.
How can I use Korean in text box?

**Comment by jean-emmanuel** [comment]
Hi, the osc spec requires ascii strings, hence your issue. I just pushed a change that encodes/decodes utf8 strings, it seems to be the way other libraries (eg liblo) deal with this problem. Depending on how you send messages to open-stage-control, you might need to ensure your strings are properly encoded (see https://encoding.spec.whatwg.org/#utf-8).

**Comment by jean-emmanuel** [comment]
Included in v0.41.3
