### ISSUE TITLE
[Feature] mutlixy: separate touch states, independent split addresses.

### ISSUE THREAD

**Issue by PLu55** [jean-emmanuel/open-stage-control#457]
In multixy I like to get a message when clicking on a point without moving it. The message should contain information about which point that was clicked (and maybe its coordinated). It can maybe be a mode where a message is sent on the first click (without moving the point). The message should be distinct from the normal possition messages.

This will give the possibility to delete specific points and also manipulating of the content the points are representing. I use the multixy as an interface to multi-point interpolation. Now I have to move the point to detect which point to delete or edit, not a very nice solution.

It would also be nice if there would be a mode where the coordinates only of the point that is moving but not spitted into separate messages for x and y. I often have many points and I'm only interested in the point that is moving but is getting info an all points for every movement, this generated quite a bit of overhead. Split mode is not really an option as it can be problems of tracking which messages belongs together.

**Comment by jean-emmanuel** [comment]
I'll dig the idea, thanks for your feedback !

**Comment by jean-emmanuel** [comment]
In upcoming v1, the `split` property has been removed (message routing is to be handled with a script or a custom module now), and `touchAddress` generates different messages for each point touched.

**Comment by dewiweb** [comment]
I want to send xy coordinates of  points using  their names defined in multixy "points" box 
["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]
osc messages formatted like this: /track/nameOfThePoint/xyz
How can I script it?

**Comment by jean-emmanuel** [comment]
Something like this:
```js
var points = getProp('this', 'points')
for (var i in points) {
  send('/track/' +  points[i], value[i * 2], value[i * 2 + 1])
}
```

(please use the [forum](https://openstagecontrol.discourse.group/) for usage questions)

**Comment by dewiweb** [comment]
Thanks, it works! But it sends each time coordinates of all points, not only the updated one! Is there a solution to send coordinates of updated point only?

**Comment by jean-emmanuel** [comment]
This would do, with `target` left empty to avoid the default osc messages
```js
var points = getProp('this', 'points')

for (var i in points) {

  locals[i] = locals[i] || []
  var x = value[i * 2],
      y = value[i * 2 + 1]

  if (locals[i][0] !== x || locals[i][1] !== y) {
    send('127.0.0.1:4444', '/track/' +  points[i], x, y)
    locals[i] = [x, y]
  }
}
```

**Comment by dewiweb** [comment]
Cool, I'm not really familiar with custom modules but this works like a charm!
Thanks.
