### ISSUE TITLE
Changement dans les éléments Keys ?

### ISSUE THREAD

**Issue by nlebellier** [jean-emmanuel/open-stage-control#460]
Bonjour,

Je me relance sur un projet basé sur open-stage-control. J'ai donc téléchargé la toute dernière version 0.41.4 et mon interface intégrant des keys ne marche plus. Si j'ai bien compris le lien avec la valeur du widget à contrôler ne se fait plus par le champ  "widgetId" comme c'était le cas dans les anciennes versions... 
```

  "widgets": [
                    {
                        "type": "keys",
                        "top": 420,
                        "left": 100,
                        "id": "keys_1",
                        "width": "auto",
                        "height": "auto",
                        "label": "auto",
                        "color": "auto",
                        "css": "",
                        "binding": [
                            "r",
                            "f"
                        ],
                        "keydown": "# this is a comment\nx = key == \"r\" ?  0.1 : -0.1;\nvalue + x",
                        "repeat": true,
                        "widgetId": "fader_1",
                        "keyup": "",
                        "linkId": ""
                    },
                    {
                        "type": "fader",
                        "top": 60,
                        "left": 100,
                        "id": "fader_1",
                        "linkId": "",
                        "width": "auto",
                        "height": "auto",
                        "label": "auto",
                        "color": "auto",
                        "css": "",
                        "horizontal": false,
                        "alignRight": false,
                        "pips": true,
                        "input": true,
                        "meter": false,
                        "compact": false,
                        "dashed": false,
                        "snap": false,
                        "spring": false,
                        "doubleTap": true,
                        "range": {
                            "min": 0,
                            "max": 1
                        },
                        "logScale": false,
                        "unit": "",
                        "origin": "auto",
                        "value": "",
                        "precision": 2,
                        "address": "/fader_1",
                        "touchAddress": "",
                        "meterAddress": "",
                        "preArgs": [],
                        "target": [],
                        "default": "",
                        "bypass": false
                    },
```
Deux remarques :
- il faut absolument indiqué dans son fichier json avec quelle version open-stage-control cela fonctionne et garder la dite-version sous le coude.
- j'ai regardé la doc [keys](https://osc.ammd.net/widgets-reference/#keys), pas trouvé d'informations...
- j'ai vu le champ LinkId est-ce la bonne piste ? J'ai tenté un >> fader_1 mais nada...
![image](https://user-images.githubusercontent.com/4880966/51799130-dab1eb80-221d-11e9-91f0-358ba4122d01.png)

Merci pour une éventuelle réponse.

**Comment by jean-emmanuel** [comment]
Salut, c'est un changement qui a été documenté, il faut absolument lire le changelog dans le détail quand on met à jour depuis un très vieille version, c'est un peu touffu mais malheusement le seul moyen d'éviter ce genre de souci, open-stage-control a beaucoup évolué en 6 mois : https://github.com/jean-emmanuel/open-stage-control/blob/master/CHANGELOG.md#0360
En l'occurrence il faut mettre `@{keys_1}` dans la propriété `value` du widget à controller.

> Il faut absolument indiquer dans son fichier json avec quelle version open-stage-control cela fonctionne et garder la dite-version sous le coude.

Bonne idée !

**Comment by nlebellier** [comment]
Merci pour cette réponse ultra rapide ! Bon ok je n'ai pas été assez assidu :+1: 

Cela ne marche pas mieux mais cela doit venir de la formule qui n'est plus de la bonne forme...
`formulas in keydown and keyup must be explicitely written using the #{} syntax`

Bon on trouve où les infos sur la syntaxe #{}... pour remplacer 
``
                        "keydown": "# this is a comment\nx = key == \"r\" ?  0.1 : -0.1;\nvalue + x",
``
Encore merci !

**Comment by nlebellier** [comment]
ok j'ai modifié la formule et ça ne veut toujours pas fonctionner.

```
{
  "type": "root",
  "tabs": [
    {
      "type": "tab",
      "id": "Sonic Pi controller",
      "label": "auto",
      "color": "auto",
      "css": "",
      "value": "",
      "precision": 0,
      "address": "/tab_1",
      "preArgs": [],
      "target": [],
      "variables": "@{parent.variables}",
      "widgets": [
        {
          "type": "keys",
          "top": 370,
          "left": 100,
          "id": "keys_1",
          "width": "auto",
          "height": "auto",
          "label": "auto",
          "color": "auto",
          "css": "",
          "binding": [
            "r",
            "f"
          ],
          "keydown": "#{ x = key == \"r\" ?  0.1 : -0.1; \nvalue + x }",
          "repeat": true,
          "keyup": "",
          "linkId": "",
          "default": "",
          "value": "",
          "precision": 2,
          "address": "/keys_1",
          "preArgs": "",
          "target": "",
          "bypass": false
        },
        {
          "type": "fader",
          "top": 60,
          "left": 100,
          "id": "fader_1",
          "linkId": "",
          "width": "auto",
          "height": "auto",
          "label": "FADER_1",
          "color": "auto",
          "css": "",
          "horizontal": false,
          "alignRight": false,
          "pips": true,
          "input": true,
          "meter": false,
          "compact": false,
          "dashed": false,
          "snap": false,
          "spring": false,
          "doubleTap": true,
          "range": {
            "min": 0,
            "max": 1
          },
          "logScale": false,
          "unit": "",
          "origin": "auto",
          "value": "@{keys_1}",
          "precision": 2,
          "address": "/fader_1",
          "touchAddress": "",
          "meterAddress": "",
          "preArgs": [],
          "target": [],
          "default": "",
          "bypass": false,
          "steps": ""
        },
        {
          "type": "push",
          "top": 0,
          "left": 100,
          "id": "push_1",
          "linkId": "",
          "width": "auto",
          "height": "auto",
          "label": "auto",
          "color": "auto",
          "css": "",
          "on": 1,
          "off": 0,
          "norelease": false,
          "precision": 2,
          "address": "/1/push_1",
          "preArgs": [],
          "target": [],
          "bypass": false,
          "doubleTap": false
        }
      ],
      "tabs": [],
      "linkId": "",
      "default": "",
      "bypass": false,
      "scroll": true
    }
  ],
  "color": "auto",
  "css": "",
  "value": "",
  "precision": 0,
  "address": "/root",
  "preArgs": [],
  "target": [],
  "variables": {},
  "id": "root",
  "linkId": "",
  "default": "",
  "bypass": false,
  "traversing": false,
  "scroll": true,
  "label": false
}
```

**Comment by jean-emmanuel** [comment]
Je n'avais pas fait bien attention:
> variable value got removed from these formulas context;

donc: `#{# this is a comment\nx = key == \"r\" ? 0.1 : -0.1;\n@{fader_1} + x}`

**Comment by jean-emmanuel** [comment]
Au fait, la session d'exemple (keys.json) avait été mise à jour et fonctionne avec le linkId : http://openstagecontrol.herokuapp.com/

**Comment by nlebellier** [comment]
Bon et bien grand merci ça fonctionne du tonnerre de dieu :+1:  et effectivement j'ai le "droit" d'aller faire un tour sur les démos avant de te contacter. 

En passant, si on met des steps pour le fader, j'ai mis 11 steps, le scroll de souris augmente la valeur de  0.01 à chaque scroll vers le haut. Peut-on avoir le comportement suivant : chaque scroll passe de valeur de step à l'autre valeur de step ?

**Comment by jean-emmanuel** [comment]
Pas de souci, je mettais le lien surtout pour l'usage du linkId possible dans ce cas là.

> . Peut-on avoir le comportement suivant : chaque scroll passe de valeur de step à l'autre valeur de step 

Ça semble assez logique, je vais ajouter ça bientôt.

> Et idem pour les touches peut-on calculer du coup la valeur du pas en récupérant la valeur fixée à step ?

Tu peut le calculer dans ta formule:

```
#{
range = @{fader_1.range}; 
step = (range.max - range.min) / (@{fader_1.steps} - 1);
direction = key == "r" ? 1 : -1;
@{fader_1} + step * direction
}
```

**Comment by nlebellier** [comment]
Merci !
c'est marrant pour le linkId personnellement j'aurais choisi le sens inverse pour les <<
<< A : send car les flèches tournées vers l'extérieur. Master
>> A : receive les flèches tournées vers l'intérieur de la case. Slave

non ?

**Comment by jean-emmanuel** [comment]
Hmm, voilà comment j'avais pensé le truc, ça parait encore assez logique:
>> A: on envoit vers le groupe A, car la flêche pointe vers A
<< B: inversement

**Comment by jean-emmanuel** [comment]
-> 1b523a0 pour le scroll de souris
