### ISSUE TITLE
OSC listeners: OSC{} not working with custom-module?

### ISSUE THREAD

**Issue by mindblower23** [jean-emmanuel/open-stage-control#463]
Hi!
First of all this application is truly awesome!

I'm experimenting with an Open Stage Control Template for communicating with Ableton Live. So I use the Midi functionality of Open Stage Control and wrote my own Midi Control Script files. It works great!

When it came to submitting the names of tracks from Ableton Live I wrapped them in a SysEx message and used a custom module to convert them in an osc command. When I bind the osc address to a text widget (by using the osc section in the widgets preferences) it works like a charm. But when I try to use the OSC Listener OSC{} in the label property of a fader widget with the same osc address only the default value is shown.

Maybe I didn't get the concept of OSC listeners right, but could it be that the listener doesn't work in conjunction with the custom module?

Thanks a lot!

**Comment by mindblower23** [comment]
Ok, i'll try...

Assuming that I send a SysEx message with a JSON string like ["/track_name_2", "3-Audio"] where the first array item ist the osc address and the second is the name of the audio track, I've attached the custom-module and a small sample session. The text widget works fine but 
the slider label is not responding to the osc message ...

[Test Controller.zip](https://github.com/jean-emmanuel/open-stage-control/files/2804774/Test.Controller.zip)

**Comment by jean-emmanuel** [comment]
Ok the problem is simple: currently OSC listeners require messages to match the host widget's `preArgs`. I've been thinking about allowing users to override this, -> todo.

**Comment by jean-emmanuel** [comment]
I the meantime you can workaround it by sending `/track_name [preArgs] name"

**Comment by mindblower23** [comment]
Ah great! Thank you!! :-)

Last question: How/where do I incorporate the preArgs in the custom module?

oscInFilter:function(data){
            // Filter incomming osc messages

            var {address, args, host, port} = data

            // do what you want

            // address = string
            // args = array of {value, type} objects
            // host = string
            // port = integer

            // return data if you want the message to be processed
            return {address, args, host, port}

        }

**Comment by mindblower23** [comment]
I got it! Sorry I was too quick with asking ... ;-) preArgs are simply array items in args before the actual value. Now it's working. Wonderful. :-)

**Comment by jean-emmanuel** [comment]
Great ! :)
