### ISSUE TITLE
float default value on faders

### ISSUE THREAD

**Issue by jgastonraoul** [jean-emmanuel/open-stage-control#464]
On fader widgets, when the default value is a float, I can't use double tap to go back to default.
Do I make something wrong ?

**Comment by jean-emmanuel** [comment]
What did you write exaclty in `default` ? It must be a number (float or int), the type is defined by `precision`.

**Comment by jgastonraoul** [comment]
My mistake : I think I wrote 0,7 instead of 0.7. 

You can close this issue, thanks ! 


De: "jean-emmanuel" <notifications@github.com> 
À: "jean-emmanuel/open-stage-control" <open-stage-control@noreply.github.com> 
Cc: "Jérémie GASTON-RAOUL" <jeremie.gastonraoul@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 29 Janvier 2019 13:15:23 
Objet: Re: [jean-emmanuel/open-stage-control] float default value on faders (#464) 



What did you write exaclty in default ? It must be a number (float or int), the type is defined by precision .

**Comment by jean-emmanuel** [comment]
Ok cool !
