### ISSUE TITLE
open-stage-control.app on mac application window size and position

### ISSUE THREAD

**Issue by mindblower23** [jean-emmanuel/open-stage-control#465]
Hi!

It would be great if the position and size of the electron application windows on mac could be persistent after restarting the app. This would be of great help while developing OSC sessions! :-)

All the best
Harry

**Comment by jean-emmanuel** [comment]
I'm dropping this request : 
1. too specific / not worth adding an option
3. can be worked around by using a detached browser instead of the built-in ui
