### ISSUE TITLE
custom-module path is not escaping whitespaces?

### ISSUE THREAD

**Issue by mindblower23** [jean-emmanuel/open-stage-control#466]
When using the gui (osx) and selecting a custom-module path from the file selector any whitespace in the path leads to

CustomModule Error: File not found

**Comment by jean-emmanuel** [comment]
It seems I have introduced this regression when I added the ability to pass arbitrary options to  `--custom-module` along with the filepath. For now you can work around this by enclosing the path in quotes.

**Comment by jean-emmanuel** [comment]
fixed in git, will be included in next release
