### ISSUE TITLE
[Feature] Multi x/y EQ

### ISSUE THREAD

**Issue by scheidleon** [jean-emmanuel/open-stage-control#467]
Feature Request:

EQ with integrated multixy to edit filter options.
Picture as an example (Achieved by putting a multixy element over an EQ element and editing CSS a bit)

![image](https://user-images.githubusercontent.com/47444075/52465674-b809c600-2b7f-11e9-8b8f-87b2dd23d7af.png)

**Comment by jean-emmanuel** [comment]
Well, if you managed to do it I'm not sure it's worth adding a new widget for it...
