### ISSUE TITLE
[Feature] New container: Commo Rose

### ISSUE THREAD

**Issue by Manaberry** [jean-emmanuel/open-stage-control#468]
Someone from VI-Control posted an idea of a Commo Rose container. Instead of clicking/touching everywhere, we do use the Drag N Drop method but with the finger: Touch and choose.

![commo rose](https://user-images.githubusercontent.com/9537424/52540466-fd99df00-2d89-11e9-8ecb-280a944cb796.jpg)

Options does work exactly as a regular push button, but with a weight parameter to sort them by importance. Options themselves can be a container for another circular grid of options. 

I'm not aware of the feasibility of this feature, but it would be a huge workflow improvement for users.

It should be a nice alternative to the drop menu. (Vertical and horizontal).

_I'm about to work on a conceptual widget for articulations switching purpose. Some features might be similar to the commo rose._ 

What do you think?

**Comment by jean-emmanuel** [comment]
It could be a nice alternative to the dropdown widget :)

On the articulation matter, take a look at https://github.com/jean-emmanuel/open-stage-control/issues/461#issuecomment-459716548

**Comment by Manaberry** [comment]
Nice! Happy you like the idea.
Thanks for the link!

**Comment by GeneralMidi** [comment]
Hi jean-emmanuel,

Love what you're doing with osc. Just wondering with this commo rose idea, if it was at all possible to get something along the lines of this video (2 min mark) :

https://youtu.be/gY0X2xXddT8

Cheers

**Comment by jean-emmanuel** [comment]
Hi, I think the o-s-c way to do that would be a new container widget like the modal but that closes upon mouse/touch release and passes the event to the last touched widget inside it. It don't have the time to work on it now but I'll keep you posted as soon as I do.

**Comment by jean-emmanuel** [comment]
For the record : https://github.com/jean-emmanuel/open-stage-control/issues/152#issuecomment-475038214

**Comment by GeneralMidi** [comment]
I know you're a busy man...but any chance of a new widget like this? The suggestion above is ok, but I think what you can come up with would be much better. I don't like the hack as suggested. What do you think? Would you have time to think about this?

**Comment by jean-emmanuel** [comment]
I still plan to implement it at some point, I'll keep you posted !

**Comment by jean-emmanuel** [comment]
Getting there.. it still needs some polishing but it should be available in next release !
![screenshot-2020-01-23-23:53:04](https://user-images.githubusercontent.com/5261671/73031360-28b2fc80-3e3c-11ea-9e8a-593fae74e602.png)

**Comment by GeneralMidi** [comment]
That looks awesome! Nice work. Very interested in this. 

Earlier in the thread, you said "the o-s-c way to do that would be a new container widget like the modal but that closes upon mouse/touch release and passes the event to the last touched widget inside it".

2 min mark here:
https://youtu.be/gY0X2xXddT8

Do you think the circle could also be adjusted to a more regular modal box shape but have the same functionality as the new circle widget?

Once again, thank you for working on this in your free time.

**Comment by Manaberry** [comment]
Splendid work Jean-Emmanuel! Looking forward to try this new widget.

**Comment by jean-emmanuel** [comment]
> Earlier in the thread, you said "the o-s-c way to do that would be a new container widget like the modal but that closes upon mouse/touch release and passes the event to the last touched widget inside it".

Actually I went for something more straightforward that's more like a switch/dropdown button, but fancier.

> Do you think the circle could also be adjusted to a more regular modal box shape but have the same functionality as the new circle widget?

There will be a option for non-circular layouts.

**Comment by jean-emmanuel** [comment]
The release is almost there, meanwhile you can test the widget in the online demo : http://openstagecontrol.herokuapp.com/

**Comment by GeneralMidi** [comment]
I love it! I notice when the button is small, circle is off, grid & vertical & toggle are true, when you hit the button, the only way to close the menu is by hitting one of the value boxes. You can't hit the background to avoid triggering a menu value item. I hope I explained that ok!

**Comment by jean-emmanuel** [comment]
@GeneralMidi Yep, I noticed that too, will fix !

**Comment by jean-emmanuel** [comment]
v0.49.0 is uploading
