### ISSUE TITLE
Toggle between two Toggle Buttons / traffic light beetween two PCs

### ISSUE THREAD

**Issue by ManuelWaldmann** [jean-emmanuel/open-stage-control#469]
Hello
Is it possible to do so when pressing a toggle button on another toggle button turns off when its on? When the button was off he stays off. 
And the other way around.

Or is it possible to do a "traffic light" with a switch widget with 3 Values? push value 1 on PC 1 - a led widget on r PC 2 turns red, push value 2 on PC 1 the led widget on PC 2 turns orange, pusch value 3 on PC 1 the led widget on PC 2 turns green?

Thanks a lot for helping, Manu

**Comment by ManuelWaldmann** [comment]
Sorry. Is done

**Comment by jean-emmanuel** [comment]
:)

**Comment by Norihirock** [comment]
Hi, I still cannot find a way to do "when pressing a toggle button on another toggle button turns off." I would appreciate if either of you guys could help me.

**Comment by jean-emmanuel** [comment]
Try this the attached session, the trick lies in the toggles' `value` properties. https://github.com/jean-emmanuel/open-stage-control/files/2970334/playstop.json.txt

**Comment by jean-emmanuel** [comment]
The syntax I used is documented here : http://osc.ammd.net/extras/advanced-property-syntax/

**Comment by Norihirock** [comment]
Thanks a lot, it works! Syntax is difficult to understand for me but I'll read it again.
