### ISSUE TITLE
Editing broken in v0.16.2?

### ISSUE THREAD

**Issue by jkroll20** [jean-emmanuel/open-stage-control#47]
Great tool!
For some reason, I can't edit anything in v0.16.2. The widget properties doesn't show up, and right-click on the canvas has no effect. Everything works in v0.16.1.

**Comment by jean-emmanuel** [comment]
Damn, I made a breaking typo error... 0.16.3 will fix that very soon !

**Comment by jkroll20** [comment]
Cool, thanks!

**Comment by jean-emmanuel** [comment]
v0.16.3 fixes it, thanks for your feedback :)
