### ISSUE TITLE
[Feature] timestamps and processing time in debug mode

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#471]
Hi,
It would be useful to display a timestamp when using ``--debug``, next to ``OSC received``, and optionally to display the time elaapsed when handling each incoming message. 

This would help to diagnose round trips from the server to the client

**Comment by jean-emmanuel** [comment]
You can do that from a custom module already. Note that printing to the console from the main process affects perfomances.

**Comment by cyberic99** [comment]
Can I print the time from the server side, in a custom module?

**Comment by jean-emmanuel** [comment]
`console.log(Date.now())`

**Comment by cyberic99** [comment]
OK, I thought this code would be executed by the client... thx
