### ISSUE TITLE
Assignation du toucher sur un second écran

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#472]
Bonjour,

J'ai un souci qui n'est probablement pas directement lié à Open Stage Control, mais peut-être avez-vous une solution? J'ai deux écrans sous Windows, un seul des deux est tactile et il est en orientation portrait alors que le second écran est en orientation paysage. Le problème que j'ai est que lorsque je touche l'écran tactile, les informations de contact sont envoyées au second écran, pas à celui que je touche.

Merci d'avance.

**Comment by nesdnuma** [comment]
Apparemment, définir l'écran tactile comme écran principal résoud le problème.

**Comment by jean-emmanuel** [comment]
Ok cool :)
