### ISSUE TITLE
Bug in the keys widget

### ISSUE THREAD

**Issue by PLu55** [jean-emmanuel/open-stage-control#473]
If the Keys widget will react on key actions or not depends on where in the widget list of a Tab it is place. It work if it's first in the list but not otherwise, then it work only in edit mode but not when edit mode is turned off. I've tried it in both the default browser and in Chrome (Chromium) with the same result.

I attach two example, keys1.json which work and keys2.json that doen't.

[keys.zip](https://github.com/jean-emmanuel/open-stage-control/files/2898171/keys.zip)

**Comment by jean-emmanuel** [comment]
Both sessions work fine with the latest version.

**Comment by PLu55** [comment]
I find out that it's when you create a new Keys that it's not working when turning edit mode off. If you save it and then load it, it's working.

**Comment by jean-emmanuel** [comment]
Ahh ok, there might be a conflict between the two keyboard shortcut contexts (editor / normal)

**Comment by jean-emmanuel** [comment]
Fixed in git !
