### ISSUE TITLE
Computed value in strip widget

### ISSUE THREAD

**Issue by WillyKaze** [jean-emmanuel/open-stage-control#474]
I wonder if it's possible to store a value in strip value attribute and reuse it in children values.

For example, a strip of leds contains 10 LEDs. In the strip value we type the following code:

```js
#{
    OSC{/feedback_address}
}
```

`/feedback_address` as an integer arg containing the led values. The value for each led is extracted using:

1st LED
```js
#{
value = @{parent.value};
value = bitAnd(value, 1);
value ? 1 : 0
}
```

2nd LED
```js
#{
value = @{parent.value};
value = bitAnd(value, 2);
value ? 1 : 0
}
```
 and so on…

Would this be feasible ?

**Comment by jean-emmanuel** [comment]
The value property is a special case, it returns the widget's state value, not the property. You can do what you describe using the `variables` property though.

**Comment by WillyKaze** [comment]
In that case, how do I do this, knowing that I already pass variables from a parent ?

I tried what you suggested but didn't managed to get it work.

**Comment by jean-emmanuel** [comment]
You just need a semi-colon at the end of the first line to prevent the variable from being outputed. Clicking on "variables" next to the edition field shows the computed value and can help debugging this kind of error.

**Comment by WillyKaze** [comment]
Got it, thanks for the useful tip !

Maybe it's worth posting a working example to include it in #152 ?

**Comment by jean-emmanuel** [comment]
Yep, I forgot to point another mistake: OSC{} should not be wrapped in a formula since you are already in a formmula context.

**Comment by WillyKaze** [comment]
Yes, I found it and fixed it, thanks

**Comment by jean-emmanuel** [comment]
cool :)
