### ISSUE TITLE
Selection is lost upon horizontal scrollbar use

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#475]
Hello,

While editing, I wanted to select a lot of sliders so I began to select but some of them were outside view. So I moved the horizontal scrollbar to see the other sliders and add them to my selection but my selection got lost.

**Comment by jean-emmanuel** [comment]
Keeping `ctrl` pressed while dragging the scrollbar do the trick.

**Comment by nesdnuma** [comment]
Indeed. Thanks.
