### ISSUE TITLE
xruns (glitch)

### ISSUE THREAD

**Issue by patricksebastien** [jean-emmanuel/open-stage-control#477]
First of all thank you for open-stage-control, it's really well done! I am using it on ubuntu-studio with a low-latency kernel with a dedicated usb soundcard. I am running pure data under jack (frames/period 128) and I have no xruns when using the gui of pd or bitwig or any other softs. But in o-s-c when moving the x/y, sliders etc some xruns occurs.

Is there a way to avoid this?
Thanks

**Comment by jean-emmanuel** [comment]
Do the xrun happen even if the xy doesn't control anything ?

**Comment by jean-emmanuel** [comment]
Also are you running jack in real-time mode ? (`jackd -R` or "real-time" option in qkackctl)

**Comment by patricksebastien** [comment]
Yes, xruns when editing (just scrolling in the editor options). I did all I could to make my system really stable and with low-latency audio (including jackd -R), fs.inotify.max_user_watches, threadirqs etc... When using chrome I also have xruns. I think o-s-c is using electron / chromium, maybe there's no way to avoid xruns (**in my case**).

**Comment by jean-emmanuel** [comment]
Electron/Chromium eats too much cpu unfortunately... what's your device ? ARM ?

**Comment by patricksebastien** [comment]
Using, x64 i7-4650u 3.3 Ghz. The round-trip latency is +-22ms and bitwig struggle to keep up. It's stable when using only the gui of pd and bitwig, but not o-s-c or chrome. Will close this issue, it's a very specific setup and once again thanks for making o-s-c.

**Comment by jean-emmanuel** [comment]
Hm, actually I'm using o-s-c in a very heavy loaded setup (https://github.com/PlagiatBros/PlagiatSetup) and with a similar hardware without any trouble. There's is something you might try though: we were having perf issues with our I7 until we disabled a power-saving-related option in the bios, it seems these chips are very good at saving power but this doesn't fit well to real-time audio needs.  Anything like this in your bios ?

**Comment by jean-emmanuel** [comment]
There was a typo in the xy code causing a significant perf issue, maybe not enough to solve your problem but still !
