### ISSUE TITLE
Led color changing from osc message

### ISSUE THREAD

**Issue by tizfra** [jean-emmanuel/open-stage-control#478]
Hi,
is possible to change led color from an osc message?
I can receive a message that contains value from 0 to 4 and I would like to change color based on the value.
Can you help me?
Thanks

**Comment by nlebellier** [comment]
hi there,

this example may help
https://github.com/jean-emmanuel/open-stage-control/issues/319#issuecomment-400693993

to put into the **style** part of your widget and into **css**

**Comment by jean-emmanuel** [comment]
In the led's `color` property:
```
#{
colors = ["red", "blue", "yellow", "green", "pink"];
osc_color_index = OSC{/osc/address, 0};
colors[osc_color_index]
}
```
