### ISSUE TITLE
Feature - sticky header in editor

### ISSUE THREAD

**Issue by Sebastian-blu** [jean-emmanuel/open-stage-control#479]
Hey hey! Long time, no post on my part. Hope your doing well!! Decided to get back to working on my interface and thought it would be great to have a keyboard short cut to go to the parent, instead of only right clicking on the bounding box. As my templat has a lot of rgbLED places beneath transparent buttons. 

Another thought that goes with this would be some sort of “sticky” title for the editor. So that the selected object can be easily seen at a glance while editing parameters. I found myself scrolling up to double check where I had a button or an led selected. Thought this might improve the work flow. 

Thanks so much for all the work 👌

**Comment by jean-emmanuel** [comment]
Yo! Thanks for your support :)

> it it would be great to have a keyboard short cut to go to the parent

There's already a shortcut for this: `ctrl+up` (or `cmd+up` under osx), see https://osc.ammd.net/editing-sessions/#keyboard-shortcuts for the complete list.

> Another thought that goes with this would be some sort of “sticky” title for the editor. 

Could be nice indeed, todo then.

**Comment by jean-emmanuel** [comment]
done !
