### ISSUE TITLE
Little bugs

### ISSUE THREAD

**Issue by Pikub** [jean-emmanuel/open-stage-control#48]
Tabs : Impossible de modifier les tabs en multitouch.
push : lorsque qu'on reste appuyé sur un push et qu'on relache un autre parametre, la valeur du push revient à 0.

**Comment by jean-emmanuel** [comment]
> Tabs : Impossible de modifier les tabs en multitouch.

Est-ce que ceka se produit uniquement après avec activé "Traversing gestures" au moins une fois ? Si oui, c'est réglé (https://github.com/jean-emmanuel/open-stage-control/commit/17bf662db5d983c42a4051b15551f613bdcd99a2), à venir avec la prochaine version

>  push : lorsque qu'on reste appuyé sur un push et qu'on relache un autre parametre, la valeur du push revient à 0.

Ça devrait être réglé aussi (https://github.com/jean-emmanuel/open-stage-control/commit/d09021ebe32d895d3e4595ce72ea70e32305860c) pour la prochaine version.

Merci pour ton retour !

**Comment by jean-emmanuel** [comment]
https://github.com/jean-emmanuel/open-stage-control/releases/tag/v0.16.4

**Comment by Pikub** [comment]
Quel talent !
C'est parfait, merci !
