### ISSUE TITLE
relier Toggle on/off 

### ISSUE THREAD

**Issue by kevin9499** [jean-emmanuel/open-stage-control#480]
Bonjour !

J'aimerais savoir si il est possible de changer la couleur d'un toggle si on l'a activé  et le rendre inaccessible un pour un utilisateur qui serait sur une autre machine ?

Merci.

**Comment by jean-emmanuel** [comment]
> changer la couleur d'un toggle

On peut utiliser la propriété [`color`](https://osc.ammd.net/widgets-reference/#color). Si tu as besoin d'un changement de couleur plus fort, ce ticket vient juste d'être fermé sur le même sujet : #476 

> le rendre inaccessible un pour un utilisateur qui serait sur une autre machine

L'aspect multi-utilisateur d'o-s-c se limite à une synchronisation des widgets en fonction de leurs adresses osc. L'utilsation asymétrique d'une même session n'est pas supportée.
