### ISSUE TITLE
Text: with vertical orientation, some characters are even turned 90° too far.

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#483]
Hello,

When using the vertical orientation in the Text widget, some characters are not just turned 90° letfwards, but are even turned upside down, as if they were rotated 90° too far. For instance: ™, ©.

**Comment by jean-emmanuel** [comment]
Unfortunately this can't be fixed without removing existing features (icon support, line breaks). The input widget doesn't have this problem but is more simple.
