### ISSUE TITLE
CSS background-color in Text sets border color, not background color

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#484]
Hello,

The CSS background-color code changes the widget's border color, not the background/inner color.

**Comment by jean-emmanuel** [comment]
```
.text {
  background: red;
}
```
You can use the inspector (f12) to find which element to style.

**Comment by nesdnuma** [comment]
Just for the record: if trying to insert 2 css properties in a row:
This doesn't function: `font-size:50px; .text{background:#0000FF};`
However this functions: `.text{background:#0000FF}; font-size:50px;`

**Comment by jean-emmanuel** [comment]
> Mixing Inline and Selector syntaxes doesn't work, once you use selectors, you have to use the :host selector to target the widget element.

http://osc.ammd.net/extras/css-tips/

**Comment by nesdnuma** [comment]
Errrr... ...what is inline syntax?

**Comment by jean-emmanuel** [comment]
DId you click on the link ? ;)
