### ISSUE TITLE
Reponse Message OSC

### ISSUE THREAD

**Issue by ServanDenes** [jean-emmanuel/open-stage-control#485]
Bonjour,

Je travail sur un projet utilisant Open Stage Control pour un déclenchement à distance de Go Button sur 5 machines différentes. Les messages OSC partent bien depuis O-S-C mais est il possible de recevoir en retour les réponses OSC de Go Button ?

Merci !

**Comment by jean-emmanuel** [comment]
Oui, par défaut o-s-c recoit les messages sur le port 8080, il faut paramétrer ton logiciel pour qu'il envoie ces réponses sur ce port.

**Comment by ServanDenes** [comment]
C'est ce que j'ai fait mais je ne vois rien en retour, est ce qu'elles sont censées apparaitre dans la console debug ? je présume que oui si l'option --debug est activé... il y a quelque qui m'échappe je pense

**Comment by jean-emmanuel** [comment]
Oui ça devrait apparaître dans la console. Tu as bien suivi cette [documentation](https://figure53.com/docs/gobutton/v3/working-with-your-show/working-with-osc/#tcpudp-port-numbers) ?

**Comment by jean-emmanuel** [comment]
Si tu utilises les logiciels sur des machines différentes il faut aussi préciser l'addresse ip de la machine où tourne le serveur o-s-c.

**Comment by ServanDenes** [comment]
Oui bien sur, je souhaiterai affiché cette méthode "/cue/{number}/duration" dans un champ texte après avoir déclenché un "/cue/{number}/start" depuis O-S-C

**Comment by jean-emmanuel** [comment]
Je ne comprends pas très bien, peux-tu détailler un peu plus ? Le problème initial est résolu ?

**Comment by ServanDenes** [comment]
Oui pardon je mélange un peu tout, en fait j'ai deux problème :
1 -  Je souhaiterai afficher dans o-s-c une durée via la methode "/cue/{number}/duration". Info retournée par Go Button . Quel widget utiliser par ça ? (le widget texte ne permettant pas de spécifier une target)
2 - Je souhaiterai synchroniser le niveau du volume (via un fader), ca marche dans le sens o-s-c -> Go Button mais pas Go Button -> o-s-c

Note : il n'est pas possible de spécifier une ip depuis Go Button. Selon la doc, l'ip de reponse est la même que l'émetteur

**Comment by jean-emmanuel** [comment]
1. tu peux utiliser le widget "input", mais le widget "text" fera aussi l'affaire :  l'option target n'est pas utile dans ton cas puisque c'est "go button" qui doit envoyer l'information à o-s-c et non l'inverse
2. le problème à l'air d'être du côté du "go button", si les messagent n'apparaissent pas dans la console c'est qu'ils ne sont pas envoyés à la bonne adresse/port

**Comment by ServanDenes** [comment]
OK je vais creuser du coté Go Button. Dernière chose, est il possible dans o-s-c de créer un bouton toggle "play" et un bouton toggle "stop" liés entre eux ? cad que l'un désactive l'autre et vice versa ?

**Comment by jean-emmanuel** [comment]
Ci-joint une session avec deux boutons liés comme tu le décris, la clé se trouve dans la propriété `value` de chacun des boutons. Les syntaxes utilisées sont documentées ici : http://osc.ammd.net/extras/advanced-property-syntax/

Cependant, si tu envisages d'utiliser la même addresse osc pour les deux actions il est plus simple d'utilser un seul toggle ou un switch (buttons/switch).

**Comment by ServanDenes** [comment]
Merci ! ou est ce que je peux trouver la session dont tu parles ? Il n'y a pas de fichier joint à ton message.

En tout cas merci pour tes conseils et pour cette application géniale !
