### ISSUE TITLE
Server interruption issue: possible cause? Possible to relaunch without quitting?

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#486]
I am using Open Stage Control as a standalone. A message "La connexion avec le serveur a été interrompue" appeared.

1. Any idea of what caused the interruption?
2. Is it possible to relaunch the server without quitting/relaunching the whole app?

**Comment by jean-emmanuel** [comment]
if you are using the default gui you can't relaunch the server without restarting the whole app. This happens when server does not respond to the client, did you see any error in the console ? The connection is supposed to be reestablished automatically when it happens.

**Comment by nesdnuma** [comment]
I read:  "Websocket connection to open-stage-constrol-client.js:sourcemap:856
'ws://192.168.1.3:8080/Qf3C4hHtiN' failed: Websocket opening handshake timed out." ( x 2)

It would be nice if a successful reconnection triggered a message too. By the way, it's not possible to erase/dismiss the warning afterwards and it's annying because it hides the last fields in the bottom of the editor. Also it would be nice to have a console widget which the user could place where he wants to and resize at will.

**Comment by jean-emmanuel** [comment]
It does trigger a message that replaces the error message. If the error doesn't disappear it means the connection failed to be reestablished.

**Comment by jean-emmanuel** [comment]
> I read: "Websocket connection to open-stage-constrol-client.js:sourcemap:856
'ws://192.168.1.3:8080/Qf3C4hHtiN' failed: Websocket opening handshake timed out." ( x 2)

That's in the client's inspector, right ? Nothing on the server's side ?

**Comment by nesdnuma** [comment]
Is the server console included in the main Open Stage Control window? I read "App available at http://192.168.1.3:8080 & http://127.0.0.1:8080".

**Comment by jean-emmanuel** [comment]
Ok so no error here, this means somehow the server stopped responding without erroring. Are you able to reproduce the bug  and describe precisely how you run the app until it does (options, session, custom module, etc) ?

**Comment by nesdnuma** [comment]
I relaunched everything but now everything is running fine. Could the cause lay in some editing situation? Anyway, I have to quit now but I'll chime if it happens again. Thank you.

**Comment by jean-emmanuel** [comment]
Ok keep me posted !

**Comment by jean-emmanuel** [comment]
Closing for now, feel free to reopen if you have more informations.

**Comment by jean-emmanuel** [comment]
Maybe related to #510
