### ISSUE TITLE
scrolling=no for a frame

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#487]
Hello

I have not found how to do this, to remove the scrollbars.

Is it possible?

thx

**Comment by jean-emmanuel** [comment]
It's not possible, I could add it as an option but the related html attribute is deprecated and will stop working someday. The sccrollbars are generated by the embedded page, not the frame, the best solution is to adapt this page so that it doesn't show any scrollbar.

**Comment by cyberic99** [comment]
yeah, you' re right, I found a way to fit the page.

I tried to embed a video into a frame, and it works well

(it is only for a demo, not for live performance ;-))

**Comment by jean-emmanuel** [comment]
kewl :)
