### ISSUE TITLE
Is current host/port exposed in the object model?

### ISSUE THREAD

**Issue by super-frais** [jean-emmanuel/open-stage-control#488]
I'm coming from C-type languages and am not sure how to determine inheritance in JS, so pardon if this is obvious ;)

In a custom module, we can easily get the current host / port merely by referencing the .data object, as it is passed as a parameter to the oscIn/Out Filter functions.

It's more tricky in the top-level function and the Init section, because there is no context. I'm wondering if there is a way to refer to the server's _current_ host/port combination, i.e. does it exist somewhere in the object tree? Or, maybe poll it? Right now I am hard-coding IPs, and this is hell when I move to another machine  ;)

Same thing for the servers's current MIDI port - if I could simply create a variable that holds this in the Init section, I would have greater portability.

[p.s. Love the ability to resize the properties panel added in today's build! I can see all my crazy conditionals without needing line breaks ;)]

**Comment by super-frais** [comment]
On further thought, I realized that since I am asking about the static server settings, and not anything attached to a specific message, the IP settings have to be in a preference file somewhere...? The "Preferences" file in the Win/User/AppData/Roaming folder is mainly GUI settings and not the actual server config.

**Comment by jean-emmanuel** [comment]
The custom module exposes the `settings.read` global function that allow accessing the server options after they've been parsed, They are defined here: https://github.com/jean-emmanuel/open-stage-control/blob/master/src/server/settings.js#L55-L103

In your case calling `settings.read("targets")` will return an array of ip:port strings, and calling `settings.read("midi")` will return the raw --midi option as an array. You can also pass arbitrary options to the custom modules by appending them after the filepath in --custom-module, these will be available in the `options` global. (see [docs](http://osc.ammd.net/extras/custom-module/))

The config file you mention currently only stores the GUI-set options and the session history.

**Comment by super-frais** [comment]
> In your case calling `settings.read("targets")` ...[snip]... these will be available in the options global. (see docs)

Lol, I've read the custom module page in the docs 100x, but for some reason I never clicked on the settings.js link - goes right to the line numbers in the source. Thank you !!

**Comment by jean-emmanuel** [comment]
To be fair the link was dead until I checked when I read your issue :)
