### ISSUE TITLE
Suggestion: create a user's forum

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#489]
Hello Jean-Emmanuel,

I think it could be useful to have a user's forum. It would help to spread the knowledge about Open Stage Control and let the users share projects.

Just my 2 cents.

**Comment by jean-emmanuel** [comment]
I can't maintain and moderate a forum at the moment unfortunately, actually I'll probably have to restrict github issues to bugs reports and feature requests only because it's starting to take more time than I can spend on this project.

**Comment by nlebellier** [comment]
I do agree @jean-emmanuel even if i often ask questions and will try to reduce them. So why don't you @nesdnuma  create a discord server ?

**Comment by jean-emmanuel** [comment]
Yeah it'd nice to have a place for users run by users. The problem with giving general support in github in that everything appears more or less like a bug report to me (labels don't really help) and I kind of feel compelled to answer.

@nlebellier you mean *discourse*, right ?

IRC can be handy too, I've added freenode#open-stage-control to my default channels

**Comment by nlebellier** [comment]
Bonsoir,

No discourse is not free i really think about discord
https://discordapp.com/, some projects use it : getuikit.com as example.
it's more like an irc salon than a forum but it can be a way to explore.

if you want me to have a serious look, tell me maybe i can create a salon i
think it's not very difficult

---
Nicolas Le Bellier









Le mer. 20 mars 2019 à 17:45, jean-emmanuel <notifications@github.com> a
écrit :

**Comment by nlebellier** [comment]
c'est parti pour voir si cela te convient
https://discordapp.com/channels/558028385884831745
---
Nicolas Le Bellier









Le mer. 20 mars 2019 à 21:42, Nicolas Le Bellier <nlebellier@gmail.com> a
écrit :

**Comment by nlebellier** [comment]
le lien pour rejoindre the OpenSalonCustomer of O-S-C https://discord.gg/MRpgFn

**Comment by jean-emmanuel** [comment]
Discourse is a free/libre software, waht they sell is support and hosting. Cool ! I'll check it out :)

**Comment by nlebellier** [comment]
https://payments.discourse.org/pricing nous n'avons pas la même notion de
gratuit. Ou bien je n'ai pas trouvé l'info...
---
Nicolas Le Bellier









Le mer. 20 mars 2019 à 21:56, jean-emmanuel <notifications@github.com> a
écrit :

**Comment by jean-emmanuel** [comment]
https://github.com/discourse/discourse

Le logiciel est libre et gratuit, ils proposent un service payant d'hébergement et de support technique.

**Comment by nlebellier** [comment]
ah ok au temps (ou autant :-) ) pour moi. C'est marrant parce que je me
demandais hier soir ce qu'utilisait le forum in_thread de Sonic PI et bien
maintenant je sais c'est disclosure et ça marche bien c'est agréable à
utiliser.

---
Nicolas Le Bellier









Le mer. 20 mars 2019 à 22:14, jean-emmanuel <notifications@github.com> a
écrit :

**Comment by nesdnuma** [comment]
Merci d'avoir créé ce forum, je pense que cela permettra de recentrer Github sur le signalement de bugs et les requêtes de développement.

**Comment by jean-emmanuel** [comment]
Oui merci !

**Comment by jean-emmanuel** [comment]
I've created a framateam channel, running with mattermost (libre/free software) https://framateam.org/signup_user_complete/?id=ksx9xx6gp7yzjqhxomuwtczqoy

**Comment by nlebellier** [comment]
j'ai supprimé le salon temporaire sur discord.


---
Nicolas Le Bellier









Le jeu. 21 mars 2019 à 17:00, jean-emmanuel <notifications@github.com> a
écrit :
