### ISSUE TITLE
Render error when open a Modal

### ISSUE THREAD

**Issue by wargreen** [jean-emmanuel/open-stage-control#49]
Hi, 
I got an display error when open a modal widget.
Here a screenshot :
![capture d ecran de 2017-02-17 19-57-15](https://cloud.githubusercontent.com/assets/5098493/23084037/dea13980-f560-11e6-9815-a3092b60da95.png)

It happen both on the build-in client and on my andoid's chromium.
Resize the window (or rotate the android device) redraw and fix the display.

Thanks again for the soft !

**Comment by jean-emmanuel** [comment]
Alright thanks, will fix !

**Comment by wargreen** [comment]
I can't reproduce, but the here the config file :

[Ardour_Batailles_1.5.js.txt](https://github.com/jean-emmanuel/open-stage-control/files/786236/Ardour_Batailles_1.5.js.txt)

**Comment by jean-emmanuel** [comment]
9f10aa7d6d0d88709175f2e21a468e79c147bcb7 fixes it, it will be included in the next release

**Comment by jean-emmanuel** [comment]
=> [v0.16.5](https://github.com/jean-emmanuel/open-stage-control/releases/tag/v0.16.5)

Thanks for your feedback

**Comment by wargreen** [comment]
Thanks for your fix !
