### ISSUE TITLE
/EDIT syntax error issue

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#490]
Hello,

I am trying to control a widget from Max.

I am sending a message to a udp object ("udp localhost 8080").

The widget's is a toggle named "mebiii_select" and I want to change the text displayed.

So I am sending this message. Note that backslashes are required by Max otherwise quotes are removed, I guess they're removed before the message is sent: `/EDIT mebiii_select {\"label\": \"Tadaa\", \"color\": \"red\"}`

It doesn't function and triggers a syntax error message in the console:

> index.js:1 Uncaught SyntaxError: JSON5: invalid end of input at 1:10
>     at nu (index.js:1)
>     at tu (index.js:1)
>     at Object.beforePropertyValue (index.js:1)
>     at JSON.parse [as parseFlex] (index.js:1)
>     at Object./EDIT (remote-control.js:12)
>     at Object.exec (remote-control.js:201)
>     at t.value (osc.js:38)
>     at receiveOsc (callbacks.js:24)
>     at Array.<anonymous> (index.js:48)
>     at t.value (event-emitter.js:29)

**Comment by jean-emmanuel** [comment]
You need to wrap your JSON string in quotes otherwise max breaks it into several arguments instead of sending a single string. Here's what o-s-c actually received (enable o-s-c's `debug` to display these messages) :
```
OSC received:  { address: '/EDIT',  args: [ 'fader_1', '{"label":', '"Tadaa",', '"color":', '"red"}' ] } 
```

**Comment by nesdnuma** [comment]
I understand. I have just activated the debug option and it allows me to see whenever there is an error but frankly the error messages are cryptic for me. Anyway, I could solve the issue. Here's the correct code to be pasted in a message box in Max: `/EDIT mebiii_select "{\"label\": \"Tadaa\", \"color\": \"red\"}"` (reader, beware of the double quotes with a preceding backslash around the tags and values and without around the braces).
