### ISSUE TITLE
What is the right widget(s) for a grid of buttons with only one active at a time?

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#491]
I want to have a matrix of buttons with 10 columns and 10 rows and whenever a button would be pushed, other buttons would be switched off.

On one hand, I have tried the switch modules which functions as I want however the layout can be set only either as a single column or a single row. Also, it's not possible to switch on/off a series of buttons in a single gesture.

On the other hand, a matrix of toggles looks much mode the way I want but several buttons can remain activated simultaneously instead of only one.

Are there options on either module which could help or should I use another one?

**Comment by jean-emmanuel** [comment]
It happens to be possible with the switch widget and some css :)

```
.switch {
display:grid;
/* replace "3" with the number of columns */
grid-template-columns: repeat(3, 1fr);
grid-gap: 1rem;
}
.value {
margin:0;
border:0;
}
```

> Also, it's not possible to switch on/off a series of buttons in a single gesture.

This will be fixed in next version

**Comment by nesdnuma** [comment]
Great!

>> 

    Also, it's not possible to switch on/off a series of buttons in a single gesture.

>This will be fixed in next version

Nice. Thanks a lot!
