### ISSUE TITLE
Synchroniser l'affichage d'un Timer 

### ISSUE THREAD

**Issue by ServanDenes** [jean-emmanuel/open-stage-control#492]
Salut, je souhaiterai synchroniser ou créer un script qui interroge en continu le "Timer" de Go Button (via l'adresse OSC "/timer") de manière à contrôler que les déclenchements de Cue effectués depuis o-s-c est bien fonctionné. Il y a t-il une fonction qui le permet ? N'arrivant pas à trouver la réponse sur le formum je me permet de poser la question. J'ai essayer de le faire le widget script et afficher la réponse dans un champs texte mais en vain...

Merci pour la réponse.

**Comment by jean-emmanuel** [comment]
Ce n'est pas possible depuis l'interface, il faut créer un "custom module", voilà une ancienne réponse à ce problème : https://github.com/jean-emmanuel/open-stage-control/issues/255

**Comment by ServanDenes** [comment]
Super ! Ca semble exactement ce dont j'ai besoin... sauf que en partant du même code que celui donner dans la discussion #255, j'ai également un erreur de syntaxe, j'ai fait attention à utiliser les bon quote (je suis reparti de ton code) mais j’obtiens ce message d'erreur : 'SyntaxError : Invalid or unexpected token' suivi de plusieurs nom de module et de fichier .js comme par exemple 'at createScript (vm.js:74:10) et encore d'autre (désolé je impossible de copier tout le message)

et voici le code que j'utilise dans un .js charger dans 'custom-module' : 

(function(){

    // Do whatever you want, initialize some variables, declare some functions, ...
    var heartbeatEnabled = false,
        heartbeat = setInterval(()=>{
            if (heartbeatEnabled) {
                sendOsc({
                    address: '/timer',
                    args: [
                        {type: 'i', value: 1}
                    ],
                    host: '10.3.141.11',
                    port: 53000
                })
            }
        }, 1000)


    return {
        init: function(){
            // this will be executed once when the osc server starts
            heartbeatEnabled = true
        },
        oscInFilter:function(data){
            // Filter incomming osc messages

            var {address, args, host, port} = data

            if (address === '/timer' && args[0]) {
                heartbeatEnabled = !!args[0].value
            }

            // return data if you want the message to be processed
            return {address, args, host, port}

        },
        oscOutFilter:function(data){
            // Filter outgoing osc messages

            var {address, args, host, port} = data

            if (address === '/timer' && args[0]) {
                heartbeatEnabled = !!args[0].value
            }

            // return data if you want the message to be and sent
            return {address, args, host, port}
        }
    }

})()

**Comment by jean-emmanuel** [comment]
Ce code fonctionne chez moi, il me faut l'intégralité du message d'erreur pour le comprendre. Quelle version d'open stage control utilises-tu ?

**Comment by ServanDenes** [comment]
v0.41.4

![Capture d’écran de 2019-03-19 16-15-09](https://user-images.githubusercontent.com/44868703/54617781-3e100b00-4a62-11e9-8b08-d3ffb513a81a.png)

**Comment by jean-emmanuel** [comment]
On dirait qu'il y a des charactères invalides au tout début de ton fichier, avant la première parenthèse.

**Comment by ServanDenes** [comment]
Je ne comprend pas... je ne vois rien. Ci-joint le fichier, dis moi si tu y vois quelques chose.
Merci de ton aide

**Comment by jean-emmanuel** [comment]
ton fichier est encodé en utf-16, cet encodage n'est pas supporté par le moteur d'open stage control, ça pourrait changer à l'occastion d'une mise à jour de celui-ci mais le plus sûr est d'enregistrer ton fichier en utf-8 (il doit y avoir une option pour ça dans ton éditeur de texte).

**Comment by ServanDenes** [comment]
Exact ! Merci beaucoup ! 
Comment est il possible de convertir la variable "data" (reçu dans la réponse OSC de la machine, voir ci-dessous) dans un format horloge (64.23502 => 01:04,2) et l'afficher dans un champ texte ? Dernière question, serait il possible de utiliser cette routine pour 5 machines simultanément ? J'en demande peut-être trop...

```
OSC received: { address: '/reply/cue/1/actionElapsed',
args: '{"status":"ok","data":64.23502,"show_id":"50540E78-2CA2-4808-B6CB-F0C374D8D3BB","address":"\\/cue\\/1\\/actionElapsed"}' } From : 10.3.141.13:53228
```

**Comment by cyberic99** [comment]
voila comment convertir des secondes en ``mm:ss``:

https://github.com/jean-emmanuel/open-stage-control/issues/152#issuecomment-366350911

**Comment by jean-emmanuel** [comment]
La réponse de cyberic99 marchera en remplacant `@{position}` par `@{position}.data`.

> serait il possible de utiliser cette routine pour 5 machines simultanément

La question n'est pas très claire, la réponse est probablement oui, si les machines utilisent des adresses osc identiques tu devras faire du routing dans le custom module pour les différencier, je te laisse chercher à partir de là.
