### ISSUE TITLE
Is it possible to define a different color for selected and unselected switch's buttons?

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#493]
.value{color:xxx} is applied to both selected and unselected switch's buttons.

How can I have different colors?

**Comment by jean-emmanuel** [comment]
`.value.on` targets selected button only. You can use the inspector (f12) to find this kind of things.

**Comment by nesdnuma** [comment]
Ok! I'll dig into the inspector more often. Thank you.
