### ISSUE TITLE
Displayed values of a switch linked to other switches' values

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#494]
I have 11 switches. One of them has 10 buttons. I want this "display" switch to reflect the state of the 10 others (over the values displayed). So, the first button of this switch should display the value of first switch, second button should display the value of second switch, etc.

I have just given it a try and have encoded the "Value" field of the "display" switch like this, with `mebiii_selector` being one of the main switches:
```
{
  @{mebiii_selector.value}: 1,
  "2": 2,
  "3": 3,
  "4": 4,
  "5": 5,
  "6": 6,
  "7": 7,
  "8": 8,
  "9": 9,
  "10": 10
}
```
However it doesn't function: the first button displays the whole array, not just the first part. I have also tried to put double quotes like this: `"@{mebiii_selector.value}": 1` It's even worse because then this part of the array is put at the end.

**Comment by jean-emmanuel** [comment]
This complex usages are better handled in formulas:
```
#{

values = {}
values[@{switch_1}] = 1;
values[@{switch_2}] = 2;

}
```

note: drop the `.value` in @{} calls, it's not necessary


> It's even worse because then this part of the array is put at the end.

side note: it's displayed at the end because numeric keys are sorted automatically (you can force them to strings by prepending a whitespace or any other character).
