### ISSUE TITLE
Dynamic matrix size/labels

### ISSUE THREAD

**Issue by nlebellier** [jean-emmanuel/open-stage-control#496]
Bonsoir,

Voilà je voudrais savoir si on peut dynamiquement dans une matrice définir le nombre de lignes et de colonnes a priori oui en passant par les propriétés 

je souhaite afficher dans deux matrices différentes un nombre de samples aléatoire environ de 0 à 10 samples pour chaque rubrique : Nature et Ville.
Comment faire pour dynamiquement remplir le nom de chaque toggle et en créer dynamiquement ? Est-ce possible ? Si oui quelles pistes dois-je suivre ? 

![image](https://user-images.githubusercontent.com/4880966/54630092-593a4500-4a79-11e9-8d08-ec95dc8201c4.png)

Merci pour une éventuelle réponse.

**Comment by jean-emmanuel** [comment]
> Voilà je voudrais savoir si on peut dynamiquement dans une matrice définir le nombre de lignes et de colonnes a priori oui en passant par les propriétés

Oui, en utilisant les syntaxes avancées pour définir la propriété `matrix` (http://osc.ammd.net/extras/advanced-property-syntax/)

> Comment faire pour dynamiquement remplir le nom de chaque toggle et en créer dynamiquement 

Pour créer des matrices complexes, voilà la méthode conseillée (en anglais, copié d'un message à un autre utilisateur):

There is another way to build your matrix that would offer more flexibility :

- create a container and build a widget template in it (button, text widget overlay, etc), use the container's "variables" property to define the subwidgets' properties that must change (id, address, etc)

- create a matrix of "clone" widgets targetting the template container and make the "variables" property change depending on the cells

--

Ci-joint une session d'exemple dans la quelle le widget modèle dupliqué par la matrice a son label dépendant de la variable reçu sur l'adresse osc `/toggle_x/label` où x est le rang du widget dans la matrice.

**Comment by cyberic99** [comment]
il y a aussi ca:

https://github.com/jean-emmanuel/open-stage-control/issues/433#issuecomment-440228660
