### ISSUE TITLE
[Feature Request] Traversing gestures don't affect Snap for knobs

### ISSUE THREAD

**Issue by super-frais** [jean-emmanuel/open-stage-control#498]
Salut! I was unable to get a matrix of knobs to respond to vertical (linear) gestures - they would always snap. I eventually realized that I had "Traversing Gestures" enabled at :root, and disabling traverse returned the default knob behavior. When traverse is on, it is impossible to change the snap behavior for knobs.

I suspect this might be a "necessary evil" of the traverse - it might not be possible to disable knob snap without a lot of work. In which case, I would suggest graying the `snap` property in the sidepanel when traverse is on ;)

**EDIT:** I realize that linking traverse and snap for the Fader object is ideal, it just doesn't make sense to me for knobs. There are many situations where you need to traverse (across faders, across buttons), but still need linear knob behavior. I can't think of a use case for traversing knobs.  So I changed the topic to be a feature request - enable traverse but be able to turn off snap for knobs.

**Comment by jean-emmanuel** [comment]
Good point. A decent traversing behavior for knobs would be reacting to both horizontal and vertical gestures in a natural way:
- from top left corner to top right corner -> clockwise
- from top left corner to bottom left corner -> counterclockwise
- etc

What du you think ?

**Comment by jean-emmanuel** [comment]
Ok it almost there :)

**Comment by jean-emmanuel** [comment]
It's in git and should be available in the online in a minute. (see commit message above)

**Comment by super-frais** [comment]
It's great!  Go to sleep, and wake up to an awesome revision  ;)

This is more predictable behavior, especially in a performance situation. It's cool that you can approach from the bottom and get counterclockwise, even though you're moving left --> right. In a large matrix, you can selectively choose direction merely by the height of your swipe.

Nice!

**Comment by fractalf** [comment]
@jean-emmanuel Sorry to ping you on a closed issue, but I read through this and even checked your commit, but couldn't figure out how this is working.

My template knob is set to *mode: vertical* and all parent panels have *traversing: true* , but still the knobs in the matrix clones are behaving *circular*. 

In the image here the top one is the template and the bottom the matrix.

I event tried to force set this in the matrix clone props, but that also didn't make my matrix knobs behave vertical.

Am I missing something here?
```
{
  "widgetId": "device_param_panel",
  "props": {"variables": {"n": #{$+1}}, "visible": true, "mode": "vertical"}
}
```

![image](https://user-images.githubusercontent.com/5707457/134810702-b90905b2-4761-42b4-9cab-fc844e186007.png)
