### ISSUE TITLE
[Feature] push / keyboard aftertouch & velocity

### ISSUE THREAD

**Issue by Pikub** [jean-emmanuel/open-stage-control#499]
Serait il envisageable d'avoir une sorte de gestion de vélocité sur les pushs ? Une variable qui serait dépendante de la surface du doigt qd on appuie sur un bouton. En général plus on appuie fort avec le doigt, plus la surface en contact avec l'écran est importante. Est ce que cette information est facilement récupérable ? On pourrait même envisager un after touch avec cette technique. Qu'en penses tu ?

**Comment by jean-emmanuel** [comment]
Pourquoi pas !

**Comment by cyberic99** [comment]
Et si on a juste des gros doigts? ;-)

**Comment by jean-emmanuel** [comment]
Hehe, l'idée serait d'avoir ça en option, un peu comme le "touchAddress" des faders/knobs

**Comment by Pikub** [comment]
Oui c'est ça, exactement comme le touchadress. Si on a des gros doigts...he bien...il faut que l'info puisse être calibrer avec un logiciel tiers en fonction de la taille du doigt (ou des doigts ; on peut imaginer avec ce système qu'on utilise 2 doigts sur un push pour avoir une vélocité élevée. Mais bon pour la calibration pour le coup je pense pas que doit être intégrer à O S C.

**Comment by jean-emmanuel** [comment]
J'envisageais plutôt d'utiliser la pression exercée sur le support tactile comme valeur (ça ne marchera pas sur tous les appareils, mais il n'y a pas vraiment d'alternative de toute façon, utiliser le nombre de doigt ne me parait pas très judicieux). La calibration est aussi peut-être possible depuis la configuration des appareil directement.

**Comment by Pikub** [comment]
Je ne savais pas qu'on pouvait récupérer les valeurs de pression, c'est top !

**Comment by Pikub** [comment]
Re, 
autre idée pour le keyboard, inspiré de Gstomper, excellente appli android : pour la vélocité sur le keyboard, plus on touche la note vers le haut plus la vélocité est élevée 
De mon coté j'avance sur un pont entre O S C et live avec un patch Max4Live, ça marche plutôt très bien ! Je travail avec une Surface 2017, la réactivité est au top, un vrai plaisir pour des minis sessions live sans contrôleurs ! Si tu travailles sur live et que tu es intéressé je peux te mettre mon patch à dispo. A+

**Comment by jean-emmanuel** [comment]
Oui, bonne idée, je pensais aussi éventuellement à utiliser la distance au point d'appui d'origine sinon.
Je n'utilise pas live mais d'autres ici peut-être, ça peut valoir le coup de faire un dépôt github/framagit et de partager ton setup sur le nouveau forum ! https://openstagecontrol.discourse.group/

**Comment by nesdnuma** [comment]
Bonjour,

Une autre idée serait de mesurer la vélocité comme on le fait sur un vrai clavier: en mesurant le temps qui s'est écoulé entre la fermeture d'une première cellule et la fermeture d'une seconde, fermetures liées à l'inclinaison de la touche.  Sur un écran tactile, on pourrait mesurer le temps entre le franchissement de deux points sur une ligne par exemple. La précision est bien sûr limitée par la fréquence de balayage de l'interface tactile. On doit être à 60Hz sur la plupart des écrans, non?

**Comment by jean-emmanuel** [comment]
Avec le widget "canvas" la valeur de pression sera utilisable dans la prochaine version, je laisse donc cette fonctionnalité potentielle aux mains des utilisateurs.
