### ISSUE TITLE
Modal in a Strip is open in the background

### ISSUE THREAD

**Issue by wargreen** [jean-emmanuel/open-stage-control#50]
Hi !
Open a modal, when placed in a strip, show it in the background of the other widgets.
![capture d ecran 2017-02-18 a 03 37 36](https://cloud.githubusercontent.com/assets/5098493/23089603/d3a26c2c-f58b-11e6-8a3d-d9ea54382329.png)
![capture d ecran 2017-02-18 a 03 37 47](https://cloud.githubusercontent.com/assets/5098493/23089604/d7b8e5de-f58b-11e6-8852-331865f6bb49.png)

Thanks !

**Comment by wargreen** [comment]
After test, it's the same on OSX with both the default client and firefox.

**Comment by jean-emmanuel** [comment]
Tricky one, will investigate :)

**Comment by jean-emmanuel** [comment]
c521162bb94b97ab7813f2cbb335db050db334b0 fixes it, to be included in next release !

**Comment by jean-emmanuel** [comment]
=> [v0.16.5](https://github.com/jean-emmanuel/open-stage-control/releases/tag/v0.16.5)

Thanks for your feedback
