### ISSUE TITLE
bug les clones ne fonctionnent pas sur ios 9.3

### ISSUE THREAD

**Issue by guitmart** [jean-emmanuel/open-stage-control#500]
Les strips en clone ne fonctionnent plus sur IOS 9.3.5, elles ne s'affichent plus. J'ai essayé avec la démo en ligne de Ardour et j'ai le même problème.
Open stage est une super application, merci.

**Comment by jean-emmanuel** [comment]
Ça devrait être corrigé pour la prochaine version, peux-tu tester la demo pour vérifier ?

**Comment by guitmart** [comment]
merci,
j'ai testé sur la démo et tout fonctionne.
Super!

Le ven. 29 mars 2019 à 04:10, jean-emmanuel <notifications@github.com> a
écrit :
