### ISSUE TITLE
[bug?] css flex updates requires reload to render

### ISSUE THREAD

**Issue by GeneralMidi** [jean-emmanuel/open-stage-control#501]
This could be normal behaviour, but I thought I'd let you know. 

1. Add a panel. 
2. add this to panel's css 
`.panel{
display:flex;
align-contents:stretch;
}`
3. add a push button inside panel. Make sure left, top, width, height is all `auto`
4. add this to button's css
`:host{
flex:1;
flex-grow:1;
}`
5. nothing changes, Save then reload. Now you see the changes. 

Apologies if this has been asked before.

**Comment by jean-emmanuel** [comment]
Thanks for the report, there's indeed a little bug at step 3 that prevents the style to apply properly, will fix soon.

**Comment by jean-emmanuel** [comment]
fixed in git
