### ISSUE TITLE
Font-size property won't function in toggle

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#502]
Hello,

I've written this in a toggle's CSS:
```
.toggle {
font-size:25px;
}
```

It doesn't function.

The following code does function however:
```
:host {
font-size:25px;
}
```

**Comment by jean-emmanuel** [comment]
The element with class  `toggle` doesn't contain any text, you should either target `.label` or `:host`.

**Comment by nesdnuma** [comment]
OK, got it. Thanks.
