### ISSUE TITLE
Encoder won't turn at all, neither with mouse nor finger

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#504]
I've tried this widget both with default settings and with some values for the "ticks" property, nothing helps. Debug shows that no OSC message is sent.

**Comment by jean-emmanuel** [comment]
It's a regression that's been introduced with the regular knobs "ticks" addition. It's fixed in git now, you can set `ticks` to the correct default value (`360`), to workaround it until the release.
