### ISSUE TITLE
Tracking of knob easily lost in the middle of rotating gesture

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#505]
I have inserted a few knobs with a big size (width: 130, height:180) but when turning them with fingers, gesture tracking is easily lost in the middle of a rotating gesture. Increasing the tolerance margin could be useful.

**Comment by jean-emmanuel** [comment]
Knobs don't follow rotating gestures but vertical gestures unless traversing gestures are enabled. I'm not sure to understand the issue.

**Comment by nesdnuma** [comment]
I thought they were following rotating gesture, hence the issue probably.

**Comment by jean-emmanuel** [comment]
That being said, it's possible to increase the knob's inner margin with css:
```css
.wrapper {
  padding: 40rem;
}
```
You'll to either resize the window or the knob or toggle the sidepanel to make the widget draw correctly after adding this.
