### ISSUE TITLE
Widget reference page navigation won't give direct access to specific widgets

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#506]
Only the links for the categories link to the matching parts but obviously the links for the individual widgets only reload the whole page and miss a # ("fragment identifier").

**Comment by jean-emmanuel** [comment]
The # is not missing, however there's is a bug preventing the page to scroll correctly which is fixed an hour ago (not deployed yet).

**Comment by jean-emmanuel** [comment]
(deployed)

**Comment by nesdnuma** [comment]
It still doesn't work for me (Firefox, Windows 10 64 bit).

**Comment by jean-emmanuel** [comment]
Can you provide a link that doesn't work ? I just tried with firefox (v60)

**Comment by nesdnuma** [comment]
I am under Firefox 66.0.2. In the attached picture you can see in the bottom left the link for the fader widget (the mouse pointer is not displayed in the screen caption). As you can see, the top of the page is displayed instead of the seeked part.

![image](https://user-images.githubusercontent.com/6513218/55888248-567dcc00-5baf-11e9-88a4-c1b81fde34b7.png)

**Comment by jean-emmanuel** [comment]
I'm really sorry, now I understand which part is problematic, I'll fix it in no time.

**Comment by jean-emmanuel** [comment]
Ok it should be good now.

**Comment by nesdnuma** [comment]
Indeed. Thanks!
