### ISSUE TITLE
Script widget syntax

### ISSUE THREAD

**Issue by WillyKaze** [jean-emmanuel/open-stage-control#507]
Hi all,

I'm trying to use a script widget to get some values from an OSC address and write the value to defined widgets. After tries and errors, I couldn't get this to work. Here is how I tried to do it:

I have some fader and text widget with a know id. My script widget script property is set to:
```
key = value[0];
val = value[1];
(key == "net:dhcp") ?
    set("umc_@{parent.variables.n}_config_net_dhcp", val) :
(key == "net:static") ?
    set("umc_@{parent.variables.n}_config_net_static", val) :
(key == "net:netmask") ?
    set("umc_@{parent.variables.n}_config_net_nm_addr", val) :
(key == "net:gateway") ?
    set("umc_@{parent.variables.n}_config_net_gw_addr", val) : "";
```
Script condition is set to 1 and script address is set to `/@{parent.variables.root}/@{parent.variables.n}/config/get/reply`

My OSC message sent to `/ROOT/55/config/get/reply` with 2 args:
* The key as a string (i.e. "net:static")
* The config value (i.e. true)

However I couldn't succeed with updating the value in associated widgets (i.e. `umc_55_config_net_static`

Any advices ?

**Comment by jean-emmanuel** [comment]
I think the problem here is `"umc_@{parent.variables.n}_config_net_dhcp"`: `@{}` statements are replaced with variables names in formulas, not with their value. To produce the string you want you'd have to write 

`concat("umc_", string(@{parent.variables.n}), _config_net_dhcp")`

**Comment by jean-emmanuel** [comment]
Note that with the new JS syntax you could write 
```js
JS{{

var [key, val] = value || ['', false];
var nets = {
  "net:dhcp": "net_dhcp",
  "net:static": "net_statis",
  "net:netmask": "net_nm_addr",
  "net:gateway": "net_gw:addr"
}
if (nets[key]) {
  set("umc_" + @{parent.variables.n} + '_config_' + nets[key], val)
}

}}
```

**Comment by jean-emmanuel** [comment]
The issue tracker is now limited to bug reports and feature requests, please use the dedicated forum :) https://openstagecontrol.discourse.group/

**Comment by WillyKaze** [comment]
Thanks for the feedback, works well now.

I will use the discourse app for further questions

**Comment by jean-emmanuel** [comment]
cool :)
