### ISSUE TITLE
sync between clients with RGB and XY widgets

### ISSUE THREAD

**Issue by jgastonraoul** [jean-emmanuel/open-stage-control#508]
Hi,

Although I have no problem to synchronise faders, buttons and switches between several clients on the same session, it doesn't work at all on RGB and XY widgets.
If I have 2 clients on the same session and I change the position of the cursor on a RGB (or XY) widget on 1 client, it doesn't change at all on the other one.

Am I missing something ?

I've attached my session file if needed.

Regards,

Jérémie
[MVS.json.zip](https://github.com/jean-emmanuel/open-stage-control/files/3059078/MVS.json.zip)

**Comment by jean-emmanuel** [comment]
Thanks for the report, there was a sync bug with the `split` option. The fix is in git and will be included in next release.

**Comment by jean-emmanuel** [comment]
-> v0.45.3
