### ISSUE TITLE
Déconnexion serveur

### ISSUE THREAD

**Issue by jibestudio** [jean-emmanuel/open-stage-control#510]
Bonjour Jean-Emmanuel,

Depuis quelques versions (à partir de la 40.3), j'ai régulièrement des notifications de déconnexions sur la tablette (OSC en mode "No Gui"). Le Wifi est bon (tablette à quelques mètres du point d'accès). La déconnexion dure quelques secondes, puis le client se reconnecte automatiquement avec toutefois des pertes ou du retard d'informations si on a cliqué sur un bouton pendant la déconnexion.
Cela s'accompagne en général de messages dans la console liés à des problèmes de Javascript et de WebSocket que je ne sais pas interpréter. J'ai vu qu'un autre utilisateur avait le même genre de problème (issue #486). Ci-joint un exemple de messages de la console. 
Par ailleurs, merci pour ton travail.
[ConsoleOSC_Win10pro_64.txt](https://github.com/jean-emmanuel/open-stage-control/files/3069351/ConsoleOSC_Win10pro_64.txt)

**Comment by jean-emmanuel** [comment]
Bonjour, ce problème n'est pas évident à pister. 
- utilises-tu bien chrome pour te connecter au server, si oui quelle version ? Si ton appareil est sous iOS, il me faudrait la version du système ?
- peux-tu confirmer que l'erreur ne se produit pas avec la version précédente (0.40.2) ?
Merci

**Comment by jibestudio** [comment]
J'utilise des tablettes sous Android, 1 sous Android 7 (nougat), l'autre
sous Android 8.1 avec Samsung Internet (à base de Chrome mais je ne sais
pas quelle version, mais c'est la dernière mise à jour sur Google Play)
Et d'après mon expérience, je n'ai pas ce problème avec la 0.40.3. C'est
les versions ultérieures qui me posent problème.

Voilà j'espère que ça t'aidera ;)

Jean-Baptiste

**Comment by jean-emmanuel** [comment]
Le système de notification à été ajouté à la version 0.41.0, il est probable que ces erreurs arrivaient déjà avant sans être notifiées. Peux-tu essayer avec une connexion réseau filaire entre ton appareil et la machine principale ?

**Comment by jean-emmanuel** [comment]
De mon côté pour l'instant je n'ai réussi à reproduire la situation (même erreur côté serveur et côté client), qu'en coupant brièvement la connexion réseau. Je vais essayer de réduire le temps de détection et réduire le délai de tentative de reconnexion.

**Comment by jibestudio** [comment]
Je suis en train de mettre en place une connexion filaire à partir d'une
tablette Android qui possède un port RJ (pas si fréquent !). Je te tiens
au courant du résultat...

**Comment by jean-emmanuel** [comment]
Il me semble que c'est aussi possible en usb, non ?

**Comment by jibestudio** [comment]
Oui sur certaines tablettes avec un adaptateur qui n'est jamais fourni
avec mais comme j'ai une tablette de kiosque public dans un carton, je
vais l'essayer...

**Comment by cyberic99** [comment]
sinon tu peux prendre un adaptateur USB otg et un donggle USB->Ethernet

On alors utiliser https://github.com/vvviperrr/SimpleRT, ca passe par l'USB

**Comment by jibestudio** [comment]
Alors après pas mal de tests en filaire avec la dernière version de
Chrome pour Android, je n'ai eu aucune déconnexion. Mais si c'est lié au
Wifi, je ne vois pas trop comment faire car le réseau est déjà excellent.

**Comment by jean-emmanuel** [comment]
J'ai un peu avancé sur le sujet, je pense qu'il y a plusieurs choses en jeu ici:
- il y a sans doute des micros coupures réseaux dues au wifi des tablettes
- la reconnexion automatique d'o-s-c est trop lente
- le processus de reconnexion engendre parfois des erreurs en laissant des connections mal fermées qui perturbent la communication avec le serveur par la suite

**Comment by jibestudio** [comment]
Bravo pour ta réactivité ;)

J'ai effectivement plus de soucis avec certaines tablettes qui n'ont que
des antennes en 2.4 GHz et sont moins performantes (Archos Sense 101X)

Bon WE,
JB

**Comment by jean-emmanuel** [comment]
Le correctif est en ligne !

**Comment by jibestudio** [comment]
Parfait, j'essaierai dès lundi !
Merci et bon WE.

**Comment by nesdnuma** [comment]
Bonjour,

Pour info, avec un autre logiciel qui envoie de l'OSC (Lemur pour ne pas le nommer), je me connecte depuis une tablette Android Samsung par un port USB mais j'ai dû installer une app qui s'appelle Tethering Toggler sur la tablette.

J'ai noté aussi des problèmes de déconnexion intempestifs récemment bien que je fasse tourner ma session directement sur O-S-C (sans navigateur, donc) et en outre sur la même machine que celle qui fait tourner le récepteur OSC (Max). Je n'ai pas testé en situation depuis une semaine mais lors de mon test précédent le problème était qu'une fois que le serveur avait planté, Max semblait ne plus pouvoir recevoir sur le port OSC. Je vais retester d'ici quelques jours.

**Comment by jean-emmanuel** [comment]
> Max semblait ne plus pouvoir recevoir sur le port OSC

Même en envoyant les messages depuis une autre application genre Lemur ? Dans ce cas il y a peut-être un problème de réseau local sur ta machine, ça pourrait expliquer tes déconnexions intempestives (même sans navigateur, la communication entre l'interface et le serveur passe par le réseau).

**Comment by nesdnuma** [comment]
Comme j'étais en répétition quand le problème s'était posé, je n'ai pas trop eu le temps d'investiguer, mais il me semble que seule la connexion depuis O-S-C posait problème. Les connexions vers les autres appareils (tablette Samsung, iPad) passent d'une part par de l'USB et d'autre part par de l'Ethernet. Une question. Quand tu écris : 

> (même sans navigateur, la communication entre l'interface et le serveur passe par le réseau).

c'est le réseau local (localhost), on est bien d'accord? Donc a priori le réseau utilisé par exemple pour naviguer sur le Web par mon navigateur n'entre pas en ligne de compte. Juste?

**Comment by jean-emmanuel** [comment]
> c'est le réseau local (localhost), on est bien d'accord ?

Oui

**Comment by nesdnuma** [comment]
Du coup, je ne vois rien qui ait changé (ordinateur, système, réseau...). Bon mais puisque c'est resté stable depuis, le problème est pour l'instant en suspens. Par contre, si le logiciel se plante, comme je travaille pour l'instant en mode debug, est-ce qu'il y a un fichier log que je pourrais te renvoyer? Sinon, à quels éléments faire attention si cela se reproduit?

**Comment by jean-emmanuel** [comment]
Le mieux serait de lancer le server depuis un terminal, les messagent devraient y être affichés persister si l'application plante, la procédure devrait ressembler à ça:
- ouvrir le terminal (quelque chose comme `cmd.exe` sous windows)
- `cd C:/Chemin/vers/open-stage-control`
- `open-stage-control.exe`

**Comment by nesdnuma** [comment]
OK, je vais essayer cela.
