### ISSUE TITLE
regression with commit bb46538e8959eaa9813776e0240a257d0febeca2

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#512]
Hello

From this commit:
```
commit bb46538e8959eaa9813776e0240a257d0febeca2

Author: jean-emmanuel <jean-emmanuel.doucet@groolot.net>
Date:   Sun Apr 7 12:42:31 2019 +0200

    jsparser: print "ERROR" when fail
```

my panel doesn't load correctly anymore

I think something has been broken, related to matrices clones.

My panel is attached, I have tried to simplify it to the max

[tod_simple.json.zip](https://github.com/jean-emmanuel/open-stage-control/files/3075439/tod_simple.json.zip)

If you need more info or a simpler repro case, tell me

before:
![before](https://user-images.githubusercontent.com/193917/56070788-5128a900-5d8a-11e9-83b8-c7a939930fc7.png)

after:
![after](https://user-images.githubusercontent.com/193917/56070792-55ed5d00-5d8a-11e9-801a-ec33a2819519.png)

Thanks a lot

**Comment by jean-emmanuel** [comment]
Effectivement ça a eu un effet de bord bien embêtant, c'est corrigé du coup.

**Comment by jean-emmanuel** [comment]
-> 0.45.4
