### ISSUE TITLE
Version 0.45.4 unexpectedly quits

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#513]
The application quit twice unexpectedly today. This is the very first time since I have been using 0-S-C (Windows 10, 64bit).

**Comment by jean-emmanuel** [comment]
Any error message that could help ?

**Comment by jean-emmanuel** [comment]
Also please provide as much contextual informations as possible (session fil, custom-module, server options, client browser version, number of clients, etc).

**Comment by nesdnuma** [comment]
There was no error message I could read (both the launcher and the session crashed). Also I had a rehearsal session this evening and the software was completely stable.

**Comment by jean-emmanuel** [comment]
Did something change in your setup between the unstable and the stable phase ? (different computer, system update, network, etc)

**Comment by jean-emmanuel** [comment]
Merged to #510
