### ISSUE TITLE
Problème CSS responsive

### ISSUE THREAD

**Issue by kevin9499** [jean-emmanuel/open-stage-control#514]
Bonjour, 

J'utilise la responsive CSS pour que l'application tablette soit adaptée sur mobile.
Les strip par exemple : je mets la width en auto, ensuite en css je déclare une width en px. et en @media.... je mets width 100% cela fonctionne pour le premier strip mais une fois que je fais la même manipulation sur le 2ème il ne veut plus prendre en compte le déplacement que je lui attribue ex :"margin-left"du coup je ne peux pas le déplacer pour le placer correctement quand l'écran est inférieur à 400.
"j'ai bien mis :host pour augmenter la width dans le @media."

Merci d'avance

**Comment by jean-emmanuel** [comment]
Salut, c'est un peu difficile à comprendre tel quel, peux-tu donner m'envoyer ta session ?

**Comment by jean-emmanuel** [comment]
Aussi, merci de n'utiliser le github que pour les bugs et les demandes de fonctionnalités, pour le reste : https://openstagecontrol.discourse.group/

**Comment by jean-emmanuel** [comment]
-> https://openstagecontrol.discourse.group/t/probleme-de-responsivite/67
