### ISSUE TITLE
[Bug] absolute paths not resolved under windows

### ISSUE THREAD

**Issue by jean-emmanuel** [jean-emmanuel/open-stage-control#515]
This applies to all css `url()` calls and affects the image widget.

- solution: escape `:` and `\`
- question: should paths be resolved relatively to `remote-root` ?

**Comment by jean-emmanuel** [comment]
> solution: escape : and \

done

> question: should paths be resolved relatively to remote-root ?

Soft fix: only images can be served this way, other filetypes are forbidden.

**Comment by GeneralMidi** [comment]
If you accidently add single quotes around the path, some definite funkyness occurs!

e.g. In value for img widget
'C:\test.jpg'

**Comment by jean-emmanuel** [comment]
Hmm it's a subtle but that's not related to this issue, I'll dig this.

**Comment by jean-emmanuel** [comment]
This happens because the backslash is an [escape character](https://en.wikipedia.org/wiki/Backslash#Usage). I fixed it for single strings only, not in arrays or objects, if you need to write windows path in arrays/objects, either use double backslashes (\\) or regular slashes (/) as separators.

**Comment by jean-emmanuel** [comment]
> If you accidently add single quotes around the path, some definite funkyness occurs! Edit: double quotes too!
e.g. In value for img widget
'C:\test.jpg'

I'm reverting the fix as it causes some side effects, the issue is easy to avoid (ie not using quotes)
