### ISSUE TITLE
[Feature] Option to automatically display a widget's code in the developer tools panel

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#518]
Hello,

It is a bit cumbersome to find a specific widget's code in the developer tools panel (F12) as long as the whole chain of its containers is not completely expanded. An option to auto-expand any chain when a widget is selected in the GUI would be quite useful.

**Comment by jean-emmanuel** [comment]
It's not possible, sorry. You can use the mouse selection tool to inspect an element faster : 
![screenshot-2019-04-18-15:08:44](https://user-images.githubusercontent.com/5261671/56363182-e8a75500-61eb-11e9-8033-f7191cac6381.png)

**Comment by jean-emmanuel** [comment]
To be fair, it would be possible by writing a chrome extension for the DevTool : https://developer.chrome.com/extensions/devtools
I don't plan to do that anytime soon though.

**Comment by nesdnuma** [comment]
I understand that it's not the immediate priority... ;-)
