### ISSUE TITLE
[Feature] Custom base for a knob's logarithmic scale

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#519]
It is quite useful to have a logarithmic scale in a knob, but it would be even better if one could set a custom logarithm's base (as in the Max for Live's dial for instance).

**Comment by jean-emmanuel** [comment]
I agree !

**Comment by jean-emmanuel** [comment]
In git, you can even set logScale under `1` to get an exponential scale.

**Comment by nesdnuma** [comment]
> In git, you can even set logScale under 1 to get an exponential scale.

That would be nice for sure. Thanks for the commit, J-E!

**Comment by jean-emmanuel** [comment]
-> v0.45.6
