### ISSUE TITLE
[Feature] Keyboard widget keys as toggles?

### ISSUE THREAD

**Issue by narrsam** [jean-emmanuel/open-stage-control#520]
I love this... great work!
Is there a way to make the Keyboard widget's keys act as toggles? 
If not please add it to the wish list :)

**Comment by cyberic99** [comment]
You can have another widget, and link it with the linkId property

for instance, I have a ``key_debug`` widget, with:

``keydown #{@{debug}?0:1}``
``keyup: #{@{debug}?1:0}``

And I have another toggle called 'debug'

**Comment by jean-emmanuel** [comment]
@narrsam is referring to the piano keyboard widget, it's not a bad idea

**Comment by cyberic99** [comment]
ha yes, sorry

**Comment by jean-emmanuel** [comment]
Included in v0.45.7 !
