### ISSUE TITLE
[Bug] multiple images, session très longue à loader

### ISSUE THREAD

**Issue by guitmart** [jean-emmanuel/open-stage-control#521]
Bonjour Jean-Emmanuel,
Dans ma session j'ai plusieurs fois la même image avec l'option cache à true mais la session est longue à loader et l'application «lag». J'ai l'impression que la cache ne fonctionne pas correctement. Peut-être que c'est moi qui n'utilise pas correctement le widget image.

Merci.

**Comment by jean-emmanuel** [comment]
Bonjour,
Est-ce que le ralentissement disparaît simplement en enlevant les images ?
Quelle taille fait le fichier de l'image ?
Peux-tu m'envoyer ton fichier de session ?

**Comment by jean-emmanuel** [comment]
Il y a effectivement un problème avec l'option cache qui fonctionne à l'envers. Aussi l'envoi de gros fichier met en pause le processus du serveur et peut bloquer l'interface si elle est lancée avec le serveur. Je vais voir si ça peut être atténué.

**Comment by jean-emmanuel** [comment]
> Aussi l'envoi de gros fichier met en pause le processus du serveur et peut bloquer l'interface si elle est lancée avec le serveur.

En fait non ce n'est pas le cas. Le blocage de l'interface vient du chargement de l'image par le navigateur, donc la seule solution si ça ne fonctionne pas mieux avec le correctif que je viens de mettre en ligne, c'est de réduire la taille des fichiers.

**Comment by guitmart** [comment]
Dans la console en debug sur chrome je viens de voir plusieurs erreurs undefined quand j'utilise la syntaxe mathématique  #{@{widgetId}}
ex: /#{["mixes","inputs"][@{this.value}]}

[192.168.0.102-1555961835450.log](https://github.com/jean-emmanuel/open-stage-control/files/3104631/192.168.0.102-1555961835450.log)

**Comment by guitmart** [comment]
Si j'enlève les images il n'y a plus de ralentissement.
La grosseur des image est environ 1.4ko en png.
J'ai voulu tester sur le site mais comment je fais pour avoir les images à la racine du site, quel path dois-je prendre?

**Comment by guitmart** [comment]
J'ai contourné le problème en donnant le même id aux images identiques de cette façon l'image n'est pas loader 100 fois. Je les ai encodé en base 64 alors plus d'URL.
On dirait qu'il y a moins de lag avec le serveur démo qu'avec celui de mon poste, c'est peut-être ton changement.

**Comment by jean-emmanuel** [comment]
Oui l'option cache fonctionnant à l'envers l'image était rechargé pour chaque widget, ça explique sans doute le ralentissement.

> J'ai contourné le problème en donnant le même id aux images identiques de cette façon l'image n'est pas loader 100 fois. Je les ai encodé en base 64 alors plus d'URL.

Ça risque d'être moyennement performant tout de même si l'image est dupliquée 100 fois (la chaine de caractères en base64 est dupliquée pour chaque widget). Si tu veux utiliser une image en base64 beaucoup de fois, le mieux serait de la déclarer une seule fois dans le css du widget `root` par exemple et d'ajouter une classe personnalisée à tes widgets image:

css (root)
```css
.classe-perso .image {
  background-image: url(data:image/png;base64,...);
}
```

css (image)
```css
class: classe-perso;
```

> Dans la console en debug sur chrome je viens de voir plusieurs erreurs undefined

Ces erreurs sont générées quand les valeurs récupérées ne sont pas encores définies (création d'un widget avant celui dont il utilise la valeur), pas de souci de ce côté là.

**Comment by jean-emmanuel** [comment]
Le correctif est inclus dans la v0.45.7.

**Comment by guitmart** [comment]
Avec le correctif et le css (root) ça fonctionne nickel sur le UI côté serveur mais sur le client il n'y a aucune image. J'ai vérifié avec le debug de chrome pour voir que le css background-image:url(base64...) était écrasé par url("") alors mon impression c'est qu'il prend la valeur entré dans la value du widget image en priorité du côté client. J'ai utilisé le theme pour ajouter les images en base64 avec un !important pour que cela fonctionne partout

**Comment by jean-emmanuel** [comment]
Ok cool ! Effectivement, la valeur du widget prime sur le css, il faut bien mettre `!important` dans le css pour passer outrre.

**Comment by jean-emmanuel** [comment]
Ça devrait être corrigé dans la prochaine version.

**Comment by guitmart** [comment]
super merci
