### ISSUE TITLE
[Feature] serveur qui écoute sur plusieurs ports

### ISSUE THREAD

**Issue by guitmart** [jean-emmanuel/open-stage-control#522]
J'aimerais savoir si cela peut se faire. Le serveur qui écouterait sur plusieurs ports.
ex:[9000, 9001, 9002].

P.S. Pour les images, tout fonctionne nickel Merci.

**Comment by jean-emmanuel** [comment]
Ce serait faisable, mais je me demande : quelle utilité ça peut avoir ?

**Comment by guitmart** [comment]
J'ai des cartes son MOTU et le logiciel qui les contrôle est Cuemix FX. Ce logiciel peut-être contrôlé par OSC. Je voulais avoir accès à tous les contrôles en même temps sauf que Cuemix limite le nombre de message OSC retourné par port. Pour réussir à faire cela je dois démarrer plusieurs instances de Open stage control par batch file et dans le custom module rediriger vers le port du OSC principale. Ça fait beaucoup de config. Je ne sais pas si ça peut-être pratique pour d'autre. Si c'est simple à implémenté se serait un nice to have. Voici un aperçu du projet
![cuemixFx](https://user-images.githubusercontent.com/28285097/57116408-f21fd980-6d22-11e9-865b-7d0d6c63d6a6.PNG)

**Comment by jean-emmanuel** [comment]
Dommage comme limitation, en tout cas avoir plusieurs instances d'o-s-c n'est pas une solution très efficace, le mieux (même comparé à une solution intégré à o-s-c) serait de faire une redirection de port (*port forwarding*), il y a des logiciels pour faire ça très simplement.

**Comment by guitmart** [comment]
Oui justement j'ai essayé de trouver un logiciel pour du port forward sur le même pc car Cuemix et OSC sont sur le même pc mais je n'ai rien trouvé de concluant. Testé avec multi port forwarder. Si tu en connais un ou un truc je suis preneur.

**Comment by cyberic99** [comment]
@guitmart tu es sur quel OS?
c'est de l'OSC en UDP?

**Comment by guitmart** [comment]
C'est sur Windows 10 et oui c'est des messages OSC en UDP.

**Comment by cyberic99** [comment]
Ha zut, sous windows je sais pas... est ce que tu peux compiler netcat pour windows?

**Comment by guitmart** [comment]
J'ai voulu télécharger NetCat et l'antivirus a poppé, perçu comme un malware

**Comment by cyberic99** [comment]
Humm... ca depend ou tu l'as pris... 
peut etre que quelqu un pourrait nous donner un lien vers une version fiable...

**Comment by jean-emmanuel** [comment]
Désolé, je n'ai pas trop le temps de suivre cette semaine, as-tu essayé d'autres logiciels, il y a l'air d'avoir pas mal de façon de le faire sous windows également : https://www.google.com/search?hl=fr&ei=ZELTXNTmE5C0Us6JpegG&q=windows+udp+port+forwarding&oq=windows+udp+port+forwarding&gs_l=psy-ab.3..0i7i30i19j0i19l2j0i8i30i19l2.14875.15932..16105...0.0..0.74.559.9......0....1..gws-wiz.......0i71j0i7i30j0i8i7i30j0i8i7i30i19.m7nvxMo_0Tk
Peut-être à essayer (trouvé parmis les résultats de la recherche) : http://aluigi.altervista.org/mytoolz.htm#sudppipe

**Comment by guitmart** [comment]
J'ai essayé avec passport et ça fonctionné, mais il a planté une fois.
Je vais tester dans les prochains jours.
Merci encore.

**Comment by guitmart** [comment]
Je vais utiliser passport alors j'annule cette feature.
Merci et good job
