### ISSUE TITLE
Dj Controller for Ableton Live 9

### ISSUE THREAD

**Issue by hiramegl** [jean-emmanuel/open-stage-control#524]
Hi, my name is Hiram and I wondered if you would like to add my project to the list of examples using Open Stage Control.

The project is called AaMakro5oul and is a controller for Ableton Live with DJ features.

Here is a screenshot:
https://raw.githubusercontent.com/hiramegl/AaMakro5oul/master/AaMakro5oul/doc/images/AaMakro5oul_Mix.jpg

There are more images at:
https://github.com/hiramegl/AaMakro5oul/tree/master/AaMakro5oul/doc/images

And the project is at:
https://github.com/hiramegl/AaMakro5oul

Let me know if there is any other information that you need.

Thx a lot for your help and for your great software!

Regards,

Hiram

**Comment by jean-emmanuel** [comment]
Wow thanks a lot for sharing, I'll definitely add it to the list :)

**Comment by hiramegl** [comment]
Thanks! :-D

**Comment by cyberic99** [comment]
Wow, this is really cool!

Your controller seems to have a lot of features, and it very wel documented, thanks for sharing this,

And the o-s-c dashboard is huge (1.7MB)

I don't know if clone widgets and matrix did exist when you started, but they could have been really useful

Are you satisfied with your touch screen? does it have multitouch?

**Comment by hiramegl** [comment]
Hi, thanks!
Yes, the dashboard is really big and I even removed some widgets and views :-)
I do not know about the clone widgets since I unfortunately had not time to continue updating to the latest version of O-S-C. I focused more on the python scripting and adding features.
I would actually like to use the latest O-S-C features and is in the roadmap but I think it might not be a small job, that is why I open source it :-)
I am satisfied with the touchscreen, according to the specifications is multitouch but the problem is that Raspbian is not, you only have one mouse cursor like any other linux distro. With that being said I actually had been pressing multiple buttons and seem to detect it, but I guess it works more with an event queue.
I also use a tablet besides my own hardware and there I have multitouch :-)

**Comment by hiramegl** [comment]
Thanks Jean-Emmanuel!

Best regards,

/Hiram
