### ISSUE TITLE
patchbay on node on raspberry pi empty

### ISSUE THREAD

**Issue by alignwaivers** [jean-emmanuel/open-stage-control#525]
First off as always, wonderful work - I'm incredibly grateful for this project!

I'm curious, is there a way of getting the patchbay to work when running via node? It's not working on my raspberry pi, but would be incredibly rad if it could. The widget shows up but no inputs or outputs show up, it's completely blank. Thanks!

**Comment by jean-emmanuel** [comment]
Thank you !

What browser (and which version) are you using to display the interface ?

**Comment by jean-emmanuel** [comment]
Closing, feel free to reopen with more informations.
