### ISSUE TITLE
[Feature] Add 'display' range for sliders

### ISSUE THREAD

**Issue by impsnldavid** [jean-emmanuel/open-stage-control#526]
Would be great to have a 'display' range for sliders. This is useful for parameters on systems which are controlled via normalised value ranges (0-1) but have a different real-world range.

This could be implemented as a 'display_min' and 'display_max' entries in the range property.

**Comment by jean-emmanuel** [comment]
This is already possible, the documentation contains an example for this use case: https://openstagecontrol.ammd.net/docs/widgets-reference/#fader_range

**Comment by impsnldavid** [comment]
I have tried the custom labels for a fader as follows:

```
{
  "min": { "0": 0 },
  "max": { "255": 1 }
}
```

Whilst this works for the min/max display on the fader range it does not change the value which is displayed under the fader, which is still in a 0-1 range.

**Comment by jean-emmanuel** [comment]
If you want the app to display something different that what's being sent you have to disable the slider's built-in input and compute the displayed value in an external input widget.

You can can use the slider's value in the input's `value` property using the [advanced syntaxes](https://openstagecontrol.ammd.net/docs/advanced-property-syntax/):
```js
JS{{
return @{fader_1} * 100
}}
```

If you need the slider to react to the input changes too, you need to write the inverse function in its `value` property too:

```javascript
JS{{
return @{input_1} / 100
}}
```

**Comment by impsnldavid** [comment]
Understood, however this is quite a time-consuming work around. In a lot of the systems I work with, nearly every parameter is configured in this manner. It would be useful to have this feature directly on the widget. 

Also from a UI perspective I think it's confusing for the end user for the displayed value to have a different range from the slider labels. It also means that the user is unable to type in a value in the correct range.
