### ISSUE TITLE
[Bug] re: #368 npm install failing

### ISSUE THREAD

**Issue by simonmcbrown** [jean-emmanuel/open-stage-control#527]
Added comment to #368 but did not realise I could not re-open.  

npm install is now failing. Any ideas? watchify is indeed missing.

Many thanks.

pi@raspberrypi:~/Downloads/open-stage-control $ git checkout $(git describe --tags git rev-list --tags --max-count=1)
Note: checking out 'v0.46.1'.

HEAD is now at fea808e... package; 0.46.1
pi@raspberrypi:~/Downloads/open-stage-control $ npm install
npm WARN deprecated cardinal-spline-js@2.3.10: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! path /home/pi/Downloads/open-stage-control/node_modules/watchify/bin/cmd.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/pi/Downloads/open-stage-control/node_modules/watchify/bin/cmd.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR! /home/pi/.npm/_logs/2019-05-18T18_50_25_955Z-debug.log

system info:
model name	: ARMv6-compatible processor rev 7 (v6l)
Linux raspberrypi 4.19.42+ #1219 Tue May 14 21:16:38 BST 2019 armv6l GNU/Linux
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"

**Comment by jean-emmanuel** [comment]
It seems the installation script fail to find the system's chmod command, is it available in your terminal ?

**Comment by simonmcbrown** [comment]
No that is not it, chmod is there.  I have done an apt-get update and retried the install.  It has got further but now have some other issues.  Can I ignore the fsevents warning and proceed to npm run build?

Thanks,

pi@raspberrypi:~/Downloads/open-stage-control $ npm install
npm WARN tarball cached data for watchify@3.11.1 (sha512-WwnUClyFNRMB2NIiHgJU9RQPQNqVeFk7OmZaWf5dC5EnNa0Mgr7imBydbaJ7tGTuPM2hz1Cb4uiBvK9NVxMfog==) seems to be corrupted. Refreshing cache.

> open-stage-control@0.46.1 postinstall /home/pi/Downloads/open-stage-control
> echo '\033[36m=> Dependencies installed successfully. Run "npm run build" to build the assets.\033[0m
'

=> Dependencies installed successfully. Run "npm run build" to build the assets.

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

added 2 packages from 2 contributors and audited 10823 packages in 210.66s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
 

I proceeded with the npm audit fix which completed fine.

**Comment by simonmcbrown** [comment]
Sorry for the delay.  I wrote it all last night and then did not press the commit button!

**Comment by jean-emmanuel** [comment]
Yes you can ignore the warnings and build :)

**Comment by jean-emmanuel** [comment]
To get into the details, the 1st attempt failed while installing a dependency that requires `chmod`, the update seem to have fixed that somehow, and the 2nd attempt worked but warned about the same dependency not being properly installed previously (`tarball cached data for watchify [...] seems to be corrupted. Refreshing cache.`),

**Comment by simonmcbrown** [comment]
I wonder if this could have been due to a dodgy internet connection during the install that lead to some corrupted files?  I'll proceed with build and report back.

**Comment by simonmcbrown** [comment]
Unfortunately it failed to build.  It seems sass is the problem. Any ideas? 

pi@raspberrypi:~/Downloads/open-stage-control $ npm run build

> open-stage-control@0.46.1 build /home/pi/Downloads/open-stage-control
> npm run build-css && npm run build-js && node scripts/copy-assets.js && echo '\033[36m=> JS and CSS assets built successfully. Run "npm run package" to build an executable or "npm start" to run the app.\033[0m
'


> open-stage-control@0.46.1 build-css /home/pi/Downloads/open-stage-control
> node scripts/build-css.js

/home/pi/Downloads/open-stage-control/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Node.js 11.x
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.11.0
    at module.exports (/home/pi/Downloads/open-stage-control/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/pi/Downloads/open-stage-control/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/pi/Downloads/open-stage-control/scripts/build-css.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! open-stage-control@0.46.1 build-css: `node scripts/build-css.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the open-stage-control@0.46.1 build-css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-05-23T17_19_33_051Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! open-stage-control@0.46.1 build: `npm run build-css && npm run build-js && node scripts/copy-assets.js && echo '\033[36m=> JS and CSS assets built successfully. Run "npm run package" to build an executable or "npm start" to run the app.\033[0m
npm ERR! '`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the open-stage-control@0.46.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-05-23T17_19_33_361Z-debug.log

**Comment by jean-emmanuel** [comment]
`Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Node.js 11.x`

Unfortunately I can't fix this, this may change in the future but until then you'll need to either use the precompiled node-only package of open-stage-control or build it from a different system. See the last two paragraphs of [this page](https://openstagecontrol.ammd.net/docs/getting-started/#running-without-electron) for running the node-only package.

**Comment by simonmcbrown** [comment]
Thanks for looking at this but I'm a bit confused as I'm not sure what you have suggested is possible.  There does not seem to be an armv6 binary (which is what the pi-zero is) and armv6 does not seem to be an option for the TARGET_ARCH ( looking at https://openstagecontrol.ammd.net/docs/getting-started/#build-from-sources)  Or have I miss understood?  Sorry to be a pain.

**Comment by jean-emmanuel** [comment]
I had overlooked your message, sorry: the only option for running O-S-C on armv6 is to use the aforementioned node package (`"open-stage-control-0.46.1-node.zip"`) which not platform dependent and only requires nodejs to run as explained in the link.

**Comment by simonmcbrown** [comment]
All is not lost.  Downgrading node to 8.12.0 (that which I used in #368) results in the build working.  Node 11.15.0 does NOT work. I do not know at which version it stopped working.

pi@raspberrypi:~/Downloads $ node -v
v8.12.0
pi@raspberrypi:~/Downloads $ npm -v
6.4.1
pi@raspberrypi:~/Downloads $ cd open-stage-control/
pi@raspberrypi:~/Downloads/open-stage-control $ npm install

> open-stage-control-builder@0.37.4 postinstall /home/pi/Downloads/open-stage-control
> cp resources/images/logo-nobadge.png app/browser/favicon.png && cp resources/images/logo.png app/browser/logo.png && cd app && npm install

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: request to https://registry.npmjs.org/fsevents/-/fsevents-1.2.4.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

up to date in 205.49s
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: request to https://registry.npmjs.org/fsevents/-/fsevents-1.2.4.tgz failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

up to date in 504.415s

pi@raspberrypi:~/Downloads/open-stage-control $ npm run build

> open-stage-control-builder@0.37.4 build /home/pi/Downloads/open-stage-control
> npm run build-css && npm run build-js && echo 'JS and CSS assets built. To build the binary package, run "npm run package".'

> open-stage-control-builder@0.37.4 build-css /home/pi/Downloads/open-stage-control
> node scripts/build-css.js

> open-stage-control-builder@0.37.4 build-js /home/pi/Downloads/open-stage-control
> npm run build-launcher-js && npm run build-browser-js

> open-stage-control-builder@0.37.4 build-launcher-js /home/pi/Downloads/open-stage-control
> node scripts/build-launcher.js > app/launcher/scripts.js

> open-stage-control-builder@0.37.4 build-browser-js /home/pi/Downloads/open-stage-control
> node scripts/build-browser.js

pi@raspberrypi:~/Downloads/open-stage-control $ node ./app --no-gui
App available at http://127.0.0.1:8080 & http://169.254.147.159:8080
