### ISSUE TITLE
Relative path to locate an image file, or embed into session json?

### ISSUE THREAD

**Issue by Roze4987** [jean-emmanuel/open-stage-control#530]
Hi all,

following tips listed in Issue #415 I achieved the result of being able to add a background image to a xy pad widget. That's okay if the image file is located on the web, but what if it's located on the hard drive?
The following code works:

```
> .pad > .wrapper:after {
background: url('C:/My/Local/File/Path/MyLocalFile.png') no-repeat;
background-size:contain;
background-position:center;
object-width=scale-down;
}
```

but only if point to MyLocalFile.png using absolute path. If I use relative path or no path at all, it searches MyLocalFile.png in C:\ root directory (I'm on a Windows PC). 
I'm really interested to use relative addressing because I would like to create a sort of "portable app" package including both my session file and all the necessary images used as backgrounds... how do you achieve such goal?

Thank you

**Comment by Roze4987** [comment]
Okay, I managed how to integrate a base64 image in the CSS property of the xy pad widget:

`url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAACXBIWXMAAAsTAAALEwEAmpwYAAAF+mlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDUgNzkuMTYzNDk5LCAyMDE4LzA4LzEzLTE2OjQwOjIyICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIiB4bWxuczpzdEV2dD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL3NUeXBlL1Jlc291cmNlRXZlbnQjIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iIHhtbG5zOnBob3Rvc2hvcD0iaHR0cDovL25zLmFkb2JlLmNvbS9waG90b3Nob3AvMS4wLyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOSAoV2luZG93cykiIHhtcDpDcmVhdGVEYXRlPSIyMDE4LTExLTI3VDIzOjAyOjMwKzAxOjAwIiB4bXA6TWV0YWRhdGFEYXRlPSIyMDE4LTExLTI3VDIzOjAyOjMwKzAxOjAwIiB4bXA6TW9kaWZ5RGF0ZT0iMjAxOC0xMS0yN1QyMzowMjozMCswMTowMCIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDpmZDQyZjM4MS1kMmNjLTYzNDQtYTkyNC1jZmM3OGQ3MjYwYjciIHhtcE1NOkRvY3VtZW50SUQ9ImFkb2JlOmRvY2lkOnBob3Rvc2hvcDozYjFhNTRhYS1iNjA3LWM2NDktODNmMC1hYjZhYmVhMzZlZDkiIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDphNjIyMjc3Ny03ODVlLTg2NGYtYmM4YS1kNDNhOWZlNDVkZjUiIGRjOmZvcm1hdD0iaW1hZ2UvcG5nIiBwaG90b3Nob3A6Q29sb3JNb2RlPSIzIiBwaG90b3Nob3A6SUNDUHJvZmlsZT0ic1JHQiBJRUM2MTk2Ni0yLjEiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJjcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOmE2MjIyNzc3LTc4NWUtODY0Zi1iYzhhLWQ0M2E5ZmU0NWRmNSIgc3RFdnQ6d2hlbj0iMjAxOC0xMS0yN1QyMzowMjozMCswMTowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTkgKFdpbmRvd3MpIi8+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJzYXZlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDpmZDQyZjM4MS1kMmNjLTYzNDQtYTkyNC1jZmM3OGQ3MjYwYjciIHN0RXZ0OndoZW49IjIwMTgtMTEtMjdUMjM6MDI6MzArMDE6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCBDQyAyMDE5IChXaW5kb3dzKSIgc3RFdnQ6Y2hhbmdlZD0iLyIvPiA8L3JkZjpTZXE+IDwveG1wTU06SGlzdG9yeT4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz4sBG7IAAAD5ElEQVR4nO3dy4uNYQDH8e+4lTRnYSE0VjZDSSKkWNgjFnZKUTIWFv4D1jZyG7cFFgqRlLJwWVlMyaVITVYsJBuDcmssXsMYZ2ae953zvs88z+/3rVlM88ycX82nOZeZOadreHgYp9uM2ANc3AxAPAMQzwDEMwDxDEA8AxDPAMQzAPEMQDwDEM8AxDMA8QxAPAMQzwDEMwDxDEA8AxDPAMQzAPEMQDwDEM8AxDMA8QxAPAMQzwDEMwDxDEC8VAH0AAeA5bGHpF5Xos8P8AJYBnwFdgK34s5Jt1QBjB79HdgG3Im0JelSvQoY3WzgOrA59pAUywEAwFzgNkZQulwAgBFUKicAYASlyw0AGEGpcgQARhBcrgDACILKGQAYwaTlDgCMYMIUAIARjFuqAD5V+BwjaFOqAH5W/DwjGFOqAKaSEYxKEQAYwZ9UAYARANoAwAjkAYA4AgMokkVgAH8bQbAx9pAmM4B/G0GwLvaQpjKA/2sBdxFBYADtk0GQKoAfDVyGBIJUAVT5ZVCVskeQKoAmyxqBAYSVLQIDCC9LBAZQruwQGED5skJgANXKBoEBVC8LBAYwtZJHYABTL2kEBtCZRhD0xh5SNgPoXC3gUOwRZUsVwOfYA3JpVuwBFfsee8CYhimuAg7HHlK2VAFMl94D536/vY68pVIGUK17QD9wE/gWd8rUMoDwPgAXgDPAYOQtHcsAJu8hxTf9OsUzk2aVAbTvM8WP+DPAq8hbas0A2jdIgvfpq5Tq4wB1txJYH3tEExnA+B2IPaCJ1AAMAQOBZ3cCC2rcMi1SATAA7AUWAdsJe4qZOcCeOkdNh1IFEPIN/AScAlYBa4HzFLfu3wI3Ai9nPzCzysBUShXA0AQfewzsAxYDfcCTNmdOBF7OEmBLqWWJlSqAp2Pe/wKcBdYAqynuv0+E5AHFy86ElPWNwVRfMqYFHAWWAteAy8DHkl+jj/CfBL1k+oBQqgA6UTfF7YHugLPHgIP1zolTqlcBnWgIuBh4djcwr74p8VIGAOFXAS1gV51DYqUO4CVwP/BsX51DYqUOAOB44LkVwKY6h8TIAIpXHX0TeDa7u4QGUDzdTH/g2R3Awhq3NJ4BFJ0l7C+NZwEbat7SaAZQ9A64GnDuB/Cs5i2NZgB/OznJxx8BW8noD0JB+5HAdg1Q/D5hpCHgEnAaeB5lUc0ZwL/1AEeA+RT3Dq6Q+b+hGYB4vg0gngGIZwDiGYB4BiCeAYhnAOIZgHgGIJ4BiGcA4hmAeAYgngGIZwDiGYB4BiCeAYhnAOIZgHgGIJ4BiGcA4hmAeAYgngGIZwDiGYB4BiCeAYj3C1hqkT+/WmQlAAAAAElFTkSuQmCC')`

**Comment by jean-emmanuel** [comment]
Cool ! Base64 is a good solution for small images, I'll try to make image paths resolve from the session file's location when possible (and fallback to absolute path).

**Comment by jean-emmanuel** [comment]
As of next version, image paths will be resolved relatively to the session directory by default, falling back to absolute resolution if  not found.

**Comment by jean-emmanuel** [comment]
-> v0.47.0
