### ISSUE TITLE
[Bug] CSS field in Tab widget modifies tabs-wrapper/tab-containers, but not tablinks

### ISSUE THREAD

**Issue by dpcb0001** [jean-emmanuel/open-stage-control#531]
Hello,

When I add custom CSS to a tab widget, the CSS is not applied to the tab (the `li` element of class tablink within the `ul` element of class tablist) but instead only applied to the divs within the `div` element of class tabs-wrapper.

I'm guessing this is intended but I would like to change the CSS of specific tabs in my tablist and I don't see how to do that with the current behaviour. Is there a workaround or am I missing something ?

Context:
I'm trying to create a sidebar menu with categories of tabs (see screenshot). Ideally, I would like the tabs which represents the categories to have the following CSS:
```
--color-bg: rgba(0, 0, 0, 0);
pointer-events:none;
```
in order to differentiate them from the "actual" tabs (named "sub" in the screenshot).

![sc_osc_sidebar1](https://user-images.githubusercontent.com/51449393/59040511-19644c00-8877-11e9-88bc-de84c0a0d6ae.png)

**Comment by jean-emmanuel** [comment]
Tablinks can only be targetted by the parent container, for example:
```css
> .panel > .navigation li:nth-child(2) a {
background:red;
}
```

**Comment by dpcb0001** [comment]
Thanks a lot, this is exactly what I was looking for. I didn't know the `>` selector existed in CSS, neither `nth-child()`. Cheers and thanks for this cool project.
