### ISSUE TITLE
Linux installation (armv8)

### ISSUE THREAD

**Issue by mrsstaceyseigle** [jean-emmanuel/open-stage-control#532]
Trying to install on raspberry pi 3 b+. I am having issues with it installing. 
armv8 process

**Comment by jean-emmanuel** [comment]
Electron doesn't provide binaries for armv8, you'll need to run the app with node : https://openstagecontrol.ammd.net/docs/getting-started/#running-without-electron

**Comment by mrsstaceyseigle** [comment]
So in order to run on Raspberry Pi with Armv8 do it require that we build
from source and create a "dist" then run headless or do we just clone from
GitHub then just run headless.

Also I notice that Raspberry Pi 3 has Armv8 processor however the system
see it as Arm7i if you run it in 32 bit mode.

**Comment by jean-emmanuel** [comment]
You can use the precompiled package that only requires [nodejs](https://nodejs.org/en/download/) to tun (the one named `open-stage-control-0.46.1-node.zip`) following the instructions in the link above.

Actually, armv8 are supported in recent versions of electron (the default engine/browser that runs open-stage-control), these processors are also called "arm64". However there are other issues with the recent electron releases so the first solution seems better.
