### ISSUE TITLE
[Bug] Labels associated with keys not displayed nor sent from knobs

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#533]
Version 0.46.1 / Windows 64.

In a knob, have pasted the Range settings from the property help but the text in quotes is not displayed as expected. Only the usual figures (here from 0. to 1.)  are displayed or sent by OSC but it is not clear in the docs whether it's for display only or not. The issue arises both in normal and compact forms.

```
{
  "min": { "-inf": 0 },
  "50%": 0.25,
  "max": { "+inf": 1 }
}
```

**Comment by jean-emmanuel** [comment]
Pips labels are never displayed in knobs, it's a mistake in the documentation, sorry.

**Comment by nesdnuma** [comment]
What is a pip?

**Comment by jean-emmanuel** [comment]
I'm referring to the marks that indicates the range values, knobs can only display visuals marks (if `pips` is set to `true`), not values/labels.

**Comment by nesdnuma** [comment]
I don't see an y visual mark linked to the example with `pip` activated. Is it normal?

**Comment by nesdnuma** [comment]
OK, it's not active in compact mode it seems.

**Comment by jean-emmanuel** [comment]
Yes, that's expected too (and documented).
