### ISSUE TITLE
Probleme gyroscope en fonction du téléphone 

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#534]
Hello Jean-Emmanuel. J'espère que tu vas bien depuis le temps. Ca fait longtemps que je n'avais pas fait un tour ici  car ton logiciel est de plus en plus parfait. Si bien que j'en parles beaucoup autour de moi et j'ai progressivement reconvertit tous mes projets ou j'utilisais lemur a open stage control! J'ai encore convertis un ingé lumière a ton logiciel le mois dernier.
Néanmoins je revenais dans le coin car j'ai repéréun soucis. Personnellement il ne me gêne pas mais je me dis que ca peut poser problematique pour certains.

En fait j'utilise la fonction gyroscope sur un galaxy S7. J'ai mis un petit temps a comprendre le fonctionnement mais une fois que c'est intégré ca marche vraiment bien.
En revanche mon telephone perso est un S9. J'ai voulu tester une fois dessus et .. ca ne fonctionne pas. Donc j'ai l'impression que sur les modèles les plus récents ca bug. J'ai fouillé un peu les issues j'ai l'impression que personne n'a encore mis le doigt la dessus.
J'ai meme poussé le vice en essayant sur une galaxy watch mais ca ne fonctionne pas non plus. Mais bon j'imagine que ca c'est un peu plus compliqué ahah

**Comment by jean-emmanuel** [comment]
Salut ! Merci pour le retour c'est cool :)
C'est toujours un peu délicat à gérer ce genre de fonctionnalité quand on a pas de smartphone ou de tablette, mais j’essaierai de trouver le problème à l'occasion.

**Comment by Adopo** [comment]
Pas de soucis ! Je m'en doutais un peu. De toute façon il y a pas d'urgence car je m'en sors avec le S7. Si jamais tu as besoin d'aide pour tester des trucs sur smartphone ou tablette ou même avec la montre dis moi !
Comme ton truc est bien faire tu peux même mettre des tests sur serveur et je peux tenter d'y acceder voir si ca fonctionne.

**Comment by jean-emmanuel** [comment]
Depuis la version 74 (avril 2019), chromium n'autorise plus l'accès à cette API si l'application n'utilise pas le protocole https. Le souci c'est que passer o-s-c en https pose un gros problèmes pour le déploiement du logiciel car cela impliquerait d'ajouter une étape technique à l'installation pour les utilisateur (génération des clés permettant l'établissement du protocol sécurisé). Cette fonctionnalité sera retirée donc dans la prochaine version (v1), en espérant qu'elle puisse être réintroduite plus tard si je trouve un compromis raisonnable dans tout ça.

**Comment by Adopo** [comment]
Arf mince. Est ce possible de la laisser au cas ou pour le moment? Car je l'utilise sur un projet et je dois revérifier mais a priori ça fonctionne sur Firefox.

**Comment by jean-emmanuel** [comment]
À priori pas dans la prochaine version du coup, mais il n'y aucune obligation à changer de version cela dit..

**Comment by Adopo** [comment]
Ok d'accord. Donc pour le moment pour ce projet je ne mets plus rien à jour. Merci pour tout le temps investi

**Comment by jean-emmanuel** [comment]
La dernière version de la branche v0 est sortie, pour la suite ce sera sans gyroscope jusqu'à nouvel ordre.
