### ISSUE TITLE
oscquery

### ISSUE THREAD

**Issue by dewiweb** [jean-emmanuel/open-stage-control#535]
It could be a nice feature to implement oscquery on open-stage-control....

**Comment by jean-emmanuel** [comment]
You mean having o-s-c generating an interface on the fly according to an oscquery response ? That's not gonna happen, interpreting an oscquery response to create a *usable* interface requires a per-application implementation. O-s-c exposes some commands that allow editing/creating an interface programmatically, but the oscquery part is out of its scope and could constitute a whole different project.
