### ISSUE TITLE
adjust header tab width (nav)

### ISSUE THREAD

**Issue by mrsstaceyseigle** [jean-emmanuel/open-stage-control#536]
Is there a way to change the header width size for each tab. 
![header](https://user-images.githubusercontent.com/43449594/59701592-f36a7000-91c3-11e9-9579-f09fb451b418.png)

**Comment by jean-emmanuel** [comment]
You can write something like this in the container's `css`:
```css
> .panel > .navigation li:nth-child(1){
min-width:60%;
}
> .panel > .navigation li:nth-child(2){
min-width:30%;
}
/* etc */
```

Please use the forum for general support, the github tracker is only for bugs report and feature requests.
