### ISSUE TITLE
How to set a switch default value to the first index, not knowing the actual values

### ISSUE THREAD

**Issue by dpcb0001** [jean-emmanuel/open-stage-control#537]
Which expression to use in order to set a switch default value to the first index, no matter what values the switch is currently holding ? I don't really care if the values are not sorted, I just need one to be selected. In my case the switch is never empty since its values are set by an external script which rewrites the .json file.

**Comment by jean-emmanuel** [comment]
Hi, please post your request on the forum, this tracker is for bug reports and feature requests only.
