### ISSUE TITLE
[Bug] problem with button Widget and text

### ISSUE THREAD

**Issue by mrsstaceyseigle** [jean-emmanuel/open-stage-control#538]
When using the button widget, if you put a string in the label section it displays in the button however for longer strings the button width does not expand and you can not see the full text. 

I have the button widget width set to auto 
I tried to adjust the text font-size however do not want the text to small. For some reason I believe this is a bug because the button width will not increase automatically using width= auto

![see](https://user-images.githubusercontent.com/43449594/59984293-73466f00-95f6-11e9-999a-ab9c4fa4e6e8.png)

**Comment by jean-emmanuel** [comment]
The button should not grow, it is the expected behavior. You can can force lne-wrapping by adding this to the css: 
```css
.label {
  word-break: break-all;
  white-space: normal;
}
```
