### ISSUE TITLE
[Bug] Can't create account at discourse

### ISSUE THREAD

**Issue by mbutz** [jean-emmanuel/open-stage-control#539]
Hi,

sorry for filing an issue here, but I don't know how else to let you know:

I tried to create an account at: http://openstagecontrol.discourse.group

I got the confirmation email, clicked the link (will not post this here because I supect it somehow related to my registration data) and got to a page with a button "Click here to create account". Then I was redirected to a page showing only an unformated error message:

```
["BAD CSRF"]
```

I can't start another registration process unless I choose another username (because oviously there is already some entry of the one I provided in discourse's database). Please let me know what I can do.

**Comment by jean-emmanuel** [comment]
Does it work with HTTPS version ? https://openstagecontrol.discourse.group/

**Comment by nlebellier** [comment]
Hi @mbutz 

it seems you use a proxy right ?
https://meta.discourse.org/t/help-cannot-login-error-shows-bad-csrf/52424

**Comment by mbutz** [comment]
Hi,

changed the protocol on the 'create-account'-page to `https`. This did work. Thank a lot!
