### ISSUE TITLE
How to disable the Bult-in Editor?

### ISSUE THREAD

**Issue by dosida** [jean-emmanuel/open-stage-control#54]
Hey guys,

OSC looks very very promising. How does one disable the built-in Editor (and use only the widgets that they built)?

**Comment by jean-emmanuel** [comment]
Hi, thanks for your interest in the project !

Currently the editor can't be disabled, but I could add a command-line switch for that, something like `--disable-editor`. I'll

**Comment by jean-emmanuel** [comment]
(read previous message, on github, I sent it unfinishd by mistake...)

**Comment by dosida** [comment]
Awesome I'll look forward to your next release :)

**Comment by jean-emmanuel** [comment]
Here it is: https://github.com/jean-emmanuel/open-stage-control/releases/tag/v0.17.2
See `--read-only` in the [documentation](http://osc.ammd.net/getting-started/).

**Comment by jean-emmanuel** [comment]
Ahem, v0.17.2 was replaced by [v0.17.3](https://github.com/jean-emmanuel/open-stage-control/releases/tag/v0.17.3) ;)
