### ISSUE TITLE
[Bug] Midi some devices are not recognized 

### ISSUE THREAD

**Issue by mrsstaceyseigle** [jean-emmanuel/open-stage-control#540]
There seem to be a bug with the midi feature. After following the instruction from the documentation  I notice that some midi devices are not recognized.

Any device that has "spaces" in their names will fail. The device name will print in the debug section of the console, however when sending a midi command they will fail to stream. 

Example:
Midi device:    GrandMidi
This will work

Midi device:  The Grand Midi
This will show in the debug console but will fail. 

Midi Device: LoopBe1 Internal Midi
This will fail because the name has spaces

Midi Device: loopmidi
This will work because no spaces are in the name

This happens with virtual midi ports and hardware midi devices

**Comment by jean-emmanuel** [comment]
The device name set in the config is just a convenience, you can use any string you want as long as it does not contain spaces, it doesn't have to match the actual device's name what actually matters are the numbers after.

**Comment by mrsstaceyseigle** [comment]
I understand but is still seam to have bug. When I put the device name in the target section, if the midi device weather its virtual driver or real hardware controller. If the device name has an space in the name it will not work. It only works with devices that do not have spaces in there device name

**Comment by mrsstaceyseigle** [comment]
Here is a video of what I am experiencing. I think I might be a bug. We have to figure out how to use midi device that have spaces in there names. 

video link:
https://drive.google.com/open?id=1VJY4uspfGrYF-fjnRrPq76L6ell8JDGU

[https://drive.google.com/open?id=1VJY4uspfGrYF-fjnRrPq76L6ell8JDGU](url)

**Comment by jean-emmanuel** [comment]
As I said, you just need to remove the spaces from the device name in the midi config and in the widget's `target` property.

**Comment by jean-emmanuel** [comment]
In next release it will be possible to write spaces in the name if the device declaration is enquoted (ie `"device name:1,2"`), there was a bug preventing this to work. It doesn't change the fact that you don't need to write spaces in the the device name, you can write anything really, only the numbers are relevant.

**Comment by jean-emmanuel** [comment]
The aforementionned bug is fixed in v0.47.0 and the documentation has been updated to explain the role of the `device_name` variable.
