### ISSUE TITLE
[Bug] button is not released if there is heavy widget changes on press

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#543]
o-s-c version 1e9e2a4ca8f25391ab2b0a671daaf570cae9a275

(I wanted to test on latest master, but unfortunately there seem to be a regression regarding zeroconf... I'll report on it later)

I'll try to explain:

This happens on my main PC, on debian, with the elctron app:

I have a push button

When I push it, several widgets are created/updated on o-s-c, and so the gui freezes a little

when I release the mouse button, the ``release`` value is sometimes not sent...

I had noticed a similar beheavour on a tablet, where the button seemed 'stuck' sometimes.. it still looked depressed even after I release it

If this is not clear enough, I can record a video

**Comment by jean-emmanuel** [comment]
That's clear enough, but I'll need need youd to confirm it happens on latest release, I don't backport fixes ;)

**Comment by cyberic99** [comment]
> but unfortunately there seem to be a regression regarding zeroconf...

I did see a regression regarding zeroconf, when upgrading o-s-c from 0.45.4 to 0.47.1:
The info retrieved with zeroconf was sometimes ``None``, and it was taking up to 3s.

But I also noticed that the python lib I was using (python-osc) was not up to date. I upgraded from 0.19 to 0.23 and it fixed this zeroconf issue.

So now, I was able to test my push button scenario again with latest master, and I can still reproduce it.

**Comment by jean-emmanuel** [comment]
Thanks, I'll dig that.

**Comment by jean-emmanuel** [comment]
The problem was that your heavy editing triggered the button's recreation at some point, from now on push buttons will be forced to release when this happens to prevent stuck values. There's is still a drawback to editing a button while it's pressed: you can't choose when to release it.

**Comment by jean-emmanuel** [comment]
included in v0.47.2

**Comment by cyberic99** [comment]
> your heavy editing triggered the button's recreation at some point

I guess so, but I think it shouldn't have...

I'll try to find a small repro case, because I can't understand why the editing triggered a recreation...

Thx anyway for the workaround, I'll test it soon
