### ISSUE TITLE
[Bug] OSC ne reçoit pas les messages sysex

### ISSUE THREAD

**Issue by guitmart** [jean-emmanuel/open-stage-control#544]
Je suis sur windows 10 64bits avec OSC version 4.7. OSC ne reçoit pas les messages SYSEX midi.
Pour tester j'ai ajouté dans un custom module un receive sysex mais dans la console de debug je n'ai aucun message sysex.
![nosysex](https://user-images.githubusercontent.com/28285097/61263219-19991680-a756-11e9-9aa4-4eef54bc4b29.PNG)

P.S. J'ai l'impression que c'est dans le fichier midi.py car il n'entre pas dans le if debug
Merci encore pour ton super logiciel

**Comment by jean-emmanuel** [comment]
Salut, le sysex est désactivé par défaut, il faut ajouter le mot clé `sysex` dans l'option `midi` pour l'activer. https://openstagecontrol.ammd.net/docs/midi/#setup

**Comment by guitmart** [comment]
Super merci je ne l'avais pas vu
 it accepts the following options (separated by spaces):
sysex: parse incomming system exclusive messages (disabled by default)
