### ISSUE TITLE
[Bug] using keys with a client browser launches browser dialogs

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#547]
I use o-s-c v0.47.3, with a chromium 75 client on linux.

I have configured keys to use ctrl+d or ctrl+p.

When I press ctrl+d, the browsers asks me to add a bookmark.

And with ctrl+p, it opens the print dialog.

Is there any way to prevent this?

Thx

**Comment by jean-emmanuel** [comment]
fixed in git !
