### ISSUE TITLE
Widget interaction

### ISSUE THREAD

**Issue by dosida** [jean-emmanuel/open-stage-control#55]
How do we get widgets to interact with each other (for example a meter and a fader)?

And how can we interact with the widgets hosted on one app server to the other?

For example if I have a temperature sensor how can it send data to a meter widget on a server?

Could you please provide examples? If already there can you point to it, or some documentation?

**Comment by jean-emmanuel** [comment]
On client's side, widgets interact with each other this way:

- if sharing the same [`id`](http://osc.ammd.net/user-guide/widgets-generics/#id), they will update each other without sending extra osc messages
- if sharing the same [`linkId`](http://osc.ammd.net/user-guide/widgets-generics/#linkId), they will update each other (updated widgets will send osc messages normally)
- some widgets can explicitly register to other widgets' value updates, like the [visualizer](http://osc.ammd.net/user-guide/widgets-specifics/plots/#visualizer)

Now that I'm writing it, I see it can be a bit confusing. Initially, the same-`id` update was meant to handle identical widgets in different tabs. Relaying on that feature for widgets like `meter` doesn't seem reasonable, and will be fixed soon by adding a [`widgetId`](http://osc.ammd.net/user-guide/widgets-specifics/plots/#widgetid)-like option where missing (meter, for instance).

Now, over the networks it works this way: widgets that send osc respond to messages with the same osc [`address` and `preArgs`](http://osc.ammd.net/user-guide/widgets-generics/#address).  Basically, if you have a meter with `/meter` for address and no `preArgs`, you'd send `/meter VALUE` on the app's osc port (see [getting-started](http://osc.ammd.net/getting-started/#run-from-binaries))  

Clients connected to the same server are also synchronized this way except [`target`](http://osc.ammd.net/user-guide/widgets-generics/#target) must also be identical for widgets to update each other.

**Comment by jean-emmanuel** [comment]
Here is a very basic example: https://gist.githubusercontent.com/jean-emmanuel/601974888af52856a198dd7d8a2e2d35/raw/0a3405546858a9f4276333970824560250831a6b/meter-example.js
The two widgets have the same `id`. Sending `/fader VALUE` or `/meter VALUE` will update them both.

**Comment by jean-emmanuel** [comment]
`widgetId` option has been added to the `meter` widget in v0.17.2: https://github.com/jean-emmanuel/open-stage-control/releases/tag/v0.17.2
See `meter` the [documentation](http://osc.ammd.net/user-guide/widgets-specifics/plots/#meter).

**Comment by jean-emmanuel** [comment]
Ahem, v0.17.2 was replaced by [v0.17.3](https://github.com/jean-emmanuel/open-stage-control/releases/tag/v0.17.3) ;)
