### ISSUE TITLE
[Bug?] Modal display:flex

### ISSUE THREAD

**Issue by iddqdosc** [jean-emmanuel/open-stage-control#552]
Hello! If I set the CSS of a panel to `display:flex` (I'm using flex-wrap to position a bunch of widgets) all the modal widgets inside the container seem to bug out:

![modalflex](https://user-images.githubusercontent.com/53092484/62413218-9e53b380-b5e3-11e9-9d1f-c7563af1e5b1.png)

As you can see, instead of being closed, the modal button shows the content of the modal window. Is this a bug or am I doing something wrong? Steps to reproduce:

Empty project;
Add a modal container;
Add a button inside the modal container;
CSS of the tab including the modal:

```
.panel {
display:flex;
flex-wrap: wrap;
}
```

Result:

![modalflex](https://user-images.githubusercontent.com/53092484/62413218-9e53b380-b5e3-11e9-9d1f-c7563af1e5b1.png)

Another example:

![modalflex2](https://user-images.githubusercontent.com/53092484/62413385-cabbff80-b5e4-11e9-9316-8435b922dff3.png)

It also happens with `display:grid` .Cheers!

**Comment by jean-emmanuel** [comment]
You need to use the `> .panel` selector otherwise the css rule will affect all matching elements in the widget.

**Comment by iddqdosc** [comment]
Thank you so much, Jean. Still banging my head on the wall, you've been a saint!
