### ISSUE TITLE
[Bug] Scrollbars displayed at startup even if no contents overrides screen size

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#553]
Hello Jean-Emmanuel,

This is a very minor bug, but still I report it in case it could be easily removed. Otherwise forget about it.

This happens in v 0.47.3 under Windows 10 x64 but I think it has been there for long.

When I set a window to full screen, at first both vertical and horizontal scrollbars are displayed even if the contents doesn't override the window size. It's not hard to make disappear however: one has just to push on any widget partly hidden by the horizontal scrollbar.

Best regards,

Roald

**Comment by jean-emmanuel** [comment]
I'm not sure how to reproduce/fix the issue, it might just be a chromium bug, does it occur when accessing the app with an external chome instance ?

**Comment by nesdnuma** [comment]
Oh. I've never tried the app with a browser.

**Comment by jean-emmanuel** [comment]
Have you had a chance to try ?

**Comment by nesdnuma** [comment]
Sadly no, I am entering my year's most busy period at my workplace, it will last till end of october.

**Comment by jean-emmanuel** [comment]
Okay, no hurry ;)
