### ISSUE TITLE
[Feature] Send an event on input validation even if the value remains unchanged

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#554]
Hi

I have an input widget.

I'd like it to send some OSC every time I press ``enter`` in it, even if the input value didn't change.

Would it be possible to implement this as an option?

Thanks

**Comment by jean-emmanuel** [comment]
This is already the default behavior.

**Comment by cyberic99** [comment]
Ha yes you're right.

My tests were using linkIds and somehow prevented a repeated value to be sent several times.

Sorry for the noise

**Comment by jean-emmanuel** [comment]
No problem!
