### ISSUE TITLE
OSC sending / receiving behaviour discussion

### ISSUE THREAD

**Issue by dosida** [jean-emmanuel/open-stage-control#56]
OS: Debian Jessie 8.7 64bit
RAM: 12GB
CPU: Intel i7
Desktop Environment: MATE 1.8.1
Hardware: HP Envy 17-j070ca
OSC Server: v0.17.1
Symptom: Starting the server from the applications -> Accessories menu, Setting port 9911 and osc-port to 9922 and clicking on the Start button to get the server running. Nmap confirms port 9911 is open but port 9922 is reported as closed.No synch ports are being setup, 

Am I missing something? a dependency or a setting perhaps?

**Comment by jean-emmanuel** [comment]
By default nmap scans for port using the TCP protocol, osc uses UDP, you can use nmap's `-sU` switch to perform an UDP scan. Alternatively, to check wether Open Stage Control receives osc correctly or not, you can run it from a terminal with the `debug` option and send some message to its osc port:

```
open-stage-control --debug --port 9911 --osc-port 9922

# from another terminal
# you might need pyliblo-utils (command line tool for sending / receiving osc from the terminal
# sudo apt install pyliblo-utils
send_osc 9922 /lets/test 1

# the first terminal should display something like "OSC received:  { address: '/lets/test', args: ..."


```

**Comment by dosida** [comment]
send_osc works great. Thanks. Manpages also showed me that there's dump_osc. However when I run it like this: dump_osc 9922
it gives me this: server error -8: Servname not supported for ai_socktype

Is this because I am already using 9922 in OSC? If so how would I run it to get the data that is coming up?

The reason I'm looking into this is because I'm thinking about linking widget results with other servers such as a Node-Red server so I can trigger several programs firing (for example playing an audio warning message if a widget value is above a certain value) or just send a push notification to an android phone.

jean-emmanuel this is an awesome piece of software :100: :+1: Great work :) Keep it up :)

**Comment by jean-emmanuel** [comment]
> Is this because I am already using 9922 in OSC? If so how would I run it to get the data that is coming up?

Maybe, you can't have two listeners on the same osc.udp port, although in that case dump_osc's error should be `server error 9904: cannot find free port`.

I might be wrong, but it seems you are not correcly interpreting the `--osc-port` option: it is meant for Open Stage Control to listen on the port for osc messages that will update widget's value (feedback). The actual output port of the widgets is defined through their [`target`](http://osc.ammd.net/user-guide/widgets-generics/#target) option, and/or with the `-s / --sync` command line switch.

However, if you want to filter the osc messages that Open Stage Control sends and receives, you might be interested in the built-in [custom module](http://osc.ammd.net/user-guide/custom-module/) solution, which gives some hacking possibilities.

**Comment by dosida** [comment]
jean-emmanuel, you were right. I thought  --osc-port was the way to go but the sync port was what I needed. However I noticed that data goes through the sync port only if there is a change when one of the controls changes on the gui but data is not sent to the sync port when you change a control from the send_osc command. Another thing I noticed is that there is no target property for meters or other controls like labels etc etc. Is that by design? Could there be a target property for this kind of controls?

**Comment by jean-emmanuel** [comment]
`--sync` was meant to act as a default `target` for widgets that send osc. Updating a widget's value through osc is considered as a feedback for visual update, not as a user physical input that triggers osc sending. I'm considering adding two commands to make this possible, something like this:

Set a widget's value and make it send it's value:
`/SET /widgets/osc/address [preArgs] value`
`/SET widget_id [preArgs] value`

Get a widget's value (make it send it's value):
`/GET /widgets/osc/address [preArgs]`
`/GET widget_id`

Does that seem like a good solution ?

Plots (meter, etc) don't have a target option because they can't be interracted with directly and therefore cannot send osc. However, if the previous solution were to be applied, it would then make sense for these widgets to have a target option of course.

**Comment by cyberic99** [comment]
I think the GET command is a great idea to poll the state of the widgets.

FAUST have this kind of ability, and can also do some 'introspection' and use wildcards for widget names:
https://ccrma.stanford.edu/~jos/aspf/Using_FAUST_Open_Sound.html

You can do for instance 
`oscsend localhost 5510 /noise/Volume s "get"` to get the current volume value
or `oscsend localhost 5510 '/*' s "get"` to get the values of all widgets

**Comment by SirSickSik** [comment]
HI,
I'm trying to get the OSC data into Puredata, but Puredata gives me a 10.013 error:
"udpreceive: bind: An attempt was made to access a socket in a way not permitted by the access permissions. (10013)".
If I load Puredata before the open stage control, it doesn't give the error, but also no data is being send either..
So somehow it seems Puredata cannot listen to the port of OSC when that one is using it..
Does anyone have a clue what I could be doing wrong?

**Comment by SirSickSik** [comment]
ps. I've checked and neighter my firewall nor my antivirus is blocking the programs..

**Comment by jean-emmanuel** [comment]
You're probably trying to listen to Open Stage Control's input port (the one you can send messages to to update the interface, by default it's the same as the http port used to access the interface with a web browser), it's not possible to do so. You should make puredata listen to another port (chose one, say 5555 for example) and do one of the following : 
-  launch O-S-C with the `--sync` option to `127.0.0.1:5555`. This will make all your widgets send to port 5555 on the computer that runs the server (see [docs](http://osc.ammd.net/getting-started/#options))
- set the widgets' `target` option to  `[ "127.0.0.1:5555" ]. That only useful if you have multiple targets, if not better use the first option.

**Comment by jean-emmanuel** [comment]
@SirSickSik's issue moved to #100

**Comment by cyberic99** [comment]
@jean-emmanuel  do you still plan to implement /GET?

**Comment by jean-emmanuel** [comment]
I'm studying the case ;)

**Comment by jean-emmanuel** [comment]
I just pushed a first implementation of the `/GET` osc method. For now every client will respond, which may lead to duplicate answers from O-S-C. Wildcard support is not to be expected anytime soon...
```
/GET ip:port /widgets/osc/address preArg1 preArg2 ...
/GET ip:port  widget_id
```

**Comment by cyberic99** [comment]
Thanks for the /GET!
I just tested it.

I have a widget that have this address:
`/0x00/EQ/hi/gain` (yes I know, 0x00 is strange, but it is like this for now)

When I do a:
`send_osc osc.udp://localhost:8080 /GET 127.0.0.1:5555 /0x00/EQ/hi/gain`

I get a proper reply.

But I also have a text widget at address /hello
When I do a `send_osc osc.udp://localhost:8080 /GET 127.0.0.1:5555 /hello`, I get:

```OSC received:  { address: '/GET', args: [ '127.0.0.1:5555', '/hello' ] } From : 127.0.0.1:58032
A JavaScript error occurred in the main process: Uncaught Exception:
TypeError: Cannot read property 'indexOf' of undefined
    at Object.sendOsc (/data/od/open-stage-control-git/app/main/callbacks.js:194:28)
    at Socket.socket.on (/data/od/open-stage-control-git/app/main/server.js:54:32)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at /data/od/open-stage-control-git/app/node_modules/socket.io/lib/socket.js:513:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
(line numbers might differ a bit because I have added some more debug)

And another question:
When I try to /GET a panel or a tab, all I get back is `/tab_2 i -1`

I was expecting to get a jsonified content, that I could  put back with a /SET

Thank you for your work!

**Comment by cyberic99** [comment]
Edit: You can discard the last question... I mean `/EDIT`, not `/SET`.
And I realize that `/GET` and `/EDIT` are completely unrelated, and that is better this way ;-)

**Comment by jean-emmanuel** [comment]
Cool !

> When I do a send_osc osc.udp://localhost:8080 /GET 127.0.0.1:5555 /hello, I get [...]

This one is due to the fact that this widget, among others, don't have a `target` property. I just pushed a fix to prevent the error and allow the /GET to execute.

**Comment by jean-emmanuel** [comment]
> When I try to /GET a panel or a tab, all I get back is /tab_2 i -1 [...]

A panel's value (tabs are panel widgets within panels) is just the index of it currently selected tab (-1 if none).

> And I realize that /GET and /EDIT are completely unrelated, and that is better this way ;-)

Yep, but a `/GET_DATA` or `/EDIT_GET` could be added to fill the gap !

**Comment by cyberic99** [comment]
> A panel's value (tabs are panel widgets within panels) is just the index of it currently selected tab (-1 if none).
Ha, right. That makes sense and knowing the currently selected tab can be useful.

> Yep, but a /GET_DATA or /EDIT_GET could be added to fill the gap !
Why not ;-)
That would allow an external program to get current layout or a part of the widgets layout, then process it (using for instance a template language), and reinject it using /EDIT

**Comment by jean-emmanuel** [comment]
[`/EDIT/GET`](https://github.com/jean-emmanuel/open-stage-control/blob/master/resources/docs/extras/remote-control.md#editget-target-id) is in master. I've changed [`/GET`](https://github.com/jean-emmanuel/open-stage-control/blob/master/resources/docs/extras/remote-control.md#get-target-id) to make it reply to the same address, it makes more sense to differentiate this from a message triggered by user interaction.

**Comment by jean-emmanuel** [comment]
I'm closing the issue since the main part of the topic has been covered, please feel free to open new issues.

**Comment by cyberic99** [comment]
Hello and thanks again!
I tested /EDIT/GET on demo example file, with latest git (83e338a1).
With 
```
send_osc osc.udp://localhost:8080 /GET 127.0.0.1:7777 /multitoggle
```
I get the expected answer on port 7777:
```
/GET sffffffff "/multitoggle" 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
```
But with
```
send_osc osc.udp://localhost:8080 /EDIT/GET 127.0.0.1:7777 /multitoggle
```
with --debug I get the confirmation that o-s-c has received the OSC:
```
OSC received:  { address: '/EDIT/GET',
  args: [ '127.0.0.1:7777', '/multitoggle' ] } From : 127.0.0.1:35003
```
But I get no response...

I can open another issue if you prefer

**Comment by jean-emmanuel** [comment]
`/EDIT/GET` did not support targetting widgets by address/preArgs, now it does. See [docs](https://github.com/jean-emmanuel/open-stage-control/blob/master/resources/docs/extras/remote-control.md).
