### ISSUE TITLE
[Weird chrome behaviour]  min font size in chrome mess the css layout of o-s-c

### ISSUE THREAD

**Issue by MartinHN** [jean-emmanuel/open-stage-control#564]
Hi just for reference,
(Im on Chrome 77 OSX)

I recently had every single html pages served by o-s-c with a huge scale and layout distortion
I finally discovered that min-font-setting in chrome preference was set to 6px
I can't remember if I played around with this setting once in my life, I just hope that its not a default setting that came from upgrading chrome

to be precise, the bug is that even fixing a \<html\> font-size to 1px will stay at 6px then mess everything up with rem calculations in css styles.

Just noticing, feel free to close this Bug Report

Thanks again

**Comment by jean-emmanuel** [comment]
Yeah, this was caused by a bug in chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=944002), many web apps had problems because of it !
