### ISSUE TITLE
[Bug] dropdown widget ends the full screen mode (iOS)

### ISSUE THREAD

**Issue by amkdev** [jean-emmanuel/open-stage-control#567]
The use of dropdown widgets ends the full screen mode on iPad

Open Stage Control Version 0.47.4
Tested on iOS 12 and 13 beta on an iPad Pro second gen 12.9"

**Comment by jean-emmanuel** [comment]
The dropdown and the fullscreen features both rely on native implementation so I'd say it's an iOS bug. Do you enter fullscreen using sidepanel button or by adding the app to your home screen ?

**Comment by amkdev** [comment]
I enter fullscreen via the OSC's sidepanel.

**Comment by jean-emmanuel** [comment]
The `menu` widget (coming in next release) will provide an alternative to this widget that doesn't trigger this bug.
