### ISSUE TITLE
[Question] Close modal with button

### ISSUE THREAD

**Issue by git-moss** [jean-emmanuel/open-stage-control#569]
I would like to close a "modal" with a button, which is inside the modal (Cancel, OK). How can I achieve that?

**Comment by cyberic99** [comment]
This solution works for me: https://github.com/jean-emmanuel/open-stage-control/issues/226

Doesn't it work for you?

**Comment by git-moss** [comment]
Ups, seems I forgot about that.
However, it works fine in the the test but conflicts with the OSC action executed in my button. Need to test a bit more.
Any idea how to extend that to 2 buttons (Cancel and OK)?

**Comment by jean-emmanuel** [comment]
Hi, here is a session file with two examples:
- modal_1 uses the solution from #226, but with the JS syntax
- modal_2 contains a script widget that monitors the button's values and closes the popup (by setting its value to 0) when on is pushed.

Also please use the forum for usage questions ;)
https://openstagecontrol.discourse.group/

**Comment by git-moss** [comment]
Many thanks! modal_2 works fine!
