### ISSUE TITLE
Feature request: user definable qwerty keyboard bindings

### ISSUE THREAD

**Issue by shimpe** [jean-emmanuel/open-stage-control#57]
Hi, thanks for writing this most interesting program!

Would it be possible (or is it perhaps already possible?) to allow defining (qwerty, not midi) keyboard bindings to widgets, which, in combination with multiple simultaneous key press detection, would turn my qwerty keyboard into a midi control surface on which I can operate  multiple sliders/knobs/buttons simultaneously. (I do not have a mobile device, and using the mouse it's not possible to operate more than one control simultaneously (and it's also difficult not to hit the wrong control at times...)

I imagine e.g. presssing letter "r" to move a fader up, and letter "f" to move that same fader down again, or assigning single keyboard keys to toggle button widgets. 

I have no idea how easy or difficult providing such feature would be, but as far as I'm concerned it'd be a killer feature! I was contemplating making something myself, but seeing how far you've come already, it' d probably take me "forever" to reach a similar level of functionality.

Detecting multiple simultaneous keypresses in itself seems to be quite doable by the looks of this stackoverflow entry: http://stackoverflow.com/questions/5203407/javascript-multiple-keys-pressed-at-once

**Comment by jean-emmanuel** [comment]
I'll dig the idea, I plan to add some keyboard shortcuts to the editor someday so this might just be part of this upcoming work. Thanks to [keyboardjs](https://www.npmjs.com/package/keyboardjs) it souldn't be too hard to code ;)

**Comment by jean-emmanuel** [comment]
The feature is almost here : the `keys` widget has been pushed to git for testing ;).

**Comment by jean-emmanuel** [comment]
See unpublished docs : https://github.com/jean-emmanuel/open-stage-control/blob/master/resources/docs/widgets/inputs.md#keys.

**Comment by jean-emmanuel** [comment]
I added `keys.json` as an example, you can try it with the online demo : http://openstagecontrol.herokuapp.com

**Comment by shimpe** [comment]
Very nice! 

However, in the online demo I see one unexpected behaviour: if I press the R key ("slider up"), and keep it pressed down, then while R pressed down, press any other unassigned key (e.g. H or J), it will move the slider down. This may lead to unintended parameter changes.

**Comment by jean-emmanuel** [comment]
It only happens when the `repeat` option is set to true, gotta 
investigate on that.


Le 31/12/2017 à 15:53, shiihs a écrit :

**Comment by jean-emmanuel** [comment]
Issue reported upstream : https://github.com/RobertWHurst/KeyboardJS/issues/133

**Comment by jean-emmanuel** [comment]
Untill my PR gets merged upstream if it does, o-s-c will be packaged using a patched version of KeyboardJS to address this issue.

**Comment by jean-emmanuel** [comment]
Included in v0.23, cheers !

**Comment by shimpe** [comment]
Thanks!
