### ISSUE TITLE
Blank window on MacOS

### ISSUE THREAD

**Issue by btownshend** [jean-emmanuel/open-stage-control#570]
Open Stage Control was previously working on my computer, but now the main screen is always b blank.   I launch from the app (0.48.0) and the control panels opens correctly, but after I click start (and after "Allow" for the accepting network connections) the new window is completely black.  This is true with all the settings at default or when pointing to my previously working .json file. 

MacOS 10.14.6

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/2666663/67344267-6f672280-f4ec-11e9-9991-562562d6fb9a.png">

**Comment by jean-emmanuel** [comment]
Hi, can you hit F12 in the blank window and check for error messages in the console that should appear ?

**Comment by btownshend** [comment]
That seems to drop into the Chrome debugger, but no error messages visible or on console:

**Comment by jean-emmanuel** [comment]
Once in the debuger, can you hit ctrl+r (or cmd+r, I'm not sure) to refresh the connection and see if anything prints ? Have you tried accessing the app with an external chrome instance ?

Was it previously working on the same version ? Did you update your system somehow ?

**Comment by btownshend** [comment]
It looks like the content of the page is just “SUCCESS”, no errors.  


Connecting from the Chrome Browser just shows a window with the word “SUCCESS”.


This was all working on this computer a few months ago, but since then there may have been some minor upgrades of MacOS.   When it stopped working I was running OSC 0.46, but upgraded to 0.48 to see if that helped (which it didn’t).

Brent

**Comment by btownshend** [comment]
That was it!   Not sure what was using 8080, but I’ll find out.   Odd though that OSC doesn’t give an error when it tries to serve on 8080 if another process is listening on that port.

Brent

**Comment by btownshend** [comment]
Was a lightroom plugin, photosmith, that runs a server (psahttp) on port 8080.

Brent

**Comment by jean-emmanuel** [comment]
Great !
Yes, that's odd, an error should have been raised, it does when I attempt to launch two instances of o-s-c on the same http port (with different osc ports, because this would also raise an error).

**Comment by btownshend** [comment]
It looks like o-s-c opens both a UDP and TCP port on 8080, whereas psahttp opens only a TCP port —just a thought, maybe your code is picking up a conflict on the UDP open (which is why it flags an error if two instances are started), but not during the TCP open?

Brent

**Comment by jean-emmanuel** [comment]
I started both applications with the same TCP port (`port` option, used of http) but with different UDP ports (`osc-port` option, used for osc messages) to make sure it wasn't the case :).

**Comment by jean-emmanuel** [comment]
Listening on the same port using different protocols (udp / tcp) works fine, other the app would not have worked in the first place.

**Comment by btownshend** [comment]
I’m fine now, and we can close this issue, but if you’d like to debug the missing error message, I can send you the (MacOS) binary for psahttp if it would help to replicate the situation.

Brent

**Comment by btownshend** [comment]
And it looks like psahttp uses the mongoose embedded web server (https://github.com/cesanta/mongoose <https://github.com/cesanta/mongoose>).   Not sure if there is anything special about how it opens 8080 that results in different symptoms compared to multiple copies of o-s-c, though I can’t imagine what that would be...

Brent

**Comment by btownshend** [comment]
No problem.   FYI, I just tried running two copies of o-s-c with different OSC ports and I do indeed see the EADDRINUSE error for the 8080 listen, but don’t see any error when starting o-s-c while psahttp is running.

Brent

**Comment by jean-emmanuel** [comment]
Starting with next release, this error will no longer be hidden.
