### ISSUE TITLE
[Bug] Patchbay does not respond to OSC commands after outputs have been altered

### ISSUE THREAD

**Issue by DjTuxeedo** [jean-emmanuel/open-stage-control#571]
Hey There,
I'm trying to control a patchbay with osc-messages from Super collider.
It works fine until I try to make connections AFTER I have changed the OUTPUTS.
To Reproduce this you can use this simple supercollider script:

~adminInterfaceNetAddr = NetAddr("localhost", 8989); //define Admin Interface Address

~openStageControlPID = ("open-stage-control -d --send 127.0.0.1:57120 --port 8989").unixCmd;

~adminInterfaceNetAddr.sendMsg("/EDIT","patchbay_1","{\"css\":\".nodes { width: 30% }\"}");//funktioniert
~adminInterfaceNetAddr.sendMsg("/EDIT","patchbay_1","{\"label\":\"Neonbraun\"}");//funktioniert
~adminInterfaceNetAddr.sendMsg("/EDIT","patchbay_1","{\"inputs\":[\"input_1\",\"input_2\",\"input_3\"]}");//funktioniert
~adminInterfaceNetAddr.sendMsg("/EDIT","patchbay_1","{\"outputs\":[\"output_1\",\"output_2\",\"output_3\"]}");//funktioniert

~adminInterfaceNetAddr.sendMsg("/patchbay_1","input_2","output_2");//funktioniert
~adminInterfaceNetAddr.sendMsg("/patchbay_1","input_1","output_1");//funktioniert

~adminInterfaceNetAddr.sendMsg("/patchbay_1","input_1","");//funktioniert
~adminInterfaceNetAddr.sendMsg("/patchbay_1","input_2","");//funktioniert

~adminInterfaceNetAddr.sendMsg("/EDIT","patchbay_1","{\"inputs\":[\"rein\",\"input_2\",\"input_3\"]}");//funktioniert
~adminInterfaceNetAddr.sendMsg("/patchbay_1","rein","output_2");//funktioniert
~adminInterfaceNetAddr.sendMsg("/patchbay_1","rein","");//funktioniert

~adminInterfaceNetAddr.sendMsg("/EDIT","patchbay_1","{\"outputs\":[\"raus\",\"output_2\",\"output_3\"]}");//funktioniert
~adminInterfaceNetAddr.sendMsg("/patchbay_1","rein","raus");//funktioniert nicht!!!!!!!!!!!!!

the last command is the only one that is not working.
the debug information from open-stage-control looks just like it should and resembles all the previous commands that have worked

Could please point me where I've done something wrong? Or is it indeed maybe a bug?

Please provide as much contextual informations as possible:

- Open Stage Control version (or commit if built from sources)
0.48 (From Repo)
- Operating system
Ubuntu budgie
- Open Stage Control options
clean session with only a default patchbay

- Client type (built-in or external chromium/chrome browser) and version
super collider

**Comment by DjTuxeedo** [comment]
Use this supercollider script line by line to reproduce this

~adminInterfaceNetAddr = NetAddr("localhost", 8989); //define Admin Interface Address

~openStageControlPID = ("open-stage-control -d --send 127.0.0.1:57120 --port 8989").unixCmd;

~adminInterfaceNetAddr.sendMsg("/EDIT","patchbay_1","{\"css\":\".nodes { width: 25% }\"}");//funktioniert
~adminInterfaceNetAddr.sendMsg("/EDIT","patchbay_1","{\"label\":\"Neonbraun\"}");//funktioniert
~adminInterfaceNetAddr.sendMsg("/EDIT","patchbay_1","{\"inputs\":[\"input_1\",\"input_2\",\"input_3\"]}");//funktioniert
~adminInterfaceNetAddr.sendMsg("/EDIT","patchbay_1","{\"outputs\":[\"output_1\",\"output_2\",\"output_3\"]}");//funktioniert

~adminInterfaceNetAddr.sendMsg("/patchbay_1","input_2","output_2");//funktioniert
~adminInterfaceNetAddr.sendMsg("/patchbay_1","input_1","output_1");//funktioniert

~adminInterfaceNetAddr.sendMsg("/patchbay_1","input_1","");//funktioniert
~adminInterfaceNetAddr.sendMsg("/patchbay_1","input_2","");//funktioniert


~adminInterfaceNetAddr.sendMsg("/EDIT","patchbay_1","{\"inputs\":[\"rein\",\"input_2\",\"input_3\"]}");//funktioniert
~adminInterfaceNetAddr.sendMsg("/patchbay_1","rein","output_2");//funktioniert
~adminInterfaceNetAddr.sendMsg("/patchbay_1","rein","");//funktioniert


~adminInterfaceNetAddr.sendMsg("/EDIT","patchbay_1","{\"outputs\":[\"raus\",\"output_2\",\"output_3\"]}");//funktioniert
~adminInterfaceNetAddr.sendMsg("/patchbay_1","rein","raus");//funktioniert nicht!!!!!!!!!!!!!


Only the last command does not work as expected

**Comment by DjTuxeedo** [comment]
note: If I save the session with the new output names and reopen it. Making connections via OSC messages does work. But if I change the names with:
~adminInterfaceNetAddr.sendMsg("/EDIT","patchbay_1","{"outputs":["raus2","output_2","output_3"]}");

then establishing a new connection with:
~adminInterfaceNetAddr.sendMsg("/patchbay_1","rein","raus");

Does again not work! This is not normal, is it?

**Comment by jean-emmanuel** [comment]
Thanks for the report, I'll check this out asap.

**Comment by jean-emmanuel** [comment]
Fixed in git, thanks again for the very detailed report :)

**Comment by DjTuxeedo** [comment]
Wow, that was fast. I'll check it out as soon as I can. I've never compiled this before so it will be a challenge for me :-)

**Comment by jean-emmanuel** [comment]
0.48.2 has been uploaded ;)

**Comment by DjTuxeedo** [comment]
You Sir are a life saver. It's working now. I wish there was a way to donate with a paypal account. With AMMD i see only credit card options
