### ISSUE TITLE
When receiving OSC response from Qlab, OSC reports "Invalid continuation byte"

### ISSUE THREAD

**Issue by lhkev** [jean-emmanuel/open-stage-control#574]
Please provide as much contextual informations as possible:

- Open Stage Control version (or commit if built from sources)

Versions 0.48.1 and 0.48.4

- Operating system

MacOS Mojave 10.14.4

- Open Stage Control options

 --send 127.0.0.1:53000 \
 --tcp-port 53001 \
 --load QlabDiacriticsFailure.json \
 --tcp-targets 127.0.0.1:53000 \
 --debug true \
 --theme orange

- Client type (built-in or external chromium/chrome browser) and version

Safari 12.1

- Session file (can be uploaded after adding the .txt extension)

zip attached containing the session file and qlab demo workspace

- Custom module

none

- Server logs (from the terminal or the launcher's console)

App available at http://127.0.0.1:8080 & http://192.168.248.128:8080
TCP: connection established (127.0.0.1:53000)
OSC sent:  { address: '/workspace/A6D3D7B0-6E08-496D-8D80-02B9D464668B/cueLists',
  args: [ { type: 'f', value: 1 } ] } To: 127.0.0.1:53000
TCP: Error: Invalid continuation byte

- Client logs (hit F12 in chromium/chrome to open the console)

n/a

- Screenshot

quicktime video: LINK 

https://www.dropbox.com/s/i7gxr9im24ewk9n/Screen%20Recording%202019-11-28%20at%2017.49.55.zip?dl=0

[OSC-Bugs-Demos.zip](https://github.com/jean-emmanuel/open-stage-control/files/3902807/OSC-Bugs-Demos.zip)

This is a link to a screen recording showing the action of running the Qlab demo workspace, the OSC demo session and the debug output produced.

https://www.dropbox.com/s/i7gxr9im24ewk9n/Screen%20Recording%202019-11-28%20at%2017.49.55.zip?dl=0

I am creating an OSC session which reads data from Qlab using OSC commands. I have been successful, but I found an issue reading one particular Qlab workspace. Other workspaces have been read without problems. The problem workspace is an existing workspace with several cue lists, but I tracked down the cause to some diacritical characters in the listName of an audio cue. 

In my actual project I am using a custom module, however for the purposes of the bug demonstration no custom module is needed. The bug is present with or without a custom module.

Attached is a zip file containing a Qlab workspace containing one cue, containing the problem characters in the cue name. 

Also in the zip file is a session file containing one push button which will send the OSC command to Qlab which results in Qlab sending the information about the cue list and its child cues.

the OSC program fails to read the OSC message, and outputs the error message : 

TCP: Error: Invalid continuation byte

In the demo Qlab workspace, in the cue name there are two characters which OSC fails to handle properly, one is an e-accent (é) and the other is e-grave (è). (Note that other diacritical characters also cause issues).

it is the e-grave which causes the error message "invalid continuation byte". If this character is removed from the cue name and the push button pressed to retrieve the cuelist, then the debug output from OSC shows the response (it does not produce an error message) HOWEVER the e-accent character is present in the response as "e\u0001"  - within the object properties "listName" and "name"..  Incidentally the presence of the \u0001 caused the JSON to be invalid when I attempted to parse it in a custom module.

`OSC sent:  { address: '/workspace/A6D3D7B0-6E08-496D-8D80-02B9D464668B/cueLists',
  args: [ { type: 'f', value: 1 } ] } To: 127.0.0.1:53000
OSC received:  { address: '/reply/workspace/A6D3D7B0-6E08-496D-8D80-02B9D464668B/cueLists',
  args: '{"status":"ok","data":[{"number":"","uniqueID":"3B900943-4D31-44FB-A58C-7465AEA7B091","cues":[{"number":"38.2","uniqueID":"6211D050-280C-42FA-99C9-161AE3C501BA","flagged":false,"listName":"Violin Jete\u0001 and","type":"Audio","colorName":"none","name":"Violin Jete\u0001 and","armed":true}],"flagged":false,"listName":"PIT Cues","type":"Cue List","colorName":"none","name":"PIT Cues","armed":true}],"workspace_id":"A6D3D7B0-6E08-496D-8D80-02B9D464668B","address":"\\/workspace\\/A6D3D7B0-6E08-496D-8D80-02B9D464668B\\/cueLists"}' } From: 127.0.0.1:53000
`

Qlab is sending the correct JSON, which contains the diacritical characters - it is not Qlab which is corrupting the JSON - as noted by using Qlab's debugging tool which shows input/output OSC messages handled by Qlab.

So I suspect within OSC something is not recognising the string as UTF-8, or is incorrectly translating UTF-8. In particular, in the received message debug output from OSC, the e-accent character has changed to 'e\u0001' so something has attempted to translate the character but has failed, but interestingly the \u0001 is c-style syntax for unicode. However for e-accent the unicode C expression would be \u00E9

I am reporting the bug because at the moment it is possible for Qlab to send legitimate OSC replies which OSC does not handle properly. I cannot work around it because the message usually is not delivered at all to a custom module (example: e-grave) or may be delivered but with invalid JSON (example: e-accent). Since the OSC message usually does not get delivered, some Qlab workspaces would not be readable - and cause of the failure to read them is something which would not be obvious to the end user.

Thanks for your attention.

Regards,

Kevin Heap.

**Comment by jean-emmanuel** [comment]
Hi thank you for the detailed report. I've tracked the bug to a recent change in the osc backend (https://github.com/colinbdclark/osc.js/commit/1b932a27bb65efc68d99e18a8b5cd80876193f1b) causing open stage control to decode utf strings twice. It should be fixed in v0.48.5 (building/uploading now).

**Comment by lhkev** [comment]
Hi thank you for the incredibly quick response. 

The issue is resolved thank you.

**Comment by jean-emmanuel** [comment]
You're welcome !
