### ISSUE TITLE
audio player widget ?

### ISSUE THREAD

**Issue by jgastonraoul** [jean-emmanuel/open-stage-control#577]
Hi !

Is there a way to make an audio player widget, displaying waveform, In/out loop points, play bar, etc ?
I've been able to display a waveform using the plot widget, but I don't know if there is a way to display some player showing where I am in the file...

Regards,

Jérémie

**Comment by cyberic99** [comment]
Hello

I have implemented such a player, it looks like this:
![image](https://user-images.githubusercontent.com/193917/70065003-b0258180-15ea-11ea-8be5-6b3c0e9c3361.png)

So yes, it is possible ;-)

Regarding the waveform... is it precalculated or is it generated in realtime?

You have several choices:
- stream pictures via OSC
- use a frame
- use a video (syncing it with audio will be difficult)
- use a HTML widget

**Comment by jgastonraoul** [comment]
>  The appropriate way to solve this would be using a dedicated audio software that reports the playback informations to o-s-c.

@jean-emmanuel It's exactly what I'm looking for ! I'm able to send all that informations to o-s-c, but I need some GUI widget to display and control the remote player.

**Comment by jean-emmanuel** [comment]
Then using a combination of sliders, buttons and inputs should do the job I think.
