### ISSUE TITLE
[Bug] Just blue window after clicking start in Open Stage Control

### ISSUE THREAD

**Issue by StephanSchelens** [jean-emmanuel/open-stage-control#578]
Hi Jean-emmanuel,
i have a problem with open stage control. When i click on the start button i get only a blue window and nothing happens. No Browser window no error messages. Nothing.
My System is Windows 10 64bit, Installed Python 3.8, installed rtmidi, installed Build Tools
Ive tried so many things but nothing worked yet.
Did you have same problems or get it worked after some similar problems?
Thank you for your help.

**Comment by jean-emmanuel** [comment]
Hi. Has it ever worked before or is it the first time you try to launch it ? Can you paste here the options set in the launcher (or a screenshot) ?

**Comment by StephanSchelens** [comment]
Hi Jean, thanks for the response. It's the first time. Ive tried different things in the launcher also clean as is, but ever only the blue window opens nothing more. I make tomorrow a Screenshot. Thank you for your help.

**Comment by jean-emmanuel** [comment]
Thanks, no need for a screen if you tried without any option set. Can you hit F12 once the blank window opens ? This should open's a development panel and hopefully show some error message. Also if that's possible can you launch the app from a terminal ?
```
cd C:/path/to/open-stage-control
open-stage-control.exe
```

**Comment by StephanSchelens** [comment]
Hi Jean, ive tried also with terminal. Its the same. i become only the note with the http ip in the terminal.
Nothing elses. Just the Blue Screen opens. I try F12 when im in the studio and hope there is a error message :) I keep you up to date. Thank you

**Comment by StephanSchelens** [comment]
So, now im in the studio. When i click start it opens the Blue Screen and i press F12. I have make a screenshot of it. I can not see any errors or something. I dont now whats wrong. 
![screenshot_1](https://user-images.githubusercontent.com/58433499/70229836-4080d500-1757-11ea-8d24-6a4448f351b6.jpg)

**Comment by jean-emmanuel** [comment]
Can you try opening the address that's printed in the terminal with a chrome browser ?

**Comment by StephanSchelens** [comment]
I have tried it but nothing happens. It doesnt load open stage control in the browser.

**Comment by jean-emmanuel** [comment]
Ok, can you try setting the `port` option to someWhat's the addthing different than 8080 ?

**Comment by StephanSchelens** [comment]
How can i do that?

**Comment by jean-emmanuel** [comment]
in the launcher window, you have an option called `port`.

**Comment by StephanSchelens** [comment]
Ok it worked. That was the problem.  Thank you very much. But why does the 8080 port doesnt work?

**Comment by jean-emmanuel** [comment]
There is another program running on your system that uses the same port. Normally this would raise and print an error but it seems that under certain conditions the failure remains silent (same issue : #570). I haven't figured out why yet although I suspect some applications may not properly lock the port they use, to be investigated.

**Comment by StephanSchelens** [comment]
Oh ok, sry i did not see the prev. post. But im very thankful for your quick support. And its great that it work now. Thank you very much.

**Comment by jean-emmanuel** [comment]
You're welcome !

**Comment by jean-emmanuel** [comment]
Starting with next release, this error will no longer be hidden.
