### ISSUE TITLE
[Bug] UI enourmously big in Chrome

### ISSUE THREAD

**Issue by ianshade** [jean-emmanuel/open-stage-control#579]
Hello,
The app is unusable in latest Chrome because of some scaling issues. Basically everything except fonts is like 10 times too big.
- Open Stage Control version: cloned straight from master (commit 778323191bdbbd746f064cb024732aa1c7659815), but it also happens on the official demo
- OS: Windows 10 Pro 64-bit (10.0.18362 Build 18362)
- Client: Chrome, version 78.0.3904.108 (Official Build) (64-bit)
- Logs: Nothing unusual except some [font warnings](https://pastebin.com/SLhef2tK) in browser console
- [Screenshot](https://imgur.com/a/5C4BNWq)

**Comment by jean-emmanuel** [comment]
Hi, the issue has been explained here : https://github.com/jean-emmanuel/open-stage-control/issues/564
You need to set chrome's minimum font-size setting to 1px to fix it.
