### ISSUE TITLE
Real example needed for midi documentation

### ISSUE THREAD

**Issue by korakios** [jean-emmanuel/open-stage-control#58]
Hi,
Thank you for this wonderful project ! I have some trouble setting a midi device. I am on Linux debian and launch PureData, then my device listed in ALSA is

client 128: 'Pure Data' [type=user]
    0 'Pure Data Midi-In 1'
    1 'Pure Data Midi-Out 1'

Open-Stage-Control list:

MIDI Inputs
 -1: null (disabled)
  1: Midi Through Port-0
  3: Pure Data Midi-Out 1

MIDI Outputs
 -1: null (disabled)
  0: Midi Through Port-0
  2: Pure Data Midi-In 1

I start the server with the '-m' argument. Then I create a fader and I don't know what to write in the target field...Tried from the guide at http://osc.ammd.net/user-guide/midi/  :
midi: Pure Data Midi-In 1
but the app automatically converts the field to 
["midi: Pure Data Midi-In 1"]

The preArgs field is
["/control 10"]

Nothing works lol ! So I need some help

**Comment by jean-emmanuel** [comment]
Hi ! Thanks for your feedback :)

You must define one or more midi device when launching the app. In your case, You'd run:

```
open-stage-control -m puredata:3,2
```

This would make the target `"midi:puredata"` valid (sending to `Pure Data Midi-In 1`, receiving from `Pure Data Midi-Out 1`). 

Alternatively you could use a virtual midi device for connecting with ALSA (requires `python-mididings` package, available in debian):

```
open-stage-control -m puredata:virtual
```

This would create a virtual midi device that can be connected via ALSA.

Either way, you'd set the target option as follows: `["midi:puredata"]


> but the app automatically converts the field to ["midi: Pure Data Midi-In 1"]

That's ok, as stated [here](http://osc.ammd.net/user-guide/widgets-generics/#target), `target` must be a javascript array, so that multiple targets can be defined; when submitting a single string value, the app converts it to a one-item array.

> ["/control 10"]

- `/control` should be the [`address`](http://osc.ammd.net/user-guide/widgets-generics/#address) of your widget
- [`preArgs`](http://osc.ammd.net/user-guide/widgets-generics/#preargs) should just be `[10]` here. If you were to need more arguments here, you'd separate them with comas, as it must be written as a valid javascript array:  `[10, 64]`  or event `[10, 64, "some_string"]`

**Comment by jean-emmanuel** [comment]
An example shall be added soon :)

**Comment by korakios** [comment]
Lol ,epic fail, did none correctly ! I was thinking trying to write a patch in PureData to translate fixed OSC messages to midi but I'll try it again! Thank you very much

**Comment by cyberic99** [comment]
Hello!
I have some trouble as well.
I've got a M-Audio X-session Pro MIDI control surface.
I would like to be able to:
- Move a knob on the X session, see the knob move on openstagecontrol (and send some OSC messages)
- Move a knob in openstagecontrol, that would send a MIDI CC (and some OSC messages) to my external devices.
I chose to create a virtual device to be able to patch it easily with Qjackctl.
With this setup, I can move physical knobs or the knobs on the (touch) screen, and I can get the current state of all the knobs on the screen.

Is such a setup possible?

I have launched OpenStageControl like this: 
`$ open-stage-control -m openstage:virtual`
In qjackctl, I have connected the MIDI out of the X-Session to the openstage_in, and
openstage_out to the MIDI input of my external MIDI interface

I have created a knob in the Editor.
The knob I selected sends a CC 24.
So in preArgs, I have put `[24]`
in target, `["midi:openstage"]`
in address, `/control`

And from there... I'm stuck...
If you got any hint to provide I would be happy to test it.
And if something is not clear, please ask.

Thank you for this great software!

**Comment by jean-emmanuel** [comment]
Hi !

There's one preArg missing in your setup that's the midi channel number (see [doc](http://osc.ammd.net/user-guide/midi/#supported-commands)). Setting `preArgs` to `[1,24]` should work (and send midi over channel 1). I'm realizing my previous answer above was missing that too sorry.

**Comment by cyberic99** [comment]
Right, the channel wasn't specified anywhere, it makes sense.
I'm gonna test it asap.
Otherwise, do you think it is possible t achieve a setup similar to what I described?

**Comment by jean-emmanuel** [comment]
Now if I understand correctly, you want to synchronize Open Stage Control and your X-Session Pro, and convert their midi messages to osc messages. Currently that's not possible without an extra tool : I'd recommend using an osc to midi router such as https://github.com/jean-emmanuel/midi2osc (simple)  or https://github.com/ssj71/OSC2MIDI (powerful).

**Comment by cyberic99** [comment]
Can you tell me what part is not supported?
I thought that all these features were supported:

- touch a knob on the xsession => the knob state on the screen is updated
- touch a knob in openstagecontrol => a MIDI event is sent through the virtual device
- send an OSC messages to openstagecontrol => the knob state on the screen is updated
- touch a knob in openstagecontrol => an OSC event is sent

Thank you

**Comment by jean-emmanuel** [comment]
All these are supported but:

- a single widget cannot send 2 different message (same args to mutliple targets), you could send midi and osc at the same time (with target = `["midi:openstage","127.0.0.1:5555"] for example) but the osc message would be `/control etc`
- updating widgets by sending midi/osc messages to Open Stage Control doesn't make them send their value again

**Comment by cyberic99** [comment]
I see, thanks for the explaination.
So I think with adequate patching and/or midi2osc or osc2midi, I got all I need!
I'll test all this soon and keep you updated
Thank you!

**Comment by cyberic99** [comment]
with the updated preArg command, this setup is working perfectly, thanks!
