### ISSUE TITLE
Try to connect with androidbox to open stage control[Bug] 

### ISSUE THREAD

**Issue by StephanSchelens** [jean-emmanuel/open-stage-control#580]
Hi Jean, 

i have set up open stage control on the same machine as my daw. Now i will connect my touch device with chrome on an hanspree android box with open stage control ip, but it says "the site cant be reached" every time. ive tried different ports (8000, 9000) but its ever the same. My Android box is in the same network as my main pc. I have tried Chrome and Fierfox on the android box.
Thank you very much.

**Comment by jean-emmanuel** [comment]
Hi,
Have you tried to access the interface with a different device/computer on the network ? Are you using the local network ip and not the localhost on ("127.0.0.1") ?

**Comment by StephanSchelens** [comment]
HI Jean, 

i have tried it with my mobilphone and it works. But with my Touchdevice over the androidbox its not possible. Both are in the same network, connected via ethernet. I try it with the IP: 193.168.178 etc..
Thanks for helping me.

**Comment by jean-emmanuel** [comment]
Is the androidbox browser using the https protocol automatically ? open stage control only works with http.

**Comment by StephanSchelens** [comment]
Hi Jean, it was an issue of the androidbox. I have buyed a other one and it works out of the box. Thank you very much for your help.

**Comment by jean-emmanuel** [comment]
ok cool !
