### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jibestudio** [jean-emmanuel/open-stage-control#581]
Bonjour Jean-Emmanuel

Il semble que le paramètre "spring" (retour à la valeur par défaut au release) pour le widget /pad/xy ne fonctionne pas alors qu'il fonctionne très bien pour le widget Fader.
version OSC : 0.48.6
OS : Win 10 pro 64bits
Client : Built in

Cordialement et merci pour ton super soft,
JB Merland

**Comment by jean-emmanuel** [comment]
Merci, c'est corrigé dans le dépôt !

**Comment by jibestudio** [comment]
C'est moi qui te remercie pour ta rapidité !;)
