### ISSUE TITLE
[Bug] Affichage incomplet en retour de veille

### ISSUE THREAD

**Issue by Ezrabox** [jean-emmanuel/open-stage-control#582]
Server 0.48.6 MacOS 10.14.4
Client ipadpro ios 13.1.3 
safari en plein écran
[LGML2070.2.7.json.zip](https://github.com/jean-emmanuel/open-stage-control/files/3964428/LGML2070.2.7.json.zip)

Lorsque j’éteins l'écran de la tablette ou qu'elle passe en veille, 
Lorsque je ré-affiche Open stage control l'affichage est tronqué comme ci dessous

Affichage en retours de veille :
![UNADJUSTEDNONRAW_thumb_104e](https://user-images.githubusercontent.com/33526688/70855548-d55c9e80-1ecc-11ea-9018-1bb68c932d13.jpg)
Affichage Normal : 
![UNADJUSTEDNONRAW_thumb_104d](https://user-images.githubusercontent.com/33526688/70855553-dd1c4300-1ecc-11ea-9001-8b5467a55ef3.jpg)

**Comment by jean-emmanuel** [comment]
Est-ce que la rotation automatique de l'affichage est verrouillée ? Est-ce que ça se rétablit en faisant une rotation ?

**Comment by Ezrabox** [comment]
Hello, la rotation automatique n'était pas verrouillée, effectivement ça se rétablie en bougeant ma tablette en position portrait puis retour à paysage. 
Je continue les tests notamment en verrouillant l’orientation.

**Comment by Ezrabox** [comment]
que la rotation soit verrouillée ou non le problème apparaît

**Comment by jean-emmanuel** [comment]
Je pensais que l'espace perdu à droite correspondait à la taille du menu latéral mais après vérification il s'agit précisément de la différence de taille entre la largeur et la hauteur de l'écran de la tablette. Je ne vois qu'une possibilité : il s'agit d'un bug du côté d'iOS ou safari qui ne parvient pas a faire le rendu correctement en sortie de veille. Il n'est pas impossible que la lourdeur de l'interface entre en compte dans le déclenchement du problème, mais je ne pense pas pouvoir le régler, je ferme donc le ticket.
