### ISSUE TITLE
[Bug] Décalage graphique d'un widget entre server et client

### ISSUE THREAD

**Issue by Ezrabox** [jean-emmanuel/open-stage-control#583]
Server 0.48.6 MacOS 10.14.4
Client ipadpro ios 13.1.3 
safari en plein écran
[LGML2070.2.7.json.zip](https://github.com/jean-emmanuel/open-stage-control/files/3964438/LGML2070.2.7.json.zip)

Le grand fader vertical qui indique 69.66 sur la gauche ne s'affiche pas au même endroit et de la même taille sur le client et le server. Je n'avais pas eu ce genre de bug me semble-t-il, serait-ce la dernière version? 

Vue sur le serveur : 
<img width="1173" alt="Capture d’écran 2019-12-15 à 00 05 13" src="https://user-images.githubusercontent.com/33526688/70855666-e0183300-1ece-11ea-8a58-548bc427e236.png">
Vue sur la tablette : 
![UNADJUSTEDNONRAW_thumb_104f](https://user-images.githubusercontent.com/33526688/70855658-d1318080-1ece-11ea-99e6-df931d4fce01.jpg)

**Comment by jean-emmanuel** [comment]
Sa position est exprimée en %, c'est donc normal qu'elle dépende de la taille de l'écran. Le bug d'affichage sur le bouton du fader est systématique ?

**Comment by jean-emmanuel** [comment]
> Le bug d'affichage sur le bouton du fader est systématique ?

Je suspecte que ce bug se manifeste après un changement d'orientation de l'appareil ou une sortie veille, je vais regarder ça.

Sinon, petite remarque, tu gagnerais à utiliser des widgets [`strip`](https://openstagecontrol.ammd.net/docs/widgets-reference/#strip) pour définir l'agencement global de ton interface au lieu de les placer de manière absolue comme tu le fais, ce te permettrait avoir une interface qui s'adapte mieux au différentes tailles d'écrans.

**Comment by Ezrabox** [comment]
Hello, effectivement c'était bien ce soucis de réglage. 
Sorry! 
Pour les soucis d'orientation je continue sur le poste #582
