### ISSUE TITLE
[Bug] Sending special Characters to Textfield fails

### ISSUE THREAD

**Issue by DjTuxeedo** [jean-emmanuel/open-stage-control#585]
Hey There,
I've encountered a problem when trying to display custom text in a "text Widget".
The code seems to have a problem with special Characters like ŝ

I used the following super collider commands:
~adminInterfaceNetAddr.sendMsg("/Score_Inspector/AudiencePreview","ŝugar");
~adminInterfaceNetAddr.sendMsg("/EDIT","AudienceTextPreview","{\"value\":\"ŝugar\"}");
~adminInterfaceNetAddr.sendMsg("/SET","AudienceTextPreview","ŝugar");

None of which updated the text. whener I replace ŝugar with sugar it works in all three cases.

I there a way to display special characters on the Interface? (like é,û,ä,ü,ö,ĉ etc.)?

Kind regards
Hauke

**Comment by jean-emmanuel** [comment]
O-S-C can send and receive special characters without trouble (they are actually encoded into ascii to conform to the osc specification). It looks like super collider doesn't send these characters properly, you can check what O-S-C receives by enabling the server's `debug` option.

**Comment by DjTuxeedo** [comment]
The --debug option does not respond whenever I send a message with a special character.
I used python to test another way of creating osc messages. 

I was able to send a string like "Hallö World" in between Python and supercollider but whenever I use Python or SC I cannot see the message in the OpenSoundControl GUI nor in the --debug output.
Needles to say everything works as expected when the String is simple "Hello World"
Here is my Python code:


import argparse
import random
import time

from pythonosc import udp_client


if __name__ == "__main__":
  parser = argparse.ArgumentParser()
  parser.add_argument("--ip", default="127.0.0.1",
      help="The ip of the OSC server")
  parser.add_argument("--port", type=int, default=8989,
      help="The port the OSC server is listening on")
  args = parser.parse_args()

  client = udp_client.SimpleUDPClient(args.ip, args.port)

  client.send_message("/Score_Inspector/AudiencePreview", "Hellö World")

**Comment by DjTuxeedo** [comment]
`import argparse
import random
import time

from pythonosc import udp_client


if __name__ == "__main__":
  parser = argparse.ArgumentParser()
  parser.add_argument("--ip", default="127.0.0.1",
      help="The ip of the OSC server")
  parser.add_argument("--port", type=int, default=8989,
      help="The port the OSC server is listening on")
  args = parser.parse_args()

  client = udp_client.SimpleUDPClient(args.ip, args.port)

  client.send_message("/Score_Inspector/AudiencePreview", "Hellö World")
`

**Comment by jean-emmanuel** [comment]
What version of o-s-c are you using ? Sending `"Hellö World"` with python-osc works fine here.

**Comment by DjTuxeedo** [comment]
The Version of o-s-c in my setup is 0.48.2

Does it maybe have to do with my locale? In my Ubuntu it is set to de_DE.UTF-8
Could you attach the code in Python you have used to send "hello Wörld"?

Out of curiosity: How does the o-s-c text-field handle an OSC blob. Could I use a Blob filled with UTF8 encoded Chars to display the text that I need?

Thanks for your help

**Comment by jean-emmanuel** [comment]
You need to update o-s-c, a bug related to utf strings was fixed in v0.48.5.

Here is the code, pretty much the same as yours:
```python
import argparse
import random
import time

from pythonosc import udp_client

parser = argparse.ArgumentParser()
parser.add_argument("--ip", default="127.0.0.1",
help="The ip of the OSC server")
parser.add_argument("--port", type=int, default=8989,
help="The port the OSC server is listening on")
args = parser.parse_args()

client = udp_client.SimpleUDPClient(args.ip, args.port)
client.send_message("/Score_Inspector/AudiencePreview", "Hellö World")
```

**Comment by jean-emmanuel** [comment]
> How does the o-s-c text-field handle an OSC blob. Could I use a Blob filled with UTF8 encoded Chars to display the text that I need?

The widget itself will probably not be able to display what you want, but you could decode it (manually) from a custom module, here is an example on the forum : 

https://openstagecontrol.discourse.group/t/getting-values-from-a-blob/313

**Comment by DjTuxeedo** [comment]
Thanks a Million. It does work with the newest version of o-s-c 0.48.8
Since I updated my setup not too long ago I didn't bother to check for a new version, sry, next time i'll do that first.
So yes, it does work with python-osc and with supercollider
Thanks again for alle the help
