### ISSUE TITLE
[Bug] ENOENT when opening a non-existent directory with the file widget

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#588]
version: git 89afc655df195ea57b9e8e2cf68716b6250e0ac8, on linux debian.

When using the file widget, setting the ``directory`` property to a non-existent dir, displays a popup with 'ENOENT'. This is fine, as the directory does not exist.

But after that, there is no way to come back to a sane directory. no ``.`` nor ``..`` button are displayed, so we can do nothing to fix the situation.

Would it be possible, in this case, to jump to the user's home directory?

Also, I would like to select directories too

one way of doing it would be to browse inside a dir, and press 'open', but this doesn't work. we HAVE to select a file in order to close the file selector.

thx

**Comment by jean-emmanuel** [comment]
> Would it be possible, in this case, to jump to the user's home directory?

I think the current behavior is correct, you can change to `directory` property to a valid one to fix the issue.

> Also, I would like to select directories too

I'll check this out.

**Comment by jean-emmanuel** [comment]
> Also, I would like to select directories too

in git

**Comment by cyberic99** [comment]
> in git

Thank you very much.

I still have another tiny request to add to the allowDir feature:

would it be possible, when the user selected a directory, to append a slash to the widget value?

this would enable to know if the user selected a directory or a file.

I know I can check that on the server too, but I'd like to know it from inside o-s-c if possible.

As always, feel free to discard this request if you find it is not relevant.

And thanks for this addition anyway!

**Comment by jean-emmanuel** [comment]
> would it be possible, when the user selected a directory, to append a slash to the widget value?

I thinking of making the option exclusive too, I'm not sure it make sense to be able to select a file or a folder at the same time.

**Comment by cyberic99** [comment]
> Done.

thx!

> I'm not sure it make sense to be able to select a file or a folder at the same time.

Humm I don't know.

maybe this can still be useful, for instance if a user wants to select a particular preset, or a folder containing several presets...

if it is not too complex to have both of them, I would keep it that way
