### ISSUE TITLE
Error: Cannot find module './socket'

### ISSUE THREAD

**Issue by tristan-k** [jean-emmanuel/open-stage-control#59]
Starting open-stage-controller with `open-stage-controller.exe --blank` gives me an javascript error.

I'm running Windows 10 64bit with an surface device. 

![java-script-error](https://cloud.githubusercontent.com/assets/732025/25001872/bd1f7922-2047-11e7-892d-a56480dd4da7.PNG)

Any suggestions?

**Comment by jean-emmanuel** [comment]
Which version are you using ? Are you using a prebuilt executable downloaded from the release page or did you build the app yourself ?

**Comment by tristan-k** [comment]
The latest prebuild executable from the github release page.

**Comment by jean-emmanuel** [comment]
Ok. Does the error show when using the `--no-gui` switch ? And then, when connecting to the server using Chrome (or `open-stage-control --gui-only`) ?

**Comment by tristan-k** [comment]
I'm sorry. It seems Windows 10 inbuilt unzipper must have corrupted the archive. I downloaded it again and extraced the files with 7-zip. Now it works.

**Comment by jean-emmanuel** [comment]
Ok cool :)
