### ISSUE TITLE
[Bug] [Feature] Save state problems

### ISSUE THREAD

**Issue by docb** [jean-emmanuel/open-stage-control#590]
7434e84bf0a1c09c95c6e0343bbcff63c0795b89 linux with node/firefox, no special options

not sure if a bug or feature.
it is not shown in the gui what is the current state file which is saved on click on save.
this traps into dataloss:
open a state. change something. click save and then choose a filename say file1.state.
open another state, say file2.state. change something. click save. imho one could expect that the state is now saved to the most recent opened state which is file2.state as it is the current loaded state. instead the file1.state is overwritten and the data is completely lost.
so the feature request would be that one can see the current state file and that the open action changes the current state file (not sure if the current behavior is intended).

**Comment by jean-emmanuel** [comment]
That sure looks like a bug, thanks for the report !

Just in case, firefox is not supported so you'll likely encounter visual quirks with it.

**Comment by docb** [comment]
ok thanks, but firefox worked very well so far ....

**Comment by jean-emmanuel** [comment]
Fixed in git

**Comment by docb** [comment]
ok, tested - after open the correct file is written on save. thanks.
