### ISSUE TITLE
[Bug] OSX Mojave, python ENOENT problem

### ISSUE THREAD

**Issue by smandrap** [jean-emmanuel/open-stage-control#594]
Hello!

I'm stuck with this inglorious issue:

`A JavaScript error occurred in the main process: Uncaught Exception:
Error: spawn python3 ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
at onErrorNT (internal/child_process.js:456:16)
at processTicksAndRejections (internal/process/task_queues.js:77:11)`

I'm running Mac OSX 10.14.6, installed python 3.8.1 with rtmidi and running OSC 0.49.3. After two days of fiddling around, i had no success (also taking into account the fact that i'm not that good at this kind of things).

This is the screenshot of my session
![Schermata 2020-02-12 alle 19 59 38](https://user-images.githubusercontent.com/60984250/74367489-425bba00-4dd2-11ea-82fd-508615511dfe.png)

How do i solve this??
Thanks in advance

**EDIT**:

It seems like i have managed to solve my problem once for all, trying a plethora of different solutions (clean python install, building OSC from source and executing it via npm), and discovered that the problem wasn't python, it was me. I didn't realize i wasn't starting the server AND THEN ask for the midi list, but the other way around. oops..

One interesting thing i noticed during my tinkering though, is that if you build the source code and execute it via `npm start`, it never raises the ENOENT exception.

**Comment by jean-emmanuel** [comment]
I just read your addendum, I'm glad your sorted it out ! Actually you can list midi devices without starting the server but in your case the settings needed to be saved before in order to apply the `path=` option. The "List devices" action should always check for the current midi configuration, I'll fix that. Thanks for reporting !

**Comment by jean-emmanuel** [comment]
> The "List devices" action should always check for the current midi configuration.

Fixed in v0.49.4
