### ISSUE TITLE
[Bug] issues when sending some characters to text widgets

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#595]
- Open Stage Control version v0.49.3
- Operating system: Linux

I use a kind of 'logs streamer' to strem my app logs into a big text widget in o-s-c.

One of the programs I use prints ``Print ^c to abort``

The text widgets behaves strangely afer receiving this...

the text is truncated and then the following lines appear with a strange offset..., as if a new text column was started...

look here, you can see 'press' at the bottom, and 'to stop' is on the right...

![image](https://user-images.githubusercontent.com/193917/74651958-48acb600-5185-11ea-8951-3e3e1d17d83f.png)

Thx!

**Comment by jean-emmanuel** [comment]
The widget tries to convert `^c` to an icon (and fails), you could avoid this by using an html widget instead.

**Comment by cyberic99** [comment]
OK thank you. I simply replaced the ^ character with a space, in javascript. Thank you.

Not sure if you consider it as a bug or not.

**Comment by jean-emmanuel** [comment]
well that's something to improve at least !

**Comment by jean-emmanuel** [comment]
fixed in v0.49.10 with 421999e70b580544873e80387efb256c0387948f

**Comment by cyberic99** [comment]
Hello @jean-emmanuel and thanks for the fix

However, it also cause a regression for me, as sone icons I use have a 3-letters name, such as ``^eye`` and also ``^cog``

**Comment by jean-emmanuel** [comment]
haha I missed these, will fix.

**Comment by jean-emmanuel** [comment]
fixed
