### ISSUE TITLE
[Bug] Command prompt possible bug?

### ISSUE THREAD

**Issue by iddqdosc** [jean-emmanuel/open-stage-control#596]
Hi!

I have the following batch file that worked fine on 0.48.7 and stopped working after I updated to 0.49.4:

`D:\path\open-stage-control.exe -m oscIn:-1,2 oscOut:3,-1 midiIn:-1,4 midiOut:5,-1 -l "D:\path\OSC.json" -n -c "D:\path\Module.js" --remote-root "D:\path\" `

Nothing happens now. Did the syntax change? I've tried using apostrophes and quotes but that gives me all sorts of errors. 

Thanks!

**Comment by jean-emmanuel** [comment]
This works fine  on my system but I have to add a backslash in the last argument to avoid escaping the last double quote (`"D:\path\\"`).

**Comment by iddqdosc** [comment]
It does not work here. Anything after the very first option does not seem to register.

Works:
`open-stage-control -m oscIn:-1,2`

Northing happens:
`open-stage-control -m oscIn:-1,2 oscOut:3,-1`

Nothing happens:
`open-stage-control -m oscIn:-1,2 oscOut:3,-1 ahkIn:-1,4 ahkOut:5,-1 `

Any ideas?

**Comment by jean-emmanuel** [comment]
could you try wrapping the midi options in quotes?
`open-stage-control -m "oscIn:-1,2 oscOut:3,-1 ahkIn:-1,4 ahkOut:5,-1"`

**Comment by GeneralMidi** [comment]
Could the OP be on Windows? Maybe it has something to do with the engine upgrade that has stopped custom modules working me...

**Comment by jean-emmanuel** [comment]
@GeneralMidi It's not related, the issue you mention is fixed in git as of https://github.com/jean-emmanuel/open-stage-control/commit/e180b889cb4cd02e9119be1eb12b35a097dc7b29

**Comment by jean-emmanuel** [comment]
@iddqdosc the cli parsing code has not changed much since v0.48.7, although it could be a windows-specific edge effect in the parser library that has been updated. Could you please confirm that your script still works on your system with v0.48.7 : the fact that "nothing happens", not even an error, is rather intriguing and I'd like to be sure that's not caused by something else like a system update.

**Comment by iddqdosc** [comment]
Yes, I'm on Windows. Wrapping the midi options in quotes (also apostrophes) was the first thing I tried, but no success

`open-stage-control -m "oscIn:-1,2 oscOut:3,-1 ahkIn:-1,4 ahkOut:5,-1"`

It loads OSC gui and gives me the following error:

```
App available at http://192.168.0.11:8080 & http://127.0.0.1:8080
A JavaScript error occurred in the main process: Uncaught Exception:
Error: ValueError: too many values to unpack (expected 2)
    at PythonShell.parseError (D:\path\resources\app\server\node_modules\python-shell\index.js:260:1)
    at terminateIfNeeded (D:\path\resources\app\server\node_modules\python-shell\index.js:139:1)
    at Socket.<anonymous> (D:\path\resources\app\server\node_modules\python-shell\index.js:113:1)
    at Socket.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
    ----- Python Traceback -----
    File "D:\path\resources\app\server\python\midi.py", line 18, in <module>
      name, ports = arg.split(':')
Service name is already in use in the network, selecting new one.
Trying with:  PCNAME_1.local
Service name is already in use in the network, selecting new one.
Trying with:  PCNAME_1.local
```

But if I wrap the midi options in quotes and write the rest of the command, nothing happens!  

`open-stage-control -m "oscIn:-1,2 oscOut:3,-1 midiIn:-1,4 midiOut:5,-1" -l "D:\path\OSC.json" -n -c "D:\path\Module.js" --remote-root "D:\path\" `

**Comment by iddqdosc** [comment]
Yes, it works fine in v0.48.7 (I rolled back in the meanwhile) but anything above v0.49 does not.

**Comment by jean-emmanuel** [comment]
Thanks, I'll downgrade the suspicious library and cut a release.

**Comment by jean-emmanuel** [comment]
v0.49.5 is uploading

**Comment by iddqdosc** [comment]
Thanks Jean, I'll try it asap and let you know.

**Comment by cyberic99** [comment]
wow @jean-emmanuel , once again you have to downgrade a dependency to solve a bug introduced in the newest versions?

If I remember correctly, you also had problems with electron, mathjs, sanitize-html, ws, and now yargs... this is worrying...

**Comment by iddqdosc** [comment]
Thanks again but unfortunately v0.49.5 did not solve the problem. I tested every v0.49 releases (including rc2) and no luck. Rolled back to v.0.48.8 and the prompt command is working fine (I've been using it since v0.47.1).

Dunno if it's related, but v0.48 has a lot of api files that v0.49 does not have.

**Comment by jean-emmanuel** [comment]
I've managed to reproduce the issue : it's due to the electron binary that for reasons beyond my comprehension crashes when given an argument containing a colon followed by any other argument. It only occurs with the windows binary since v3 and is not related to o-s-c. I'm reporting this upstream and will keep you posted.

**Comment by jean-emmanuel** [comment]
I figured it out. Since v3, electron stops parsing arguments after a colon is found (https://github.com/electron/electron/pull/13039), it's been motivated by security reasons (https://www.electronjs.org/blog/protocol-handler-fix) and will probably not change. As of v0.49.6, windows users launching the app from a terminal will need to add a double dash (--) before their options to avoid this issue. I'm pushing a new release and will update the docs accordingly.

**Comment by jean-emmanuel** [comment]
@cyberic99 when updating dependencies there always a chance of having edge effects, it's not worrying, it's just something to be careful with.

v0.49.6 is uploading.

**Comment by iddqdosc** [comment]
Thanks for the explanation but unfortunately v0.49.6 didn't fix it either.

Nothing happens:
`open-stage-control --m oscIn:-1,2 oscOut:3,-1 midiIn:-1,4 midiOut:5,-1 --l "D:\path\OSC.json" --n --c "D:\path\Module.js" --remote-root "D:\path\" `
(also tested wrapping the midi options in quotes but nothing)
Nothing happens:
`open-stage-control --midi oscIn:-1,2 oscOut:3,-1 midiIn:-1,4 midiOut:5,-1 --load "D:\path\OSC.json" --no-gui --custom-module "D:\path\Module.js" --remote-root "D:\path\" `

Running o-s-c with just the midi options and wrapping it in quotes, give me different errors for --m or --midi

--midi
```
open-stage-control --midi "oscIn:-1,2 oscOut:3,-1 midiIn:-1,4 midiOut:5,-1"

App available at http://192.168.0.11:8080 & http://127.0.0.1:8080
A JavaScript error occurred in the main process: Uncaught Exception:
Error: ValueError: too many values to unpack (expected 2)
    at PythonShell.parseError (D:\path\resources\app\server\node_modules\python-shell\index.js:260:1)
    at terminateIfNeeded (D:\path\resources\app\server\node_modules\python-shell\index.js:139:1)
    at ChildProcess.<anonymous> (D:\path\resources\app\server\node_modules\python-shell\index.js:131:1)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
    ----- Python Traceback -----
    File "D:\path\resources\app\server\python\midi.py", line 18, in <module>
      name, ports = arg.split(':')
```

--m or -m:
```
open-stage-control -m "oscIn:-1,2 oscOut:3,-1 midiIn:-1,4 midiOut:5,-1"

App available at http://192.168.0.11:8080 & http://127.0.0.1:8080
A JavaScript error occurred in the main process: Uncaught Exception:
Error: ValueError: too many values to unpack (expected 2)
    at PythonShell.parseError (D:\path\resources\app\server\node_modules\python-shell\index.js:260:1)
    at terminateIfNeeded (D:\path\resources\app\server\node_modules\python-shell\index.js:139:1)
    at Socket.<anonymous> (D:\path\resources\app\server\node_modules\python-shell\index.js:113:1)
    at Socket.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
    ----- Python Traceback -----
    File "D:\path\resources\app\server\python\midi.py", line 18, in <module>
      name, ports = arg.split(':')
Service name is already in use in the network, selecting new one.
Trying with:  PCNAME_1.local
Service name is already in use in the network, selecting new one.
Trying with:  PCNAME_1.local
```

**Comment by jean-emmanuel** [comment]
Sorry if I didn't make it clear, you need to add double dash this way:
```
open-stage-control.exe -- -m etc
```

**Comment by jean-emmanuel** [comment]
Also wrapping the midi arguments in quotes was an irrelevant idea of mine, it doesn't work.

**Comment by iddqdosc** [comment]
Now it works perfectly! Thanks a lot for your attention and for fixing the issue so quickly.
