### ISSUE TITLE
[Feature] Improve OSC Listeners syntax

### ISSUE THREAD

**Issue by moonshaadow** [jean-emmanuel/open-stage-control#597]
Hi there.

OSC listeners need sometimes to use differents arguments than preArgs.

Example : `SooperLooper`

To send values to SL "global input gain" we need to use `/set [input_gain]` with no more args.
To listen values from SL "global input gain" we need to use` /sl/global [-2, 'input_gain']`, so it's different preArgs.

For now, if, I'm not wrong, OSC listeners can use preArgs, or can bypass them by 'false'. Why not let us type the args, like this : `OSC{adress, default, argument}` or `OSC{adress, default, [i,s,f]}`

**Comment by moonshaadow** [comment]
As a workaround, I can use here two widgets with same linkID. But it could be nice to do the same thing with only one widget.

**Comment by jean-emmanuel** [comment]
I've decided to leave it as is: complex use cases can now be easely solved with the use of a "variable" widget and a @{} block.
