### ISSUE TITLE
multiclient sync problem

### ISSUE THREAD

**Issue by jgastonraoul** [jean-emmanuel/open-stage-control#598]
Hi,

Since release 0.48.7, I have a problem while trying to sync multiple clients.
If I do not set any input OSC port in app preferences while having a target set for a widget, when I change a value on a client, the others do not update.
Before this release, it was working flawlessly.

Any idea of what has changed ?

regards,

Jérémie

**Comment by jean-emmanuel** [comment]
Hi,
Does it occur with v0.49.6 ?

**Comment by jgastonraoul** [comment]
Hi,

Yes it does.
Please find an exemple file where I have the problem (maybe there is something I do wrong...).

Regards,

[MO.json.zip](https://github.com/jean-emmanuel/open-stage-control/files/4292505/MO.json.zip)

**Comment by jean-emmanuel** [comment]
Thanks, I thought I had fixed it, but I made a mistake. It should be fixed in v0.49.7 (uploading atm).

**Comment by jgastonraoul** [comment]
Thanks for the quick fix !
I looks like you're having problems with your continuous integration builds so I'll wait there is a Mac release before to test !

**Comment by jean-emmanuel** [comment]
It's online now.

**Comment by jgastonraoul** [comment]
I've tested it and it's way better !
But I've discovered a problem with rgb widget : if I set range from 1 to 1.1, it doesn't update well between clients...
You can test with the file of my previous message (tab : "COULEURS", widget "COULEURS_FB").

**Comment by jean-emmanuel** [comment]
It's fixed in the v1 branch that's not online yet, I'm not sure to do a backport fix release for this though.

**Comment by jgastonraoul** [comment]
Ok, thanks !

Do you have an idea of when the v1 will be out ?

**Comment by cyberic99** [comment]
> It's fixed in the v1 branch that's not online yet, I'm not sure to do a backport fix release for this though.

@jean-emmanuel  you already talk a lot about v1, about not backporting fixes to the "current" branch...

please do not forget, that for now, all the users are still using the 'old' branch ;-)

That said, the v1 features you mentioned in various places seem very interesting.

I think too that it is a good idea to rework/respin o-s-c after all the changes/features/bugifxes/use cases seen during these last years ;-)

count on me to test it once it is released, even in beta...

I just fear about the time I'll spend redoing everything identical in the new version ;-(

**Comment by jean-emmanuel** [comment]
> please do not forget, that for now, all the users are still using the 'old' branch ;-)

There may be a few backport releases for critical bugs, but maintaining v0 and v1 is just not possible for me.

> I just fear about the time I'll spend redoing everything identical in the new version ;-(

My 2 cents: don't update it if it works.

**Comment by jean-emmanuel** [comment]
> Do you have an idea of when the v1 will be out ?

Not yet, but I'll post about it (soon hopefully) on the forums.

**Comment by GeneralMidi** [comment]
> > Do you have an idea of when the v1 will be out ?
> 
> Not yet, but I'll post about it (soon hopefully) on the forums.

Can't wait!

**Comment by jean-emmanuel** [comment]
> if I set range from 1 to 1.1, it doesn't update well between clients...

Turns out it wasn't fixed in v1 either, so fixed it in both branches

**Comment by jean-emmanuel** [comment]
fixed in v0.49.8
