### ISSUE TITLE
[Feature] Add Basic Plotting Support

### ISSUE THREAD

**Issue by fundamental** [jean-emmanuel/open-stage-control#6]
Adding some basic non-interactive plotting of data points could be used to better visualize the state of OSC controlled data. Examples of such data include ADSR envelopes, filter graphical responses, and raw waveforms.

**Comment by jean-emmanuel** [comment]
Alright, it seems we've got something working here, check out the demo app and read [this](https://github.com/jean-emmanuel/open-stage-control/blob/master/resources/docs/widgets-reference.md#plot) !

**Comment by jean-emmanuel** [comment]
Load [example/plot.js](example/plot.js) for a simple example.

**Comment by fundamental** [comment]
After reading through the doc & src it looks like this only supports a collection of widget id's which have a scalar type (e.g. a single float) or literals. Would it be possible to generalize support s.t. something like

> points : ["waveform_data"]

where waveform_data returns a collection of float data? (e.g. [fffffffffffffffffffffffffffff])

**Comment by jean-emmanuel** [comment]
No reason not to do so, indeed !

**Comment by jean-emmanuel** [comment]
Okay, some updates : 
- `points` can be :
  - a single string (widget id) for multiple values to be displayed
  - an array of [x,y] coords, which can be numbers or strings (widget id) 
- the widgets receives osc now, it interprets the received array as y-coordinates, evenly spaced on the x-axis

The example session has been updated (also contains a new plotting widget, the visualizer)

**Comment by fundamental** [comment]
I just got a chance to test this and everything seems to be working as I'd expect. I'll have to mess around with zyn to get some real data for it to consume, but this is looking pretty nice so far.

OT, you have a typo in run-from-sources.md where you have "cd Open-Stage-Control/", but in reality it is "cd open-stage-control/"

**Comment by jean-emmanuel** [comment]
Thanks, i'm fixing it right now
