### ISSUE TITLE
impossible d'ouvrir la démo avec un ipad

### ISSUE THREAD

**Issue by guitmart** [jean-emmanuel/open-stage-control#60]
Bonjour Jean emmanuel,
J'adore ton application et elle fonctionne très bien entre 2 pc sur le même réseau.
J'ai essayé avec un ipad mini avec chrome installé version 58.0.3029.83 mais cela ne fonctionne pas, alors j'ai essayé la démo et rien ne se passe non plus. Version IOS 9.3.5.
Je ne comprends pas pourquoi çà ne fonctionne pas.
Merci.
Cordialement Martin.

**Comment by jean-emmanuel** [comment]
Salut Martin, merci pour ton retour !
Peux tu lancer l'application depuis un terminal ? Cela permettrai de récupérer un éventuel message d'erreur lors de la connexion de l'ipad.

**Comment by guitmart** [comment]
Quand tu parles de lancer avec le terminal, tu parles de le lancer en ligne de commande exemple
start open-stage-control -s 192.168.0....:8000 -p 9000 -d ?
Je ne peux pas le faire  pour l'instant mais je vais le faire ce soir vers 20:00, heure du Québec.
Merci pour le retour

**Comment by guitmart** [comment]
Bonjour Jean Emmanuel,
J'ai lancé l'app en ligne de commande sans erreur mais quand je me connecte avec l'ipad rien ne se passe dans la console. L'ipad se connecte au serveur car il trouve l'adresse mais l'écran reste bleu foncé.
Si je me connecte avec un pc tout fonctionne et si j'ajoute -d pour débugger les messages alors je vois défiler les données OSC.
Même chose si j'utilise le port 8080 ou 9000.

**Comment by guitmart** [comment]
J'ai essayé avec un ipad dernière génération avec ios 10 et ça fonctionne mais pas avec l'ipad mini ios 9.

**Comment by jean-emmanuel** [comment]
Ok, je ne vois pas ce ça peut être du coup, peut être un bug de chrome sur io9...

**Comment by guitmart** [comment]
Je crois que c'est la compatibilité des [Arrow functions](http://stackoverflow.com/questions/37096005/how-to-make-arrow-functions-work-on-ios-9-3-1) voir "npm install babel-cli babel-preset-es2015" dans l'exemple et voici la [liste des compatibilités](https://kangax.github.io/compat-table/es6/#test-arrow_functions)

**Comment by jean-emmanuel** [comment]
Le navigageur integré de io9 semble poser problème en effet, mais pas chrome; lances-tu bien Chrome sur l'ipad ? (installer Chrome ne remplace pas le navigateur par défaut)

**Comment by jean-emmanuel** [comment]
Autant pour moi, il semble que Chrome fonctionne avec quelques restrictions sous ios9...

**Comment by guitmart** [comment]
Oui je lance bien Chrome sur l'ipad et quand j'ouvre la page de compatibilité il m'indique qu'il n'est pas compatible.

**Comment by jean-emmanuel** [comment]
Ce sera réglé dans la prochaine version, les scripts sont maintenant transpilés automatiquement vers une version du langage plus compatible. La demo en ligne devrait déjà fonctionner.

**Comment by guitmart** [comment]
Super j'ai essayé la démo et ça fonctionne comme pour l'autre ipad ios10.
Je te remercie :).
Je suis entrain de faire un template pour le logiciel de MAO Reaper et je crois qu'il y aura quelques utilisateurs de plus pour open stage control.
Thanks.

**Comment by jean-emmanuel** [comment]
Cool !!
