### ISSUE TITLE
[Feature] Android

### ISSUE THREAD

**Issue by hellishvictor** [jean-emmanuel/open-stage-control#600]
Any plans on short term about release OSC for the Android Platform?

**Comment by jean-emmanuel** [comment]
No, o-s-c is a desktop software only.

**Comment by jean-emmanuel** [comment]
Just in case, it may be possible to make it work on Android, but it's definitely not supported : https://github.com/jean-emmanuel/open-stage-control/issues/405

**Comment by hellishvictor** [comment]
Awesome :)

**Comment by hellishvictor** [comment]
Awesome :)
