### ISSUE TITLE
[Feature] Move store settings file ".open-stage-control" to install folder.

### ISSUE THREAD

**Issue by hellishvictor** [jean-emmanuel/open-stage-control#601]
Here in W7x64 all the settings of OSC are stored on **C:\Users\Administrador\ .open-stage-control**.
It would be awesome if were possible select where this file is stored, or at least, put it on the same folder where the executable is installed; that way, OSC can be launch as portable (you'll only need have already installed on your system python).

**Comment by jean-emmanuel** [comment]
Actually it seems the most standard way would be to put it with the cache folder (the one in [...]/Roaming/).

**Comment by jean-emmanuel** [comment]
`--cache-dir` & `--config-file` options will be added to allow that.

**Comment by hellishvictor** [comment]
Looking forward for the next release +1:
