### ISSUE TITLE
[Feature] Downloable Docs/Manual on html, CHM format or PDF

### ISSUE THREAD

**Issue by hellishvictor** [jean-emmanuel/open-stage-control#602]
Have the option of download the [manual/docs](https://openstagecontrol.ammd.net/docs/getting-started/) so it can be used offline will be really helpful :)

**Comment by jean-emmanuel** [comment]
Indeed!

**Comment by jean-emmanuel** [comment]
As of next version the documentation website will packaged with the app, running `open-stage-control --docs` from a terminal or clicking on the launcher's `Documentation` menu entry will serve it locally and open in with the system's defaut browser.
