### ISSUE TITLE
[Bug] 2 releases tagged for 0.49.8

### ISSUE THREAD

**Issue by trebmuh** [jean-emmanuel/open-stage-control#603]
[Ici](https://github.com/jean-emmanuel/open-stage-control/releases/tag/v.49.8) et [là](https://github.com/jean-emmanuel/open-stage-control/releases/tag/v0.49.8).

<mode highlander = on>il ne doit en rester qu'un ! `<mode highlander = off>`

**Comment by jean-emmanuel** [comment]
merci, corrigé!
