### ISSUE TITLE
Check in drop down menus are not updated 

### ISSUE THREAD

**Issue by Normandeau** [jean-emmanuel/open-stage-control#604]
Please provide as much contextual informations as possible:

- Open Stage Control version (or commit if built from sources)
0.49.11
- Operating system
MacOS 10.14.6
- Open Stage Control options
none
- Client type (built-in or external chromium/chrome browser) and version
Chrome
- Session file (can be uploaded after adding the .txt extension)
ControlGrisOSC
- Custom module
None
- Server logs (from the terminal or the launcher's console)
- Client logs (hit F12 in chromium/chrome to open the console)
- Screenshot

We are using Open Stage Control to send OSC data to a plugin called ControlGRIS. It works pretty well in both directions, which means that OSC data is sent to ControlGRIS and vice versa. Except for one little thing. We have two drop down menus in ControlGRIS: Source Link and Source Link Alt. When one of the options is chosen, it's updated in both ways, except that in Open Stage Control,  there is a check (√) beside the chosen menu which doesn't exist in ControlGRIS. If the option is changed in ControlGRIS, the option is changed accordingly in the iPad, but the check stays to the previous option.

See the joint image:
![Open Stage Control Check](https://user-images.githubusercontent.com/8959779/77261122-94f68480-6c62-11ea-87f2-d74a81ff2063.jpg)

ControlGRIS is available here:
https://github.com/GRIS-UdeM/ControlGris/releases

ControlGrisOSC.json is here:
https://github.com/GRIS-UdeM/ControlGris/blob/master/ControlGrisOSC.json

**Comment by jean-emmanuel** [comment]
Thanks for the detailed report. 

Is the dropdown menu already opened on the iPad when the value changes ? This widget relies on the system's dropdown implementation is somewhat limitated: the check mark is only updated when the menu opens. The only fix I found is to simply close the dropdown when it receives a value while opened.

**Comment by Normandeau** [comment]
No, the drop down menu is not open in the iPad. But there is no difference in the behaviour, whether the drop-down menu is opened or not. The option with a check mark is never the good one if it was changed from the ControlGRIS. But as the option that shows is the real active one, it's not really an issue. It's mostly cosmetic. We have had also a check mark in ControlGRIS that we just removed because essentially it is a pleonasm.

**Comment by jean-emmanuel** [comment]
Ok, last question: when OSC receives a value, does the check mark never update or does it always update to the value under the correct one ?

**Comment by Normandeau** [comment]
The check mark stays at the option chosen on the iPad. In this case, let's say I chose Circular on the iPad. After that, whatever the option I chose In ControlGRIS (Independent. Fixed Radius, etc.), Circular remains checked.

**Comment by Normandeau** [comment]
Also, a question: why thee is an empty slot in the drop-down menu:
![Capture d’écran, le 2020-03-23 à 11 23 19](https://user-images.githubusercontent.com/8959779/77332797-e7828000-6cf8-11ea-9770-370c879d0405.jpg)

have we made amistake here:

**Comment by Normandeau** [comment]
Go to Github to see the second part of the message. My post was sent too early!

**Comment by jean-emmanuel** [comment]
It may be a bug in this particular version of iOS, the one I could test did not behave that way. Do you know which iOS/iPad version you're using ?
 
> Also, a question: why there is an empty slot in the drop-down menu:

It is indeed a questionable design choice I made long ago and that I'm getting rid of in v1.

**Comment by Normandeau** [comment]
iPadPro iOS 13.3.1

**Comment by jean-emmanuel** [comment]
I confirm, the bug only occurs on iOS 13, it should be fixed in v0.49.12 (last v0 release).

**Comment by Normandeau** [comment]
v0.49.12
Solved

**Comment by jean-emmanuel** [comment]
Great !
