### ISSUE TITLE
[Bug] widgets with same address but different targets update each other

### ISSUE THREAD

**Issue by jgastonraoul** [jean-emmanuel/open-stage-control#605]
In release 0.49.11, I've a problem with widgets using the same address on different targets that update each other...
Is it a normal feature ? If yes, how to avoid that ?

Regards,

Jérémie

**Comment by jean-emmanuel** [comment]
Do the widgets have the same id or linkId ? If so, you need to make change one of them to avoid that.

**Comment by jgastonraoul** [comment]
I can confirm that the widgets have no linkId, different ids and different targets, but they are synchronized as long as they have the same OSC address...

**Comment by jean-emmanuel** [comment]
Can you post a minimal session to help me reproduce the issue ?

**Comment by jgastonraoul** [comment]
Here is an exemple...

[2020-03-23_13_34.json.zip](https://github.com/jean-emmanuel/open-stage-control/files/4369676/2020-03-23_13_34.json.zip)

**Comment by jean-emmanuel** [comment]
Loading your example with all server options to default does not produce the error.

**Comment by jgastonraoul** [comment]
I think I've located the problem...
And I have a question : if I set a default "send" option in O-S-C startup interface and a different "target" in the widgets, does it send to the default send AND specific target or does the "target" override the default "send" ?

**Comment by jean-emmanuel** [comment]
It sends to both unless the widgets has a `null` target: `["localhost:5555", null]` would bypass the server's target.
https://openstagecontrol.ammd.net/docs/widgets-reference/#osc

**Comment by jgastonraoul** [comment]
Ok, thank you ! I was thinking that "target" was overriding "send".

Regards,

Jérémie
