### ISSUE TITLE
[Bug] Can't use --send argument when building from tip of master

### ISSUE THREAD

**Issue by philipstarkey** [jean-emmanuel/open-stage-control#607]
I was attempting to build from source today, which seemed to work, but it would not accept anything for the --send command line argument when attempting to launch. Diving into the source code it looks like some erroneous spaces were added to the regex here: https://github.com/jean-emmanuel/open-stage-control/commit/a588fb2b4a06fffc36a5294e815b3ac04f461d31#diff-e41fd35d2c0e16ad123b0928bcd0dde7

Particularly the space in {4, 5} seems to cause a problem (according to testing on regex101.com) but I suspect the other spaces are probably also not meant to be there (otherwise users need to specify it as "host: port" instead of "host:port" on the command line)

**Comment by jean-emmanuel** [comment]
Fixed, that was a replace error. v1 is not released yet, using source builds is notto be consirdered safe at the moment.

**Comment by jean-emmanuel** [comment]
(also thanks for the accurate report :))
