### ISSUE TITLE
[Bug] prise en compte des paramètres lors d'un lancement avec npm start

### ISSUE THREAD

**Issue by nlebellier** [jean-emmanuel/open-stage-control#610]
Version : v1.alpha2

![Capture d’écran_2020-04-06_09-26-01](https://user-images.githubusercontent.com/4880966/78533285-01d45780-77e9-11ea-8f0b-ce0642ee2620.png)

les paramètres passés dans la ligne de commande ne sont pas repris totalement et persistent les paramètres auparavant existants.

**Comment by jean-emmanuel** [comment]
Peux-tu détailler ? Quel paramètres ne sont pas pris en compte ?

**Comment by jean-emmanuel** [comment]
Ah, tu as oublié le `--` après `npm start`

**Comment by nlebellier** [comment]
oups... désolé
la bonne syntaxe :
```
npm start -- --send 127.0.0.1:4560 --port 8085 --osc-port 7777 ----instance-name myInstanceName --ad ~/audio/OpenStageControl-scripts/3_faders_3_pushes-o-s-c-v1.json
```
