### ISSUE TITLE
[Bug] Can not declare more than one midi port

### ISSUE THREAD

**Issue by ejhense** [jean-emmanuel/open-stage-control#612]
In V1 alpha 3 on windows 10 professional can not declare more than 1 midi port. If I do I get the message: (INFO) Server stopped.

**Comment by jean-emmanuel** [comment]
Can you paste your midi config here please ?

**Comment by ejhense** [comment]
This one works: 
OSC:10,11
This one does not:
OSC:10,11 OSC_ks:11,12 
(I did not put midi-- in front...)

**Comment by jean-emmanuel** [comment]
Thanks, does it work with `OSC_ks:11,12` only ? Just in case, could you save your server config (menu>save) and upload the file here ?

**Comment by ejhense** [comment]
yes it does work with every single declared midi port.
[OSC1.zip](https://github.com/jean-emmanuel/open-stage-control/files/4464555/OSC1.zip)
Thanks for the extremely fast reaction! :-)

**Comment by jean-emmanuel** [comment]
No problem ;)
The config looks fine (btw setting port to 8080 is not required, it's the default value).
Does the "List MIDI Devices" menu action work ?

**Comment by jean-emmanuel** [comment]
Nevermind my last question, if single port declarations work then the python-rtmidi package is working.

**Comment by jean-emmanuel** [comment]
Where you using v0 before ? Did such a config work then ?

**Comment by jean-emmanuel** [comment]
Maybe related to https://github.com/jean-emmanuel/open-stage-control/issues/576

**Comment by ejhense** [comment]
I have a V0 template with seperate midi ports for Dorico, Wavelab, Cubase keyswitches, Cubase remote etc. which works perfectly.

**Comment by jean-emmanuel** [comment]
Could you try running the server in terminal ?
```
open-stage-control.exe -- --midi OSC:10,11 OSC_ks:11,12 --send 192.168.178.31:7001
```

**Comment by jean-emmanuel** [comment]
I figured it out, I'll upload alpha 4 soon.

**Comment by ejhense** [comment]
Excellent!

**Comment by ejhense** [comment]
Hi! 
Sorry to bother you again...
[OSC_screenshot.zip](https://github.com/jean-emmanuel/open-stage-control/files/4465327/OSC_screenshot.zip)
I think there's a typo in alpha 4. It now opens a second 'terminal' and a blank main screen. See attached screenshot.

**Comment by jean-emmanuel** [comment]
Hi, thanks for testing, I'm uploading alpha5 which fixes it I hope, let me know.

**Comment by jean-emmanuel** [comment]
Alpha 5 is online.

**Comment by ejhense** [comment]
Fixed! Thanks!

**Comment by jean-emmanuel** [comment]
Great !
