### ISSUE TITLE
[Bug] css: line-height property not working

### ISSUE THREAD

**Issue by ejhense** [jean-emmanuel/open-stage-control#616]
Hi! In alpha 12 on windows 10 the css line-height property for buttons  does not work(on my system). Other properties like font-size, letter-spacing  are just fine.

Kind greetings,

Erik

**Comment by jean-emmanuel** [comment]
Hmm, currently you need to target the `label` element to make it work because of a small mistake I made. It's now fixed in git.

**Comment by ejhense** [comment]
Great, thanks!
