### ISSUE TITLE
[Bug] matrix : traversing mode not working in iOs

### ISSUE THREAD

**Issue by matcham** [jean-emmanuel/open-stage-control#617]
O-S-C v1.0.0-alpha12

matrix traversing mode works as expected in chrome in macOs, but not in safari / chrome in iOs (13.4.5) (iPad)

[matrix traversing not working in ios.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/4539434/matrix.traversing.not.working.in.ios.json.txt)

**Comment by jean-emmanuel** [comment]
Thanks, fixed in git.
