### ISSUE TITLE
[Bug] no scrollbar in iOS 13

### ISSUE THREAD

**Issue by matcham** [jean-emmanuel/open-stage-control#618]
O-S-C v1.0.0-alpha12

iPad + safari / chrome
Session --> open : file browser 
unable to scroll in file browser. I can only select a file or click on Cancel / Open buttons

(this used to work as expected in O-S-C 0.49.x )

**Comment by jean-emmanuel** [comment]
Confirmed (on iOS 13 only).

**Comment by jean-emmanuel** [comment]
It seems io13 disables all scrollbars, I haven't found a way to fix this yet.

**Comment by jean-emmanuel** [comment]
Scrolling is fixed in git, however scrollbars are tied to the os default styling, iOS13 doesn't honor scrollbar styling anymore.

**Comment by jean-emmanuel** [comment]
Fix included in alpha 14
