### ISSUE TITLE
[Bug] - custom-module parameter can't handle path with space

### ISSUE THREAD

**Issue by mikerodd** [jean-emmanuel/open-stage-control#619]
- Open Stage Control version : Alpha 12
- OS : Ubuntu 19.10
- Custom module : open a custom module with a space in the directory (it seems to work fine with other parameters, like "load")
- Server logs : 
`(ERROR) --custom-module: Custom module file not found: /home/michel/data/05.,musique/2019/OpenStageControl/nsm/nsm-serverlist.js`
(the file is : ~/data/05. musique/2019/OpenStageControl/nsm/nsm-serverlist.js)
- Screenshot
![image](https://user-images.githubusercontent.com/4293086/80465625-a3a81980-893b-11ea-81d1-d5a077b0eb98.png)

**Comment by jean-emmanuel** [comment]
Thanks, fixed in git.
