### ISSUE TITLE
[Feature] custom spring location for xy Pad widget

### ISSUE THREAD

**Issue by AlexanderVartzbed** [jean-emmanuel/open-stage-control#620]
Right now it always springs back to the lowest value, makes using it like a "joystick" not possible instead, can one have custom Spring back positions?
So when one sets the min x and y to -1 and the max to 1, then maybe one could set 0,0 as the custom spring back point or even arbitrary numbers like X:0.75, Y:-1.

**Comment by jean-emmanuel** [comment]
Setting the `default` property does that, for example to `[0, 0]` for x:0 and y:0.

**Comment by AlexanderVartzbed** [comment]
this doesnt appear to be working :(

**Comment by jean-emmanuel** [comment]
Cool !
