### ISSUE TITLE
[Bug] Erreur Javascript à partir d'un ipad

### ISSUE THREAD

**Issue by tharosd** [jean-emmanuel/open-stage-control#621]
- Open Stage Control version : 1.0.0 beta 14
- Operating system: osx 10.15.3 catalina

Bonjour,

OSC fonctionne tres bien en local sur mon iMac à partir de Chrome. Avec mon écran de test, le click sur le bouton envoie bien la note configurée dans mon DAW (Studio One). L'evenement midi est bien présent et la note peut être enregistrée dans une piste midi. ça fonctionne.

En revanche à partir de mon iPad, quand j'appelle l'url du serveur OSC à l'adresse 192:168.1.9:8080, l'écran de test ne se charge pas (uniquement le fond d'écran noir d'OSC avec la barre bleu horizontal en haut et les 3 points blancs en haut à gauche qui ouvre les menus quand on clic dessus). Mon bouton de test n'est pas affiché et dans la console OSC est affiché une erreur javascript (voir screenshot)

<img width="753" alt="Capture d’écran 2020-05-01 à 10 19 32" src="https://user-images.githubusercontent.com/2097791/80793223-d69a1980-8b96-11ea-81c3-1534b0f848c5.png">

<img width="663" alt="Capture d’écran 2020-05-01 à 10 22 26" src="https://user-images.githubusercontent.com/2097791/80793229-da2da080-8b96-11ea-9cb6-87745262fd09.png">

Je ne trouve pas la solution ou mon erreur ? 

Merci pour l'aide

**Comment by jean-emmanuel** [comment]
Salut, il y avait bien un souci d'empaquetage pour iOS 10,  c'est réglé pour la prochaine version. En revanche si ton iPad tourne sous iOS 9, cette version n'est plus supportée.

**Comment by tharosd** [comment]
Parfait. Mon ipad est sous ios 10.3.3
Merci pour la réponse rapide. Je vais attendre alors la prochaine mise à jour

**Comment by jean-emmanuel** [comment]
-> alpha 15
