### ISSUE TITLE
[Bug] - when creating new session, window title display old one 

### ISSUE THREAD

**Issue by mikerodd** [jean-emmanuel/open-stage-control#622]
- Open Stage Control version : Alpha 15
- Operating system Ununtu 19.04
- Client type : built-in
- Screenshot
![Peek 04-05-2020 22-17](https://user-images.githubusercontent.com/4293086/81009568-2efe3f00-8e55-11ea-9c4a-dbcfb6db2253.gif)

**Comment by jean-emmanuel** [comment]
Thanks, fixed in git.

**Comment by jean-emmanuel** [comment]
-> alpha 16
