### ISSUE TITLE
[Bug] led: wrong opacity when mode == "color"

### ISSUE THREAD

**Issue by RBasile** [jean-emmanuel/open-stage-control#624]
In the beta 1 and build-in client
with a led in rgb mode
setting the range to 
```
{
  "min": 0,
  "max": 255
}
```
make the opacity of the element very low
![image](https://user-images.githubusercontent.com/13667769/81939173-44fac500-95f6-11ea-853f-ec5b99cc6b13.png)

it make the led color very dim 
![image](https://user-images.githubusercontent.com/13667769/81939374-87240680-95f6-11ea-9810-ee91b3f6e52c.png)

[led range .json.txt](https://github.com/jean-emmanuel/open-stage-control/files/4628649/led.range.json.txt)

**Comment by jean-emmanuel** [comment]
Thank you, it's fixed now.

**Comment by jean-emmanuel** [comment]
Fixed in beta 2.
