### ISSUE TITLE
Advanced syntax : key instead of label for value

### ISSUE THREAD

**Issue by paulmacmillan** [jean-emmanuel/open-stage-control#625]
Hi Jean-Emmanuel, first of all thank you for the amazing work you're doing on this project !
Truly mind blowing.

## Here is the situation :
if we have a switch component with a `values` field like :
```
{
    "homer": simpson,
    "rick": morty
}
```
Is there a way, when using the advanced syntax (`@{id.value}`) to set the `label` field of another component, to use the key (or label as described in the documentation) (here it would be homer) instead of the value (simpson).

Been reading the doc for hours now and cannot find the way to do it.

Thanks for your help

**Comment by jean-emmanuel** [comment]
In case this was closed by accident, here is a snippet:
```javascript
JS{{
var object = @{switch_1.values},
    value = @{switch_1}
return Object.keys(object).find(key => object[key] === value)
}}
```
Source: https://stackoverflow.com/a/28191966

**Comment by paulmacmillan** [comment]
Thank you for your help ! So fast as usual. In fact I found another solution you posted on discourse and didn't want to bother you ^^
Btw, very of you to give the explanation for the solution though so we can better understand.
