### ISSUE TITLE
[Bug]   exponantial -1 value on logScale option(fader) doesn't work

### ISSUE THREAD

**Issue by dewiweb** [jean-emmanuel/open-stage-control#626]
- Open Stage Control version v1.0.0-beta7
- Ubuntu 18.04 64bits
- Open Stage Control options: local
- Client type (built-in ) 

"true" and "false" work fine but with "-1" o-s-c just send the first value but after nothing else (my range is from -128 to 15)

**Comment by jean-emmanuel** [comment]
Thanks, fixed in sources.

**Comment by jean-emmanuel** [comment]
-> beta8

**Comment by dewiweb** [comment]
Ok thanks
