### ISSUE TITLE
Undo not working

### ISSUE THREAD

**Issue by 80icio** [jean-emmanuel/open-stage-control#629]
Undo is not really working for me, if i accidentally delete a widget there's no way to go back

**Comment by jean-emmanuel** [comment]
> Please provide as much contextual informations as possible:
>- Open Stage Control version (or commit if built from sources)
>- Operating system
>- Open Stage Control options
>- Client type (built-in or external chromium/chrome browser) and version
>- Session file (can be uploaded after adding the .txt extension)
>- Custom module
>- Server logs (from the terminal or the launcher's console)
>- Client logs (hit F12 in chromium/chrome to open the console)
>- Screenshot

**Comment by 80icio** [comment]
Mac Os 10.13.6 (17G10021)
OSC v1.0.0 beta7

![OSC undo bug](https://user-images.githubusercontent.com/67228387/85232335-76895c00-b3fe-11ea-92bd-88faaebf1494.gif)

**Comment by jean-emmanuel** [comment]
Thank you. The undo action you are using is not related to the editor, it's a generic undo/redo action that acts on text inputs only, you need to use the client app menu actions (upper left 3-dots button) or hit cmd+z while *not* writing in a text input.
