### ISSUE TITLE
How to implement a EQ kill and a conditional spring

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#63]
Hello

First of all, thank you for this software, it is incredibly easy to create a powerful interface!
I have two questions, maybe it is not the best place to ask because these are not really issues... just tell me is there is a better way.

I) I would like to implement a 3 band mixer, with a kill switch

Each band is made of a knob and a kill.

1. When the kill switch is on, one can move the knob, but it must not send any value (or it can send the min knob value).
2. When the switch is released, the knob must immediately send its value, then act normally.

Do you think it is possible to implement?
Even by using a custom module, the second item might be tricky because it needs to know the current value of the knob...

Maybe the right way would be t use a formula...
Could you please add a concrete example in the docs?

II) I also wanted to know if the 'spring' property of an object can depend on a switch...
If the switch is on, spring is true. else sprint if false.

Thank you

**Comment by jean-emmanuel** [comment]
Thanks for your feedback, it is really appreciated !

I) The right would be with a formula, I just pushed an extra [`condition`](http://osc.ammd.net/user-guide/widgets-specifics/maths/#condition) option to it to make it possible, it will be included in next release.

II) Widgets properties can't be linked to each other in a clean way but there is a way... yet a bit hacky but still, you could send /EDIT_SOFT to app itself for editing the widget. Try the attached session file (remove the .txt, github doesn't accept .js) with the latest master build (I just fixed a tiny bug that's making this fail)

[selfedit.js.txt](https://github.com/jean-emmanuel/open-stage-control/files/1014113/selfedit.js.txt)

**Comment by jean-emmanuel** [comment]
0.17.8 is out !
