### ISSUE TITLE
[Feature] Indiquer 0 appareil midi détecté

### ISSUE THREAD

**Issue by nlebellier** [jean-emmanuel/open-stage-control#631]
Lorsqu'on lance la découverte des ports midi, List Midi Devices, si aucun appareil est détecté, un petit message rassurerait tout le monde sur le fait que la commande a bien eu lieu.
A noter que sous windows 10, il ne liste pas en tant qu'Output Microsoft GS Wavetable Synth 0 si aucune entrée est détectée.

**Comment by jean-emmanuel** [comment]
La commande indique à minima ceci :
```
(INFO, MIDI) Inputs
    -1: Void (bypass)
(INFO, MIDI) Outputs
    -1: Void (bypass)
```

Il y a donc bien un retour quant à l'execution de la commande à mon sens.

**Comment by nlebellier** [comment]
ah je n'ai rien vu sous windows 10. Je vérifierai.

**Comment by nlebellier** [comment]
Je confirme pas de message la preuve en image :

Si aucun midi device de lancé, pas de retour mais pas la table midi de windows

![noMidiNoMessageWin10](https://user-images.githubusercontent.com/4880966/85520344-0f88c480-b603-11ea-8641-3cbe530d4c46.gif)

Si je lance loopMidi, retour car devices détectés 
![noMidiNoMessageWin10-02](https://user-images.githubusercontent.com/4880966/85520737-9a69bf00-b603-11ea-9bb5-fca78353e9fc.gif)

**Comment by jean-emmanuel** [comment]
Alors c'est que le fonction n'est pas appelée du tout et que quelque chose échoue en silence... peux tu lancer cela dans un terminal et copier le retour ici ?
```
cd chemin\vers\app\server\python
python list.py
```

**Comment by nlebellier** [comment]
```
nlb@speedy MINGW64 /d/audio/open-stage-control/app/server/python (master)
$ npm --version
6.9.0

nlb@speedy MINGW64 /d/audio/open-stage-control/app/server/python (master)
$ node --version
v12.3.1

nlb@speedy MINGW64 /d/audio/open-stage-control/app/server/python (master)
$ python list.py

MidiInWinMM::initialize: no MIDI input devices currently available.

["log", "(INFO, MIDI) Inputs\n    -1: Void (bypass)\n(INFO, MIDI) Outputs\n    -1: Void (bypass)\n    0: Microsoft GS Wavetable Synth 0"]

nlb@speedy MINGW64 /d/audio/open-stage-control/app/server/python (master)
$

```
mais pas de retour dans la console de la fenêtre de lancement O-S-C

**Comment by jean-emmanuel** [comment]
Ça y est, j'ai compris ! C'est corrigé dans les sources.

**Comment by jean-emmanuel** [comment]
-> beta 8

**Comment by nlebellier** [comment]
Je confirme tout fonctionne ! Merci
