### ISSUE TITLE
Autostart & hidden centext menu

### ISSUE THREAD

**Issue by ManuelWaldmann** [jean-emmanuel/open-stage-control#632]
Hi,

I'm thrilled with your 1.0 version. It works wonderful for me.

At the moment I try to deactivate the context menu button in my own theme. But I fail in my own abilities.
Does it even work? Can you help me?

I want the server to run on a Raspbery Pi.
When the Pi starts, the server should also start automatically. With the right settings and the right file. Of course you can do that with the terminal, but here I also fail. 
Can you describe this in more detail than in the documentation.

Thank you for your great work!
Manuel

**Comment by jean-emmanuel** [comment]
Hi !

> At the moment I try to deactivate the context menu button in my own theme. But I fail in my own abilities.

This works when put in a theme file:

```css
osc-toolbar {display:none;}
```

> Can you describe this in more detail than in the documentation.

Your command should look more or less like this:
```
open-stage-control --no-gui --load path/to/your/session.json --theme path/to/your/theme.css
```

All available options are documented [here](https://openstagecontrol.ammd.net/docs/getting-started/server-configuration/), you can also run `open-stage-control --help` to display the option descriptions in the terminal.

Please use the forum for further usage question, this tracker is for bug reports.

**Comment by ManuelWaldmann** [comment]
Thanks.
Thank you for pointing to the forum.
Will use this next time
