### ISSUE TITLE
[Bug] Uncaught TypeError: this.remoteControl.exists is not a function

### ISSUE THREAD

**Issue by DoughnutWuff** [jean-emmanuel/open-stage-control#633]
Version: Open Stage Control v1.0.0-beta9
OS: Server is Windows 10 build 2004, Client is a Raspberry Pi 3B+ running Raspbian Buster
Options: Custom HTTP Port, OSC Port and Debug is on
Client Type: External Chromium - both Kiosk and Normal.
Session File: [BMF2020.txt](https://github.com/jean-emmanuel/open-stage-control/files/4866600/BMF2020.txt)
Custom Modules: None
Server Logs: It's full of OSC Debug messages and:
`Uncaught TypeError: this.remoteControl.exists is not a function
    at Osc.receive (osc.js:44)
    at receiveOsc (callbacks.js:23)
    at Array.<anonymous> (index.js:65)
    at Ipc.trigger (event-emitter.js:29)
    at Ipc.receive (index.js:148)
    at WebSocket.socket.onmessage (index.js:99)`

Chromium also shows that error 1000+ times before crashing out due to RAM.
![image](https://user-images.githubusercontent.com/22278710/86408313-ad892880-bcae-11ea-8e12-c3f729866bb3.png)

**Comment by jean-emmanuel** [comment]
Hi, could you please provide the browser's version number ?

**Comment by DoughnutWuff** [comment]
Hi, it's doing it on the most recent Chromium version (fresh install of Raspbian Buster) and also on Chrome version 83.0.4103.116 (Official Build) on Windows 10 Build 2004

**Comment by DoughnutWuff** [comment]
Sorry I didn't get back to you, I'm currently broadcasting a festival and am trying to use OSC to control CasparCG.

**Comment by jean-emmanuel** [comment]
No problem. This error occurs when an osc message is received when the client app initializes, I'm pushing a change that prevents this error.

**Comment by jean-emmanuel** [comment]
Should be fixed in beta 10.
