### ISSUE TITLE
switch reorders values when it receives an object containing pairs of values

### ISSUE THREAD

**Issue by matcham** [jean-emmanuel/open-stage-control#634]
when a switch receives an object containing pairs of values like :
```
(DEBUG, OSC) In:  {
  address: '/mySwitch/values',
  args: '{\r\n\t"Z" : 1,\r\n\t"10" : 2,\r\n\t"A" : 3,\r\n\t"2" : 4,\r\n\t"1" : 5\r\n}\r\n'
} From: 127.0.0.1:60092
```

`{
	"Z" : 1,
	"10" : 2,
	"A" : 3,
	"2" : 4,
	"1" : 5
}`

values are displayed in a different order :
![image](https://user-images.githubusercontent.com/122241/86486874-c9e39e80-bd5c-11ea-8546-dd3d5b3089d0.png)

values are reordered, starting by indexes containing integers, (sorted in ascending order), then letters.

mySwitch values has this script :
```
JS{{
var oscValues = OSC{values}
return oscValues 
}} 
```

I would expect it to respect the order of the values...

**Comment by jean-emmanuel** [comment]
It's a documented limitation : 
> Numeric labels must be prepended or appended with a white space (or any other non-numeric character) otherwise the order of the values won't be kept

**Comment by matcham** [comment]
thanks for your reply and sorry for the noise, I didn't thought it coud be a feature :-)

**Comment by jean-emmanuel** [comment]
No problem !
