### ISSUE TITLE
Automatic conversion yields empty session configuration??

### ISSUE THREAD

**Issue by ke5stl** [jean-emmanuel/open-stage-control#636]
My understanding, based on user interface feedback, is that a legacy session definition is supposed to 'auto convert' to a 1.0 equivalent?

Well, my session .json file, after seeing the announcement that it has been converted, when exported, contains essentially an empty configuration!

Is this the 'correct' behavior?  I'm thinking it should have done the conversion into a working result that looks similar to the original?

I am attaching my config file.

[OSC1.zip](https://github.com/jean-emmanuel/open-stage-control/files/4900137/OSC1.zip)

**Comment by jean-emmanuel** [comment]
Your session raised a case I did not took into account, it is now [fixed](f0951e7aabb07e715878cb6018ec93d000310cc3) in sources for the next release. Meanwhile you can fix it manually simply by removing the first and last square brackets ("[" and "]") in your session file, or by loading and saving the session with the latest v0 release before opening with v1.

Note that the conversion is pretty basic, complex sessions may require many manual adjustments.
