### ISSUE TITLE
new menu 

### ISSUE THREAD

**Issue by walterlutzu** [jean-emmanuel/open-stage-control#637]
Hi! I'm very surprised about the improvements of this project!!!! Thanks a lot!
I need a little help about new menu widget. Is it possible to use it to show/hide a tabs element? How to do it?
Thanks a lot!
Walter

**Comment by jean-emmanuel** [comment]
Hi, would you mind reposting your question on the forums (you can use your github account to connect there) ? Thanks

**Comment by walterlutzu** [comment]
oops, ok thanks!
