### ISSUE TITLE
Question: SVG support

### ISSUE THREAD

**Issue by dosida** [jean-emmanuel/open-stage-control#64]
Hey Jean-Emmanuel,

In its current state does OSC support creating controls based on SVG shapes?

If yes, when you have some free time (which I know doesn't come easy) can you provide us with an example?

If no, would it be a huge change architecture-wise if you add support for SVG that might be calling javascript functions and react to javascript callbacks coming back from OSC?

**Comment by jean-emmanuel** [comment]
Hi,
There is no such thing yet, but it would be nice to have something like it, probably based on canvas rather than svg though. Don't expect it too soon, TODO, they say ;)

**Comment by dosida** [comment]
At least it's on the TODO list that's good enough for now :)
I am sure that at some point that task will be reached :)

**Comment by jean-emmanuel** [comment]
I'm reopining this jst as a reminder ;)

**Comment by cyberic99** [comment]
Would it be possible to support images too?
An image would simply be a widget with a filename and/or a base64content attribute

With this, o-s-c could show graphs, animated gifs, and so on

**Comment by jean-emmanuel** [comment]
Base64 would be a reliable solution. Until a proper widget gets coded, you can acheive this using the `css` property. For example, for a panel widget:
```css
.panel {
  background-image: url(data:image/...);
  background-size: cover;
}
```

**Comment by cyberic99** [comment]
Is it possible to change a picture using OSC?
with /EDIT for instance?

**Comment by jean-emmanuel** [comment]
Yes it is, any property can be edited using OSC. If the container has other css properties that you don't want to send everytime, use its `variables` property to store the base64 string and write the `css` property as follows (it's also useful if you wan't to use the same image multiple times): 
```css
.panel {
  background-image: url(@{this.variables});
  background-size: cover;
}
```

See [property inheritance](http://osc.ammd.net/extras/property-inheritance/).

**Comment by cyberic99** [comment]
Great, thank you!
I'll try that

**Comment by nestanqueiro** [comment]
Hi,
I've just started using your software and it is working very well for a controller I'm designing... So forgive my question but I'm a complete noob... I'm trying to see an image on background of a panel using the css code you show 4 comments before, but I can't figure out where to store the image... where should I place it? can I use a custom URL for my own html server? 
Thanks

**Comment by jean-emmanuel** [comment]
Hi !
It doesn't seem raisonnable to have the app check for static files updates automatically. Editing any property of the widget should be enough to reload the image.

**Comment by nestanqueiro** [comment]
Ok, thanks! 
For the controller I'm writing makes sense to see the image because it's a video controller... no need to have live 25fps update, but needs to actually update... I was using it on a panel, and that component has nothing to update, so I'll try on a diferent component.

**Comment by jean-emmanuel** [comment]
There's actually a little css cache problem too, I'll try to fix it soon.

**Comment by jean-emmanuel** [comment]
I just pushed the image widget _for testing_, it should be included in next release. Updating any of its properties remotely (see [remote control](http://osc.ammd.net/extras/remote-control/)) will reload the image set in its `value` field. It doesn't have a browse function (yet?) but it accepts absolute file paths, urls, and base64 `data:image...` strings.

**Comment by jean-emmanuel** [comment]
Support for the special value `reload` is now implemented.

**Comment by cyberic99** [comment]
Just a quick note to let you know that http:// URLs work, but not https:// ones

**Comment by jean-emmanuel** [comment]
Supporting https would require some extra dependencies and is not something I'd like to implement : security is way out of the app's scope. If you are concerned about safety regarding your O-S-C usage, use a private network ;).

**Comment by cyberic99** [comment]
I get that and you are completely right. It could be useful to mention it clearly in the docs, though.

**Comment by jean-emmanuel** [comment]
Yes that would be a good thing !

**Comment by jean-emmanuel** [comment]
I'm closing this. As for the initial request, custom canvas widget remains something I'd like to try implementing someday.

**Comment by cyberic99** [comment]
I tried to use different types of images: jpg, png, svg, and gif.
It worked with all these types, as long as the correct mime type is used.

**Comment by jean-emmanuel** [comment]
I just pushed an experimental svg widget to master. For now it's a plot widget that can't receive direct interaction but it takes advantage of many cool new features
[svg.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/1719386/svg.json.txt)
, check out the attached session file (with an up-to-date build or in the online demo) ;)
