### ISSUE TITLE
[Feature] Midi input to control UI and bridge OSC messages

### ISSUE THREAD

**Issue by diegodorado** [jean-emmanuel/open-stage-control#641]
It would be awesome to be able to build an UI on open-stage-control which defines simple osc target addresses, but still be able to hook up a midi controller to the UI.
So, upon a midi message received, the UI would be updated, and an osc event would be sent at the same time.

As far as I know this is not currently possible, o rmaybe I am missing something?

**Comment by jean-emmanuel** [comment]
It's possible to do that using a custom module to route incomming midi message so that they update the UI and trigger a reply at the same time, I've added this to the example section : https://openstagecontrol.ammd.net/docs/custom-module/examples/#midi-routing

**Comment by diegodorado** [comment]
thanks! that worked!

**Comment by jean-emmanuel** [comment]
great !

**Comment by diegodorado** [comment]
Just a detail. There is a typo in the example where it defines a var called
rouing onstead of routing
