### ISSUE TITLE
[Feature] How to fill a fader from .5, not 0?

### ISSUE THREAD

**Issue by gwatcha** [jean-emmanuel/open-stage-control#643]
Hey, I made faders to control a bunch of attenuators which don't do anything at .5, and at 1 they send a signal through, and 0 they flip and send a signal through (& values between scale). 

It's hard to see what the value is with the current way the fader is filled, I'd love to be able to fill only from .5 -> .7 (if .7 is the value), or from .5 -> .1 & e.t.c. Preferably green in the first case and red in the second. 

Is there a css trick to do this? I read the documentation but can't figure it out.

And thanks for making this program, I've spent so many hours making a music interface in it and I'm having a blast! Thanks for your hard work.

**Comment by jean-emmanuel** [comment]
Hi, try setting "origin" to `0.5` and "gradient" to
```{
  "0.49": "red",
  "0.5": "green"
}```
