### ISSUE TITLE
File widget not responding to changes in directory in the editor.

### ISSUE THREAD

**Issue by PLu55** [jean-emmanuel/open-stage-control#644]
File widget not responding to changes in the directory property when changing it in the editor, the property is not changed but gets back to what it was before editing.

open-stage-control v1.0.2

**Comment by jean-emmanuel** [comment]
Hi, could you please provide more informations:
- value submitted to the editor
- error in the server's logs (?)
- operating system
- client type (default client or browser / version)

**Comment by PLu55** [comment]
I can not reproduce the problem today. Yesterday I could reproduce the problem several times but not today. Sorry for the inconvenience.
