### ISSUE TITLE
Can't have scrollable panel in modal

### ISSUE THREAD

**Issue by wargreen** [jean-emmanuel/open-stage-control#645]
Hi,
The min-height attibut of .contains-widgets.layout-vertical.panel-container>inner>.widget prevent to have a scrollable panel inside a modal. We can see this in the plugin's modal of ardour-control with a large number of parameters (x42's EQ of instance).
 https://github.com/jean-emmanuel/open-stage-control/blob/master/src/scss/widgets/containers.scss#L81
I havn't seen another effect of this attribut.

Thank you for the work !

**Comment by jean-emmanuel** [comment]
I've added a `contain` property to the panel/modal/tab widgets, when set to false with a vertical/horizontal layout, the children can overflow the panel.

**Comment by jean-emmanuel** [comment]
(ardour-control updated btw)

**Comment by wargreen** [comment]
Thank You !
