### ISSUE TITLE
Ancienne version - 0.23.0

### ISSUE THREAD

**Issue by Adopo** [jean-emmanuel/open-stage-control#646]
Hello. J'espère que tout va bien depuis le temps !

Je continue d'utiliser en long en large et en travers ton super logiciel. 

Et pour le fun je voulais tester l'application AaMakro5oul pour avoir une interface open stage control pour ableton. Cependant elle ne fonctionne qu'avec la 0.23.0...

Par précaution en fonction de mes projets à chaque fois que je télécharge une version d'open stage control je la mets de côté pour ce genre de soucis. mais malheureusement la version la plus lointaine que j'ai c'est la 0.24.0

J'ai voulu récupérer la 23 sur github mais il n'y a plus que le fichier source et... je ne suis pas assez callé pour en faire quoi que ce soit... Comment compile t'on une ancienne version?

Merci d'avance pour ton aide.

**Comment by jean-emmanuel** [comment]
Salut, voilà ce qu'il faut faire :

1. installer [git](https://git-scm.com/) et [node](https://nodejs.org/en/)
2. récupérer les sources
```
git clone https://github.com/jean-emmanuel/open-stage-control
cd open-stage-control/
```
3. basculer sur la version souchaitée
```
git checkout v0.23.0
```
4. installer les dépendance (dans le dossier, cela n'affecte pas le système)
```
npm install
```
5. compiler / générer l'executable (dans le dossier "dist/")
```
npm run build
```

**Comment by Adopo** [comment]
Merci beaucoup pour ta réactivité !!!!! 

J'ai un soucis a partir de l'étape 4 :/ (installation des dépendances) j'ai une erreur.

Voici ce qu'il affiche (j'ai mis aussi le fichier log correspondant)




/Users/adopo/.node-gyp/12.18.3/include/node/v8.h:3135:5: note: candidate
      constructor not viable: requires 2 arguments, but 1 was provided
    Utf8Value(Isolate* isolate, Local<v8::Value> obj);
    ^
1 error generated.
make: *** [Release/obj.target/binding/src/create_string.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/adopo/Downloads/open-stage-control/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/adopo/Downloads/open-stage-control/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/adopo/Downloads/open-stage-control/node_modules/node-sass
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adopo/.npm/_logs/2020-08-25T09_09_46_770Z-debug.log

[2020-08-25T09_09_46_770Z-debug.log](https://github.com/jean-emmanuel/open-stage-control/files/5122684/2020-08-25T09_09_46_770Z-debug.log)

**Comment by jean-emmanuel** [comment]
Zut, il faut utiliser une version de node plus ancienne pour que ça marche, je t'ai uploadé une version déjà compilée sur la page de cette version d'OSC.

**Comment by Adopo** [comment]
merci !!! c'est bon j'ai récupérer. Par contre l'interface de OSC est anormalement sombre.. etrange. Sans doute que la version est trop vieille et qu'il y a des soucis depuis. Pas grave ca me suffira pour tester. Merci !
