### ISSUE TITLE
copy/paste multiple items with id+1

### ISSUE THREAD

**Issue by jgastonraoul** [jean-emmanuel/open-stage-control#648]
When I copy/paste several widgets at one time (for example 5 text widgets), if I paste with ID+1 option, all widgets take the same id.

**Comment by jean-emmanuel** [comment]
Confirmed, thanks for reporting.

**Comment by jean-emmanuel** [comment]
Fixed in sources

**Comment by jean-emmanuel** [comment]
-> v1.2.0
