### ISSUE TITLE
example to split values in XY and RGB widgets

### ISSUE THREAD

**Issue by jgastonraoul** [jean-emmanuel/open-stage-control#649]
Is there an example somewhere of a solution to replace "split"  in XY and RGB widgets, which has been removed from v1 releases ?
The only thing I've found is in the changelog : "pads: removed split property -> use custom-module or script instead"

Thanks !

**Comment by jean-emmanuel** [comment]
Hi, here is an example using a custom module : https://openstagecontrol.ammd.net/docs/custom-module/examples/#arguments-split-merge
Alternatively, you can use the widget's [script](https://openstagecontrol.ammd.net/docs/widgets/scripting/) property:
```js
send("127.0.0.1:5555", "/x", value[0])
send("127.0.0.1:5555", "/y", value[1])
```
