### ISSUE TITLE
Feature request: Configurable OSC address for slider (fader) meter

### ISSUE THREAD

**Issue by riban-bw** [jean-emmanuel/open-stage-control#65]
There is the ability to configure a slider (fader) to show a meter which has a hard-coded OSC address. (Documentation says: "The meter's address will be the same as the widget's with /meter appended to it.")
It would be advantageous to allow the meter's OSC address to be configured individually.

**Comment by wargreen** [comment]
Hey,
+1
Example, for use with Ardour, the gain control is "/strip/gain ssid gain" and the feedback address is "/strip/meter ssid meter"

**Comment by jean-emmanuel** [comment]
Included in 0.17.8.

**Comment by riban-bw** [comment]
Thanks! The documentation needs to be updated.

**Comment by jean-emmanuel** [comment]
[Done](http://osc.ammd.net/user-guide/widgets-specifics/sliders/#meteraddress) ;)

**Comment by wargreen** [comment]
So fast again, Thanks !
Ps: Another OSC's Ardour config, with meters : https://github.com/wargreen/osc_ardour_ctl
