### ISSUE TITLE
[Feature] prise en compte des modifications de texte sans validation

### ISSUE THREAD

**Issue by Ezrabox** [jean-emmanuel/open-stage-control#652]
Hello, 
Cela concerne les paramètres des widget, et plus particulièrement les champs textuels :
Lorsque je fais des modifications, si j'oublie de taper sur "entrer" et que je clic directement sur le widget suivant, la modification n'est pas prise en compte. 
Cette validation supplémentaire me semble superflue et fait perdre pas mal de temps lorsque l'on apporte des grosses modifications à une session. 
Il me semble que lorsque l'on quitte un champs d'édition cela devrait valoir pour validation

**Comment by jean-emmanuel** [comment]
C'est corrigé pour la prochaine version !

**Comment by Ezrabox** [comment]
Waw! Merci :)
