### ISSUE TITLE
[Bug] Image value ignored

### ISSUE THREAD

**Issue by moncopainal1** [jean-emmanuel/open-stage-control#653]
OSC 1.3.0
linux ubuntu 18.04.5 LTS
Client type built-in and external chromium/chrome browse
can't use image, when i give file on image/value , nothing appends...
sorry for my english, i'm french (juste like you!)<!--

I will try update

Thanks for your amazing OSC, it work !
Al1

**Comment by moncopainal1** [comment]
I just tried to use OSC 1.4.1, and it's the same, perheaps something i don't understoud...

**Comment by jean-emmanuel** [comment]
Merci pour le rapport, c'est corrigé pour la prochaine version !

**Comment by moncopainal1** [comment]
je viens de vérifier, ça marche sur la 49.12 ...
merci pour la correction de la prochaine version, j'ai hâte ...
Al1

**Comment by jean-emmanuel** [comment]
Ça devrait être réglé dans la 1.5.0 (en cours d'envoi)

**Comment by moncopainal1** [comment]
Merci tout plein, ça marche au poil!
Al1
