### ISSUE TITLE
[Bug] version warning

### ISSUE THREAD

**Issue by nlebellier** [jean-emmanuel/open-stage-control#654]
Bonjour Jean-Emmanuel,

Juste pour signaler que osc nous indique qu'une nouvelle version existe alors qu'elle est antérieure à la nouvelle. 1.5.

![image](https://user-images.githubusercontent.com/4880966/95014091-d40b8680-0644-11eb-8665-674b7c936cb2.png)

Voilà peanuts je suppose !

**Comment by jean-emmanuel** [comment]
Salut, c'est normal car la 1.5.0 n'est pas sortie et ne compte donc pas dans le calcul.

**Comment by nlebellier** [comment]
ok tout roule alors désolé du dérangement.
