### ISSUE TITLE
[Bug] multixy ephemeral mode : points label stay visible

### ISSUE THREAD

**Issue by matcham** [jean-emmanuel/open-stage-control#655]
OpenStageControl 1.5.1

when multixy ephemeral mode is true : points label stay visible when touch is released.

well, it could be an interesting feature (showing where a point has been released...), but looks more like a bug actually :-)

![image](https://user-images.githubusercontent.com/122241/95680922-3e8c6b80-0bdd-11eb-99e1-7ca10785d21b.png)

**Comment by jean-emmanuel** [comment]
Hehe, actually I was aware of this but unsure whether I should leave it or not. It seems I got the answer now :)

**Comment by matcham** [comment]
Look like a bug but could be a feature :-)
Not sure you should remove it...
Could be an option for the ephemeral mode ?
False / true / keep_id (or ?..)

**Comment by jean-emmanuel** [comment]
Hmm, I'm going with the most simple solution for now (hide label), we'll see if the "feature" gets missed ;)

**Comment by jean-emmanuel** [comment]
Ready for 1.5.2
