### ISSUE TITLE
[Bug] Fullscreen not working on iPadOS in Chrome, large X button in Safari fullscreen

### ISSUE THREAD

**Issue by lhalman** [jean-emmanuel/open-stage-control#656]
- Open Stage Control version 1.5.1
- MacOS Catalina 10.15.7 (19H2)
- O-S-C options (not sure what to put here)
- iPad 13.4.1 (17E262)
- iPad Chrome app version 81.0.4044.124 and iPad Safari app
- Session file: [20.10.10 OSC test.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/5368993/20.10.10.OSC.test.json.txt)
- No custom module
- Server logs: I don't know how to get this / show what's relevant beyond a bunch of MIDI CC info
- Client logs: Don't know how to grab these from iPad (this issue is not presenting itself in PC-based Chrome browser)

![IMG_15187045BD41-1](https://user-images.githubusercontent.com/46271586/95815941-b8eae780-0cd2-11eb-889a-40b3e1538b3c.jpeg)
![RPReplay-Final1602563566](https://user-images.githubusercontent.com/46271586/95816630-69a5b680-0cd4-11eb-9b14-ec5c49e3070c.gif)

Any help would be lovely for the following issues:
1. Fullscreen in Chrome on iPad OS does not work! This is only on the iPad, not on my desktop computer
2. Fullscreen in Safari on iPad OS has HUGE escape 'X' button — any way to eliminate?

Thanks!

**Comment by jean-emmanuel** [comment]
Fullscreen is still not properly supported on iOS (that's an apple issue). A popup is supposed to appear when you click on "fullscreen" with the following message: «You must add this page to your home screen to launch it in fullscreen », I'll check why it doesn't.

> Fullscreen in Safari on iPad OS has HUGE escape 'X' button — any way to eliminate?

Not that I know of...

**Comment by lhalman** [comment]
Thanks @jean-emmanuel , you're the best. How disappointing! 

But if I'm understanding right, I would need to add the server as my homescreen to make it work in fullscreen?

**Comment by jean-emmanuel** [comment]
Yep :)

**Comment by jean-emmanuel** [comment]
The aforementioned help message should be back in 1.5.2 (to be released).
