### ISSUE TITLE
Feature request: Hide labels

### ISSUE THREAD

**Issue by riban-bw** [jean-emmanuel/open-stage-control#66]
It would be advantageous to be able to hide labels of controls. An example is adding content to a "Strip" container which stacks all content as a single vertical or horizontal set of controls. If one wants to add a horizontal row of buttons within a vertical strip, e.g. adding "Mute" and "Solo" buttons next to each other, one could add a horizontal container to the strip but there is an undesirable label on the left occupying screen space.
Having an option to hide the label would allow more flexible use of controls within containers.

**Comment by riban-bw** [comment]
Just found this can be done by adding css: .label { display:none; } to the container / control.

**Comment by jean-emmanuel** [comment]
Setting [`label`](http://osc.ammd.net/user-guide/widgets-generics/#label) to `false` also works ;)

**Comment by riban-bw** [comment]
CSS doesn't work because it acts on all children. Setting label to false works. I didn't find this in the documentation which could be improved.

**Comment by jean-emmanuel** [comment]
> CSS doesn't work because it acts on all children

`>  .label { display:none; }` would work better in this case (see the [doc's examples](http://osc.ammd.net/user-guide/widgets-generics/#css))

> I didn't find this in the documentation which could be improved.

The link above point to the very place in the docs where this is explained.

**Comment by riban-bw** [comment]
My bad! Found it in docs - thanks. I didn't notice that "label" was a link in previous post and didn't notice in docs when I first read them. There is something about docs navigation that I struggle with but I will try to identify and report in separate report. Thanks for solution to this issue.

**Comment by jean-emmanuel** [comment]
You're welcome ! Don't hesitate to send suggestions and pull requests !
