### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by CtrlZ-Music** [jean-emmanuel/open-stage-control#661]
I'm trying to set the max of midi range[](url)
[127.0.0.1-1604359823463.log](https://github.com/jean-emmanuel/open-stage-control/files/5478601/127.0.0.1-1604359823463.log)

**Comment by jean-emmanuel** [comment]
Not a bug, but an error in your code, that #{} block returns `null`, probably because you're dividing 127 by 0, you could add a fallback value to avoid that (`#{whatever || 127}` would fallback to 127 if `whatever` is null or zero).

**Comment by CtrlZ-Music** [comment]
I found my solution with It was a bit tricky because one fader as to set the max of an other with mixed with midi problems ... what a mess. 

```
{
  "min": 0,
  "max": #{Math.min(127, @{text_stepsvalue_@{parent.variables.ID}}*2)|| 127}
}
```
