### ISSUE TITLE
[Bug] slow fader when controlling "on" parameter of keyboard

### ISSUE THREAD

**Issue by danpal96** [jean-emmanuel/open-stage-control#662]
- Open Stage Control version (or commit if built from sources)
1.6.0
- Operating system
Manjaro Linux x86_64
- Client type (built-in or external chromium/chrome browser) and version
built-in
- Session file (can be uploaded after adding the .txt extension)
[test.txt](https://github.com/jean-emmanuel/open-stage-control/files/5478774/test.txt)

When using a fader or (knob) to control the "on" parameter of a keyboard, the animation gets very slow after using it a few times, and one of my cores goes to 100%.
Regards,
Daniel Palma Igor

**Comment by jean-emmanuel** [comment]
The keyboards `on`/`off` properties are not dynamic (see [docs](https://openstagecontrol.ammd.net/docs/widgets/advanced-syntaxes/#dynamic-properties)), updating them at high rate is expected to slow. I'll try to change that in the future.

**Comment by jean-emmanuel** [comment]
fixed in sources, will be included in next release
