### ISSUE TITLE
[Bug] input field displays "null" for empty strings

### ISSUE THREAD

**Issue by git-moss** [jean-emmanuel/open-stage-control#663]
- Open Stage Control version (or commit if built from sources): 1.6.1
- Operating system: Windows 10 - 2004
- Client type (built-in or external chromium/chrome browser) and version: built-in

I switched some elements from text display to an input field and noticed that received empty strings are displayed as "null".

**Comment by git-moss** [comment]
![grafik](https://user-images.githubusercontent.com/3090132/98437031-88367c00-20df-11eb-957f-f2e44457e710.png)

**Comment by jean-emmanuel** [comment]
Thanks for the report !

**Comment by jean-emmanuel** [comment]
Fixed in v1.6.2 (uploading atm)

**Comment by git-moss** [comment]
Wow, that was fast! Thanks :-)
