### ISSUE TITLE
[Bug] osc_listener *sometimes* doesn't work if osc prop = auto

### ISSUE THREAD

**Issue by matcham** [jean-emmanuel/open-stage-control#665]
If a widget's osc prop = auto, some osc_listener won't work : 
for example, `colorWidget = OSC{color, red}`
will work as expected, but
(geometry) `left = OSC{left, 30}`
won't.

unless osc prop is set manually (or to` /@{this.id}` )

![image](https://user-images.githubusercontent.com/122241/98547164-0ccbfa80-2298-11eb-93c0-e8825009d548.png)

**Comment by jean-emmanuel** [comment]
Thanks, fixed in sources.
