### ISSUE TITLE
[Bug] Dropdown in clone

### ISSUE THREAD

**Issue by CtrlZ-Music** [jean-emmanuel/open-stage-control#668]
Hello, 

les dropdown menu d'un container ne s'ouvre plus dans les clones.

[dropdown_clone.json.zip](https://github.com/jean-emmanuel/open-stage-control/files/5593371/dropdown_clone.json.zip)

**Comment by jean-emmanuel** [comment]
Corrigé dans les sources pour la 1.7.4. (en attendant, ils s'ouvrent tout de même quand l’éditeur est désactivé)
