### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by KennyG5000** [jean-emmanuel/open-stage-control#669]
Hope you can help! I have a clone widget of a circular menu working fine on the server side on the Windows machine (as in it pops up and you can make your selection). However, when I try the same circular clone menu on either Full Screen Browser, Safari or Firedox on my ipad (IOS 14.2, 7th Gen) I cannot open the menu (I mean it pops up but is just a corner of the circle, the rest is not displayed). I have just opened it on my Android phone in Chrome and that works as expected, so it seems to be an issue only on my Ipad! 

I will attach my session file (it is happening on the Sequencer Tab, 'trigger select' and 'stages' circular menus (only on the clone, the original menus work fine!). 

[EaselTemplate2.zip](https://github.com/jean-emmanuel/open-stage-control/files/5607761/EaselTemplate2.zip)

All the best,

Oli (KennyG5000)

**Comment by jean-emmanuel** [comment]
It's fixed in sources (for v1.7.5); there are still some edge cases where iOS fails to render things properly though ;)
