### ISSUE TITLE
Feature request: Ability to inherit a parameter from parent and use in OSC address

### ISSUE THREAD

**Issue by riban-bw** [jean-emmanuel/open-stage-control#67]
It would be advantageous to be able to create a single channel strip then clone it, setting the channel ID once for each strip and for the child widgets to each inherit the strip ID, e.g.

Strip 1 has stripID = 1.
Strip 2 has stripID = 2.

Each strip has fader widget with OSC address = /strip/fader/{stripID}

**Comment by wargreen** [comment]
Same #43 
And agree !

**Comment by jean-emmanuel** [comment]
I did some experimentations, and I think it might be actually doable; I'll keep you guys up to date, I don't wanna rush this one as it could bring lots of bad side effects.

**Comment by cyberic99** [comment]
I think there are other use cases beside the stripID, that could be useful too.
For instance, knobs could have an OSC address of this form: /knobs/{id} with id being the ID of each knob.
For the strip ID, instead of inheriting, I think the children could have access to their parent's properties:
/strip/fader/{parent.stripID}
this would enable to get properties from widgets that are several levels ' above' .

**Comment by jean-emmanuel** [comment]
The implementation I'm working on will probably look like this: 

- `@{widgetID.propertyName}` where `widgetID` can be any widget's `id` and `propertyName` is the widget's property to retreive
- `@{parent.propertyName}` same as above but for targeting the parent widget (thus allowing retreiving its `id`)

**Comment by jean-emmanuel** [comment]
It's becoming pretty functional for string properties, you can build the latest sources to check it out. `@{parent.propertyName}` works fine, `@{widgetID.propertyName}` is limited (widgets can't retreive props from widgets created before them.)

**Comment by riban-bw** [comment]
I couldn't find any instructions on github on how to build the source.

**Comment by jean-emmanuel** [comment]
See http://osc.ammd.net/getting-started/, but you can also try the online demo, it's built from master.

**Comment by jean-emmanuel** [comment]
- [x] `@{parent.propName}` // ok
- [x] `@{this.propName}`  // ok
- [ ] `@{widgetID.propName}` // Almost there, still some troubles preventing the app to choke on circular references

**Comment by jean-emmanuel** [comment]
Ok, will ship in next release.

**Comment by jean-emmanuel** [comment]
Included in v0.18.0

**Comment by jean-emmanuel** [comment]
FYI, `@{widgetId._value}` is in git, it makes possible to use a widget's value to define another widget's property (the underscore is meant to differentiate from the `value` property that is used to define a widget's initial value).

https://github.com/jean-emmanuel/open-stage-control/issues/122
