### ISSUE TITLE
Unable for use with GrandMA3

### ISSUE THREAD

**Issue by sstaub** [jean-emmanuel/open-stage-control#675]
macOS 10.15.7
version 1.7.5
There is an installation of GrandMA3 onPC (v1.3.1) for Mac on my macBookPro.
When I start the server the Open-Stage-Control opens the MA Webbrowser instead of a new app window.

**Comment by jean-emmanuel** [comment]
It looks like this software uses the same port as open stage control (you should see an error message about that in o-s-c's console), simply set the server's `port` to something other than 8080 .

**Comment by sstaub** [comment]
Thank you for the fast response, changing the port made it.
