### ISSUE TITLE
[Bug] Problem with control on iOS 10.3.4 with OSC v1.7.8

### ISSUE THREAD

**Issue by Hipox** [jean-emmanuel/open-stage-control#676]
Hello!

The problem is I can not control OpenStageControl through my iPad.
As captured on the screenshot I get the main window open in a browser but there is no OSC version in the header written and the header itself (I mean three dots that should open a menu) is not clicable and I can not interact with it.

I tested the  same setup on iOS 12.5 on iPad Air (version 1) and I it's working properly.

Also, I tried to run the terminal from a Command Promp on my PC, but nothing has changed.

Thank you for help!

- Open Stage Control version (or commit if built from sources): v1.7.8
- Operating system: Desktop PC - Windows 10.0.19042 | iPad 4 - latest iOS 10.3.4
- Open Stage Control options: send 127.0.0.1:8080 | midi OSC:3,5 | osc-port 8000 | fullscreen TRUE | force-gpu TRUE 
- Client type (built-in or external chromium/chrome browser) and version:  iOS App Google Chrome version 71.0.3578.89
- Session file (can be uploaded after adding the .txt extension): not really important in this case
- Custom module: none
- Server logs (from the terminal or the launcher's console): none
- Screenshot: ![IMG_5917](https://user-images.githubusercontent.com/42555375/102238505-1f200080-3ef6-11eb-8bcc-758fe10d2557.PNG)

**Comment by jean-emmanuel** [comment]
Thanks for the detailed report I'll get back to you soon.

**Comment by jean-emmanuel** [comment]
It should be fixed in v1.8.0 (currently deploying).

**Comment by Hipox** [comment]
Wow, that was so fast!
Works flawlessly now :) thank you very much.

Have a wonderful day!

st 16. 12. 2020 v 11:37 odesílatel jean-emmanuel <notifications@github.com>
napsal:

**Comment by jean-emmanuel** [comment]
great, you too!
