### ISSUE TITLE
[Bug] Impossible to reach the "Save" or "Save as" in the editor Session dropdown menu

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#679]
Hello,

This happens in O-S-C 1.7.5 under Windows64. As I go over "Récemment ouvert(s)", the list of recently opened files is displayed over the bottom of the menu, hiding the controls down ("Enregistrer", "Enregistrer sous...", "Importer", "Exporter") and it's impossible to go over it (have a look at the video). Of course I can use shortcuts for Save and Save as but then what's the menu for???

Best regards.

https://user-images.githubusercontent.com/6513218/103406363-bf169480-4b5a-11eb-9218-4517cad65f03.mp4

**Comment by jean-emmanuel** [comment]
You need to make the window bigger to avoid that. It's also possible to "avoid" the dropdown:
![Peek 31-12-2020 11-35](https://user-images.githubusercontent.com/5261671/103406836-61834780-4b5c-11eb-9897-de5aecae6e2f.gif)

**Comment by nesdnuma** [comment]
Ah, yes the North-East passage! Thank you!
