### ISSUE TITLE
Question : Add widget via custom module ?

### ISSUE THREAD

**Issue by wargreen** [jean-emmanuel/open-stage-control#68]
Hi !
I think to how build a "generic" auto-filled session for ardour.
Is it possible to add new widgets from a custom module ?

Thanks !

**Comment by jean-emmanuel** [comment]
Yes it is, by sending [`/EDIT`](http://osc.ammd.net/user-guide/remote-control/) messages to the app, one can edit a panels children list.

```
// from the custom module oscInFilter method 
receiveOsc({
  address:'/EDIT'
  args: [
    {type:'s', value:'panel_ID'},
    {type:'s', value: JSON.stringify( {widgets: [ WIDGET_OBJECTS ] } )
  ]
})
```

**Comment by wargreen** [comment]
Thanks a lot for your reponse !
