### ISSUE TITLE
[Feature] Reduce lost space in knob widget when Pips activated

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#680]
Whenever with a know the pips option is activated, there is much space left between the widget's name and the knob itself :

![current_OSC](https://user-images.githubusercontent.com/6513218/103410266-e5dcc700-4b6a-11eb-9d05-03fb162f97c5.JPG)

It spoils a lot of space on the screen. It could be changed like this :

![possible_OSC](https://user-images.githubusercontent.com/6513218/103410299-086ee000-4b6b-11eb-8f55-26f0f1898b32.JPG)

Another option would be an option not to display the widget's name at all and put a text widget on top instead.

**Comment by jean-emmanuel** [comment]
Styling the extra html is up to you, you can use `.html {position: absolute;}` to avoid the label from taking any space.

**Comment by nesdnuma** [comment]
Good to know. Thank you!
