### ISSUE TITLE
[Bug] Dropdown's "align" property not respected when menu is open

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#681]
Despite the align property set to "center", the items are aligned to the default position (left) when the menu is open.

![image](https://user-images.githubusercontent.com/6513218/103415999-dff3df80-4b84-11eb-9bef-c9daa0b17536.png)

(O-S-C 1.7.5/Windows 64)

**Comment by jean-emmanuel** [comment]
This can't be fixed as the native dropdown element (provided by the browser/system) does not support text alignment. The only thing that seem to work is playing with css `padding-left` on the `select` element.

**Comment by nesdnuma** [comment]
OK
