### ISSUE TITLE
[Feature] session fragment import / export

### ISSUE THREAD

**Issue by jean-emmanuel** [jean-emmanuel/open-stage-control#682]
https://openstagecontrol.discourse.group/t/feature-request-export-import/1032

**Comment by matcham** [comment]
I was about to write a FR about that when I found this ticket :-)
so +1 👍 
(actually I can't see the difference between session open / save and import / export...
I would love to be able to export the selected widgets into a file, and import a file into the current session.

This would allow to build a kind of "user lib" :-)

another FR : drag'n'drop a .json file into a session editor would import the file into the current project.
That would let you compose a new session very easily, in a modular way...

**Comment by jean-emmanuel** [comment]
> actually I can't see the difference between session open / save and import / export...

Import / export allows loading/saving a session from/to the client filesystem, it's what saving/loading looked like before the remote file browser was added.
