### ISSUE TITLE
Error in clone variables 

### ISSUE THREAD

**Issue by CtrlZ-Music** [jean-emmanuel/open-stage-control#683]
Not so much time just shared this capture
Strange because when I re write my value it's ok ...

![Capture d’écran 2021-02-01 à 15 55 12](https://user-images.githubusercontent.com/35999472/106475366-2602d280-64a6-11eb-9daf-fa0ac58ce652.png)

**Comment by CtrlZ-Music** [comment]
c'est idiot je pourrai l'écrire en français ...

**Comment by jean-emmanuel** [comment]
J'ai vois comment régler le problème mais j'aurais besoin d'un peu plus de précision sur le contexte de l'erreur, au moins un fichier de session et un protocole pour reproduire l'erreur.

**Comment by CtrlZ-Music** [comment]
Hop 
Tab "Eucl Fx" le container bleu est le parent les autres les enfants.
La variables "ID" se trouve dans les enfants (logique en faite) 
Bizzarement je n'arrive plus a reproduire l'erreur 

[HTD_MC01.json.zip](https://github.com/jean-emmanuel/open-stage-control/files/5906060/HTD_MC01.json.zip)

**Comment by jean-emmanuel** [comment]
Ok, je préfère ne rien changer pour l'instant pour éviter les effets de bords, si le problème se reproduit et qu'on arrive à avoir un protocole pour le répéter et le comprendre n'hésite pas à rouvrir le ticket.
