### ISSUE TITLE
[Bug] Cannot load project containing multiplexy with dynamic number of points

### ISSUE THREAD

**Issue by jln-** [jean-emmanuel/open-stage-control#685]
I created a project containing a multiplexy widget whose number of points is defined dynamically, based on two other widgets (basically a widget defining a number of audio sources, a widget defining whether sources are mono or stereo. I then want to control each channel with a point on the multiplexy widget).

To do so, I added a JS script for the 'points' property of multiplexy : `"JS{{var points = @{bfg/sources.value} * (@{bfg/mode.value} + 1);return points;}}"`

It works fine as long as Open Stage Control is running.

When I quit, launch again Open Stage Control then load the session, I get the following error message:

`
(ERROR, CLIENT) Uncaught TypeError: Cannot read property 'length' of null
    at constructor (src/client/widgets/pads/multixy.js:52:90)
`

and project cannot be opened.

**Comment by jln-** [comment]
I actually solved my problem by setting a default value to my widgets used to define the number (sorry for noise, I am still learning my way)

Actual bug here though, may be that the project cannot be load at all. When there is such a problem, it could be nice if one could still load the project and have the error message.

(I'm leaving the bug report as is for further reference, but feel free to delete or rename as wanted)

**Comment by jean-emmanuel** [comment]
This specific error is now fixed. Loading sessions that produce errors is something I'd like to implement at some point but it requires some changes I haven't quite figured out yet.

**Comment by jln-** [comment]
Great ! Thanks for the good work.
