### ISSUE TITLE
[Bug] /TABS not working anymore

### ISSUE THREAD

**Issue by knobtwister420** [jean-emmanuel/open-stage-control#686]
I used to be able to send "/TABS" to Open Stage Control and it would switch between tabs for me, but the commands I used to use no longer work with the newest version

It DOES however work with version 0.41.5

I managed to find something about /TABS in the open-stage-control-client.js in 0.41.5 but not in the newest version

**Comment by jean-emmanuel** [comment]
It's been removed in v1.0.0 (tabs can still be controlled per container by sending the desired tab index to a container).

**Comment by knobtwister420** [comment]
Thank you for your prompt reply! Would you please elaborate more on controlling tabs via a container or point me in the right direction so I learn how to do that?

My friends and I have been using the "/TABS" function extensively in our workflows and we'd love to be able to upgrade to the newest version of Open Stage Control! Would it be possible to add it in to the newest version?

Thanks again! Best Wishes, -Zack

**Comment by jean-emmanuel** [comment]
I restored that piece of code from v0, it will be back in next release.

> Would you please elaborate more on controlling tabs via a container or point me in the right direction so I learn how to do that?

A container that contain tabs can be controlled via osc messages: `/container_address index` will set which tab (among its direct children) should be active (where `index` is an integer, starting with 0).

**Comment by knobtwister420** [comment]
Ayyy!!!! Thank you so much!! We're all looking forward to it!! And ahh gotcha!!

Best Wishes, -Zack
