### ISSUE TITLE
[Bug] multixy : decimals has no effect

### ISSUE THREAD

**Issue by matcham** [jean-emmanuel/open-stage-control#688]
setting decimals prop to 0 (or any other value) has no effect, multixy always sends float : 
(DEBUG, OSC) Out:  {
  address: '/multixy_1',
  args: [
    { type: 'f', value: 3.4468085106382955 },
    { type: 'f', value: 5.916666666666669 },
    { type: 'f', value: 6.297872340425535 },
    { type: 'f', value: 4.666666666666661 }
  ]
} To: 127.0.0.1:8000

Open Stage Control 1.8.8 Windows

**Comment by jean-emmanuel** [comment]
Thanks for reporting, I'll fix it soon. Note that setting decimals to doesn't make the widget send integers, you have to use the typeTags property to do that.

**Comment by matcham** [comment]
Thanks for the tip ; never used typeTags before, good opportunity to change my habits :-)

**Comment by jean-emmanuel** [comment]
fixed in sources
