### ISSUE TITLE
[Feature] IRC Freenode Channel

### ISSUE THREAD

**Issue by freddieventura** [jean-emmanuel/open-stage-control#691]
Hi there guys,

First of all many thanks for this resource which I see it will become a huge advantage in Audio and Video Industries.
I have some doubts I will be resolving myself but I've seen you don't have a freenode IRC channel yet?

IRC Freenode is such a nice place to solve some troubleshooting questions and make a community, I will encourage you to open a Channel on there and redirect people to it so we can help with each other's expertise.

Also you could potentially make a bot to link IRC with discord and span even more people.

Best Regardos!!

**Comment by jean-emmanuel** [comment]
Hi ! As much as I like IRC I won't be able to hang out there much, the discourse forum is already quite time consuming but lets me get back to unanswered questions when I can. That being said, I don't see any problem with adding a link to 
freenode#openstagecontrol
