### ISSUE TITLE
[Bug] Not able to load a Session from the Command Line, Windows10 Powershell x64

### ISSUE THREAD

**Issue by freddieventura** [jean-emmanuel/open-stage-control#693]
Hi,

I have used open stage control on linux and everything is great, I can 
```
open-stage-control --load fakeBCRXL-MIDI02.json
```
But on Windows10 seems that adding --load an a parameter to it doesn't trigger Open Stage Control
```
.\open-stage-control.exe --midi fakesynth:14,14 --load ./fakesynth.json
```
The .json is located in the same path of the executable, and my prompt is on that path
Proof is that if I do 
```
\open-stage-control.exe --midi fakesynth:14,14
```
It works
I have tried different ways of inputing the path such as
```
.\open-stage-control.exe --midi fakesynth:14,14 --load "./fakesynth.json"
.\open-stage-control.exe --midi fakesynth:14,14 --load fakesynth.json
.\open-stage-control.exe --midi fakesynth:14,14 --load ".\fakesynth.json"
.\open-stage-control.exe --midi fakesynth:14,14 --load "c:\full\path\to\file\fakesynth.json"
```
None of them work

Thanks

**Comment by jean-emmanuel** [comment]
https://openstagecontrol.ammd.net/docs/getting-started/server-configuration/#running-in-a-terminal-on-windows

**Comment by freddieventura** [comment]
Thank you!
