### ISSUE TITLE
[Feature] When in the GUI on project tree , be able to select a range of widgets by Ctrl + Shift

### ISSUE THREAD

**Issue by freddieventura** [jean-emmanuel/open-stage-control#694]
Hi there,

I just find myself sometimes wanting to change properties for a bunch of widgets at the same time, so I go to the project tree and I make a selection of the widgets I want by leftclicking + Ctrl , but in some programs if items are contiguous you can do a Ctrl + Shift + Click on the last contiguous item and will select all of them instead of having to be clicking each of them.

I don't know if it is a technological complication but It would be a nice feature to have

Thanks

**Comment by jean-emmanuel** [comment]
Currently you can shift + drag to select contiguous items. I'm experimenting the shift + click implementation, it seems doable

**Comment by jean-emmanuel** [comment]
included in upcoming v1.8.12
