### ISSUE TITLE
[Feature]  Alt + Left Click  Drag and Drop a Widget = Duplicate the selected Widget 

### ISSUE THREAD

**Issue by freddieventura** [jean-emmanuel/open-stage-control#695]
Hi,

I think in order to improve the interoperability with the Editor GUI, the model to follow "in my opinion" is `Adobe Illustrator` , is quite simple to manage different Objects on there.
Without me been an expert of Illustrator, I kind of miss that: 
 - Alt + Left Click  Drag and Drop a Widget = Duplicate the selected Widget 
 - Alt + (Mousewheel + or - ) = Increase decrease Zoom in the selected area (I know thisone may not work as there may not be zoom possible because it gets rendered according to the view port).
 
 These are just ideas

**Comment by jean-emmanuel** [comment]
Done in v1.8.13 

> Alt + Left Click Drag and Drop a Widget = Duplicate the selected Widget

I went for alt+c and alt+shift+c (paste n+1)

> Alt + (Mousewheel + or - ) = Increase decrease Zoom

It will need some polishing but it's here
