### ISSUE TITLE
[Feature] drag & drop .json files 

### ISSUE THREAD

**Issue by matcham** [jean-emmanuel/open-stage-control#696]
The file browser susks !
But I guess you have good reasons for not using os native file browser...

adding json drag & drop support would help a lot :-)

droping a json file into the window would load the session file.

droping a json file when the session is in "edit" mode would import the file into the current session.
That would let you compose a new session very easily, in a modular way...

**Comment by jean-emmanuel** [comment]
> The file browser susks !

Nice and constructive. I do have good reasons, the native file browser can't be used due to the web browsers limitations / security policy.

> droping a json file into the window would load the session file.

This should be possible

**Comment by jean-emmanuel** [comment]
Dropping a file in the browser won't let the app know its location on the drive, thus making the feature pretty much useless.
