### ISSUE TITLE
[Feature] silder/xy/multixy... : changing spring prop --> update value

### ISSUE THREAD

**Issue by matcham** [jean-emmanuel/open-stage-control#697]
I think that changing dynamically the spring prop of a slider / xy / multixy ... should update the slider/point value.
when enabling spring : the value should go immediately to it's default value if the slider/point is not being controlled by a touch.

it would be coherent with the way ephemeral mode of xy / multixy widgets actually work : if you change the ephemeral mode : the point is updated.

**Comment by jean-emmanuel** [comment]
fixed in 1.8.13
