### ISSUE TITLE
Feature request: always on top container

### ISSUE THREAD

**Issue by cyberic99** [jean-emmanuel/open-stage-control#70]
Hi

It would be very useful if we could have some containers or tabs displayed above the others.
For instance on ardour.js, all the transport bar is duplicated for tab1 and tab2.
If we had a 'always on top'  property, the same transport bar would be displayed above the others.

I tried to simulate this using modals and adjusting popupHeight, but unfortunately when the modal is opened, I can only click inside the modal, and not on any widget below.

Thank you for the work you put in this project, Jean-Emmanuel!
Accessing the parent' s property seems really useful already!

**Comment by jean-emmanuel** [comment]
Yo!

The only way to achieve something like this is to put your tabs in a panel, this might change when/if I rewrite the tabs system, but currently widgets are strictly tied to their parent tabs

Thanks for the feedback :)

**Comment by cyberic99** [comment]
Oh, so you CAN have 'always on top' widgets already!
I didn't realise you could add tabs to containers.
I assumed I could only add tabs to the root window.
Thanks!

Now another question: is it possible to switch to a tab via OSC messages?

**Comment by ovenwerks** [comment]
I do not know if this is possible in your situation, But it should be possible to run another instance of open stage control that just has transport controls. Depending on your desktop environment it may be possible to set it always on top. I have also used two instances of O-S-C to extend the surface by taking something like ardour.js and setting it to see only buses, and then a second simple surface that sees only tracks. There are many possibilities.

**Comment by jean-emmanuel** [comment]
> Now another question: is it possible to switch to a tab via OSC messages?

yep: http://osc.ammd.net/user-guide/remote-control/#tabs-id-id-etc

**Comment by cyberic99** [comment]
Sorry I missed the info in the documentation again...
Thanks

@ovenwerks Yes you're right it could use my desktop window manager directly.
Tabs inside a panel seem to be a cleaner solution

**Comment by jean-emmanuel** [comment]
FYI, panel can now switch their active tab through osc (value = tab index).
