### ISSUE TITLE
[Feature] Separate scrolling in edit mode from scrolling in use mode

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#700]
Hello,

I use a fullscreen setup and I need the position of the widgets to be set very precisely. To gain space I disable the scrolling.

However I need to scroll across the screen while editing because things are hidden by the various tabs (Inspecteur, Arborescence, etc). So I re-enable the scrolling to access the widgets.

The problem is I have to scroll again to the right position after editing before disabling the scrolling and saving if I want to see everything whenever going back in use mode.

So it would be nice to have access to scrolling in edit mode without impacting on the position of display in use mode.

Thank you in advance.

**Comment by jean-emmanuel** [comment]
Setting the root's width and height properties should address your issue.

**Comment by nesdnuma** [comment]
It made the trick. Thanks a lot!
