### ISSUE TITLE
[Feature] Button "Bang" fonction

### ISSUE THREAD

**Issue by Ezrabox** [jean-emmanuel/open-stage-control#702]
Hello, in button fonctions (toggle, push, tap) it should be great to have fourth fonction who should be "Bang" or "Gate" one. 
This one should send a "1" and imediatly a "0" not at realease like push and different than tap, who do not send any "0"
Thanks :)

**Comment by jean-emmanuel** [comment]
It doesn't seem like a usual button behavior, but you if you need to do that you can simply use the "tap" mode and send the second message using the script property:
```
send('/address', 0)
```

**Comment by Ezrabox** [comment]
Merci :) au top!

Le mer. 7 avr. 2021 à 18:16, jean-emmanuel ***@***.***> a
écrit :
