### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by sargaroth** [jean-emmanuel/open-stage-control#703]
Whenever I open the editor, all my input widgets' padding is increased. This happens as I open the editor, not as I close it.

EDIT: Occurs when I open the F12 console as well. Can't replicate in a new session though.

- Open Stage Control version 1.8.15
- Windows 10 1909 x64
- Open Stage Control options (fullscreen. Force GPU doesn't affect issue
- Client type: built-in.
[X32v4 - Copy.txt](https://github.com/jean-emmanuel/open-stage-control/files/6273785/X32v4.-.Copy.txt)
[receive data from x32 - Copy.js.txt](https://github.com/jean-emmanuel/open-stage-control/files/6273789/receive.data.from.x32.-.Copy.js.txt)
 
![bild](https://user-images.githubusercontent.com/45758116/113917000-f3948f00-97e0-11eb-8e5c-d95f9ef8b3cb.png)
![bild](https://user-images.githubusercontent.com/45758116/113917027-fc856080-97e0-11eb-821f-e43c698e193f.png)
![bild](https://user-images.githubusercontent.com/45758116/113916942-dfe92880-97e0-11eb-9ffc-34f3b9abe38d.png)

**Comment by jean-emmanuel** [comment]
Thanks for the report, I'll fix it in v1.9.0

**Comment by jean-emmanuel** [comment]
v1.9.0 is available now
