### ISSUE TITLE
Toggle Auto send state when recieve

### ISSUE THREAD

**Issue by Ezrabox** [jean-emmanuel/open-stage-control#704]
hello, with toggle buttons i need than it automaticaly send is state when it recieve a change from an other soft, i know than it's not a normal case but i would like to know if it can be an option? 
Thanks
Ezra

**Comment by jean-emmanuel** [comment]
Widgets don't reply to incoming messages and that's not something I'm willing to change, however this can be handled by writing a [custom module](https://openstagecontrol.ammd.net/docs/custom-module/custom-module/). There is a an [example](https://openstagecontrol.ammd.net/docs/custom-module/examples/#reply) in the docs for this exact use case.

**Comment by Ezrabox** [comment]
Merci!

Le jeu. 8 avr. 2021 à 20:42, jean-emmanuel ***@***.***> a
écrit :
