### ISSUE TITLE
[Bug] One Push do not display external  osc info 

### ISSUE THREAD

**Issue by Ezrabox** [jean-emmanuel/open-stage-control#705]
Salut, après quelques heures à chercher la cause avec l'aide de Ben Kuper de Chataigne, nous ne trouvons pas la raison de ce bug, je m'en remet donc à toi. 
OSX 11.2.3

Le retour visuel du mute sélectionné dans l'image jointe ne répond pas à la commande osc : /looper/1/track/1/mute
Il devrait à l'aide du JS afficher un état selon in "int" envoyé par le logiciel commandé. 
Tous les autres mutes de ma session fonctionnent mais celui ci malgré les vérifications ne réagit pas. 
Si je change le nom du bouton ex :  /looper/1/track/1/test  et que je lui envois cette commande alors j'ai une réaction du picto mais pas de la couleur. Il recoit donc bien des infos mais ne réagit pas correctement. 
Ci-joint l'image et ma session

<img width="1288" alt="Capture d’écran 2021-04-15 à 14 41 06" src="https://user-images.githubusercontent.com/33526688/114870672-bf305c80-9df8-11eb-8606-2aca3fb496d5.png">

[LGML2071.json.zip](https://github.com/jean-emmanuel/open-stage-control/files/6317950/LGML2071.json.zip)

**Comment by jean-emmanuel** [comment]
Ici ça fonctionne: 
![Peek 15-04-2021 15-04](https://user-images.githubusercontent.com/5261671/114873854-04a25900-9dfc-11eb-9188-d9143fbd9228.gif)

**Comment by Ezrabox** [comment]
Effectivement lorsque j’envoie depuis la console chez moi ça marche aussi mais pas depuis une autre app, j'ai bien vérifié que l'adresse que j’envoie est la bonne en la recevant sur une 3eme app mais quand je m'adresse au serveur open stage control, rien....

**Comment by jean-emmanuel** [comment]
Tu utilises un custom module ?

Est-ce que tu peux activer le mode debug du serveur pour vérifier ce que OSC reçoit ?

**Comment by Ezrabox** [comment]
Aïe! effectivement je te prie de m'excuser c'est un vague test de custom module qui était resté pointé... Merci pour ta réactivité  et désolé pour ce faux bug...
