### ISSUE TITLE
[example]

### ISSUE THREAD

**Issue by CtrlZ-Music** [jean-emmanuel/open-stage-control#706]
Hey 

je peux proposer mon custom script pour Ableton 
[Remote_Script_CtrlZ.zip](https://github.com/jean-emmanuel/open-stage-control/files/6319636/Remote_Script_CtrlZ.zip)

**Comment by jean-emmanuel** [comment]
Tu peux le présenter dans la section du forum prévue pour cela : https://openstagecontrol.discourse.group/c/community/made-with-open-stage-control/9
