### ISSUE TITLE
Encoder does not respond to mouse wheel.

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#71]
both the slider and the pot respond to mouse wheel movement, but the encoder does not. I am using the encoder as a selector where the mouse wheel is easier to control.

**Comment by jean-emmanuel** [comment]
Each mousewheel increment should send the forward or backward message then, but what about the release ?

**Comment by ovenwerks** [comment]
On Tue, 6 Jun 2017, jean-emmanuel wrote:

> 
> Each mousewheel increment should send the forward or backward message then, but
> what about the release ?

I don't think in this case release is needed. Or it could be sent after 
each tick. A mouse wheel tick should not (in my opinion) be considered a 
touch.

The encoder in hardware is very versatile. It can be used in so many ways 
it is hard to describe what limits should be put on it.

--
Len Ovens
www.ovenwerks.net

**Comment by jean-emmanuel** [comment]
Ok, I tried something, tell me I it behaves as you'd expect it to.

**Comment by ovenwerks** [comment]
Perfect. It should be good, this is a cheap a mouse as I can imagine ($3 special) so if this works, I think anything should.

**Comment by jean-emmanuel** [comment]
Included in v0.18.0
