### ISSUE TITLE
[Bug] Run from sources fails on aarch64 ManjoroARM, Fix identified

### ISSUE THREAD

**Issue by Rippert** [jean-emmanuel/open-stage-control#711]
- Open Stage Control version  - 1.9.1
- Operating system  - ManjaroARM minimal with Xorg and LXDE installed
- Open Stage Control options -none
- Client type (built-in or external chromium/chrome browser) and version -N/A
- Session file (can be uploaded after adding the .txt extension) -N/A
- Custom module -N/A
- Server logs (from the terminal or the launcher's console) - N/A
- Client logs (hit F12 in chromium/chrome to open the console) - N/A
- Screenshot - N/A

 I successfully followed the Build from Sources guide on a Raspberry pi 3B+ running Raspberry Pi OS 10 (Buster) previously.

I tried to follow them for a Raspberry Pi 4B running ManjaroARM, substituting `npm install --arch=aarch64` for `npm install --arch=armv7l`. everything seemed to work until I tried to run with npm start, then I received this error:
```
$ npm start

> open-stage-control@1.9.1 start
> electron app/

sh: line 1: electron: command not found
```
Afterwards, I tried `npm install electron --save-dev` in the O-S-C directory. It proceeded normally, and I was able to start the full GUI of O-S-C using  `npm start` after that. It may be that using `--arch=arm64` in the initial instructions might work, but I did not try that yet.

**Comment by jean-emmanuel** [comment]
>  It may be that using --arch=arm64 in the initial instructions might work

Yes, most probably, I'm adding that to the docs.

**Comment by Rippert** [comment]
I will test it if you want me to. I assume just creating a new directory and starting the whole procedure from scratch will work? It take a while on my puny RPI!

**Comment by jean-emmanuel** [comment]
That'd be great

**Comment by Rippert** [comment]
OK, I'll get back to you tomorrow about it. Thanks again.

**Comment by Rippert** [comment]
It did work with `--arch=arm64 `.

**Comment by jean-emmanuel** [comment]
Thank you for testing!

**Comment by Rippert** [comment]
You're welcome. Thank you for all your work on O-S-C.
