### ISSUE TITLE
[Bug] Cannot build package on ARM

### ISSUE THREAD

**Issue by Rippert** [jean-emmanuel/open-stage-control#712]
- Open Stage Control version - 1.8.15 and 1.9.1
- Operating system Rapberry Pi OS 10 (buster) and Linux 5.10.25-3-MANJARO-ARM
- Open Stage Control options - N/A
- Client type (built-in or external chromium/chrome browser) and version -N/A
- Session file (can be uploaded after adding the .txt extension) - N/A
- Custom module - N/A
- Server logs (from the terminal or the launcher's console) - N/A
- Client logs (hit F12 in chromium/chrome to open the console) - N/A
- Screenshot - N/A

 I tried to build a package following instructions from Running from Sources, and received the following error: 
```
$npm run package

> open-stage-control@1.9.1 package
> node scripts/package.js

Packaging app for platform linux arm64 using electron v12.0.5
Downloading patent safe FFMPEG for platform linux arm64 using electron v12.0.5
Failed to load FFMPEG Error: spawn unzip ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn unzip',
  path: 'unzip',
  spawnargs: [
    '-o',
    '/tmp/tmp-safe-ffmpeg/ffmpeg-v12.0.5-linux-arm64.zip',
    '-d',
    '/tmp/electron-packager/linux-arm64-template'
  ]
}
/home/tedrippert/src/open-stage-control/node_modules/electron-packager-plugin-non-proprietary-codecs-ffmpeg/dist/index.js:33
    done(new Error(err));
         ^

Error: Error: spawn unzip ENOENT
    at /home/tedrippert/src/open-stage-control/node_modules/electron-packager-plugin-non-proprietary-codecs-ffmpeg/dist/index.js:33:10
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by jean-emmanuel** [comment]
The error shows that "unzip" is missing, you can install it with the distrib's package manager.

**Comment by Rippert** [comment]
You are correct! Thank You! 
Now if I want to install it on another Raspberry Pi, do I move the whole `open-stage-control-linux-arm64` directory to the new machine and set a symlink in the PATH?

**Comment by jean-emmanuel** [comment]
Yes (if they have the same cpu architecture). To enable midi support (if needed) on that machine you'll need to follow the instructions under "other systems" [here](https://openstagecontrol.ammd.net/docs/midi/midi-configuration/) on that system.

**Comment by Rippert** [comment]
Thank you. I already had to do the "other systems" thing for a previous install. I will try it tomorrow and close this issue if it works.

**Comment by Rippert** [comment]
I did test installing this on another Raspberry Pi from the package, and it worked. Thanks again.
