### ISSUE TITLE
osc-midi-windows.exe malicious since open-stage-control 1.9.0?

### ISSUE THREAD

**Issue by maddin152** [jean-emmanuel/open-stage-control#713]
Hi,

when I try to extract the downloaded file (open-stage-control-1.9.1-win32-x64.zip) my AV is alerting me.
It seems that a couple of AV vendors is tagging osc-midi-windows.exe as malicious.

Best,
Martin

**Comment by jean-emmanuel** [comment]
It's a false positive, as said [here](https://openstagecontrol.discourse.group/t/testing-needed-out-of-the-box-midi-support/808/29), there's nothing I can do.

**Comment by maddin152** [comment]
Hi there,

I submitted the file (from version 1.9.3) to Bitdefender for review. Bitdefender has whitelistet the file.

Best,
Martin

**Comment by jean-emmanuel** [comment]
Thank you !
