### ISSUE TITLE
grid template document spelling [Bug] 

### ISSUE THREAD

**Issue by GeneralMidi** [jean-emmanuel/open-stage-control#715]
Should this be "or" ??

You may have also meant valid instead of value? Not sure on that one. Cheers :)

![image](https://user-images.githubusercontent.com/47597511/116826310-ac0ce300-ab93-11eb-9eff-4c2464d6cae0.png)

**Comment by jean-emmanuel** [comment]
I meant "or" and  "valid" :), thanks, fixed to
> can be either a number of columns or a valid value for the css property "grid-template"
