### ISSUE TITLE
Editor Mode Not working on Firefox , with Linux amd64 [Bug] 

### ISSUE THREAD

**Issue by freddieventura** [jean-emmanuel/open-stage-control#716]
Just a quick feedback you may already know , I normally use Firefox in Linux , and noticed that the Editor mode is not working for this Version of the Browser (it does work though in Win10):
OS : Linux Debian  4.19.0-12-amd64
Firefox Version: firefox-esr/stable,now 78.10.0esr-1~deb10u1 amd64 

I have downloaded google-chrome and it works fine on there . Thanks

**Comment by jean-emmanuel** [comment]
Hi, could you be more specific on what doesn't work exactly ? I just tried with the exact same version and it seems to work.

**Comment by freddieventura** [comment]
In my case , by pressing Ctr + E , or Pressing the Three dots to access the Editor mode seems not be making any effect.

**Comment by jean-emmanuel** [comment]
Could you check the browser's console for error messages (f12) ? Can you be really more specific and describe what you do step by step ? Just in case, you can"t open the editor if no session is loaded first.

**Comment by freddieventura** [comment]
It is fine , my mistake , the instance of `open-stage-control` in Firefox doesn't come with the `project-tree` and `inspector` activated , so even when I enabled `editor` it didn't show up as that (in Chrome for some reason it does).
So it is working fine my bad. Thank you!

**Comment by jean-emmanuel** [comment]
Ok cool!
