### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by GeneralMidi** [jean-emmanuel/open-stage-control#717]
In 1.9.3 the panels aren't updating in the tree to visible once the visible property changes. 

I have this on the panels
#{@{button_30} == 1}

[notSHowingVisiblePanelsInTree.zip](https://github.com/jean-emmanuel/open-stage-control/files/6425558/notSHowingVisiblePanelsInTree.zip)

**Comment by jean-emmanuel** [comment]
Thanks, it's fixed, v1.9.4 is on its way

**Comment by jean-emmanuel** [comment]
Oh wait, you mean they keep appearing greyed out in the tree when you push the button ? The tree is not aware or this kind of update, I'll probably not fix that sorry.

**Comment by GeneralMidi** [comment]
Ah ok, yes that's what I meant. But no probs.

**Comment by jean-emmanuel** [comment]
Turns out it's possible actually :D, 1.9.4 is already deployed so this will be for next release !
