### ISSUE TITLE
[Bug] advanced syntax error

### ISSUE THREAD

**Issue by GeneralMidi** [jean-emmanuel/open-stage-control#718]
Sorry, me again. Hope I'm not being annoying. Let me know if I am. 

in 1.9.4 my 1.9.3 session had this in and it wouldn't open. Also pasting it into a button in 1.9.4 results in an error. Thought you'd like to know. 

```// this is wrong console.log(@{button_30) //wrong```

looks like it's missing the last } and has a parenthesis instead ```@{button_30)```

But wouldn't a comment in a script property render the whole line as a comment? Or do comments not work in scripts?

Oh, and I now know (finally) not to use @{} in scripts!!

**Comment by jean-emmanuel** [comment]
No problem, there really is a bug behind this which I'm fixing at the moment.
