### ISSUE TITLE
npm run build ends in a different directory than it starts

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#72]
from: http://osc.ammd.net/getting-started/

starts off in */open-stage-control/
$ npm run build
after this: */open-stage-control/dist/open-stage-control-linux-x64/
so
$ npm run deb64
fails. after cd ../../ it works ok.

**Comment by jean-emmanuel** [comment]
Hmm, I can't reproduce the bug, `npm run build` doesn't change the working directory here...

**Comment by ovenwerks** [comment]
Another pull and the problem is gone here too.
