### ISSUE TITLE
Imposter! 1.9.5 is 1.9.4!!

### ISSUE THREAD

**Issue by GeneralMidi** [jean-emmanuel/open-stage-control#720]
1.9.5 shows as 1.9.4 in the filename still.

Actually it's still 1.9.4 as the geometry issue and VAR issues still exist. 

![image](https://user-images.githubusercontent.com/47597511/117167528-9d0e7680-adc7-11eb-8de3-4c380bc91ad9.png)

**Comment by jean-emmanuel** [comment]
1.9.5 is reuploading
