### ISSUE TITLE
[Bug]VAR syntax doesn't update default value.

### ISSUE THREAD

**Issue by GeneralMidi** [jean-emmanuel/open-stage-control#721]
VAR syntax doesn't update default value. 

![vars don't update](https://user-images.githubusercontent.com/47597511/117283390-080e8a80-ae66-11eb-84ce-acea8768a425.gif)

edit: Also, cutting the text widget, then hitting undo also stops it updating. Have to then remove the VAR{}, enter random text, then re-add the VAR{}

And re-opening a session makes the text widget show nothing if it has VAR{} in its label.

**Comment by jean-emmanuel** [comment]
Fixed.

> And re-opening a session makes the text widget show nothing if it has VAR{} in its label.

I could not reproduce that.

**Comment by GeneralMidi** [comment]
I can't reproduce it now either...feel free to close this.

**Comment by jean-emmanuel** [comment]
It's not related to the var syntax, it's just that the two widget's values are sync'ed and the last one that's created has an empty value.

**Comment by GeneralMidi** [comment]
Oh. Yes, that is then rather simple. Thank you. Feel free to close this.
