### ISSUE TITLE
Word wrap in Text boxes

### ISSUE THREAD

**Issue by GeneralMidi** [jean-emmanuel/open-stage-control#722]
Not a deal breaker, a slight cosmetic improvement if possible. I'm using text widgets a lot to help me remember certain things within the program. 

If possible, can text wrap avoid breaking in the middle of words?

![image](https://user-images.githubusercontent.com/47597511/117359350-8d6e5b00-aeb7-11eb-94cf-a6eb4daae2d2.png)

**Comment by jean-emmanuel** [comment]
haha, I already pushed that an hour ago  !

**Comment by GeneralMidi** [comment]
That's so funny. Awesome though. 

What about also....if I could ask....if a numbered list is there, indent the output it looks like a numbered list? Hope you get what I mean.

**Comment by GeneralMidi** [comment]
Hi. Soft is working for buttons, but can you please make it work for text boxes?
