### ISSUE TITLE
[Feature] assist user with VAR syntax

### ISSUE THREAD

**Issue by GeneralMidi** [jean-emmanuel/open-stage-control#725]
I find myself forgetting the syntaxes often. Yes, I should learn them. But perhaps, if quotes are useless in VAR{} blocks (as in you would never ever need to put quotes for the property name), perhaps you could make life a tiny bit easier for the user and they could be removed upon hitting enter? This already exists when entering digits in a numeric field in quotes, they are automatically removed (e.g. entering '2' in gridTemplate removed the quotes)

![image](https://user-images.githubusercontent.com/47597511/117424182-cd6a2800-af21-11eb-9f33-aba7717c3381.png)

Maybe also here, if quotes are this time **necessary**, perhaps it might be an idea to put them in if we forget? We should probably just learn correct syntax...but it's an idea.

![image](https://user-images.githubusercontent.com/47597511/117446322-352d6c80-af3c-11eb-83e3-90e0b51d513d.png)

**Comment by jean-emmanuel** [comment]
I'm pushing a commit to simply ignore quotes around the name in the VAR syntax.

> Maybe also here, if quotes are this time necessary, perhaps it might be an idea to put them in if we forget? We should probably just learn correct syntax...but it's an idea.

Correcting code syntax on the fly is way too complex, learning the syntax and checking the console for syntax errors is the way.
