### ISSUE TITLE
[Bug]1.9.7 script Syntax Error: Unexoected Token '}' 

### ISSUE THREAD

**Issue by GeneralMidi** [jean-emmanuel/open-stage-control#729]
![image](https://user-images.githubusercontent.com/47597511/117624046-c4bd6000-b174-11eb-9337-16ffc4eb18dd.png)

I have this in a script widget
![image](https://user-images.githubusercontent.com/47597511/117624145-df8fd480-b174-11eb-9b87-f61f889c4bce.png)

A small session file here:

[broken.zip](https://github.com/jean-emmanuel/open-stage-control/files/6450360/broken.zip)

**Comment by jean-emmanuel** [comment]
There must be a statement after the condition, that's the cause of the error.
