### ISSUE TITLE
[Feature request] double click and tap

### ISSUE THREAD

**Issue by guitmart** [jean-emmanuel/open-stage-control#73]
Hi, is it possible to implement a dooble click or double tap for reset fader and knob to default value.
ex: fader at 106db, double tap, fader at 0db.
Thanks

**Comment by cyberic99** [comment]
I think that double clicks could be a bit hard to implement on a touch interface.
On these, maybe a 'long press' could be used?

That said, I would find it useful too if a single button could set the state of several widgets at the same time...

**Comment by guitmart** [comment]
I implement with this code in scripts.js but is not perfect 

		this.timeout;
		this.lastTap = 0;
	
		this.widget.on('dblclick',this.dblclickHandleProxy.bind(this))
		this.widget.on('touchend',this.doubleTapHandleProxy.bind(this))
        this.widget.on('mousewheel',this.mousewheelHandleProxy.bind(this))
        this.canvas.on('draginit',this.draginitHandleProxy.bind(this))
        this.canvas.on('drag',this.dragHandleProxy.bind(this))

        if (widgetData.spring) {
            this.canvas.on('dragend', ()=>{
                this.setValue(this.springValue,{sync:true,send:true,fromLocal:true})
            })
        }

        this.input.change(()=>{

            this.setValue(parseFloat(this.input.val()),{sync:true,send:true})

        })

        this.setValue(this.originValue)

    }
	
	dblclickHandleProxy(){
		
		this.dblclickHandle (...arguments)
		
	}
	
	doubleTapHandleProxy(){
		
		this.doubleTapHandle (...arguments)
		
	}
	
    mousewheelHandleProxy() {

        this.mousewheelHandle(...arguments)

    }

    draginitHandleProxy() {

        this.draginitHandle(...arguments)

    }

    dragHandleProxy() {

        this.dragHandle(...arguments)

    }

	dblclickHandle(e, data, traversing) {
		
		this.setValue(this.springValue,{sync:true,send:true,fromLocal:true})
		
	}
	
	doubleTapHandle(e, data, traversing) {
		
		var currentTime = new Date().getTime()
		var tapLength = currentTime - this.lastTap

		e.preventDefault()
		clearTimeout(this.timeout)

		if(tapLength < 500 && tapLength > 0){
			this.setValue(this.springValue,{sync:true,send:true,fromLocal:true})
		}
		
		this.lastTap = currentTime
		
	}

**Comment by jean-emmanuel** [comment]
Hi, unified double taps/clicks should not be too hard to implement, I'll give it a shot this evening. Long press/touch is already used as it acts as a right click.

**Comment by jean-emmanuel** [comment]
Alright, double tap/click support is implemented as an option (`doubleTap`, disabled by default) for:
- faders/knob/encoder/xy: reset to initial value on double tap/click
- modal: require a double tap/click to open instead of a single tap

**Comment by jean-emmanuel** [comment]
Included in v0.18.0

**Comment by guitmart** [comment]
Wow super déjà dans cette version je ne pensais pas que ce serait déjà
dedans la version.
Super thank you.

P.S. J'aimerais savoir comment builder sur windows car quand j'ai essayé
une erreur a été levée disant que je n'étais pas sur un environnement
"debian"

2017-06-14 18:24 GMT-04:00 jean-emmanuel <notifications@github.com>:

**Comment by jean-emmanuel** [comment]
Tu peux ouvrir un nouveau ticket avec plus d'infos ?
