### ISSUE TITLE
[Bug]Can't select widgets in session

### ISSUE THREAD

**Issue by GeneralMidi** [jean-emmanuel/open-stage-control#731]
Apologies if this is obvious. Might be worth a look though. 

![cantSelectFadersInSession](https://user-images.githubusercontent.com/47597511/117938185-0b42c400-b307-11eb-83f4-a512008beb82.gif)

[cantSelectFadersInSession.zip](https://github.com/jean-emmanuel/open-stage-control/files/6464402/cantSelectFadersInSession.zip)

**Comment by jean-emmanuel** [comment]
Your faders all have a width of 270...
