### ISSUE TITLE
[Feature] Improve importing from earlier versions

### ISSUE THREAD

**Issue by GeneralMidi** [jean-emmanuel/open-stage-control#732]
I'm really not sure if you can do much, but this looks  rather terrible when converted. 

Original (ver 0.45 I think)
![image](https://user-images.githubusercontent.com/47597511/117957544-7a75e380-b31a-11eb-9451-efd49d89a873.png)

And after conversion
![image](https://user-images.githubusercontent.com/47597511/117957751-a8f3be80-b31a-11eb-8777-70e748dad829.png)

Apart from the odd widget conversion, the general look looks really bad. The glowing text has disappeared, the colours are off, padding is missing, it just doesn't look good. 

Is there anything you can do to get the conversion looking better, or do I have to go in and redo it? If so, do you have any tips?

Thank you for your time. 
Luke

More images here:
https://github.com/ThrashJazzAssassin/REAPER-OSC-panels

Original session here
[REAPER OpenStageControl TJA 0.2.3.zip](https://github.com/jean-emmanuel/open-stage-control/files/6465414/REAPER.OpenStageControl.TJA.0.2.3.zip)

**Comment by jean-emmanuel** [comment]
> Is there anything you can do to get the conversion looking better

No, automatic conversion from v0 sessions to v1 is basic and will never provide a 1:1 conversion, too many things have changed.

> or do I have to go in and redo it? If so, do you have any tips?

Maybe ask the session's author to help you porting the interface to v1 ?

**Comment by GeneralMidi** [comment]
I completely understand, and don't want to waste any more of your time.

One last question, then I won't disturb for a while!

It seems in this session, the only css rule that the author has added is ``--color-track: #111922;`` to root. 

I had a look and it seems this variable isn't around anymore in v1. Would you briefly point me to the correct variable? It's this kind of faded out glow colour that I'm hoping this variable was responsible for...

![image](https://user-images.githubusercontent.com/47597511/118032903-75d81c00-b368-11eb-890e-146ac685e3bb.png)

**Comment by jean-emmanuel** [comment]
There's no equivalent to this in v1. You'll need to fiddle with css to get this effect.
