### ISSUE TITLE
[Feature] Bring back "edit parent"

### ISSUE THREAD

**Issue by GeneralMidi** [jean-emmanuel/open-stage-control#733]
Or perhaps, 'select parent' instead of 'edit parent'. 

I would find this really helpful. You probably don't want too many right click menu options, but a way to quickly select the parent in the session without scrolling all the way up the tree would be really great.

![bring back select parent container](https://user-images.githubusercontent.com/47597511/118443606-63edd480-b6ec-11eb-8176-d0405f829b85.PNG)

**Comment by jean-emmanuel** [comment]
You can hit the left arrow to do that.

Le 17/05/2021 à 08:49, GeneralMidi a écrit :

**Comment by GeneralMidi** [comment]
Oh! That's awesome. Thanks!

**Comment by jean-emmanuel** [comment]
No problem ;)
