### ISSUE TITLE
[Bug]Button sending 0

### ISSUE THREAD

**Issue by GeneralMidi** [jean-emmanuel/open-stage-control#734]
Me again. I hope this is ok to ask. I need to send the value 0 from a button (for a cc value which can be 0). You can see from the gif that changing it to 0 ,even when on tap, causes the button to stay on. Changing the off value is a workaround. 

![button send 0](https://user-images.githubusercontent.com/47597511/118798550-0f8a5680-b89e-11eb-9ebb-09b254aabfaf.gif)

This could be me not understanding this properly, so if so, I apologise.

**Comment by jean-emmanuel** [comment]
This happens when on and off are equal, change off to fix it.

**Comment by GeneralMidi** [comment]
Ok, but I don't need off because it's set to tap. Hrmm

I'm generating the buttons, so I guess I'll need to add some logic into check if on and off are equal. Seems excessive if the button is set to tap?

**Comment by GeneralMidi** [comment]
yes of course, like a string. Thank you.
