### ISSUE TITLE
[Feature] switch, pouvoir doubler les valeurs

### ISSUE THREAD

**Issue by Ezrabox** [jean-emmanuel/open-stage-control#735]
Sur le switch j'ai besoin de mettre plusieurs boutons avec la même valeur, mais ce n'est aujourd'hui pas autorisé, il efface automatiquement les doublons. Serait il possible de permettre différents boutons avec la même valeur sans qu'il s'efface automatiquement?

**Comment by jean-emmanuel** [comment]
Problème déjà discuté ici: https://openstagecontrol.discourse.group/t/switch-text-duplicate-labels/1541

**Comment by Ezrabox** [comment]
Merci! --
