### ISSUE TITLE
Scrollbars on IOS can't be disabled.

### ISSUE THREAD

**Issue by stevmills** [jean-emmanuel/open-stage-control#738]
Seeing a new issue after updating past version 1.8.13 where scrollbars are always shown, regardless of configuration.

Running on iPad Pro 12.9" @ iOS v.14.4.2. Browser is Kiosker.

Screen capture from Open Stage Control v.1.8.13:
![before](https://user-images.githubusercontent.com/4315440/120571901-aef03300-c3e0-11eb-8cc7-566f977e3cde.jpg)

Screen capture from any version newer than 1.8.13:
![after](https://user-images.githubusercontent.com/4315440/120571950-c16a6c80-c3e0-11eb-9139-438fa6f69e99.jpg)

Seeing the same behavior on regular browsers on iOS, such as Safari.

**Comment by jean-emmanuel** [comment]
Are you using the latest 1.9.8 ?

**Comment by stevmills** [comment]
I definitely checked that the scroll properties were set to false. However, I am on 1.9.7 instead of 1.9.8 because of a separate issue! I apologize for not realizing that when I opened the issue; I got so distracted trying to solve the scroll bar issue that I forgot about having downgraded to 1.9.7 previously.

The issue with 1.9.8 is that the matrix of clones will not populate at load time. The only way to get them to show up is to enable the editor, navigate to the matrix in the widget tree, change the matrix "props" field in some way, and then revert the changes.

![198](https://user-images.githubusercontent.com/4315440/120647372-273a1100-c440-11eb-8bac-21c5b601f0bb.jpg)

Should I open a separate issue for this?

One thing to note, I haven't tested the above workaround to get the matrix clones to show up on iOS because I can't seem to edit any fields from iOS.

Thank you for your time!!

**Comment by jean-emmanuel** [comment]
There was a fix for ios scrollbars in 1.9.8. Can you upload your session so that I can debug the matrix issue ?

**Comment by stevmills** [comment]
Sure thing! Thanks!
[millers.zip](https://github.com/jean-emmanuel/open-stage-control/files/6592617/millers.zip)

**Comment by jean-emmanuel** [comment]
It's fixed in v1.9.9 (deploying at the moment). Here is your session with some small layout fixes made to the faders.  
[millers.zip](https://github.com/jean-emmanuel/open-stage-control/files/6593713/millers.zip)
