### ISSUE TITLE
Use webMidi instead of requiring pyo dependency

### ISSUE THREAD

**Issue by diegodorado** [jean-emmanuel/open-stage-control#74]
I'm not sure if this may be possible.. but couldn't open-stage-control use webMidi to send notes and cc instead of requiring pyo?
I'm actually using windows 10 and pyo doesnt work here, so I am looking for an alternative. In the meantime I am planning to send osc to supercollider and route that to a midi device.

**Comment by jean-emmanuel** [comment]
Hi, I'm probably going switch to [pyrtmidi](https://github.com/patrickkidd/pyrtmidi) for handling midi, it's much lighter, dedicated to it and handles virtual ports (linux & osx). Can you check if it builds/runs  well under windows 10 ?

WebMidi is an interesting option but I haven't managed to make it work server-side (o-s-c clients don't send osc/midi themselves, only the server does), plus doens't provides enough features to replace the current implementation completely.

**Comment by jean-emmanuel** [comment]
Migration to `pyrtmidi` can be tested in the dev branch, the release should come within the end of the month.

**Comment by diegodorado** [comment]
y cannot see the dev branch... i only see master and gh-pages

**Comment by jean-emmanuel** [comment]
I just merged it today, you can checkout the master branch now
