### ISSUE TITLE
[Feature] QWERTY keyboard mapping to Keyboard widget

### ISSUE THREAD

**Issue by brbrr** [jean-emmanuel/open-stage-control#740]
I'm using OSC to simplify the development of a MIDI-related project. While the existing functionality is sufficient, I'd love to have a way to trigger midi notes via the keyboard on my computer. (Similar to how DAWs provides a "note keyboard" functionality. 

Thanks!

**Comment by jean-emmanuel** [comment]
You can use a script widget with  `event` set to `keyboard` to bind arbitrary actions to keystrokes : https://openstagecontrol.ammd.net/docs/widgets/scripting/
