### ISSUE TITLE
How to build with windows

### ISSUE THREAD

**Issue by guitmart** [jean-emmanuel/open-stage-control#75]
Hi Jean Emmanuel,
When I tested to build the source, I had  a message (... debian...).
My question is What is the procedure to build with windows?

Thanks

**Comment by jean-emmanuel** [comment]
Can you tell me exactly what you did ? The full error message could help too.

**Comment by guitmart** [comment]
I want to build from windows because I have some issues with Ipad ios 9 and I do not want to bother you with that. I want to buid with ecmascript 5.
This the error

------directory---->npm install
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "E:\\nodeJs\\node.exe" "E:\\nodeJs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for electron-installer-debian@0.5.1: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:

**Comment by jean-emmanuel** [comment]
You can remove line 15 from the `package.json` (`"electron-installer-debian": "0.5.2"`), it's not needed and cannot be installed on windows. I'm gonna make this dependency optionnal to make sure build doesn't fail on windows. Thanks for the feedback (don't hesitate with other issues !).

**Comment by jean-emmanuel** [comment]
Fixed since https://github.com/jean-emmanuel/open-stage-control/commit/31b88df6beb61bde5aeee2263ba2c728b396e1be
