### ISSUE TITLE
[Bug] Windows identifies multiple versions of win32-x64 zip as Trojan

### ISSUE THREAD

**Issue by Daddygassy** [jean-emmanuel/open-stage-control#750]
Hi,

I've attempted to download multiple versions of win32-x64 zip and each is identified as Win32/Zpevdo.B by windows security centre.

![Screenshot 2021-09-01 074224](https://user-images.githubusercontent.com/89899730/131625184-8195dc05-24f6-4173-a40c-ccd271ee4fdf.png)

I have a previous installation of open-stage-control-1.6.1-win32-x64 which works fine.

I'm on Windows 11 version 21H2 (OS Build 22000.168)

Can you please advise?

**Comment by jean-emmanuel** [comment]
It's a false positive alert caused by one file and how it is built, I can't fix it unfortunately. See [this post](https://openstagecontrol.discourse.group/t/testing-needed-out-of-the-box-midi-support/808/29?u=jean-emmanuel).
