### ISSUE TITLE
[Bug] v0 templates looks very off in v1

### ISSUE THREAD

**Issue by fractalf** [jean-emmanuel/open-stage-control#751]
Hi,
thank you for this great project!

I just discovered it (coming from TouchOSC) and tried it out today.
I'm on Linux Mint 20.2 using Bitwig 4.

So i found a couple of pre-made templates

* https://github.com/kdejaeger/open-stage-control-bitwig
* https://github.com/Sebastian-blu/sebastianBitwigOpenSoundControl

I didn't try to connect anything to Bitwig, just opened them in the downloaded osc package (v1.9.14)

Everything looked very different from the screenshots, so I downloaded v0.49.12 and tried it. That seemed to work just fine.

So, is there a backward compability issue here or just me missing something?

Here's some screenshots I made testing this:

Template 1 with v0.49.12

![osc-bitwig-0 49](https://user-images.githubusercontent.com/5707457/133936770-c9f6fc7d-075f-4ed7-a95d-50a32346f8a2.png)

Template 1 with v1.9.14

![osc-bitwig-1 9](https://user-images.githubusercontent.com/5707457/133936771-b4a8d5f0-cbdb-416b-8148-f42f01d8187e.png)

Template 2 with v0.49.12

![osc-bitwig-barry-0 49](https://user-images.githubusercontent.com/5707457/133936772-b3231b1d-ea61-45ed-81cf-6cab0cfb9732.png)

Template 2 with v1.9.14

![osc-bitwig-barry-1 9](https://user-images.githubusercontent.com/5707457/133936773-3c21db9d-d87d-477c-a832-3839584c8f63.png)

Cheers

**Comment by jean-emmanuel** [comment]
Backward compatibility between v0 and v1 merely allows old sessions to load, too many things have changed in v1 (hence the major version increment, which indicates breaking changes), things are expected to look off and possibly behave differently or even break in some cases.
