### ISSUE TITLE
[Bug] In Sliders range the order of the keys is significant.

### ISSUE THREAD

**Issue by PLu55** [jean-emmanuel/open-stage-control#752]
If the order of min and max keys are changed in the range of a sliders it stop working. The order of the keys should not be significant but it is.

I'm generating session files programmatically and when I updated my software the sliders stop to work and I realized the order of the keys in the range setting of the sliders has been reversed.  

- Open Stage Control version: 1.9.14
- Operating system: Kubuntu 21.04
- Open Stage Control options: none
- Client type: built-in

[slider-range-order.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/7207772/slider-range-order.json.txt)

**Comment by jean-emmanuel** [comment]
Fixed in sources.

**Comment by jean-emmanuel** [comment]
Fixed in 1.10.0
