### ISSUE TITLE
[Bug] Scrolling a panel by it's value do not initially follow it.

### ISSUE THREAD

**Issue by PLu55** [jean-emmanuel/open-stage-control#756]
When moving the scrollbar in the left panel is initially not following the right panel as expected, only after the scrollbar has hit it's bottom then the left panel starts to follow. It's indifferent if the left panels scrollbar is hidden or not.

- Open Stage Control version: 1.11.0
- Operating System: Kubuntu 21.04
- Kernel Version: 5.11.0-38-lowlatency
- Open Stage Control options: --disable-gpu
- Client type: built-in
- Server logs: none 
- Client logs: none

[scroll.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/7462455/scroll.json.txt)

**Comment by jean-emmanuel** [comment]
Should be fixed in v1.11.1
