### ISSUE TITLE
[HELP] Changing Button's State via OSC

### ISSUE THREAD

**Issue by shouweiteoh** [jean-emmanuel/open-stage-control#757]
Hi All,

New to scripting & osc would like to seek some help on how to achieve the following :

1. Changing button's state on off(0/1) remotely via OSC. 

Specifically I have setup network cue from Qlab and couldn't change the button state.

I am aware of this page https://openstagecontrol.ammd.net/docs/remote-control/ but couldn't make qlab take to the button.

Any help is greatly appreciated !!!

Thanks

**Comment by jean-emmanuel** [comment]
Setting the target is not required to receive messages, see https://openstagecontrol.ammd.net/docs/widgets/general-mechanics/#receiving-messages. To make it simple, setting a widget's value in osc is done by sending the same message its sends. 

Please use the forum for usage question : https://openstagecontrol.discourse.group/

**Comment by shouweiteoh** [comment]
Thanks guys !!!! The forum helps !!!! Will be closing this and pay more attention to the forum !!!
