### ISSUE TITLE
[Bug] running npm install result in an error

### ISSUE THREAD

**Issue by pitrackster** [jean-emmanuel/open-stage-control#758]
Hi,

First of all what you did is amazing, thx a lot for your work !

I'm trying to install from sources and when I run `npm install` it results in an error.

- OSC Master branch
- Ubuntu 20.04 LTS
- npm 8.1.0
- node 16.13.0

From what I found in npm logs this is related to node-sass

```log
4975 timing command:install Completed in 189351ms
4976 verbose stack Error: command failed
4976 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
4976 verbose stack     at ChildProcess.emit (node:events:390:28)
4976 verbose stack     at maybeClose (node:internal/child_process:1064:16)
4976 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
4977 verbose pkgid node-sass@5.0.0
4978 verbose cwd /home/pitrack/electron-workspace/open-stage-control
4979 verbose Linux 5.11.0-40-generic
4980 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
4981 verbose node v16.13.0
4982 verbose npm  v8.1.0
4983 error code 1
4984 error path /home/pitrack/electron-workspace/open-stage-control/node_modules/node-sass
4985 error command failed
```

So I removed node-sass dependency from `package.json` execute `npm install` again and it worked. 

Then I installed node-sass `npm install node-sass` and everything seems to work (I can build assets and launch the app).

Regards

**Comment by jean-emmanuel** [comment]
The version of node-sass in package.json doesn't support node v16, installing it like you did downloaded the latest version that supports it. The package.json will be updated eventually.

**Comment by pitrackster** [comment]
Ok thanks for the answer. Any reason to not update node-sass package to the current version ?

**Comment by jean-emmanuel** [comment]
No, I simply don't do automatically to avoid regressions.
