### ISSUE TITLE
Feature request - button color and text from OSC

### ISSUE THREAD

**Issue by einsteincz** [jean-emmanuel/open-stage-control#76]
It would be great to have a possibility to fetch button (led) background color and text from OSC. I am working on Martin M-PC control surface where are small LCDs.

**Comment by jean-emmanuel** [comment]
I'm not sure to understand your request, can you elaborate please ?

**Comment by einsteincz** [comment]
Martin M-PC is sending OSC like { address: '/Mx/belt/6122/button/color', args: 'green' }, it would be great to have a possibility to fetch button background color from this OSC messages. And same situation with text where { address: '/Mx/belt/6122/button/text', args: 'Intensity' } tells me the button actual  function.

**Comment by jean-emmanuel** [comment]
[`RgbLed`](http://osc.ammd.net/user-guide/widgets-specifics/plots/#rgbled) widgets can display a color received via osc, though it only supports numerical rgb values currently. I'll add the standard colors strings support in next release (coming soon, for real ;)).

[`Text`](http://osc.ammd.net/user-guide/widgets-specifics/plots/#text) widgets can display strings received via osc.

Combining these widgets with a toggle or a push button should do what you want
