### ISSUE TITLE
[Bug] Midi config preventing server start

### ISSUE THREAD

**Issue by ntrocado** [jean-emmanuel/open-stage-control#760]
If I enter something on the midi router config box (e.g. `midi:0,1`) I get the following error:

`(ERROR, HTTP) Could not setup http server, maybe try a different port ?`

With all settings empty the server starts and everything works.

Version is 1.11.1. I'm on 64-bit Windows.

The previous version (1.11.0) works, so it seems this was introduced in one of the latest commits.

**Comment by jean-emmanuel** [comment]
There no difference between the two versions that could explain that (https://github.com/jean-emmanuel/open-stage-control/compare/v1.11.0...v1.11.1). I also went through the packaging logs to verify nothing went weird for this release. I'll test on a windows system when I can.

**Comment by ntrocado** [comment]
I installed the most recent version on a different Windows machine, and the error is gone. Turns out this is a (very mysterious) problem on my side...

**Comment by jean-emmanuel** [comment]
Glad to hear that, thanks for the update.

**Comment by nilsporrmann** [comment]
i am having the same error ((ERROR, HTTP) Could not setup http server, maybe try a different port ?) without any midi settings, after having moved to windows 11. same settigns work fine on other PCs (windows 10).

**Comment by jean-emmanuel** [comment]
Did you try setting the port option to anything else than the default 
8080 as suggested in the error message ? The operating system may be 
using it already.

Le 06/06/2022 à 13:29, nilsporrmann a écrit :
