### ISSUE TITLE
Copying a line from a script seems to delete script from that widget [Bug]

### ISSUE THREAD

**Issue by Skateboss** [jean-emmanuel/open-stage-control#763]
If you copy a line from a script on one widget and paste it into another widgets script area, the script is removed completely from the first widget.

Version 1.13.0 Beta

Kind regards,
Chris

**Comment by jean-emmanuel** [comment]
Could you please try with the latest non-beta version and - if the bug still occurs - provide step by step instructions to reproduce it ?

**Comment by Skateboss** [comment]
I haven't had a chance to test in the stable release but these are the steps needed to produce the bug in 1.13.0 beta:

1. create two buttons
2. write a script in button one
3. highlight a line in the script
4. right click then click copy or (ctrl+c) seems to do the same
5. select second button then right click paste in the scripting area

This erases the script from the first button.

If you try to paste the script back into the first button it seems to dissapear from both buttons.

It seems to occur upon selecting the second button after copying the script.

Hope this helps.

Kind regards,
Chris

**Comment by jean-emmanuel** [comment]
Thanks, bug confirmed.

**Comment by jean-emmanuel** [comment]
Fixed in v1.13.1 (deploying at the moment)

**Comment by Skateboss** [comment]
I can confirm that the bug is now fixed in 1.13.1 

Many thanks for your prompt fix!
