### ISSUE TITLE
[Bug] html & css - Enter key

### ISSUE THREAD

**Issue by Skateboss** [jean-emmanuel/open-stage-control#765]
If you press the enter key while focused on html or css properties in the editor, the focus is lost rather than moving the cursor down to the next line

it would also be great to have a 'cut' button when right clicking in the script editor rather than just copy & paste
regards,
Chris

**Comment by jean-emmanuel** [comment]
This is not a bug but the default behavior for property inputs (hit shift+enter to insert a new line). Adding the multiline editor feature to these properties (like with `script`) is an option though, I havent made up my mind about it yet.

> it would also be great to have a 'cut' button when right clicking in the script editor rather than just copy & paste

done
