### ISSUE TITLE
[Bug] Fragments session does not load correctly, need to preload each fragment

### ISSUE THREAD

**Issue by groolot** [jean-emmanuel/open-stage-control#767]
- Open Stage Control version (or commit if built from sources)
1.12.0

- Operating system
Debian GNU/Linux unstable, Firefox 96.0, Chromium 97.0.4692.71

- Open Stage Control options
N/A

- Client type (built-in or external browser) and version
Built-in

- Session file (can be uploaded after adding the .txt extension)
end fragment [chainsaw-gui-global-instrument-mixer.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/7884774/chainsaw-gui-global-instrument-mixer.json.txt)
mixers fragment with 4 instances of `chainsaw-gui-global-instrument-mixer` [chainsaw-gui-global-mixer.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/7884775/chainsaw-gui-global-mixer.json.txt)
FX chain fragment [chainsaw-gui-track-chain-fx.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/7884778/chainsaw-gui-track-chain-fx.json.txt)
Particle fragment with an instance of `chainsaw-gui-track-chain-fx.json` [chainsaw-gui-particletrack.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/7884777/chainsaw-gui-particletrack.json.txt)
Looper fragment with an instance of `chainsaw-gui-track-chain-fx.json` [chainsaw-gui-loopertrack.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/7884776/chainsaw-gui-loopertrack.json.txt)
Main with an instance of `chainsaw-gui-loopertrack.json` and `chainsaw-gui-particletrack.json` and `chainsaw-gui-track-chain-fx.json` [chainsaw-gui.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/7884773/chainsaw-gui.json.txt)

# Problem
When I try to load a global session with encapsulated fragments (nested) client enters in a kind of endless loop which is unfortunately not debugable within JavaScript console.
But, if I preload each fragment before it is loaded by an encapsulator, everything is fine and the UI is fluid as beer in a dry throat.

**Comment by groolot** [comment]
https://user-images.githubusercontent.com/632571/149843384-53636b07-7383-4879-a604-a78b6d2e3562.mp4

**Comment by jean-emmanuel** [comment]
Found and fixed with f419ac8b, a nasty bug indeed !

**Comment by groolot** [comment]
Still have the same behaviour :(

**Comment by jean-emmanuel** [comment]
If you packaged v1.14.0 before pulling the latest commits you may encounter a caching issue, please pull and run `npm run build` again.

**Comment by groolot** [comment]
ok, the latest 291eb669 fixes the bug!
great job!
