### ISSUE TITLE
Editor warning/error tooltip appearing on the left side of client window

### ISSUE THREAD

**Issue by Clelsonrl** [jean-emmanuel/open-stage-control#768]
OSC version 1.14.1
Windows 10

It's a cosmetic issue, but I decided to report it here.
When you have wrong syntax or the editor have a syntax suggestion, when hovering the highlighted colored line with the mouse, the tooltip appears in the opposite side (hard left) of the client window. See picture below:

![Image 1](https://user-images.githubusercontent.com/67846371/150215633-022ab2f1-8f40-4974-96b8-73671291f85e.png)

**Comment by jean-emmanuel** [comment]
Yes, it's a regression introduced in v1.14.0, it's been fixed in sources earlier today :)
