### ISSUE TITLE
Clone of canvas not working in 1.14.1

### ISSUE THREAD

**Issue by Clelsonrl** [jean-emmanuel/open-stage-control#769]
In version 1.13.2 I created some clones of the new canvas widget, and they were working fine.
When I opened those sessions in 1.14.1, the same clones just don't draw anything anymore.
I tested in isolation with the two before mentioned versions creating a session from scratch, using a simple ctx.fillRect() call, and the problem is confirmed in version 1.14.1.

I hope you have some lights about what's happening. I have no clue ^.^
Thanks again!

**Comment by jean-emmanuel** [comment]
could you please upload the session file created with v1.13 ?

**Comment by jean-emmanuel** [comment]
Nevermind, bug confirmed.

**Comment by jean-emmanuel** [comment]
Should be fixed in v1.14.2

**Comment by Clelsonrl** [comment]
Amazing! Thank you very much!
