### ISSUE TITLE
[bug] On the ipad the modal button does not look the same.

### ISSUE THREAD

**Issue by dotzspee** [jean-emmanuel/open-stage-control#770]
On the ipad the modal button does not look the same.
When I press the modal button on the iPad, it turns black on the iPad.
Tried Chrome, Firefox, Safari and Full Screen Web Broser, always the same.

Same
<img width="2168" alt="iMacNotPushed" src="https://user-images.githubusercontent.com/13273454/150633624-16d3461b-dfb3-4f9f-9581-dc981c6e77b2.png">

Same
![iPadNotPushed](https://user-images.githubusercontent.com/13273454/150633628-38867a63-8472-46c1-90cc-f843ea8a3321.PNG)

I think this way it has to be on the iMac...
<img width="2165" alt="iMacPushed" src="https://user-images.githubusercontent.com/13273454/150633632-8e691429-0553-4893-adbd-6ceba34c5b38.png">

The pushed button is black on the iPad
![iPadPushed](https://user-images.githubusercontent.com/13273454/150633637-a90a1a83-56f5-4879-b00c-2b4a40440beb.PNG)

**Comment by jean-emmanuel** [comment]
Please try without any theme file loaded, there are some css rules that may not work properly on ipad (in which case I don't think I can fix it).

**Comment by dotzspee** [comment]
The Theme was only a Test with

.rounded-corner5 {
    border-radius: 5px;
}
.schrift100 {
    font-size: 100%;
}
.schrift200 {
    font-size: 200%;
}

The theme is removed now but the result does not change. Modal is not working for me. Maybe i have to create panel and hide.
What do you think?

**Comment by jean-emmanuel** [comment]
Could you please upload your session file and tell me the version of the operating system on the ipad ?

**Comment by dotzspee** [comment]
I used the newest iPad Software 15.2.1. 
[2022-01-22_07_01.json.zip](https://github.com/jean-emmanuel/open-stage-control/files/7919247/2022-01-22_07_01.json.zip)

Here I have the file for you. With both modal buttons I have the same problem.

**Comment by jean-emmanuel** [comment]
Thanks, it's fixed in sources, to be included in next release.
