### ISSUE TITLE
Character offset in editor while typing

### ISSUE THREAD

**Issue by Sakamacheee** [jean-emmanuel/open-stage-control#774]
Hi !

Here's the bug : when typing (here in props field), it occurs that kind of an offset "appears" when typing.
For example, if i have typed "Wonderzul", if i want to delete the "z" character, i'll have to place the cursor right before the "r" character, otherwise i will delete the "u" character...

Here's a small gif : 
![HIAHCIv9eb](https://user-images.githubusercontent.com/95777621/152989894-516f7448-079f-4522-b0df-7ab10c8f947c.gif)

As we can see here, typing is ok in the first line, but starts to bug at line 2.

Thank you

**Comment by jean-emmanuel** [comment]
It seems to happen only when there is a long sequence of spaces at the beginning of the line, I'll investigate.

**Comment by jean-emmanuel** [comment]
Fixed in sources. If you can't wait for next release, put this in a theme file : 
```css
.ace_indent-guide {
    margin-left: -1rem;
}

**Comment by Sakamacheee** [comment]
Well done, thank you !
