### ISSUE TITLE
Text input in modal dialog fails working with android mobile browser

### ISSUE THREAD

**Issue by mxklb** [jean-emmanuel/open-stage-control#775]
First of all thank you for that great piece of software!

I just realized this with one of the latest releases: [v1.14.4](https://github.com/jean-emmanuel/open-stage-control/releases/tag/v1.14.4)

- running the node version on raspberry host (ubuntu server 20.04, arm64)
- accessing osc over LAN via android mobile browser (chrome)

I use a modal dialog with some text inputs. This is working fine when using desktop browser (vivaldi, chrome, ..).

- When using android mobile browser to edit a text input placed inside a modal dialog it does not pop up the android keyboard.
- Moving a copy of the text input out of the modal (placing it in parent tab widget) makes it work again.

I think it's a bug with modals, inputs and mobiles. In former releases this was working as expected (keyboard pops up).

Hope this helps making great software even greater :beers:

**Comment by jean-emmanuel** [comment]
Thanks for the report, I made a tiny mistake indeed that's now fixed in sources (https://github.com/jean-emmanuel/open-stage-control/commit/24019c72030ca7bf3cf80be6ada4435a7e72f95e)

**Comment by jean-emmanuel** [comment]
Fixed v1.14.6
