### ISSUE TITLE
[Bug] Upper left "..." menu no longer hidden in '--read-only' mode

### ISSUE THREAD

**Issue by rawbengal** [jean-emmanuel/open-stage-control#776]
Using 1.14.5 and specifying '--read-only' on the server command line no longer hides the '...' menu in clients. The menu button appears not to respond to clicks but remains visible.
The desired behavior is for '--read-only' to completely hide any menu or other actions related to editing of the session.

**Comment by jean-emmanuel** [comment]
Right, a little regression caused by the addition of the "hideMenu" option to the root widget, to be fixed !
