### ISSUE TITLE
Broken $ in matrix props

### ISSUE THREAD

**Issue by ThrashJazzAssassin** [jean-emmanuel/open-stage-control#777]
Input:
![image](https://user-images.githubusercontent.com/15689085/157657228-4ec725de-607d-4aa7-87ec-0632a5505c7c.png)

Output:
v1.15.3
![image](https://user-images.githubusercontent.com/15689085/157657307-40e39f37-e0aa-4280-b5b9-07654a9cefd0.png)

v1.15.4
![image](https://user-images.githubusercontent.com/15689085/157657496-aef62a60-43c1-4c24-be0f-a405c07ae978.png)

**Comment by jean-emmanuel** [comment]
Thanks, it should be fixed in v1.15.5

**Comment by ThrashJazzAssassin** [comment]
Thanks Jean
