### ISSUE TITLE
[Bug] calling "set" on "range" widget only sets a single value

### ISSUE THREAD

**Issue by urstruktur** [jean-emmanuel/open-stage-control#779]
OSC version: v1.15.6
OS: Windows 10, 64-bit
Client type: tested both with built-in and external

Once both of the two sliders are interacted with via the UI, calling set("range_1", [0.1,0.9]) only changes one slider. This happens only when "max" is moved first and the "min" slider second.

![range_bug](https://user-images.githubusercontent.com/11160574/160367848-a115c662-6477-40e1-8ffb-67357a793ecf.gif)
[test_session.txt](https://github.com/jean-emmanuel/open-stage-control/files/8361377/test_session.txt)

Thank you for considering.

**Comment by jean-emmanuel** [comment]
Fixed in sources (for v1.15.8)
