### ISSUE TITLE
[Bug] Patchbay Label

### ISSUE THREAD

**Issue by Ezrabox** [jean-emmanuel/open-stage-control#782]
Hello, 
oSc v1.16.2
osx 11.2.3 
Il semblerait dans le descriptif que le Patchbay permette d'afficher un label sous la forme a"label_1": "input_1" à la place du "input_1" or cela ne fonctionne pas. 
Idéalement il serait bien que la valeur puisse être personnalisable comme dans les switchs or il n'accepte que "input_1" et non "x_1". Je ne sais pas si c'est voulu ou un dysfonctionnement? 
La bise
Ez

**Comment by jean-emmanuel** [comment]
Salut,
Les propriétés `inputs` et `outputs` permettent bien de définir des labels avec cette syntaxe :
```js
{
  "label A": "valeur 1",
  "label B": "valeur 2"
}
```

**Comment by Ezrabox** [comment]
En revanche , je vois que l'on ne peut pas procéder ainsi pour les outputs, je viens de créer cette liste : 
 {
  "M": "o_1",
  "j": "o_2",
  "k": "o_3",
  "l": "o_4",
  "p": "o_5",
  "o": "o_6",
  "h": "o_7",
  "b": "o_8",
  "v": "o_9",
  "n": "o_10",
  "s": "o_11"
}
et j'ai ce message qui revient
<img width="451" alt="Capture d’écran 2022-06-01 à 12 29 41" src="https://user-images.githubusercontent.com/33526688/171384585-2bb0df75-0d72-439f-8a7c-61dd1ef2e73a.png">

**Comment by Ezrabox** [comment]
merci!
