### ISSUE TITLE
[Feature] Patchbay exclusive mode

### ISSUE THREAD

**Issue by Ezrabox** [jean-emmanuel/open-stage-control#783]
Hello, j'utilise patchbay pour contrôler un matrix mixer que j'ai paramétré en mode exclusif (chaque entrée vers 1 seule sortie)
J'aimerais savoir si il serait possible de créer une option "routing exclusif" dans le patchbay quand cette option serait cochée une entrée ne pourrait aller que vers une sortie, ainsi l'adresse envoyée ne prendrait que la dernière sortie en argument et pas toutes les précédentes.

**Comment by jean-emmanuel** [comment]
option "exclusive" ajouté à la patchbay dans la prochaine version.
