### ISSUE TITLE
[Bug] Ports MIDI pas listés sous macOS

### ISSUE THREAD

**Issue by nesdnuma** [jean-emmanuel/open-stage-control#784]
Bug rencontré avec O-S-C 1.16.4 et 1.15.5 sous macOS El Capitan.

Simplement en lançant le serveur depuis l'app sous macOS et en indiquant "list" dans le champ "midi", avant même de créer une session, rien ne s'affiche alors que deux bus IAC ont été créés et sont actifs dans les préférences Audio/MIDI de macOS.

<img width="597" alt="Capture d’écran 2022-06-09 à 13 31 50" src="https://user-images.githubusercontent.com/6513218/172837142-64279fd8-f9a2-4bd9-ac1b-ada1333ff9e7.png">

**Comment by nesdnuma** [comment]
Via le menu -> List MIDI Devices, j'obtiens ce message d'erreur:
(ERROR, MIDI) [2145] Error loading Python lib '/var/folders/yc/1v4y0pvs14j3kt8cd2q0sswm0000gp/T/_MEIzgNh2j/Python': dlopen: dlopen(/var/folders/yc/1v4y0pvs14j3kt8cd2q0sswm0000gp/T/_MEIzgNh2j/Python, 10): Symbol not found: _clock_getres
  Referenced from: /var/folders/yc/1v4y0pvs14j3kt8cd2q0sswm0000gp/T/_MEIzgNh2j/Python (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/yc/1v4y0pvs14j3kt8cd2q0sswm0000gp/T/_MEIzgNh2j/Python

A JavaScript error occurred in the main process: Uncaught Exception:
TypeError: results is not iterable
    at /Applications/open-stage-control-darwin-x64/open-stage-control.app/Contents/Resources/app/server/src/server/midi.js:136:1

Je confirme que le fichier osc-midi-osx est présent.

**Comment by nesdnuma** [comment]
A tout hasard, est-ce que la version installée de Python a une importance quelconque? C'est la 2.7.10.

**Comment by jean-emmanuel** [comment]
Ok, l'executable `osc-midi-osx` n'est pas compatible avec cette version d'OSX (car compilé sur une machine plus récente à priori), j'essaierai de régler le problème mais je ne vais pas avoir le temps avant un moment. 

Tu peux tenter de remplacer ce fichier avec sa version précédente (https://github.com/jean-emmanuel/open-stage-control-midi/releases/download/v1.9.1/osc-midi-osx), à part un avertissement dans la console ça devrait fonctionner (il n'y a pas eu de changement important dans ce fichier).

Si ça ne marche pas non plus, tu peux t'en sortir en supprimant ce fichier et en suivant la procédure de configuration du midi à [cette page](https://openstagecontrol.ammd.net/docs/midi/midi-configuration/) sous "Installation > Other Systems".

**Comment by nesdnuma** [comment]
La première solution ne fonctionne pas! Tant pis pour aujourd'hui mais merci pour la réaction rapide!

**Comment by jean-emmanuel** [comment]
Je ne pense pas que j'aurais les moyens de regler le problème, j'ai trop peu de temps à passer sur la partie midi d'open stage control pour me plonger dans des problèmes de compilation spécifiques à os x.
