### ISSUE TITLE
[Bug] Non synchronisation des widgets lorsque que leur valeur "target" changent

### ISSUE THREAD

**Issue by HalTobin** [jean-emmanuel/open-stage-control#786]
Bonjour,

J'ai un mapping OSC dont la valeur "target" des widgets peut évoluer. Cependant les widgets ne sont pas automatiquement resynchronisé lorsque que la valeur "target" change, à moins que l'un des widgets soit à nouveau modifier par un autre client. Existe t-il une solution pour résoudre ce problème ?

J'ai joint le fichier du mapping qui pose problème. Pour changer la valeur "target" des widgets, il suffit de changer la valeur du DropDown situé à droite de l'objet textarea qui affiche "INSTANCE".

Passez une excellente journée,
Alexis

[MVS_multi.zip](https://github.com/jean-emmanuel/open-stage-control/files/9001796/MVS_multi.zip)

**Comment by jean-emmanuel** [comment]
C'est le comportement attendu (https://openstagecontrol.ammd.net/docs/widgets/general-mechanics/#widget-synchronization), pour résoudre le problème il faut leur donner la même `target` et gérer le routing des messages sortant avec un [custom module](https://openstagecontrol.ammd.net/docs/custom-module/custom-module/).

**Comment by HalTobin** [comment]
Merci pour votre réponse, je vais regarder ce que je peux faire avec la _target_ !
Bonne journée
