### ISSUE TITLE
Node server with authenticaton does not show up on iPhone

### ISSUE THREAD

**Issue by tihomir-pesikan** [jean-emmanuel/open-stage-control#788]
When running with authentication on node server, it does not show up on iPhone but fine on Android & OSX.
On iPhone is an empty screen, and  the "State" and "Editor" menus are greyed out.

When running the same on OSX server, is ok everywhere.

When i remove the authentication from the node server it functions on iPhone as well.
 
![WhatsApp Image 2022-07-16 at 4 24 01 PM](https://user-images.githubusercontent.com/31093050/179361280-bb05575c-32f3-453f-a153-edcc7e1715c2.jpeg)
![WhatsApp Image 2022-07-16 at 4 24 01 PM (1)](https://user-images.githubusercontent.com/31093050/179361286-c75c776d-6543-4093-bf57-7e5cecb3e62a.jpeg)

**Comment by jean-emmanuel** [comment]
Hi, sorry for getting back this late. Does the user/password popup show up on the iPhone ?

**Comment by tihomir-pesikan** [comment]
Yes the pop-up shows, clearing the cookies didn't help

**Comment by jean-emmanuel** [comment]
This should be fixed in v1.25.4.
