### ISSUE TITLE
Prevent device sleep in fullscreen

### ISSUE THREAD

**Issue by wargreen** [jean-emmanuel/open-stage-control#79]
Hi !

We are now using O.S.C for our show [Level up sound] and you can see that in Aurillac festival if you is there.
All work well, but my tablet go to sleep...
So is it possible to prevent this in fullscreen mode ?
I've found this js snippet :
http://qnimate.com/prevent-sleep-using-html5-standby-api/

**Comment by jean-emmanuel** [comment]
The snippet uses an API that's not implemented in any browser yet, but I'll dig this though, good idea :)

**Comment by jean-emmanuel** [comment]
Can you try the online demo, it might work now, but needs testing.

**Comment by jean-emmanuel** [comment]
There doens't seem to be a reliable way to acheive this yet. I'm leaving it to the many many 3rd party apps that are meant to prevent sleep mode ;).
