### ISSUE TITLE
[Feature] New container needed: Folder

### ISSUE THREAD

**Issue by AtmanActive** [jean-emmanuel/open-stage-control#795]
Hi,

I'm using Open Stage Control daily and I'm very much enjoying it.

Here are a few feature suggestions with the aim of making it even better.

Right now, we have all of these container options which are all great. Kudos for developing all that.
But, in my daily work I feel the need for one more container type: Folder.
Unlike a Panel or any other type, I would like Folder to pertain only to the tree on the left and nothing else. So, with Folder, I would like to avoid having my widgets grouped geometrically. The only purpose of a Folder would be to hide/show it's children in the tree (not hiding them in the canvas), and, optionally, to allow me to select all children with one click.

Yes, I know, Panel is very similar to this, but panel (like <div>) is a DOM container with it's own coordinates, which is not what I always want. In some cases, yes, Panel is great, but there are cases where I wish I could group/folderize/collapse widgets without them being stuffed in a separate panel.

Thank you for developing this awesome software!

**Comment by jean-emmanuel** [comment]
Unfortunately I hardly see it coming in a near future as it would require big changes to make it possible.

**Comment by AtmanActive** [comment]
Is there maybe a way to adjust/hack a Panel to behave like that?

**Comment by jean-emmanuel** [comment]
Actually there is and I'm fiddling with it at the moment... browser support might bean issue though

**Comment by jean-emmanuel** [comment]
The folder widget can be tested in v1.19.0-beta, a far as I can tell it works, but it relies on a css feature that's known to have pitfails...

**Comment by AtmanActive** [comment]
Wow. 
And I thought I knew CSS.
You learn something new every day.
Thanks!

**Comment by AtmanActive** [comment]
Working flawlessly here.
Running the editor on windows, FireFox v106.0.1, and running the surface on raspbian, Chromium v101.0.4951.57.
Thanks!
