### ISSUE TITLE
[Feature] Ad-hoc hide the marquee

### ISSUE THREAD

**Issue by AtmanActive** [jean-emmanuel/open-stage-control#797]
Hi,

I'm using Open Stage Control daily and I'm very much enjoying it.

Here are a few feature suggestions with the aim of making it even better.

It would be super-nice to have a keyboard shortcut to temporarily hide the selection rectangle (marquee) and it's handles.
Many, many times while I'm in design mode I find myself deselecting the widget(s) just to be able to see the design properly, and then need to select it/them again to continue working.
In experienced design programs this is solved by adding a dedicated keyboard shortcut that when held, and only when held (not a toggle) hides the marquee and as soon as it is let go, the marquee is visible again (if anything was selected in the first place, of course).
This keyboard shortcut should never be a toggle as that leads to confusing state where the designer can't be sure if something is selected or not. But, if it is hold-only, then, it works beautifully and speeds up the design process a lot.

Thank you for developing this awesome software!

**Comment by jean-emmanuel** [comment]
done

**Comment by jean-emmanuel** [comment]
This can be tested in v1.19.0-beta with the "h" key.

**Comment by AtmanActive** [comment]
Working flawlessly!
Fantastic.
Kudos and thanks for this.
