### ISSUE TITLE
[Bug] Script Editor - toolbar() method is not defined, graphical misconception

### ISSUE THREAD

**Issue by DMDComposer** [jean-emmanuel/open-stage-control#799]
v1.19.2
In the script editor in the client, `toolbar()` is showing as not defined, but the method still functions/works. It's just a graphical error.

![image](https://user-images.githubusercontent.com/53786232/199784362-0576d3d4-1aa8-4186-9a0b-a9fd6b0caca6.png)

Cheers,
DMDComposer

**Comment by jean-emmanuel** [comment]
It's fixed in sources already
