### ISSUE TITLE
Open-stage-control doesn't build on Arch=ARM

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#8]
From the npm-debug.log:

2 info using npm@3.8.1
3 info using node@v0.10.29
11 verbose request uri https://registry.npmjs.org/open-stage-control
12 verbose request no auth needed
13 info attempt registry request try #1 at 19:01:59
14 verbose request id e416d22ca8a50a24
15 http request GET https://registry.npmjs.org/open-stage-control
16 http 404 https://registry.npmjs.org/open-stage-control
18 silly get cb [ 404,
19 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/open-stage-control
19 silly fetchPackageMetaData     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)

I think all of these errors are to do with doing this on an ARM based system

**Comment by jean-emmanuel** [comment]
What procedure did you follow ? It seems you are trying to install the app directly through npm, which is impossible since it's not referenced on npmjs.org yet.

**Comment by ovenwerks** [comment]
On Thu, 17 Mar 2016, jean-emmanuel wrote:

> What procedure did you follow ? It seems you are trying to install the app
> directly through npm, which is impossible since it's not referenced on npmjs.org
> yet.

Oh, Ok, In the Git README.md there is a line:
Build from sources
That links to:
https://github.com/jean-emmanuel/open-stage-control/blob/master/resources/docs/build-from-sources.md
I tried to follow that.
I can see why it wouldn't work then.
Sorry to bug you about it.

Looking at the *.deb package it seems there is nothing to compile? (all 
scripts) So maybe the thing to do is find the right place to install them. 
I will fiddle...

--
Len Ovens
www.ovenwerks.net

**Comment by jean-emmanuel** [comment]
There is no proper compilation indeed, since it's more or less a web app running under electron (node+chromium), which is already precompiled for a bunch of platform including arm7.

**Comment by ovenwerks** [comment]
It is looking very good. I am able to use chrome in android and it looks 
like I can make my whole channel fit. Just need to get the server side to 
work on the RPi. I found the meter switch on the fader (thank you). I just 
have to find out what the path is :)

The coloured LEDs are nice, but due to space concerns, I would really like 
the push buttons to have variable colours like the LED. If you wanted to 
have a LED inside the push button that would be fine... but just changing 
the on colour would be nice. I am using them for rec (red), select (hard 
white), solo/pfl/afl (Green), mute (Yellow) and F (function keys standard 
colours are fine there).

Since the last push it now seems to at least be able to load a file made 
with chrome... maybe it could do that before but I had no file to try.

Copy/paste: Paste has two options: keep same IDs, or use default 
ids/labels. I would like a third option :)  Keep the same IDs, but 
increment the the last digit(s) if it is a number, or add a number if 
there is not one. So if I have a panel (Ch1), with Pan1, Fade1, Mute1, and 
Solo1 in it... and paste I wuld get a panel Ch2, with Pan2, Fade2, Mute2 
and Solo2 in it unless there is already a 2, then use 3. Or better have a 
paste n option.

I don't know how important this is if the screen is being made on the fly 
by SW though. That is what I intend to do.

Do be aware that I am saying these crazy things because they fit my use 
and may not be the best ideas for everyone.

Thankyou for the time you have put into this.


--
Len Ovens
www.ovenwerks.net

**Comment by jean-emmanuel** [comment]
These are reasonable requests, don't worry.

- The path for updating the fader's meter is `/widget's_path/meter`
- I'm not satisfied with the led widget, it hasn't evolved since its creation for testing purposes
- I agree, let's have a color property for more widgets
- Smart pasting would be nice, i'll investigate that

You're welcome !

**Comment by jean-emmanuel** [comment]
ok it seems to work fine, though i haven't added a 'paste N' option yet.

**Comment by jean-emmanuel** [comment]
I'm closing this since the original issue is not discussed anymore.

**Comment by ovenwerks** [comment]
Hello, installed 64bit version on my i5 machine.

running:
  open-stage-control
from the commandline works ok.
running:
  open-stage-control -n 8100 -l mix03.js
from CLI gives:
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'acorn'
     at Function.Module._resolveFilename (module.js:338:15)

And then a pile more places in the same script.

I had thought acorn had been renamed to Electron and wonder if that is 
what should be looked for. Neither acorn or electron seem to be in the 
path. But that may be meaningless anyway it does work in some cases.

Feeling dazed and confused :)  Actually I am wondering if you happen to 
have acorn installed as well as electron.

--
Len Ovens
www.ovenwerks.net

**Comment by ovenwerks** [comment]
Arch arm has not been added yet to electron_package... there is a PR for 
it though. I may try building my once I get intel64 to work all the way.

Nice things to have...
"scale": "true"/"false" For fader and maybe knob
I like the scale for long faders, but it is causing trouble for me on 
short ones.
Ability to use faders for pan/bal (marker starts from 0 not left)

Of course changing scales, break points, log/lin on the fly would be 
wonderful :) but I am figuring ways around that as I go.

I am finding the "LED" on push is too small to be caught on a quick eye 
scan of the window. That is, it looks nice, but in use one has to look at 
each button to see if it is on or not. For something like Solo one wants 
to see it right away (record or mute too).

Hey wait a minute, push should 
not send 1/0 to itself. (toggle should) push should expect the "host" to 
turn the indication on or off. If the host does not, that is ok because 
the push is momentary anyway. The problem is this, I press record, the daw 
sends a 1 back to the same push, maybe before I have even lifted my 
finger/mouse, I release the push... the indicator goes out even though 
record for that channel is still active. I guess that one is a bug.

Toggle: This should be considered something that does not expect a DAW 
reply (for whatever reason). However, if the daw does send a 1 or a 0 the 
toggle should be hard set on or off accordingly. (someone changed 
something using the DAWs GUI) This works correctly right now.

After all that I may change my push buttons to toggle buttons. I have to 
decide if I need key release or not.

Also, the OSC spec allows for just sending the path with no parameter. 
Ardour for one uses this quite a lot (/ardour/transport_stop for example) 
and considers the message invalid if a parameter is added. I have to try a 
value of false. I don't know if that just doesn't send the value or the 
whole message.

I was going to say I could not figure out how to send OSC data to open 
stage control, but did get it working after all. It is just headless 
doesn't work for me.

--
Len Ovens
www.ovenwerks.net

**Comment by jean-emmanuel** [comment]
In the future, please open new issues instead of adding comments here :)

> Error: Cannot find module 'acorn'
It seems to be related to the headless mode, i'll investigate

> "scale": "true"/"false" For fader and maybe knob

This can already be done by adding `--color-pips:transparent` to the `css` property.

> Ability to use faders for pan/bal (marker starts from 0 not left)

Starting value can be set via osc, it seems enough to me since it's the only reliable way to ensure your widget will be the same as the controlled value. Tthe gauge can be hidden by adding  `--color-gauge:transparent;` to the `css` property.

> I am finding the "LED" on push is too small to be caught on a quick eye [...]

You should use the toggle button instead I think, since the push are not supposed to be stuck in `on` position.

> Hey wait a minute, push should not send 1/0 to itself.

This is a rather classical behavior actually (note on & note off on release), note that you can disable the `off` value send by setting it to false.

>Toggle: This should be considered something that does not expect a DAW reply (for whatever reason). However, if the daw does send a 1 or a 0 the toggle should be hard set on or off accordingly. 

This is actually how the toggles behaves already. 

> Also, the OSC spec allows for just sending the path with no parameter. Ardour for one uses this quite a lot (/ardour/transport_stop for example) and considers the message invalid if a parameter is added. I have to try a value of false. I don't know if that just doesn't send the value or the whole message. 

Indeed, it's not possible yet, but it will be, soon.

**Comment by jean-emmanuel** [comment]
> Error: Cannot find module 'acorn'

Fixed (ed6d54b41aefc4c0668c105bc707c767fc045f46)

> Also, the OSC spec allows for just sending the path with no parameter. Ardour for one uses this quite a lot (/ardour/transport_stop for example) and considers the message invalid if a parameter is added. I have to try a value of false. I don't know if that just doesn't send the value or the whole message. 

Fixed (abdec110945c36bd59069d6a7af4992087033e40)
