### ISSUE TITLE
Visual format error in iOS

### ISSUE THREAD

**Issue by wargreen** [jean-emmanuel/open-stage-control#80]
Hi,

On my session (https://github.com/wargreen/ardour-control), we got this error in chrome for OS and safari, but not in my android's chromium or electron's chrome.
`Visual format error in strip_btns_3.layout: undefined is not an object(evaluating't.hashCode') (line66)`

thanks

**Comment by jean-emmanuel** [comment]
The layout solver library was updated, this should be fixed now.

**Comment by jean-emmanuel** [comment]
Fixed in v0.19.4
