### ISSUE TITLE
[Feature] Autostart minimized

### ISSUE THREAD

**Issue by AtmanActive** [jean-emmanuel/open-stage-control#800]
Hi,

Thank you for developing this awesome software!

I like it so much that I have it added to my app-launcher to run it at all times on my windows. OSC launcher's Autostart option is great for this. But I'm lacking a way to have it minimized when launching. Yes, I know, it is just one more click to minimize it when it starts, but these add up during the days and months and years and inevitably lead to frustration.

So, I would kindly request for one more launcher-UI-option right next to Autostart which would be Autominimize or similar.
When both are enabled, OSC's launcher would auto-start the server engine and auto-minimize the launcher window upon startup.

Thanks!

**Comment by jean-emmanuel** [comment]
Done (might need some tweaking as I can't test it on Mac)

**Comment by AtmanActive** [comment]
Works great on windows.

Thank you!
