### ISSUE TITLE
[Feature] fall-back Fragment file

### ISSUE THREAD

**Issue by ThrashJazzAssassin** [jean-emmanuel/open-stage-control#802]
I have a fragment that gets its filename from a variable `@{fx/@{parent.variables.n}/name}.json`, it works great, but if the file does not exist, the fragment remains blank and a 'Fragment file not found' error appears in the console. Please implement a field that can direct the fragment to a fall-back fragment file when this happens.

Thank you.

**Comment by jean-emmanuel** [comment]
Done
