### ISSUE TITLE
[Feature] Add package-lock.json to repo

### ISSUE THREAD

**Issue by lilyinstarlight** [jean-emmanuel/open-stage-control#805]
I'm not sure if there is a specific reason it is excluded, but having a package-lock.json would help downstream packagers by providing the dependency versions that releases are built with and allow our tooling to use that for fetching dependencies

Currently, we're generating our own package-lock.json when updates occur and committing it to nixpkgs (https://github.com/NixOS/nixpkgs/blob/fd538cf515ea2243f9b9c018ba0e4ce01e83a449/pkgs/applications/audio/open-stage-control/package-lock.json), but we would love to avoid doing this if it can be added directly to this repo

**Comment by lilyinstarlight** [comment]
Awesome, thank you so much!

I'll close this issue and will begin using the bundled package-lock.json when packaging new releases :)

**Comment by lilyinstarlight** [comment]
Hi @jean-emmanuel! It looks like the lockfile has started to lag behind the released version numbers and the dependencies releases were actually built with:

https://github.com/jean-emmanuel/open-stage-control/blob/403a1d55781b00f68d742b5b94152a0f60a98925/package-lock.json#L2-L3

Is the lockfile not being updated intentional, or was it just missed the last two releases?

Thank you again!

**Comment by jean-emmanuel** [comment]
Actually only the version number for open-stage-control is wrong, the dependencies' versions are correct. Funnily, this provides an insight on when dependencies were last updated, but also yes I didn't think of updating o-s-c version in that file :)

**Comment by lilyinstarlight** [comment]
Ah, good to know! I was wondering, but that makes sense

Thanks again for adding it :)
