### ISSUE TITLE
App not accessible on local network when using ports other than 8080

### ISSUE THREAD

**Issue by harryhjsh** [jean-emmanuel/open-stage-control#806]
Running from electron on 1.21.0, if I specify a port as a command line argument or in the GUI, the app isn't accessible from any other device (using the appropriate local IP for the host machine). 

If I don't specify a port, or explicitly specify 8080, everything works as expected.

Any ideas?

Thanks!

**Comment by jean-emmanuel** [comment]
What port did you try exactly ? Are you referring to the `port` option and not the `osc-port` option ?

**Comment by harryhjsh** [comment]
I tried as many as I could think of: 8090, 8081, 9000, 15000, etc.

Yep, definitely `port` rather than `osc-port`. 

It seems to be fine when running with `node index.js --port 8081` inside `resources/app`.

I'm running Windows 11 and because of a misconfigured security rule, I have to run open-stage-control.exe from a terminal rather than launching it directly. Could this be affecting it? Potentially some IPC-related issue?

**Comment by harryhjsh** [comment]
Just realised the last sentence of that comment doesn't make much sense - I'll clarify: 

Running `open-stage-control.exe` brings up the GUI. Pressing the start button with a port set to anything other than 8080 doesn't result in the app being accessible on the local network.

Running `open-stage-control.exe --no-gui --port 8081` doesn't result in the app being accessible on the local network.

Running `node index.js --port 8081` in `resources/app` *does* result in the app being accessible on the local network on port 8081. 


I've just tried on a Windows 10 machine and all of the above things work as intended, so this is probably a Windows 11 thing

**Comment by harryhjsh** [comment]
Don't worry - firewall configuration issue after upgrading to Windows 11. I was mislead by the fact that it *does* work on 8080, which it seems like might have been a rule that was pre-configured. Thanks!

**Comment by jean-emmanuel** [comment]
Glad you sorted it out !

Le 08/12/2022 à 12:12, harryhjsh a écrit :
