### ISSUE TITLE
[Bug] Lien mort

### ISSUE THREAD

**Issue by nlebellier** [jean-emmanuel/open-stage-control#808]
Bonsoir,

Juste pour signaler un lien mort

https://openstagecontrol.ammd.net/docs/getting-started/running-from-sources/

![image](https://user-images.githubusercontent.com/4880966/209984153-26b303f4-3b14-4834-9fee-364553e13096.png)

le bon lien est https://openstagecontrol.ammd.net/docs/midi/midi-configuration/

**Comment by jean-emmanuel** [comment]
Merci c'est corrigé
