### ISSUE TITLE
[Bug] QRCode in wrong order on windows 

### ISSUE THREAD

**Issue by ameisso** [jean-emmanuel/open-stage-control#809]
On the latest version (1.22.0) the servers IP addresses are displayed in the wrong order and in my case, localHost is displayed last. 

Thus, the QRCode leds to "127.0.0.1:8080". 

Also, in the same case I have two networks connected (WiFi and RJ45) so sometimes I don't have the correct QRCode displayed. 
Do you think that the menu items can show QRCodes for all adresses ? 

Best

**Comment by jean-emmanuel** [comment]
Thanks for the report, I'd rather fix the the address order because a qr code for localhost doesn't make sense.

**Comment by jean-emmanuel** [comment]
I missed the rj45/wifi point, I'll will try to print both in that case.

**Comment by jean-emmanuel** [comment]
Fixed in v1.24.0
