### ISSUE TITLE
Use generic font family sans-serif as fallback

### ISSUE THREAD

**Issue by danielappelt** [jean-emmanuel/open-stage-control#81]
With the current CSS, the web browser will generally fall back to using a _serif_ font if Roboto is not found on the system:

https://github.com/jean-emmanuel/open-stage-control/blob/d807032ace34fadbd9f6ec35286a96324ba7ce0f/src/browser/scss/style.scss#L49

It might be a good idea to provide _sans-serif_ as a fallback as it will look much better. Furthermore, there is still an older font-family definition some lines up in the CSS.

**Comment by jean-emmanuel** [comment]
The font file is provided with the app (https://github.com/jean-emmanuel/open-stage-control/tree/master/app/browser/fonts) so this should not be a problem if the browser supports the woff2 font format. Still, it's a good thing to do, thanks for the feedback.

**Comment by danielappelt** [comment]
Thank you! I noticed the rendering problem in the launcher the first time I started v0.19.0. Installing Roboto font system wide solved the problem.

So, I suppose Roboto needs to be also loaded in here instead of Droid Sans:

https://github.com/jean-emmanuel/open-stage-control/blob/03e8ec80201b46b3d1cfa8a6691fe4c6daa57f8d/app/main/launcher/index.html#L13

**Comment by jean-emmanuel** [comment]
Indeed nice catch !
