### ISSUE TITLE
Callback after activating a TAB

### ISSUE THREAD

**Issue by LX222** [jean-emmanuel/open-stage-control#810]
Hi dear devs,
is there a possibility to automatically send a MIDI CC when switching Tabs?

I tried to copy the OSC-Panel data in the inspector from a button to the "Tab-element" but it seems that it is not triggered.
I also tried out with scripting , but no success :(

KindRegards,
Alex

**Comment by jean-emmanuel** [comment]
Hi, it's already possible but it's the tab's parent that send the message, not the tab itself. https://openstagecontrol.discourse.group/t/midi-cc-via-tabs/1074
