### ISSUE TITLE
[Bug] trouble using eq widget

### ISSUE THREAD

**Issue by patricecolet** [jean-emmanuel/open-stage-control#814]
I've found an inconsistence in OpenStageControl documentation, the web-audio documention mentions "peaking" filter type, and not "peak".

https://webaudio.github.io/web-audio-api/#BiquadFilterNode

**Comment by jean-emmanuel** [comment]
You closed the issue, did you manage to make it work ?

**Comment by jean-emmanuel** [comment]
No problem, have fun with o-s-c !

Le 05/03/2023 à 21:56, patrice colet a écrit :
