### ISSUE TITLE
[Bug] Prevent Sleep not working

### ISSUE THREAD

**Issue by mr-plaid** [jean-emmanuel/open-stage-control#817]
Hello!  I've been playing around with the "prevent sleep" option when using a mobile device, but sadly it does not seem to work.  

I am trying this using Chrome on a Samsung Galaxy Tab S7.  I tried using several different sessions, including a fresh blank session, and still no success.  I am using O-S-C v1.23.0

I did some experimenting/investigating, and I tested the NoSleep.js live demo using the same setup, and it worked correctly.  Though after looking through the NoSleep.js repo, it looks like it may be somewhat unmaintained at this point, and perhaps has some issues in the library itself...

Anyways, not sure if there's a simple fix for it or not. It looks like there is also a fairly straightforward [Screen Wake Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API) that is perhaps worth investigating?? 

Let me know if I can provide any more useful details.

Thanks for your investigation/consideration!

**Comment by jean-emmanuel** [comment]
Thanks for the report, I'll take a look at this when I can :)

**Comment by jean-emmanuel** [comment]
Well shame on me, it looks like I managed to break that a long time ago simply by reversing an if/else statement... it's now fixed and also takes advantage of the wake lock api when available (thanks for the pointers).
