### ISSUE TITLE
[Feature] Patchbay exclusive wiring

### ISSUE THREAD

**Issue by Ezrabox** [jean-emmanuel/open-stage-control#818]
Hello, thanks, oSc is still amazing years after years.
I would like to know if it could be possible to have an option on the patchbay for an exclusive wiring
ex :
I have a link from in_1 to out_1
If i link In_1 to out_2 the first link auto unlink

Thanks! 
Ezra

**Comment by Ezrabox** [comment]
Re, i found the exclusive who is on settings of patchbay but it looks than it's only exclusive for input and not for output

**Comment by jean-emmanuel** [comment]
in/out/both modes will be available for the exclusive property in next release

**Comment by Ezrabox** [comment]
Perfect! Merci pour ce maintien indefectible de ton super logiciel.
A bientôt.
Ezra

Le mer. 5 avr. 2023 à 23:25, jean-emmanuel ***@***.***> a
écrit :
