### ISSUE TITLE
[Feature] Long press

### ISSUE THREAD

**Issue by Ezrabox** [jean-emmanuel/open-stage-control#819]
Hello, do you think the long press option on buttons could be native in oSc or should be done by script?
I use them a lot as secutity on contrôleurs makes clear or changing a dangerous preset.
It should be great to specify how long time the button should be pressed to send the message

Thanks
Ezra

**Comment by jean-emmanuel** [comment]
Using scripting is the way to go for this specific use case, something like this with a push widget:
```js
if (value === getProp(this, 'on'))  {
  setTimeout(()=>{
    // do something
  }, 500) // after 500 ms
} else {
  clearTimeout()
}

**Comment by Ezrabox** [comment]
Thank You!

Le mer. 5 avr. 2023 à 23:28, jean-emmanuel ***@***.***> a
écrit :
