### ISSUE TITLE
raw_input() was renamed to input() in Python 3

### ISSUE THREAD

**Issue by danielappelt** [jean-emmanuel/open-stage-control#82]
The midi engine fails on my system which uses Python 3 by default: raw_input is not defined.

I guess the problem is that raw_input was renamed to input in Python 3 (https://docs.python.org/3/whatsnew/3.0.html#index-32). So, this code currently seems to be only compatible with Python 2:

https://github.com/jean-emmanuel/open-stage-control/blob/03e8ec80201b46b3d1cfa8a6691fe4c6daa57f8d/app/main/midi.py#L163

**Comment by jean-emmanuel** [comment]
This should be fixed now,

**Comment by danielappelt** [comment]
The errors are gone now! ALSA and Jack MIDI ports are created successfully on my Linux system. Still, I need to find a way to actually send MIDI messages via these ports. But this is another issue.

**Comment by jean-emmanuel** [comment]
Feel free to ask ;) http://osc.ammd.net/extras/midi/
