### ISSUE TITLE
Can't change widget's "position" (send to back/front, etc) - Error raised

### ISSUE THREAD

**Issue by MagnusReichel** [jean-emmanuel/open-stage-control#822]
When right clicking a widget in the editor and selecting any option in the menu "Position", I get this error in the console:

`TypeError: editor.handleKeyboard is not a function
    at action (src/client/editor/context-menu.js:205:31)
    at e.preventDefault (src/client/ui/context-menu.js:39:25)`

The widget does not change it's position.

- Latest OSC version
- Error appeared too in approximately 5 versions below (As far as I noticed)
- does not correlate with any of my client-options
- in both built-in and browser editor
- MacOS 12.6.3

**Comment by jean-emmanuel** [comment]
Thanks for the report, fixed in sources.

**Comment by jean-emmanuel** [comment]
Fixed in v1.24.2 (currently deploying)
