### ISSUE TITLE
[Feature] Serial control

### ISSUE THREAD

**Issue by JonnyTech** [jean-emmanuel/open-stage-control#823]
I have some devices that require serial control - stuff like Arduino's and other custom boards. Currently using PuTTY or other terminal emulators to send strings - even from terminal:

```
stty -F /dev/ttyS0 9600 -parity cs8 -cstopb
echo 'hello' > /dev/ttyS0
```

Does Open Stage Control support sending / receiving serial (or even serial-over-IP)?

If not, can this be considered a feature request please?

**Comment by jean-emmanuel** [comment]
Serial communication support is considered out the app's scope and won't be implemented, but it should be possible to make it work using a [custom module](https://openstagecontrol.ammd.net/docs/custom-module/custom-module/) and node's [serialport](https://www.npmjs.com/package/serialport). You'd need to install `node` and `npm` on your system and run `npm install serialport` in the custom module's folder, then the module would look like this
```js
const SerialPort = requireNative('serialport')

//  do things with that module

module.exports = {
  oscInFilter: (data)=>{
    // maybe do something with incoming osc messages
    return data
  },
  oscOutFilter: (data)=>{
    // maybe do something with outgoing osc messages
    return data
  },
  unload: ()=>{
    // close/destroy serialport (if editing the custom module while running)
  }
}
```
