### ISSUE TITLE
Switch in different tabs[Feature] 

### ISSUE THREAD

**Issue by Ezrabox** [jean-emmanuel/open-stage-control#825]
I have switches in differents tabs with differents nice names and vales, but to make the feedback info running well i have to make a copie of each switch nice name and message in a ghost switch. Do you know why and if there is an other way ar if it is a bug on an enhance feature? 
Thanks

**Comment by jean-emmanuel** [comment]
I don't understand the issue, please try with more context (or in french maybe).
