### ISSUE TITLE
IOS/ Android  [Feature] 

### ISSUE THREAD

**Issue by Reaper10** [jean-emmanuel/open-stage-control#828]
can you make a native IOS/ Android?

**Comment by jean-emmanuel** [comment]
Nope (https://openstagecontrol.discourse.group/t/mobile-app-implementation/3096)

**Comment by Reaper10** [comment]
> Nope (https://openstagecontrol.discourse.group/t/mobile-app-implementation/3096)

could someone do for you

**Comment by jean-emmanuel** [comment]
Sorry if my previous reply sounded a bit rude, I should have taken more time to write it. I believe I've made my point clear regarding this matter in the thread I've linked and I'm afraid I don't have much to add except that of course people are free to develop their own mobile port of open stage control as long as they comply with the terms of the GNU/GPLv3 license.
