### ISSUE TITLE
Touch events not firing on mobile [Bug]

### ISSUE THREAD

**Issue by smithkyle** [jean-emmanuel/open-stage-control#829]
Please provide as much contextual informations as possible:

- Open Stage Control version (or commit if built from sources): 1.25.1
- Operating system: macos 12.4 / ios 16.5.1
- Open Stage Control options: none
- Client type (built-in or external browser) and version: built-in (macos) / safari (ios)
- Session file (can be uploaded after adding the .txt extension): attached
- Custom module: none
- Server logs (from the terminal or the launcher's console): n/a
- Client logs (hit F12 in chromium/chrome to open the console): all events below ONLY displayed when interacting with pad via the built-in client
```
{"type":"start"}
{"type":"stop"}
{"type":"start"}
{"type":"stop"}
```
- Screenshot: see attached
-->
[testXY.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/11863053/testXY.json.txt)
![osc](https://github.com/jean-emmanuel/open-stage-control/assets/328670/ad0a9030-ee51-4f02-a894-e29f51236605)

**Comment by smithkyle** [comment]
Doesn't appear to be confined to mobile - I just tried in safari and chrome on macos, and neither triggered the ontouch function (I believe safari isn't supported, but chrome is).

**Comment by jean-emmanuel** [comment]
Everything appears to behave as expected here, `onTouch` only exposes the start and end events [as documented](https://openstagecontrol.ammd.net/docs/widgets/scripting/#ontouch) and the pad itself reacts normally to drag events.

**Comment by smithkyle** [comment]
I made a video of me setting up a fresh session, and then using two built-in client windows to observe the behavior of the onValue function of a button, and the onValue / onTouch functions of an XY pad. When clicking the button, the onValue function updates both instances of the client. When clicking the XY pad, the onTouch function ONLY runs for the client which was clicked, but as I drag around on the pad, you can see that the onValue function updates BOTH clients.

Should the onTouch function only update the client that was interacted with? I am also including the session that was created during the video.

[https://www.youtube.com/watch?v=T-d7I7lK5kQ](example video)
[test2.json.txt](https://github.com/jean-emmanuel/open-stage-control/files/11875029/test2.json.txt)

**Comment by jean-emmanuel** [comment]
Yes, `onTouch` should only run when the widget is physically interacted with. On the other hand, since the value is passed sent to other clients for widgets to synchronize it triggers `onValue`*.  The behavior you describe is correct. 

*Note that unless `onValue` is triggered by a direct interaction the `send()` function has no effect to prevent sending duplicate messages.

**Comment by smithkyle** [comment]
Thanks for your reply. If set() [not send()] is being called in the onTouch function, shouldn’t the widget being set() synchronize the new value to all clients? The behavior that I am seeing is that only the client that received the touch event updates the widget targeted by set() with the new value - the other clients are not synchronizing the widget being set() via the onTouch event with the new value.Thanks again.KyleOn Jun 26, 2023, at 10:52 PM, jean-emmanuel ***@***.***> wrote:﻿
Yes, onTouch should only run when the widget is physically interacted with. On the other hand, since the value is passed sent to other clients for widgets to synchronize it triggers onValue*.  The behavior you describe is correct.
*Note that unless onValue is triggered by a direct interaction the send() function has no effect to prevent sending duplicate messages.

**Comment by jean-emmanuel** [comment]
If you change the type of the text widget to `input` it will work as you expect, there's currently a blind spot here for widgets that don't send any message when their value changes (it's not related to the explicit use of `send()`)

**Comment by smithkyle** [comment]
Sorry for the delay in responding. Switching the ```variable``` widget to an ```input``` widget worked. After fussing with this, I realized I could actually just use ```setVar``` and ```getVar``` to much easier avail, which worked better.

**Comment by jean-emmanuel** [comment]
Ok cool ! As of v1.25.2, variable, text and led widgets will have their value synced accross clients.
