### ISSUE TITLE
Debugging is not as easy as expected

### ISSUE THREAD

**Issue by danielappelt** [jean-emmanuel/open-stage-control#83]
I have a hard time debugging the application.

In the front end, breakpoints that I create via the developer tools (F12) do not work as expected.

Is there a specific reason that this transformation needs to be applied?:
https://github.com/jean-emmanuel/open-stage-control/blob/5e6fb695932cf4fc61b3a53ce78b13b1974561f9/scripts/build-js.js#L11

Removing it resolves the developer tools problem outlined above.

Then, I still have to find out how to debug the server backend. For example, what needs to be done in order to see the log messages created in app/main/callbacks.js?

**Comment by jean-emmanuel** [comment]
Le 19/08/2017 à 13:57, Daniel Appelt a écrit :
>
> I have a hard time debugging the application.
>
> In the front end, breakpoints that I create via the developer tools 
> (F12) do not work as expected.
>
> Is there a specific reason that this transformation needs to be applied?:
> https://github.com/jean-emmanuel/open-stage-control/blob/5e6fb695932cf4fc61b3a53ce78b13b1974561f9/scripts/build-js.js#L11
>
> Removing it resolves the developer tools problem outlined above.
>

This is a minification transform, only used to reduce the file size, you 
can bypass it;

> Then, I still have to find out how to debug the server backend. For 
> example, what needs to be done in order to see the log messages 
> created in app/main/callbacks.js?
>

The server should output directly to your console (must be run from a 
terminal then).

**Comment by jean-emmanuel** [comment]
Le 19/08/2017 à 15:32, Jean-Emmanuel a écrit :
>
> The server should output directly to your console (must be run from a 
> terminal then).
>
>

If you need to print log from the midi python module (midi.py), you'll 
have to use the following function :

ipcSend('log', MSG)

**Comment by jean-emmanuel** [comment]
Since 1874d62, scripts are minified only when building for production (running `npm run build` or `npm run build-js -- --prod`). The minification process is also much longer than before (saving more than 1MB !).

**Comment by danielappelt** [comment]
Cool :+1: Exactly what I was hoping for!
