### ISSUE TITLE
I am unable to open the application - Java script error in main application 

### ISSUE THREAD

**Issue by kheller13** [jean-emmanuel/open-stage-control#830]
![Screenshot 2023-07-27 105710](https://github.com/jean-emmanuel/open-stage-control/assets/140745671/3461c680-04b0-4e94-904a-dd7053e889ee)
HI I am using a windows 11 home  - when I extract the files and try and open the application it gives me this java script error  that I attached in a screen shot

**Comment by jean-emmanuel** [comment]
What does the file `C:\...\open-stage-control_1.25.2_win32-x64\resources\app\server\open-stage-control.js` exist ? Otherwise the archive might have been unproperly downloaded or extracted.
