### ISSUE TITLE
[Bug] Code Editor does not recognize the ** operator

### ISSUE THREAD

**Issue by chnoma** [jean-emmanuel/open-stage-control#831]
- Open Stage Control version v1.25.3
- EndeavourOS
- Default Options
- Built-in Client
- Session file N/A

There's really not much to say. I'm using the exponentiation operator (**) and it seems that the code editor doesn't like it.

Steps to reproduce:
  - Create a new session
  - Add a canvas widget (or any other scriptable widget)
  - Add `let x = 2**2` into any script field
  - See editor warning

![image](https://github.com/jean-emmanuel/open-stage-control/assets/85920821/050311fe-0205-49db-a032-064030333343)

The code seems to run fine

**Comment by jean-emmanuel** [comment]
Thanks for the report, it's now fixed in sources.

**Comment by chnoma** [comment]
Thanks!
