### ISSUE TITLE
1.22 to 1.25 : "step not defined" en tentant d'ouvrir une session contenant des knobs

### ISSUE THREAD

**Issue by Sakamacheee** [jean-emmanuel/open-stage-control#835]
Bonjour,

Après une très longue pause, je reviens vers OSC... et passe de la 1.22 à la 1.25. Avec cette dernière, j'ai ce message d'erreur dans la console, avec impossibilité d'ouvrir la session contenant des knobs  ("step is not defined") : 

slider.js:244 Uncaught ReferenceError: step is not defined
    at t.setSteps (slider.js:244)
    at new Slider (slider.js:83)
    at new t (knob.js:63)
    at Parser.parse (parser.js:77)
    at new Panel (panel.js:239)
    at new Tab (tab.js:36)
    at Parser.parse (parser.js:77)
    at new Panel (panel.js:198)
    at Parser.parse (parser.js:77)
    at new Panel (panel.js:239)

Par curiosité, j'ai regardé dans le slider.js, et à la ligne 244, il y a 
             } else if (Array.isArray(steps) && step.every(x=>typeof x === 'number')) {

Est-ce que le problème vient de step.every, qui devrait être steps.every ?...  

Pure curiosité, je n'ai pas les compétences pour décoder tout ça.

Merci

**Comment by jean-emmanuel** [comment]
En effet ce que tu pointes est une erreur de ma part, je vais sortir une version patchée pour la corriger. Merci !

**Comment by jean-emmanuel** [comment]
Ça devrait êtré reglé dans la v1.25.6

**Comment by Sakamacheee** [comment]
C'est en effet réglé, merci beaucoup !
