### ISSUE TITLE
[Bug] Installation de python-rtmidi sous Linux.

### ISSUE THREAD

**Issue by nlebellier** [jean-emmanuel/open-stage-control#838]
Bonsoir Jean-Emmanuel,

Juste pour indiquer que la procédure (indiqué https://openstagecontrol.ammd.net/docs/midi/midi-configuration/) pour installer sous Linux le package python-rtmidi se résume désormais à ceci (du moins sous Ubuntu 23.10) :

```
sudo apt install python3
sudo apt install python3-pip
sudo apt python3-rtmidi

``` 

Voilà voilà

Nicolas

**Comment by jean-emmanuel** [comment]
Merci pour l'info!
