### ISSUE TITLE
Touch not working in lobby

### ISSUE THREAD

**Issue by frboyer** [jean-emmanuel/open-stage-control#84]
Touch is not working in lobby, that is we can click on an item with mouse but not with touch screen, which makes it unusable on a tablet.  The problem was introduced in commit d807032.  In "callbacks.js", I removed the "touchstart" from the three "on('mousedown touchstart' ...", and it works again.

**Comment by jean-emmanuel** [comment]
Sorry for that, I'm releasing a fixed release (v0.19.2) right now, thanks for the hint !

**Comment by frboyer** [comment]
Wow, that was fast!  Thanks.
