### ISSUE TITLE
[BUG] with node, clone is updated but not target widget

### ISSUE THREAD

**Issue by patricecolet** [jean-emmanuel/open-stage-control#841]
- Open Stage Control version 1.25.2
- macos monterey
- Open Stage Control options:  'node open-stage-control --port 5000'
- Client type firefox 122.0.1
- 
[testDynamicPresetAdd.json](https://github.com/jean-emmanuel/open-stage-control/files/14256795/testDynamicPresetAdd.json)

the bug is in the title

**Comment by jean-emmanuel** [comment]
Thanks, it's now fixed in sources, to be included in next release.
