### ISSUE TITLE
Bro, how to even friggin display a friggin boolen, friggityfruggfrogg, man?

### ISSUE THREAD

**Issue by Bracket-H** [jean-emmanuel/open-stage-control#844]
Got a damn message schema that returns either T or F (hot damn I'm mad at this point)
Via 
```
/automate/slot[0,15]/active T
/automate/slot[0,15]/active F
```
How the hell do I indicate this with an LED for example?

/automate/slot0/active
is the LEDs OSC address

A button has the message too, to send the message "in" to the synth
How the funk do I get the return value to fokkin show, m8?!?!?!??!?!>!>!>!>!?!?!?!?

I read the docs.
I can even show you a screenshot.

![image](https://github.com/jean-emmanuel/open-stage-control/assets/93729441/9247d89b-3a1d-41af-9476-bdbc06ba5249)

There, this is it, right?

Guess how much this means to me? 
Nothing. 

preArgs?
```
*|
array
```

\* or array?!

What? Huh? Asterisk? Anything? But the anything is not an array? Because the array is the other choice othe than asterisk?
Am I supposed to put a literal asterisk in the pre args? What? Who? When? Santa Claus?

It says:
`Incoming messages must match these to affect by the widget.`
And I want incoming messages to must match these to affect by the widget, I really do want that, I very much want it, I crave it extremely muchly.
I want to must match these to affect by the widget.

But how?

The example/tutorial shows a slider and a button, I already know how to SEND data and manipulate something. 
But how to must match these to affect by the widget?

I did click on `See [OSC 1.0 specification](http://opensoundcontrol.org/) for existing typetags`

On typeTags 
But that link does not show the specification, that's found at another link at the bottom of that page.
Anyway, it's a lot of blahdedeebloob and I just want to know..........................

How to ...well you should get what I want by now.
I'm so tired, dude. I looked on the forum, nothing, someone shared '
![image](https://github.com/jean-emmanuel/open-stage-control/assets/93729441/f9974150-593d-4102-9d68-3ed9af038601)
patches' and it was this

My brother in christ, I appreciate the effort but what the fok man.

LED, on or off, if fukken slot is active or not.
HhhhhhhhhhhhhhhhhhHHhhHhhHHhhHhhHHhHHhhHhhHHhhow?

Do I need to write a 'custom module' or something?

This is the sauerkraut of software.
or maybe I'm just extremely ultra dense like some sort of black hole of dumbness, that's an option too.

But hot diggity hippity hoppity bro, just make such simple tasks clear, pllllllleeeaaase.
I'm s'il vous pleading here.

What to do for some clarity?

**Comment by jean-emmanuel** [comment]
« How to not get help » by Bracket-H...

The led widget does not accept boolean. The relevant part of the documentation for that is the `value` property (https://openstagecontrol.ammd.net/docs/widgets/properties-reference/#led_value)

You could use a script widget to receive the boolean (it accepts anything) and set the led's value accordingly:
```js
// script.onValue
set('led_id', value ? 1 : 0)
```

`preArgs` can be of any type (hence the asterix), multiple preArgs can be set using an array.

`typeTags` only affect outgoing messsages, they are irrelevant here.

----

Please use the forums for anything other than bug reports. Also please keep in mind this project is developped and supported on my spare time, it comes without any warranty whatsoever. If open stage control doesn't do the job for you, there are well documented alternative out there.

**Comment by nlebellier** [comment]
May i invite you @Bracket-H to have a little walk instead writing such a comment.

The energy you took to write these poor lines should have be more usefull to read the doc to get some infos about the o-s-c.
Again as says @jean-emmanuel, nobody forces you to use the software. Some people manage to get good interfaces with this piece of software and the forum is the place to post your questions.

Have a nice day and don't forget to take a pause :-)
