### ISSUE TITLE
[Feature] current nodejs compatibility

### ISSUE THREAD

**Issue by jpnielsen** [jean-emmanuel/open-stage-control#845]
```
~/open-stage-control $ node -v
v21.7.3
```

For security reasons, I'm trying to keep my installed software uptodate - I hope you can find time and prioritize to make open-stage-control build and run with a current nodejs ?

Best regards
JP Nielsen
___________________________________________
[2024-04-11T23_29_32_995Z-debug-0.log](https://github.com/jean-emmanuel/open-stage-control/files/14952428/2024-04-11T23_29_32_995Z-debug-0.log)

**Comment by jean-emmanuel** [comment]
Thanks for bringing this to my attention. Building now works up to v20, v21 is not supported yet by one of the build dependencies.

**Comment by nlebellier** [comment]
Cool @jean-emmanuel !
