### ISSUE TITLE
[Bug] QR code doesn't update after switching Wifi network

### ISSUE THREAD

**Issue by jamshark70** [jean-emmanuel/open-stage-control#846]
- Open Stage Control version: 1.26.2
- Operating system: Linux
- Open Stage Control options: just "send to" IP and "load"
- Client type (built-in or external browser) and version: Firefox
- Session file (can be uploaded after adding the .txt extension): Doesn't matter

1. Open the launcher, and start the server.
2. Realize that you're on the wrong Wifi router, so... stop the server.
3. Switch the computer's Wifi setting to the proper router.
4. Restart the Open Stage server.
5. Now the console shows the correct IP address in text.
6. Using a mobile browser, scan the QR code. It points to the *old* address from step 1.
7. Quit everything (including launcher).
8. Reopen launcher, restart Open Stage server, scan the code, all is fine.

At stage 4-5, Open Stage recognizes that the IP address has changed, but doesn't update the QR code.

**Comment by jean-emmanuel** [comment]
Thanks for reporting, dev time is tight these days but I'll get to it eventually.

**Comment by jean-emmanuel** [comment]
This should be fixed in next release.

**Comment by jamshark70** [comment]
Thanks!
