### ISSUE TITLE
[Bug] Issue sending OSC with multiple arguments

### ISSUE THREAD

**Issue by bootsie123** [jean-emmanuel/open-stage-control#849]
Hi! I seem to be having an issue when trying to send OSC commands with multiple arguments. More specifically, when using the integer value type, it seems to convert the given integer into its ASCII representation.

Any ideas? Thanks!

---
### **Debug Info**
Open Stage Control Version: `v1.26.2`
Operating System: `Windows 10`
Open Stage Control Options: ![image](https://github.com/jean-emmanuel/open-stage-control/assets/22622963/27bd612c-e2f5-4c2d-83af-9180be933c48)

Custom Module Snip-it:
```javascript
send(
  ip,
  oscPort,
  "/14." + timecode.selectedSlot,
  { type: "s", value: "play" },
  { type: "i", value: 1 }
);
```

Server Logs:
```
(DEBUG, OSC) Out:  {
  address: '/14.1',
  args: [ { type: 's', value: 'play' }, { type: 'i', value: 1 } ]
} To: 127.0.0.1:9003
```
Recieved OSC Input (grandMA3 onPC):
```
OSCReceiver : OSCInput: /14.1   ,si play
```

When `i` is changed to `100`:
```
OSCReceiver : OSCInput: /14.1   ,si play   d
```

**Comment by jean-emmanuel** [comment]
Looks like a bug on the receiving end, or maybe it's simply not printing integers properly. I confirm open stage control sends what it's supposed to send here.

**Comment by bootsie123** [comment]
Gotcha. Thanks for looking. I've used tools such as TouchOSC with MA3 and that works fine. I'll do some more investigating and troubleshooting on my end
