### ISSUE TITLE
rtMidi's noteOff() expects two arguments instead of three

### ISSUE THREAD

**Issue by danielappelt** [jean-emmanuel/open-stage-control#85]
Currently, no noteOff MIDI messages are sent because the corresponding rtMidi function expects two instead of three parameters:

https://github.com/jean-emmanuel/open-stage-control/blob/ee1d76b184ad4ad820ca76cc728e6239298cb7e7/app/main/midi.py#L148

If you enclose this statement into a try/except, an error will be reported. Possible solution:

``
m = rtmidi.MidiMessage.noteOff(args[0], args[1])
``

Furthermore, it would be helpful if such errors were not ignored silently but reported on the console.

**Comment by jean-emmanuel** [comment]
Solution adopted :)

> Furthermore, it would be helpful if such errors were not ignored silently but reported on the console.

So true, 5aef31b9eadb9877ea3796e60458c2e417f1f575 fixes it.

**Comment by danielappelt** [comment]
Thank you!
