### ISSUE TITLE
Fragment Value in onValue script

### ISSUE THREAD

**Issue by tylerGirraphic** [jean-emmanuel/open-stage-control#854]
OSC v1.27.0
Windows
send: 127.0.0.1:8080 osc-port: 8081 debug: true client-options: usePercents=1
built in client

When using a fragment and a script in the onValue to get the widget ID based on panel variable "n" the value appears to be either 1 or 0, or just 1 in some cases. Backing up to v1.26.2 and changing nothing produces proper results.

```
let X = get("actorLocX_@{parent.variables.n}")
console.log(getProp(this, "id"))
send("/test", X)
```

![image](https://github.com/user-attachments/assets/547642c1-1052-4d93-b62f-e1d46a56fa4a)

![image](https://github.com/user-attachments/assets/9b72c4f5-9487-4240-85b1-acca47b9d02e)

**Comment by jean-emmanuel** [comment]
I don't see what could cause such issue between v1.26.2 and v1.27.0, nothing was changed regarding scripting and advanced syntaxes.  Could you try making a minimal session to help reproduce the issue ? Also this
```js
let X = get("actorLocX_@{parent.variables.n}")
```
should be
```js
let X = getProp("actorLocX_" + getProp("parent", "variables").n)
```
as per the [warning in the docs](https://openstagecontrol.ammd.net/docs/widgets/scripting/).

**Comment by tylerGirraphic** [comment]
Certainty. It could just be that line of code. The widget id matches regardless, just that value when loaded into a matrix appeared to be 1, instead of whatever I actually entered into the input widget.

**Comment by tylerGirraphic** [comment]
Some of the issue could have stemmed from the widgets being faders when they were created, then I switched the type to input?
Also seemed like I had to save and reload the main file for it to take effect regardless of having the fragment opened and saving in it.

[240731_matrixFragmentTest.zip](https://github.com/user-attachments/files/16445508/240731_matrixFragmentTest.zip)

**Comment by jean-emmanuel** [comment]
I tried the session and the values sent over osc are all correct. What's not is the log message in the client console because you wrote the same thing for every widget:
``` js
console.log(get("X_1"))
```
where you should have writter
```js
console.log(get(this))
```
