### ISSUE TITLE
[Feature] Dark mode title bar for fullscreen view in Safari on iOS/iPadOS

### ISSUE THREAD

**Issue by dzisowski** [jean-emmanuel/open-stage-control#856]
When adding o-s-c to the home screen on iOS (which uses safari to open the web page), the browser controls are hidden providing more screen space. However, even with dark mode enabled, the small title bar remains white. This behavior has been consistent across iOS 17 and 18, as well as on iPadOS.

It seems that it can be solved by editing index.html to add this line in <head>

``
<meta name="theme-color" content="#000000">
``

Unfortunately, it can't be done using root widget html field. It would be great if the title bar color could be changed in root widget properties, or in some other user accessible way.   

Also I'd suggest the default color could be set to default (theme) bg color instead of being left undefined which results in white.

<details>
  <summary>Screenshots:</summary>

  <img src="https://github.com/user-attachments/assets/a824d0c2-e951-4be1-9fd0-082602a173d8" alt="IMG_2888" width="40%">
  <img src="https://github.com/user-attachments/assets/22334f58-4327-4a63-bf19-18af3414cf9d" alt="IMG_2888" width="40%">

</details>

**Comment by jean-emmanuel** [comment]
Thanks for the report ! Applying the root's `colorBg` to `theme-color` seems like a good solution, what do you think ?
