### ISSUE TITLE
[Bug] `onValue` not called when OSC message updates widget value

### ISSUE THREAD

**Issue by zax71** [jean-emmanuel/open-stage-control#860]
# General info
- **Version**: v1.27.1
- **OS**: Debian 12.8
- **Options**: Load [this custom module](https://pastes.dev/8I1ah9AUCN) although any OSC input should cause the issue. Also turn on debug to see that no message is output
- **Client type**: Mainly browser (Firefox) but the built-in client portrays the same issue
- **Session file**: https://pastes.dev/3uP654wEnY
- **Custom module**: https://pastes.dev/8I1ah9AUCN but you also need [this JSON file](https://pastes.dev/KIk4B3nh7D)
- **Logs**: 
  - [Server](https://pastes.dev/UtpNDLZbPG)
  - Client: see image
- **Screenshot**: 
![image](https://github.com/user-attachments/assets/ee436758-18bd-4059-be1c-de1678931457)

# Description
When updating the value of a widget via an OSC message in: be that the `OSC` config section or the [`@OSC{}`](https://openstagecontrol.ammd.net/docs/widgets/advanced-syntaxes/#osc-listeners-oscaddress-default-usepreargs) syntax. The widget does not call it's `onValue` event.

# Conclusion
Anything would be appreciated, I am running a show that requires this in a weeks time, so even a workaround would be greatly appreciated.

**Comment by zax71** [comment]
Ah, I see. I'll write it in to my existing custom module then.

**Comment by jean-emmanuel** [comment]
No problem, good luck with your show !
