### ISSUE TITLE
No transparent button since V.19

### ISSUE THREAD

**Issue by ManuelWaldmann** [jean-emmanuel/open-stage-control#87]
Hello,

Since V.19 my buttons are not transparent anymore.

I have a text it recive the osc message and over the text i have a button ro send a osc.
Its important that the button are transparent to see the text widget.
In Version 18.x i did it with "css" background:transparent. But this solution did not work anymore.
Was that changed?

Best
Manuel

**Comment by jean-emmanuel** [comment]
Hi,
The widget's structure has changed a bit, you'll have to add `.toggle {background:tranparent}` to your css to work around this. I'm fixing the code now to make your former solution valid again, as it's likely to be the expected behaviour. Thanks for your feedback !

**Comment by jean-emmanuel** [comment]
Fixed in v0.19.4
