### ISSUE TITLE
Fader Values

### ISSUE THREAD

**Issue by ManuelWaldmann** [jean-emmanuel/open-stage-control#88]
Hello

First of all THANKS for your great work. I am fan of your OSC Program.
I make a remote for my lightdesk Cobalt by ETC.

Now my question:
Is it possible to change the value i see by fader?

in my projekt i have a lot of fader. the osc command is /cobalt/master/1 for Fader 1, /cobalt/master/2 for Fader 2 etc. and the range is 0 to 1.
But i won't see 0.00 to1.00 but 0 to 100 because the fader control light intensity and the range of intensity is 0 to 100%.

Now i set the fader at 0.25 and the light intensity is 25%. i would be happy when i see 25 instead 0.25.
I hope you unterstand what i mean. Its not really a problem. but its looks better...

Best
Manuel

**Comment by jean-emmanuel** [comment]
Hi, thanks a lot for the kind word :)

Well, having an input that sends another value than the one it displays seems a bit wrong to me and I'd prefer not to implement that as a widget option. However you still have two ways to achieve what you describe:

- set your fader range to `{"min":0, "max":100}` and write a [custom module](http://osc.ammd.net/extras/custom-module/) to divide output values and divide input values.
- hide the fader's input and add a formula widget that multiply the fader's value by 100 (you won't be able to edit the value manually though). Adding a `%` symbol will be possible soon as I'm just added the `unit` option to the formula widget. See [formula_example.js.txt](https://github.com/jean-emmanuel/open-stage-control/files/1251374/formula_example.js.txt) for example.

**Comment by ManuelWaldmann** [comment]
Hi,

Thanks.
I understand your point of.

My skills are not good enough to write a custom module )-:
Your second idee is good, but i still see 0 to 1 when the pips are active. 

Thanks,
Manuel

**Comment by jean-emmanuel** [comment]
You can set custom pips label by setting fader's [range](http://osc.ammd.net/widgets/sliders/#range) as follows:

```
{
  "min": { "0%": 0 },
  "max": { "100%": 1 }
}
```

**Comment by ManuelWaldmann** [comment]
Thanks!!

That what I need.

Manuel
