### ISSUE TITLE
No MIDI ports found

### ISSUE THREAD

**Issue by danielappelt** [jean-emmanuel/open-stage-control#89]
One of the latest changes to midi.py seems to have broken the MIDI support on my system. Listing MIDI ports does only yield empty lists for ALSA and Jack, and creating a (virtual ALSA) MIDI port no longer works.

**Comment by jean-emmanuel** [comment]
Can you paste here the command you ran and check your rtmidi version ? MIDI seems to run fine here.

**Comment by danielappelt** [comment]
Nevermind! I updated my system and forgot to do a reboot. Everything is fine again :-)
