### ISSUE TITLE
Fader wish list

### ISSUE THREAD

**Issue by ovenwerks** [jean-emmanuel/open-stage-control#9]
1) No scale. I tried making it transparent, but the space used by the scale is still used. In other words the reason for removing the scale is for better real estate use.

2) The knob widget has a "pan" settings where centre shows no marker bar but left or right do. It would be nice to be able to do this with faders too. Round knobs look nice, but they take a lot of room and on a tablet there is not much room. So a fader is nicer to use. Perhaps a setting that only shows the value point and not the origin to value bar might serve better for this use being more generic. Maybe there is already a way of doing this with a CSS command.

3) I am not sure if this can be done... Using a db scale like a standard fader works really well with breakpoints. There is one exception. There is no way of putting an infinity mark at the bottom. I can live without this though. right now I do 1%= -150 (24bit limit-ish) minimum -1000, but of course the -150 and -1000 are on top of each other. I have copied the breakpoints from a P&G fader. Looks nice works really well with the DAW too. On second thought, I think -1000db is pretty obvious and the DAW shows -inf.

Note: sorry for using the same issue again. I was just using the email address.

**Comment by jean-emmanuel** [comment]
1) I think you are referring to the case where the fader is right or left-aligned, I see the problem, will fix.

2) I just removed the pan option actually since it was not rendering nicely. Still, you can hide the gauge (hence showing only the dot)  by adding `--color-gauge:transparent;` to the `css` property.

3) Allowing custom labels for breakpoints would solve this : 

```js
range: {
    min:["label",value],
    // ...
    max:["label",value]
}
```

**Comment by ovenwerks** [comment]
1) Actually, it would be top or bottom aligned, but that doesn't exist :) I am using horizontal faders. See:
[http://www.ovenwerks.net/paste/mixstrips3.png](url) for an example. Because the scale is between the marker and the value, I can't see the value. Not having the scale would allow the value to show. Or having the Value on top would work for me. Not sure what is best.

2) Perfect!

3) That would be great.

**Comment by jean-emmanuel** [comment]
I forgot about horizontal faders too ! Ok I add the option. 

Le 26.03.2016 16:08, Len a écrit : 

> 1) Actually, it would be top or bottom aligned, but that doesn't exist :) I am using horizontal faders. See:
> http://www.ovenwerks.net/paste/mixstrips3.png for an example. Because the scale is between the marker and the value, I can't see the value. Not having the scale would allow the value to show. Or having the Value on top would work for me. Not sure what is best. 
> 
> 2) Perfect! 
> 
> 3) That would be great. 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub [1]

  

Links:
------
[1]
https://github.com/jean-emmanuel/open-stage-control/issues/9#issuecomment-201852730

**Comment by jean-emmanuel** [comment]
3) done, breakpoints' values can be set as objects if a custom label is needed : 
```js
range: {
  min: {"-inf":0},
  // ...
  max: 1
}
```

**Comment by jean-emmanuel** [comment]
1) added `noPip` option to knob and fader
3) fader and knob scale system are the same now
