### ISSUE TITLE
No transparent border

### ISSUE THREAD

**Issue by ManuelWaldmann** [jean-emmanuel/open-stage-control#91]
Hey my friend,

I have a encoder and in the middle of that i have a button with the same color like the encoder.
But i see  a border. the same, when ich change the background of the button to transparent. The same with a text widget.
In version 18 it was possible to make the border also transparent.
is it in version 19 not possible?

Best
Manuel

**Comment by jean-emmanuel** [comment]
I'd set `css` as follows:

```css
border radius:100%; /* This would actually be enough for a toggle/button I think */
--color-border: transparent; /* hides the dark border */
--color-light: transparent; /* hides the inner light border */
```

These css variables a not well documented yet...

**Comment by ManuelWaldmann** [comment]
Thanks a lot.
It works.
