### ISSUE TITLE
No button text color

### ISSUE THREAD

**Issue by ManuelWaldmann** [jean-emmanuel/open-stage-control#92]
Hello again,

Iam sorry for the many questions...
Since V.19 the color of the button text is always the same. i cant change it anymore.
I think its easy but iam to stupid... maybe...

Best 
Manuel

**Comment by jean-emmanuel** [comment]
No problem !

What did you use before ? Setting css' `color:red` works fine to override default text color (unless it's using the blue accent color, in which case the `color` option is the way to go).

**Comment by ManuelWaldmann** [comment]
Ohh, i use --color-text:#FF6600 before.
Thanks, with color:red it works fine.

THANKS

**Comment by jean-emmanuel** [comment]
Hm, it's a little bug I introduced though, I'm fixing it so that both work except `color:red` applies locally and `--color-text` applies to children too
