### ISSUE TITLE
Combining multiple values with /EDIT

### ISSUE THREAD

**Issue by ManuelWaldmann** [jean-emmanuel/open-stage-control#93]
Hello,

I use two dropdown widgets.

the first is for the background:
```json
{
  "Black": "{ \"css\": \"--color-bg:black\" }",
  "Orange": "{ \"css\": \"--color-bg:orange\" }",
  "Grey": "{ \"css\": \"--color-bg:grey\" }",
  "Red": "{ \"css\": \"--color-bg:red\" }",
  "White": "{ \"css\": \"--color-bg:white\" }"
}
```

the second is for the text color:
```json
{
  "Black": "{ \"css\": \"color:black\" }",
  "Orange": "{ \"css\": \"color:orange\" }",
  "Dark Grey": "{ \"css\": \"color:grey\" }",
  "Grey": "{ \"css\": \"color:#ACB2BB\" }",
  "White": "{ \"css\": \"color:white\" }"
}
```

Both of the dropdowns works fine, but not together.
The one replace the other. Its possible to add instead to replace??

Best
Manuel

**Comment by jean-emmanuel** [comment]
Using the `/EDIT_SOFT` command, you can merge object properties in a non destructive way but this doesn't work with string properties such as `css`. Here's how I'd do (it's a bit tricky !):

1. Set the widget's `variables` property (or it's parent's) to 
```json
{
  "bg-color": "DEFAULT_BG",
  "color": "DEFAULT_COLOR"
}
```

2. Set the widget's `css` to (replace `this` with `parent` if the `variable` property is held by the parent widget)
```css
--color-bg:@{this.variables.bg-color};
color:@{this.variables.color};
```

3. Set the dropdowns' props as follows
- `address` to `/EDIT_SOFT`
- `preArgs` to `["id"]` where `id` targets the widgets that holds the `variables` property
- `values` to

```js
{
  "Black": "{ \"variables\": \"{\"color-bg\":\"black\" }}",
  // etc
}
```

and 

```js
{
  "Black": "{ \"variables\": \"{\"color\":\"black\" }}",
  // etc
}
```

**Comment by ManuelWaldmann** [comment]
Hi.
Thanks. I think i keep it simple and use the "normal" way without merge multiple values. :-)
But is it possible to change the background color for all buttons?
I try:
{
  "Black": "{ \"css\": \"background:black\" }"
}
But its doesen't work.

**Comment by jean-emmanuel** [comment]
You can edit the parent container and target multiple children at once by setting its `css` to
```css
.toggle-container, push-container {background:black};
```

**Comment by ManuelWaldmann** [comment]
Thanks my friend.
