### ISSUE TITLE
keyboard widget stuck notes

### ISSUE THREAD

**Issue by circuitb** [jean-emmanuel/open-stage-control#94]
hello,
great tool, bravo!!
just discovered  playing the keyboard with fingers on a surface pro 4 
some notes (on) gets stucks with a velocity = 1 
especially when playing fast or in a polyphonic/multi touch mode!
perhaps a flush function can be cool to avoid stuck noteS? 

ps: adding the pressure data of the tablet's pen could be nice
for example an option on the XY pad widget!?

**Comment by jean-emmanuel** [comment]
This should be fixed in the online demo and next release (see commit above).

> ps: adding the pressure data of the tablet's pen could be nice
for example an option on the XY pad widget!?

Let's put a pin on that !

**Comment by circuitb** [comment]
thanks!
